### ISSUE TITLE
Duplicate frames appearing in sliced clips on timeline

### ISSUE THREAD

**Issue by mlcoley** [OpenShot/openshot-qt#1015]
**System Details:**
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.0
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
In the course of investigating the cause of a jittery playback, both in preview and in the exported MP4 file, I've noticed that there are duplicate frames here and there throughout clips that I've dropped into the timeline and then sliced down to the section I want. Two versions of the problem:

1) 4-5 frames inserted at the beginning of the sliced clip that appear to be duplicates of the clip's last frame, causing the appearance of a jarring and unclean transition from the previous clip in the timeline
2) 2-3 frames inserted randomly within a clip that appear to be duplicates of the immediate previous frame, causing the appearance of a lag when played back slowly or a jitter when played back at normal speed

I've checked the original clips and they play back normally with no lag or jitter. When I open a new project in Openshot and reproduce my own steps of inserting these clips into the timeline and slicing, there is also no occurrence of duplicate frames. It seems the issue is happening within Openshot, after dropping the clips into the timeline and perhaps sometime during the course of working on other editing in the project. 

I am working with MP4 files from GoPro Hero 5 Black and Hero 5 Session cameras, shot at 1080p 60fps and 1080p 30fps respectively. The project profile is set to 1080p 30fps.

**Comment by DylanC** [comment]
@mlcoley - Same result in v2.4.1?

**Comment by johanch** [comment]
Hi there,

I am now facing the exact same issue with v2.4.4.
Transitions between sliced clips look good in the Openshot preview but after exporting the video, duplicated frames appear.

Is there any workaround for this issue?
Thanks and regards,
Johan

**Comment by ferdnyc** [comment]
@johanch 

This issue was originally reported against OpenShot 2.4.0. The slice code was modified in 2.4.2 (I think? Or 2.4.3.) to address this issue. 

So, if you're seeing problems in 2.4.4, it's unlikely to be the _same_ problem, but rather a new one. Please file a [new issue](https://github.com/OpenShot/openshot-qt/issues/new/choose) using the Bug Report template, and provide the requested details.

**Comment by johanch** [comment]
Thanks for your answer.
I figured out that the issue appeared only for a few profiles, not all of them...

**Comment by ferdnyc** [comment]
@johanch Interesting — the profiles have a wide range of frame rates, did you get any sense that it was related to that? 

Typically, working at a different frame rate than the source video is going to make things like Slicing less reliable, since the splice points for the clips may no longer match up with frame boundaries in the source. (Splicing, like any other Timeline operation in OpenShot, always uses the selected profile (output) frame rate.)
