### ISSUE TITLE
Automatically created transitions don't adjust with moving clip

### ISSUE THREAD

**Issue by Bugsbane** [OpenShot/openshot-qt#103]
If I put two clips so that they're overlapping, OpenShot automatically creates a fade transition between the two of them which is perfect. The only problem is that if I then go and move either clip, the transition doesn't adjust, as it does in other editors such as Vegas, which often leaves it fading between the wrong in and out points.

I would suggest that if a transition was automatically created and has not been manually adjusted that it should automatically adjust to cover the period where the two clips overlap, when either or both clips are moved.

**Comment by BF3000** [comment]
I agree with that.
Transition logic need an improvement.

**Comment by jonoomph** [comment]
What if multiple clips are overlapped in a large chain... should all chained clips be moved together by default? Maybe when you click a clip that overlaps other items, it should just select all of them by default, which would then move them together. I just need to play around with that logic a bit more.

**Comment by BF3000** [comment]
You need to try Magix (ex Sony) Vegas.
That the transition logic I like.
https://www.youtube.com/watch?v=KzCvd-Lphrc

**Comment by yoyoyvr** [comment]
As of March 2023 this is still an issue. For example, if I have clips with transitions created by overlapping the clips, then I select all and move everything on the entire timeline, the transitions get messed up.

**Comment by Colorjet3** [comment]
Hello @yoyoyvr.  I just tried this with two image clips (.jpg).  I overlapped the two, which then a Fade in transition was automatically added to the 2nd clip.  I played it and it was all good.  I then select all 3 objects (the two clips and the transition) and move all 3 to the right on the same track (from the 0:00 to the 00:00:32 marker).  Played it an it was all good.

I then moved all three to another track and back to 0:00 marker.  No issues with the transition.

My specs:
1.  Windows 10 Pro with the latest updates.
2.  Openshot v3.0.0-daily-11058-....   If you are running v3.0.0-Release-Candidate-... then I would upgrade to the latest DEV daily build.
3.  I used two .jpg files and overlapped as indicated above.

If you don't mind, and so that we can get to the bottom of this issue, please provide the following:
1.  What version of Openshot are you running?
2.  What operating system/version are your running (Widnows 11 Pro? Ubuntu 22.04 LTS?, etc?)
3.  what type of image files are you working with (.jpg? .svg? .mp4? .mov? etc.?)
4.  Does this happen with other Transitions that are in Openshot?
5.  Please provide me with step-by-step of what you are doing so I can try and replicate exactly how you are doing it?

If you are not running the latest DEV Daily Build, please download it, install it, and test with it as well.
1.  Go to openshot.org/download/#daily and get the latest DEV daily build (Windows or AppImage).
2.  Close Openshot if running.
3.  Backup c:\users\username\.openshot_qt folder or /home/username/.openshot_qt folder (windows / linux respectively).
4.  Delete the appropriate ...\.openshot_qt folder.
5.  Install Openshot (Windows) or just run the AppImage (Linux).
6.  Test again.

Let me know the results and we can continue to troubleshoot if needed.

Thank you in advance!
