### ISSUE TITLE
Keyframes do not remain in the same place when exporting to a different fps that they were placed in.

### ISSUE THREAD

**Issue by ChemicalXandco** [OpenShot/openshot-qt#1034]
**System Details:**
https://uk.pcpartpicker.com/b/nn7WGX
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.0
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
Set video profile to any resolution lets say HD 720p 30 fps
Put in any keyframe, say 9 seconds into scale the video from 1.0 to 0.5
Export the video to any resolution, but different fps: HD 1080p 60 fps 
Play the exported video in windows media player or whatever, the video will stop shrinking at 4.5 seconds and not nine seconds.

This issue is obviously because if you place a keyframe at 1 second, the software says it will happen 30 frames in. When it goes to 60 frames per second, it still thinks it should happen 30 frames in. This equates to half a second so it happens earlier then it should. I think this theory is correct.

It could be fixed by emulating a different set of keyframes so if it was from 30 to 60, it would be multiplied by 2.

If anyone is wondering why I don't just edit in the same profile as I export, it's because by halving the fps, I am halving the amount of work my computer has to do when viewing the video before exporting.

Please fix this as it is really annoying but I love openshot anyway. Keep up the good work!

**Comment by N3WWN** [comment]
I've noticed this when changing the profile mid-project, too.  If I start the project at 60 fps, then realize I'm using all 30 fps video and 60 fps doesn't make sense, and I change the profile to 30 fps, the keyframes shift by the amount of the profile change.

To replicate (which is basically what @ChemicalXandco is doing when he exports at a different framerate):

- New project with profile of "HD 1080p 60 fps" (my default profile)
- Import a video at least 20s long
I used this 25.14s long video: https://videos.pexels.com/videos/aerial-shot-of-mountain-and-ocean-1469
- Move the play head to 10s (well, 10.01s since 10.00s isn't possible)
- Adjust Scale X property to 0.50
- Note that green keyframe marker is at the playhead position
- Change profile to "HD 1080p 30 fps"
- Note that the green keyframe marker has moved to 20.01s

**Comment by peanutbutterandcrackers** [comment]
Just a relevant info here: Work is under progress to fix this issue [here](https://github.com/OpenShot/libopenshot/tree/experimental/auto-convert-keyframes). Hope that helps! :)

**Comment by DylanC** [comment]
Dup of #519

**Comment by ferdnyc** [comment]
Closing as dup of (fixed) #519
