### ISSUE TITLE
Crash Bug When exporting

### ISSUE THREAD

**Issue by FlyGames** [OpenShot/openshot-qt#1043]
**System Details:HP Probook 4530s **
* Operating System / Distro: Windows 7 64 ?
* OpenShot Version:2.4.1 ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
Exporting video with the Target AVI(h.264) causes the program to crash.

**Comment by exit151** [comment]
I am having this problem too. (crashing on export).
In my case it works fine if I go from HD source material to lower (mpeg-2, 1920x1080, 29.97 to mp4 720p), but when I do this the audio loses it's sync.  So my plan was to take my same source settings, and export it with the cuts made to the same source so I can use handbrake which took my source material just fine without causing an audio sync issue.  Problem is, every time I tell OS to export at HD 1080p (1920x1080) 29.97 it immediately crashes on job start.  Attached is my debug output.
[OpenShotCrashLog.txt](https://github.com/OpenShot/openshot-qt/files/1497774/OpenShotCrashLog.txt)

What I'm doing is opening recorded TV footage, editing it (removing commercials) and exporting it back to a mpeg2 format.  It *IS* coming into OS as a .ts file but I didn't see that as an option for export, nor do I think that would matter. for target I do select MPEG2, but I think the log shows that because every button I click I see the web debug whirring notations :)
