### ISSUE TITLE
'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by rmwebber** [OpenShot/openshot-qt#1051]
**System Details:**
* Operating System / Distro: Windows 7 x64
* OpenShot Version: 2.4.x
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

2.4.0 crashed during work on a project. Now I get a dialog every time I open the project: "'NoneType' object has no attribute 'get' ". An OK in the dialog makes it go away until the next time I load the project. Upgrade to 2.4.1 did not resolve the issue.

**Comment by DylanC** [comment]
@rmwebber 

Maybe try some other projects and let us know if its just a problem with that one.

**Comment by rmwebber** [comment]
I have solved my problem by no longer using OpenShot. I've spent weeks of wasted time putting a project badly behind schedule and now must waste more time teaching myself a new interface in a tool that is closed source but works and has effective support.

**Comment by DylanC** [comment]
@rmwebber - No problem. Thanks.

**Comment by Mystic-Mirage** [comment]
I have the same issue after crash with one of my projects.

**Comment by peanutbutterandcrackers** [comment]
@Mystic-Mirage - This is probably an issue of the history stack being corrupted. Could you please run the script as outlined inthe README.md here: https://github.com/peanutbutterandcrackers/meet-tux It is a sed script that removes the history stack from the project file. If it works for you, please do follow up so that we can work on fixing this issue. Thanks!

**Comment by Mystic-Mirage** [comment]
@peanutbutterandcrackers Thank you, but it didn't help.
Here are all 'null' values in my project that I think can cause the error
```
$ python -m json.tool my_project.osp | grep null
    "0": null,
    "1": null,
    "10": null,
    "11": null,
    "13": null,
    "2": null,
    "3": null,
    "6": null,
    "7": null,
    "8": null,
    "9": null,
    "history": null,
```

**Comment by peanutbutterandcrackers** [comment]
@ferdnyc - Sorry to bother you, sir, but could you please take a quick look at this? Thank you.

**Comment by ferdnyc** [comment]
Look at... what? I'm going to need to see at least the project file in question. I'd be happy to look at _that_...

**Comment by ferdnyc** [comment]
Regarding this, specifically:

> ```
> $ python -m json.tool my_project.osp | grep null
>     "0": null,
>     "1": null,
>     "10": null,
>     "11": null,
>     "13": null,
>     "2": null,
>     "3": null,
>     "6": null,
>     "7": null,
>     "8": null,
>     "9": null,
>     "history": null,
> ```

Null values _in and of themselves_ are not a problem in `.osp` files — in fact, they are normal and **expected** in at least the undo/redo lists. Some history items inherently don't have a "previous state", and that condition is represented with the `"old_values"` key being set to `null`. So, finding null entries shouldn't be considered a sign of a problem by any means, it's all about _where_ they're found.

What's **more** concerning to me is the fact that your project file apparently has keys with labels like `"0"`, `"1"`, `"2"`, etc. I can't really **think** of _any_ place where keys should be named with numeric labels — that doesn't make sense, you'd use a `[ list, of, values ]` for something like that. So, it's surprising to me that keys like that would be showing up, no matter what their value! 

I also don't seem to have any such keys in any of the `.osp` files I've checked so far, both my own and ones other users have submitted with bug reports. The only time the strings `"0"`, `"1"`, shows up in any of these project files is in the value of the `"minor_version"` key.

Now, I could be wrong that numerical-label keys aren't normal in `.osp` files, there might be some use for  them that I'm not remembering or have never encountered. (Though I would argue that, if they _are_ a normal part of OpenShot's JSON data in some instances, it's still the **wrong** way to store the information, and that dictionary should be changed to a list.)

Regardless, point is: I'm _really_ going to need to see that project file.

**Comment by ferdnyc** [comment]
Aha, of course right after posting that I found a project file with a `"2" : null` in it — but it's in the project data I recovered from #1768, which was also causing loading / functionality issues in OpenShot. (And we never got word back from the original reporter on whether the attempts at recovery were successful.)

So, that project file has a key with the label `"2"` (and value `null`, but that's probably irrelevant) just sitting at the top level of the project dictionary, for **no** obvious reason. Which means now we have to figure out where _that_ came from, or what can happen to cause keys like that to be created where they **SHOULDN'T** be created.

The JSON handling is really falling apart suddenly, seems like. I'm still willing to blame the inclusion of history data, and consequent excessively-large JSON datasets that result. #2400 can't get merged fast enough.

**Comment by maximumhax** [comment]
I'm not 100% positive, but I just had this happen to one of my saves. When the project loads, it all looks fine, if I try to play the video footage, openshot segfaults. I have fixed the segfaults, by clicking on each video and going to properties and clicking update, also went through and made a few changes to the timeline, saved it, put them back, saved it, and now I'm able to play the footage, but I still get this error when opening the project. Now, as far as what caused this error on my project file (at least I think) is that I renamed the directory the video files were stored in. /home/user/path/to/video/file/0001.MTS + /home/user/path/to/video/file-a/000045.MTS was my structure, in this example I renamed /home/user/path/to/video to /home/user/path/to/videos-and-photos/file/0001.MTS etc... so at first I had a bunch of errors about finding video.. at first I started giving each video new paths, which was taking forever as there were multiple directories deep, not all videos were in same dir, so after running through most, I then ran a simple script to change text /video/ to /videos-and-photo/ which I think somewhat screwed things up as I think the very first video you load in a project is set to the "path" and then every video you load after that is based off of that path but when i started telling openshot where each video was I think made those changes example ../../../some other video youll see as a path instead of the full path /home/user/path/to/video 

Anyway, I'm done rambling.. basically my project file worked fine, until I renamed a directory, then had to tell openshot where each one was, and then made a script do it for me.. 

I was at first so ticked that I just didn't killall -9 so it didn't update the save and just rename my main directory back until I finished that project. but after I started telling openshot where they were, it was already too late :( 

Hope this little bit of information will help others or atleast devs figure something out to fix the issue.

**Comment by ferdnyc** [comment]
@maximumhax 

Yeah, due to design decisions made by the OpenShot developers, you really can't move any project files without breaking everything. But they want it that way.

**Comment by ThomasBerends** [comment]
@DylanC 
I have the same issue as this one now. It seems some weird stuff happened to the save file. 'history' is null, and some seemingly random numbers were added. I'm not sure what happened, but here is the save file (I cannot provide my recordings unfortunately).

I would love to hear how I can fix this file, unfortunately, I can't reproduce the bug again so far.
[RPM01 - kopie.zip](https://github.com/OpenShot/openshot-qt/files/3139542/RPM01.-.kopie.zip)

**Comment by jonoomph** [comment]
I would love to add this fix directly into OpenShot (for cases of corrupted history)

**Comment by ferdnyc** [comment]
@jonoomph This wasn't corrupted history, though.The `null` history is actually OK, the issue was the insertion of these values at the top level of the JSON structure, right at the end of the file...
```json
{
    "1": null,
    "13": null,
    "19": null,
    "6": null
}
```

Which is something we've seen before. No idea where it's coming from. (...Not that OpenShot's `project_data` class couldn't be made tolerant of unrecognized top-level keys, of course. But the corruption is at the project-file level, not the history... somehow.)

**Comment by ferdnyc** [comment]
@ThomasBerends 

A copy of any `C:\Users\Thomas\.openshot_qt\openshot-qt.log*` files containing the session that resulted in that file would be _really_ helpful, if at all possible. It doesn't have to have been in debug mode, timeline-data changes are pretty well traced with just the regular logging.

**Comment by jonoomph** [comment]
I'm working on a fix now, thx!

**Comment by jonoomph** [comment]
The **null** history attribute does break saving and loading history though, and although most other things are still functional, it permanently breaks history for that specific project file. It's an easy fix for that, but not sure about the strange numbers.

**Comment by ferdnyc** [comment]
> The **null** history attribute does break saving and loading history though,

Aha, that's good to know. Yeah, I usually replace it with `history: {},` when I find that. (The `undo` and `redo` keys, it _seems_ to be able to fill back in on its own. Though I should probably test that assumption more concretely.)

**Comment by jonoomph** [comment]
Adding those #'s to my test project does not break anything though (this is after my fix though).

**Comment by jonoomph** [comment]
Okay, making a PR: https://github.com/OpenShot/openshot-qt/pull/2764

**Comment by ThomasBerends** [comment]
@ferdnyc 

[openshot-logs.zip](https://github.com/OpenShot/openshot-qt/files/3139963/openshot-logs.zip)

Here are the 4 logfiles I have in that spot. Based on the times I'm gonna guess *.1 contains the moment it broke my file.

On a sidenote, thanks for this quick response. It's really encouraging to know there's a team working on making OpenShot better. It's an awesome editor to work with, and this is the first big issue I've encountered.

**Comment by jonoomph** [comment]
Always glad to help! Merged into `develop`. A new daily build should be available in the next 60 minutes (or so), accessible from  https://www.openshot.org/download/#daily

**Comment by jonoomph** [comment]
I've actually be emailed about this specific issue many times in the past few days, and it feels good to have a fix for everyone.

**Comment by ThomasBerends** [comment]
Okay. I'll check if I can install the daily build on my windows machine tomorrow, if so, I'll test it the corrupted file works again.

**Comment by ferdnyc** [comment]
Hm. This is interesting... (probably not _useful_, but interesting):
```console
$ for file in openshot-qt.log*; do \
$ wc -l $file; echo "$(grep -i save $file|wc -l) (auto)saves\n"; done
7064 openshot-qt.log
40 (auto)saves

17735 openshot-qt.log.1
11 (auto)saves

16199 openshot-qt.log.2
37 (auto)saves

17709 openshot-qt.log.3
89 (auto)saves
```

So if the corruption was introduced in `log.1`, it came during a time of highest activity level, with either a lot of edits occurring very quickly, or very _large_ edits (logging the highest number of lines for each action) — which makes sense, as the history had probably grown especially lengthy, with particularly large entries.

Just need to write a few quick scripts to tease out the logged JSON data and reformat it, that might help me get a better picture.

**Comment by ferdnyc** [comment]
@jonoomph 

In the `openshot-qt.log` file that @ThomasBerends posted:
```
openshot-qt.log:     updates:ERROR Couldn't apply 'update' to update listener: 
<classes.project_data.ProjectDataStore object at 0x000000000f9860b8>
openshot-qt.log-'NoneType' object has no attribute 'update'
openshot-qt.log- main_window:INFO updateStatusChanged
openshot-qt.log-project_data:INFO Saving project file: D:/OpenShot/RPM01.osp
```

Appears three times.

Here's the content of the update that was logged right before one of them, converted from Python to JSON and somewhat-exploded enough to make the Atom editor's folding and JSON validation happy. It _appears_ valid, though it is a full 20 history entries and _quite_ long.

[failed-update.formatted.json.txt](https://github.com/OpenShot/openshot-qt/files/3140255/failed-update.formatted.json.txt)

**Comment by jonoomph** [comment]
Those errors are caused by having a null "history" attribute. I was receiving those errors each time I attempted to "save" over the  null attribute in my tests. So by simply fixing the null attribute when a project is opened, it should avoid all this mess (in theory).

**Comment by JustaKing4** [comment]
not sure if this is effecting my exported video causing the audio to be out of sync but i am getting this error on launch as well.....

**Comment by ferdnyc** [comment]
@JustaKing4 

Sync issues, highly unlikely that it's _directly_ related. However, since this bug was reported almost two years ago against OpenShot 2.4.0/2.4.1, you should file a [new issue](https://github.com/OpenShot/openshot-qt/issues/new/choose) using the Bug Report template, and fill in the details of what system you're running on, what version of OpenShot, etc.

**Comment by ferdnyc** [comment]
(...And I see, now, that you'd done that the day before your comment here, so never mind!) 😁

**Comment by Foadsf** [comment]
I'm getting the same issue on 

- OpenShot 2.4.4
- Windows 1809 (OS build 17763.720)

I get the error message of 

> 'NoneType' object has no attribute 'get'


![OS](https://user-images.githubusercontent.com/12762442/64528667-596d1c00-d309-11e9-8c58-be8fb79a897d.PNG)

it opens the file but doesn't show the imported media in the "Project Files" area. This is after I silve the [other isssue](https://github.com/OpenShot/openshot-qt/issues/840#issuecomment-526850926) by manually deleting the "thumbnales" folder. 

This is has been reported also [here](https://github.com/OpenShot/openshot-qt/issues/2071), [here ](https://github.com/OpenShot/openshot-qt/issues/1748)and [here](https://www.reddit.com/r/OpenShot/comments/ba5jxl/osp_file_not_opening_project/).

**Comment by ssww888** [comment]
> 
> 
> **System Details:**
> 
>     * Operating System / Distro: Windows 7 x64
> 
>     * OpenShot Version: 2.4.x
> 
>     * _Please attach log files if crash_
> 
> 
> **Issue Description and steps to reproduce:**
> 
> 2.4.0 crashed during work on a project. Now I get a dialog every time I open the project: "'NoneType' object has no attribute 'get' ". An OK in the dialog makes it go away until the next time I load the project. Upgrade to 2.4.1 did not resolve the issue.

This worked for me:
1. Look for the line containing 
   `"history": null,`
quite at the end of the osp-file
2. remove this line completely
3. reopen the osp-file.
Finished :-)
