### ISSUE TITLE
Making voice louder from interview

### ISSUE THREAD

**Issue by anbleyth** [OpenShot/openshot-qt#1059]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by anbleyth** [comment]
Hi, 
I have an interview where my voice is much louder than the interviewee because I used a GoPro. Any ideas how to make it louder? It is also known as an MP4 IVX

**Comment by N3WWN** [comment]
I don't think there is any way to do this within OpenShot, but you could look at using ffmpeg on the command line.

Here are two examples that I've used to improve audio.

The first reduces loud sounds, minimizes background noise and improves spoken audio that varies in volume due to position and orientation of the speaker:

`ffmpeg -i GOPR0165.mp4 -af "compand=0:0.2:-90/-900 -70/-70 -30/-30 -25/-20 -20/-12 0/-12:0.01:18:-45:0" -c:v copy -c:a aac -strict -2 GOPR0165_comp.mp4`

This next one uses a highpass and lowpass to effectively create a bandpass filter (which I could have also used) to reduce wind noise (frequencies below 100Hz and above 4kHz are attenuated):

`ffmpeg -i GOPR0165_comp.mp4 -af "highpass=f=100, lowpass=f=4000" -c:v copy GOPR0165_comp_bandpass.mp4`

You can find out more about the compand and high/low pass filters [here](https://ffmpeg.org/ffmpeg-filters.html#compand), [here](https://ffmpeg.org/ffmpeg-filters.html#highpass) and [here](https://ffmpeg.org/ffmpeg-filters.html#lowpass).

**Comment by anbleyth** [comment]
Thanks for that - I will try ffmpeg. I am not experienced with coding so I may have to ask for more details later on!

**Comment by DylanC** [comment]
@anbleyth - I would go with that suggestion by N3WWN.
