### ISSUE TITLE
Profile selections not being remembered

### ISSUE THREAD

**Issue by jarid1** [OpenShot/openshot-qt#1070]
Release Linux Mint 17.3 Rosa 64-bit
Open Shot 2.4.1-dev1
![image](https://user-images.githubusercontent.com/33955427/33233302-2dc68502-d214-11e7-859d-326d23f9b65b.png)
![image](https://user-images.githubusercontent.com/33955427/33233312-9415124c-d214-11e7-88e7-6f846a80a705.png)
This mistake appears after actualization. Before was booth parameters the same. I mean parameters of default export profile (1080p, mp4, 30fps) and real parameters after pressing export button.

**Comment by DylanC** [comment]
@jarid1 - So you are saying the params set didn't match up and they should?

**Comment by jarid1** [comment]
My typical workflow with 10 years old PC is presnip, making of 8 s exported sequences and after that export of digested sequences of project to video. And making of 10 presnipps means selecting 3x10 parameters of export, because its not possible set default profile. In version 2.4.1. is default profile of each export first profile from list of profiles. Previous version 2.4.0 had not this mistake.

**Comment by jarid1** [comment]
There is some possibilities, how I can solve this problem: Reinstall to version 2.4.0. was unsuccsessful, because there is huge of versions 2.4.0 on websites as appimages and I dont know, which version is right. Second possibility for me is setting of default profile as custom profile : http://cs_cz.utf-8.openshot.org/files/user-guide/?app-menu. But I am not a linux programmer and I cannot find /.openshot_qt/profiles/ directory. Third possibility is to buy a new PC and change my typical workflow. Any other ideas? Some button "set this profile as default" or ...?

**Comment by DylanC** [comment]
@jarid1 - I can check with the devs if we changed something in relation to the profile selection. That is the best I can do for now on the issue.

**Comment by ferdnyc** [comment]
An old issue, I realize, but I _believe_ this was simply a miscommunication. @jarid1 was looking at the Default Profile setting in the Preferences, which sets the default for **new** projects.

Each project file, though, has its _own_ profile (by default, the one selected in Preferences), which will be used as the default settings for the Export window.

To change an existing project's profile, you can either use File > Change Profile...

![image](https://user-images.githubusercontent.com/538020/61956716-b1cfa080-af8b-11e9-8e7a-d4e676024d3d.png)

Or the toolbar button, either of which will bring up a profile selection dialog. The project's currently-selected profile is shown in the titlebar of the OpenShot window, next to the project name, as a reminder.

![image](https://user-images.githubusercontent.com/538020/61956790-d9bf0400-af8b-11e9-9d60-16e3beb0ff97.png)

I'm going to close this as hopefully-answered, since it was filed under an old version of OpenShot. If there are problems not addressed here that still occur with OpenShot 2.4.4, they should be filed as new Issues.
