### ISSUE TITLE
retro filter for video

### ISSUE THREAD

**Issue by Joseph65** [OpenShot/openshot-qt#1079]
Would be nice to have retro color filters like lomo, holiday, bloom, etc.
something like instagram filters for video.

**Comment by peanutbutterandcrackers** [comment]
Currently, Mr. Thomas, the lead (and turns out sole - for now, at least) developer is porting effects from OpenShot 1.x to Openshot 2.x. He has finished 'Hue', 'Shift', 'Bar' among others. So, yeah. Also, according to this [blog post](http://www.openshotvideo.com/2018/01/happy-new-year-2018.html?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+OpenshotVideoEditor+%28OpenShot+Video+Editor%29), he will be working on "an easy plug-in framework to allow others to quickly create video and audio effects" too. So, yeah. It's going to be an exciting year for OpenShot development. :)

**Comment by DylanC** [comment]
@Joseph65 - Would be great indeed. More effects are being added at the moment. I can make a suggestion of these too for you.
