### ISSUE TITLE
Tutorial popups have nomal window type

### ISSUE THREAD

**Issue by Zuccace** [OpenShot/openshot-qt#1080]
* Gentoo Linux + i3wm
* OpenShot Version: 2.4.0

**Tutorial popups have nomal window type --> i3 tiles them**

The tutorial popups have wrong window type sent to X server. 

```
$ xprop 
I3_FLOATING_WINDOW(CARDINAL) = 1
_NET_WM_USER_TIME(CARDINAL) = 272836524
_NET_WM_STATE(ATOM) = 
_NET_WM_DESKTOP(CARDINAL) = 6
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_ICON_NAME(UTF8_STRING) = 
XdndAware(ATOM) = BITMAP
WM_NAME(STRING) = "Tutorial"
_NET_WM_NAME(UTF8_STRING) = "Tutorial"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x1, 0x0, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _KDE_NET_WM_WINDOW_TYPE_OVERRIDE, _NET_WM_WINDOW_TYPE_NORMAL
_XEMBED_INFO(_XEMBED_INFO) = 0x0, 0x1
WM_CLIENT_LEADER(WINDOW): window id # 0x2400007
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
_NET_WM_PID(CARDINAL) = 13451
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 37748748
WM_CLASS(STRING) = "openshot-qt", "openshot"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		user specified location: 2340, 206
		user specified size: 1918 by 1162
		program specified minimum size: 350 by 100
		window gravity: Static 
```

Please note that I'm not sure if this fault of some qt component or PyQt5. It might be But I decided to raise an issue here so that at least we know this bug exists and maybe there's a way to solve it in this project.

Also the tutorial popup window buttons _rarely_ take click input. I need to tap my mouse, should I say, in rapid fire mode to make them take input. But that issue seems to already been reported.

**Comment by DylanC** [comment]
@Zuccace - Pretty sure its just a small tweak required. Qt has window modes such as "normal" in this case. It should probably be set to be a modal/dialog of the parent window.

**Comment by Zuccace** [comment]
Thanks for the reply.
The severity of this isn't really high, but I'd guess every linux user with tiling wm may bump into this, and only once when going trough the tutorial.

I could circumwent this by telling i3 to recognize those tutorial windows and make them float. But that's not the "correct" way. ;)

**Comment by DylanC** [comment]
@Zuccace - Yeah I wouldn't say its super high priority but its good to keep track of it all the same.  This will be fixed eventually but I think it may be when the issue count gets really low. (if possible)

**Comment by peanutbutterandcrackers** [comment]
@ferdnyc - Perhaps you'd like to take a look at this? o.O

**Comment by ferdnyc** [comment]
> The tutorial popups have wrong window type sent to X server.

Mmm, Qt5 doesn't expose the raw window manager hints (Qt4 had a mechanism for getting at them, but Qt5 has subsumed all of that into its own class hierarchy), but the windows are currently being created as normal frameless windows with a translucent background...
```py3
        self.setWindowFlags(Qt.Window | Qt.FramelessWindowHint)
        self.setAttribute(Qt.WA_TranslucentBackground, True)
```
That's... probably not right, as @DylanC says some other type may be more correct. I'm not sure about straight _dialog_ per se, because then Gnome Shell is likely to attach it to the main window, so that'll break things there. There's got to be some combination of flags/hints that will communicate the right things to all of the various WMs, though.

> Also the tutorial popup window buttons rarely take click input. I need to tap my mouse, should I say, in rapid fire mode to make them take input. But that issue seems to already been reported.

**_Hmmmmm._** I wonder if that could be related to the fact that the window is next set unfocusable (well, actually _kept_ unfocusable, as `NoFocus` is the default), after which an event handler is installed that looks specifically for a WindowActivate event.

```py3
        self.setFocusPolicy(Qt.NoFocus)

        # Install event filter
        self.installEventFilter(self)

    def eventFilter(self, object, e):
        if e.type() == QEvent.WindowActivate:
            # Raise parent window, and then this tutorial
            get_app().window.showNormal()
            get_app().window.raise_()
            self.raise_()

        return False
```

The widget focus policy is documented as controlling _keyboard_ focus, so in theory a widget that doesn't need to accept keyboard input should not accept focus. But at the same time, [the documentation for isActiveWindow](http://doc.qt.io/qt-5/qwidget.html#isActiveWindow-prop) and [QApplication::activeWindow()](http://doc.qt.io/qt-5/qapplication.html#activeWindow) make it clear that the active window is "the application top-level window that has the keyboard input focus". So it's possible that some window managers take that literally, and will refuse to send activate events to a window that's in turn refusing to accept focus. The focus policy may need to be at least [Qt::ClickFocus](http://doc.qt.io/qt-5/qt.html#FocusPolicy-enum).

**Comment by ferdnyc** [comment]
Aha! This:
```py3
            get_app().window.showNormal()
```
from the event handler also explains #1036 / #1447 about the tutorial popups unmaximizing OpenShot, since `showNormal()` — as opposed to `showFullScreen()`, `showMaximized()`, or `showMinimized()` — specifically requests that the window be shown in a normal, floating, decorated state. That should probably just be `get_app().window.show()` to respect the existing window state regarding fullscreen/maximization.

**Comment by peanutbutterandcrackers** [comment]
Hey there! Could you all please try [this build](https://drive.google.com/open?id=1n5_joUIWr4FI7daLaCj7WwFUk-sXsVKN) that incorporates the changes from the PR by @ferdnyc? This issue has, hopefully, been resolved. And if you give confirm it as resolved, we can go ahead and merge the changes into the main source. Thanks!

**Comment by peanutbutterandcrackers** [comment]
The following are the beta-builds that contain the changes made to resolve this issue (PR #1726 by the awesome @ferdnyc). Please try them out and report whether this resolves the issue. Thanks!
1. [Windows Builds](https://drive.google.com/open?id=1n5_joUIWr4FI7daLaCj7WwFUk-sXsVKN)
2. [Mac Builds](https://drive.google.com/open?id=10zy1SQz6gGCxfmYZtMnTYHkC5NBQy6Oz)
3. [Linux Builds](https://drive.google.com/open?id=10D6BIF_n8krpYB-goNQ7jj4W33OSv4Yg)
