### ISSUE TITLE
Upload to phone no audio

### ISSUE THREAD

**Issue by SweetLem0ns** [OpenShot/openshot-qt#1085]
#I was using openshot to edit my Videos, but when I Transfer the video to my phone {Via, sendanywhere} the video didn't have any sound
(I have an Iphone 5}
 ##

**Comment by peanutbutterandcrackers** [comment]
@SweetLem0ns - I see. That is a very simple issue to fix. The next time you try to export a video, instead of trying to export, select the 'Target' to be 'OGG (theora/vorbis)'. Like so:
![screenshot from 2018-02-12 07 20 43](https://user-images.githubusercontent.com/26764547/36081321-4f719658-0fc5-11e8-9e0c-970713f83df4.png)
The reason why the sound is not playing on your phone is because the audio encoder used by default does not seem to be supported on most phones.

**However, if you use the VLC app for smart phones, it seems to play really well.**

I had to struggle with this issue myself, too. And this solved it. I hope this solves it for you too. All the very best. :)

P. S: If you want to re-encode the exported video again (because you have already lost the project), use [handbrake](https://handbrake.fr/) instead.

**Comment by DylanC** [comment]
Closing question as answered. Thanks!
