### ISSUE TITLE
Rotation and Transform: viewpoint ?

### ISSUE THREAD

**Issue by gbonline** [OpenShot/openshot-qt#1095]
**System Details:** intel i7 - 16gb ram - nvidia 620
* Operating System / Distro: ? ubuntu 16.05 64bit
* OpenShot Version: ? latest 2.4.1 appimage
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
I've some video captured with my phone on vertical position, I import the files and put one on the Track 0 bar, then right click and select Rotate clockwise 90°. Till now it' s ok, but I need to reposition the viewpoint : the subject of the video is on top of frame, so it's cutted  out a bit.
Then I select Transform to move down the center of image in the preview box. **When I click on the middle circle the image disappear e I need to move the mouse to the left (with left button pressed) to re-center the image.** 
So now I 've an animation of my video viewpoint: playing it I see the video that disappear and then came in from the right agree with the "transform"  operation. 
But I only need to define the new center of the viewpoint.

**Comment by peanutbutterandcrackers** [comment]
I just answered a similar question so I am copy pasting the following:

_...some parts of the video will be chopped off [because the original length of the video is now the breadth of the video (in case of a 90 degree rotation) and the canvas size is still constant]. To resolve this, go to the very first frame of the clip on the timeline (use the arrowed keys for frame-by-frame navigation) and right click and click on properties. In the properties tab, go and change the 'Scale X' and 'Scale Y' property to be a tad bit smaller from the default 1 (for me, 0.57 and 0.57 seemed to work, but you might have to play around). Make sure both scale x and scale y have the same value. That should solve your problem._

The reason I instruct to go to the very first frame is that these parameters apply keyframes where they are being set. And that is what is happening in your case too. The transform tool is setting a keyframe where your play-head was at the time. You might want to look up some of these videos:
- https://www.youtube.com/watch?v=mgi4esWA84M
- https://www.youtube.com/watch?v=P3zIprwr1rk
- https://www.youtube.com/watch?v=7YV6kiwg4fU
- https://www.youtube.com/watch?v=nEyrC1v-M1s

Once you've mastered keyframes, though; a whole new world of possibilities will open up for you.

Hope that helps.

Please do not forget to close the issue once it is resolved. Thanks!

**Comment by peanutbutterandcrackers** [comment]
P.S: Seeing that you are running Linux, the easiest way to do what you are trying to achieve would be this:
`$ ffmpeg -i input.mp4 output.mp4`
It will automatically rotate the video for you. Hope that does help. :)
