### ISSUE TITLE
Timeline breaks when changing speed of clip

### ISSUE THREAD

**Issue by kkursor** [OpenShot/openshot-qt#1116]
**System Details:**
* Operating System / Distro: Ubuntu 16.04
* OpenShot Version: 2.4.1-dev1
* _Please attach log files if crash_

I have a problem after one of updates of Openshot. First of all I used 1.4.3 bundled in Ubuntu, it has same bug. When I add a video to timeline, cut a section and try to speed it up, the timeline becomes confused. It seems like the part of video that continues begins from double-time of the cut fragment.

How to reproduce:
1. Add a video.
2. Cut a fragment in it so it looks like: |______part1____|__part2__|______part3______|
3. Speed up part2 and look at part3. It does not start from the time it originally started. Instead it starts forward or backward. 

Expected behaviour:
Part3 should NOT be affected when altering part2.

**Comment by Periniquus** [comment]
Wanted to second this issue. However:

 

> System Details:

Operating System: Windows 10 64bit
OpenShot Version: 2.4.1
Not crashing in this instance.

Same issue, but a) it doesn't happen consistently and b) speeding up (as in his example) "part 2" will sometimes make several clips (both before and after the sped-up clip) mess up.

How to reproduce:

E.g.: Add a video and add a clip. Edit things as usual, experiencing no issues. Preview video and decide one clip is too slow and 2x it. Preview that section of video again and realize part of the original that you trashed in an earlier split is back. Get confused; fix it; pat yourself on the back. Go to preview the whole thing for a final review and realize the very first clip (which you haven't even touched since you split it as your very first edit) starts at the beginning of the original video instead of where you had set it to start 10 seconds in.

I'm also new to video editing, so I'm working solely with one video and one track (a CCTV clip). This has happened on two different computers, as well, but both are running identical versions of OpenShot.


Expected behaviour:

What he said: why am I even splitting things into clips if they're all still affected by each other and the only thing I effectively accomplish is making all of the other clips angry when I'm working on one clip. :[


Sorry if this should have been in its own thread. I feel like we're describing the same issue and it'd be pretty pertinent, if that's the case, to know that it's happening on three different versions of the software and two completely different operating systems.

**Comment by DylanC** [comment]
@kkursor Can you try v2.4.2 and let us know if you have any success?
