### ISSUE TITLE
How to cut and split a video ?

### ISSUE THREAD

**Issue by stehgold** [OpenShot/openshot-qt#1135]
Hi,

first of all: I've double checked. https://www.openshot.org/user-guide/ 'Support-Ask a question' lead me here. This looks like bug tracking but anyway.

**System Details:**
* Operating System / Distro: ?
System:    Host: oppa-hex-ssd Kernel: 4.14.6-towo.1-siduction-amd64 x86_64 bits: 64 gcc: 7.2.1
           Desktop: Gnome 3.26.2 info: gnome-shell dm: gdm3
           Distro: siduction 13.2.1 December - kde - (201401272125)

* OpenShot Version: ?
OpenShot 1.4.3

**Issue Description and steps to reproduce:**
Seems to much to ask for in Linux: I have a stream recording and want to cut off the beginning, the end and split the remains into 3 equal parts. With MovieMaker I was able to accomplish that within 10 minutes. With this 1 have now one cut at the start. But how do I get rid of this ? How do I split the rest and save the 3 parts ?

It's a 5G file and I have no chance to move this to Windows right now or I would do this. And I don't want to download that big file again.

Stephan

**Comment by N3WWN** [comment]
Hi @stehgold !

You will need to export each part separately.

Start a new project and set the project profile to the same as your source material.  

Import your 5G clip and drag it onto the timeline.

Place the playhead at the position where you want the beginning cut to occur, right click, hover over `Slice` and then select `Keep Right Side`.

Now, move the playhead to where you want to make the 2nd cut (to the end of the "first part"), right lick, hover over `Slice` and this time, select `Keep Left Side`.

Move the remaining portion all the way to the left side of the timeline and export your video.

Now, undo the move and the 2nd slice, but don't move the playhead.  Hover over `Slice` and select `Keep Right Side`.

Now, move the playhead to where you want to make the 3rd cut (to the end of the "second part"), right lick, hover over `Slice` and select `Keep Left Side`.

Move the remaining portion all the way to the left side of the timeline and export your video.

Do the same thing for the 3rd portion.

**Comment by stehgold** [comment]
Hi,

> Place the playhead at the position where you want the beginning cut to occur, right click, hover over Slice and then select Keep Right Side.

right click where ? I don't get 'Slice', I get a menu "Duplicate | Fade | Animate | ...

Thanks for trying to help,
Stephan

**Comment by N3WWN** [comment]
Hmmm... I've never used version 1.4.3, so the slice operation may be elsewhere.   The steps I provided work with the 2.3.x and 2.4.x versions.

**Comment by stehgold** [comment]
Well, Debian, it's unstable already but still very old software versions but kernel and compiler are bleeding edge :)

**Comment by N3WWN** [comment]
You could try the 2.4.1 daily build [AppImage](https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.4.1-2-g445a326-57-656-x86_64.AppImage).  (This one is from Nov 23, 2017.)  

Other AppImage versions are available from the openshot.org [download page](https://www.openshot.org/download/)

There's no install required; just download and run.

**Comment by stehgold** [comment]
Aha, now this looks all dark and I get a different menu including Slice. I do have the 'keep right part' done. Now, where is this playhead and how do I move this ? I went to the end of my video using the slider at the bottom but clicking into the track does nothing.

**Comment by N3WWN** [comment]
The playhead is the red vertical line in the timeline with the blue "teardrop" on top.

You can move the playhead by clicking in the timeline, above the tracks, where the times are displayed.  You can also move the playhead one frame at a time with the left and right arrow keys.

The slide with the + and - changes the timeline zoom.

**Comment by stehgold** [comment]
I don't have anything like that, maybe that's why the video doesn't play anymore. How do I find/get this ?

**Comment by N3WWN** [comment]
Can you post a screenshot of what you're currently looking at?

**Comment by stehgold** [comment]
![image](https://user-images.githubusercontent.com/7829667/34119344-13962ce4-e422-11e7-930f-c47552a3e69f.png)

**Comment by N3WWN** [comment]
Okay, your playhead is not visible at your current zoom level.  

You can zoom out (click the - by the `11 seconds`) a few times and see if you can relocate the playhead, or you can use the scroll bar under the timeline to scan left and right.

**Comment by stehgold** [comment]
Hmm,  I guess it's some bug or something. The picture in the preview doesn't change when I move the playhead and cklicking play does nothing but changing the button.
![image](https://user-images.githubusercontent.com/7829667/34119625-270b7274-e423-11e7-8c2b-e28dbdea78fc.png)

![image](https://user-images.githubusercontent.com/7829667/34119666-4de6faee-e423-11e7-8399-937cfd250dae.png)

**Comment by Casanova88** [comment]
Is it possible to cut segments in the middle of the videos and export the result without reencoding the whole video again?

**Comment by stehgold** [comment]
Hi,
I don't think so. At least that's what I learned during my search for a cutting program. I was wondering which codec to use... ffmpeg from the command line can do. But you have to provide the starting time and length of the slice you want.

You can use the -ss option to specify a start timestamp, and the -t option to specify the encoding duration. The timestamps need to be in HH:MM:SS.xxx format or in seconds (s.msec).

The following would clip the first 30 seconds, and then clip everything that is 10 seconds after that:

ffmpeg -ss 00:00:30.0 -i input.wmv -c copy -t 00:00:10.0 output.wmv
ffmpeg -ss 30 -i input.wmv -c copy -t 10 output.wmv

source https://superuser.com/questions/138331/using-ffmpeg-to-cut-up-video

**Comment by stehgold** [comment]
Hi,

me again. I made it ! Yeah :) But I had to use the systems 1.4.3 version. The one I downloaded crashed and made my DE inresponsive. I couldn't even logout, I had to hit the reset button and restart the computer.

Thanks and have fun,
Stephan

**Comment by N3WWN** [comment]
@stehgold 

I'm glad you found a way to accomplish what you needed to and I'm sorry I could be of more help.  

I was going to suggest the ffmpeg solution for cutting without reencoding, but you beat me to it! 😃 

Regarding your preview window not updating, that may be due to the size of the preview window.  The preview is rendered in the background and then displayed.  With a full-res preview window that large, you're asking quite a bit of the current preview renderer.  If you were sticking with OpenShot, I'd suggest making the preview window smaller, or, if that didn't help, going into the preferences, caching to disk and lowering the quality and/or scale so that the preview can render faster. 

Not sure what to say about the crashing.  OpenShot 2.4.1 has been really stable for me and lot of other folks.  It may be that you're editing such a large file.

**Comment by stehgold** [comment]
@N3WWN Hi,
at the point where the preview window didn't update anymore OpenShot was hanging/had crashed already. No menu did open nor would it close after clicking X. There may be a reason why the Debian maintainers still ship the old version...

Thanks and have fun,
Stephan

**Comment by THRUSTDeltaV** [comment]
I think what you are looking for is clips. Export the entire file open it back up in OpenShot and cut off the parts you do not want.

https://cdn.openshot.org/static/files/user-guide/clips.html

**Comment by Imaginative-Creations** [comment]
I run Voyager 20.04.4 with OpenShot.
Granted I am pretty new at video editing but I have had a lot of problems with OS.
-- one concern is it likes to freeze and sometimes when trying to export or change 
function, it will close when I am in the middle of editing a vid.  Frustrating.
I finally am at a point where I can now cut and swap vid partials, but when you do 
that, you get that flicker on the right side of the preview screen.   Then if you export
the vid, you have that flicker.
I thought I found a fix by going to the FILTER section and changing SCALE X from
1.00 to 1.01.
Doing this removes the flicker from the preview screen but now when you try to 
export the vid, when it tries to close, it says it does not recognize the format.
-- I thought, well I know, I had once been able to "expand" the preview vid which covered 
the flickers and it would save, but this program won't do that now.  I don't know what
changed.
Any usable fixes would be appreciated otherwise I am going to look for another
vid editor.
