### ISSUE TITLE
Openshot becomes slower gradually

### ISSUE THREAD

**Issue by AdityaSher** [OpenShot/openshot-qt#1138]
**System Details:**
GPU : 2GB DDR5 940MX NVIDIA
CPU: INTEL i5 7th gen 
RAM: 8GB
TYPE: notebook (laptop) - running on max performance mode ,in all possible ways

* Operating System / Distro: Windows 1
* OpenShot Version: 2.4.1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
Description: open shot becomes slower gradually 

Steps:
1.Start a new project
2. Add audio file 
3. Start adding images(30+)
4. Arrange them on timeline with transition 
5. Software gets gradually slower , dragging action becomes slower, mouse pointer changes late.

Comments: such thing is not happening with other editors.

**Comment by DylanC** [comment]
Dup of #902

**Comment by peanutbutterandcrackers** [comment]
@anstg - The thing is, OpenShot does not yet have GPU capabilities. Also, because it is a free software made by (mostly) a single person in the time he squirrels away from work, using a Linux machine for primary development, it has performance issues in Windows. Please do however keep on supporting OpenShot. It will only get better with time and more volunteers/supporters. Sorry for the inconvienience. Thanks!

**Comment by DylanC** [comment]
@AdityaSher - Try v2.4.3 and let us know if you still have a problem.
