### ISSUE TITLE
How to rotate the video?

### ISSUE THREAD

**Issue by IceBotYT** [OpenShot/openshot-qt#1145]
**System Details:**
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1

**Description: I need a way to rotate my video because my video is recorded vertical on my phone, I am wondering how to roatate?**

**Comment by IceBotYT** [comment]
Someone please help.. This has been open for 4 days and no answers!

**Comment by N3WWN** [comment]
Can you provide any more details?  Perhaps a screenshot of what your video looks like now and another picture as an example of how you'd like it to look?

Thanks!

**Comment by peanutbutterandcrackers** [comment]
Hey there,

First drag your clip on to the timeline. Then Right click it, go to Rotate and choose the desired Rotation (90 or 180 in desired direction). This should rotate your video.

However, some parts of the video will be chopped off [because the original length of the video is now the breadth of the video (in case of a 90 degree rotation) and the canvas size is still constant]. To resolve this, go to the very first frame of the clip on the timeline (use the arrowed keys for frame-by-frame navigation) and right click and click on properties. In the properties tab, go and change the 'Scale X' and 'Scale Y' property to be a tad bit smaller from the default 1 (for me, 0.57 and 0.57 seemed to work, but you might have to play around). Make sure both scale x and scale y have the same value. That should solve your problem.

If it does, please do not forget to close this issue. Thanks!

**Comment by DylanC** [comment]
Closing as answered. Thanks.
