### ISSUE TITLE
User profile not in the Profiles list

### ISSUE THREAD

**Issue by jkaufeld** [OpenShot/openshot-qt#1154]
**System Details:**
* Operating System / Distro: Mac OSX 10.11.6
* OpenShot Version: 2.4.1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
Trying to follow the instructions at https://www.openshot.org/static/files/user-guide/profiles.html#custom-profile and at http://openshotusers.com/forum/viewtopic.php?f=11&t=3126 to create a custom profile. 

Found the correct subdirectory on my Mac. Created a simple text file named "facebook_600" (no extension), and restarted Openshot. My custom profile isn't in the list.

After finding a reference to adding "prf" as an extension on the file, I tried it. Still didn't work.

Your help is appreciated!!!

**Comment by N3WWN** [comment]
Are you running Openshot as the same user that has the `.openshot_qt/profiles` directory in their home dir?  Does the user that Openshot runs as have access to the files in the `.openshot_qt/profiles` directory?

**Comment by N3WWN** [comment]
Greetings John! 

That is quite interesting as I can replicate the profile, but not the problem.  

I created a file named `facebook_600` in my ~/.openshot_qt/profiles directory and used `chgrp` to set the same group ownership and `chmod` to set the same permissions:

```
[ralloway@video profiles]$ ls -al
total 24
drwxrwxr-x  2 ralloway ralloway   4096 Jan  2 17:01 .
drwxrwxr-x 12 ralloway ralloway   4096 Jan  2 17:04 ..
-rw-rw-r--  1 ralloway ralloway    200 Oct 23 16:13 atsc_1080p_100
-rw-r--r--  1 ralloway 1344686075  199 Jan  2 17:01 facebook_600
-rw-rw-r--  1 ralloway ralloway    182 May 10  2017 youtube_170510
-rw-rw-r--  1 ralloway ralloway    191 May 16  2017 youtube_720_170516
[ralloway@video profiles]$ 
```

My OpenShot (I'm using `OpenShot-v2.4.1-x86_64.AppImage`, BTW) finds the custom profile and makes it available just fine, as you can see just over 1/3 of the way down the profile list:

<img width="343" alt="facebook 600" src="https://user-images.githubusercontent.com/19431804/34502031-b3c7be62-efdf-11e7-8cc4-a7e693b94534.png">

I'm not sure why you're having problems.

I agree with you that, since openshot-qt.log is being updated, the paths and permissions are likely good.

Since I'm using Linux and you're using a Mac, there may be subtle differences that we're not aware of.  

You could try to reset the group ownership of the profile file.  Maybe also check the ownership and permissions of the `/Users/kaufeldj/.openshot_qt/profiles` folder - they should be the same as the other directories. 

One more thing is to make sure you have a new line at the end of the profile file and that there aren't any control (or other unprintable) characters in the file.   I looked at mine using `hexdump` and there is a 0x0a at the end of each line, which is correct:

```
[ralloway@video profiles]$ hexdump -C facebook_600 
00000000  64 65 73 63 72 69 70 74  69 6f 6e 3d 46 61 63 65  |description=Face|
00000010  62 6f 6f 6b 20 36 30 30  20 73 71 75 61 72 65 0a  |book 600 square.|
00000020  66 72 61 6d 65 5f 72 61  74 65 5f 6e 75 6d 3d 33  |frame_rate_num=3|
00000030  30 0a 66 72 61 6d 65 5f  72 61 74 65 5f 64 65 6e  |0.frame_rate_den|
00000040  3d 31 0a 77 69 64 74 68  3d 36 30 30 0a 68 65 69  |=1.width=600.hei|
00000050  67 68 74 3d 36 30 30 0a  70 72 6f 67 72 65 73 73  |ght=600.progress|
00000060  69 76 65 3d 31 0a 73 61  6d 70 6c 65 5f 61 73 70  |ive=1.sample_asp|
00000070  65 63 74 5f 6e 75 6d 3d  31 0a 73 61 6d 70 6c 65  |ect_num=1.sample|
00000080  5f 61 73 70 65 63 74 5f  64 65 6e 3d 31 0a 64 69  |_aspect_den=1.di|
00000090  73 70 6c 61 79 5f 61 73  70 65 63 74 5f 6e 75 6d  |splay_aspect_num|
000000a0  3d 31 0a 64 69 73 70 6c  61 79 5f 61 73 70 65 63  |=1.display_aspec|
000000b0  74 5f 64 65 6e 3d 31 0a  63 6f 6c 6f 72 73 70 61  |t_den=1.colorspa|
000000c0  63 65 3d 37 30 39 0a                              |ce=709.|
000000c7
[ralloway@video profiles]$ 
```

Anywhere there is a `.` in the 4th column of the output, it should align with a 0x0a in the 2nd or 3rd columns.

If you have other occurrences of `.` characters, there may be an unprintable character that has snuck into the file, causing OpenShot to be unable to parse the file properly.

Another possibility may be characters that look alike, but are not encoded the same.  For instance, quotes in a command displayed in a Microsoft application, for instance, usually won't work well if you copy and paste the command to the command line without deleting and retyping the quotes in the terminal window.  If you copied and pasted the original contents of the facebook_600 file, you may have better luck if you open a brand new file and typed each line in manually.

Make sure that the editor that you're using isn't saving the file in a rich text format or anything, too.  The hexdump output should help with determining if that is the case, so feel free to reply and paste the results in a quote block or otherwise attach them.

73 de Rich N3WWN

**Comment by jkaufeld** [comment]
Good news -- the problem is resolved! Funky news -- the problem was extra spaces before my custom profile commands.

SOLUTION
Make sure each line in the custom profile file starts in column 1. If the commands in the file have spaces in front of them, the software ignores them.

NARRATIVE
When I saved the facebook_600 profile, my text editor indented each line in the file by five spaces, which made it very pretty code. Unfortunately, those spaces made OpenShot ignore my preferences file.

Using the nano editor in Terminal, I deleted the extra spaces so the commands started in the first column of each line. I saved the file and started OpenShot, then checked the Profiles. Success! My custom profile appeared in the list and seems to work perfectly.

Thanks again for all of your help, Rich!!

73 de John K9INK
