### ISSUE TITLE
 TitleFileName-7.svg cannot be found

### ISSUE THREAD

**Issue by MMG2002** [OpenShot/openshot-qt#1170]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ? most recent 
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
when i start open shot it has a popup saying TitleFileName-7.svg cannot be found. what does this mean and how can i fix it it will not let me do anything in the program other than open file manager and try to look for file

**Comment by peanutbutterandcrackers** [comment]
When one saves an openshot project, Openshot creates 1 or 2 folders in the same folder as the .osp file (the project file)  - 'thumbnail', which includes the thumbnails of the clips and, depending on whether or not you have created any titles from inside Openshot, an 'assets' folder that contains the titles.

If Openshot is unable to find the files that were saved in these folder while trying to ooen the .osp file, it complains and can not open the project.

So, it seems that you somehow had that fie deleted and so, are unable to open the project.

As a temporary workaround, create another title file in a new project, and find the title asset for that project (note how it resides in the 'assets' folder), rename it to whatever title file Openshot says it can't find and copy it to the 'assets' folder for the un-openable project. This should trick OpenShot into opening the project.

My way of saving a project, in light of OpenShot's aforementioned behaviour, is to save the project in a specific folder made for the project. That way, the odds of me loosing any project related file, and thereby loosing my entire project, are far less.

I hope that helps. Please do keep on supporting OpenShot. It is the labor of love of (mostly) a single person.

**Comment by DylanC** [comment]
@MMG2002 - Yes, just put a file with the same title in the project for now. That should be enough to get past the issue. Hope you don't mind if I close this as the question has been answered.

**Comment by edwardudell** [comment]
I put an audio file in the Openshot 'assets' folder, and the audio file disappeared.  Any ideas.

**Comment by peanutbutterandcrackers** [comment]
@edwardudell - I did try putting a file in the 'assets' folder too. It didn't disappear. Also, if you have another copy, you might want to point to it's parent folder when OpenShot complains it can't find that particular file.

**Comment by peanutbutterandcrackers** [comment]
Wait, according to your [comment](https://github.com/OpenShot/openshot-qt/issues/1118#issuecomment-390412470) in another issue, I think that you put the file in .openshot_qt/assets, which would explain why the file is disappearing, because OpenShot wipes those folders when it starts.
Where you should have put the files instead was in the 'assets' folder in the same folder as your `.osp` project file. If you still have another copy of the file, you might want to try that. Hope that helps. If I have made any wrong assumptions, please do correct me. All the very best with your video project. And I am sorry for the inconvenience caused. This is a free/libre software project and we, as a community, are doing our part to make it better. Hope you'll understand. We'll still try to solve these issues, if we can., as soon as possible...
