### ISSUE TITLE
Static in my video

### ISSUE THREAD

**Issue by Williambless** [OpenShot/openshot-qt#1182]
**System Details:**
* Windows 10 Pro
* OpenShot Version: 2.4.1
Hearing lots of static and popping in my video 

To reproduce this take a video with audio and take a loud aggressive wav. file (like electric music) and put it over the video. You will hear static and popping in the preview and the exported video.

Looking forward to your response,
William Blessing 
p.s. a link to a static video: https://www.youtube.com/watch?v=Pvjin-XoUZQ skip to 0:30

**Comment by N3WWN** [comment]
Is it possible that the wav file is clipping due to the volume?  Is any static audible in the source wav?

Does the amount of static change if you decrease the volume, either on the track as it exists on the timeline or by decreasing the default volume in `File` -> `Preferences` -> `General` -> `Volume`?

**Comment by DylanC** [comment]
Dup of #1162

**Comment by DylanC** [comment]
@Williambless Can you try v2.4.2 and let us know if you have any success?

**Comment by mikelacsa** [comment]
No response from @Williambless. Closing the ticket.
