### ISSUE TITLE
Music reading like video?

### ISSUE THREAD

**Issue by ElenaC1** [OpenShot/openshot-qt#1184]
**System Details:**
* Operating System / Distro: Windows 10
* OpenShot Version: n\a

When I add my music its reading like video, what I need to do with it

**Comment by DylanC** [comment]
@ElenaC1 
Disable the video/display part of it by clicking on the correct track icon or find in the right click menu.

**Comment by peanutbutterandcrackers** [comment]
Perhaps you want to see the waveforms instead of the thumbnail? If so, you should probably A. Upgrade OpenShot to the latest version and B. right-click on the 'video' which is infact just audio and go to Display -> Show Waveform. That should help you.

**Comment by lenov** [comment]
I have the same issue. I downloaded an mp3 from the Free Music Archive. When imported in OpenShot 2.4.1, it is interpreted as a video. I do not want to display anything, neither thumbnails or waveform. I just want to use the audio.

**Comment by peanutbutterandcrackers** [comment]
You could always right click on the said mp3 file on the timeline, click on `Properties` and go to `Enable Video` which should default to `-1` (which means 'automatic'), and change it to `0` (which means 'No'). But you'll have to make sure that the playhead is at the very beginning of the clip. Or else, you'll end up having unexpected behaviours - unwanted interpolations. In order to master all of that, though, you might want to read [this awesome guide](https://gist.github.com/peanutbutterandcrackers/f0f666243133e0ed25abbc12a4ba23d7).

Hope that helps! :+1:

**Comment by lenov** [comment]
I'm afraid that does not work. I still have a big black square in the middle of the image. One possibility would be to re-order the tracks so that the music is below the video (I should have thought of that when creating the tracks ...). But it seems that we cannot re-order tracks in openshot 2

**Comment by peanutbutterandcrackers** [comment]
@lenov - I just downloaded one `.mp3` from Free Music Archive and it doesn't have any problem. Could you perhaps please point us to the .mp3 file that is causing you trouble? Either the URL or the file itself (perhaps zipped) would be just fine.
![screenshot at 2018-06-10 16-41-34](https://user-images.githubusercontent.com/26764547/41200923-4dec1834-6ccd-11e8-99d9-89e5dbad6d05.png)
