### ISSUE TITLE
Runtime Error with launch.exe

### ISSUE THREAD

**Issue by feutl** [OpenShot/openshot-qt#121]
Hi,

I do get a runtime error at the very beginning on starting OpenShot. I am using version 2.0.6 on a Windows 8 machine.

![image](https://cloud.githubusercontent.com/assets/8522012/13562611/b84d838e-e43a-11e5-8936-5d36586e28c9.png)

I found a similar issue but seems to occure during runtime but on Windows 10, perhaps this is somehow related
https://github.com/OpenShot/openshot-qt/issues/13
https://github.com/OpenShot/openshot-qt/issues/59

This is the content of my log file after trying to start openshot 2 times.
[openshot-qt - Copy.txt](https://github.com/OpenShot/openshot-qt/files/160900/openshot-qt.-.Copy.txt)

**Comment by jonoomph** [comment]
Does the interface ever appear? Or does it just pop up that error dialog?

**Comment by LiquidOctarine** [comment]
I get the same error.  I'm using Windows 10 (64 bit).  I've tried it on two different machines.  Usually happens when I'm trying to edit something, or render something.  This started days after I downloaded it, and I was just trying it out.  It first showed up when I tried to render something with three tracks and multiple cuts and transitions--the render on that one never goes above 60%.  Ever since, it happens a few minutes after I open it if I don't try to render right away, even on the second computer.  I've even tried uninstalling and reinstalling but the error continues to pop up then forces the program to close altogether.

**Comment by feutl** [comment]
@jonoomph 
Sorry for replying that late.The interface never appears at all. The only thing I see is the error dialog.

**Comment by carlosnewmusic** [comment]
![sin titulo](https://cloud.githubusercontent.com/assets/19379457/20460147/1a331030-aedb-11e6-8607-773cca41acd0.jpg)

**Comment by jonoomph** [comment]
We have recently made a ton of improvements for video freezing and crashes, and I would like to verify this issue still occurs with our latest daily build. Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. 

If the issue still occurs, please reopen this issue and attach log files (https://github.com/OpenShot/openshot-qt/blob/master/.github/CONTRIBUTING.md), and hopefully we'll be able to nail this down and fix it. Thanks!
