### ISSUE TITLE
Question on changing default export folder

### ISSUE THREAD

**Issue by SJoh527** [OpenShot/openshot-qt#1227]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
Is it possible to change the default export folder? If so where can I do so. If not can this be added?

**Comment by DylanC** [comment]
@SJoh527 - Did you try in the Preferences?

**Comment by peanutbutterandcrackers** [comment]
@DylanC - I don't think it can be done in the preferences. However, @SJoh527, OpenShot uses the folder where the project (the *.osp file) is saved as the default folder to export the video to. However, if the project has not yet been saved, OpenShot uses the home folder to export the videos.

I hope that helps!

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Closing question as answered. (maybe worth a separate enhancement issue)

**Comment by peanutbutterandcrackers** [comment]
@DylanC - I wonder if this is really worth doing. There is no default export folder, per say. It's just the location where the project is currently saved in... And if the project is still untitled/unsaved, it tries to export into the home directory. Which seems to be a fine choice to me at least. It could be the 'Videos' directory, but then again, because the program is cross platform, it might require a bit of duck-taping if the project went the route of making the 'Videos' directory the 'default' (I think it's 'My Videos' on Windows, and 'Videos' on most Linux Distros).

@SJoh527 - Perhaps you'd like to explain how you'd like this change to be implemented, good sir? Maybe I am not able to see something here...

@ferdnyc - What do you think, good sir?

Perhaps @N3WWN would also like to add some input here?

**Comment by ferdnyc** [comment]
Cross-platforming wouldn't be any kind of issue. Qt offers the [`QStandardPaths` enum](http://doc.qt.io/qt-5/qstandardpaths.html), so the user's standard "Videos" folder location on any system would simply be `QStandardPaths::MoviesLocation`.

I wouldn't _object_ to that being the default import _or_ export target location. Nor would I _object_ to OpenShot retaining the last-used location for either/both in the user preferences, instead of or in addition to the project file, and defaulting there instead of `QStandardPaths::HomeLocation` (which is where it now quite aggressively defaults to). I don't really see any/all of those changes as a priority, myself... but they're actually pretty good "low-hanging fruit", if someone wanted to get their feet wet in PyQt by tackling a pretty straightforward code change.

A user _preference_ for the default path... might be overkill, it's another setting to keep track of and worry about when to respect and when to ignore. So I guess that's a slight objection to that. Though, if anyone were to do all the work to make it happen and submit a PR implementing that preference, I'd have no issues with it getting merged.

**Comment by ferdnyc** [comment]
Oh, but if the default export location changed, the default project file save location _and_ the default Import Files... location would _have_ to be changed as well. Currently OpenShot uses _relative_ directory paths to all of the clips on the timeline (but absolute paths in the Project Files list, confusingly; that's something that really needs to be looked at as well), so it is still a **very** good idea to keep your project media together with the project file itself. Move the project file anywhere else on disk, relative to the media files, and you're going to be trapped in the dreaded "Missing File (_file\_id_) _myvid.mp4_ cannot be found." dialog-box loop for all of your clips.

So, it's best to still encourage keeping files together. In fact, it'd probably be better to change the default _project-file_ save path to `QStandardPaths::MoviesLocation`, but continue to default the export path to the project-file location after the project file is saved. 

(If the user saves their project files in their Videos folder, great, it'll have the same effect. But we should not encourage them to separate project files from media in or out, not even implicitly. At least not until OpenShot gains something akin to Audacity's consolidation features: "Copy all audio into project" [a preference governing reference- vs. duplication-importing] and "Save compressed copy of project" [a project export/archival tool which bundles copies of all input media together with the project data files].)

**Comment by N3WWN** [comment]
I agree with @ferdnyc ... the current behavior of exporting to the same dir as the .osp file is pretty intuitive and, if you haven' saved the project, the home dir is the first place I'd look for the rendered video.  

You can see the folder that OpenShot is going to render to in the `Export Video` dialog... and can probably change it there, too, though I haven't actually attempted this.

**Comment by uncoolcentral** [comment]
FWIW - I use OpenShot without ever saving project files. I load my footage in, and export it. No need for an intermediary project file. It would be great UX to be able to specify a default export directory. ...It's not an uncommon feature. I specify default export/save paths in most other applications, from Audacity to Word.
