### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by petermeriva** [OpenShot/openshot-qt#1256]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

Tried to change language to English under preferences. Restarted etc, but prog continues in Spanish. Can I change this?

**Comment by peanutbutterandcrackers** [comment]
Works for me though. Perhaps try changing language to 'Default', if your default language is also English?

Mine is. And I just successfully changed it to Spanish and American English and back to default.

If you're using an older version of OpenShot, perhaps consider upgrading to the latest one (v 2.4.1)?

**Comment by peanutbutterandcrackers** [comment]
Question: Are you on windows, too?

Theory: If you are on windows, like a LOT of the other issues reported here, this, too, might be windows-specific...

**Comment by woytam** [comment]
Same problem here.
**Windows 7 x64 Czech, OpenShot 2.4.1**
My `default` language in OpenShot is Czech (according to Windows language). If I change language in preferences to other non English language and restart, everything is OK (tested with Dansk - `da`). Also Australian English `en_AU` is OK. But if I choose American English `en_US`, after restart, it is like `default` - Czech.
I think, there is problem in file `openshot-qt/src/classes/language.py` on [line 88](https://github.com/OpenShot/openshot-qt/blob/c06e3d68d280a891f880b1f97507126c6f9cd1c2/src/classes/language.py#L88), where it expects that our default lang is english (`en_US`).
```
# Don't try on default locale, since it fails to load what is the default language
if 'en_US' in locale_name:
    log.info("Skipping English language (no need for translation): {}".format(locale_name))
    continue
```
It is necessary to rewrite `IF` statement. Instead of hardcoded `en_US` use `os.environ.get('LANG', QLocale().system().name())` or `os.environ.get('LOCALE', QLocale().system().name()`.
I hope, that this will help.

**Comment by peanutbutterandcrackers** [comment]
@woytam - Thank you for the detective work. That's awesome!
@DylanC - Perhpas we should ask @woytam here to make a Pull Request? What do you think, Cap'n?

**Comment by woytam** [comment]
Thank you for your confidence, but I do not program in Python and I do not understand program logic in deep.
So I let somebody else to take care of making Pull Request.

**Comment by DylanC** [comment]
@woytam - Thanks, this is great information.  @peanutbutterandcrackers - Leave it to me. I will put something in as soon as the PR's are cleaned up.

**Comment by peanutbutterandcrackers** [comment]
@woytam - I see. I hope you do continue to support OpenShot and provide us with such valuable insights to help the devs fix the bugs. :)

@DylanC - I see. Okay. I hope @jonoomph comes back soon.

**Comment by peanutbutterandcrackers** [comment]
@DylanC - The PRs have been cleaned up!!! :smile:

**Comment by DylanC** [comment]
@peanutbutterandcrackers - I've added a PR for this now. Not very sure if its the right fix but Jonathan can let us know either way.

**Comment by peanutbutterandcrackers** [comment]
@DylanC - Awesome! Hope this fixes the issue for everyone!

**Comment by peanutbutterandcrackers** [comment]
Hey there, the pull request to fix this has just been merged into the main branch. If any one among you is using an Ubuntu-based Linux Distro, please use the [daily PPA](https://www.openshot.org/ppa/) to test and confirm that this bug has been resolved. Else, we might need to report to the developers that the bug still needs a proper resolution. Thanks!

**Comment by peanutbutterandcrackers** [comment]
[Here](https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.4.1-30-gce4232b-59-683-x86.exe) is the latest build of OpenShot for windows, BTW. :)

**Comment by DylanC** [comment]
Dup of #331

**Comment by DylanC** [comment]
@petermeriva - Closing this since the original issue is solved. (see #331)
