### ISSUE TITLE
Can't remove video from mp3-file

### ISSUE THREAD

**Issue by LievenHanssen** [OpenShot/openshot-qt#1257]
**System Details:** 
* Operating System / Distro: elementary OS
* OpenShot Version: 2.4.1-dev1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

I have a mp3-file that is recognized as a video-file. If I place it on the time line it overlaps my video with some sort of logo of a website. I would like to remove the video entirely from it, and only use the audio. When I separate the audio and delete the remaining file, the problem of the overlapping logo remains. Is it possible to remove the video-part from a clip and only use the audio? I know this used to be trivial in the OpenShot 1.4 series, but I can't seem to find this option anywhere.

**Comment by peanutbutterandcrackers** [comment]
I think you should try putting the mp3 in a lower layer in the timeline. Perhaps have the video in an upper layer. This should help.

Or, since you're using linux, try using ffmpeg to resolve this issue.
$ ffmpeg -i input_file_name.mp3 output_file_name.oga
oga is an open audio container and works really well, too.
Note: Make sure you execute this command in the same directory as the mp3 file.

But this is one strange problem, indeed. Unless you're putting the audio in the top layer and video in the botom one.

Hope this helps. :)

**Comment by LievenHanssen** [comment]
Putting the audio in a bottom layer does work and that's what I used as a workaround at first, but it's not optimal. Reencoding with ffmpeg is a more permanent way to getting what I would like, thanks for that tip! I'll open a feature request for it. Thanks for your help!

**Comment by peanutbutterandcrackers** [comment]
I think OpenShot is designed that way: the things in the higher layer gets precedence over the things in the lower ones. And perhaps the issue was the mp3 metadata - an album art on the thing. Perhaps.

But I'm glad it's resolved.
