### ISSUE TITLE
How do you add a black and white filter to a track?

### ISSUE THREAD

**Issue by Serdna101** [OpenShot/openshot-qt#1271]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by peanutbutterandcrackers** [comment]
@Serdna101 - Head over to the 'Effects' tab, and drag and drop the 'Color Saturation' effect on to the clip. A (red) box with the letter 'S' should now appear in the timeline, on the clip. Right Click the 'S' and click properties. Make sure your play head is at the very beginning of the clip that you want to have as black and white, or else you'll probably not get the desired effect. On the properties tab that should have now opened up on the left of the screen, change the saturation to 0 instead of 1. That should turn your clip into black and white.
![b w effect openshot](https://user-images.githubusercontent.com/26764547/36080790-fa3b17b0-0fbd-11e8-9f62-5404fb1c465a.png)
Please do not get confused by the additional 'Shift' and 'wave' effect that I have in my Effects tab. I am using a daily (unstable) version of OpenShot.

I hope that helps!

**Comment by peanutbutterandcrackers** [comment]
P. S: You can also have values like 0.07 or 0.1 in the Saturation property. Might help you get the right B&W effect.

**Comment by DylanC** [comment]
Closing this question as answered. Thanks @peanutbutterandcrackers!
