### ISSUE TITLE
video export quality setting ignored

### ISSUE THREAD

**Issue by steelbytes** [OpenShot/openshot-qt#1273]
No matter what I select on the simple or advanced tabs of the export video dialog, it always exports with the same mbps.

I'm trying to do mp4/h264 (no audio) 720p@25 at around 3mbps.  it always generates around 6mbps

2.4.1 x64 on Win10

**Comment by peanutbutterandcrackers** [comment]
Issues like these do not happen on my linux machines. It seems that there are a lot of windows-specific bugs in openshot. Because of lack of developers esp to look after windows versions, the project is falling behind. But I think that once he has the time, Mr. Jonathan Thomas - our one and only developer for now - will hopefully get around to solving these issues. Sorry for the inconvienience...

**Comment by peanutbutterandcrackers** [comment]
On second thought, it might be worth installing ffmpeg manually and then reinstalling openshot to see if that works.... but I am not quite sure, as I do not use windows...
