### ISSUE TITLE
Incorrect horizontal size transforming bug

### ISSUE THREAD

**Issue by xxmadbrinexx** [OpenShot/openshot-qt#1277]
# System/Software Info:
Operating System: Windows 10
OpenShot Version: 2.4.1

# Issue Description:
When I resize an image, the width is only half of what it should be.
# Steps to reproduce:
Put an image into a project
Transform
Resize horizontally
Done. Doesn't size properly

## So,
does anyone else have this problem?

**Comment by peanutbutterandcrackers** [comment]
Hey there! Thanks for this wekk-written issue report. Hopefully, someone will soon test and confirm this. (I do not have a computer with me right now) Thank you for your patience.

**Comment by peanutbutterandcrackers** [comment]
@xxmadbrinexx - I think it is an inherent design. I tried resizing horizontally and vertically - both of them didn't maintain the original aspect ratio. However, when I resize using the corners, it keeps the aspect ration intact. I think it was designed that way to mimic the resize features in word-processors so that the users can find similarities and find the Video Editor easy to use. Ease of use is what OpenShot strives for, despite being so very powerful. Please use the corners to resize. It will give the result that you want. I hope that helps.

(Please do not forget to close the issue, too. Thanks! I hope you keep on supporting OpenShot! God Bless You! :) )

**Comment by xxmadbrinexx** [comment]
@peanutbutterandcrackers When I found this, I was using the corners. Then I tested the sides, and it was still messed up. It's pretty annoying to be honest...

**Comment by peanutbutterandcrackers** [comment]
@xxmadbrinexx - Sorry. I later realized that the aspect ratio was not being maintained even while using the corners. I meant to inform you, but forgot. Yes, it is a little iffy.

@DylanC - I can confirm this bug! Pretty sure this was not the way it was meant to be. Even dragging by corners (transform tool), does not maintain the aspect ratio.

I hope this will be solved soon. :)

**Comment by DylanC** [comment]
@peanutbutterandcrackers - No problem! Thanks for confirming.

**Comment by xxmadbrinexx** [comment]
Thanks for the help!

**Comment by xxmadbrinexx** [comment]
So, since it's confirmed as a bug, I guess I close the discussion??

**Comment by peanutbutterandcrackers** [comment]
@DylanC @xxmadbrinexx  You're most welcome! Always happy to help. :)

**Comment by peanutbutterandcrackers** [comment]
So I've figured something out! It seems that the transform tool behaves like InkScape's transform tool rather than LibreOffice and GIMP's... All you have to do to protect the aspect ratio is to press CTRL while dragging from the corner!
