### ISSUE TITLE
Issue : Can not add pictures files on project if picture's title is a number ?

### ISSUE THREAD

**Issue by Jehan67** [OpenShot/openshot-qt#1288]
**System Details:**
* Operating System / Distro: Windows 10 ; version: 1709 ; OS_version : 16.299.248
* OpenShot Version: OpenShot-v2.4.1-14-ge4a5aa1-57-672-x86_64.exe
No logfile

**Issue Description and steps to reproduce:**
Hi there,

I think i've found a bug here. When I start a new project, I add the MOV part and then a lots of pictures. All thoses pictures had a title like 1.jpg 2.jpg 3.jpg, etc...
Each time I tried to load these on the project, there was a runtime error as soon as I accepted to added them.
I tried to load others pictures with letters, it worked. 

**Quickfix** 
My temporary fix is to rename the files you want to add. Worked for me.

**Comment by peanutbutterandcrackers** [comment]
@Jehan67 - Excuse me but are you THE JEHAN??? The one who is working on Zemarmot and fixes bugs in GIMP!??

**Comment by peanutbutterandcrackers** [comment]
P.S: I will test this on my machines and get back to this soon.

**Comment by Jehan67** [comment]
Hi Peanut,

I'm am a Jehan, but only an homonym of the one you think I am :)

**Comment by Jehan67** [comment]
Hi Peanut,

I'm am a Jehan, but only an homonym of the one you think I am :)

**Comment by peanutbutterandcrackers** [comment]
@Jehan67 - You can reopen this issue. I'm pretty sure. I think there's a "comment and reopen" or sth there...

**Comment by peanutbutterandcrackers** [comment]
@Jehan67 - And oh... I see. lol It says you use windows. That shoukd have given it away. The Jehan probably never use windows.... but nice to meet you, anyways. :)

**Comment by ferdnyc** [comment]
Interesting. Here's what happens when I try that in 2.4.0 (which is the version rpmfusion is still distributing for Fedora Linux):

If I import png files `1.png` and `2.png` using the File→Import Files... menu (or Ctrl+F), they're both imported without incident.

If I try to drag-and-drop those two files into the OpenShot window, This dialog pops up:

![screenshot from 2018-02-20 08-15-25](https://user-images.githubusercontent.com/538020/36426048-e87403c0-1616-11e8-82dc-af7cb44a818e.png)

If I say no, the files are again imported normally. If I say _yes_, I end up with `1.png` imported as an image file, along with a new video titled `Desktop (%01d.png)` (if the files were stored in the folder `Desktop`), which had properties setting it up as an image sequence (path `/home/ferd/desktop/%01d.png`, Video Format: png, width/height matching the images, etc)... but it didn't seem to work properly. (And never displayed anything.)

So then I took an actual image sequence I have (115 exploded frames of a GIF animation), and dragged `frame0.png` through `frame2.png` into OpenShot. It gave me the same dialog, and answering "Yes"... promptly crashed OpenShot. ("No" still imported them normally, though.)

So my guess is that what's failing for you might be OpenShot's automatic Image Sequence recognition, which as of 2.4.0 didn't appear to be quite functional anyway. And you might also be able to work around that by using the file-selection dialog to import your images, instead of drag-and-drop. (If you were using drag-and-drop.)

**Comment by ferdnyc** [comment]
Actually, it appears `/home/ferd/Desktop` is the _only_ place I can drag images from, without crashing OpenShot (if I say "Yes" to the import dialog). and it only works if I drag two files named `1.png` and `2.png`. Any other folder, or any other set of (pattern-named) files even from that folder, and saying "Yes" to the image sequence dialog results in an immediate crash. I'm not sure what's so special about those filenames in that location, that it even sorta-works only under those particular conditions.

**Comment by ferdnyc** [comment]
And, having built OpenShot 2.4.1 for my system (atop libopenshot-0.1.9, libopenshot-audio-0.1.5), I can now confirm that trying to drag `1.png` and `2.png` from my Desktop and responding "Yes" to the "Would you like to import 2.png as an image sequence?" prompt now causes OpenShot to instantly crash, same as everywhere else. So, whatever weird corner case was causing that to work for me with 2.4.0 has stopped working.

**Comment by peanutbutterandcrackers** [comment]
As for my Elementary OS Loki 0.4.1 'Loki' machine, importing works just fine. I can drag and drop from Pictures/openshot_import_test/ directory just fine and all the pictures there were re-named to be 1.png, 2.png and it works just great. The image sequence is imported. OpenShot doesn't crash. And the playback is pretty neat too.

I think I should test using jpegs now. Maybe I'll convert the pngs into jpgs...

**Comment by peanutbutterandcrackers** [comment]
Okay. So when I import the same files converted to jpgs from Pictures/openshot_import_test/jpgs, openshot seems to freeze. I think it's doing sth. But it kinda' freezes. Yup. It's frozen.

I think it has to do with jpgs. pngs work just fine. At least on my machine...

**Comment by peanutbutterandcrackers** [comment]
@DylanC - This one probably deserves your attention, good sir! :)

**Comment by DylanC** [comment]
@ferdnyc @peanutbutterandcrackers - I've went over to Windows 10 to try reproduce this issue. Indeed it seems to freeze up for me when I try to import image sequence via the small dialog that pops up. It turns into a "Not Responding" window but does not crash.

**Comment by ferdnyc** [comment]
In light of my experiences testing #1526 I concur, and suspect they're one and the same bug — there appear to be Windows-only issues with drag-and-drop file import, specifically, that aren't encountered either with "Import Files..." on Windows or at all on Linux. (Haven't heard one way or the other on these issues from any Mac users, from what I can tell.) On Windows the pathname of the dropped file can cause import failures, for some reason.
