### ISSUE TITLE
Not responding to simple actions

### ISSUE THREAD

**Issue by Lysatoo** [OpenShot/openshot-qt#1298]
**System Details:**
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1
* _Please attach log files if crash_

I am creating a video made from simple images (10 image) and titles (12 titles). Any action I take (move a clip) (create a fade) takes several minutes (I timed it to see how long it was really taking, the average is 2.5-3 minutes) for the program to process. Half my project time is spent simply waiting for a response. This can't possibly be normal lag time. Is there something I can do to speed the performance?

**Comment by peanutbutterandcrackers** [comment]
@Lysatoo - I am sorry for the inconvenience that has been caused. The thing is, since OpenShot is the labour of love of a single person and he is the only active developer right now (who also uses Linux machine as his main development platform), the project lags a bit behind when it comes to windows in terms of stability. There are a truck load of issues specific to windows that do not occur on my Linux machine. Please be patient. Maybe, soon, we'll have more volunteer programmers trying to help out with the development in other platforms too... sorry again.

**Comment by schwares** [comment]
Hello,
I use Linux with OpenShot V2.4.1-dev1 and I have the same problems. Every action takes a long time. I work with Kubuntu 16.04. I would like to create a Dia Show from approx. 200 Images.
Have you a tip for me how I can increase the performance?

Thank you

Kind Regards, Erich

**Comment by peanutbutterandcrackers** [comment]
@schwares - My first suggestion would be to see if switching to the latest [daily PPA](http://openshot.org/ppa) would fix it. Secondly, if the images you're using are of way too high quality, perhaps try using something like `imagemagick` (`$ for i in *.JPG; do imagemagick -quality 85 $i.JPG Reduced_$i.JPG`) and try importing those again and seeing if that works?

Hope that helps!

**Comment by schwares** [comment]
Hello,

Am Montag, 26. März 2018, 00:32:42 CEST schrieb peanutbutterandcrackers:
> @schwares - My first suggestion would be to see if switching to the latest
> [daily PPA](http://openshot.org/ppa) would fix it. Secondly, if the images
> you're using are of way too high quality, perhaps try using something like
> `imagemagick` (`$ for i in *.JPG; do imagemagick -quality 85 $i.JPG
> Reduced_$i.JPG`) and try importing those again and seeing if that works?

Thank you for the fast answer.
The newst build crashd on my computer. I had redunced the images before 
importing to 1600x1200. I thought that this sould be enough.
I think the count of the images is a problem for openshot.

Kind Regards, Erich

**Comment by peanutbutterandcrackers** [comment]
Perhaps try a not-so-new daily build to see if that works? Currently, the support for ffmpeg 3.x is being added and it's only half done. Maybe that is why it is crashing. Could you use a daily build that is 2 weeks old? I think it should work then. Hope that helps!

I think it has more to do with the size of the image rather than the dimension... or the numbers. I have crashed OpenShot, too, while using pictures from my pal's DSLR.

Always happy to help. :)

**Comment by peanutbutterandcrackers** [comment]
Also, in case of crashes, please do [attach log files](https://github.com/OpenShot/openshot-qt/blob/master/.github/CONTRIBUTING.md). I will try to get the devs attention to this issue once we have the logs and stuff. Thanks!

**Comment by Alejo66** [comment]
Thanks a lot for being there!
I'm a 3  weeks Openshot user. I already edited a video with over 60 files (images, titles and music) and numerous transitions. Now I was about to end my 2nd video with similar load and the same 2 errors recurr: 
1) when an image is taken to any time moment of any track, it is not stored there but at the beginning of Track 1 (even staying several minutes with the file selected for letting the system time to proceed). Then:
2) when the image is selected in order to operate with it, it does not change the border color to red as it should , but to yellow, and the image cannot be moved. (It can be shortened pulling from the lefet-hand side border, though, once it loses red color to omission blue.)
I' really in need of help, and I'd be so thankful if you could assit me. I cross fingers!
I'm operating with and Widows 10 and Office.
Many thanks in advance!
