### ISSUE TITLE
Windows 2.0.6: C++ Runtime Error

### ISSUE THREAD

**Issue by thoro87** [OpenShot/openshot-qt#130]
What I did:
- drag videos on two tracks
- now drag the timeslider to a point where the videos overlap

I was able to reproduce the bug on two machines (both running Win7 x64).

Might be related to #13 and #59 

![2016-03-22 12_45_04-unbenanntes projekt hdv 720 24p - openshot video editor](https://cloud.githubusercontent.com/assets/17052830/13950862/b6217f6c-f02d-11e5-980a-eae707b36716.png)

**Comment by LiquidOctarine** [comment]
I use Windows 10 (64 bit), and I get the same error.  It sometimes pops up when I'm trying to render a video.  At first the program was working great, now it's 100% unusable because of this error.

I have tried it on two separate machines, both with the exact same error.  It's impossible to use this because of this error.

**Comment by mov51** [comment]
same error version 2.10, windows 10 64 bit. happens when i put a video in the editor

**Comment by oookotooo** [comment]
everytime i do rightclik it show me this error
http://joxi.ru/LmG0l83HOwBp2l

**Comment by jreynojustin** [comment]
OpenShot is now in Version 2.2 if you are still noticing issues in the latest version please re-open this issue letting us know.
