### ISSUE TITLE
video randomly fades to black and fade out effects disappear (when rendered)

### ISSUE THREAD

**Issue by bobbelli** [OpenShot/openshot-qt#1312]
**System Details:**
* Operating System / Distro: windows 10
* OpenShot Version: 2.4.1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
when i have edited my video and i render it it randomly loses fade out effects and
randomly fades out (sometimes)
it only sometimes does this, on the latest edit i have done it
took me 3 tries to get it looking presentable.
still it had lost some fade out effects

i have uploaded these videos to my youtube channel
as private
(both i have 2, 1 with random fade out mid video and another one with the fade out effects)
VIDEO 1: RANDOM FADE OUT IN MIDDLE (TIME of random fade out: 22-36) its a pause there it was supposed to be the clip after the black screen. 1.09 random fade out its not supposed to be there and shortly after the music cuts off idk why
LINK: https://youtu.be/UIJ2XePtDxE
*********
VIDEO 2: 
random loss of fade outs ( TIMES where a fade out was supposed to be: 43 when the horse tips head down there was fade out slow.  1.41 fade out slow when the horse was out of the building. 1.55 fade out slow on that last clip. 2.00 fade out slow on the music.
LINK: https://youtu.be/b9xFWBs0j9c

i sorta wrote a novel in here there was just so many problems.
i dont know if its the frame rate of the camera and my exporting fps idk it might be that
CAMERA: iphone 5s (my mom shot it so idk the settings)
exporting guality and fps:
guality: normal
resolution: 720p
fps: 50

**Comment by peanutbutterandcrackers** [comment]
@bobbelli - Haha. Those are some nice videos. I really like the pump-up music. :+1: 
First and foremost, it could be the video profile issue, too. So, if the footage was shot at 24fps and one edits it using 25fps profile, it has some of these weird issues.
Secondly, if it is not the first issue, could you post a screenshot of the project timeline so that we can see and better help you? Esp. the part where it is fading in and out randomly.

You're probably cutting the clips into smaller chunks and using right click > Fade > Fade In/Out to achieve the effects, right? A look at your project timeline would really help us understand what's wrong.

**Comment by bobbelli** [comment]
umm i deleted the project but i was not shortening the clips but i was using the fade out effects (right click)

**Comment by peanutbutterandcrackers** [comment]
I think that is where the problem lies. So, in order to have fades in the middle of the clips, there are two ways:
i. Either cut the clip at that point and use the Right Click > Fade > .... method
ii. Use Alpha Keyframes

Actually, keyframes are where OpenShot really shines at. You might want to look at the following video tutorials so that the next time around, your video project in OpenShot will be absolutely awesome:
1. Introduction to Keyframes: https://www.youtube.com/watch?v=YRtdCK9ZDUQ
2. Basic Animation: https://www.youtube.com/watch?v=P3zIprwr1rk&t=1s
3. More about Keyframes: https://www.youtube.com/watch?v=mgi4esWA84M&t=298s
4. Zooming with Keyframes: https://www.youtube.com/watch?v=nEyrC1v-M1s&t=18s
5. OpenShot User Guide (for all the properties that are keyframe-able): https://www.openshot.org/static/files/user-guide/index.html

Hope you create awesome videos with OpenShot!
