### ISSUE TITLE
OpenShot Video Player will not open on Windows 10 64bit

### ISSUE THREAD

**Issue by gusax42** [OpenShot/openshot-qt#1319]
**System Details:CHUWI Lapbook 15, Atom x5-Z8350, 64Gb eemc HDD, 4Gb ram
* Operating System / Distro: Windows 10 64bit
* OpenShot Version: 2.4.1-x86-64
* _Please attach log files if crash_

**Issue Description and steps to reproduce: Click on the OpenShot shortcut as administrator or standard user in Windows 10 64bit and it just give this error message and did not allow Open Shot Video Editor to open and run.

cx_Freeze: Python error in main script

Traceback (most recent call last):
File "C:\Program Files\OpnShot Video
Editor\classes\json_data.py", line 143, in write_to_file
with open(file_path. 'w') as f:
PermissioError: [Errno 13] PErmission denied:
'C:\\Users\\user\\.openshot_qt\\openshot.settings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "C:\Program Files\OpenShot Video Editor\classes\app.py",
line 85, in_init__
self.settings.load()
File "C:\Program Files\OpenShot Video Editor\classes\settings.py", line 148, in write_to_file raise Exception(msg)
Exception: Couldn' save user settings file:
[Errno 13] Permission denied:
'C:\\Users\\user\\.openshot.qt\\openshot.settings'

During hadnling of the above exception, another exception occurred:

Trace back (most recent call last)
File
"C:\msy64\mingw64\lib\python3.5\site-packages\cx_Freeze-5.0-
py3.5-mingw.egg\cx_Freeze\initscripts\consol.py", line 21, in
<module>
File "openshot_qt/launch.py", line 77, in <module>
File "openshot_qt/launch.py", line 70, in main
File "C:\Program Files\OpenShot Video Editor\clesses\app.py",
line 88, in_init__
exit()
NamError; name 'exi' is not defined

![openshot](https://user-images.githubusercontent.com/36912125/36772946-49e11d4c-1c92-11e8-8d80-62e6af705e14.png)

**Comment by peanutbutterandcrackers** [comment]
Could you please try deleting the .openshot_qt folder? It is the only other thing that has worked for others apart from running as admin and/or non-admin user. I hope that helps.....

**Comment by DylanC** [comment]
@gusax42 - Yes, delete the preferences folder. This should resolve your issue.

**Comment by EdwardTheGamer2005** [comment]
Hello,im having the same problem,but i tried deleting the openshot.qt but when i open the software,the folder still reappears,so that solution doesn't work.I really need this thing fixed,because im working in a project and i need a good video editor that doesn't export videos with watermarks!

**Comment by lauraros** [comment]
same issue

**Comment by David263** [comment]
Similar issue: deleted openshot.qt and error still happens when clicking a link for OpenShot--just suddenly started happening. Error message at end of stack: "Permission Error: [WinError 5]: Access is denied: %USERPROFILE%"

Important: when I issue the same command as in the link ("C:\Program Files\OpenShot Video Editor\launch.exe") in an admin console, it works: it opens OpenShot.

Please fix, thanks.

**Comment by ferdnyc** [comment]
@David263 The problem is that it's a permission problem on your local computer, which is not something we can easily fix. Completely deleting the `.openshot_qt` folder in your home directory _should_ fix it, because OpenShot will automatically re-create that folder on startup. The only way that would fail is if your user account doesn't have permission to create folders in your own home dir. The fact that running it as an admin succeeds would seem to confirm that, but it also may be making the problem worse: when run like that, OpenShot will create an `.openshot_qt` folder that's owned by Administrator, which will definitely prevent it from writing to that folder as a regular user.

If you could try one thing for me, it might help us get a better handle on this problem: Could you completely delete the `.openshot_qt` folder in your home directory, empty the trashcan to make sure it's been removed, and then CREATE that folder — right in your `C:\Users\username\` folder and with the exact same name — before running OpenShot? All of this needs to be done from your regular account, WITHOUT admin privileges, and OpenShot needs to be completely stopped before you do it. (You may want to use the Task Manager to make sure, or restart the computer first.)

That _should_ fix the permissions issue starting OpenShot as a regular user, and if it does maybe we can add some tools to the Windows installer to optionally reset permissions. (We just have to figure out how to do it without creating the same problem, since the installer runs as Administrator.)

**Comment by Liniik** [comment]
I solved it by deleting the said folder BUT there is one big change when is automatically created after that - it doesn't have "hidden" attribute in Properties, it is normally visible folder. WHEN I hide it, I get this error. So keep it "unhidden" and it should work.

**Comment by HJFR** [comment]
Hello all. 
I had similar issue and nothing resolved. I have identified my root cause as being the Antivirus protecting the path c:/Users 
I had to enable the option to trust the application. 
As soon I have change that setting in the antivirus the application started to run without issues.
