### ISSUE TITLE
text is truncated and thumbnails is to big in detailed view

### ISSUE THREAD

**Issue by nwgat** [OpenShot/openshot-qt#134]
![http://i.imgur.com/zZdrBsN.png](http://i.imgur.com/zZdrBsN.png)

ubuntu 15.10
latest openshot from daily ppa

**Comment by komackaj** [comment]
I wasn't able to reproduce the thumbnail bug - this happens when first frame of video is black, may that be the problem?

Openshot still cuts names in current master 9e5c4375. The source is here
https://github.com/OpenShot/openshot-qt/blob/9e5c437535700278de6a6b96c50e9cf3e35da7d9/src/windows/models/files_model.py#L197
(same logic on Ln189 for thumbnails). I believe the reason is that columns are autoresized using
https://github.com/OpenShot/openshot-qt/blob/9e5c437535700278de6a6b96c50e9cf3e35da7d9/src/windows/views/files_treeview.py#L303 and it would cause display problems with long names.

IMHO the right way would be pass full data to setText and let QTreeView do the hard work of shortening text column overlaps, which it does automatically. The only two problems are to persuade FilesTreeView to set initial columns width (which should be easy) and not to autoresize them on new file addition (not so easy as I've found out). Unfortunately I don't have enough QT skills to make it work the right way, maybe someone else will.

**Comment by DylanC** [comment]
@nwgat - Does this issue occur on OpenShot 2.3.4?

**Comment by DylanC** [comment]
Unable to reproduce this issue on the daily build.
