### ISSUE TITLE
How to mute the sound in a certain place in the video? openshot 2.4.1

### ISSUE THREAD

**Issue by donkikhot** [OpenShot/openshot-qt#1343]
**System Details:**
* Operating System / Distro: Ubuntu 16.04
* OpenShot Version: 2.4.1

**Comment by donkikhot** [comment]
Probably I hurried, I'll study in detail!

**Comment by donkikhot** [comment]
Apparently such a parameter is missing

**Comment by DylanC** [comment]
@donkikhot - Why does your version say 2.3.4? This is an out of date version of Openshot. You should try either the v2.4.1 or v2.4.1 daily build.

**Comment by peanutbutterandcrackers** [comment]
@donkikhot - Hey there, again!

First and foremost, please use OpenShot v2.4.1. It is the latest stable release. Or, if you're feeling even more adventurous (as I presume is more likely), please use the latest daily build. 

[Daily Builds](https://github.com/OpenShot/openshot-qt/releases/tag/daily)
[PPA](https://www.openshot.org/ppa/)

And, once you're using v2.4.1 or the daily PPA, right click on the clip, click 'properties'. On the properties tab that will open to the side of the timeline, you should find a 'volume' property that can be changed (keyframe-able, actually). You can have the volume go from silent to loud within a certain time. You can have it change using various curves too.

You might want to look up 'OpenShot Keyframes' on youtube and also look at the user guide at openshot.org. I guarantee you that you'll fall in love with OpenShot once you get the hang of keyframes and how to use them in OpenShot. The possibilities are virtually limitless!

**Comment by DylanC** [comment]
@donkikhot - A simple method would be to cut the clips on the start and end of the video. On the middle clip you can right click and set audio level to 0%.

**Comment by donkikhot** [comment]
> @donkikhot - Why does your version say 2.3.4? 

Misprint

> @donkikhot - A simple method would be to cut the clips on the start and end of the video. On the middle clip you can right click and set audio level to 0%.

Then the video will break, and I need to mute the sound in the video in a certain place and let the sound from the other track where the music is attached

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Any ideas about this? Not sure if this is possible yet.

**Comment by peanutbutterandcrackers** [comment]
It is possible, actually, yes.

Here is how:

Right click on the video in the time line and click on 'Properties'. A tab will appear to the left of the time line.
![screenshot from 2018-03-07 15 42 39](https://user-images.githubusercontent.com/26764547/37085879-4b1ce844-221e-11e8-9d27-3a7d97e46d49.png)

Drag the play head to the point where you want to mute the audio. (Use the arrowed keys to step frame-by-frame.) Click on the 'volume' property and set it to 0. A green marker will appear on the clip at that point. It's a keyframe. Volume keyframe.
![screenshot from 2018-03-07 15 45 15](https://user-images.githubusercontent.com/26764547/37086085-ce921cbc-221e-11e8-8dd0-c5ecffd531f9.png)

If you play it now, you'll see that the volume fades out gradually from the start of the clip, and turns completely silent at the point where you set the volume to 0. Probably not what you want.

If you take a look at the 'Volume' tab, you'll see that there is a graph on the right side. This is quite important.
![screenshot from 2018-03-07 15 53 58](https://user-images.githubusercontent.com/26764547/37086476-c8880aec-221f-11e8-8b56-6089b12d354a.png)

Go back to the *exact frame - the exact key frame - * where you set the volume to be 0. You'll know you've reached that point when the 'volume' property turns green.
![screenshot from 2018-03-07 15 56 35](https://user-images.githubusercontent.com/26764547/37086631-2416cd1c-2220-11e8-8f71-9168f7e24d9a.png)
![screenshot from 2018-03-07 15 57 06](https://user-images.githubusercontent.com/26764547/37086660-369597fc-2220-11e8-8a01-8dab9cd8ebb1.png)

Now right click on the graph in the 'volume' property. Select 'Constant'.
![screenshot from 2018-03-07 15 59 20](https://user-images.githubusercontent.com/26764547/37086791-90eadbae-2220-11e8-8c68-dd06ccbc7ec5.png)
Please note that I am on the same exact frame (keyframe) where I set volume to 0. It's just that because it is selected, it looks blue instead of green.

The 'volume' property thingy now looks like this:
![screenshot from 2018-03-07 16 00 15](https://user-images.githubusercontent.com/26764547/37086835-af5bfafa-2220-11e8-9bf1-2e8d482302b7.png)

Now if you play the clip from the beginning, you should see that right at that point, the volume shifts from 1 to 0, thereby achieving what you wanted.

Hope that helps!

P. S: You should totally look up 'OpenShot Keyframes' and read the [user guide](https://www.openshot.org/static/files/user-guide/index.html) too. 
P. P. S: The greatest power of OpenShot is keyframes. Please do learn to harness it. :)

**Comment by donkikhot** [comment]
> P. S: You should totally look up 'OpenShot Keyframes' on YouTube and read the user guide too.
P. P. S: The greatest power of OpenShot is keyframes. Please do learn to harness it. :)
Thank you all very much, have made for Google more informative)

**Comment by DylanC** [comment]
@peanutbutterandcrackers  - Wow, this was really great! @donkikhot - Hopefully this fully answers your question.

**Comment by peanutbutterandcrackers** [comment]
Yeah. OpenShot is really powerful once you know how to use keyframes. :+1:

**Comment by DylanC** [comment]
@donkikhot - Closing this question as answered. Thanks again @peanutbutterandcrackers

**Comment by peanutbutterandcrackers** [comment]
@DylanC - You're most welcome! :)

**Comment by dsmurl** [comment]
volume contorl doesn't work in 2.5.1.  When I click a clip, change the volume to 0, hit enter, click off the clip, then click back on the clip, the volume is back to 1.  It doesn't apply the volume changes.  Or any other changes for that matter.

**Comment by Colorjet3** [comment]
hello @dsmurl You may want to upgrade to 3.2.x.  
If running Windows (10 or 11)
a.  Close OpenShot if running.
b.  Make a backup of c:\users\username\.openshot_qt folder.  Please label this backup as 2.5.1 so in case you need to go back to 2.5.1 you need to restore this.
c.  Delete c:\users\username\.openshot_qt folder.
d.  Uninstall Openshot using add or remove programs.
e.  Go to openshot.org/download/#daily and download the latest dev daily build available.
f.  Install it and try the audio mute option.

If running Linux:
a.  Close OpenShot if running.
b.  Make a backup of /home/username/.openshot_qt folder.  Label this as 2.5.1 in case you need to go back to 2.5.1.
c.  Delete /home/username/.openshot_qt folder.
d.  go to openshot.org/download/#daily and download the latest dev daily build AppImage.
e.  Make the AppImage executable and run it.
f.  Try the audio mute option.
