### ISSUE TITLE
Exported mp4 has no audio

### ISSUE THREAD

**Issue by Geoff0627** [OpenShot/openshot-qt#1347]
**System Details:**
* Windows 7 Home Premium
* OpenShot Version: 2.4.1 
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

I edited an mp4 video down to a 58-second clip from the original 1 hr. plus source file. The final product's video and audio (audio from the source file) play perfectly inside OpenShot. However, when I export the 58-second product to my desktop and try to play it, the video plays flawlessly but there is no audio. How can I fix this problem?

**Comment by Geoff0627** [comment]
Thank you for your helpful reply, sir. In fact, even before receiving your
reply I did changing the Target which did in fact bring back the sound for
me. I do appreciate the links to VLC and handbrake. Both of these tools are
new to me as are video editing in general and OpenShot in particular. I am
pleased to be able to count them among my resources thanks to your
courtesy. OpenShot too seems to me to be a wonderful editor. I'm sure I
will be even more impressed as I continue to work with it and learn to
appreciate its subtleties.

I'm sorry it took me these few days to get back to you. I've been a little
off my game lately. In closing, I would just like to note that your
courteous and well-worded writing style reminds me of someone I once knew
from another board. He went by the username of The Magistrate. Of course
you don't have to answer, but I'm just wondering if you are he. :-)

Skype Name: ed.frank0627

**Comment by peanutbutterandcrackers** [comment]
@Geoff0627 - I am glad that I could be of some help to you, good sir. No, sorry, I am not The Magistrate. It probably is just mere coincidence (and the unhealthy amount of Victorian Era novels that I often comfort-read) that our language seems to be the same.
I hope you create awesome videos using OpenShot. And, since you're saying that you're new, please allow me to point you towards some tutorials that should help you out a lot.
1. [Tutorials by Mr. Jonathan Thomas - the creator of OpenShot](https://www.youtube.com/watch?v=1k-ISfd-YBE&list=PLymupH2aoNQNezYzv2lhSwvoyZgLp1Q0T)
2. [OpenShot Keyframes](https://www.youtube.com/results?search_query=openshot+keyframes) Keyframes are the forte of OpenShot. And learning to use keyframes will provide you with limitless creative possibilities.

I hope you continue to love and support OpenShot, too. God bless you. :)
