### ISSUE TITLE
File issue.

### ISSUE THREAD

**Issue by BeastlierCat214** [OpenShot/openshot-qt#1350]
Operation System: Windows 10
OpenShot version: 2.4.1
My export video file (which was downloaded from Panzoid) doesn't seem to show and video. But it works fine when I view the clip from the file itself.

**Comment by BeastlierCat214** [comment]
But how do I change the video's media player? Because it was downloaded from Panzoid.

**Comment by peanutbutterandcrackers** [comment]
So, apparently, in Panzoid you create custom intros and stuff and you download that, right? What is the extension of the downloaded file? Is it a .mkv? .mp4?

I wonder if it is only not showing in the preview in OpenShot, but will render out fine?

Or else, you could transcode the Panzoid video into another format (preferably an Open Format like .MKV) using [Handbrake](https://handbrake.fr/) and maybe then use the converted file and edit it with OpenShot? Perhaps that'll do it?

**Comment by peanutbutterandcrackers** [comment]
Also, just in case, you might also want to try out the latest [daily build](https://github.com/OpenShot/openshot-qt/releases/tag/daily) of OpenShot. A user has reported that the daily build works better than v2.4.1 on Win 10.

**Comment by gary9872** [comment]
Panzoid actually is very open source in its files: Container MKV lavf encoder (rather old version), Video VP8 and PB your 'favourite' audio codec opus. 

That being said there is an issue with the video encoding that openshot doesn't like. It is not the video codec itself, but somehow it wasn't properly used.  Suprisingly the opus audio works fine. 

So like PB said try Handbrake or if you are okay with command line and ffmpeg you could do the following

 ffmpeg -i panzoidvideo.mkv -c:v libx264 -c:a copy panzoidfixed.mkv

I used x264 because VP8 is really slow on ffmpeg

**Comment by BeastlierCat214** [comment]
It has worked using Handbrake but it seems that the audio will stutter a bit

**Comment by peanutbutterandcrackers** [comment]
I think the audio stuttering is only in the preview. If you export it out, it should render out just fine. (Has happened to me too before) Hope that helps!
