### ISSUE TITLE
Time Stamps Incorrect  while watching in OpenShot preview window

### ISSUE THREAD

**Issue by gary9872** [OpenShot/openshot-qt#1355]
Time Stamps seem to jump in regards to profile selected

ie 25fps ... starts at 0 seconds count good until 25 then jumps to next minute
60fps start at 0 seconds counts to 60 not 59. then goes to next minute

https://youtu.be/NNJ9VuPj6VA

AMD Ryzen 1600
Arch Linux
* OpenShot Version: 2.4.1

**Comment by peanutbutterandcrackers** [comment]
The time stamp actually goes Hrs:Min:Sec:Frames. Maybe that is causing some confusion. Do you think there's a better and more intuitive way of displaying the time?

**Comment by gary9872** [comment]
Yes absolutely.

Thank you for the clarification. That makes perfect sense now.

**Comment by gary9872** [comment]
Yes absolutely.

Thank you for the clarification. That makes perfect sense now.

**Comment by peanutbutterandcrackers** [comment]
@gary9872 - I'm glad I could be of some help. Do you have any suggestions as to how this could be made more clear to the end user?

**Comment by N3WWN** [comment]
Frame numbers would probably be more accurate, esp since there are some of us who are requesting frame-by-frame editing features.

I have a video loaded with 29.97 fps, my project is 29.97 fps.  If I move the playhead to 00:00:21:30 and hit the right arrow, the playhead is now at 00:00:21:31.  Another frame to the right and the playhead is now at 00:00:22:02.

This would intermingle with another comment I left a little bit ago about how keyframes need to be stored in order to retain their meaning at various frame rates.  I'm not 100% sure what the best solution is for this right now.... one of the two units needs to be interpolated and the other exact.  

It is not possible for both to be exact in all situations, unless the clip frame rate and project frame rate are equal and/or whole numbers which result in 1 or 2 decimals to be accurate.

For instance, frame rates like 0.5 fps, 1 fps and 10 fps can be displayed exactly as both time and frame number, but frame rates like 23.97 fps, 29.97 fps, 30 fps and 59.94 fps cannot without introducing a bunch of decimals after the seconds to show the precision necessary.

If the "time" on the timeline is made smaller (like the track name font and size), both could be displayed.  

What I'm thinking is:  

If there is perfect sync between the two (i.e. at 10 fps), there could be a `=` between them and they could be the same color (bold for the exact value since I can't use color here):

**00:00:01.2 [s] = 12 [fr]**

If the sync is imperfect (i.e. at 29.97 fps), the `=` could be a `~` and the interpolated value could be grey instead of white (italics used to show what is interpolated and bold for the exact value):

**00:00:01.2 [s]** ~ _36 [fr]_
or
_00:00:01.20 [s]_ ~ **36 [fr]**
