### ISSUE TITLE
Waveform cuts off

### ISSUE THREAD

**Issue by MrTertius** [OpenShot/openshot-qt#1359]
**System Details:**
i5 Intel Processor, Integrated GPU, 4GB RAM
* Operating System / Distro: ?
Windows 10
* OpenShot Version: ?
2.4.1
* _Please attach log files if crash_
No Crashes
**Issue Description and steps to reproduce:**
Waveform will not cut off

**Comment by peanutbutterandcrackers** [comment]
As in, an audio isn't being sliced? o.O Some screenshots would help you help you, good sir. For now, my suggestion would be to try out one of the [daily builds](https://github.com/OpenShot/openshot-qt/releases/tag/daily) instead. It seems that there are way too many problems on Windows 10 with v2.4.1. A lot of these issues will be fixed with v2.4.2

**Comment by DylanC** [comment]
Closing until we have more details or screenshots.
