### ISSUE TITLE
Smoother preview playback with proxies

### ISSUE THREAD

**Issue by philiplb** [OpenShot/openshot-qt#1380]
Hi,

in Blender, you can setup proxy files for smoother preview playback. It is a bit too manual there, but it gets the job done. For complex stuff, this comes in handy.
Checkout https://www.youtube.com/watch?v=KZl1xS9Lmvw

(Sorry for the many feature requests. I don't want to be demanding, just things coming into my mind.)

**Comment by peanutbutterandcrackers** [comment]
@philiplb - Thanks for all the ideas. Hope you stick around and continue to help/love/support OpenShot. Yes, proxies would be awesome too. But since we currently have only one active developer and only 2 active contributors, it might take a while before this is actually implemented, though..
But still, this would be awesome for sure!
