### ISSUE TITLE
Struggles when showing waveform (could be just me)

### ISSUE THREAD

**Issue by ghost** [OpenShot/openshot-qt#1389]
**System Details:**
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1
* _Please attach log files if crash_

I am not sure of how to label this as a question more than a request.

When I ask Openshot to show the waveform, it does...but it struggles with each subsequent action of any kind.
I am not sure if this is relevant, but maybe the file size or initial video length is to blame? Again, I could be wrong.

**Comment by EXEFake** [comment]
Please pardon the double-post, but I actually managed to crash it. Here is the log.
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/1821289/openshot-qt.log)

**Comment by peanutbutterandcrackers** [comment]
Because you are using win 10 and many problems have been reported with win10, I'd like to suggest you to try out a latest [daily build](https://github.com/OpenShot/openshot-qt/releases/tag/daily) to see if it works any better. A user recently did report that the latest daily build worked a lot faster and was more responsive/stable. Worth a shot, I think.

Thank you for the log too. It will help the devs fix this issue as soon as possible. v2.4.2 should be a lot more stable - esp. on windows platforms.

@N3WWN - Perhaps you could take a look at this too, good sir?

**Comment by EXEFake** [comment]
Okay, I see the page, and a most of them, especially towards the bottom, read 2.4.1-8 and 2.4.1-9. Do I just grab the latest one compatible with Windows?

**Comment by peanutbutterandcrackers** [comment]
Yes. The latest one compatible with windows. :)

It will be updated within a few hours of *any* change made to the OpenShot source code. So, please do try out the latest version(s) of the daily build.

Hope that helps!

**Comment by DylanC** [comment]
@EXEFake - I think the waveform generation is slow in general. Something that should be fixed.

**Comment by N3WWN** [comment]
So, is the issue here that the **generation** of the waveform data is too slow, or that OpenShot slow **after** waveforms are shown?  

Also, which waveforms?  

The waveform that is shown in the timeline (useful when syncing clips from different cameras with the same audio) or the waveform that is shown in the final output and visible in the preview window?

Either way, I'd suggest trying a daily build newer than about Apr 17th as there was a lot of performance related improvements that were put into OpenShot around that time.

**Comment by DylanC** [comment]
@N3WWN - I think its the generation of it **and** after they are shown. :laughing: 

The waveforms we are talking about are the audio ones when you right click>>Show waveform. (or something like that from what I remember)

**Comment by N3WWN** [comment]
> I think its the generation of it and after they are shown.

I know that generating the waveforms can take a bit of time, with longer clips taking longer to process the audio, but after the waveform has been generated, OpenShot performs just as fast as it did beforehand.

@EXEFake - Have you had chance to check out a recent daily build to see if the performance gains help with this issue, also?  I don't know if the performance improvement will help with waveform generation, so having that feedback would be very helpful.

**Comment by TharenaMelishka** [comment]
![2019-12-03](https://user-images.githubusercontent.com/9803487/70107051-6ef59780-1613-11ea-895a-22e6b7a71241.png)

So... I just converted one segment to waveform.   It took several minutes and I was about to force close it, but then it popped through.  Please note all my time markings switched to this stylish screenshot ones as soon as it finished rendering the waveform.  

Not sure the version but I downloaded it and installed November 6 2019, so whatever the most recent version was then.  I'm assuming the 2018 daily builds would have made it to production by now.... 
Windows 10 latest update.  
No log, because it didn't crash.  I try NOT to crash the program when my projects are that close to render, but I was trying to fix an audio problem... and decided that risking corrupting my project wasn't worth it.  
Thanks!
