### ISSUE TITLE
OpenShot Crashes when Exporting to MPEG (mpeg 2)

### ISSUE THREAD

**Issue by JCannon2018** [OpenShot/openshot-qt#1398]
I have OpenShot installed on Windows 10 Pro, 64-bit, machine.  8 GB RAM, Intel i7-5500U 2.40 GHz.   When I go to export to the MPEG (mpeg 2) profile, the launch.exe application crashes.   I do not know what logs to attach.   

Any suggestions?

**Comment by peanutbutterandcrackers** [comment]
Could you perhaps try exporting in a different profile? If the crash still persists, you might want to follow [these steps](https://github.com/OpenShot/openshot-qt/blob/master/.github/CONTRIBUTING.md) to submit the logs.

Also, you might want to try out the latest [daily builds](https://github.com/OpenShot/openshot-qt/releases/tag/daily) and see if this problem also arises in them.

**Comment by JCannon2018** [comment]
Yes, I can export to the MP4 profile without any problems.  I just seem to have problems with the MPEG profile.   I will see about getting the logs.  Thanks for the help.

**Comment by peanutbutterandcrackers** [comment]
I see. Awesome. I hope that issue, too, will be resolved soon. :)

Hope you make awesome videos with OpenShot!

**Comment by janekska** [comment]
I have similar problem on Ubuntu 16.04. and OpenShot 2.4.1.-dev1
The crash is hard - Ubuntu quits.
It happens on:
Profile: Web
Target: YouTube-HD
Video Profile: HD 1080p 25fps (1920x1080)
Quality: Hight

I tried to collect some debug info as written in link above:
![ekranattels 2018-03-22 22-21-05](https://user-images.githubusercontent.com/7089760/37796779-bc7d0736-2e20-11e8-886d-ba3d3b750c69.png)
Restarted and did crashing work again, but found no log files... :(

**Comment by peanutbutterandcrackers** [comment]
@janekska - Can you export using other profiles? o.O

**Comment by janekska** [comment]
Yes I can.
I did not tried on all yet, but I have couple successful exports using Youtube, VGA NTCS(640x480), average qality.

Could it be connected with low system resources (pc is quite old and I got similar hard system crashes on larger HD video editing.) ?

**Comment by peanutbutterandcrackers** [comment]
Could be so, too...

@DylanC @ferdnyc - Any ideas? o.O

**Comment by ferdnyc** [comment]
Not without seeing logs, no.

I updated the CONTRIBUTING document (which was linked to above) with a more detailed explanation of where the logfiles can be found. Until that change makes it to the main source, you can [see my updated version here](https://github.com/ferdnyc/openshot-qt/blob/3b9b4a4daa9afb93c6dc119eb00d67df98508a23/.github/CONTRIBUTING.md).

We'd really need to see logfiles to get an idea of the problem. Also, please be sure to follow the procedure outlined there: _delete_ the logfiles, immediately reproduce the bug as efficiently as possible (no extra or unrelated steps), then post or copy the logfiles before using OpenShot further. Otherwise the logfiles will be huge and full of unnecessary output, which makes it harder for us to locate the problem.

**Comment by janekska** [comment]
Log files attached in archive (huge anyway).
[openshot_qt_logs.tar.gz](https://github.com/OpenShot/openshot-qt/files/1861269/openshot_qt_logs.tar.gz)

**Comment by peanutbutterandcrackers** [comment]
*waits for @ferdnyc to see the logs*

**Comment by janekska** [comment]
Yes there was a lot of clips, but there are just two videos clipped into 5-7 parts, but all others are photos.
Yes I can export at lover quality - see above in some previous post.

I'll try to reduce project complexity.
I had have similar crash with not so complex videos/clips, but HD or even more as a source - one clip with some cut-outs.

Hm, probably I should look in some system logs, because finally it is system crash/exit.
Could you help with that - which files to look?

System info here in screenshot:
![ekranattels 2018-03-30 14-43-28](https://user-images.githubusercontent.com/7089760/38137489-8d0a2f48-342d-11e8-8504-900f23bd30db.png)

**Comment by ferdnyc** [comment]
Ohhh, sorry, I'd overlooked or not understood this:

> The crash is hard - Ubuntu quits.

If the _system_ is going down, then yeah the OpenShot logs wouldn't show anything because it's not getting the chance to write them. Sorry about the wild goose chase regarding logs. (Though logs from @JCannon2018 would still be useful.)

In my experience, system crashes are almost never _actually_ the fault of the application triggering them. I'm not saying that to shift blame or anything, simply that it means we should look beyond OpenShot itself for the root of the problem. Under normal circumstances, there **shouldn't** be any way for an application to take down the operating system even if it _tries_. (Certainly, not applications written in high-level languages like Python. They don't have access to any critical system internals.)

If the system is freezing/hanging, or spontaneously hard-resetting, there probably won't be any logs anywhere of the problem, unfortunately. Anything that would log an error usually doesn't get the chance to do so. But, those problems are nearly always caused by power problems, cooling problems, or similar physical hardware issue that happens to be triggered by periods of higher system activity.

If the computer is unexpectedly rebooting, or you're getting logged out and thrown back to the login screen, something like that, then the system journal would be the best place to look. 
```bash

# Start at the bottom of the last 5000 lines of the system journal
#   Use PgUp to page backwards
#   Use arrows to scroll, including right/left — long lines don't wrap

sudo journalctl -n 5000 -e

# Start at the bottom of the last 5000 lines of the previous boot
#   That's "boot negative one", meaning "one ago".
#   "-b -2" is the one before that, etc.
#   "-b 0" is the logs since the system booted

sudo journalctl -n 5000 -b -1 -e

# More info on the journal
man journalctl
```

There may also be user session logs, but I have no idea where those would live in Ubuntu, sorry. Session logs are less likely to contain any useful data. System crashes => system logs.

**Comment by janekska** [comment]
Thank you - so I found, that it was not a OpenShot problem, but some hardware cooling problem.

**Comment by ferdnyc** [comment]
@janekska, glad to hear you tracked it down! Those things can be a real pain.

**Comment by ferdnyc** [comment]
@DylanC : That close might be premature, @JCannon2018 was the original reporter. They haven't responded yet, but it's only been a couple of weeks.

**Comment by JCannon2018** [comment]
I am sorry, all.  Things have been crazy.   I am able to use another profile to create/export video, but the MPEG one crashes every time.  I will work on getting logs ASAP.   Again, sorry for the delay.

**Comment by DylanC** [comment]
@ferdnyc - Oh right. I thought that was the original reporter. Reopened. :)

**Comment by peanutbutterandcrackers** [comment]
@JCannon2018 - [This guide](https://github.com/OpenShot/openshot-qt/blob/master/.github/CONTRIBUTING.md) should be of help, good sir!

**Comment by JCannon2018** [comment]
Peanut....

Much thanks.  I have attached the log files, per those instructions you sent.   This is for when OpenShot crashes when I try to export to an MPEG file.

[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/1924191/openshot-qt.log)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/1924192/libopenshot.log)

**Comment by peanutbutterandcrackers** [comment]
Thanks! I have notified a developer. Perhaps he'll see about this issue, soon. :)

**Comment by ferdnyc** [comment]
Unfortunately, once again, there's very little in the logs. Certainly, nothing in the way of information _about_ the crash. The `libopenshot.log` file ends abruptly, right after it creates the first 8 frames of the output video.

These lines:
```
FFmpegWriter::process_video_packet (frame->number=1.0000, bytes_source=1382400.0000, bytes_final=518400.0000)
FFmpegWriter::process_video_packet (frame->number=2.0000, bytes_source=1382400.0000, bytes_final=518400.0000)
FFmpegWriter::process_video_packet (frame->number=3.0000, bytes_source=1382400.0000, bytes_final=518400.0000)
FFmpegWriter::process_video_packet (frame->number=4.0000, bytes_source=1382400.0000, bytes_final=518400.0000)
FFmpegWriter::process_video_packet (frame->number=5.0000, bytes_source=1382400.0000, bytes_final=518400.0000)
FFmpegWriter::process_video_packet (frame->number=6.0000, bytes_source=1382400.0000, bytes_final=518400.0000)
FFmpegWriter::process_video_packet (frame->number=7.0000, bytes_source=1382400.0000, bytes_final=518400.0000)
FFmpegWriter::process_video_packet (frame->number=8.0000, bytes_source=1382400.0000, bytes_final=518400.0000)
```

_should_ normally be followed immediately by eight corresponding `FFmpegWriter::write_video_packet` lines, and then the export process would move on to frames 9+. That very, very last step in exporting the first 8 frames (`FFmpegWriter::write_video_packet`) is missing from the end of the log.

So, that it crashes at precisely **that** point feels like it's probably both significant and useful. Hopefully @jonoomph has seen export processes that terminate precisely at the point of the first write attempt, or something similar. Maybe he'll be able to provide some insight into what's causing the crash, based on that information.

**Comment by DylanC** [comment]
@JCannon2018 Can you try v2.4.2 and let us know if you have any success?

**Comment by JCannon2018** [comment]
Tried converting a MOV to MPEG2 on v2.4.2.  Still crashing.   No error windows.  The program just closes.

**Comment by peanutbutterandcrackers** [comment]
@JCannon2018 - Good sir, could you please [attach the logs](https://gist.github.com/peanutbutterandcrackers/d84c257e74b72d8b06b4daffaebc5a14) for the crash with version 2.4.2? That should help the devs fix the issue.

Also, if you are only going to transcode your videos, [HandBrake](https://handbrake.fr/) might be a tool better suited for this purpose.

**Comment by peanutbutterandcrackers** [comment]
@JCannon2018 - Good sir, could you please [attach the logs](https://gist.github.com/peanutbutterandcrackers/d84c257e74b72d8b06b4daffaebc5a14) for the crash with version 2.4.2? That should help the devs fix the issue.

Also, if you are only going to transcode your videos, [HandBrake](https://handbrake.fr/) might be a tool better suited for this purpose. But please do attach the logs, nevertheless.
