### ISSUE TITLE
Preview still out of sync with audio

### ISSUE THREAD

**Issue by MrTertius** [OpenShot/openshot-qt#1409]
**System Details:** Intel i5 Processor, Integrated GPU, 4GB RAM
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1-52
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
I have recorded a Video in 30FPS and the preview is still out of sync with the audio

**Comment by peanutbutterandcrackers** [comment]
Are you sure your editing profile is currently set to one that uses 30 frames per second? o.O

**Comment by MrTertius** [comment]
Yes, it is set when i launch openshot

**Comment by MrTertius** [comment]
Wait a second, i recorded 2 Videos in a different encoding option, the one was recorded in x264 and the other one was recorded in Quicksync H.264, the one with the x264 encoding sync perfectly, maybe Openshot does not support Quicksync Encoded Videos

**Comment by peanutbutterandcrackers** [comment]
Strange, when I launch OpenShot, the default is [HDV 720 24p]

@DylanC @ferdnyc - Does Openshot not support Quicksync Encoded Videos? o.O

@MrTertius - Perhaps you'd like to use something like [HandBrake](https://handbrake.fr/) to transcode the video and then import it into OpenShot, for now?

**Comment by ferdnyc** [comment]
QuickSync isn't a _format_ or even an _encoding_, it's a *codec* for doing GPU-accelerated encoding and decoding on Intel systems. IOW, "QuickSync encoded videos" aren't technically a thing: any video files produced using the QuickSync encoder **SHOULD** be standard videos encoded in whatever format it's set to output (in this case. H.264/AVC). The file produced would most accurately be described as "MPEG-4 AVC video encoded by QuickSync", in contrast to the other file which is "MPEG-4 AVC video encoded by x264".

In theory it would even be possible to have x264 and QuickSync generate identical video files, the QuickSync codec should simply do it a bit faster. In practice, of course, there are thousands of variables that affect the output of their encoding, and they'll never be identical. But they should be _supported_, because MPEG-4/AVC is supported and they're both _supposed_ to be standard MPEG-4/AVC.

I'm unsure if OpenShot _uses_ QuickSync for either decoding or encoding, on Windows. I didn't think the support for hardware acceleration was there yet. But I can't be _sure_, because the [FFMpeg QuickSync doc's 'Windows' section](https://trac.ffmpeg.org/wiki/Hardware/QuickSync#Windows) consists entirely of: "(TODO)". **#GeeThanks** 

Regardless, either it does or it doesn't, and if it _does_ it would be using it for **ALL** H.264/AVC videos, including those generated by x264.

So if it makes a difference whether the AVC video was encoded using x264 or QuickSync, then there are two possibilities:
1. The QuickSync-encoded file _**does**_ contain a valid, standards-compliant MPEG-4 Part 10 (H.264/AVC) video stream. But something about the way it's formatted triggers a bug in ffmpeg and/or OpenShot, so they fail to process it correctly. That same something isn't present in the x264-produced video, so that file doesn't trigger the bug.
1. The QuickSync-encoded file _**doesn't**_ consist of properly-encoded H.264/AVC video which fully conforms to the spec, because there's a bug in the encoder which causes it to output malformed data that ffmpeg/OpenShot doesn't know how to handle, or doesn't handle properly.
    (This may apply even if the file plays correctly in other software (e.g. VLC), because that software _does_ know how to handle the bad data output by the QuickSync encoder. Though if that's the case, it may be fixable on the OpenShot side since ffmpeg could be taught to do the same.)

I'd look at whether other software can play the file encoded by QuickSync, whether there are any issues (similar or different), and whether it reports any encoding errors for the file. If it works fine in everything except OpenShot, then it may point to a bug in libopenshot.

QuickSync is relatively young, so ffmpeg's compatibility with the files output by its encoder is probably still evolving. I believe there's work underway to upgrade OpenShot with a more recent version of ffmpeg, which may prove more compatible right out of the box.
