### ISSUE TITLE
[Critical] Chroma Key Drops Performance

### ISSUE THREAD

**Issue by MrTeeXD** [OpenShot/openshot-qt#1412]
**System Details:** Intel i5 Processor, Integrated GPU, 4GB RAM
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1-52
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
When i apply a Chroma Key to clip, the entire Video Editor slows down including the preview window

**Comment by peanutbutterandcrackers** [comment]
Thanks for pointing this out. Hope this will be fixed as soon as possible.

:)

**Comment by peanutbutterandcrackers** [comment]
I think this should be kept open. Also, #1462.

**Comment by MisterTeeXD** [comment]
Issue still exists in all Daily Builds, Awaiting fix.

**Comment by peanutbutterandcrackers** [comment]
To be honest I don't think this will get any resolution any time soon because of all the other issues that need attention. However, I am currently using Image Sequences with with transparency (`png`s) instead of chroma keying. I wonder if this issue should be closed for now as it doesn't give anything concrete but is just a vague observation. I reckon fixing other issues might just fix this one as well. But then again, it is all up to you.

**Comment by mikelacsa** [comment]
The same issue was raised in [2199](https://github.com/OpenShot/openshot-qt/issues/2199)
