### ISSUE TITLE
Add a clip .avi and it's all blak and it plays bad

### ISSUE THREAD

**Issue by Blay3** [OpenShot/openshot-qt#1415]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
Add a clip .avi and it's all blak and it plays bad. I have another clip .flv and it goes perfectly. Any ideas?

**Comment by bnieuwveld** [comment]
Hi @Blay3 - we'll need a few more details in order to help. For example:

* Are you using Windows/Mac/Linux? If so, which version (e.g. Windows 7)
* If Linux - did you download the AppImage from the OpenShot website, or install it through a software centre?
* The version number can be found by going to the Help toolbar menu and clicking About. 

This will be a great start in helping us to help you!

**Comment by peanutbutterandcrackers** [comment]
@Blay3 - An immediate work-around, for the moment, would be to use a transcoder like [HandBrake](https://handbrake.fr/) to transcode your .avi video into something along the lines of .flv or .mkv and importing that into OpenShot to see if that works.

@bnieuwveld - Hey! Good to see you too helping out here! Awesome! :+1:

**Comment by DylanC** [comment]
@Blay3 Can you try v2.4.2 and let us know if you have any success?
