### ISSUE TITLE
M2U00104.MPG cannot be found.

### ISSUE THREAD

**Issue by Heathbrother** [OpenShot/openshot-qt#1416]
Hello,

My little sister made a video for a schoolproject and she saved her video as an .osp file. She excually wanted to save it as an MP4 file. So she called my father and he wanted to open the file, but it gave a pop-up with this: 

> M2U00104.MPG cannot be found.

Does anybody know how to solve this problem?

**System Details:**
* Operating System / Distro: Windows
* OpenShot Version: Downloaded a few days ago the latest version
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by peanutbutterandcrackers** [comment]
OpenShot is complaining because it can't find the M2U00104.MPG file (it is the video she shot from her camera) in the location from where she imported it. For example, if the video was in 'My Videos' when she created the project, it isn't there now.
I think she connected the camera, and didn't copy the video into the computer and was importing it directly from there. If so, go ahead and connect the camera and try opening up the project again. Or, if that is not the case, see *where* OpenShot can't find the file. And put the original file back there. That should fix it.

Also, you can't really save as an .mp4 file. You have to export it. So, .osp is just the project file - one that you can spend 10 days or 15 editing the finest details. And, once you're done, you export the video as an .mkv or .mp4 or .flv and stuff.

You might want to look at [this tutorial playlist](https://www.youtube.com/playlist?list=PLymupH2aoNQNezYzv2lhSwvoyZgLp1Q0T).

**Comment by DylanC** [comment]
@Heathbrother - You would need to put that video file back to its original location. Sounds like you moved the video file or the .osp file was moved. Also follow the advice given by @peanutbutterandcrackers
