### ISSUE TITLE
Razor tool

### ISSUE THREAD

**Issue by maidenvoyager** [OpenShot/openshot-qt#1418]
I am trying to delete a few seconds in the middle of the video. The instructions for the Razor Tool say, "The razor tool cuts a clip wherever you click, so be careful. Easy and dangerous." So, how do you do it? I tried positioning the head at the beginning of the section to be deleted, clicked the Razor tool (which looks like a scissors, by the way, not a razor, which is confusing), moved to the end of the section and clicked again, nothing happened.

**Comment by peanutbutterandcrackers** [comment]
Perhaps you'd like to take a look at [this](https://www.youtube.com/watch?v=BQS2tmgD_Rk&t=16s) video and become a video splitting ninja. Fun Fact: The video is made by Mr. Jonathan Thomas - the creator of OpenShot - himself.

@ferdnyc - It is true that the razor tool looks like scissors. Could you perhaps fix that too, Cap'ain? Sorry for the trouble.

**Comment by DylanC** [comment]
@maidenvoyager - I also answered this question here too #1404.

**Comment by ferdnyc** [comment]
This feels like a documentation issue, to me.

Cutting is a _mode_, not an action, which is activated by the scissors icon. (That icon is the standard user interface icon for "Cut", and there's an advantage to using standard toolkit icons. But we should probably correctly refer to it as the Cutting Mode icon, or something similar, since as noted it doesn't look like a razor.) But Snapping and Cutting are both Mode toggles, which is why they're grouped together on the toolbar, and there are separators between them and the other (action) icons.

Entering Cutting Mode _activates_ the Razor Tool. (As indicated by the cursor changing into a razor — really more of an X-Acto Knife, but let's not quibble — with a dotted vertical line showing where it will operate on the timeline elements.) While in Cutting Mode, clicking the Razor Tool on any Timeline element (clip, transition) will split that element at that point. The playhead isn't involved. 

(The type of splitting that @maidenvoyager was attempting to do, splitting an element at the playhead's current position, can be achieved when **not** in Cutting Mode, by bringing up that element's context menu and selecting "Slice: Keep Both Sides".)

If any of that isn't clear in the documentation, it should be made clearer.

**Comment by ferdnyc** [comment]
> But we should probably correctly refer to it as the Cutting Mode icon, or something similar, since as noted it doesn't look like a razor.)

Including in the icon's tooltip, which currently reads "Razor Tool". That should probably be something more like "Cutting Enabled", to match the Snapping Mode icon's "Snapping Enabled".

**Comment by DylanC** [comment]
@ferdnyc - Yes, I think that naming does make some more sense to the user!

**Comment by ferdnyc** [comment]
We should probably ping @jonoomph for buy-in on these terminology changes, though, since (without having watched it) I'm guessing this would invalidate the language used in his video?

...Also, if there are tutorial videos for UI features, we should probably also think about incorporating those into the user manual. I wonder how difficult ReStructuredText/Sphinx are going make things, if we try to convince them to generate HTML with embedded YouTube videos? I bet pretty damn difficult. Hrm. I'll look into that.

**Comment by maidenvoyager** [comment]
Thanks much! Can you tell I used to be a tech writer? 
For newbies like myself, clear, consistent, and obvious naming is crucial. Because I haven't used many video editors, my tendency is the obvious: click, hold, and move mouse to Select and then "Cut" if I want to Paste it or just Delete if I don't. But it sounds like "Cut" has a different meaning in video editing. The scissors icon also threw me off because it's always associated with cutting.
I'll try again now rhst im not in emergency mode. Thx.


 
 
  On Mon, Mar 26, 2018 at 8:03 PM, Frank Dana<notifications@github.com> wrote:   
This feels like a documentation issue, to me.

Cutting is a mode, not an action, which is activated by the scissors icon. (That icon is the standard user interface icon for "Cut", and there's an advantage to using standard toolkit icons. But we should probably correctly refer to it as the Cutting Mode icon, or something similar, since as noted it doesn't look like a razor.) But Snapping and Cutting are both Mode toggles, which is why they're grouped together on the toolbar, and there are separators between them and the other (action) icons.

Entering Cutting Mode activates the Razor Tool. (As indicated by the cursor changing into a razor — really more of an X-Acto Knife, but let's not quibble — with a dotted vertical line showing where it will operate on the timeline elements.) While in Cutting Mode, clicking the Razor Tool on any Timeline element (clip, transition) will split that element at that point. The playhead isn't involved.

(The type of splitting that @maidenvoyager was attempting to do, splitting an element at the playhead's current position, can be achieved when not in Cutting Mode, by bringing up that element's context menu and selecting "Slice: Keep Both Sides".)

If any of that isn't clear in the documentation, it should be made clearer.

**Comment by peanutbutterandcrackers** [comment]
*braces self for an awesome new PR from @ferdnyc*

**Comment by maidenvoyager** [comment]
Thanks much. I did check out the video. Clearly there's a lot I need to learn about video editing!

**Comment by peanutbutterandcrackers** [comment]
Glad the video was of some help to you!

**Comment by ferdnyc** [comment]
I'd like to see this reopened, the issue of the tool naming / documentation was never addressed.

**Comment by peanutbutterandcrackers** [comment]
@ferdnyc - Right on it, sir! [*braces self for a new PR from you that'll resolve this* :smile: ]

**Comment by ferdnyc** [comment]
Nope, if you'll recall where I left it was:

> We should probably ping @jonoomph for buy-in on these terminology changes, though, since (without having watched it) I'm guessing this would invalidate the language used in his video?

Never heard a peep.
