### ISSUE TITLE
Add shortcuts for moving between clip start/ends/edits

### ISSUE THREAD

**Issue by qubodup** [OpenShot/openshot-qt#1428]
The only way to move quickly on the timeline via shortcut as far as I can tell is SHIFT+LEFT ARROW KEY and SHIFT+RIGHT ARROW KEY for moving to beginning/end of the currently selected clip. (undocumented? https://www.openshot.org/static/files/user-guide/main_window.html#keyboard-shortcuts )

I recommend ARROW UP and ARROW DOWN (which strangely currently start/stop playback like space) to move left or right to the next start/end of a clip or transition or anything on any track.

References of other video editors:
https://helpx.adobe.com/premiere-pro/using/default-keyboard-shortcuts-cc.html
https://shotcut.org/howtos/keyboard-shortcuts/

**Comment by peanutbutterandcrackers** [comment]
Hmm... I agree.

@ferdnyc - Good sir, I think you could surely fix this one, too. :)

**Comment by ferdnyc** [comment]
> The only way to move quickly on the timeline via shortcut as far as I can tell is SHIFT+LEFT ARROW KEY and SHIFT+RIGHT ARROW KEY for moving to beginning/end of the currently selected clip. (undocumented? https://www.openshot.org/static/files/user-guide/main_window.html#keyboard-shortcuts )

Not just undocumented, they're not configured as default keybindings. Shift+Left / Shift+Right have no effect in my OpenShot 2.4.1 install with default keys.

What you're probably seeing are the effects of <kbd>**_Ctrl_**</kbd>+<kbd>←</kbd> and <kbd>Ctrl</kbd>+<kbd>→</kbd>, which are "Previous Marker" and "Next Marker" respectively. (Maybe you reconfigured them to <kbd>Shift</kbd>+<kbd>←</kbd> / <kbd>Shift</kbd>+<kbd>→</kbd>?) They will also jump to the start/end of the currently-selected clip, which are treated as markers.

In #1363 I suggested that keyframes be added to the list of "things treated as a marker", so that Ctrl+Left/Right would let you quickly skip among all of {keyframes, markers, clip boundaries}. I still think that would make sense.

In addition to Prev/Next Marker, there's also Jump To Start/End, which are bound to <kbd>Ctrl</kbd>+<kbd>Home</kbd> and <kbd>Ctrl</kbd>+<kbd>End</kbd> by default. Those will take you to the extremes of the project.

> I recommend ARROW UP and ARROW DOWN (which strangely currently start/stop playback like space) to move left or right to the next start/end of a clip or transition or anything on any track.

<kbd>↑</kbd> and <kbd>↓</kbd> are currently bound as alternate "Play/Pause Toggle" keys, true. There are probably reasons for that, or at least some users who currently rely on one or both of them. Certainly, for quick one-handed video scrubbing it's convenient that you can trigger playback right from the arrow keys cluster. But you can rebind those keys to Prev/Next Marker in the Preferences, if you'd like to use them for that purpose. OpenShot's keybindings are reconfigurable for that reason.

I do still think there should be a shortcut method to move the current clip selection to an adjacent clip. Prev/Next Marker will only move within the bounds of the selected clip. Jump To Start/End move outside the selected clip _without_ affecting the selection, so after using them Prev/Next Marker are still constrained within the same selection. I find this makes Jump To Start/End... not as useful as they could be, in practice.

Whether the selection-change is a separate keybinding, or is implemented by having Prev/Next Marker jump to the adjacent clip after reaching the bounds of the current one, is up for discussion. Also an open question: whether a selection-change keybinding also moves the Playhead, and to where. 

What keys are bound to what shortcuts by default is in some ways an unrelated question, since as I said they can all be configured to the user's preferences. (We should endeavor to make the defaults sensible for most users, though.)
