### ISSUE TITLE
Support elementary OS Icon please 

### ISSUE THREAD

**Issue by torikulhabib** [OpenShot/openshot-qt#1431]
elementary os
I hope support elementary os icon .

**Comment by peanutbutterandcrackers** [comment]
Could you please explain a little further, good sir? Maybe add a few screenshots and stuff? That would really help us help you and/or take your suggestions on board to make OpenShot even better. Thanks!

**Comment by torikulhabib** [comment]
I hope openshot like libreoffice that support icon with elementary os.
![screenshot from 2018-03-29 05-36-50](https://user-images.githubusercontent.com/26135527/38060087-5fccf0ee-3313-11e8-95d5-97c7b2cbe4f6.png)
![screenshot from 2018-03-29 05-38-23](https://user-images.githubusercontent.com/26135527/38060107-7227faf4-3313-11e8-9fa7-10ada9bd8b20.png)
 
![screenshot from 2018-03-29 05-44-27](https://user-images.githubusercontent.com/26135527/38060310-63d696b2-3314-11e8-896a-c9cc5675a6cd.png)

**Comment by peanutbutterandcrackers** [comment]
@ferdnyc - Any ideas, good sir?

**Comment by ferdnyc** [comment]
@torikulhabib How are you running OpenShot? From an Elementary OS package (or third-party package for Elementary?) From the AppImage? Or self-installed?

If OpenShot is **packaged** for the distro, or if it's self-built, and your system theme uses the Elementary icon set, then OpenShot _should_ also use them. If it doesn't, that might be a packaging issue.

If you're running it from the AppImage, only the bundled Humanity icons are used. As far as I know there are no plans to change that, since bundling every possible icon set into the AppImage would be unrealistic.

**Comment by peanutbutterandcrackers** [comment]
I have used OpenShot on elementary OS from the PPA and it doesn't really use elementary icons. Perhaps it is something that has to be added? I know there's a `libreoffice-style-elementary` package that activates elementary icons for LO.

**Comment by torikulhabib** [comment]
i hope there is style icon elementary os for openshot like libreoffice-style-elementary

**Comment by peanutbutterandcrackers** [comment]
Not at the moment, sorry no. But perhaps we can get the elementary team to help out with this? Maybe you could help us out with this? This is, after all, a community-backed project. :)
