### ISSUE TITLE
The program is very slow and it crashes when I try to preview a newly cut video.

### ISSUE THREAD

**Issue by trialism** [OpenShot/openshot-qt#1459]
**System Details:**
* Operating System / Distro: Manjaro?
* OpenShot Version: 2.4.1?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

**Comment by peanutbutterandcrackers** [comment]
Could you please try out the latest daily build? Please head over to the [download](https://www.openshot.org/download/) page and click on 'daily builds'. The latest stable version might work better.

If it doesn't, please follow [this guide](https://github.com/OpenShot/openshot-qt/blob/master/.github/CONTRIBUTING.md) and attach log files so that the devs can actually help you. Thanks!
