### ISSUE TITLE
Openshot Video Editor How to bring back Project File

### ISSUE THREAD

**Issue by AverageAsianJoe** [OpenShot/openshot-qt#1460]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

I don't know how I closed the project file but now I don't know where to go to bring it back.

**Comment by DylanC** [comment]
@AverageAsianJoe - Did you try File >> Recent projects?

**Comment by AverageAsianJoe** [comment]
How do I do that?

**Comment by peanutbutterandcrackers** [comment]
On your OpenShot window, at the top-right, you should see 'File', 'Edit', 'Title', 'View' and 'Help'.
Click on 'File'.
From the drop-down that appears, hover your mouse over 'Recent Projects'.
From the drop-down that appears (to the side), click on the project that you lost.

Please note that if you had not saved the project in the first place, you won't get it back... sadly

**Comment by ayanais** [comment]
Hi! I did the same thing. I was messing around and accidentally closed out the project files panel. I created a github account, because no one could help me and I wanted to help others. On the top it says File, Edit, Title, View, and Help. Click on View. Then go to where it says "Views" on the bottom. Once you go there, hover over it and click on simple view (or advanced if you want it). This should pop the project files panel back up.
