### ISSUE TITLE
Make A Section For Daily Builds Changes

### ISSUE THREAD

**Issue by MrTertius** [OpenShot/openshot-qt#1461]
**System Details:** Intel i5, Integrated GPU, 4GB RAM
* Operating System / Distro: ? Windows 10
* OpenShot Version: ? 2.4.1-53
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
There should be a list or something to display the changes made in the daily builds because I have no idea what has been changed or fixed, I really want to know what has been fixed.

**Comment by peanutbutterandcrackers** [comment]
@DylanC @ferdnyc - I think this is quite a good idea. We could have a place where it will show the [commits](https://github.com/OpenShot/openshot-qt/commits/master) that went into daily build 'X' since daily build 'W'.

@MrTertius - Good sir, at the moment, the best way for you to figure it out would be to look at the [commit logs](https://github.com/OpenShot/openshot-qt/commits/master). Hope that helps!

**Comment by ferdnyc** [comment]
Please don't tag me in every issue that comes by. I have no control over the OpenShot website, or the build generator, and cannot possibly contribute to this.

**Comment by DylanC** [comment]
@MrTertius - Yes, I think you will just need to view the commit logs for now. I don't think more work will be done on this tbh.

**Comment by peanutbutterandcrackers** [comment]
Oopsie. Sorry. I've gotten into the habit of thinking you can solve anything. lol :D
