### ISSUE TITLE
Error Message: invalid load key, '$'.

### ISSUE THREAD

**Issue by PapsOu** [OpenShot/openshot-qt#1468]
**System Details:**
* Ubuntu 16.04
* OpenShot Version: 1.4.3

[openshot.log](https://github.com/OpenShot/openshot-qt/files/1874682/openshot.log)

**Issue Description and steps to reproduce:**

Hi,

**Note: I know that this repository is for the version 2.x**

We cannot open an openshot project on the computer that made the project or from another computer, after changing those absolute paths in the `.osp` file (related to this issue https://github.com/OpenShot/openshot-qt/issues/988)

When replacing `$` by `S` in .osp file, I've got another error related to pickle lib.

e.g. : 

```diff
-$'./thumbnail/a5cb9d5e-31d1-11e8-b0a2-c03fd56a439a_png_1.png'
+S'./thumbnail/a5cb9d5e-31d1-11e8-b0a2-c03fd56a439a_png_1.png'
```

the error message is :
```
Failed to import 'from openshot.openshot import main'
Error Message: pickle data was truncated
```

Here is a little stack trace :
```
Traceback (most recent call last):
  File "/usr/share/openshot/openshot/windows/MainGTK.py", line 881, in recent_item_activated
    self.open_project(file_to_open)
  File "/usr/share/openshot/openshot/windows/MainGTK.py", line 886, in open_project
    self.project.Open(file_to_open)
  File "/usr/share/openshot/openshot/classes/project.py", line 347, in Open
    open_project.open_project(self, file_path)
  File "/usr/share/openshot/openshot/classes/open_project.py", line 39, in open_project
    project_object = pickle.load(myFile)
```

My question is, is there any chance to open and recover this project with a 2.x version or with existing version ?

Please find attached the two `.osp` files.
[OSP-issue.zip](https://github.com/OpenShot/openshot-qt/files/1874739/OSP-issue.zip)

**Comment by DylanC** [comment]
@PapsOu - This is a tough question. I think maybe only @jonoomph would have the answer.

**Comment by peanutbutterandcrackers** [comment]
Perhaps @N3WWN and @ferdnyc might also be able to shed some light into this?

**Comment by N3WWN** [comment]
Sorry, I'm not familiar enough with pickle files to explain this, but lines that start with an `S` appear to be strings.  I do not see any lines in the files within OSP-issue.zip that start with `$`, so I don't know what lines you're replacing the dollar signs with the letter `S`.

In fact, I don't see the `$` character occurring in these files at all.

**Comment by ferdnyc** [comment]
If you're attempting to open a _legacy_ `.osp` file (from OpenShot 1.x, using the non-JSON pickled serialization that looks like this):
```
(iopenshot.classes.project
project
p1
(dp2
S'USER_DIR'
p3
S'/home/ferd/.openshot'
p4
sS'theme_settings'
p5
NsS'THEMES_DIR'
p6
S'/usr/lib/python2.7/site-packages/openshot/themes'
p7
sS'mlt_profile'
p8
```
you **SHOULD NOT** change any paths in the file, or if you **MUST** (if files are no longer in the locations listed), you should update them to current _absolute_ paths — **DO NOT** make the paths relative. The legacy importer code in OpenShot 2.4.x understands the format of OpenShot 1.x files, and knows how to convert the stored data. So, it _expects_ all paths to be absolute (as they were in the 1.x `.osp` files). 

Changing any paths to relative in a legacy OpenShot 1.x `.osp` file will most likely make it unreadable by both OpenShot 1.x and Openshot 2.x. (Or, at least, I don't know _what_ the result would be. If it worked it'd be a lucky accident, since it was never designed to work that way.)

The advice in issue #988 about editing paths in the `.osp` file is meant for someone wishing to import an _Openshot 2.x_-format `.osp` file that was saved elsewhere, it doesn't apply to legacy `.osp` files.
