### ISSUE TITLE
Thumbnail For The Openshot Project File :)

### ISSUE THREAD

**Issue by MisterTeeXD** [OpenShot/openshot-qt#1470]
**System Details:** Intel i5 Processor, Integrated GPU, 4GB RAM
* Operating System / Distro: Windows 10
* OpenShot Version: 2.4.1-55
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
I have designed a little thumbnail for the Openshot Project File, it does not look great but i tried

![openshot project file icon](https://user-images.githubusercontent.com/37266538/38323877-d7f163a4-383e-11e8-9746-8f626ecc669b.png)

**Comment by DylanC** [comment]
@MrTertius - Thanks! Its good to even try, that is how we can improve things by learning more and doing better.

**Comment by MrTertius** [comment]
You are welcome.

**Comment by peanutbutterandcrackers** [comment]
How does the current windows thumbnail look right now?

@DylanC - Is this something we can change - the thumbnail that appears for a file pertaining to a program? I like this one.

@MrTertius - Awesome!

**Comment by peanutbutterandcrackers** [comment]
You'll probably have to attach a png with transparency, though - if you want the project to take it in. :)

**Comment by MrTertius** [comment]
That is a png file, i just checked

**Comment by peanutbutterandcrackers** [comment]
Yes. It is. I meant with transparency. I believe the white rectangular border around the blue boundary of the thumbnail probably isn't necessary/desirable. But I am not really sure.

Perhaps @ferdnyc might have some ideas. :)

**Comment by MrTertius** [comment]
Ok then

**Comment by ferdnyc** [comment]
Looks transparent to me. (Viewed in a new tab in Chrome...) 
![screenshot from 2018-04-06 15-08-08](https://user-images.githubusercontent.com/538020/38439640-629768c8-39ac-11e8-9d45-fec667421eab.png)

The only issues I'd raise are 
1. The rounded corners on the bottom. (Weird because the top-left isn't rounded.) Also, as you can see in my screenshot the background isn't transparent behind the rounded corners, there's a tiny bit of white.
1. The diagonal isn't a straight line — it looks like it's in three segments, right now (possibly more), with two visible discontinuities along the path between the two corners. Removing those extra points and making it into a straight line would clean it up a little.

Also, if there's a vector source file the PNG is generated from (like an .SVG or similar), it couldn't hurt to have that as well. Linux supports .SVG icons, I'm guessing macOS does as well since I know support for scalable icons showed up there before anywhere else.

Thanks!

**Comment by peanutbutterandcrackers** [comment]
There you go! Nothing escapes @ferdnyc's eyes! Awesome! [Could you please also take a look at #1454, too, good sir?]

@MrTertius - I hope you will soon submit an enhanced thumbnail icon, good sir!

**Comment by ferdnyc** [comment]
It doesn't strike me that @MisterTeeXD is ever coming back, I guess this can be closed? The image isn't quite usable as-is, I'm afraid.

**Comment by MisterTeeXD** [comment]
I will close this and in the meantime i will make an improved version of this, after all im not a pro graphics designer

**Comment by ferdnyc** [comment]
> I will close this and in the meantime i will make an improved version of this, after all im not a pro graphics designer

Hey, none of us are! It was a strong start, just needs a bit of polish. 

The most important things would be for the icon to be in structured-graphics form natively (an SVG from Inkscape or similar tool), that way it can be edited if necessary, and rendered to PNG from there if need be. But the vector form would be the primary source file. With the wide range of screen resolutions these days, more and more we're seeing SVG files used for even regular file/app icons, since they can be any size needed.

**Comment by peanutbutterandcrackers** [comment]
@MisterTeeXD - Please do use [InkScape](https://inkscape.org) and InkScape only. It is [Free Software](https://en.wikipedia.org/wiki/Free_software). We do not want this amazing gem of a Free Software to be tainted with proprietary evil scum. Yeah, I've been watching/reading way too much [Richard Stallman](https://en.wikipedia.org/wiki/Richard_Stallman). :laughing: But seriously though, please do use InkScape to make it.

I'm so much of a free software guy that I look forward to the day when we'll have open graphics card and that will do all the hardware acceleration for Linux Distros and it'll be the Linux Kernel of graphics cards. I also wonder if OpenShot's default export profile should be ogg/vorbis or ogg/theora. Because freedom! lol

**Comment by ferdnyc** [comment]
Please don't listen. Software prescriptivism is as gauche as telling someone what sports team to root for. There's nothing wrong with using Libreoffice Draw to create a file icon. Or [sK1](https://sk1project.net/). Inkscape is only one of at least a dozen free applications that can create SVG files.

And if you should happen to legally own and want to use Adobe Illustrator to create an OpenShot `.osp` icon, then that's perfectly fine too. Because it's your _effort_ that's being donated to the project, not the software, and how you choose to put in that effort is, ultimately, really up to you. We're glad to have it all the same. _...Right?_

**Comment by ferdnyc** [comment]
> I also wonder if OpenShot's default export profile should be ogg/vorbis or ogg/theora. Because freedom! lol

Don't even joke about that. (Also, they wouldn't be an either/or — Ogg is the container, Theora the video codec, and Vorbis the audio codec. Analagous to an MP4 with H.264 video and AAC audio. You'd need all three, so an export profile for Ogg video would be something like `ogg/theora+vorbis`.

Ogg is fine (though Matroska is far superior as a container). Vorbis was fairly good at the start, and pretty competitive with MP3, but it's been left behind since then, and MP4/AAC can run rings around it. Theora is the problem, though, as it's pretty much been crap since the beginning. 

I wouldn't force or even encourage anyone but my worst enemy to use Theora video. (Which helps explain why the official list of [hardware players that even _support_ Theora](https://wiki.xiph.org/Theora_Hardware) is like four devices long and was last updated in 2010. And despite mumblings about Google Summer of Code projects from 2006(!) that are still featured on that page, the list of **working** hardware-accelerated Theora decoders is exactly this: `[ ]`.

**Comment by peanutbutterandcrackers** [comment]
I was just prescribing a *free* software to use. *sigh* lol :smile: 

BTW, didn't know about sk1 project. Looks pretty cool. Should probably give it a try.

That comment was written half jokingly though. But yeah, I confess that I am a free software vegetarian now (Not yet a vegan). :laughing:

**Comment by peanutbutterandcrackers** [comment]
But yes, @ferdnyc is right (as always), it is your effort that matters, @MisterTeeXD. :+1: 

[But I would be happier if you used Free Software, though. But that's just me. :)]
