### ISSUE TITLE
Time keyframes do not match playhead position

### ISSUE THREAD

**Issue by Rendrman** [OpenShot/openshot-qt#1471]
Time keyframes insert on consecutive frames, regardless of playhead position. I need to animate playback speed faster and slower over the course of the clip, but cannot place keyframes where I need them.

This seems to be isolated to the "Time" property. Other property values seem to work as expected.

I am on Linux CentOS 7, Openshot 2.4.1

**Comment by peanutbutterandcrackers** [comment]
This issue has been already noticed and a [patch submitted to fix it](https://github.com/OpenShot/openshot-qt/pull/1384), too.

Also, regarding the time-keyframing, it seems that it is currently [broken](https://github.com/OpenShot/openshot-qt/issues/1198), sadly.

**Comment by DylanC** [comment]
@ferdnyc - Would you say there is still something to be fixed here in relation to the clip not having initialized the time parameter?

**Comment by ferdnyc** [comment]
Mmmmm... no, honestly, because if you're _not_ planning to set Time parameter keyframes, it's best to leave it uninitialized.

There might be the possibility of initializing it IFF the user tries to drop a manual keyframe, and it hasn't yet been initialized, but that's already getting complicated. And, also, the keyframe values won't really have any meaning for them _unless_ they've initialized it, which is when the Time parameter gets filled with frame#s.

I think, at least with the current implementation of playback rate / the Time parameter in general, this unfortunately has to remain a documentation / user-education issue, rather than something that can be addressed in the code.
