### ISSUE TITLE
4 cores processor

### ISSUE THREAD

**Issue by PetrxStepanek** [OpenShot/openshot-qt#1495]
**System Details:*Intel Core i5-7500 CPU, 3,40 GHz, 64bit, x-64 processor*
* Operating System / Distro: Win10
* OpenShot Version: 2.4.1
* _Please attach log files if crash_

How to set up Open Shot video editor to use all processor cores during work? Currently work with just one core so the program is very slow.

Thank you for reply

**Comment by peanutbutterandcrackers** [comment]
Could you please try out the latest daily build? Please head over to the [download](https://github.com/OpenShot/openshot-qt/issues/1494) page and click on 'daily builds' button. According to a recent [tweet ](https://twitter.com/ctrl_alt_d/status/985157566492790786)from a user, OpenShot is indeed using all available CPU cores. I think it must be because of the recent support for ffmpeg 3.2 for OpenShot.

Hope that helps!

**Comment by DylanC** [comment]
@PetrxStepanek - Openshot does use all cores in the latest daily builds. I would recommend to give one of those a try or wait until v2.4.2 is released.
