### ISSUE TITLE
Numeric selection slider only works when dragged

### ISSUE THREAD

**Issue by risimmons** [OpenShot/openshot-qt#150]
I noticed this yesterday when playing with animated titles using Openshot-qt installed from the PPA (all up-to-date, fresh install yesterday) on LM 17.3.

When dragging the preview slider to select a frame number for the animated title preview all works fine; the frame number for the preview changes and the preview updates.  However if you click somewhere on the slider to move it instead of dragging it, the slider moves to the new location but doesn't update the frame number or generate a new preview.

Looks like a missing onclick handler or something.

**Comment by jonoomph** [comment]
This was a bit more complicated than expected... which is why it was a bit flawed I'm guessing. I've messed with this a few different times, and the QSlider in Qt5 doesn't work quite the way you might expect, especially considering I don't want to render the frame on every single valueChanged signal since it's so CPU intensive with Blender. Seems to work well now though... with some creative hacking. =)

**Comment by risimmons** [comment]
Awesome, thanks. I'll try this out once it hits the ppa.

Richard
