### ISSUE TITLE
Crashing when Exporting

### ISSUE THREAD

**Issue by CAMFR** [OpenShot/openshot-qt#1508]
**System Details:** 
* Operating System / Distro: ?    windows 10
* OpenShot Version: ? ver2.4.1
* _Please attach log files if crash_
"Launch.exe a cessé de fonctionner"
or Microsoft visual c++ runtime library "Runtime error
The application has requested the runtime to terminate it in an unusual way"

**Issue Description and steps to reproduce:**

I tried every type of export,with just a really light video it does work but  with a more complicated editing if I export in mp4 and low quality it might work but don't export the whole thing (which should be 1min30) . I might think it's because of the weigh of the files 

(Also sorry I'm french if a sentence is unclear I'm deeply sorry)

**Comment by peanutbutterandcrackers** [comment]
@paintlover70 - I am very sorry for the inconvenience, good sir. Could you please try attaching the log files, so that we can help you out?
At the moment, I suggest you try out the latest daily build (if you weren't using the *very* latest one). Or perhaps some other a not-so-latest one?

@DylanC - Fire men here, Cap'ain! Good men need our help!

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Not sure what we can do here?

**Comment by peanutbutterandcrackers** [comment]
@DylanC - I don't really know. It's just that @paintlover70 is making a video for a fire department so I thought we should make this a high priority issue. :)

**Comment by paintlover70** [comment]
Thanks, but at this point I have moved on from trying to use the program to create the video.  I really didn't have the time to try and figure out how to get the program to work for me.
