### ISSUE TITLE
Cannot find files while openning an existing saved .osp

### ISSUE THREAD

**Issue by Flyingdishes** [OpenShot/openshot-qt#1510]
**System Details:**
* Operating System / Distro: ? Windows 10 enterprise, I7-5600 CPU, 8GB, 64 bit
* OpenShot Version: ? V2.4.1 (french version)
* _Please attach log files if crash_
![cannot find file jpeg](https://user-images.githubusercontent.com/21989133/38819579-0ec09f24-419c-11e8-804f-29a57688c737.JPG)
![cannot find file jpeg 2](https://user-images.githubusercontent.com/21989133/38819609-1e743124-419c-11e8-85a6-636ee40a1bae.JPG)

**Issue Description and steps to reproduce:**
- When trying to open an existing osp file saved the day before, openshot cannot fing a first file -in that case a JPEG- (first attachement). 
- After entering OK on the first warning message, a second windows opens (second attachement) to select missing file, but not viewing any avalable JPEG files but just an empty directory (which is not empty).
- Openshot enters into an infinite loop between screen 1 & 2 and program has to be killed thru windows task manager.

Thanks for your support, OpenShot is a fantastic tool !

Flying

**Comment by gary9872** [comment]
Did you move the OSP file?
Did you move any of the imported files to a different location.
Is it now mapped on a different drive number? It is on a network drive?

Projects in Openshot are not portable yet so you need to store it locally and move nothing.

If none of this applies then let us know and wel'll see if there is some other problem with OpenShot.

cheers,

Gary

**Comment by Flyingdishes** [comment]
Hi Gary,
Thank you for your quick answer.

Yes I moved the all OSP Folder (including all source files) on a different drive, as my C:drive became saturated. I'll try to reposition the folder to its initial drive.
This however does not explain why, why proposing to search for the file as not having acced to the original location, no file is presented in the 'find directory'  search window.

All the best,
Flying

**Comment by gary9872** [comment]
My best guess is that it hasn't be implemented yet. 

Open up a new issue asking for this feature to be added.

Cheers,

**Comment by Flyingdishes** [comment]
Thanks Gary,
Will do!

**Comment by Flyingdishes** [comment]
Thanks Frank for taking the time and the in detail and patient answer.

•	Understand your point and I agree, even if showing no files can be confusing, it is indeed a directory which is to be chosen.  However, in my case, I intentionally placed the missing JPEG file in the directory I then selected, with similar effect as the file was still not detected ( I double checked, the file was present in the selected new directory).
•	Because of the previous point, as I was not able to get the file detected in the appropriate directory, I was in the situation of an infinite loop.

Thank you again for your time and patience,
Flying.

**Comment by Flyingdishes** [comment]
Thanks Frank for taking the time and the in detail and patient answer.


·         Understand your point and I agree, even if showing no files can be confusing, it is indeed a directory which is to be chosen.  However, in my case, I intentionally placed the missing JPEG file in the directory I then selected, with similar effect as the file was still not detected ( I double checked, the file was present in the selected new directory).

·         Because of the previous point, as I was not able to get the file detected in the appropriate directory, I was in the situation of an infinite loop.

Thank you again for your time and patience,
Flying.

**Comment by ferdnyc** [comment]
> However, in my case, I intentionally placed the missing JPEG file in the directory I then selected, with similar effect as the file was still not detected ( I double checked, the file was present in the selected new directory).
> 
> ·         Because of the previous point, as I was not able to get the file detected in the appropriate directory, I was in the situation of an infinite loop.

Ah, OK — my mistake, you're right; if for whatever reason a missing file _can't_ be provided to OpenShot, the recovery process will keep retrying that same file forever. 

The situation you were experiencing with files that were present but didn't show up sounds _very_ weird. (Permissions problems, maybe? I mean, that's the Windows standard file-chooser dialog; if the files aren't even showing up _there_, then there's something external to OpenShot that's preventing it from accessing the files. OpenShot has no control over what the file-chooser dialog can *see*, that's handled by Windows itself.)

But that aside, that issue is no different from the simpler and more common case of a file that's since been deleted or edited, and no longer exists in the form that OpenShot expects. Sometimes, missing files are simply gone forever, and **can't** be replaced. In that case, just like yours, OpenShot will end up locked in the file-recovery process with no way to complete it. Which is definitely another thing about that process which desperately needs to be improved.

I assume you've moved on and worked around that issue you were having some other way, by now? On the off chance you _haven't_, or if you can still re-create the invisible-JPEG problem, I'd be really interested to find out what was going on there. 

My instincts say that there _has_ to be some sort of file-permissions or ownership issue with the files/folder/filesystem that was preventing OpenShot from being able to access those files, since if it *could* have accessed them they'd have shown up in the file-recovery chooser. If possible, the next test I'd want to perform would be to create a new project, and use "Import File..." to test whether they show up in _that_ file chooser. I'd be completely shocked if they did, and only became invisible in the recover-file chooser. But that would certainly indicate some sort of OpenShot bug! 

(If they **don't**, I'm still going to put my money on incorrect file permissions / ownership that prevented OpenShot accessing those files. When you put the files back into place, is it possible you accidentally copied them as Administrator? Or had OpenShot running as a different user that didn't own the files or that folder?)

**Comment by Flyingdishes** [comment]
Hi Frank,
Sorry for my late answer, but I did want to reproduce the case cautiously.
 In fact you were perfectly right: What I took for an infinite loop was in fact a sequence of 10 JPEG files, with a very similar file name (DSC01753, DSC01754, ...,  etc) that I took for the same file name being requested.
In fact Opneshot work as you describe and what I took for an infinite loop was infact the sequence of 10 request for 10 different files.
My suggestion to avois such a use case would be to take the last directory entered as the default one and avoid to ask each time the same directory if all missing files could be found in the last folder entered. (as it is logicaly he consequence of a move of the fully working folder to another disk/space).

Thank you for insisting and sorry for introducing doubt as I was not cautiously noticing the file name differences.
Flying.

**Comment by ferdnyc** [comment]
> My suggestion to avois such a use case would be to take the last directory entered as the default one and avoid to ask each time the same directory if all missing files could be found in the last folder entered. (as it is logicaly he consequence of a move of the fully working folder to another disk/space).

Exactly, once you've located one missing file all of the other ones in that directory (at least) should be automatically reconnected. That's part of my "vision" for a Recovery Mode fix, along with removal of the path component from timeline Clips (there's no reason for it, as all clips are associated with media in the project library, and those already have pathnames) — both of those are feature request #1325 — and the addition of "Skip" and "Cancel" buttons so that you can escape the process if need be (with the understanding that you'll be working with a damaged project).

Thanks for taking the time to test again, and for confirming that things are merely as bad as they seem, not worse. :laughing:

**Comment by Flyingdishes** [comment]
All good then. Thanks again for your patience .
Openshot is working as good as it promises, and I understand that the list of opportunities of progress is as usual infinite, you have to manage priorities

**Comment by Vlad412** [comment]
> These two things are both... well, admittedly not ideal, but not bugs either:
> 
> > * After entering OK on the first warning message, a second windows opens (second attachement) to select missing file, but not viewing any avalable JPEG files but just an empty directory (which is not empty).
> 
> That's intentional. If you notice, the title of the window is "Find directory containing...", and that's what the selection dialog is expecting. You aren't asked to choose the missing file, but rather the _folder_ that contains the missing file. OpenShot assumes the file still has the same name, and can't handle renamed media files at this time. So, the window presented is a directory-chooser window, not a file-chooser window, which is why it doesn't show files. (This confuses a lot of people, because it's confusing. But, now you know.)
> 
> > * Openshot enters into an infinite loop between screen 1 & 2 and program has to be killed thru windows task manager.
> 
> It isn't actually an infinite loop, though it can seem like one. (And you're right that the recovery process **IS** impossible to abort except by forcibly killing the application, which _should_ probably be considered a bug. However, recovery can also be exited by successfully completing the process.)
> 
> The way file-recovery works right now, you need to give OpenShot the new location for **each** individual _media file_, **as well as** for each individual _clip_ on your project timeline. So, even if you only have a single file imported, that you placed just once on the timeline, you'll have to choose that new location a minimum of twice. If you placed more than one clip, you'll need to do this an additional time for each additional instance of the clip. Imported more than one file, ditto.
> 
> It's a pretty ugly and needlessly tedious process that very badly needs improvement, and hopefully that'll happen sooner rather than later. But it's neither not working nor an infinite loop, it's just... the way it is. If you'd selected the appropriate folder where OpenShot can find each of your files and clips (even if it's the same folder every time), you'd eventually have gotten through the recovery process and been left with your project opened and fully recovered. As things currently stand, that can be a long and frustrating process, and it's usually a _lot_ faster and simpler to just put the files back where OpenShot expects them. If at all possible, it's highly recommended to stick with that approach for now.

Thanks that helped !! (it was searching for folder lol)

**Comment by farse** [comment]
I have just updated my openshot from 2.4 to 3.0 and I have not moved the original osp file (I tried two different projects) and I am getting this issue, except when I select the correct directories the program then crashes. I am using linux.

`libopenshot logging: Tue Jan 31 21:56:04 2023
------------------------------------------
---- Unhandled Exception: Stack Trace ----
  /lib/x86_64-linux-gnu/libc.so.6 abort                                    0x141  [0x7f2d334257f1]
  /usr/lib/x86_64-linux-gnu/libstdc++.so.6                                          0x8c957  [0x7f2d2e420957]
  /usr/lib/x86_64-linux-gnu/libstdc++.so.6                                          0x92ae6  [0x7f2d2e426ae6]
  /usr/lib/x86_64-linux-gnu/libstdc++.so.6                                          0x91b49  [0x7f2d2e425b49]
  /usr/lib/x86_64-linux-gnu/libstdc++.so.6 __gxx_personality_v0                     0x2a8  [0x7f2d2e4264b8]
  /lib/x86_64-linux-gnu/libgcc_s.so.1                                          0x10573  [0x7f2d2e18c573]
  /lib/x86_64-linux-gnu/libgcc_s.so.1 _Unwind_Resume                           0x125  [0x7f2d2e18cdf5]
  /usr/lib/x86_64-linux-gnu/libopenshot.so.23 openshot::QtImageReader::QtImageReader(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool) 0x135  [0x7f2d2fcad735]
  /usr/lib/x86_64-linux-gnu/libopenshot.so.23 openshot::Mask::SetJsonValue(Json::Value) 0x373  [0x7f2d2fcdda83]
  /usr/lib/x86_64-linux-gnu/libopenshot.so.23 openshot::Timeline::SetJsonValue(Json::Value) 0x453  [0x7f2d2fcbe353]
  /usr/lib/x86_64-linux-gnu/libopenshot.so.23 openshot::Timeline::SetJson(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) 0xb5  [0x7f2d2fcb1065]
  /usr/lib/python3/dist-packages/_openshot.cpython-36m-x86_64-linux-gnu.so                                          0xb93a9  [0x7f2d306993a9]
  /usr/bin/python3               PyCFunction_Call                         0x56  [0x564626]`

**Comment by Colorjet3** [comment]
Please download the latest DEV Daily Build AppImage from openshot.org/download/#daily and give it a try.  I have not used version 2.4 and that is a pretty big jump version wise (you have skipped 2.5x (and many daily builds), 2.6x(and many daily builds), v3.0.0 (and many daily builds).

After you download the latest DEV Daily AppImage create a new project and test it to ensure v3.0.0-Daily is operational.

Another thing you can try is (still run v3.0.0-Daily):
1. Close Openshot.
2. Make a backup of /home/username/.openshot_qt folder.
3. Delete /home/username/.openshot_qt folder.
4. Start v3.0.0-Daily AppImage.
5. Open your project that was created with 2.4.x

**Comment by jasonroosdev** [comment]
> Projects in Openshot are not portable yet so you need to store it locally and move nothing.

It's 2023 and they are still not portable. Absolute garbage software.

**Comment by jasonroosdev** [comment]
I'm experiencing the same thing, and I literally cannot even close the app without losing all my work. I haven't moved any files. If I close the app and reopen it, it can't find 20% of the files.

**Comment by Colorjet3** [comment]
The "Missing Files" message is due to source files being renamed, deleted, moved, or the folder they exist in being renamed.  Please see this:  https://github.com/OpenShot/openshot-qt/wiki/Missing-File-Prompt
