### ISSUE TITLE
Drag and drop doesn't work for importing file with Greek characters

### ISSUE THREAD

**Issue by Daniel-Mantzakos** [OpenShot/openshot-qt#1526]
**System Details:**
* Operating System / Distro: Windows 10 Pro 64 bit Version 1709
* OpenShot Version: 2.4.1

**Issue Description and steps to reproduce:**
As the title says, when you drag and drop a file containing Greek characters in its title, it doesn't get imported. There is no crash during the process. The import from the menu though works as expected.

**Comment by Daniel-Mantzakos** [comment]
@ferdnyc I am talking about filename.

This issue happens for any type of file (audio, video and images).

In order to reproduce the issue, you can rename a song or picture or video you already have with the first letter of the Greek alphabet, for example, which is α. You can then drag and drop it into OpenShot and verify that it's not working.

**Comment by ferdnyc** [comment]
Gotcha, thanks.

Hmmm. I renamed a video file to `α.mp4` and an audio file to `ααα.mp3`, and had no problems importing both by drag-and-drop from my Desktop to the OpenShot window.

![screenshot from 2018-04-21 12-48-55](https://user-images.githubusercontent.com/538020/39086632-7faad546-4562-11e8-9148-ad4e95681519.png)

...I'm guessing the reason it works for me is because I'm on Linux. So this looks like it may be a Windows-only issue. I'll try to find some time later on to spin up my Win7 VM, so I can test it there.

**Comment by Daniel-Mantzakos** [comment]
Ok, then it should be a Windows issue. I also found a more general problem. Even if the filename does not include Greek characters, the file won't be imported by drag and drop if the location path of the file contains Greek characters. I did a test by creating a Greek named folder on my desktop and pasting inside it an audio file with only English characters in its filename. The file still wouldn't be imported by drag and drop, because its parent folder was named in Greek.

**Comment by ferdnyc** [comment]
OK, good information, thanks. I'll be sure to test that, too.

**Comment by DylanC** [comment]
@Daniel-Mantzakos - Can you try this in a daily build? @ferdnyc put in a fix for this issue recently.

**Comment by misterhatoola** [comment]
This issue occurred with Hebrew characters as well. Just tried it with the latest daily build, and it works fine - files with Hebrew characters in their filenames, or in the folder name, drag just fine into OpenShot's window.

**Comment by DylanC** [comment]
@misterhatoola - Excellent. Fantastic news to hear. :)
