### ISSUE TITLE
Volume doesn't change

### ISSUE THREAD

**Issue by kjtop** [OpenShot/openshot-qt#1533]
**System Details:**
* Operating System / Distro: Windows 10
* OpenShot Version: April 21st daily build
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
The volume won't change on any clips. Whether I select 100% or 10%, the level is the same.

**Comment by xjelinek** [comment]
I have the same issue :-(
You can whatever but nothing between works. Only **0** or **100**. I tested on the same part of the video in line with 0%, 50%, and 100%.
Moreover when the video is 0% and music is 100% it's louder, then when video is 50% and music 100%.
In stable version 2.4.1 I was able to pronounce video up to 20 (so 2000%), which is not possible now (it's always reverts to 1 (so 100%).

Made o really large and complex clip and unable to finish it :-(
Do any1 know which last build works with audio correctly please? I need to export it.
ty!!!

**Comment by peanutbutterandcrackers** [comment]
You can keyframe the volumes using the properties tab. You might want to look up about keyframing in OpenShot before you can use it, though. But that is the proper way to do it, rather than just right click and volume and stuff.

Here are some links that should help you with keyframing in general:
Intro to keyframes: https://www.youtube.com/watch?v=YRtdCK9ZDUQ&t=6s
1. https://www.youtube.com/watch?v=P3zIprwr1rk&t=1s
2. https://www.youtube.com/watch?v=mgi4esWA84M&t=307s
3. https://www.youtube.com/watch?v=nEyrC1v-M1s&t=18s
4. https://www.openshot.org/static/files/user-guide/index.html

**Comment by DylanC** [comment]
Solved via pull/90:
https://github.com/OpenShot/libopenshot/pull/90

@kjtop @xjelinek
