### ISSUE TITLE
Set the default automatic transition in preferences

### ISSUE THREAD

**Issue by amuellerde** [OpenShot/openshot-qt#1535]
It is possible to change theTransition whitch addet automaticly (fade)?
I mean, without select of pictures and rigth click  and select "add to timline (+)"

**Comment by N3WWN** [comment]
I just looked at the code and I don't see a means to change the default.  The fade is hardcoded as the default.

**Comment by gary9872** [comment]
#88

**Comment by gary9872** [comment]
This is my # 1 wish as well.

**Comment by amuellerde** [comment]
I would like this add to wishlist ;-)
Possibly by Add an entry to preferences ?

**Comment by DylanC** [comment]
@gary9872 - Adding this as a separate enhancement as it sounds a little different to #88

**Comment by jwm-art-net** [comment]
Yes this gets my vote too. When zoomed in working with lots of short clips with tight transition times 10 seconds is just too long. It's the kind of setting which would just speed up my workflow if I could set it to 1 second.

**Comment by SuslikV** [comment]
Not a big deal at all. Modern edit assumes short transitions per 2 sec long clips or so. Far easier here is to copy/paste objects (right-click _Paste_ - inserts transition, for example, to the pointed place, instead of timeline Track's cursor position). And because of short duration of clips - the used transitions are close to each other in the timeline (easy to copy/paste them).
