### ISSUE TITLE
time in the property editor does not show playback speed multiple

### ISSUE THREAD

**Issue by jpritikin** [OpenShot/openshot-qt#1538]
**System Details:**
* Operating System / Distro: ? Linux
* OpenShot Version: ? 2.4.1

When I switch a clip to 2X forward playback speed then I would expect to see 2.0 in the time property. Instead, I see a big number that looks like duration in frames or something? The number is different for clips of different length.

**Comment by N3WWN** [comment]
It's not obvious, but the time is a keyframe of what the clip time should be on the timeline.

If I have a clip that is 500 frames long without any time dilation, the `Time` property is 1.0 across the entire duration of the clip.

But, if I take the same clip and use `Time -> Slow -> Forward -> 1/2x`, keyframes are now added for the clip, the clip is now 2x as long on the timeline and the `Time` property is 1 for the first frame of the clip and 500 for the last frame of the clip.  This is how time dilation is applied to the clips.

Using the same 500 frame clip and applying `Time -> Fast -> Forward -> 2x`, keyframes are added for the clip (just like last time), but the clip is now 1/2x as long on the timeline.  The `Time` property is still 1 for the first frame of the clip and 500 for the last frame of the clip.

If you had performed cuts on clip before dilating the time, you would see different start and end `Time` properties.

For instance, if I slice this 500 frame clip in 1/2 and keep the right side, then apply 1/2x speed playback, the `Time` property shows 250 for the first frame of the resulting clip and still 500 for the last frame of the clip.  The clip is still the same duration in the timeline as the original.

**Comment by jpritikin** [comment]
OK, I guess it's just a documentation bug.

**Comment by PorcelainMouse** [comment]
Confusing.  So, is there any way to choose a time scale that is not in the list of presets?  I need something like 1.1x.

**Comment by N3WWN** [comment]
This is not going to be entirely straight-forward or intuitive, but I think I can provide instructions on how to get a 10% speed gain (1.1x playback speed)... or any other playback speed, for that matter.

- Add the clip to the timeline
  - I added a 10s long clip
- Determine the current number of frames that the clip occupies in the project.  This is determined by the frame rate of the project profile, not the frame rate of the original clip.
  - My project is using a `HD 1080p 60 fps` profile, so my frame is 60 fps, multiply that by 10s and I know that my clip is 600 frames long
- Obtain the `Duration` of the clip from the `Properties` frame
  - My clip has a duration of 10.01, which makes sense because my clip is 10s long
- Based on how fast you want it to play back, determine how long the clip should be
  - Using 1.1x, which is 10% faster, I multiplied 10.01 by 0.9 and got 9.009s (9s is close enough)
- Move the playhead to that position in the clip.  If your clip is all the way at the start of the timeline, you can move the playhead directly to that position.  If your clip does not start at the start of the timeline, you will need to add the desired position to the `Position` property of the clip.
 - My clip was at the start, so I move the playhead to 00:00:09:01 (this is frame 1 of the 9th second)
- Now, in the `Properties` frame, double-click on the 1.0 in the `Time` property and enter the clip's number of frames
  - I entered 600 and hit <kbd>Enter</kbd>
- You should see that the `Time` field turned green and a small green tick mark appeared at the bottom of the clip, right where the playhead is.  That means that a keyframe was added for the `Time` property.
- Without moving the playhead, right click on the clip and select `Slice` -> `Keep Left Side` to get rid of the "frozen" frames (repeats of the last frame in the clip) to the right of the green keyframe mark
- You should now be left with a clip that will play back at your desired speed

**Comment by PorcelainMouse** [comment]
Wow, thanks!  That's a recipe I can follow.  Much appreciated.

**Comment by DylanC** [comment]
Setting this as a bug in the documentation.

**Comment by jpsilverio** [comment]
> This is not going to be entirely straight-forward or intuitive, but I think I can provide instructions on how to get a 10% speed gain (1.1x playback speed)... or any other playback speed, for that matter.
> 
>     * Add the clip to the timeline
>       
>       * I added a 10s long clip
> 
>     * Determine the current number of frames that the clip occupies in the project.  This is determined by the frame rate of the project profile, not the frame rate of the original clip.
>       
>       * My project is using a `HD 1080p 60 fps` profile, so my frame is 60 fps, multiply that by 10s and I know that my clip is 600 frames long
> 
>     * Obtain the `Duration` of the clip from the `Properties` frame
>       
>       * My clip has a duration of 10.01, which makes sense because my clip is 10s long
> 
>     * Based on how fast you want it to play back, determine how long the clip should be
>       
>       * Using 1.1x, which is 10% faster, I multiplied 10.01 by 0.9 and got 9.009s (9s is close enough)
> 
>     * Move the playhead to that position in the clip.  If your clip is all the way at the start of the timeline, you can move the playhead directly to that position.  If your clip does not start at the start of the timeline, you will need to add the desired position to the `Position` property of the clip.
> 
>     * My clip was at the start, so I move the playhead to 00:00:09:01 (this is frame 1 of the 9th second)
> 
>     * Now, in the `Properties` frame, double-click on the 1.0 in the `Time` property and enter the clip's number of frames
>       
>       * I entered 600 and hit Enter
> 
>     * You should see that the `Time` field turned green and a small green tick mark appeared at the bottom of the clip, right where the playhead is.  That means that a keyframe was added for the `Time` property.
> 
>     * Without moving the playhead, right click on the clip and select `Slice` -> `Keep Left Side` to get rid of the "frozen" frames (repeats of the last frame in the clip) to the right of the green keyframe mark
> 
>     * You should now be left with a clip that will play back at your desired speed

Works perfect, thanks!

**Comment by kriekos** [comment]
This works for just 1 clip but what if there are several clips together?

I have made the attached excel based on the help above. I am applying it to a 2hr long clip that I am cutting into pieces and pasting together again with certain clips fast forwarded at certain speed. When applied it gives a weird result. Attached you find my excel.

[2019.04.03 v5.xlsx](https://github.com/OpenShot/openshot-qt/files/3203652/2019.04.03.v5.xlsx)

**Comment by MSoliven** [comment]
I followed the steps above and it doesn't seem to work anymore. It will just truncate my video up to the green tick mark. instead of speeding it up. I'm using Openshot 2.5.1 Windows.

**Comment by FairyTaleKnits** [comment]
I also tried following this and it just cut my video at that point.  I want to be able to speed up my videos so they are around 29 seconds to use in reels but using the presets cuts them down too much sometimes.  I'm using Openshot 2.6.1

**Comment by N3WWN** [comment]
Just to keep everything together, here is what I sent to @FairyTaleKnits in response to their question posted to Facebook (formatting and step order updated):

You shouldn't be using any presets, though. 

In the comment https://github.com/OpenShot/openshot-qt/issues/1538... , I explain how to do it. 

I'll go over it again, though: 

1. Set (or examine) your project profile so you know how many frames per second will be rendered (I used "HD 1080p 60 fps"). 
2. Import your clip. 
3. Add the clip to the timeline at position 0. 
4. Select the clip and note the "Duration" property (my test clip was 157.53s long). 
5. Multiply the clip duration by your project framerate (for me, that was 157.53 * 60 = 9451.80)
6. Move the playhead to 29s, select the clip and change the Time property to the value you calculated (for me, it was 9451.80). 
7. The length of the clip doesn't change, so right-click on it and select Slice -> Keep Left Side. 
8. Render your video and it should now be 29s long.

**Comment by MSoliven** [comment]
Thanks, N3WWN, that worked! My problem now is I get chipmunk echoing my normal voice after I sped up the video. Any tips?

**Comment by JacksonRG** [comment]
@MSoliven Does it work if you separate video and audio, then adjust the speed of both? Might be related to the fact that sound is sampled at a far higher rate than video frames.

**Comment by omian** [comment]
@N3WWN thanks for your explanation. It has enabled me understand how to speed up a clip via the time property. However, I can't seem to adapt your instructions to slow down a clip (i.e. play it over a longer duration).  It seems to me the slice step is only relevant when speeding up, and something else would be needed for slowing down. 

Could you please explain how to slow down via the time property?

Thanks
