### ISSUE TITLE
Preview is not activated when Project File is selected

### ISSUE THREAD

**Issue by vchekan** [OpenShot/openshot-qt#1543]
* Operating System / Distro: Linux Mint
* OpenShot Version: 2.4.1

**Issue Description and steps to reproduce:**

When I select a file in "Project Files" panel, no Preview is shown. Preview activates only when file is move to a track and selected there.
This makes choosing file in Project Files panel very inconvenient.

**Comment by peanutbutterandcrackers** [comment]
@DylanC - This should be a good enhancement, Cap'ain!

**Comment by N3WWN** [comment]
I'm trying to imagine what this would look like.

We already have `Thumbnail View` and `Details View` in the `Project Files` frame and both show a thumbnail of the item.

A preview of the item can be viewed in a new window by Right-Clicking on the item in the `Project Files` frame and selecting `Preview file`.

Is the idea to be able to preview the items in the `Project Files` frame in the primary `Video Preview` frame that is currently used for the timeline?

If so, we may need to add a "preview mode" toggle to change the source of the currently displayed preview.

Another option may be changing what is shown in the preview based on the current focus object.  If the timeline is in focus, then the preview behaves as it currently does.  If the focus is an item in the `Project Files` frame, the preview shows a preview of that item.

I know that the layout of the main window can change, but, if we change the item which the preview shows, we could have an arrow displayed which points at either the `Project Files` frame or the timeline.  In the typical layouts (`Video Preview` in upper right, `Project Files` in upper left and timeline alone the bottom), there could be a ⬅️ icon in the `Video Preview` frame when previewing a project file which would change to a ⬇️ when previewing the timeline.  This icon could also function as a "preview mode" button described above.

Another option may be to make the preview file window dockable and update when the selected project file changes.

**Comment by vchekan** [comment]
I was not even aware about Preview File context menu. It seems quite counter-intuitive to have Video Preview window, not use it and instead have context menu to open yet another modal window to preview. According to the principle of least surprise I would remove Preview File context menu and move this functionality to Video Preview window,
Thumbnails are good, but sometimes useless. I took a lot of videos in Grand Canyon and to turn my camera on I have to point it down, so most of my videos in thumbnail mode are red rocks :) I can not distinct them in thumbnail mode.

**Comment by N3WWN** [comment]
It may seem a little counterintuitive if you're not familiar with OpenShot and other video editors the behave in a similar fashion, but the `Video Preview` frame is the preview for the rendered project (aka what is on the timeline), not the items contained in the `Project Files` frame.

One thing that I think may be helpful in a situation like you have is if we could display more details about the item in the `Details View`, such as the file created/modified timestamps, `Recorded Date` (i.e. .MTS files) or `Encoded Date` (i.e. .mp4 files) or other such metadata, duration, etc in addition to the thumbnail and complete filename.

**Comment by ferdnyc** [comment]
Yeah, as a random example, here's how this is handled in Final Cut Pro X. (A professionally-developed software suite that costs many hundreds or thousands of dollars to own, for which Apple has surely spent many, many MILLIONS of dollars to develop, it must be noted.) Every part of their interface and workflow is different from OpenShot's, so this is not really a good comparison, but it uses its viewer window for all previewing. In fact, the viewer automatically follows the mouse pointer, so that it's showing previews of the timeline whenever the pointer's down there, it switches to previewing a clip whenever you hover over one of THOSE, and you can scrub through anything you like just by moving the mouse.

[A random YouTube tutorial video](https://youtu.be/NPbBDs67aCY?t=18m36s), positioned to jump right in at the middle of the tutorial, where a rough overview of those features can be gleaned just by watching 30 seconds or so of the entire 70-minute video).

I'm sure that's a very nice system and all, and I'm equally sure that OpenShot will never be _that_. However, the idea of using the preview window to preview media in the Project Files library isn't an unworkable one. (And regardless whether it's displayed there or in a popup window, there should really be a toolbar button somewhere to trigger media previews, rather than forcing the user into the context menu.)

**Comment by vchekan** [comment]
"One thing that I think may be helpful in a situation like you have is if we could display more details about the item in the Details View"

No, metadata is not helpful when fast preview is needed.
It boils down to ergonomics and productivity.
When working on a clip of 20+ fragments, clicking each, selecting menu, navigating in a window, closing window, clicking next is waste of time. And given that there is idling preview frame right in front of you, it could be made just with single click, without interrupting your creativity process.
