### ISSUE TITLE
Converting of videos

### ISSUE THREAD

**Issue by DobclockGaming** [OpenShot/openshot-qt#1549]
Hello, can anybody help me with converting of videos on OpenShot??? I´d like to convert it to .mp4

**Comment by N3WWN** [comment]
Converting/transcoding of videos is not one of the primary intended uses of OpenShot.  Usually we recommend using something like ffmpeg or handbrake, but if you'd like to use OpenShot, that should be doable, as well.


- Open a new project
- Set the profile of the project to match your desired output (`HDV 720 24p`, for instance)
- Import your existing video
- Drag the video from the `Project Files` frame to the timeline (make sure it's at the start of the timeline)
 - Alternatively, a Right-Click on the clip in `Project Files`, selecting `Add to Timeline` and leaving everything at the default values and clicking `OK` should add the clip appropriately
- Click on the red export button (or use `File`->`Export Video`)
- Confirm that the `Target` is "MP4"
- Click `Export Video`
- Sit back while your video is exported

Keep in mind that OpenShot will actually re-encode the video, even if it is the same profile as the original video, which is where tools like ffmpeg may be more useful since you can tell them to simply copy the audio and/or video streams without re-encoding them.

**Comment by peanutbutterandcrackers** [comment]
[This](https://handbrake.fr/) might be a tool that is better suited for this particular job. :)

**Comment by ferdnyc** [comment]
Only thing I would add to that would be the inclusion of [avidemux](http://fixounet.free.fr/avidemux/download.html) in the list of recommendations, since it can do some things that [HandBrake](https://handbrake.fr/) can't, but doesn't force you to go fully command-line like ffmpeg.

Things like: 
* Apply filters/effects to the video as it's processed,
* Set start/end points visually, by playing/skipping through the video, instead of caring about time indexes,
* And last but not least (this is the single biggest limitation of HandBrake), join together multiple videos — as long as they're in the same format — by using "File→Append" to load additional files after the first one.

HandBrake is an excellent tool for straight format conversion, one video file in to one (reformatted) video file out. And it's the first thing I reach for when that's _all_ I need to do. Avidemux is more of a video _processing_ tool, and as such can do more with your video, in preparing it for a particular output device or for incorporation into a full-fledged video editing project in a video editor such as OpenShot.

**Comment by DylanC** [comment]
@DobclockGaming - Openshot is not really a converting tool but of course you can simply export to the .mp4 format if you wish. Plenty of advice to follow here from the guys. :)

**Comment by DobclockGaming** [comment]
Thank you very much!

2018-05-02 11:08 GMT+02:00 DylanC <notifications@github.com>:
