### ISSUE TITLE
Rotating video cuts off portion of video

### ISSUE THREAD

**Issue by XCSapphire** [OpenShot/openshot-qt#1572]
Pretty new to OpenShot and video editing. I have a "sideways" video I took with a camera. When I rotate it, the head of the subject is cut off in the rotated view because it maintains the original height. I can't figure out how to either rotate the entire video so that the ratio of Height:Width becomes Width:Height, or to shift the video in the rotated view so that it will include the side with the person's face.

Any help will be greatly appreciated.

**Comment by N3WWN** [comment]
@XCSapphire - Try playing with the `Scale` property for the rotated clip.  

Out of the `Scale` options of `Crop`, `Best Fit`, `Stretch` and `None`, one may present the video as expected.

**Comment by peanutbutterandcrackers** [comment]
@N3WWN - Actually, I can confirm this bug. It has happened to me, too before. in my case, `ffmpeg -i original_video.mp4 output.mkv` resolved this. Perhaps this is also something you need to look into?

@XCSapphire - Perhaps [HandBrake](https://handbrake.fr/) can fix it, like ffmpeg did for me?

**Comment by peanutbutterandcrackers** [comment]
@N3WWN - [Here](https://drive.google.com/file/d/1z5BO1qCPryXsSJyfdVNlGym0egd3CXbI/view?usp=sharing) is one. Strangely enough, it does auto-rotate to the correct orientation. Other one, I had to manually rotate by 90 degrees to get the proper orientation. However, you can still see that, in OpenShot, the top and bottom part are cut off. Yet, VLC seems to play it flawlessly. `ffmpeg -i input ouput' does indeed fix this issue though. I think OpenShot is not reading something regarding the orientation in the metadata that VLC and ffmpeg seem to notice and/or take into account...

**Comment by N3WWN** [comment]
What I've been able to determine is that the metadata doesn't appear to actually be stored in the clip info.  

`FFmpegReader::Open()`, `FFmpegReader::UpdateAudioInfo()` and `FFmpegReader::UpdateVideoInfo()` are obtaining the metadata from the container, video stream and audio stream, respectively, but that info does not persist.  

Calls to `DisplayInfo()` after the clip is opened result in no metadata of any type, even though your example video has all 3 types of metadata.

The data is populated into `info.metadata[]`, but I am unable to find that metadata outside of those functions.  

The metadata code was added on Feb 8, 2018 in https://github.com/OpenShot/libopenshot/commit/f2b0f3a0f4612bd34080d9e4e62cc271a718ecc1#diff-1e742ee30cac0b97fb6433daa0cab43d , specifically for this type of video, so I think it worked at one time for at least one type of rotated video.  Regardless, OpenShot does not currently appear to behave properly since the metadata disappears.  

I don't know enough about how the ReaderInfo struct works at this point to continue looking into it today.

My guess is that the data copies between `root` and `info` within `ReaderBase.cpp` are not handling metadata properly.

@DylanC - Would you mind adding a BUG tag here, sir?

**Comment by XCSapphire** [comment]
Thank you all for your advice. What finally worked for me was to use the Layout option: 1/4 size - center. This resulted in the entire shot being visible.
