### ISSUE TITLE
Problem - Export video process

### ISSUE THREAD

**Issue by emtpywallet** [OpenShot/openshot-qt#1580]
working with version 4.2.1 to create a clip less than (>) 720 seconds duration. using the export video option and choosing web and device profile with quality set at low, medium and high, the progress bar reaches to 25% then slows.  The process resources jump to 100% and the production process is slowed. 1.1Gb of RAM is consumed also.
When the production finishes, part was through the view the clip is blank both (audio and visual).

I am working with OpenSuse from a Lenovo Thinkpad (Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz) with 4Gb RAM with more than (<) 5Gb of HHD space.  Previously worked with the software on 8 April 2018 and created a clip with no issue.

Thank you in Advance for useful comments that may follow

**Comment by N3WWN** [comment]
I don't have any useful input on this topic, but did want to point out that you're use of greater-than and less-than symbols is reversed.

> a clip less than (>) 720 seconds

This should be:

"a clip less than (<) 720 seconds"

> with more than (<) 5Gb of HHD space

This should be:

"with more than (>) 5Gb of HHD space"

The use of the proper symbol will be helpful in future bug reports so that your intent comes across correctly.  Luckily, you wrote out the words, too, so we are able to be determine what you actually meant. 😀 

BTW, the way I remember which one to use is that "less-than" looks like an "L" : <

My wife remembers which one to use by remembering that the "arrow" points to the smaller number:  `3 > 2` and `1 < 10`

**Comment by emtpywallet** [comment]
Thank you for the update. God bless the dyslexics post Brexit under the hammer with a conservative stammer

**Comment by peanutbutterandcrackers** [comment]
@emtpywallet - I would like to suggest that you [try out the latest daily build](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914) as it is known to be a lot more robust than v2.4.1. v2.4.2 will be out soon, though. I think using the latest daily build will solve your problem. It might, anyways. Hope that helps!

**Comment by peanutbutterandcrackers** [comment]
@emtpywallet - I would like to suggest that you [try out the latest daily build](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914) as it is known to be a lot more robust than v2.4.1. v2.4.2 will be out soon, though. I think using the latest daily build will solve your problem. It might, anyways. Hope that helps!

**Comment by emtpywallet** [comment]
sudo zypper update openshot-qt

--------For being useful ---------
