### ISSUE TITLE
Slicing video and exporting broke the application (faulty project recovery/handling?)

### ISSUE THREAD

**Issue by Patrik356b** [OpenShot/openshot-qt#1601]
v 2.4.1

797MB MP4 Input file, recorded through GeForce Experience:
![explorer_2018-05-18_06-04-07](https://user-images.githubusercontent.com/2000703/40215535-58489b8c-5a61-11e8-9fef-c6b1e8f0f87a.png)

I slice it to get a 12 second clip to export.
Export doesn't tell me it failed (last 10 out of 12 seconds are black/blank frames)
Tried to export again, same result. 

 >Restarted application
 >Process entered zombie-state with 0% cpu usage and 4GB ram usage
>The cycle repeats

**Comment by peanutbutterandcrackers** [comment]
1. You might want to try out the [latest daily build](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914) instead of the latest stable version (v2.4.1) as it is known to be a lot more stable.
2. You might want to [create a custom profile](https://www.openshot.org/static/files/user-guide/profiles.html#custom-profile) to match your 59.78 FPS video (as I don't think there are any 59.78 FPS video profiles in OpenShot by default); the original video profile and the profile one edits it in has to match.
3. If the crash still persists, you might want to [attach the logs](https://github.com/OpenShot/openshot-qt/blob/master/CONTRIBUTING.md).

Hope that helps!

**Comment by Patrik356b** [comment]
It turned out that a small message box was hiding on a different monitor other than the primary. (it is my TV in another room) 

Regarding the source media fps; I believe it is an artifact from the game I recorded the clip in, because it is able to do 144Hz by G-Sync

**Comment by Patrik356b** [comment]
But, it still doesn't explain the black frames in the exported video clip

**Comment by DylanC** [comment]
@Patrik356b Can you try v2.4.2 and let us know if you have any success?

**Comment by Patrik356b** [comment]
Seems to work fine. I think it is solved
