### ISSUE TITLE
Openshot Splash Screen Made By Me :)

### ISSUE THREAD

**Issue by MrTertius** [OpenShot/openshot-qt#1604]
**Is your feature request related to a problem? Please describe.**
I have no problems with Openshot so far

**Describe the solution you'd like**
The Splash Screen will appear when your double click on the .exe file

**Describe alternatives you've considered**
Non so far

**Additional context**
I have made a Splash Screen for Openshot that can be used, i hope it looks good :).

![openshot splash screen](https://user-images.githubusercontent.com/37266538/40320645-a9be8792-5d2c-11e8-96b1-efaeddfadcf3.png)

**Comment by peanutbutterandcrackers** [comment]
Neat. What did you make this with? It would be awesome if you've use something like [GIMP](http://gimp.org/) or [InkScape](https://inkscape.org/en/) instead of other proprietary software to create this. And the fonts, too. It'd be nice if you'd use open fonts like [Liberation Sans](https://fontlibrary.org/en/search?query=Liberation+Sans). After all, OpenShot is a GPL V3+ Licensed free software gem. We would not want to taint it with anything even remotely proprietary. :D 

But then again, I'm not sure if the devs will be putting in a splash screen for OpenShot.

@ferdnyc might have some ideas, and constructive criticisms though.

**Comment by ferdnyc** [comment]
Thanks, @MrTertius. I wouldn't worry too much about open tools / resources, though. Were OpenShot to incorporate a splash screen, it would need to be implemented using PyQT (OpenShot's GUI language), and it would use the same fonts and style as the rest of the interface. This image would be helpful as a design guide, but it wouldn't be incorporated into the software directly.

As @peanutbutterandcrackers said, though, I don't know of any plans to incorporate a splash screen — on my system, OpenShot's main window appears roughly 2 seconds after I launch the application, so there really isn't time to show any sort of loading screen. AFAIK the goal is to keep it loading quickly enough that a splash screen isn't necessary.
