### ISSUE TITLE
Multiple .osp projects in the same directory overwrite each other's project files with the same name

### ISSUE THREAD

**Issue by peanutbutterandcrackers** [OpenShot/openshot-qt#1606]
OpenShot version: 2.4.1+ (latest daily build as of today)

1. Create a project. Insert a title with the default name. Save it as 'asdf' under the dir 'test'.
2. Create another project. Add another title with the default name (which is same as the previous one's). Save it as 'fjkl' under the dir 'test', again.

On opening the project 'asdf', one would see that the title-file-name1 file now has been replaced by another title - the one from project 'fjkl'.

Because user's are prone to make such errors. Perhaps something must be done to prevent this.

**Comment by nsgitfr** [comment]
@peanutbutterandcrackers - confirmed here with OpenShot-v2.4.1-129-g42fbaf5-2d81121d-e7451201-x86_64.exe
Created a project, saved it as aaa.osp ; can see a folder called thumbnails.
Created a new project, saved it as bbb.osp ; only one thumbnails folder.
So feel multiple projects saved in a single directory will share the same thumbnails folder...
Tricky  to save project/folder data, move  or delete...

Some thoughts to share

As per Windows users
Best would be to be like .html files along with folder images that folow when we move or delete.
Save an HTML file with title toto, you have a filder called toto_images, delete HTML will also remove the folder.
But this is dedicated to Windows... and may be managed from Windows 

Alternative and to get a single element, saving thumbs as mime64 encoded within the osp file ?
This may mean much bigger osp file !

Best

**Comment by ferdnyc** [comment]
> As per Windows users
> Best would be to be like .html files along with folder images that folow when we move or delete.
> Save an HTML file with title toto, you have a filder called toto_images, delete HTML will also remove the folder.

\*nod\* That's also what I call [the Audacity model](https://github.com/OpenShot/openshot-qt/issues/1325#issuecomment-388516696), where (in that software) a `projectname.aup` file created alongside a `projectname_data` folder which holds all of the audio blocks for the project.

OpenShot clearly needs **something** like that. Whether it's that, or creating a Project Folder and placing the `.osp` file _inside_ the folder (along with other ancillary files, with the folder and its entire contents intended to be moved/copied as a single unit), clearly the single-`.osp`-file model is not sufficient for managing an OpenShot project's data. I hadn't even realized that the titles create **more** auxiliary data files.

> Alternative and to get a single element, saving thumbs as mime64 encoded within the osp file ?
> This may mean much bigger osp file !

It would, and I think it would be the wrong approach because it wouldn't solve the larger, general problem of project data file management. _Ideally,_ for maximum manageability, we should really try to encourage the user to even store their **media** files in the OpenShot project folder, and at some point you can't encode EVERYTHING into the `.osp` file. Video project data is far too large and complex to manage in a single datafile.

**Comment by udippel** [comment]
Surely not a bug, but a RFE. To me personally, Within a user-defined folder (not ~/.openshot), each project gets a sub-directory created at the instruction 'New Project...' with all files going into there.
