### ISSUE TITLE
exportation bug

### ISSUE THREAD

**Issue by renleren** [OpenShot/openshot-qt#1607]
when i want to exportate a vidéo in full HD whit destiantion 👍 siteweb/ destination youtube, openshot close automatically.
![openshot bug](https://user-images.githubusercontent.com/39515063/40349143-f0a5fe14-5da5-11e8-92ac-cd2cc77751e1.jpg)

**Comment by peanutbutterandcrackers** [comment]
Hey there!

I suggest that you [switch to the latest daily build](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914) and try exporting the video using that version of OpenShot instead of v2.4.1. The daily builds are known to be a lot more stable. Hope that helps!

**Comment by renleren** [comment]
Hello,

but this bug is arrived with the last version (2.4.1) !

2018-05-22 11:51 GMT+02:00 peanutbutterandcrackers <notifications@github.com

**Comment by peanutbutterandcrackers** [comment]
Good sir,

2.4.1 is the latest stable version. However, there have been quite a lot of changes to the code since then. And daily builds are up to date with those changes. They aren't the latest stable version. But they are the latest one. Please follow the instructions provided, and [use the daily build](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914). Or, you could also wait for version 2.4.2 which should be out any day now.

Hope that clears things up.

**Comment by DylanC** [comment]
@renleren Can you try v2.4.2 and let us know if you have any success?

**Comment by renleren** [comment]
unfortunaly it disn't work with this new version

2018-07-27 16:49 GMT+02:00 DylanC <notifications@github.com>:
