### ISSUE TITLE
crop feature is not available in daily build ppa version 2.4.1 dev 1

### ISSUE THREAD

**Issue by xlicz** [OpenShot/openshot-qt#1620]
there is a issue said that the video crop feature will be available in 2.4.2 and in daily build version. I download the daily build version but can only find a crop icon file in the software install directory. I'm wondering when would the crop feature available to use? Thanks!

**Comment by peanutbutterandcrackers** [comment]
Good sir, 2.4.1-dev1 is not the latest daily build. In order to get the latest daily build, you must follow [these instructions](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914). Perhaps, you added the stable ppa instead of the daily one.

Also, on a side note, v. 2.4.2 will be out really soon. Any day now. :)

**Comment by DylanC** [comment]
@xlicz Can you try v2.4.2 and let us know if you have any success?
