### ISSUE TITLE
Audio Stutters With Chroma Key Applied

### ISSUE THREAD

**Issue by MisterTeeXD** [OpenShot/openshot-qt#1630]
**Describe the bug**
The audio will stutter when chroma key is applied to the video clip

**System Details (please complete the following information):**
 - Operating System / Distro: Windows 10
 - OpenShot Version: 2.4.2-rc1

**To Reproduce**
1. Go to Effects
2. Click, drag and drop the Chroma Key Effect on the video clip
3. Scroll down to (No scrolling needed)
4. See error by playing the video in Openshot

**Expected behavior**
The audio will no longer stutter when Chroma Key is applied to a video clip

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**
This bug was in other Builds of Openshot

**Comment by sspmrsomebody1** [comment]
I have had a problem where OpenShot does not buffer properly (including sound stuttering) #1567, especially when debuffering to conserve memory and rendering more demanding effects such as Chroma Key and fade transitions.

**Comment by peanutbutterandcrackers** [comment]
I have notified the devs about this. Hopefully, this will be fixed by rc2! :)

Thank you for your time and patience and your efforts to make OpenShot even better. I can confirm that all throughout the project @MrTertius and @sspmrsomebody1, good sirs, you two are the only ones that use windows and yet are actively volunteering to make OpenShot better on the platform by reporting bugs and other issues. Most of the others do report issues (most of them do come from windows platforms) but do not follow it along. You two sirs, however, do test the program and make good reports. You are awesome! I hope you continue to help make OpenShot better, good sirs!

**Comment by DylanC** [comment]
Dup of #1593

**Comment by peanutbutterandcrackers** [comment]
@MisterTeeXD - I see that you have closed a lot of the issues that you'd opened. I hope you do keep on reporting issues - as the performance issues that you point towards is what needs to be fixed in OpenShot. Perhaps we can fix all of them one at a time in future releases. Thank you for loving and supporting OpenShot, Mr. Tee. :+1:
