### ISSUE TITLE
Titles do not update on the timeline

### ISSUE THREAD

**Issue by sspmrsomebody1** [OpenShot/openshot-qt#1637]
**Describe the bug**
If I create a title (not an animated title) and add it to the timeline, then change it it does not update itself on the timeline.

**System Details (please complete the following information):**
 - Operating System / Distro: Windows 8.1
 - OpenShot Version 2.4.1-dev1 (From Daily Build Installer `OpenShot-v2.4.1-115-ge7a99e9-59-697-x86_64.exe`)

**To Reproduce (Example)**
Go to Title > Title and create a title.
Put the title on the timeline.
Play it.
Edit the title (eg change the colour or text)
Play your project again and the title will not update.

**Expected behavior**
I believe this problem is caused because title clips on the timeline are not debuffered when the title is edited. As a result of this a title on the timeline is played as it was prior to being edited.

**Comment by ferdnyc** [comment]
> I believe this problem is caused because title clips on the timeline are not debuffered when the title is edited. As a result of this a title on the timeline is played as it was prior to being edited.

You're correct about the bug, but it's actually a bit more insidious than that, even.

The problem is that Titles are editable, uniquely within OpenShot, from the _Project Files_ area, not on the Timeline as Clips. Which means that the _changes_ made when editing a Title file **don't affect** any existing Clips made from that Title which have been previously placed on the Timeline.

(This is _somewhat_ analogous to the fact that Splitting a video file from the Project Files list doesn't affect any previously existing Clips made from that file. The difference is, the result of Splitting is created as a new, separate entry in the Project Files list, so it's not unexpected that Clips referencing the original file would be left unchanged.)

The upshot of all this is, even if a Title Cip **isn't** buffered on the Timeline, it **_STILL_** won't use the updated version of the Title after an Edit operation, because the Clip's data file was already read and processed from the old version of the Title. It isn't the preview buffer that's out of date, but rather the Title data that OpenShot has loaded into memory.

What needs to happen is, after a Title is edited, OpenShot needs to notify any Clips associated with that Title that the source file has changed, and force them to reload so they pick up the changes.

(**TL;DR**: Yup, it's broked.)

Until that's fixed, two workaround options:
1. You can remove the existing Clips from the Timeline for any edited Title, then add the Title back to the Timeline again — new Clips created after the edit will pick up the new data.
1. Or, you can Save your project file, then Open it again: when OpenShot loads the project, all Clips will be updated to the current version of the Title.

**Comment by sspmrsomebody1** [comment]
It might be a good idea to double-check that you have the right path.
If you copy the path, open a File Explorer window, then paste it into the address bar does it open Blender?
If so then there is a bug with OpenShot. If not you typed the path wrong.

**Comment by sspmrsomebody1** [comment]
Thanks!
