### ISSUE TITLE
Very slow, Freezes Win. 10

### ISSUE THREAD

**Issue by BigChubs** [OpenShot/openshot-qt#1640]
I'm having the same issue as this form: https://github.com/OpenShot/openshot-qt/issues/1076. 
When adding video. Then play, it will freeze up. I even adjust the cache limit to 10,240 mb for memory since i plenty of ram. Before the video starts playing again. My cpu will jump up from anywhere between 50% to 100%. Does the same thing when a slice a video clip. Is this software very cpu dependent? It should be using more of my graphics card then it does my cpu. It doesn't even touch my graphics card. 

Windows 10 64 bit Home Verison 1803
Intel Core i7-6700k cpu @4.00 GHz
4 cores Logical processors 8
24 GB of Ram
Nvidia GeForce GTX 960

**Comment by peanutbutterandcrackers** [comment]
Good sir, I suggest that you [try out the latest daily builds of OpenShot](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914) rather than using v2.4.1 which is known to have A LOT of issues on windows. Or, you could also wait for v2.4.2 which should be out in about a week or two (if all goes according to plan). But I suggest for now that you switch to the latest daily build.

Also, OpenShot does not yet support GPU processing. We might have that some time in the future. But sadly, as of right now, we do not yet have that capability.

**Comment by DylanC** [comment]
@BigChubs Can you try v2.4.2 and let us know if you have any success?

**Comment by BigChubs** [comment]
I did try this. It did help a lot from the daily build. But Their's still some minor issues with it. When start's playing the video in the time. It jitters within 2-3 seconds. And it jitters for a about 1.5 seconds. Then it smooths out. It even does it when you export it to a file. I double check the original video file. The original video it just fine. Test the same videos in my other video software i have. I have no issues their. So I'm going to stick with my other video software until OpenShot becomes a little more stable.

**Comment by peanutbutterandcrackers** [comment]
@BigChubs - Perhaps you could help OpenShot to become stable by testing and making good reports, if you have the time? Even if you don't, we wish you luck. We shall try to make OpenShot as stable as possible. So maybe you'll be able to use it for production grade work pretty soon. :)
