### ISSUE TITLE
Worked for a day then crashed... doesn't open after that

### ISSUE THREAD

**Issue by PleaseHelpM** [OpenShot/openshot-qt#1662]
**Describe the bug**
Basically what happened was that I used it for a day and then when I exported it just crashed, following message flashed on the screen 
"This application has requested the Runtime to terminate it in an unusual way. Please contact the application's support team for more information."

**System Details (please complete the following information):**
 - Operating System / Distro: Windows 8
 - OpenShot Version: Newest

**To Reproduce**
1. Go to 'OpenShot'
2. Click on 'Download'
3. Install OpenShot
4. Make a video and click 'Export'
5. Use the exported video to make another video, click 'Export'
6. See error

**Expected behavior**
What's gonna happen is that a little window will pop up saying 
"This application has requested the Runtime to terminate it in an unusual way. Please contact the application's support team for more information."

**Screenshots**
![image](https://user-images.githubusercontent.com/40033338/41108395-b384ebfe-6a74-11e8-8072-98c5857ef60f.png)

**Additional context**
If I try going into the program again it doesn't work, I searched for the problem but nothing works

**Comment by peanutbutterandcrackers** [comment]
It's all right. You don't need to panic. I suggest you switch to [the latest daily build]() for now. It is known to be a lot more stable on windows. The version you are using (v2.4.1) is known to be quite prone to crashes. Also, v2.4.2 will be out soon - with a lot more features and stability fixes. Hope you'll enjoy using it! :)

**Comment by DylanC** [comment]
@PleaseHelpM Can you try v2.4.2 and let us know if you have any success?

**Comment by dannafe** [comment]
@DylanC 
I figured out my issue: v2.4.x cannot overwrite an exported file on OS-X.
Workaround: put a unique file name in the "export" modal dialog box.

**Comment by peanutbutterandcrackers** [comment]
@dannafe - Did you have the same issue, too, sir? Also, does not OpenShot give the choice to overwrite an exported file in OS-X? If not, then perhaps it should be worked upon...

**Comment by dannafe** [comment]
> On Jul 2, 2018, at 9:20 PM, peanutbutterandcrackers <notifications@github.com> wrote:
> 
> @dannafe <https://github.com/dannafe> - Did you have the same issue, too, sir? Also, does not OpenShot give the choice to overwrite an exported file in OS-X? If not, then perhaps it should be worked upon…
> 
I misdiagnosed the problem: It only seems like it is failing to overwrite an existing export. In reality, it is crashing before even getting to the file system asking you if you want to overwrite an existing file. 

The real problem is that  OpenShot crashes, almost all of the time, as soon as you hit the “Export” button, inside the modal dialog box for exporting.

This occurs when attempting to use ANY profile.



Dan Nafe
http://OurSafeHome.net <http://oursafehome.net/>
Vero Beach, Florida
email: dan@OurSafeHome.net <mailto:dan@OurSafeHome.net>

**Comment by peanutbutterandcrackers** [comment]
Right on it, sir! Thank you for the info. We will get right on to fixing this in 2.4.2.x bug-fix release series. Could you please [attach the logs](https://gist.github.com/peanutbutterandcrackers/d84c257e74b72d8b06b4daffaebc5a14) for your crash in the time being?

@steinybot, @DylanC - Since you two seem to have a mac, could you please test this issue out, please? Thank you.

**Comment by peanutbutterandcrackers** [comment]
Possibly related to #1787

**Comment by peanutbutterandcrackers** [comment]
@steinybot - Hmm... I have quite forgotten what I was thinking back then (it's hard to juggle all these issues around)... but I guess I just wanted other mac-users (hopefully with good knowledge about how computers work) to confirm this...

You haven't yet been able to set up a dev environment on a mac, yet, good sir? Perhaps I should ask the devs to get the documentation page a bit of updating for mac users?

**Comment by DylanC** [comment]
@PleaseHelpM - Try v2.4.3 and let us know if you still have a problem.
