### ISSUE TITLE
Best source for editing ?

### ISSUE THREAD

**Issue by nsgitfr** [OpenShot/openshot-qt#1669]
Hi team,
What's best source for editing with OpenShot from AVCHD (MTS file at 1080/50p), MP4 or iFrame (also at 1080/50p or 720/25p) ?
Difference should mainly be between MTS files from Panasonic device against MP4 file format from same device...
Best

**Comment by peanutbutterandcrackers** [comment]
Hey there,

While I don't quite fully understand what 'source' means, I think I have a few helpful tips:
1. Please make sure you are using the correct profile to edit the footages. So, for your 1080p @ 50fps use a profile that makes use of - at least the 50fps part. If you want, [here](https://www.openshot.org/static/files/user-guide/profiles.html#custom-profile) is how you create custom profiles to fit your needs.
2. Go to Edit > Preferences. Under 'Cache' tab, increase the cache limit. That will let OpenShot use the specified amount of RAM for caching, and generally would mean better playback during preview.
![screenshot at 2018-06-09 06 33 29](https://user-images.githubusercontent.com/26764547/41186040-43f0ac4c-6baf-11e8-8c9b-0f51e1652513.png)

Hope that helps!

**Comment by gary9872** [comment]
I would assume MP4 would work better as IFrames is some mystery voodoo from Apple.

**Comment by peanutbutterandcrackers** [comment]
Oh! A comma there! I forgot to parse that. Silly me! Thank you, @gary9872! You're awesome! :)

**Comment by nsgitfr** [comment]
Ok, so, MP4 or MTS... no IFrames. Thanks @gary9872 
@peanutbutterandcrackers source file is what we get as input for Openshot from camcoders aso. 
But what's best (most efficient) for editing MTS compared to MP4 ?
Could MTS be mixed with MP4 (camcoder deliver both, MTS is better resolution MP4 is classic) but other sources only deliver MP4 (still image camera for example)...
If mixing is ok, guess I would consider MTS as native from camcoder... and MP4 for still image (as no better format)
As MTS and MPM4 resolution may not be the same, downscale is OK if needed ?
What is mandatory if mixing ? same FPS ?
Thanks for help
Best

**Comment by peanutbutterandcrackers** [comment]
@nsgitfr - That is lot of questions packed into one. Haha. I don't really know which one is better - MTS or MP4. You chould mix the two, yes. And having both be in the same FPS should be preferable (and not an issue, as it'll be from the same video capture device, I believe). You might want to look into [creating custom profiles](https://www.openshot.org/static/files/user-guide/profiles.html#custom-profile) too. Not sure if that helps. But it might.

You might also want to go through [this guide](https://gist.github.com/peanutbutterandcrackers/f0f666243133e0ed25abbc12a4ba23d7) (not sure if I've recommended you this or not).

Sorry to have kept you waiting. Hope this helps!

**Comment by nsgitfr** [comment]
@peanutbutterandcrackers MTS is AVCHD is 1080/50p, so, from the specs, it is a better choise...
But have to accommodate with all the upcoming process... and wonder depending destination... DNLA served to a TV, DVD, or played on computer...
Will have to check sources videos, as each may come with a different resolution or worse, with different FPS !

**Comment by peanutbutterandcrackers** [comment]
@nsgitfr - Hmm... looking forward to the results of your further investigations!

**Comment by nsgitfr** [comment]
@peanutbutterandcrackers I will give some tries... Have to fix the crash issue 1st ;o)

**Comment by peanutbutterandcrackers** [comment]
@nsgitfr - Hmm... Please do keep on being patient and showing love to OpenShot. After all, it is our efforts as users that will push this project forward. :)

**Comment by N3WWN** [comment]
For me, video from my Canon digital camcorder which saves videos in MTS format (video is AVC High@L4 with variable bitrate maxing out at 16Mbps and audio is AC3) is much _easier_ to edit if I first convert it to MP4 (video is AVC Main@L3.1 with fixed bitrate of 3.8Mbps and audio is AAC).  

There is no loss in quality after converting to MP4 that the human eye can distinguish with the video from my camera even though the MP4 file is 1/4 the size of the MTS file.

When I said "easier" above, what I mean is that OpenShot reacts much faster when scrubbing the playhead, generating previews, etc with the MP4 file.  This may be due to the size of the MP4 or it may be due to the codec, I'm not sure, but either way, I always convert my MTS files to MP4 before editing.

**Comment by nsgitfr** [comment]
Looks fine, ok for so. Thx @N3WWN
How do you convert toMP4 ? External tool or OpenShot ?
Any other change for example, FPS to get a standard if mixing different sources or resolution to get the same where ever we are in the project ?
Not sure where to set this, before editing (along with MP4 convert) or from OpenShot final project...

**Comment by N3WWN** [comment]
I use [ffmpeg](https://ffmpeg.org) to convert from MTS to MP4, but there are other tools like [handbrake](https://handbrake.fr) which are very good. 

For me, my projects all use a 60 FPS profile.  My source clips are either 60 FPS or 100 FPS and OpenShot is fine with either.  I do find that if all my clips have the same frame rate as the project profile, OpenShot feels a little "snappier", but that's probably due to the overhead of libopenshot locating frames in dissimilar frame rate sources.

The resolution of the source clips doesn't seem to have any bearing on OpenShot's speed in my environment.  I use 720p, 1080i and 1080p clips as well as various sizes of PNG, JPG and SVG files with no problem or additional lag.
