### ISSUE TITLE
Text Overlay Scramble

### ISSUE THREAD

**Issue by reedj2** [OpenShot/openshot-qt#1673]
Every time I export a video, one text overlay is scrambled with another in the final render, and it differs every time. 

 - Operating System / Distro: Windows 10
 - OpenShot Version [e.g. 2.4.1]

**Comment by peanutbutterandcrackers** [comment]
Good sir, please switch to the [latest daily build](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914), that should help you out. v2.4.1 is known to be a lot unstable on windows platform. However, many improvements and fixes have been made since the release. Also, v2.4.2 is also under way. :)

Hope that helps!

**Comment by DylanC** [comment]
@reedj2  Can you try v2.4.2 and let us know if you have any success?
