### ISSUE TITLE
Animated alpha mask

### ISSUE THREAD

**Issue by alpoptv** [OpenShot/openshot-qt#1691]
In first I want to compring how does work the alpha mask effect(not in using transitions) and I want to know if it is possible to move the mask to get an animation like this video https://drive.google.com/open?id=1JsuGkRWfKoPbZr7h2NCajNSyUNTn6N-9 (or if this animation is possible in another way)?
Thanks

**Comment by N3WWN** [comment]
If this is the desired effect, I wouldn't use alpha mask.  I would create an all black image (of any size because you can resize it inside OpenShot) and put that image on a track above the title clip.  The animation can be accomplished using the transform feature or manually setting location keyframes for the black image clip.

**Comment by peanutbutterandcrackers** [comment]
@N3WWN *always* has a way to do things. Always. :smile:

**Comment by DylanC** [comment]
Closing as answered.
