### ISSUE TITLE
Welcome/Tutorial Window stays and buttonclick only reloads Window

### ISSUE THREAD

**Issue by k4yaman** [OpenShot/openshot-qt#1708]
**Describe the bug**
Welcome/Tutorial window stays and buttonclick only reloads window on first start. You can right click in the task bar and close but it reopens again.

 - Operating System / Distro: Manjaro
 - OpenShot Version [e.g. 2.4.1]

Startet with starter which has: openshot-qt %F
With Terminal sart: openshot-qt
starts the tutorial but still popup stays open

after clicking excessively on the buttons they start to apply
regards

**Comment by Lloyd-H1** [comment]
I am have a similar problem on a Ubuntu Linux system. Tutorial window pops up and can only be hidden by clicking on the Openshot program window. But it will pop back up after saving a file or several other operations. The "NEXT" button does not work.

It really is annoying for that "Tutorial" window to keep popping up, but won't do anything.

Version 2.4.1
(Version 2.4.1 is the latest version available through Ubuntu.)

Ubuntu 18.04


![screenshot_2018-06-18_16-59-59](https://user-images.githubusercontent.com/15940631/41564738-713e6074-7319-11e8-8381-30847e45e71e.png)

**Comment by peanutbutterandcrackers** [comment]
Hey there, could you please switch to the [latest daily PPA]()? A fix to this issue was pushed in recently (and we still need to test it).

Also, for manjaro, perhaps trying out the latest daily AppImages should work. Please do not use the RC builds but the other ones (ones that do not end with rc-1 or rc-2 or rc-3).

Hope to hear the results soon!

**Comment by k4yaman** [comment]
2.4.1-dev1 still contains this behavior

**Comment by erikjms** [comment]
Still happening with the latest non-rc AppImage that I see at https://www.openshot.org/download/

OpenShot-v2.4.1-170-g2ff63e3-9ae61e50-f32c7c30-x86_64.AppImage (21 June 2018)

running on:
AVLinux 2018 (based on Debian Stretch)

**Comment by peanutbutterandcrackers** [comment]
Gentlemen, I have good news for you!

Currently, a fix is in progress. And hopefully, this fix will be released in `2.4.2.1` - the bug fix release (if all goes well). `2.4.2` is still not out yet, but will soon be.

If you want to follow the developments regarding the solution to this problem, you can follow it [here](https://github.com/OpenShot/openshot-qt/pull/1726). However, I would advise you not to comment about your problems there, as it is a thread for code reviews and not for user support.

Hope that helps!

Please do keep on loving and supporting OpenShot!

**Comment by peanutbutterandcrackers** [comment]
Hey there! Could you all please try [this](https://drive.google.com/open?id=1n5_joUIWr4FI7daLaCj7WwFUk-sXsVKN) build out, please? It integrates the changes of the PR by @ferdnyc that has, hopefully, fixed this issue. If you confirm that the issue has been fully resolved, the changes can be merged into the main source. Thanks!

**Comment by peanutbutterandcrackers** [comment]
The following are the beta-builds that contain the changes made to resolve this issue (PR #1726 by the awesome @ferdnyc). Please try them out and report whether this resolves the issue. Thanks!
1. [Windows Builds](https://drive.google.com/open?id=1n5_joUIWr4FI7daLaCj7WwFUk-sXsVKN)
2. [Mac Builds](https://drive.google.com/open?id=10zy1SQz6gGCxfmYZtMnTYHkC5NBQy6Oz)
3. [Linux Builds](https://drive.google.com/open?id=10D6BIF_n8krpYB-goNQ7jj4W33OSv4Yg)

**Comment by k4yaman** [comment]
Linux Build fixed to Problem. Just doesn't look so gracefully on Manjaro XFCE. Regards
![bildschirmfoto_2018-07-05_19-27-26](https://user-images.githubusercontent.com/10848113/42338439-240acce2-808a-11e8-8c79-b6f1136970e4.png)

**Comment by ferdnyc** [comment]
Well, crap. That means the QDockWidget isn't being rendered transparent on your system, for some reason. It's configured transparent, though... I wonder why it isn't rendering that way?

Hmm, XFCE you say...  I wonder if the WM (openbox, I think?) supports compositing? If not, we may be in trouble with the transparent window background... but then again, I wouldn't have expected the previous code to work either. And I can't imagine it's lacking a compositor in 2018.

Out of curiosity, was the tutorial popup transparent in the previous version? It may have been hard to tell, since that window didn't have a side arrow, so you'd only have seen a _tiny_ bit of black poking out from behind the rounded corners, like in the lower-left corner of the one on your screenshot.

If the old tutorials weren't transparent either, then it may just be an issue with the compositing on XFCE. If they _were_, I'll have to figure out why the new ones aren't being rendered the same way. Perhaps I missed something in how I set up the drawing canvas that gets defaulted to black on XFCE, but "clear" on Gnome Shell.

(Thanks for taking the time to try that out, BTW, @k4yaman .)

Oh, and one more thing: Do you happen to know what video card your system has?

**Comment by k4yaman** [comment]
Hello,
XFCE uses  [Xfwm](https://wiki.archlinux.org/index.php/Xfwm), compositing is active. Old Popup was transparent in the corners, sorry to say. Seems like something different is the reason for not being transparent in the new Version. lspci says: `02:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Pitcairn PRO [Radeon HD 7850 / R7 265 / R9 270 1024SP]`

**Comment by ferdnyc** [comment]
> Seems like something different is the reason for not being transparent in the new Version.

*nod* Well, basically everything is different with the new tutorial, the way the popups are managed was completely restructured. I must've missed something in the setup code, but I'll keep looking.

The first "Welcome" popup, that one was also non-transparent in the new code, right? And even though it doesn't have an arrow, there was still a wide black bar to the left? Just making sure I have a complete picture of the layout issues, pardon the pun.

("...What pun?" is the correct answer there.)

**Comment by k4yaman** [comment]
> The first "Welcome" popup, that one was also non-transparent in the new code, right? And even though it doesn't have an arrow, there was still a wide black bar to the left?
Yes, and I additionally am able to change the window size on all edges except the top one. And on the left side I can change the size on the left side of the black bar

**Comment by ferdnyc** [comment]
> Yes, and I am additionally able to change the window size on all edges except the top one. And on the left side I can change the size on the left side of the black bar

Yeah, that part's perfectly normal — a consequence of how the tutorials are managed now is that they can be resized on some systems. Normally it's pretty difficult to do. (You have to find a 1-pixel-wide invisible hairline window edge.) But your system cheats with that opaque window background, which makes it a lot easier to find.

**Comment by ferdnyc** [comment]
Well, I just made a couple of changes that might help. Though to be honest I'm not very confident in that, the documentation says the flags I just added should already be set automatically.

**Comment by ferdnyc** [comment]
Hmmm... curiouser and curiouser. Thanks @meoso , so it's apparently not a universal thing. Now, the question is, what is it about @k4yaman 's system that's different, and is there anything OpenShot can do to account for it?

(One idea I've already thought of is simply _not_ doing transparent tutorial popups, **if** we can detect that they won't be supported. The tutorial could easily render itself as a simple non-transparent window, without the blue arrows or rounded corners, in situations where that's necessary.)

**Comment by ferdnyc** [comment]
Just moving a couple of @meoso 's XFCE 4.10 / `OpenShot-v2.4.1-180-gfdd5e96-2f45a4eb-f32c7c30-x86_64.AppImage` screencaps into the Issue...

![image](https://user-images.githubusercontent.com/538020/42384609-778c487c-8108-11e8-9014-827f8a8e0029.png)
![image](https://user-images.githubusercontent.com/538020/42384587-6ad92898-8108-11e8-8ce6-6fd0414a2533.png)

**Comment by peanutbutterandcrackers** [comment]
@k4yaman - Good sir, in order to test the changes made by @ferdnyc, could you please clone the repos and test it from the source for the time being, please? It seems the builds are failing currently. However, should it work, I will post the AppImages for testing here as fast as I can. But then again, it might take a few more days... [Here](https://www.openshot.org/static/files/user-guide/developers.html) is the developers guide, BTW.

**Comment by ferdnyc** [comment]
> @k4yaman - Good sir, in order to test the changes made by @ferdnyc, could you please clone the repos and test it from the source for the time being, please?

Testing "from source" only works if you have a working libopenshot and libopenshot-audio installed somewhere, which any users running from AppImages don't have. I don't know anything about Manjaro, is that something that's easy enough to obtain?

(As long as the libraries from a 2.4.2 release are installed on the system, I agree — running `openshot-qt` itself from the source is child's play, I can easily talk anyone through the process of checking out the right tree. But the libraries are a trickier matter.)

**Comment by peanutbutterandcrackers** [comment]
Hmm... the developers page does get into getting all the libraries installed on Ubuntu, at least. I wonder if finding their equivalents in majaro would be that hard (it probably would be though). The guide is pretty well documented, nevertheless... It seems like our only choice now. Because buildkite. :D

**Comment by ferdnyc** [comment]
The developers guide details _**building**_ the libraries! We should never point **any** endusers at that guide!

Ubuntu users can just install `libopenshot-audio` and `libopenshot` from those PPAs you keep mentioning, right? There's no need for them to be building libraries just to test OpenShot!

**Comment by peanutbutterandcrackers** [comment]
Well... in my defense he does use majaro - the arch linux for the common man. :smile:

I wouldn't want to do this, either. It's just that currently, we have no choice... :disappointed:

**Comment by peanutbutterandcrackers** [comment]
[Here](https://drive.google.com/open?id=19DaAQClOOCaCxSEG9iHqjJEoTI3pdwZH)! The AppImage! Finally!!!

**Comment by k4yaman** [comment]
I tried the AppImage, still same Issue. I even tried to build the whole thing, but my [ffmpeg](https://www.archlinux.org/packages/extra/x86_64/ffmpeg/) is just the wrong one. (I don't think the PPA is working on arch) regards

**Comment by ferdnyc** [comment]
Unfortunately for @peanutbutterandcrackers I just today think I finally found the transparency issue and fixed it, too late to make it into that AppImage. Perhaps if we get a next one. He's also seen the same issue, though, so hopefully he can test it locally first.

> When I install libopenshot and libopenshot-audio and run python3 src/launch.py it breaks at my QT Version: Cannot mix incompatible Qt library (version 0x50b00) with this library (version 0x50b01)

Hmmm. That _should_ work. I've never actually seen that before, since I don't even know how it's possible to get mismatched versions of Qt5 on the same system. 

The page you linked to says that the 'libopenshot' package was [built with QtMultimedia 5.11.1 (`qt5-multimedia`)](https://www.archlinux.org/packages/extra/x86_64/qt5-multimedia/).

From that error it sounds like your system is using Qt 5.11.0. (`0x[5][0b][00]` in hex is `[5][11][0]`.) Is there any way you can update your system Qt to 5.11.1? (I'm an Arch dummy, sorry, so that's as specific as I can get offhand.)

**Comment by peanutbutterandcrackers** [comment]
I really hope we can sort something out for his local build first. That'd be great.

Could you use a ffmpeg 4 patch in [this PR](https://github.com/OpenShot/libopenshot/pull/128) for the issue regarding ffmpeg?

In the meantime, something has come up with the PR and once that has been resolved, I will try my best to get you an AppImage as fast as I can...

**Comment by k4yaman** [comment]
Good news, the branch _test/ferd_tutorial2_ is working without out any Problems. Good work guys, thank you.

**Comment by peanutbutterandcrackers** [comment]
@k4yaman - Awesome! Thank you for the good news, sir! Could you please also write a quick gist regarding how to compile openshot from source on arch linux? That should be quite helpful for future degubbers/developers/testers.
