### ISSUE TITLE
video distortion line on right side even after extracting

### ISSUE THREAD

**Issue by ubuntu2388** [OpenShot/openshot-qt#1709]
When I downloaded videos from shutterstock and import them to openshot for editing, I noticed that some of the clips have a line on the right most side that have different viewing, meaning it is not in coherence with the video, but instead have a video of its own as if it is an overlay. That line consists of almost the same video but in distorted form. It is visible when I edit it on openshot, worse it is still there when I extracted the video already. I am sure there is no overlap in my clips. 

**System Details (please complete the following information):**
 - Ubuntu 16.04 LTS
   Memory: 1.8 Gib
Processor: Intel Celeron (R) 2955u
 - OpenShot Version  2.4.1

**To Reproduce**
1. Go to shutterstock, download free preview footage
2. Import in Openshot project
3. Notice the right side of preview panel
4. A line is not uniform with the video

**Expected behavior**
Inform possible solutions to the problem, alternate suggestions

**Screenshots**
![pizap bilog](https://user-images.githubusercontent.com/40376714/41573464-71b2c8d8-73af-11e8-9ad3-0cd4ddebe2ce.jpg)

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**

**Comment by N3WWN** [comment]
Since you say "some of the clips" have this distortion, can you provide a link to two ShutterStock videos:  One with the distortion and one without?

If you can't link, can you put the two original files from ShutterStock in DropBox, Google Drive, etc for us to obtain so we can attempt to duplicate the issue.

Thanks!

**Comment by DylanC** [comment]
@ubuntu2388 Can you try v2.4.2 and let us know if you have any success?

**Comment by CmdrMic** [comment]
I have noticed this issue with v.2.4.2 and v.2.4.3. This approx 5px. wide strip, seems to be animated and linked to the audio. I am seeing it with all my Simple Screen Recorder vids.  These vids play perfect in VLC, the stock vido player in Linux Mint 17.3 etc. Also they look fine in Kdenlive, and in the Package Managers ancient 1.4.3 ver. of OpenShot. Its really annoying, as it get totally added to the export. Once I resave the clip in 1.4.3, it can be loaded back into OS 2.4.3 and it looks fine. No problem at all working with the original in kdenlive, but I am still an OpenShot fan. I hope this can get addressed.

**Comment by mfreeman72** [comment]
I'm seeing the same exact problem here. I'm using OS v. 2.4.4

**Comment by in8sworld** [comment]
I have experienced this issue now on at least three versions including the latest 2.5.0.  Here's my workflow which seems to always produce the issue:  Running Ubuntu 18.04 LTS, original video is captured with OBS in 720p with a Logitech c920 which creates an H264 Matroska video (.mkv) 30fps file. No evidence of the video artifact is evident in these originals when played in VLC or Ubuntu's default video program.  I convert the video with Handbrake to mp4 (with my old machine Openshot could not handle the mkv file so I'm still doing this even though I've got a newer faster machine).  The resulting file is ISO MP4/M4A but has dimensions 1260x710, still H264 at 30fps. There is no evidence or the artifact in this file as above.  I import the file into Openshot and edit.  Mostly simple edits and no transitions.  I export to 1080p at 24fps, the resulting mp4 shows the artifact, which for me is a sort of colorful digital pixelated vertical strip about 5 pixels wide on the right side.  I have resorted to adding a Crop effect on all video clips and removing 0.01 from the right side and this masks the effect.  Perhaps from the information above you will be able to quickly see what I am stupidly doing to cause this.  Thanks for all you do to help make this awesome software!

**Comment by SuslikV** [comment]
This one is similar to #2053

**Comment by CmdrMic** [comment]
Hi guys. I have been dealing with this for a while now, I would like to offer some observations and workarounds. First, the issue is entirely source dependent. Videos out of my cameras don't have the problem. Like others, it seems to get produced the most with sources on the system. I see it with Losslesscut, Simple Screen Recorder, but Kazam output does not do it... Definitely an Openshot bug. Open the problem file in Kdenlive - it is simply not present, all is well. Alternatively, open in amazing, Shotcut (a definite rival to Openshot now, and also - not an issue. So my simple solution has been to open the "striped" source in Kdenlive and just re-save it out again as an Mp4. The problem is then GONE when you re-open the new file with Openshot. LOL  Alternately just use Kdenlive for editing or Shotcut - which is very easy, much like the Openshot format we have all come to know and love.
