### ISSUE TITLE
Chroma Key Lag Not Fixed

### ISSUE THREAD

**Issue by MisterTeeXD** [OpenShot/openshot-qt#1720]
**Describe the bug**
There is this Chroma Key Performance issue that has still not been fixed

**System Details (please complete the following information):**
 - Operating System / Distro: Windows 10
 - OpenShot Version: 2.4.2-rc5

**To Reproduce**
1. Go to Effects
2. Click and Drag the Chroma Key Effect in the video clip
3. Select a color you want to key out
4. See error by playing the video in the editor

**Expected behavior**
Chroma Key Effect will no longer slow down the editor

**Screenshots**
[2018-06-21 18-06-34.zip](https://github.com/OpenShot/openshot-qt/files/2124426/2018-06-21.18-06-34.zip)

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**
I have attached a Zipped Video Recording of this bug, please review it. Its still in the newest Release Candidate Version

**Comment by N3WWN** [comment]
How many CPUs/cores to you have?  Under the `Performance` tab, can you set it up to show one graph per core and capture how many cores are utilized (and what is that utilization) during preview playback?

What is the behavior if Chroma Key is not applied?  Is there any lag in the preview or is it smooth?  As above, how are the cores used in this situation?

I'm thinking that perhaps the effect application code is single-threaded (or functionally single-threaded due to exclusive locks) while the rest of the preview playback is multithreaded.

**Comment by MisterTeeXD** [comment]
Last time i checked i had 4 cores, the behaviour of the Chroma Key is it makes the Audio and Preview Stutter, there is lag in the preview, i am not sure how the cores are used in that situation

**Comment by peanutbutterandcrackers** [comment]
I highly doubt that this will be fixed soon. Perhaps in `2.4.2.x` bug fix releases. But I don't think the devs will get around to fixing this right away, sadly...

**Comment by DylanC** [comment]
Dup of #1412
