### ISSUE TITLE
error message popup everytime openshot starts

### ISSUE THREAD

**Issue by bobcrikey** [OpenShot/openshot-qt#1739]
Hello can any dev's tell me why this pop up error message box always comes on screen
every time i start openshot linux mint 18.3 and it doesnt do this on my ubuntu laptop only on mint.
I asked to jonathan about this problem but he never replied.

any ideas guys?
thanks
  bob
![mint error openshot](https://user-images.githubusercontent.com/40479177/42008657-1153a332-7aca-11e8-8ffc-7f671018ccf1.jpg)

**Comment by bobcrikey** [comment]
I DO NOT RUN OPENSHOT IN A TERMINAL WINDOW MATE. WHY WOULD YOU THINK THIS?
its been installed from the app image itself
and yes its a damm nuisance this pop up message

**Comment by peanutbutterandcrackers** [comment]
Because it is one plausible reason behind this.

I suggest you try out another AppImage from the [daily builds](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914). Or, even better yet, switch to using the [latest PPA](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914).

**Comment by peanutbutterandcrackers** [comment]
Also, please be a little more patient with the program. This is not a commercial program but a labour of love of a single man - Mr. Jonathan Thomas. And we are all just trying to help him out with this. Nobody receives any compensation for the work they do on this amazing software. We all do it because of our love for the program. That is why the bugs won't be fixed fast, the replies will be tardy, and enhancements won't be able to be made on a regular basis. You will have to be a bit more kind to the project, good sir.

If OpenShot, in it's current form, isn't what you're looking for, you could try out one of the following:
1. KdenLive - https://kdenlive.org
2. Shotcut - https://shotcut.org
3. Pitivi - https://pitivi.org
4. Lives Video Editor - http://lives-video.com/

Hope that helps.

**Comment by DylanC** [comment]
@bobcrikey - I would recommend to try a daily build and see if it still happens. Try to stay calm if possible. 😉

**Comment by bobcrikey** [comment]
hello everyone, i just might had solved this problem, i was looking through some of the earlier 
problems with openshot and both dylan and peanuts were discussing libsodium18, so i checked in the terminal and it was already installed and the latest, ok then i remembered about ppa so i installed
ppa and it downloaded the latest dev and installed it, well this time it ran without that pop up message box, so i reset the computer and this latest ppa dev worked again no popup message box, however, i did notice a bit of stuttering or noise in the audio at the end of the short clip , and the forward and reverse play buttoms are blacked out no colour to them, thats ok but at least iv gotten this far

and just before i close here, i put the same little short clip one wave file and 2 png's 
into open shot 1.43 and it played back no audio stuttering or noise in it. but this is about version 2.4.1

and dylanc the daily build app images wernt even running only the normal 2.4.1 app on its on was 
the only app image that was working,

cheers
  bob

**Comment by peanutbutterandcrackers** [comment]
@bobcrikey - OpenShot version 2.4.2 is also out now. Maybe it'll work, too. You might notice a bit of problems if you upgrade the daily PPA right now. But please be patient. Mr. Thomas is working on fixing the PPA at the moment. :+1: 

Hope you create awesome videos using OpenShot!

**Comment by bobcrikey** [comment]
Well since trying to upgrade to the latest final release via ppa this is the error box message i just got
and now not even the previous dev version wont run now.
not happy i can tell you that. i just lost 12 hours work on some animations since this final release
error wont even start not even the appimage will work either on linux mint 
![install errors](https://user-images.githubusercontent.com/40479177/42130581-a049fea6-7d2c-11e8-9e7e-6e61b0361725.png)

**Comment by peanutbutterandcrackers** [comment]
Please remove openshot and the ppa and then use the stable ppa. That will fix it.

**Comment by peanutbutterandcrackers** [comment]
Or, should, at least.

`$ sudo apt remove openshot-qt`
`$ sudo add-apt-repository -r ppa:openshot.developers/libopenshot-daily`
`$ sudo add-apt-repository ppa:openshot.developers/ppa`
`$ sudo apt update`
`$ sudo apt upgrade`
`$ sudo apt install openshot-qt`

And if even that doesn't work, we'll just figure out a new way. :+1:

**Comment by bobcrikey** [comment]
hold on im doing this now as i type to you

**Comment by peanutbutterandcrackers** [comment]
*holding*

**Comment by bobcrikey** [comment]
horray, its working now thanks peanuts, i had to wait while the system updated itself and on a 2.5mb speed its not fast enough at times, no pop up messages either :)
cheers
 thanks mate.:)

**Comment by peanutbutterandcrackers** [comment]
@bobcrikey - Awesome! I'm glad that the issue has been resolved. Mind if I close this one, sir?

Also, please do remember that OpenShot is a labour of love and we can all do our part (albeit small) in helping us grow to become a lot better. :)

Closing this one for now. Hope you create amazing videos using OpenShot!
