### ISSUE TITLE
How Do I Make A Keyframed Image Go Fast???

### ISSUE THREAD

**Issue by MisterTeeXD** [OpenShot/openshot-qt#1749]
Hello, I have a question, how do I make a keyframed image go fast, in other words, how do I change the speed?

**Comment by N3WWN** [comment]
Are you asking about changing the displayed duration of a still image or increasing the playback speed of a video clip?

**Comment by N3WWN** [comment]
Gotcha!  

There isn't a keyframe editor at this point in time, but it's on the "TODO" list for a future release.

So, you could manually add another keyframe earlier in the timeline to make the animation occur sooner.  

If you want to double the speed (not just adjust it slightly), you can render the animation to a video file (.mp4 or something) and import that clip into your project and use the `Time` -> `Fast` -> `Forward` -> `2x` or something.

You can't use the `Time` menu with keyframes because the keyframes aren't modified with the display speed of the clip.

**Comment by MisterTeeXD** [comment]
Ahh Thank you.
