### ISSUE TITLE
Keyboard shotcut to slice just the selected clip

### ISSUE THREAD

**Issue by timlau** [OpenShot/openshot-qt#1764]
**Describe the bug**
Keyboard shotcuts Ctrl-L & Ctrl-J slice all tracks instead of just the selected one.
(Right click menu -> Slice -> Keep Left etc. does the right thing)

**System Details (please complete the following information):**
 - Fedora 28
 - OpenShot 2.4.2 from flathub.org
https://flathub.org/apps/details/org.openshot.OpenShot

**To Reproduce**
1. Add 2 clips on above each other
2. Select a place in the middle to cut
3. Select on of the clips
4. Press Ctrl-J or Ctrl-L

**Expected behavior**
Only selected clip is sliced

**Comment by N3WWN** [comment]
@timlau - May I ask what tool you used to create this animated GIF showing the issue that you're reporting?  That looks very useful! 😉 

Now, regarding the issue that you've reported, <kbd>CTRL</kbd>+<kbd>J</kbd> and <kbd>CTRL</kbd>+<kbd>L</kbd> are listed in the `Keyboard` section of the `Preferences` as `Slice All: Keep Right Side` and `Slice All: Keep Left Side`, respectively.

There currently are no keyboard shortcuts for `Slice Selected...`

**Comment by ferdnyc** [comment]
As @N3WWN says, <kbd>Ctrl</kbd>-<kbd>L</kbd> and <kbd>Ctrl</kbd>-<kbd>J</kbd> are documented as "Slice All: Keep {Left/Right} Side". Ditto <kbd>Ctrl</kbd>-<kbd>K</kbd> for "Slice All: Keep Both Sides". And they worked that way in 2.4.1 as well, so I think the `2.4.2-issue` label is erroneous. If anything, this is a feature request, as to my knowledge there never was a "Slice Selected" keyboard binding.

Right-clicking on a Clip invokes the Slice function on _that Clip_, same as using the Razor Mode tool. Which is different from "Slice All".

**Comment by peanutbutterandcrackers** [comment]
@N3WWN - Precisely what I was thinking! Pretty neat tool! I'd like to know what it is, too.

@ferdnyc - Fixed it, sir! :)

**Comment by timlau** [comment]
@N3WWN the gif is a screen cast, process with the chop filter in shotcut and rendered to a GIF (1024x720, 10 FPS).(keymon is used to show the keypresses)
I can see that that in the keyboard shotcut in preferences Ctrl-L & J is assigned to slice all, but
when i right click on a selected clip and select slice the shotcuts is listed on the menu.
But when i right click on time marker and select slice all,no shotcuts is listed.
![openshot-slice](https://user-images.githubusercontent.com/283985/42207829-2cba32a0-7eab-11e8-8625-79e0a18443ac.png)

So if i understand it right, there is no keyboard shotcut to spit the selected clip ?

**Comment by ferdnyc** [comment]
> I can see that that in the keyboard shotcut in preferences Ctrl-L & J is assigned to slice all, but
> when i right click on a selected clip and select slice the shotcuts is listed on the menu.
> But when i right click on time marker and select slice all,no shotcuts is listed.

Oh! You're absolutely right, and that's definitely a new bug. Those shortcuts weren't shown there in 2.4.1. But I do see them as well in the 2.4.2 AppImage. So, now we're back to this indeed being a 2.4.2 bug.

> So if i understand it right, there is no keyboard shotcut to spit the selected clip ?

Not to my knowledge, no. Though it would probably be a good thing to have.

**Comment by ferdnyc** [comment]
Actually, I don't really understand _why_ those shortcuts weren't showing in 2.4.1, because the commit that added them to the menus (in the wrong place) was made two _years_ ago, and should've been in 2.4.1 as well. It's not clear to me what changed between 2.4.1 and 2.4.2 that would affect this. Unless I just did something wrong in testing, and they really were present in 2.4.1 as well.

Regardless, #1780 fixes the issue of the shortcuts showing in the wrong menu. It doesn't address the lack of Slice keyboard shortcuts for the selected Clip.

**Comment by lobneroO** [comment]
I just came across the same "issue". Will a slice for the selected clip be added anytime soon?
Also, what does the "Split" shortcut do? I couldn't see any effect using it.

**Comment by ferdnyc** [comment]
> I just came across the same "issue". Will a slice for the selected clip be added anytime soon?

Any suggestions for the default shortcut bindings? We're running pretty low on available combos, and _picking_ the shortcuts may be one of the most difficult parts of the task.

> Also, what does the "Split" shortcut do? I couldn't see any effect using it.

Unless I'm mistaken, when you have a media file selected in Project Files, that'll open the Cutting dialog where you can trim the source file down to just the part you need, or divide a single file up into multiple clips. No effect on anything on the Timeline, only Project Files.

**Comment by MBB232** [comment]
> > I just came across the same "issue". Will a slice for the selected clip be added anytime soon?
> 
> Any suggestions for the default shortcut bindings? We're running pretty low on available combos, and _picking_ the shortcuts may be one of the most difficult parts of the task.
> 

Shift-J / Shift/K; it helps to remember the letters because they are the same. 
Or re-assign current keys to slice single track, and increase to crtl-shift-J/K  to slice all. Reduces risk of accidentally slicing all when pressing the wrong modifier key, but may upset current users that are used to that combo.

**Comment by lobneroO** [comment]
Simply "S". Reaper (a DAW, not video editor) splits the selected track with that, so I'd reset the shortcut to that anyway. Otherwise the current one for slicing all is Ctrl+K so I guess Ctrl+Alt+K or just Alt+K would work nicely (so along the lines of MBB232's answer. Just using Alt, since it usually is meant for alternative actions of the given command).

**Comment by ferdnyc** [comment]
We don't currently have any shortcuts bound on both the shifted and unshifted versions of the same letter key. I suspect that's intentional/deliberate, and means that it doesn't work correctly.

<Kbd>Alt</kbd> bindings are similarly not available for remapping, unfortunately, because Qt will process those as menu accelerators.

Plain  'S', surprisingly enough does appear to be free. Bare-letter shortcuts can be a tiny bit problematic because they inherently conflict with any text input fields, and weird things can happen with keyboard focus at times. But it's not like we don't have several of those already, so one more shouldn't be a problem.

**Comment by ferdnyc** [comment]
Done, in #3447. Three new keyboard shortcuts: "Slice Selected: Keep Both Sides" is bound to <kbd>s</kbd> as requested, and since they were both free, <kbd>a</kbd> and <kbd>d</kbd> got the corresponding "Keep Left Side" / "Keep Right Side" operations. When activated they will slice only the selected timeline item(s) that **also** intersect with the playhead.

They do support multiple selections, although our <kbd>Ctrl</kbd>-click multi-selection is a little broken in ways that can trip it up just like any other selection-dependent function. (There might be a PR that fixes that, I don't recall.) Regardless, multiple items selected using "draw-a-box" type group selection or <kbd>Ctrl</kbd>+<kbd>A</kbd> work fine, though of course select-all + slice-selected == slice-all, so that one's pretty pointless.

These are keyboard-only actions for now, they don't appear in any context menu. The actual shortcut keys are reconfigurable in the Preferences, as usual.
