### ISSUE TITLE
can't export

### ISSUE THREAD

**Issue by Pr0GamerHD** [OpenShot/openshot-qt#179]
whenever i try to export my video, the app always crashes

**Comment by ZackTheCardshark** [comment]
I'm a Mac user (El Capitan) who just discovered OpenShot, and would like to like it—but the program hangs every time I try to export. It seems to be this issue, or https://github.com/OpenShot/openshot-qt/issues/82 (which seems to have more helpful information). This is kind of the ultimate showstopper of a bug; is anybody looking into it?

BTW, also cross-posting to similar issues, since all of them are still open: https://github.com/OpenShot/openshot-qt/issues/82, https://github.com/OpenShot/openshot-qt/issues/119 and https://github.com/OpenShot/openshot-qt/issues/125

**Comment by jonoomph** [comment]
We've fixed many video freezes recently, and I would like to re-verify this bug on the latest daily build of OpenShot. Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. Please reopen this bug if you still experience an issue, and also please attach log files at that time (https://github.com/OpenShot/openshot-qt/blob/master/.github/CONTRIBUTING.md). Thanks!
