### ISSUE TITLE
import files

### ISSUE THREAD

**Issue by AbelCastroFigueroa** [OpenShot/openshot-qt#1791]
I can't import files in any of the ways

**System Details (please complete the following information):**
 - Operating System> Windows 10
 - OpenShot Version 2.4.2

**Comment by peanutbutterandcrackers** [comment]
Could you please provide us with some more details please? Screenshots? Screen-recording? More explanations? Please? That will help us help you.

[This](https://www.youtube.com/watch?v=1k-ISfd-YBE&list=PLymupH2aoNQNezYzv2lhSwvoyZgLp1Q0T) tutorial series should really help you get started with OpenShot. And [this](https://www.openshot.org/static/files/user-guide/quick_tutorial.html#step-1-import-photos-music) page details how to import media into OpenShot.

If even these methods fail, then we can take further steps to making this a good bug report so as to get this fixed in the upcoming releases. Hope that helps! :+1:

**Comment by AbelCastroFigueroa** [comment]
I tried to open an MP4 file different ways with same result:
1- Rightclick the file nema, Open with and select Launch.  Open Shot opens but no file is shown.
2- Dragging MP4 file intoth left side of OpenShot but nothing happens.

Note on the screenshot, the bar and 14 seconds label.  Looks like some file is stuck in the
![untitled](https://user-images.githubusercontent.com/40813146/42415082-0641a972-8212-11e8-83b6-22584824861f.jpg)
re.

**Comment by peanutbutterandcrackers** [comment]
I wonder if it is because your current OpenShot layout does not have the 'project files' tab. Could you please go to `view` > `views` > `simple view` and try again, please? Please drag the files first to project files. Perhaps it'll work then...

If it doesn't, we'll have to do some further investigations into this...

**Comment by AbelCastroFigueroa** [comment]
I won something, but from here I cannot play the video

2018-07-08 0:45 GMT-04:00 peanutbutterandcrackers <notifications@github.com>
:

**Comment by AbelCastroFigueroa** [comment]
Sorry, I think everything is OK now. Thank you!
Abel

2018-07-08 12:21 GMT-04:00 Abel Castro <castroabel87@gmail.com>:

**Comment by DylanC** [comment]
@AbelCastroFigueroa - Great to hear thanks!

**Comment by pollekepol** [comment]
Same problem here on:
Xubuntu 18.04.1
OpenShot 2.4.3-dev1

Importing a file (MP4 or MPEG or M4V) and click play: nothing happens with all of the files.
![snap_19](https://user-images.githubusercontent.com/46296721/50576431-ce4e9480-0e11-11e9-8067-6bc107bb28cd.jpg)

**Comment by peanutbutterandcrackers** [comment]
@pollekepol - You have to drag the video file in to the timeline first. Please look at these videos first: https://www.youtube.com/watch?v=1k-ISfd-YBE&list=PLymupH2aoNQNezYzv2lhSwvoyZgLp1Q0T

**Comment by pollekepol** [comment]
Thanks, but I know that and I did.
It worked all fine on Xubuntu 16.04 ( I used it without problem's) but now: nothing works.
