### ISSUE TITLE
Just installed OpenShot uses pt language despite my system language is pt-br

### ISSUE THREAD

**Issue by glaubersm** [OpenShot/openshot-qt#1793]
**Describe the bug**
I just installed OpenShot 2.4.2 from flathub, my system language is pt-br but OpenShot used pt instead.
I needed to set the correct language in OpenShot settings manually.

**System Details (please complete the following information):**
 - Operating System / Distro: Arch Linux
 - OpenShot Version 2.4.2 installed via flatpak/flathub

**To Reproduce**
1. set your system language to pt-br
2. install Openshot
3. start OpenShot
4. OpenShot language is pt instead pt-br

**Expected behavior**
OpenShot should use the system language

**Comment by peanutbutterandcrackers** [comment]
Possible dup of #1521 

Possible fix in progress with PR #1795 

If the fixes are merged into 2.4.2.x bug-fix series, then it should be available on flathub too.

**Comment by peanutbutterandcrackers** [comment]
@glaubersm - If it is okay with you, please do close this issue here (if the problem you're facing is really a duplicate) and follow the discussion over at the other issue. That will help us manage the large influx of issues here. Thank you!

**Comment by ferdnyc** [comment]
It's **_possible_** this is a _special case_ of #1521, that only affects locales where translations exist both with and without a country component. If that's the case, I'd expect the same thing to be happening to French Canadians, with OpenShot loading in French instead. If _that's_ the case, then yes my PR will probably fix it, as a consequence of fixing #1521.

However, the **labeling** thing is still weird. Especially since @mnwstl posted screenshots showing that both locales are being labeled "Português do Brasil" on his system... but on _my_ system (with `en_US` as the system locale), instead I'm seeing **both** `pt` and `pt_BR` labeled "Português"! That's true in 2.4.2 release and in my new-translation branch.

So, the question of how OpenShot is coming up with these labels, and how we can get it to use the right ones every time, everywhere, still seems to require additional investigation.

**Comment by ferdnyc** [comment]
So, curiouser and curiouser:

I just ran the latest Daily Build (post-2.4.2), and I'm now seeing the same thing  @mnwstl had posted screenshots of: both `pt` and `pt_BR` locales are being labeled "Português Do Brasil". But when I run OpenShot 2.4.2 release from the installed Fedora (actually RPMFusion) package, _both_ are labeled "Português" instead!

I'm not sure which translations it's actually _using_ for the various scenarios. @mnwstl supplied the following in #1873:
> To differentiate pt from pt_BR:
> File, in the menu bar in pt is "Ficheiro" and in Pt_BR is "Arquivo".

So that should make it easy enough to figure out whether it's just a labeling issue, or an actual translation-misselection problem. I'll look into that, and also look at the actual translation files on disk and make sure it isn't something stupid like a different language file copied into the wrong place.

**Comment by glaubersm** [comment]
installed daily build via PPA on neon unstable, based on ubuntu 20.04.
Now OpenShot uses pt-br language even when my system language is english.
My formats (numbers, time, currency, etc) are pt-br.
Language is set to "Default" in OpenShot preferences.

**Comment by glaubersm** [comment]
Tested daily build from PPA repository and got the same result described in my previous comment.
