### ISSUE TITLE
Stuttering

### ISSUE THREAD

**Issue by MitchPlease** [OpenShot/openshot-qt#1794]
Hi there! I'm new to the program. Using windows 10, editing Playstation 4 clips. I'm having issues with stuttering, both with the audio and sometimes even the video. It seems to differ each time I run the track, and I'm wondering if there's any way to smooth it out?? These are all short clips that I'm tying together, and the originals don't stutter whatsoever.

**Comment by peanutbutterandcrackers** [comment]
I suggest transcoding the original footages into `.mkv` using [HandBrake](https://handbrake.fr). Hope that helps.

Also, could you please try providing us with the output of [MediaInfo](http://mediaarea.net/MediaInfo) on the original footage please?

If the problem still persists, please give us your full system specs and [attach the logs](https://gist.github.com/peanutbutterandcrackers/d84c257e74b72d8b06b4daffaebc5a14) so that we can look into fixing it in the upcoming releases.

Hope that helps! :+1:
