### ISSUE TITLE
Openshot Version 2.4.2 won't open

### ISSUE THREAD

**Issue by lcontic** [OpenShot/openshot-qt#1806]
I recently downloaded version 2.4.2 of Openshot Video Editor to my Lenovo laptop and I'm having trouble opening it.   I've tried it about 15 times unsuccessfully.   Can anyone direct me please?

**Comment by peanutbutterandcrackers** [comment]
Which system are you on, ma'am? Windows 10? Windows 8? Linux Mint? Please provide us with some more details. Thank you.

**Comment by lcontic** [comment]
So sorry..... thanks for responding.  I'm on Windows 10.  It turns out the program did finally open but it took almost 30 minutes.  Not sure what the problem is.

**Comment by peanutbutterandcrackers** [comment]
Whoa. That is kinda' a serious issue. Could you please attach the logs here so that the developers can investigate this issue? Just go to the `.openshot_qt` folder in your user accounts main folder and inside it, you should find some files ending with `.log` -- `openshot_qt.log` and `libopenshot.log` (among possibly others). Please zip all of the log files and then attach the zip here. That will help us investigate into this matter further. Thank you!

**Comment by peanutbutterandcrackers** [comment]
Windows: OpenShot stores its logs in your user profile directory (%USERPROFILE%, e.g. C:\Users\username\)

    %USERPROFILE%/.openshot_qt/openshot_qt.log
    %USERPROFILE%/.openshot_qt/libopenshot.log

**Comment by lcontic** [comment]
Attached are the zipped files which I hope are what you need.  Thanks again for you help!  

[libopenshot.zip](https://github.com/OpenShot/openshot-qt/files/2173182/libopenshot.zip)
[openshot-qt.zip](https://github.com/OpenShot/openshot-qt/files/2173184/openshot-qt.zip)

**Comment by peanutbutterandcrackers** [comment]
Thank you, ma'am!

@N3WWN @DylanC - care to take a look at this, gentlemen?

**Comment by ferdnyc** [comment]
@peanutbutterandcrackers - In the future I'd just point people to [CONTRIBUTING.md](https://github.com/OpenShot/openshot-qt/blob/develop/CONTRIBUTING.md) (and perhaps mention they don't need to enable debug mode, for things like this), as it explains how to find the logs for any system.

Unfortunately, without timestamps in the logs, there's no way of knowing where the slowness is. However, it _seems_ like there may have been multiple copies of OpenShot running at the same time, at some points. There are a lot of duplicate log messages trampling all over each other.

As clichéd as it is, @lcontic , can you try restarting your computer, then running OpenShot again? I'm curious if it's just a case of old OpenShot processes hanging around, confusing things. Thanks.

**Comment by peanutbutterandcrackers** [comment]
I usually point people out to [this guide](https://gist.github.com/peanutbutterandcrackers/d84c257e74b72d8b06b4daffaebc5a14) to attach the logs. There I walk the users through deleting the original logs first and re-creating the crash again - so as to minimize the size of the logs. :)

**Comment by lcontic** [comment]
I'm not surprised there were multiple copies running at the same time.   I had unfortunately tried to open it again when it wasn't responding.  Then 1/2 hr later when it did finally open, multiple sessions opened.  Sorry I hadn't mentioned that previously.  I restarted my computer today, clicked once to open the program an hour ago and still no luck.  If you'd like for me to attach new logs please let me know.

**Comment by lcontic** [comment]
UPDATE - it's been an hour and 20 minutes and the program finally opened!

**Comment by lcontic** [comment]
Sorry for the delay.  The program still took over an hour to open but I've followed your instructions and attached the new openshot-qt.log   Thanks again for all your help!

[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2174421/openshot-qt.log)

**Comment by verbgio** [comment]
I have a similar issue on UBUNTU 18.04. I downloaded the application, made it executable but after clicking on the icon nothing happened. Any advice? And I had serious problems also with the previous version (2.1.4 if I remember well), as after 15 minutes it gets slower and slower and finally freeze and I have to restart the computer each time. 
Thank you for your help!

**Comment by ferdnyc** [comment]
@verbgio Please open a new issue, those problems aren't related to @lcontic 's Windows startup troubles.

(Though, actually it sounds like you were probably seeing #1757, there's a workaround there that may help you. Slowness issues on Linux with the previous 2.4.1 also have a report (multiple, actually) open, I'd recommend searching the Issues.)

**Comment by ferdnyc** [comment]
@lcontic : I did take a look at that log, thanks for taking the (considerable!) time to capture it. Unfortunately, as I feared there's really nothing at all out of the ordinary visible in the log.

I can't believe I didn't think to ask this until now, though: Is OpenShot 2.4.2 the first version you've tried to run on your computer? or was OpenShot previously working for you, and only started having troubles with this new release?

If you haven't tried the previous release, could you please download OpenShot 2.4.1 ([Windows installer](https://github.com/OpenShot/openshot-qt/releases/download/v2.4.1/OpenShot-v2.4.1-x86_64.exe)), and give that a try? At this point I'm wondering if the problem is something new that just cropped up with 2.4.2, or if it's a larger problem that predates the new release. And if you're able to use 2.4.1 for now while we figure this out, then that's at least something...

**Comment by lcontic** [comment]
Hello Ferdnyc - 

Yes version 2.4.2 was the first version I've attempted to use of Openshot.  I've downloaded the previous release 2.4.1 and in the last 2 hours I've attempted to open it twice without any luck.  It unfortunately almost seems worse than the updated release.  I really appreciate all your help up to this point.

**Comment by DylanC** [comment]
@lcontic - Try v2.4.3 and let us know if you still have a problem.
