### ISSUE TITLE
[Needs Fixing] Split Issue

### ISSUE THREAD

**Issue by MisterTeeXD** [OpenShot/openshot-qt#1810]
**Describe the bug**
When a video clip has been splitted, the other part of the video moves somewhere else on the timeline

**System Details (please complete the following information):**
 - Operating System / Distro: Windows 10
 - OpenShot Version: 2.4.2

**To Reproduce**
1. Go to Razor Tool
2. Click on the Razor Tool
3. See error by splitting a video clip on the timeline

**Expected behavior**
A part of the video clip would not jump somewhere else on the timeline

**Screenshots**
[2018-07-07 16-49-01.zip](https://github.com/OpenShot/openshot-qt/files/2172840/2018-07-07.16-49-01.zip)

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**
This was in the first release of 2.4.2 (See attached recorded video)

**Comment by peanutbutterandcrackers** [comment]
Normally I would have called for some more testing but I'll mark this as a bug anyway because while the waveform is visible, OpenShot is known to be quite erratic.

Could you please check and make sure if this problem persists even when the waveforms are not being shown?

Thank you for good report, BTW. :+1:

**Comment by MisterTeeXD** [comment]
Hello, i have just tested this, apparently if you split the clip twice, it will push the other part away from the rest of the other clips

**Comment by peanutbutterandcrackers** [comment]
Not only that but it seems to push it further with every other split. Hmm... Interesting. Thank you, Mr. Tee for this investigation. :+1: 
![screenshot from 2018-07-09 17-36-49](https://user-images.githubusercontent.com/26764547/42448988-c80c4160-839e-11e8-811a-40e2eb741c3b.png)

**Comment by rigues** [comment]
I can confirm the behaviour reported by MisterTeeXD on Linux Mint 19 (Cinnamon Edition) on AMD-64 and OpenShot 2.4.2, installed from the official PPA. Also, like peanutbutterandcrackers reported, the split clip is pushed further into the timeline with every split. This drove me NUTS yesterday while editing a video with multiple cuts. Workarounds are appreciated, if available.

This seems to have been introduced in 2.4.2, since I was using 2.4.1 until two days ago without any problems.

**Comment by MisterTeeXD** [comment]
This issue is officially fixed and Closed

**Comment by MisterTeeXD** [comment]
Reopened issue because its still in the latest version
