### ISSUE TITLE
Fast forward option causes blinking?

### ISSUE THREAD

**Issue by briarmae** [OpenShot/openshot-qt#1811]
Hi, I'm trying to fast forward some screen capture footage. When I apply the x16 (or whatever speed) the program does it fine, though it wont load the preview. It takes forever to render, like 8 hours or so (which I assume is normal since that is a big task) but when I play back the new file the footage "blinks". Every few moments there's a black frame and it's really disorienting to watch. 

Does anyone know of this issue and how to fix it? I assume it is a user issue and not a program issue.

**Comment by peanutbutterandcrackers** [comment]
"Like 8 hours or so"? Whoa. That is a lot of time. How long is the footage, sir? Is it like 2/3 hours long?

I would call this a program issue if the footage isn't that large.

Could you please [attach the logs](https://gist.github.com/peanutbutterandcrackers/d84c257e74b72d8b06b4daffaebc5a14) so that we can investigate? Also, could you please provide us with a sample video of the 'blink'? That should really help us understand this issue. Thanks!

**Comment by briarmae** [comment]
Yeah, here's a video of the blinking [https://youtu.be/3tnO_f8pFVk](url)

I'm re-exporting now to try and make a .log

**Comment by briarmae** [comment]
I'm running windows10. The video I'm exporting is only 5 minutes long (at x16 speed, so the original length is fairly long)

I've just re-installed OpenShot as well, to see if that helps. I think it will, since the exportation been maybe ten minutes and it's already at 23%. Fingers crossed.

**Comment by briarmae** [comment]
Awesome, no more blinking this time! It still took about 5 hours to render. I'm attaching the .log anyways, just in case anyone wants a look.
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/2174180/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2174181/openshot-qt.log)
