### ISSUE TITLE
Question on export and adding together.

### ISSUE THREAD

**Issue by Hunteil** [OpenShot/openshot-qt#1815]
I'm not too experienced in video editing. But I was recommended to use Openshot and have taken a liking to it. I'm editing some footage for a tutorial/demonstration for building some props.

Anyways I have a basic question:
1. I have about 3-4 hours of footage over a dozen mp4's. I just got done all the intro, tools and parts needed lists. I'm noticing my computer is starting to struggle with everything and wondering if I can export video now and start a part2 project to continue my work... I'll probably have 3 parts if I do it this way... Then I'm thinking I can plug those 3 parts together into 1 project and export them again as 1 video. Is this okay? or will it cause the final product to look like dirt? (granted I'm not doing high rez. Only HDV 720 24p then uploading to youtube) I just don't know what is right on that.

**Comment by DylanC** [comment]
@Hunteil - I'm not experienced enough with editing videos to know this. @N3WWN - Any ideas here?

**Comment by N3WWN** [comment]
@Hunteil - You could definitely break up a large video into multiple projects and combine them later.  

If you just need to combine them without any special effects (fades, etc) joining the two, you could use something like ffmpeg (with the concat demuxer and no transcoding) to join them very easily without any changes to the content of each video file.  The codecs used for all 3 would need to be identical, IIRC.

If you'd prefer to use OpenShot to add fades between the videos, that would work as well, and the overhead on the system would be much less since you'd be working with only 3 clips instead of a dozen clips + titles + effects + etc.  If the profile that the 3 parts are created in is `HDV 720 24p` for all three and the profile that is used to combine the 3 parts is `HDV 720 24p`, OpenShot shouldn't need to transcode anything and the quality should be retained.

**Comment by peanutbutterandcrackers** [comment]
Also, a developer (the awesome Mr. Peter - the Dark Knight of OpenShot) has already submitted patches for lossess export for OpenShot. So, pretty soon, we should be able to do lossless exports from within OpenShot and combine the exported videos from within OpenShot. Thought I'd just share a good news here. :)

**Comment by ferdnyc** [comment]
> Also, a developer (the awesome Mr. Peter - the Dark Knight of OpenShot) has already submitted patches for lossess export for OpenShot.

...OOC, where?

**Comment by peanutbutterandcrackers** [comment]
Um... He is like John Cena - you can't see him. Not even in the commit history (because the patches he sends are apparently aren't `git am`-ed). But he is the one who gave us the ffmpeg 3.0 support and is currently working on other cool features for OpenShot. He's an awesome dude. Same ranks as yourself when it comes to contributing to OpenShot. But he only does patches.

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Yup, I talk to him regularly and he has contributed lots but he sends the patches straight to Jonathan. 

@ferdnyc - He really does exist, I swear! 😆

**Comment by peanutbutterandcrackers** [comment]
I have been talking to the BDFL and him about using `git format-patch` and `git am` to do all of that so that he'll at least have some digital footprint in the git logs.

If we see hardware-acceleration in OpenShot in the near future, chances are, it'll be his work.

**Comment by DylanC** [comment]
Closing this question as answered.

**Comment by ferdnyc** [comment]
> He is like John Cena - you can't see him

Can... you not... see... John Cena? 

I've never been able to _miss_ him (though, admittedly, I tend to look **really** hard), he's over six feet tall and enormous! I'm worried you may need your eyesight tested.

**Comment by Hunteil** [comment]
Thank you guys! :-)

**Comment by peanutbutterandcrackers** [comment]
@ferdnyc - Hahaha :laughing:
