### ISSUE TITLE
Issue with Inkscape (Can't try to add emoji.....again)

### ISSUE THREAD

**Issue by rogerio77** [OpenShot/openshot-qt#1820]
OS: Windows 10 64bit
Openshot : 2.4.2
Inkscape Version: 0.92.3
Look the similar error but in Red hat (https://github.com/OpenShot/openshot-qt/issues/1225)
I have to say, this a excelent soft, but I have the similiar problem that I had with linux. 
When I want to modify a "Tittle" (Use Advanced Editor) with inkscape there I got the error  that I will write down. I have added or installed the emoji the emojis (https://github.com/Xaviju/inkscape-open-symbols). When I want to added a emoji to tittle this doesn't appears then in the open shot. Could you tell me how to fix this?
Thanks

**Comment by peanutbutterandcrackers** [comment]
I wonder if it is perhaps because of the lack of support for all of svg features in Qsvg that OpenShot currently uses to render the `.svg` files... Could you please attach the svg file here so that we can test it out? Currently, work is under way for better `.svg` rendering with resvg. But it might not be until `2.4.3` or so that it will be out...

**Comment by rogerio77** [comment]
[archive.zip](https://github.com/OpenShot/openshot-qt/files/2177501/archive.zip)
inside of this you have the svg file requested (just is an example)

**Comment by N3WWN** [comment]
Exactly what I was thinking @peanutbutterandcrackers !

**Comment by peanutbutterandcrackers** [comment]
@N3WWN - I just compiled from your resvg branch and tested the .svg file and it didn't seem to be able to render it right even then... Hmm :thinking:

**Comment by rogerio77** [comment]
Any update or worarround ?

**Comment by N3WWN** [comment]
@peanutbutterandcrackers - What version of resvg are you using?  The version I'm using is from May 15th (specifically, commit 68e5e7b) and renders the emoji:

<img width="906" alt="image" src="https://user-images.githubusercontent.com/19431804/42595477-690d3e0c-8520-11e8-9c18-2febbfbb010b.png">

When I tried the same thing with an older version of resvg, it would no longer render the emoji.

Also, make sure that your build found resvg:

`ldd <path/to>/libopenshot.so | grep resvg`

@rogerio77 - For a workaround, you could use another tool, like Inkscape or ImageMagick's `convert` to render the .svg file to a .png file with transparency and import that into your OpenShot project.  That is what I have done for SVG items which are not properly rendered by Qt's TinySVG implementation.

**Comment by rogerio77** [comment]
Hi
When you said this "What version of resvg are you using?" what do you mean? Inkscape version? as I mentioned above I'm working over windows now

**Comment by N3WWN** [comment]
@rogerio77 - The question about the resvg version was for @peanutbutterandcrackers , not you 😁

**Comment by N3WWN** [comment]
@rogerio77 - I wouldn't say the "next" version.   The changes are still a Work In Progress (WIP) but you can follow the discussion at https://github.com/OpenShot/libopenshot/pull/88 (which was closed due to a recent change in workflow) and https://github.com/OpenShot/libopenshot/pull/143 (the new PR).

Even when the PR is merged into the develop branch code, it will need to be tested before it is merged into a release candidate.  Also, the way the code is configured, even if it is present in a release candidate code, the build system will need to have the required resvg package installed for the published release to have the feature enabled.

**Comment by rogerio77** [comment]
Thanks for your answer and help

**Comment by peanutbutterandcrackers** [comment]
Hmm... true. Probably was just my config issues. I'll have to compile the new PR branch again (and get the latest resvg and compile that too) so it'll be a while before I test it out on my machine....

However, @rogerio77 - this is such a great time to be around! OpenShot is getting better by the day thanks to awesome people like @N3WWN!
