### ISSUE TITLE
Speed up without cutting video

### ISSUE THREAD

**Issue by CluelessPersonOnSite** [OpenShot/openshot-qt#1821]
So I keep trying to speed up my footage but every time I do so, it cuts my video. How can I speed it up but keep all of my footage??

**Comment by peanutbutterandcrackers** [comment]
It isn't really 'cutting' your video, good sir. Because you have sped up your, say 10 seconds long video, it is now only, say, 5 seconds long and that is why it appears 'cut' in the timeline.

If my understanding of your problem isn't correct, please do correct me. I would like to see some screenshots and the final render of the video too. That should be helpful. Thank you!

**Comment by DylanC** [comment]
@CluelessPersonOnSite - All of your footage is still there, it just appears smaller on the track because it plays faster.

**Comment by AnonymousNow** [comment]
Hi, I know this is a necro post, but I'm getting the issue as described by the OP and not by the comments. I don't know what causes it, but the resultant clip from speeding up footage starts at random places in the clips and can be cut down from anywhere to 60% to 95% (est.) from a simple 2x speedup, essentially removing footage. It's devastated my output, since I can't trust any sort of speed up any more and have to manually check them every time to make sure they're not cut - and if they are, I have no options to get around that roadblock.
