### ISSUE TITLE
Audio skipping even though audio sample rate is the same

### ISSUE THREAD

**Issue by AngryFIlly888** [OpenShot/openshot-qt#1826]
**Describe the bug**
My videos have an audio sample rate of 48000, but even though I set it the same in OpenShot it skips.

**System Details (please complete the following information):**
Windows 10
OpenShot 2.4.2

**Comment by DylanC** [comment]
@AngryFIlly888 - Did you sort this by changing the OBS format like in your previous issue?

**Comment by AngryFIlly888** [comment]
No, I didn't have this problem until after.

**Comment by peanutbutterandcrackers** [comment]
@N3WWN - Perhaps you could help out here, sir?

**Comment by N3WWN** [comment]
@AngryFIlly888 - Is this a preview window playback issue or a problem with the audio in the final exported video?

**Comment by AngryFIlly888** [comment]
Preview window backplay

**Comment by N3WWN** [comment]
Awesome!  Now we have something we can work with! 😁 

Depending on the bitrate of the original clip(s) on the timeline, any effects that may have been applied, the resources of your system, etc, the preview window may not be able to keep up during playback.

Try this:  `Edit`->`Preferences`->`Cache`, set `Cache Mode` to `Disk`, set `Scale Factor` to 0.5 and set `Image Quality` to 50 and see if the preview playback audio improves.  

If so, you may be able to tweak these two values to give you audio playback without skipping at a reasonable video quality.

**Comment by AngryFIlly888** [comment]
The problem is fixed, I think. I recorder with a 41000 audio sample rate and set it to 22050 in OpenShot.

**Comment by AngryFIlly888** [comment]
I fix the audio skip by recording in 41000 audio sample rate in OBS and setting it to 22050 in OpenShot.  But now the video is skipping.

**Comment by AngryFIlly888** [comment]
Fix audio. Used 41000 audio sample rate in OBS and set it to 22050 in OpenShot.  But after the video started skipping. I fixed that though. I had to so the same thing I did for the audio. Recorded in 30 Fps and set to a custom profile ( Thanks peanutbutterandcrackers) that was set to 15 Fps.  I started to see the problem.  What ever it be sample rate of Fps, for it to work it had to be cut in half. Don't know why, don't know how. But that is the fix. Sort of.

**Comment by AngryFIlly888** [comment]
P.S. and by sort of I mean I don't know why it has to be half. :)

**Comment by peanutbutterandcrackers** [comment]
That is strange. Perhaps someone will find this scarlet thread and trace it to the bug that is weaving it... Thank you for the information, good sir! :+1:

**Comment by N3WWN** [comment]
This definitely sounds like a resource issue.   My first impression was that it was going to be a CPU bottleneck, which would show improvement by using disk caching and reduced quality.  But, since that made it worse, I think it may be more of an I/O bottleneck.

@AngryFIlly888 Can you open your project in OpenShot, adjust the zoom to show the entire timeline (and all tracks), take a screenshot and add it here?  I'd like to see how much processing OpenShot needs to do in order to create each preview frame.

@peanutbutterandcrackers , what can @AngryFIlly888 use to determine the source clip settings in Windows?  

@peanutbutterandcrackers or @DylanC - Do we have a write-up on how Windows users can open Task Manager, configure it to show all cores with kernel times and remain on top as well as capture a video of the desktop (including sound) so we can see exactly what the user sees sync'd with the resource utilization of the system?

**Comment by AngryFIlly888** [comment]
Here's the screenshot: https://user-images.githubusercontent.com/40869378/42707793-f5e3e26e-86a0-11e8-9d0c-42404e9e1f1f.PNG

**Comment by N3WWN** [comment]
@AngryFIlly888 - So this issue is happening with a single clip with no effects, fades, keyframes, etc?

Hopefully @peanutbutterandcrackers can help with determining how to obtain the info for your source video.  In Linux I'd suggest `mediainfo` (preferred) or `ffprobe`, but I'm not sure on Windows.

**Comment by AngryFIlly888** [comment]
Yes, no effects or anything.

**Comment by peanutbutterandcrackers** [comment]
Hey! Sorry I have been a bit too busy...

[MediaInfo](http://mediaarea.net/MediaInfo) is also available for windows. So that would be my recommendation. Hope that helps! :)
