### ISSUE TITLE
arbitrarily crop video

### ISSUE THREAD

**Issue by fedorovenskiy** [OpenShot/openshot-qt#1831]
I want to crop my video arbitrarily, not only up, dow, right and left. Like in adobe Premiere Pro.

**Comment by peanutbutterandcrackers** [comment]
@N3WWN - Because you have already enhanced an effect, I think you're the best person to call for this one too. :) [Would be really really neat, indeed. I wonder if we could have the up, down, left and right crops have an angle and even the angles could be keyframed. That would be super neat too. We could do all sorts of cool effects. I'm thinking about the Kung Fu Panda 1 Po's training/readying for battle scene.]

**Comment by fedorovenskiy** [comment]
@peanutbutterandcrackers I hope this feature will be soon, because it is very needful and it absent in other linux editors

**Comment by peanutbutterandcrackers** [comment]
@N3WWN - Yeah. He means the ability to have those rectangular bars' angles to be changed. I would love that too. Keyframe-able angle parameters. Would be *awesome*!

@fedorovenskiy - I hope so too, sir. But it might take a while. Please do keep on loving/supporting OpenShot. :)
