### ISSUE TITLE
Exporting video is now slow after 2.4.2 Update

### ISSUE THREAD

**Issue by jimbean10** [OpenShot/openshot-qt#1838]
After Updating to 2.4.2, exporting videos is now abnormally slow. I'm only using jpeg and mp3 files to make videos to upload to YouTube. Were it took around 5 minutes to export its now taking anywhere from 2 to 3 hours and sometimes longer to finish. The average file size after export is 110 mb (HD 720p 25fps 1280x720 MEDIUM Quality). 
Also I should report that when I attempted to export using the SD YouTube profile at low quality the program crashes.

Operating System: Windows 10 Pro
Chipset: Intel I5
Memory: 8gb
OpenShot version: 2.4.2

Thank You for this awesome software.

**Comment by peanutbutterandcrackers** [comment]
This is strange... the newer version now uses multiple cores to render the final video. It should have been even faster.

Could you please [attach the logs](https://gist.github.com/peanutbutterandcrackers/d84c257e74b72d8b06b4daffaebc5a14) so that the devs can investigate on this one? Thanks!

**Comment by bobcrikey** [comment]
Hello, i too have been noticing a slow down for final export rendering, 45fps average .
previous versions including some dev's versions hit 80 fps encoding.
i have a ryzen 1600 6 core 12 threads( 2 threads per core), and 16gigs of ddr4 2400mzh ram.
now im wondering also whether openshot 2.4.2 is being optimized for Amd ryzen chips, especially
 the 1600(mine), 1700,1800 chips.
cheers
  bob

**Comment by peanutbutterandcrackers** [comment]
That is most certainly strange.

@N3WWN @DylanC - Any thoughts? o.O Perhaps this needs some testing...

**Comment by N3WWN** [comment]
Would it be possible for either @jimbean10 or @bobcrikey to download 2.4.1 and 2.4.2 and render the exact same project with the same output settings in both and provide feedback on the time it took with each version and perhaps a screenshot showing how many cores are being used (and how much RAM, while we're at it) while the render is going?

**Comment by jimbean10** [comment]
![openshot cpu](https://user-images.githubusercontent.com/41130109/42655162-2e3fcbe0-85e9-11e8-8ddd-bf16d92aab6a.JPG)
![openshot cpu 2](https://user-images.githubusercontent.com/41130109/42655174-38502e36-85e9-11e8-9e12-abb39bcbfd70.JPG)

after about 50% into the render there is a noticeable drop in the fps. It is at this point is the rendering takes longer than usual. I will attempt to download 2.4.1 later today to perform another test.

**Comment by N3WWN** [comment]
Thanks @jimbean10 !  Could you post the results of 2.4.2 again after first right-clicking in the CPU graph and selecting `Change graph to` -> `Logical processors` as well as selecting `Show kernel times` so we can see how many cores are in use and whether it is userland applications or the Windows kernels that is using the most time on the cores in use?

Also, just over 1/2 way through your video, are you applying additional effects, using more tracks or perhaps the clips have a higher resolution and/or framerate than the ones at the start of the project?

**Comment by bobcrikey** [comment]
hello here are my results from 2.4.2 and bear in mind i use linux 90% of the time for my video encoding.
they are quite mixed, and i have up to 6-7 tracks being used mosty png's and jpeg;s and wav files i also
use tracks 0 and 1 for audio only i have sound effects going in the back ground along with voice talking since i make animations . 

im not using transitions either, im also noticing after playing back the video i sometimes see a brief
picture (like a flash) of another scene somewhere from the time line sometimes at random.
but its not present on the exported video so i assume its a memory flash bug of one of the pngs. 
as it only happens after your start playback of the video several times to make sure everything 
is looking good both video and audio wise, anyway lets keep going :)

now heres the first picture , and things started off well 
encoding 6.8%- 62 fps
![62 fps](https://user-images.githubusercontent.com/40479177/42668329-5d86a1d0-8693-11e8-8c43-abfd39a335f9.png)

encoding 23.3% - 38 fps
![38fps](https://user-images.githubusercontent.com/40479177/42668363-8d131582-8693-11e8-8d5b-5370d6a2edf2.png)

encoding 35% -36 fps
![36fps](https://user-images.githubusercontent.com/40479177/42668376-a4efe0c2-8693-11e8-877a-6d530e686e84.png)

encoding 89.8% -47.75 fps
![47fps](https://user-images.githubusercontent.com/40479177/42668408-c6c25a4a-8693-11e8-8f71-96746e5ef983.png)

i could try to record using my camcorder the screen if that helps but as you can see from my screen
pics, the endcoding fluctuates. going up and down in fps. 

cheers  bob

**Comment by peanutbutterandcrackers** [comment]
This might be related to: https://github.com/OpenShot/libopenshot/issues/114#issue-331491111

It seems that normal export works just fine but when it gets to places where some effect has been applied or a keyframe is being interpolated, only one core does that work and thus it gets slower...

**Comment by N3WWN** [comment]
@peanutbutterandcrackers - I'm not so sure this is the same issue that you encounter where applying an effect puts OpenShot into "single threaded" operation for a while.  Bob's CPU utilization is fairly constant with no single CPU spiking during rendering (leaving the other CPUs starved for work).

@bobcrikey - Does Win10 system monitor include disk I/O graphs?  I wonder if the disk is the bottleneck and times where more disc I/O occur is when the frame render rate decrease.  Do you have any energy saving modes turned on in Windows?  

I don't use Windows, so I'm taking some stabs in the dark based on when my wife **had** a Windows 10 machine and no matter what I did, I could not get _any_ software to use more than about 66-75% of any one core or all cores combined.  I didn't know enough about Windows to get it figured out, but it was enough to abandon Windows for good.  All I know is that Windows wouldn't let any core run faster than about 2.4-2.5 GHz (they were 3.0 GHz cores, IIRC) and would only schedule enough work to occupy about 2/3 of the governed cores. 😭   It's possible you could be seeing the same thing: Windows dynamically controlling how much work is sent to each processor.

Luckily, @peanutbutterandcrackers doesn't seem to have the same issues I had with my wife's machine since his graphs show 100% utilization during the single-threaded portions.

**Comment by bobcrikey** [comment]
@N3WWN i think your talking about now with win 10 system the other bloke using the intel laptop mate,
It was him who showed the win 10 graphs, i use amd ryzen 1600 with 16 gigs dual channel 2400gzh ram

But to add a footnote to this , i have linux installed on a  samsung evo M.2 860 ssd drive :)
although i do dual boot win 10 in the other partition, with the lan cable pulled out , i only use the win 10
partition now for gaming offline, but i will go and do some openshot on that today and look at the graphs and take some pics  and put back a report later today.

**Comment by bobcrikey** [comment]
@N3WWN i was able to export a video on win 10 2.4.2 version perfectly and the frame rate hit 77fps
and it was alot quicker than my linux version,
 but then again i am using the ryzen 1600 chip vs @jimbean10 laptop intel core m 2.5mzh win 10.

Im not too fussed about my linux version  openshot. just i did notice a frame drop rate .
as long as it does the job :)

cheers 
  bob

**Comment by N3WWN** [comment]
@bobcrikey - Sorry, you're right.  I was thinking of multiple users at the same time with similar reports.

**Comment by AdmFubar** [comment]
I wonder if this slowdown is caused by the os updates to mitigate the recently found spector flaws found in cpu's?

**Comment by DylanC** [comment]
@jimbean10 @bobcrikey - Can ye guys try v2.4.3 and see is it better in this aspect?

**Comment by tsimonq2** [comment]
I'm having the exact same issue on the development version of Ubuntu 19.10 (which has the latest version).

I've been facing some OOM problems and it's exactly this.

**Comment by JerryDurand** [comment]
I've got a video exporting now that is running at 0.06 frame per second.  The original file is an avi, there are no transitions or special effects.  Exporting to mp4.

Kubuntu 18.04, latest open-shot through the stable PPA.

**Comment by nifty-coder** [comment]
same

**Comment by DanPinGF** [comment]
@speedytechdev / @JacksonRG - I think I have the same issue despite having enough memory (8GB) and a fast processor (>1GHz). Under Windows, not only does a lengthy project take forever to export the final output, but it also produces a bloated file size (#4077), ranging from hundreds of megs to merely a gig. We're probably gonna have to reinstate this...

**Comment by hitbuyi** [comment]
I have same problem, exporting video is too slow, video with 6 minutes takes half an hour to export, without resolution changing
