### ISSUE TITLE
Crop properties window doesn't consider rotation

### ISSUE THREAD

**Issue by singalen** [OpenShot/openshot-qt#1841]
If I rotate a clip by 90 right (clockwise), "Left" will be cropping on the upper side, etc.

**Comment by peanutbutterandcrackers** [comment]
Hmm... I wonder if that is a problem in and of itself... Do you have any ideas as to how it *should* work? BTW, great to see you back in the forums!

@DylanC - Any thoughts on this. I can confirm this does happen. But wonder if it really is a problem.

**Comment by singalen** [comment]
Thanks. 
Well, cropping on the right should crop the right side of the resulting video, not the source clip.

The source clips could have went through several different transformations/rotations; the user has things to do in their life besides of remembering what source clip was rotated in what way.

This raises a question about the order of effects application, but I believe it has been already resolved in some way.

**Comment by peanutbutterandcrackers** [comment]
Hmm... I haven't had much experience with stacking up effects...

Maybe, a better way would be to have another thing - adjustment layer thingy so that the sum of all the tracks (or a single track - untouched) can be rotated using the adjustment layer? That way, effects won't apply on the clip but on top of it?

But then again, it might take a while before that becomes a reality... quite a while, actually.

**Comment by peanutbutterandcrackers** [comment]
There's also a good discussion about non-destructive editing in OpenShot over at [this thread](https://github.com/OpenShot/openshot-qt/issues/1587#issuecomment-399702934), too.
