### ISSUE TITLE
Resolution of key window elements changes on dual screen systems on Ubuntu 18.04 with Gnome

### ISSUE THREAD

**Issue by dkeats** [OpenShot/openshot-qt#1863]
**Description**
Resolution of key window elements changes on dual screen systems on Ubuntu 18.04 with Gnome

**System Details (please complete the following information):**
 - Ubuntu 18.04 with Gnome Shell
 - OpenShot Version 2.4.2 both released versions and daily builds
 - Desktop resolution for both monitors is 1920 x 1080 px

**To Reproduce**
1. Open Openshot on the left monitor
2. Observe the menus and general text elements will be the expected size, but all other elements are magnified too large to be useable
3. Move the window to the right monitor, the previously magnified elements take on the correct sizes, but the text shrinks too small to be readable

**Expected behavior**
Text and window elements are correctly sized on all screens

**Screenshots**
Shown on the left monitor
![selection_262](https://user-images.githubusercontent.com/1401367/42772340-6b74d4c6-892a-11e8-9907-1f1503b28577.png)

Shown on the right monitor
![- untitled project hdv 720 24p - openshot video editor_260](https://user-images.githubusercontent.com/1401367/42772383-869ef236-892a-11e8-8abc-0bc444cc7f47.png)

**Logs**
Not applicable

**Additional context**
This behaviour is consistent across all versions of the 2.4.2 code, downloaded, and PPA versions, including daily. No other QT applications behave this way that I can see.

**Comment by peanutbutterandcrackers** [comment]
@ferdnyc - Perhaps this might be of some interest to you, sir?

**Comment by ferdnyc** [comment]
I can't say I'm particularly surprised this breaks, to be honest. Did anyone ever test dual-display on Linux? I don't have such a setup. Which is why I also don't have any immediate ideas about fixing it. 

It smells like something boneheaded is occurring in a geometry computation, perhaps one that makes bad assumptions based on screen coordinates/dimensions mapped to the virtual viewport, i.e. the coordinate system where OpenShot's geometry on the left-hand screen is 1920x1080+0+0 and on the right-hand screen it's 1920x1080+1920+0.

OOC, what happens if you _start_ OpenShot on the right-hand monitor?

Oh, and what video card / display drivers are you using?

**Comment by DylanC** [comment]
@dkeats - I can try this on my setup at home to see. I have a FHD laptop screen and FHD monitor.

**Comment by dkeats** [comment]
@ferdnyc - I am not sure how I can start it on the right hand monitor. If I open terminal there, and type openshot-qt, it just opens on the left monitor. Same if I have the terminal on the left monitor, it always opens on the left monitor. 

Interestingly, when I switch to Wayland, the left monitor shows everything big, and the right monitor shows everything normal. Under Xorg, it behaves as I noted in the report.

**Comment by dkeats** [comment]
*ADDITIONAL INFO*

I just downloaded yesterday's daily Appimage build and it works as expected. Previous Appimages would not start, but this one works perfectly as far as geometry is concerned. Hope this is useful to resolving the matter. I will monitor here and test if there is any update.

**Comment by ferdnyc** [comment]
@dkeats – Well, that's good to hear.

Hmm, AppImages not starting was probably #1757, which has since been worked around in the packaging. 

If the previous AppImages would not start, then I take it you weren't able to test this behavior with any of the previous AppImages, correct? Including the 2.4.2 release? I'm just curious to find out if the behavior really changed recently (I can't think of any reason why), or if the AppImages were always OK, and it's something in the native packages specifically.

If you'd be willing to run two tests for us, it'd really be helpful in figuring out what was going on.

1. If I'm correct in interpreting that you hadn't tried any of the previous 2.4.2 AppImages because they wouldn't start, could you download the [2.4.2 release AppImage](https://github.com/OpenShot/openshot-qt/releases/download/v2.4.2/OpenShot-v2.4.2-x86_64.AppImage), and then run it from a terminal as 
follows?
   ```sh
   cd /path/to/wherever/you/saved/OpenShot-v2.4.2-x86_64.AppImage
   export LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libdrm.so.2"
   ./OpenShot-v2.4.2-x86_64.AppImage
   ```

   That should work around a packaging issue with the early 2.4.2 AppImages and let you run it. I'm curious if you have size issues with that build, or if 2.4.2 was always OK when run from the AppImage.

2. I'd like to see Qt's picture of your system, to get an idea of why it's giving OpenShot stupid ideas about how to render things. If you could `sudo apt-get install qttools5-dev-tools`, then run `/usr/lib/x86_64-linux-gnu/qt5/bin/qtdiag` in a terminal and post the output here, that'd give us a really complete overview of things like detected screen geometry, resolution, etc.

Glad to hear you've found a way to get up and running, though, and thanks for updating us!

**Comment by dkeats** [comment]
@ferdnyc  - here is the result os the command  you suggested I run in 2: /usr/lib/x86_64-linux-gnu/qt5/bin/qtdiag > qt-query.txt

I am getting a new machine at the office next week, and it has  an Nvidia graphics card. I will install there and test as well just in case it has something to do with Radeon RX 550 Series graphics.

[qt-query.txt](https://github.com/OpenShot/openshot-qt/files/2216823/qt-query.txt)

**Comment by dkeats** [comment]
@ferdnyc I can confirm that the Release AppImage works with the commands you gave there. The issue seems to be related to native packages specifically. 

Thanks for this.

**Comment by ferdnyc** [comment]
@dkeats — Excellent, and very helpful thanks!

As far as OpenShot running natively on your system, I have to think this must have _something_ to do with the crazy size issues you're seeing (from your `qtdiag` output):
> Screens: 2, High DPI scaling: inactive
> \# 0 "HDMI-A-0" Depth: 24 Primary: yes
>   Manufacturer: 
>   Model: 
>   Serial number: 
>   **Geometry: 1920x1080+0+0 Available: 1861x1053+59+27**
>   Virtual geometry: 3840x1080+0+0 Available: 3781x1053+59+27
>   2 virtual siblings
>   **Physical size: 160x90 mm**  Refresh: 60 Hz Power state: 0
>   **Physical DPI: 304.8,304.8 Logical DPI: 96,96** Subpixel_None
>   DevicePixelRatio: 1 Pixel density: 3
>   Primary orientation: 2 Orientation: 2 Native orientation: 0 OrientationUpdateMask: 0
> 
> \# 1 "DVI-D-0" Depth: 24 Primary: no
>   Manufacturer: 
>   Model: 
>   Serial number: 
>   **Geometry: 1920x1080+1920+0 Available: 1920x1053+1920+27**
>   Virtual geometry: 3840x1080+0+0 Available: 3781x1053+59+27
>   2 virtual siblings
>   **Physical size: 509x286 mm**  Refresh: 60 Hz Power state: 0
>   **Physical DPI: 95.8114,95.9161 Logical DPI: 96,96** Subpixel_None
>   DevicePixelRatio: 1 Pixel density: 1
>   Primary orientation: 2 Orientation: 2 Native orientation: 0 OrientationUpdateMask: 0

Your system is giving Qt the impression that one of your screens is 1920x1080 pixels in 509x286 mm (pretty normal size, and right around the "standard" 96dpi pixel density for computer displays), but it thinks the **other** screen is 1920x1080 pixels in only 160x90mm, which is the sort of pixel density you'd see on a smartphone. (I assume that's not _actually_ true, right? The HDMI-connected display isn't a phone-sized screen?)

To my knowledge OpenShot doesn't _explicitly_ make any attempts to format the interface in real-world dimensions (adjusted to the size of the physical display), but it sure seems like that's what's happening on the left monitor, which I'm assuming is the HDMI-connected, "160x90mm" one, yes?

I'm surprised you say it doesn't happen with any other Qt apps, though, because I'd expect them to be affected similarly. Unless we're doing something uncommon with selection of the interface style. (Though we just use the standard "fusion", which `qtdiag` does show as available on your system.)

I'll do a little more research (read: haphazard googling around), see if I can find other reports of similar sizing issues when Qt apps are run on systems with two screens that have very different sizes / pixel density. But I'm also definitely curious what the actual physical properties of your left screen are, and why Qt (and, presumably, your display server) thinks it's so physically tiny.

**Comment by ferdnyc** [comment]
Heh. Here's a (long, sprawling) bug report of similar issues on Fedora, where openshot-qt gets mentioned as one of the affected apps way towards the end.

It sounds like it's _possible_ running openshot (your native install, not the AppImage) with `QT_SCALE_FACTOR=1` in the environment might help some. Or, at least, if it makes _any_ difference then we'd know it's definitely a DPI scaling issue.

So, if OpenShot is installed natively as `/usr/bin/openshot-qt`, you'd run the following in a terminal window:
```sh
QT_SCALE_FACTOR=1 /usr/bin/openshot-qt
```
I'd be curious to hear whether that has any effect at all.

**Comment by ferdnyc** [comment]
Oh, one more shell command to try, in a freshly-launched terminal session:
```sh
env | grep -i scale
```
I'm curious whether that produces any output. (Which could mean that your user environment contains some sort of default scaling configuration, possibly from an `/etc/profile.d/` script or something.)

**Comment by dkeats** [comment]
Thanks @ferdnyc - that is weird. Now that  you point out this 

Physical size: 160x90 mm

I can see in Gnome settings that my first display thinks it is 7 inches. Clearly this has nothing to do with either QT or OpenShot. The screen is not being correctly detected, even though it looks right. 

Thanks for helping get to the bottom of this. At least I know now that I have to look at the reason for this weird screen detection. 

Oh, and env | grep -i scale did not produce anything.  I will check QT_SCALE_FACTOR=1 /usr/bin/openshot-qt later as I need to first remove the Appimage, but I am using it.

**Comment by ferdnyc** [comment]
> I can see in Gnome settings that my first display thinks it is 7 inches.

Hah! How odd. 

I'm not sure how it's getting set like that in the first place (which is where you'd want to solve this permanently), but you should be able to solve it short-term for the current session using the `xrandr` command.

(Note: `>` is our example shell prompt, don't enter that...)
```sh
# show the configured monitors on the current display
> xrandr --listmonitors

# On my system that outputs
> xrandr --listmonitors
Monitors: 1
 0: 0 1920/512x1200/324+0+0  DVI-D-0

# On yours I'd expect something like
> xrandr --listmonitors
Monitors: 2
 0: 0 1920/160x1080/90+0+0  HDMI-A-0
 1: 0 1920/509x1080/286+1920+0  DVI-D-0

# Then you can reconfigure the undersized one using a similar format
#
# --dryrun will let you test the command, remove it once xrandr accepts
# your command as valid and you want to actually apply the new config.
#
# If the command is invalid you'll get an error, if it's valid you'll get something
# like (though I'm guessing at the specifics, based on my single-monitor testing)
> xrandr --dryrun --setmonitor 0 1920/509x1080/286+0+0 HDMI-A-0
output list HDMI-A-0 DVI-D-0
add monitor HDMI-A-0
output name HDMI-A-0

# Then you can repeat it without --dryrun
> xrandr --setmonitor 0 1920/509x1080/286+0+0 HDMI-A-0
# (...Profit?)
```

That won't stick past the current session, but it will at least let you see if correcting the screen size/DPI will resolve these issues. Good luck!

**Comment by ferdnyc** [comment]
Oh, and if you think we've addressed everything we can on the OpenShot end of things, please feel free to Close this issue.
