### ISSUE TITLE
Property Specification Enhancement: Lock Property Parameters using a toggle-able visual cue (padlock icon?)

### ISSUE THREAD

**Issue by bobcrikey** [OpenShot/openshot-qt#1877]
hello everyone .one thing openshot needs is a green padlock clickable on/off toggle switch
in the properties windows for the sliders especially for loc x/y and scale x/y

as its frustrating sometimes when trying to adjust the sliders and the mouse slightly moves and you 
end up changing other slider.
So a padlock switch locks that particular slider so the values cant be changed or clicked off so its
able to be changed .

I hope this can be implimented in the next version of openshot

heres a picture to show what im talking about

cheers bob
![lock needed](https://user-images.githubusercontent.com/40479177/42951048-aef6cea8-8bb8-11e8-9de1-f767021ca902.jpg)

**Comment by peanutbutterandcrackers** [comment]
Another good addition would be another 'link' icon thingy that would link two properties. If I have scale x and y set to 5 and 10 respectively, and I 'link' them together and change the value of scale x, scale y would change respectively, too. Just writing it down here so that a feature request can be made in the future when the issues are less cluttered.
