### ISSUE TITLE
"Slice > Keep both sides" is keeping just left side

### ISSUE THREAD

**Issue by analogic** [OpenShot/openshot-qt#1895]
**Describe the bug**
"Slice > Keep both sides" is keeping just left side
**System Details (please complete the following information):**
 - Operating System / Distro: Ubuntu
 - OpenShot Version 2.4.2-dev1 (latest daily from ppa)

**To Reproduce**
1. Click on Slice > Keep both sides at video

**Expected behavior**
Both sides at place.

**Comment by Lunardog15** [comment]
what happens if you select slice >keep left side?
Does it act like Slice > Keep both sides?

**Comment by sirex** [comment]
I think this is same issue as described in #1900.

**Comment by peanutbutterandcrackers** [comment]
Any update on this? I know I was using 'keep both sides' recently and it seemed to work just fine.

Or, this just might be related to #1900 

Whatever the case, I am going to take the liberty of closing this issue, for now, so as to control the number of open issues (and because this is probably fixed). If you want to re-open please do.
