### ISSUE TITLE
Weird Export: Duplicated video segment (no effect on audio)

### ISSUE THREAD

**Issue by Patrik356b** [OpenShot/openshot-qt#1909]
Screenshot is comparing frames that should be similar.

Windows 10 - OpenShot 2.4.2

I don't know how to reproduce the behavior.
But this is consistent with this project.

There is a video segment being duplicated before the exported file ends
Audio is unaffected by this bug

**Expected behavior**
1:1 video export which is scaled down

**Screenshots**
https://i.imgur.com/YR2eKRD.jpg

**Comment by DylanC** [comment]
@Patrik356b - Can you attach the screenshot on here? I can't see them on imgur for some reason.

**Comment by Patrik356b** [comment]
![2018-07-23_20-20-08](https://user-images.githubusercontent.com/2000703/43420609-93382754-9444-11e8-8770-de4a73f3d75e.jpg)

Enjoy it @DylanC

**Comment by peanutbutterandcrackers** [comment]
I wonder if this  is happening due to FPS mis-match.

Could you please make sure all the footage you are using to edit the  video is in the same FPS as the current video profile that you are editing in? If not, could you please change the profile to match the FPS of your footages? Perhaps that'll help?

Closing this for now (with prejudice) as it is very likely that you will not come around to the discussions, or that the issue has been resolved in the  latest versions, etc.

**Comment by Patrik356b** [comment]
It's just one video file in this project. I'll have to look at the fps in the file vs OpenShot settings but they should be the same I believe.
