### ISSUE TITLE
Popping audio in Openshot when overlaying multiple audio tracks.

### ISSUE THREAD

**Issue by AndrewK7503** [OpenShot/openshot-qt#1911]
When overlaying multiple audio tracks, in the exported file there is a lot of popping sounds.

Running on Windows 10 on the current version of Openshot.

**Comment by video55** [comment]
Same here I was running on windows 7

**Comment by Patrik356b** [comment]
How's the audio track volume? It might be too close to clipping upon importing.

**Comment by MarcBooster** [comment]
Same probleme here on windows 10

**Comment by Arreaux1** [comment]
Anybody figure out what's going on with audio? 
I get the same thing. Win 10.

**Comment by MarcBooster** [comment]
Problem not solved, and incredibly annoying... whatever sound level I set, as soon as two sound tracks are overlaying, popping sounds happen. Please, HELP ! There is no way we can keep going with openshot with such a problem, it just ruins the entire video...

**Comment by Patrik356b** [comment]
@MarcBooster see my question in an earlier reply

**Comment by MarcBooster** [comment]
@Patrik356b I set both tracks volumes to 10%, and it keeps popping, in both preview and exported video

**Comment by Patrik356b** [comment]
@MarcBooster sorry, I got nothing then.

**Comment by MarcBooster** [comment]
@Patrik356b Thanks for trying :)

**Comment by DylanC** [comment]
@AndrewK7503 - I can confirm this as an issue. Happened to me on Windows 10 and Ubuntu too. Its pretty minor popping for me but well its still popping, so still a problem that needs to be solved. :)

**Comment by asdke1** [comment]
Same problem, Windows 10, tried all I could think but nothing seems to work. please update me if anyone finds a solution

**Comment by DylanC** [comment]
Dup of #1069

**Comment by fabrixx** [comment]
I have this problem again. Is so frustrating because openshot export better video and after one hour of editing i have this popping again with latest release. I have to make several video. For nexts i have to use kdenlive again damn popping. I hope in a solution please.

**Comment by fabrixx** [comment]
I have this problem again. Is so frustrating because openshot export better video and after one hour of editing i have this popping again with latest release. I have to make several video. For next i have to use kdenlive again damn popping. I hope in a solution please. Pop appear random. In some parts are more in other light or disappear

**Comment by DylanC** [comment]
@fabrixx - I hope to make audio a focus for the next release. I see many audio issues lately.

**Comment by fabrixx** [comment]
Pop sounds disappear on exported file. First time for me. I can try with my
others jobs.

Il lun 15 ott 2018, 12:54 DylanC <notifications@github.com> ha scritto:

**Comment by Carolus64** [comment]
Unfortunately I see as in date of 22 Feb 2019 the issue is still present.
I installed OpenShot V2.4.3 for Windows 10 Pro 64 bit in Ryzen 5 computer and GTX1050Ti grapic card.
To practice with program I placed in timeline some MOV clips obtained by a DSLR camera.
The properties for all the clips is the following: 
Video W=1920 H=1080, video codec h264, bitrate 2463376
audio: pcm_s16le, sampling =48000, channels=2 bitrate =1536000
When the clips are overlapped in the timeline to create transitions a cracling sound occurs when the video is played.
The problem occurs only during the transition, inside the clip the audio plays well.
The problem occurs also in exported video.
I hope that you can find resources to work on this problem that makes the software unusable despite the other good features.

**Comment by toonjoey** [comment]
As of June 4th, this still seems to be an issue sadly. It's a major issue for me as I enjoy this software and have a video ready to go right now but the only thing holding it back is the clipping (and some other sounds, but that's unrelated).

**Comment by SuslikV** [comment]
@toonjoey can you post small examples of two files when your issue happens? Please, say amount of clip overlap you trying and transition type if any. The FPS of source files vs project (profile) FPS important.

**Comment by toonjoey** [comment]
@SuslikV Hi there, my apologies for the extremely delayed reply. I'm redoing the video from scratch so I'm able to answer your question.

As of right now, there's only 2 clips overlapping (the music, and a sound effect), with the only transition effect being an extremely quick fade-in on the music at the beginning. I plan on adding some more but it doesn't matter as the clipping still exists even without the extras.

I can't find the FPS for either the source video or the project FPS (but I haven't used this software much so I can't remember how).

Here are some files from the project:
https://ufile.io/r6yv198t Sound effect causing the clipping
https://streamable.com/xk02z Clip from the video (this isn't the same sound effect since I forgot to change it, but there's still noticeable clipping)
