### ISSUE TITLE
Freesound (or others) online site inegration

### ISSUE THREAD

**Issue by jEsuSdA** [OpenShot/openshot-qt#1915]
Hi!
Recently I saw this piece of news about Pitivi:

https://cfoch.github.io/tech/2018/07/24/a-freesound-plugin-for-pitivi.html

I think is amazing the way you can import any sound from Freesound into your project.
So, I think it will be a great feature to do the same with Openshot.

![https://cfoch.github.io/img/posts/freesound-preview.gif](https://cfoch.github.io/img/posts/freesound-preview.gif  "https://cfoch.github.io/img/posts/freesound-preview.gif")

What do you think?

**Comment by DylanC** [comment]
@jEsuSdA - Looks cool! Might be a good enhancement to make.

**Comment by peanutbutterandcrackers** [comment]
I wonder if we should, if we do implement this, ever, do it as a plug-in just like Pitivi and not have it as a core feature. The reason being even though freesound has a lot of sounds that are licensed under CreativeCommons BY-NC, etc. The average OpenShot user, because of the drag-and-drop availability, might not even bother to check the license and that might have some legal repercussions. I wonder how pitivi is going about that route. Perhaps the plugin only lists CC0 licensed sounds?
