### ISSUE TITLE
Slice all selected clips

### ISSUE THREAD

**Issue by rhythmicdevil** [OpenShot/openshot-qt#1916]
**Is your feature request related to a problem? Please describe.**
As a windows 10 user primarily working with music videos I need to be able to play the track and slice video clips with a keyboard shortcut in real time.

**Describe the solution you'd like**
1. Select the tracks I want to slice. Could use a grouping function, but not required.
2. Start playback
3. Press a key combination

When the key combo is pressed the selected clips should be sliced at that point. It must be quick and not cause the audio to pause. This is crucial to keep the timing of the slices in time with the music. 

**Describe alternatives you've considered**
I watched the video on https://www.youtube.com/watch?v=BQS2tmgD_Rk
I tried the tools provided they work as I need them. 
I tried to lock the audio track, and then use CTRL-K but it got sliced anyway. 
I tried to use CTRL-X but it does not appear to do anything.

**Additional context**

**Comment by peanutbutterandcrackers** [comment]
I must admit, I don't quite fully grasp the idea here.

OpenShot does have a (really slow, I admit) slice all function. I just have to click on the playhead and click slice all, and it does the work (slowly).

I think what you are trying to say is:
1. You need a shortcut key to slice all clips. Which seems, to me, to be possible (Edit > Preferences > Keyboard).
![screenshot at 2018-12-12 16-32-02](https://user-images.githubusercontent.com/26764547/49864856-8dbfb480-fe2b-11e8-8f81-7ccda7553003.png)
2. You need almost real-time slicing. Which might happen in future releases as there are just limited volunteers right now in the project and virtually unlimited issues increasing by the day.

But that is what we aim to go towards - virtually real-time execution. Let's hope that it'll happen someday, soon.

Closing this issue with prejudice for now, as I do not think this really is an 'enhancement' request, so that we can keep the number of issues somewhat low. But please do correct me if I am wrong.
