### ISSUE TITLE
Setting persistent locations and scale of images across full clip

### ISSUE THREAD

**Issue by alanrburns** [OpenShot/openshot-qt#1918]
**My Question:**

How can I set the location / scale of an image across the full length of a clip(disable transitioning)?
I find that it is pretty random when you set the location or scale whether it is recognized as a transition or set as a static position. 

All I want is an image in the corner of the video, what I'm getting is an image dancing on the screen.
I have spent a full day on one video with zero results. am I missing something? 

**System Details**
 - Operating System / Distro: Debian 9.4
 - OpenShot Version 2.4.2

**Screenshots**

**Comment by alanrburns** [comment]
So sometimes when I change the location in gets is little square to indicate how it will transition and some time it doesn't.. I'm now on day 2 and repeating the same action gives random results. Does anybody know how I can disable transitioning?

**Comment by alanrburns** [comment]
...Even in the tutorial video it seems to happen https://youtu.be/2sushecqMs4?t=4m24s
Jonathan recommends going to the start of the clip... I'm assume this recommendation was to avoid openshot's assumption that it needs to be a transition. Later in the video he seems to forget to go back to the beginning. That is when openshot starts enforcing the assumption of transitioning. I have found that even when I go to the start of the clip it still randomly decides it needs to enforce transitioning instead of setting the value as a constant across the length of the clip.

**Comment by ferdnyc** [comment]
@alanrburns — Like most video effects and animation systems, OpenShot works on the principle of [keyframes](https://www.openshot.org/static/files/user-guide/animation.html#key-frames), which is how it manages most Clip parameters (including location and scale, the ones set by the [Transform](https://www.openshot.org/static/files/user-guide/clips.html#transform) tool). When dealing with keyframed parameters, OpenShot will _always_ animate between the values at different points on the timeline, if a parameter is set to change over time by the placement of multiple keyframes.

(A "Transition", in OpenShot terminology, is a different type of timeline element, used to connect one video clip to another seamlessly. That's a totally separate thing from the keyframe animation of the various parameters _within_ the clip.)

Anyway, the most important thing to be aware of when using the Transform tool to scale or position Image Clips is this: The parameters you choose will always be applied as a keyframe **at the current position of the Playhead**. That's why it's so important to make sure you position the Playhead at the first frame of a clip, if you wish to adjust it with Transform.

If you select a Clip, position the Playhead at the first frame, and select Transform from the Clip's action menu, whatever size/position you select for the image will apply to the _entire_ Clip, regardless of its length (and even if you subsequently adjust the length). That happens not because that first frame is in any way special, or because it tells OpenShot to apply those parameters to the entire clip — it happens simply because OpenShot will use those parameters for the _first_ frame, and then because there are no **additional** keyframes later in the video telling it to _change_ those parameters, they will simply remain constant. Any parameter set by a keyframe remains in effect, unless a later keyframe modifies it.

Adding any additional Transform keyframes **later** in the Clip (by setting them with the Playhead positioned on a later frame) tells OpenShot that it is supposed to smoothly animate from the values at the initial keyframe to the values at the later keyframe. The only way to get OpenShot to "hold" a parameter for the entire length of a clip is to set one, and only one, keyframe for that parameter, located at the very first frame of the Clip.

**Comment by alanrburns** [comment]
Nevermind I used Shotcut and got it done in a couple of hours with no assumption from the software of my intent.

**Comment by ferdnyc** [comment]
Glad you found something more your speed.
