### ISSUE TITLE
Takes a whole lot of ram

### ISSUE THREAD

**Issue by arunrawat2112** [OpenShot/openshot-qt#1922]
So I am trying to edit a 1080 25 fps video ogv format.. first of all the editiing is really slow. It freezez like 10 sec than works for 5 and freezes again.
Somehow I did the edit part and now want to export to 1080 60fps..
It took all 12 gb ram + 8gb swap and than the computer freezes. This keep happening

**Comment by DylanC** [comment]
@arunrawat2112 - What version of OpenShot are you using?

**Comment by arunrawat2112** [comment]
I am using 2.4.2

**Comment by peanutbutterandcrackers** [comment]
Does this issue still persist in the latest version/daily builds of OpenShot?

Work is underway to fix the issues in Windows platform (which if what I presume you are using) and there will be fixes in the newer releases. Perhaps you might want to wait for the new releases?

Closing this for now, as this might no longer interest you. But please re-open if you want to do so. Although, this issue is being tracked broadly as the devs are well aware of this issue (on Windows).
