### ISSUE TITLE
video pause but not stop the video in general

### ISSUE THREAD

**Issue by goodty1** [OpenShot/openshot-qt#1937]
**Is your feature request related to a problem? Please describe.**
while editing, it can be useful if the editor could stop the video; but on the viewer end, the video still goes. it can improve peoples editing even more to a new level.

**Describe the solution you'd like**
under the effects tab, there needs to be a spot that it has that video pause which does not affect the viewer end.

**Describe alternatives you've considered**
there is not much other ways besides the video being a presentation.

**Comment by peanutbutterandcrackers** [comment]
Please clarify this idea further. It seems you want to mark a certain point in the video without actually stopping the video preview. You could certainly use the 'marker' feature for that.
![screenshot at 2018-12-12 15-44-07](https://user-images.githubusercontent.com/26764547/49861785-cb6d0f00-fe24-11e8-8b14-d170e05cc222.png)

If that is exactly what you were looking for, please close this issue so that we can keep the number of open issues in check. Thanks!
