### ISSUE TITLE
Importing Pictures Crashes Entire Program Every Single Time

### ISSUE THREAD

**Issue by DravenNightingale** [OpenShot/openshot-qt#1945]
**Describe the bug**
Importing pictures crashes the program over and over. Reinstalling doesn't work.

**System Details (please complete the following information):**
Windows 10 x64 , AMD Fx 8370, GTX 1050 ti 4G DDR5, 16 gigs Vengeance Ram, CX 850 PS

**To Reproduce**
Your outline is unclear. Just go to Open shot.
Import Picture.
Watch it crash.
**Expected behavior**
I expected the program to import pictures and not start crashing out of nowhere. Windows movie maker back in my day, had NO issues in comparison to todays industry.

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**
I am a youtuber who is working on getting official media editing software...in the time being I figured I'd try a third party program...not going well so far.. This is a freshly installed OS . I know it isn't on my end in the registry.

**Comment by DylanC** [comment]
@DravenNightingale - Try v2.4.3 and let us know if you still have a problem.

**Comment by speedytechdev** [comment]
**Closing Warning Reason:** inactive

**Comment by DravenNightingale** [comment]
Go right Ahead

**Comment by DravenNightingale** [comment]
Didn’t work anyway

**Comment by speedytechdev** [comment]
@DravenNightingale we can leave the issue open until it gets fixed?

**Comment by peanutbutterandcrackers** [comment]
@DravenNightingale - Since I just noticed you are an aspiring Youtuber, I would recommend the following other Free/Libre Open Source Video Editors to you:
1. https://shotcut.org
2. https://kdenlive.org
Perhaps they might be of some help.

I think we should keep this closed for now as this issue doesn't really provide any insights into the issue itself. I think that with future releases this issue will also be fixed, somehow. At least that is what has been happening on the windows front mostly...
