### ISSUE TITLE
Duration of a clip can be negative

### ISSUE THREAD

**Issue by ywiyogo** [OpenShot/openshot-qt#1956]
**Describe the bug**
I was cutting a 4GB video into several video clips on the timeline area. On a video clip, I can expand the size by moving my mouse to the end of the clip, press left mouse click, hold and move it right or left. Suddenly, I don't see any video of this clip. After opening the properties, I saw that the value of the duration is -550.

**System Details (please complete the following information):**
 - Operating System / Distro: Linux Mint 18., Manjaro 17.1.11
 - OpenShot Version: 2.4.2

**To Reproduce**
1. Go to timeline
2. Click on the end of a video clip
3. Hold and move to right or left
4. Result: Black screen and duration has negative value

**Expected behavior**
No negative value of the duration. 

**Screenshots**
![openshotbug_duration](https://user-images.githubusercontent.com/4080600/43685171-3dcbdb26-98ae-11e8-89c4-ceeb065ebd00.png)

**Logs**
-

**Additional context**
-

**Comment by peanutbutterandcrackers** [comment]
While this certainly is interesting, I couldn't quickly reproduce this by slicing a clip and then extending the left-most clip. But then again, my investigation has not been thorough. But a few things that stand out: Why is the thumbnail broken in your screenshot? Could you reproduce this with smaller clips, too?

 And just out of curiosity - why is channel mapping keyframed? What does it do?

**Comment by morrowsend** [comment]
This is happening to me repeatably while chopping up a large video. It is a major issue because the simply act of cutting, then moving the clip to the left in the timeline causes the duration to be negative. As there is no way to manually override the negative sign, I have to reimport the clip and try to edit it again. 

In one example in my case, the clip starts at 570.58, ends at 629.75 and has a position of 437.21.  Once I move the clip, the duration = -152.58.
