### ISSUE TITLE
Crash on Export for YouTube target

### ISSUE THREAD

**Issue by cgrebeld** [OpenShot/openshot-qt#1961]
**Describe the bug**
Consistent crash on export.

**System Details (please complete the following information):**
 - Windows 10
 - 2.4.2-dev1 

**To Reproduce**
1. Go to Export Video, Target YouTube
2. Click "Export Video"

**Expected behavior**
Crash right away.

**Logs**
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/2260857/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2260858/openshot-qt.log)

**Additional context**
Target Vimeo didn't crash.

**Comment by catnapster** [comment]
Hi. Windows 7 build here. Just confirming that youtube exports instantly breaks the program. I've never had this work, throughout different iterations of Openshot across various setups. I can't remember what workaround I used on my desktop and I'm pretty far from home right now. Just wanted to confirm that yes, Openshot still crashes on export, because you seem to have closed the last "crashes on export" thread despite not solving the problem ~

**Comment by DylanC** [comment]
@cgrebeld - Try v2.4.3 and let us know if you still have a problem.

**Comment by cgrebeld** [comment]
Hi, sadly I still have the problem with 2.4.3.

[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/2496715/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/2496716/openshot-qt.log)

**Comment by catnapster** [comment]
Hey cgrebeld. I found a solution for this, easy fix. I can't remember it offhand. Plz give me a day, there's an easy solution, maybe you'll find it faster than I can respond. In hindsight, it felt so "right in front of my face" that I felt like a dumbass at the time. Brace yourself. But yes, they totally could have made that particular setting a bit more obvious, right? That's going to be a common setting.
