### ISSUE TITLE
Animated Title

### ISSUE THREAD

**Issue by amazonian1971** [OpenShot/openshot-qt#1976]
**My Question:**
 I am trying to make an animated title and i  get the message that i have to check the path to blender. can some one please help me so as to what is correct path. i am using windows 10. what should be done.No matter how many times i put in the correct path it tells me to make sure the path is correct.
i downloaded Blender 2.7.9

![2018-08-11_1602](https://user-images.githubusercontent.com/8660749/43990916-0a843dcc-9d80-11e8-988e-782ee0cb28fe.png)

**Comment by DylanC** [comment]
Dup of #1974

**Comment by UMNVideo** [comment]
I am having this exact same problem. I can not for the life of me figure out how to fix it.

**Comment by michalfita** [comment]
O that's easy - for some reason undocumented and not in any FAQ:
![image](https://user-images.githubusercontent.com/4925040/44399252-d1ba4100-a53e-11e8-9a59-2b53c64c4dfb.png)
Sorry it's in Polish, but still demonstrates the sense.
You need to type full path to blender here, if you installed it after OpenShot.
For example `"C:\Program Files\Blender\bin\blender.exe"`...

BTW the bug here is that OpenShot doesn't allow you to find the binary for both Blender and Inkscape via any form of Open Dialog.

**Comment by Jibo-oh** [comment]
Hi, 
I have the same problem, 
It works 1 time, and after it doesn't work
In preferences of openshot I have the full path for blender 
https://s15.postimg.cc/pgp882uzr/2018-08-19_PB_OSV-_Blender_2.png
The versions of soft are
-Openshotvideo V2.4.1
-Blender V 2.79
Thank's for answers

**Comment by peanutbutterandcrackers** [comment]
This is a known issue that keeps coming up in a lot of instances. Perhaps this needs a good fix. So, hopefully in future releases?

**Comment by DylanC** [comment]
I put in a change to have browse buttons in future. This will work better in newer releases:
https://github.com/OpenShot/openshot-qt/pull/2255
