### ISSUE TITLE
Your video editing software is using WAY too much cpu and memory

### ISSUE THREAD

**Issue by Therizo552** [OpenShot/openshot-qt#1981]
Everytime I run this program it instantly devours my memory and I have seen it hit 12,000 mb at one point. Not only that but it was running in the background at 6000 mb in the background. I do not wish for my computer to melt due to overheating so I would like to know how this can be resolved.
![wth](https://user-images.githubusercontent.com/42325430/44006256-d5e3eb4a-9e46-11e8-82c0-08ac2a997c5e.PNG)

**Comment by Therizo552** [comment]
P.S. that screenshot is actually the lowest amount of memory it took up during its runtime

**Comment by Baldrickk** [comment]
As this issue is open, and the title matches my issue, posting here:

*Describe the bug:*
Excessive memory usage re-encoding 4k video (40GB+)

*System Details:*

Operating System windows 10
OpenShot Version 2.4.2
Intel i7 6700K
32GB DDR4 

*To Reproduce*

1:

Short video (approx 1:30) captured with Nvidia Geforce Experience, native 4K@60fps

Video imported into openshot timeline, trimmed to size, roughly 0:20 of content.

Exporting 4k video instantly attempts to use over 40GB of memory locking up the system for hours. 

2:

Same video clip. Add to time-line.

Right click on clip -> audio -> split to seperate tracks
Similar issue.

Will link file once system is responsive again and uploaded.

*expected behaviour:*
Recommended memory for openshot: 16GB
Expected to operate within this or expand usage to match availiable memory but not use excessive amounts. 

*Screenshots:*
Pending

**Comment by ShurikMur** [comment]
Out of memory exporting a video.

OpenShot version: 2.4.2
Win 7
16G RAM

Exporting project using 4K source video to 1080p. The RAM usage continuously grows until everything crashes. It is just impossible to export my project, it uses whole RAM every single try and crashes.

**Comment by DylanC** [comment]
@Therizo552 - Try v2.4.3 and let us know if you still have a problem.

**Comment by rekcodocker** [comment]
New user here. 
I am running 2.4.3.

The memory usage is enormous.  For a small clip of 1:11, it takes 8GB of ram to render it at 1080p. 
The memory grows and is never released.  
To test, I encoded the same clip twice (same settings).  The first time memory usage grew from 1GB to 8.3GB.
The second encode the usage grew from 8.3GB to 9.6GB.   
So while it does seem to re-use some memory of the first run, I still thing this usage is excessive.
Memory usage only grows - quickly at first, the growth slows down later. But it only goes up, never down.

Final thought: If it can encode the first 10 seconds of the clip within less than 4GB of memory, why does it need 8GB to finish the final 10 seconds?

**Comment by speedytechdev** [comment]
dup of [2237](https://github.com/OpenShot/openshot-qt/issues/2237) This will be closed since the report has information.

**Comment by gabrielpotamianos** [comment]
I faced a similar issue recently. Whenever I would open up the program would be fine, but as soon as I would slice a 5 minutes video it would start to stutter and buffer. 
**_I have solved the issue by converting my originally mp4 video to mvk_**

https://cloudconvert.com/mp4-to-mkv

Have a great one you all!
