### ISSUE TITLE
Display size vs screen size

### ISSUE THREAD

**Issue by NicoleMarieNicole** [OpenShot/openshot-qt#1997]
**My Question:**

I just downloaded OpenShot. The app display does not fit my computer screen size. -OpenShot has a font/layout that is way too big to view on my screen. Is there a way to change display settings to make it fit?  I run a Windows 10 pc with a 13" screen 

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**Screenshots**

**Comment by DylanC** [comment]
@NicoleMarieNicole - Can you provide us with a screenshot?

**Comment by Edelawit** [comment]
It happens to me as well. Just installed the app and I am unable to drop my videos on the timeline because it remains outside the lower side of my screen. 
Is there any way to fix this?

**Comment by peanutbutterandcrackers** [comment]
@Edelawit - Could you please provide us a screenshot so that we could perhaps fix this?

Also, I wonder if you could use the handle that resides between the top and bottom part of openshot and resize the time-line using that as shown in the following screenshot:
![screenshot at 2018-11-26 18-20-37](https://user-images.githubusercontent.com/26764547/49014421-31606200-f1a8-11e8-87a4-558e9415c000.png)

**Comment by pxldevv** [comment]
Need solution as well.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/61668117/236337472-23265a29-b7e4-43d3-b232-fb1a4d0e5898.png">

**Comment by pxldevv** [comment]
This isn't my main computer but I need to use this device. I do not want to change app scale because it makes all the other apps smaller as well.

**Comment by Colorjet3** [comment]
This is a known issue and an internal ticket has been submitted to work on this in a future release.  So, for now, your option is to change the application scale when using Openshot, and then revert back to your default display for all other applications.
