### ISSUE TITLE
problem rotation  [ Read 2nd try which is ok]

### ISSUE THREAD

**Issue by YvanDestruk** [OpenShot/openshot-qt#2010]
**Describe the bug**
I have  picture, track 1 ;  false oriented video, track 2 and well oriented video,  track 3
rotation does not work only for the video 2 which needs to be rotated ???
It works for picture1 and video3 which dont need it !

**System Details (please complete the following information):**
 - W7 64 bits 2009 SP1  [updated 19august2018]
 - OpenShot Version 2.4.2 [20august2018]

**To Reproduce**
1 select video to be rotate  : click right
2. Go to 'rotate'
3. Click on 'all the rotation see below'

**Expected behavior**
rotate 90 Left 

**Screenshots**
my film is > 
I want it ^  ie 90 L
rotate 90 L : it is < ( = rotation 180°)
rotate 180 : it is v (
rotate 90 R : it stayes like it is >

**Logs**
not yet ;)

**Additional context**
Thank you. It's my first try => I will make another to know if it will work fine.

**Comment by YvanDestruk** [comment]
2nd try :+1: for others false oriented videos I filmed with the same ZOOM Q8: All the rotations were OK 
> 90L is ^
< 90R is ^
v 180 flip is ^   
I don't why 1st try did not work. Hope it is not a random issue

**Comment by YvanDestruk** [comment]
Sorry :+1:  1st try is a WIKO Sunny2 / 2nd try is a ZOOM Q8 => sunny2 doen't work

**Comment by peanutbutterandcrackers** [comment]
I do not understand your issue. Could you please attach some screenshots, etc. to explain the issue even further?

Closing this one for the time being because this might not get your attention again. If you come back around, we can always re-open this.

Thank you.

**Comment by Po46n2** [comment]
I have the same rotate issue with a GoPro video.

**Original:**
![original](https://user-images.githubusercontent.com/13472449/53514610-642c3600-3ac8-11e9-8dd4-4ac39351acf4.PNG)

**Rotating it 90 to the right rotates it 180:**
![rotated90rightfromoriginal](https://user-images.githubusercontent.com/13472449/53514642-71e1bb80-3ac8-11e9-8925-1edd25033bbf.PNG)

**Rotating it 180 rotates it 270 to the right. (Or 90 to Left...):**
![rotated180fromoriginal](https://user-images.githubusercontent.com/13472449/53514650-78703300-3ac8-11e9-9421-3b7838edef75.PNG)

**Rotating it 90 to Left doesn't do anything.**

I've found this tag in the original file's metadata: **rotate": "270**
This tag doesn't exist for my properly oriented videos.

Seems like OpenShot replaces this value with the selected one so there is no way to make rotation 0.

If "No rotation" is selected then the video returns to the original orientation so it is still not good. (OpenShot then probably uses the original value that came with the file instead of setting it to 0.)


Properties of the original video:
{
    "acodec": "aac",
    "audio_bit_rate": 189361,
    "audio_stream_index": 1,
    "audio_timebase": {
        "den": 48000,
        "num": 1
    },
    "channel_layout": 3,
    "channels": 2,
    "display_ratio": {
        "den": 9,
        "num": 16
    },
    "duration": 200.1706695556641,
    "file_size": "1955424556",
    "fps": {
        "den": 1001,
        "num": 60000
    },
    "has_audio": true,
    "has_single_image": false,
    "has_video": true,
    "height": 2160,
    "id": "53N3JY70MW",
    "interlaced_frame": false,
    "media_type": "video",
    "metadata": {
        "compatible_brands": "mp41",
        "creation_time": "2019-02-01T12:28:48.000000Z",
        "encoder": "GoPro H.265 encoder",
        "firmware": "HD7.01.01.51.00",
        "handler_name": "GoPro AAC",
        "language": "eng",
        "major_brand": "mp41",
        "minor_version": "538120216",
        **"rotate": "270",**
        "timecode": "12:40:44:46"
    },
    "path": "W:/Picture backups - Clena Up - NOW/GoPro/GX010091.MP4",
    "pixel_format": 12,
    "pixel_ratio": {
        "den": 1,
        "num": 1
    },
    "sample_rate": 48000,
    "top_field_first": true,
    "type": "FFmpegReader",
    "vcodec": "hevc",
    "video_bit_rate": 9768786,
    "video_length": "11997",
    "video_stream_index": 0,
    "video_timebase": {
        "den": 60000,
        "num": 1
    },
    "width": 3840
}

**Comment by Po46n2** [comment]
I have found a way to change the rotation in the original video by changing its metadata using exiftool:
exiftool -rotation=90 video.mp4

This solved my issue but it would still be nice if rotation could be changed from OpenShot for videos having a rotate tag in their metadata.

**Comment by biamorton** [comment]
having same problm as above

**Comment by ferdnyc** [comment]
@biamorton What problem exactly, that you can't get a video with EXIF orientation to rotate? That's #2794, OpenShot interprets "No Rotation" to mean "don't rotate the video" even when the starting orientation is not 0°, which is a bug.

The workaround for now is to set the "Rotation" property to a very small number (e.g. `0.001`), instead of exactly 0.
