### ISSUE TITLE
Downgrading OpenShot?

### ISSUE THREAD

**Issue by jason11892** [OpenShot/openshot-qt#2013]
I have a trashy computer and the new version of openshot is too beefy for it.  Is there a way I can downgrade back to the original openshot?

**System Details**
[Ubuntu 18.04]
[Openshot 2.4.1]

**Comment by cdefy** [comment]
@jason11892 : I found this page with old versions of OpenShot to download. I don't know what it's worth. I tried without success the 2.3.4 for Windows (as 2.4.2 is currently crashing on export). I'll try other when I have time...

**Comment by peanutbutterandcrackers** [comment]
While I think the AppImages from [this page](https://github.com/OpenShot/openshot-qt/releases/tag/daily) might be a solution that you are looking for (on Linux), I don't think downgrading will help you, good sir. The newer versions of OpenShot are, even as they are, a lot better than the old ones... OpenShot, with it's support for 32 bit computers, aims to be not too beefy on older hardwares. And we still have quite a lot of stability related issues, which will be fixed in the future...

**Comment by cdefy** [comment]
Ah thanks for the link @peanutbutterandcrackers  (and sorry looks like I forgot to put the link in my previous message :-s )
Best wishes for the future!

**Comment by DylanC** [comment]
@cdefy @peanutbutterandcrackers - Just so ye know. He is looking for OpenShot version v1, not v2.
