### ISSUE TITLE
Mirroring effect

### ISSUE THREAD

**Issue by mnwstl** [OpenShot/openshot-qt#2030]
Hello!
I searched and did not find how to apply the mirroring effect, that is, the left passes to the right and the right passes to the left. Does anyone know how to do this?

Linux/ubuntu 18.04
OpenShot Version 2.4.2-dev1

This effect has already existed on some day:
![openshot-mirror](https://user-images.githubusercontent.com/22776404/45227419-d1d47380-b296-11e8-9a4f-fab6f53f6f83.png)

**Comment by peanutbutterandcrackers** [comment]
It was in 1.x series. 2.x series is a complete rewrite from the ground up and does not have as many effects as the 1.x series but work is being done to re-implement the effects in 2.x series. But it might not be until a few more releases before ports of the effects starts again. I myself have been wishing for the mirroring effect since quite some time now. Let's hope we get it soon.

Closing this as answered.

**Comment by mnwstl** [comment]
@peanutbutterandcrackers @ferdnyc I searched all the options of the program and got the effect on property / scale x / value, changing from 1.00 to -1.00

**Comment by peanutbutterandcrackers** [comment]
@mnwstl - Whoa that is neat! Thank you for sharing that! I might use it in my next project! I can even keyframe it! Super cool!

**Comment by ferdnyc** [comment]
@mnwstl  Clever!
