### ISSUE TITLE
openshot wont update image sequence video name and wont allow a 2nd image sequence video

### ISSUE THREAD

**Issue by bobcrikey** [OpenShot/openshot-qt#2031]
Hello everyone, i discovered a small bug tonight, i made an image sequence into a video perfectly
and i was able to rename the image sequence video in the project video however.
It will not update on the time line video the new name.

Also once you have completed the image sequence video, if you attempt to bring a new image sequence
openshot wont allow you do this , even after deleting the image sequence individual png's, and
wanting to start a new image sequence video . 

All openshot does is to import the pngs only and 
does not offer to import as image sequence.

heres a picture to show what im talking about
cheers bob

![image sequence wont update name](https://user-images.githubusercontent.com/40479177/44618094-e5550700-a8b2-11e8-87b4-b653d7b0e87f.png)

**Comment by bobcrikey** [comment]
Just an update to this, 13 hours later, i just discovered that the 2nd imported image sequenced
overwrote the 1st image sequence output video that had been renamed in the projects,

So rather openshot ask you "Would you like to replace your current image sequence video yes or no",
it just overwrites it automatically, which is not good.

this needs also to be addressed, 
 iv had to redo my two video  sequences again in two separate projects, 
and export two different videos from the image sequence  and bring them into my main project
as this  slows down openshot using chromakey especially for final render video   :(

bob

**Comment by DylanC** [comment]
@bobcrikey - Good find. Thanks bob! :+1:

**Comment by peanutbutterandcrackers** [comment]
Hmm... this is strange. I was recently importing image sequences too, and things seemed to work pretty well for me.

But the thing is: My `png`s were `%05d.png`s. And secondly, each set of `png`s were housed in a different directory (Image_Sequence_A, Image_Sequence_B) and it didn't over-write anything. Perhaps that information might help out? Not sure if this *really* is a bug.

Also, this might be helpful: https://github.com/OpenShot/openshot-qt/issues/90#issuecomment-197684951

**Comment by ferdnyc** [comment]
Honestly, the image sequence misfeature should not exist, as everything about it is fragile and bad. I'm not saying OpenShot shouldn't be able to import sequences of images, but it should probably do it by rendering them all to a video file immediately and then placing that _video_ on the Timeline. The image sequence mess is... a mess.

One issue is that it probably **shouldn't** have let Bob rename the image sequence at all, since the name of the sequence is part of how it identifies the component images. That may be part of what broke things. Would it be terrible to be forced to work with videos named things like `%02d.png`? Yes, and that's part of why image sequences suck.

As Bob discovered, OpenShot renamed the sequence "but not really", since internally it was still storing the file match identifier that lets it know what files to include in the sequence. That identifier is the **only** thing that's stored regarding the identity of the component images — like, you'd _think_ it would make a list of files and store it in the project file or whatever. You'd be wrong.

Here's how an imported image sequence looks from a project-file perspective, editing out the extraneous properties:
```json
{
   "start" : 0,
   "reader" : {
      "has_audio" : false,
      "type" : "FFmpegReader",
      "video_length" : "25",
      "fps" : {
         "den" : 1,
         "num" : 10
      },
      "has_video" : true,
      "width" : 1920,
      "vcodec" : "png",
      "path" : "blah/blah/images/%02d.png",
      "duration" : 2.5,
      "height" : 1080,
      "has_single_image" : false
   },
   "title" : "%02d.png",
   "id" : "7F3CCHNJ2H",
   "duration" : 2.5,
   "file_id" : "J9DMXXO3QF",
   "image" : "../home/ferd/.openshot_qt/thumbnail/J9DMXXO3QF.png",
   "display" : 0,
   "effects" : [],
   }
}
```

That's _all_ it stores, even in the project file, to be able to locate those images in the future. As you can probably imagine just from looking at it, this is **_incredibly_** fragile. Moving files, renaming files, anything like that has the potential to bring the whole house of cards tumbling down, so I can't say I'm surprised that making use of the image sequence support a _second_ time can also have that effect.

**Comment by peanutbutterandcrackers** [comment]
@ferdnyc - While I do not to disagree with your in-depth knowledge and analysis about the underlying code, and it certainly has it's issues, I am glad that image sequences exists. Perhaps it needs to be worked upon, but it is a really handy feature to have. One thing that I can do using image sequences is that I can use  anything animated in `gimp` into my project. Which is pretty neat. Here's a small script that I wrote that I've been using pretty regularly: https://github.com/peanutbutterandcrackers/ORA2ImgSeq Another thing that I personally love about Image Sequences is that, essentially, everything exported from GIMP using `png`s are lossless. So no quality loss.
Another thing I've noticed is that the blender output - it also seems to be an Image sequence, which I also think is neat.
Maybe you could provide some constructive criticisms as to how Image Sequences could be re-implemented properly? After all, you have most certainly fixed a lot of things about OpenShot that was poorly written in the first place *cough* Tutorial Window *cough* (which, granted, probably triggers PTSD in you).
Speaking of which, OpenShot has moved from slack to zulip and the few devs who are there are pretty active. It is a good way to communicate. Perhaps you could join us. We do get a few news/notices before they are made public. We get to grab Mr. Thomas's attention towards certain things. A really handy thing. Please don't say no!

P. S: I myself have found that often long image sequences tend to have their final images left out of the sequence for some reason but failed to reproduce it on a quick gimp animation just now. I need to do more tests.

**Comment by ferdnyc** [comment]
> Speaking of which, OpenShot has moved from slack to zulip and the few devs who are there are pretty active. It is a good way to communicate. Perhaps you could join us. 

Oh FFS. I am not going to follow this project around from one website to another like some movable feast.

> We do get a few news/notices before they are made public. 

I have no interest in doing non-public development. I'd rather not learn about, or discuss, things if they're not [yet] public.

> We get to grab Mr. Thomas's attention towards certain things. A really handy thing. Please don't say no!

 What, am I supposed to go _**there**_ and argue for my PRs, now, to have any hope of seeing them merged? Why is submitting them _here_ not sufficient? The code lives here. I'm happy to discuss it _here_. If nobody can be bothered, then so be it.

Not just no, but _hell_ no.
