### ISSUE TITLE
using Openshot to edit video clips taken with digital photo cameras and smartphones

### ISSUE THREAD

**Issue by Aryana68** [OpenShot/openshot-qt#2046]
**My Question:** hi
I'm using Openshot to paste short video clips to each other. These clips are taken with 1 Panasonic digital camera { Quick time movie (.MOV) } and another Panasonic camera { AVCHD video (.MTS) & Samsung Galaxy S4 smartphone { MP4 video (.mp4) and Samsung Galaxy S6 smartphone  { MP4 video (.mp4) }. 

I have had no issues with editing video clips taken with the digital photo cameras but i have issues with the editing video clips taken with the samrtphones especially video clips which were taken with Samsung Galaxy S4 smartphone { MP4 video (.mp4) }. 

After i import the video clips from my pc to Openshot, i add them to Timeline of Openshot. Before exporting, i play the pasted video clips with Openshot on Timeline and the issue begings whan the player line passing the place where the clips are pasted to each other. I see a short delay and repeating very fastly audio at that point. This issue is remaining also after it exported to my pc ( end result file) and playing it ( with Windows media player).

Some details and properties of video clips before editing:

Video clips with (.MOV) extentions: ( first Panasonic photo camera )

Frame width: 640
Frame height: 480
Frame rate: 30 frame/second

Video clips with (.MTS) extentions: ( second Panasonic photo camera )
Frame width: 1920
Frame height: 1080
Frame rate: 25 frame/second

Video clips with (.Mp4) extentions: ( smartphones )
Frame width: 1920
Frame height: 1080
Frame rate: 29 frame/second
**System Details**

 - Operating System / Distro: [e.g. Windows 7]
 - OpenShot Version [e.g. 2.4.2]

Thanks in advanced

Saeed

**Screenshots**

**Comment by peanutbutterandcrackers** [comment]
Some of the problems you are experiencing might be partly due to the fact that you are using footage that has 3 different FPS and are editing them in a profile that can't encompass all of them (probably 30 fps). My suggestion would be to convert everything to the same fps. I would suggest that you use something like [avidemux](http://fixounet.free.fr/avidemux/) to convert the frame rates to something equal (like 30 fps for every footage) and then edit them in OpenShot using a profile using 30fps.

However, if that is too much of a hassle for you, you might want to use something like [Kdenlive](http://kdenlive.org/) or [Shotcut](https://shotcut.org/) to do the editing and see if they work any better (which they might). Hope that helps!

Closing this for now as this is kinda' 'stale' and you might not be back. However, if you think this needs to be left as open, please do feel free to re-open. Thanks!
