### ISSUE TITLE
Slow Development

### ISSUE THREAD

**Issue by MisterTeeXD** [OpenShot/openshot-qt#2055]
I noticed that the Development has gone slow, i guess theres a waiting for something?

**Comment by peanutbutterandcrackers** [comment]
Yes, unfortunately, the development seems to be going quite slow. It is because the volunteers - the ones that tackle the issues and bring critical things to the devs attention, and the programmers all seem to be busy right now. However, a lot of the devs will be returning back to helping out with OpenShot soon. That is a matter of excitement for us all. We hope to get the development really going soon. :)

Hope this answers your question.

**Comment by DylanC** [comment]
@MisterTeeXD @peanutbutterandcrackers - I think it's all down to this:

- The Summer was here. People like to go on holidays or have fun doing outdoor things usually. (Developers have lives too 😆)
- Most of the OpenShot development is focused on the hardware acceleration at the moment. #1983 
- Other project items are being worked on to help development such as replacing the Buildkite CI with Travis CI. (You don't need to know anything about these except that it's important and takes time to setup)

Hopefully that clears things up for you. I'm sure things will improve towards the end of the year.

**Comment by MisterTeeXD** [comment]
And for me, i will make sure to have all the patience that i can get XD
