### ISSUE TITLE
Can't edit title font

### ISSUE THREAD

**Issue by SunAlma** [OpenShot/openshot-qt#2069]
When I validate a change in a title font it doesn't work : it always stays on Unbuntu Regular 11.

 - Operating System: Windows 7 64 bits
 - OpenShot Version 2.4.2

1. Right click on a title file > 'Edit title' > 'Change font'
2. Change the font or the font style or the size
3. Click on 'OK'
4. The change is not registered

**Comment by IGWorks** [comment]
I am having these same issues.  I am unable to change the font type and size of titles.

Right click on a title file > 'Edit title' > 'Change font'
Change the font or the font style or the size
Click on 'OK'
The change is not registered

**Comment by ferdnyc** [comment]
@IGWorks 

It works for me, using the latest development code on Fedora 30. Here's what I did:
1. Open the title editor and select the Cloud 1 template
2. Set the font to something distinctive
3. Click Save
4. Dragged the title to the Timeline of a new project, twice on two different tracks just for fun
5. Right-clicked `TitleFileName-1.svg` in my Project Files list, selected Edit Title
6. Changed the font to Times New Roman and clicked Save
7. Moved the Playhead to a different spot on the Timeline, and saw that the preview of my existing title clip(s) updated.

If that doesn't work for you, please do the following:
* Consider trying the latest Daily Build from https://openshot.org/download/ to see if it solves the problem for you.
* Provide details on your OS, OpenShot version, etc. — In fact, consider opening a new Issue using the Bug Report template, which prompts for all of the necessary details. (This existing report is about OpenShot 2.4.2. Which I assume is _not_ the version you're running, since it's from over a year ago).

**Comment by IGWorks** [comment]
Hi Frank,

Check out this video screen capture.  I've done everything that you
suggested.  I'm using Windows 10 Home.

Thanks for the quick response!

https://drive.google.com/drive/folders/1O80xcbI75o5D1o01cjZm5x8wpgIUlLbo?usp=sharing



[image: photo]
*Dave Stevens*
Founder/CEO, IGWorks

720-217-9371 | Dave@IGWorks.com

www.IGWorks.com
<http://www.facebook.com/IndoorGardenWorks/>
<http://www.instagram.com/indoor_garden_works/>
<http://twitter.com/IG_Works>
Create your own email signature
<https://www.wisestamp.com/signature-in-email?utm_source=promotion&utm_medium=signature&utm_campaign=create_your_own>

**Comment by ferdnyc** [comment]
> Hi Frank, Check out this video screen capture. I've done everything that you suggested. I'm using Windows 10 Home. Thanks for the quick response!

Thanks, that was very helpful! I think I know what's going on, now. Couple of things:

1. The font selector always _opens_ on Ubuntu Regular 10.5pt. I'm going to file **that** as a separate bug, if it's not already filed, because it's  just needlessly confusing — but it's merely an interface quirk, it doesn't actually affect functionality. But, long story short, the font that's selected when the font dialog opens has no relationship to the font actually in use.

2. The _size_ selection in the font dialog is ignored; the title templates let you choose the typeface, but not the size. If we could open up a font dialog _without_ a size selector, we would, but I don't think that's possible. So, that's a bit misleading as well, but unfortunately there may not be that much we can do about it.

Now, with that out of the way: Compare the title preview image at [0:18](https://drive.google.com/file/d/1tnQoh1-pfunehew4dmySRC0h1LYAVs4X/view?t=0m18s) vs. [0:31](https://drive.google.com/file/d/1tnQoh1-pfunehew4dmySRC0h1LYAVs4X/view?t=0m31s) vs. [1:00](https://drive.google.com/file/d/1tnQoh1-pfunehew4dmySRC0h1LYAVs4X/view?t=1m00s) — the font _is_ different each time!

That's why I stressed setting the font "to something distinctive" in step 2 of my first comment. When I performed my test, I set the font to a font I have called Vademecum Italic. Then I changed it to Crackman Bold.

Trust me, you _notice_ when your titles go from this:

![image](https://user-images.githubusercontent.com/538020/63645067-a1aefc00-c6c4-11e9-94d0-882f09c59721.png)

to this:

![image](https://user-images.githubusercontent.com/538020/63645075-c2775180-c6c4-11e9-93d0-4220bb79adb4.png)


I think if you perform a similar test, you'll find that the font in your titles **is** actually changing, as well.

(Here's a TrueType copy of Crackman Regular, just in case your system is suffering from SameyFontitis: [CrackmanFont.zip](https://github.com/OpenShot/openshot-qt/files/3537807/CrackmanFont.zip) )

**Comment by IGWorks** [comment]
Frank,

Thanks again for the quick response.  I see now that some fonts work and
some do not.  Check out the video, below.  That, combined with the size of
the font not changing, led to my thinking that nothing was happening.  I
appreciate your help.  Keep on keeping on!

https://drive.google.com/open?id=1c3NVzelNDNhNQwVZhbO6SpgaPFGdXse_


[image: photo]
*Dave Stevens*
Founder/CEO, IGWorks

720-217-9371 | Dave@IGWorks.com

www.IGWorks.com
<http://www.facebook.com/IndoorGardenWorks/>
<http://www.instagram.com/indoor_garden_works/>
<http://twitter.com/IG_Works>
Create your own email signature
<https://www.wisestamp.com/signature-in-email?utm_source=promotion&utm_medium=signature&utm_campaign=create_your_own>

**Comment by ferdnyc** [comment]
> I see now that some fonts work and some do not.

That's a good point, the font selected has to be compatible with SVG, which excludes bitmap fonts — still relatively common to encounter on Windows, though not on Linux or MacOS.

I'm not going to file that as a _bug_, but I'll do some poking around and see if there's a way we can tell the font dialog to exclude bitmap fonts, at least on Windows. It's not outside the realm of possibility that there may be a way to do that.

Glad I could help, and thanks for reporting the issues you were seeing (helps us move towards a better program overall!)

**Comment by ferdnyc** [comment]
All: Since this issue was originally reported for OpenShot 2.4.2, and we've definitively shown that it doesn't still occur in the latest development code (modulo the bitmap font selection thing), I'm going to close this issue as no longer applicable.

**Comment by IGWorks** [comment]
Just one more thing, Frank.  When I click on the Use Advanced Editor
button, I get the following message.  However, I've installed Inkscape and
still get this message.  Any suggestions?

[image: image.png]

Great program in so many ways!  Thanks for providing a nice solution to
those who don't want to spend hundreds of dollars.


[image: photo]
*Dave Stevens*
Founder/CEO, IGWorks

720-217-9371 | Dave@IGWorks.com

www.IGWorks.com
<http://www.facebook.com/IndoorGardenWorks/>
<http://www.instagram.com/indoor_garden_works/>
<http://twitter.com/IG_Works>
Create your own email signature
<https://www.wisestamp.com/signature-in-email?utm_source=promotion&utm_medium=signature&utm_campaign=create_your_own>

**Comment by ferdnyc** [comment]
@IGWorks Whoops, sorry I didn't spot this when you initially sent it.

Unfortunately, GitHub stripped the embedded image out of your email when translating it into a comment, looks like image embeds only work through the web interface.

I can pretty much guess the nature of the message, though.

First thing to check would be the "Advanced Title Editor (path)" setting in the Preferences' General tab. You'd want to make sure that points to the location of `inkscape.exe` on your system. (The Browse button next to the field is the best way to set the location, it'll let you use a file chooser to pick the `inkscape.exe` file.)

**Comment by ferdnyc** [comment]
PR #2948 will fix the font dialog so it remembers previous selections. Unfortunately, as I detail in https://github.com/OpenShot/openshot-qt/pull/2948#issuecomment-524628631 filtering out bitmap fonts isn't really workable.
