### ISSUE TITLE
Distorted line on the right side when importing videos recorded from OBS

### ISSUE THREAD

**Issue by jakehsiao** [OpenShot/openshot-qt#2081]
https://github.com/OpenShot/openshot-qt/issues/1709

The same issue as this one.

When importing videos that recorded from OBS(which are in flv format), there's a distorted line on the right side of the video.

**Comment by mfreeman72** [comment]
I'm seeing this in other video sources, as well, not from OBS, and in mp4 format. I also commented on issue #1709, but it was already closed. This is clearly not resolved.

**Comment by ferdnyc** [comment]
The other issue was closed because, after 6 weeks, the original poster had not provided any of the information we needed to troubleshoot this. And by the time you commented, over a year and 3 OpenShot releases had passed, so the original information was out of date.

This report still provides none of the necessary information. Please open a new issue using the [bug report template](https://github.com/OpenShot/openshot-qt/issues/new?assignees=&labels=%3Abeetle%3A+bug&template=bug-report.md&title=Give+your+bug+report+a+descriptive+title) and fill out **all** of the necessary details, plus which Profile your project was created with in OpenShot.

If possible, also include one or more of the following:
* a link to a sample input file that illustrates the problem
* A [MediaInfo](https://mediaarea.net/en/MediaInfo) report (from the "HTML" or "Text" view) for your input video
* (Failing the above, at least...) The resolution (W×H), aspect ratio, framerate, and exact format (container and codec) of your input video
* An OpenShot project file with the relevant media imported and placed on the Timeline

Screenshots alone are not useful for troubleshooting this problem, which is why #1709 was closed. We _believe_ users when they tell us that their video isn't displaying properly — we don't need proof. And just _seeing_ the distortion doesn't help, when we don't have any information _**about**_ the video that could lead us to figuring out **WHY** it's being distorted.

**Comment by ferdnyc** [comment]
If I had to _guess_ (and I do, with so little information to go on), since so many of the reports of this issue involve some sort of screen captures I'd say that the issue is probably down to differences in aspect ratio between the input video and the output.

For instance, I have a 1920×1200 display. (Which amounts to a 16:10 aspect ratio, slightly taller than the standard 16:9 HD resolution of 1920×1080.) If I were to capture full-screen video and then try to import it into a 1920×1080 or 1280×720 HD project, I'd expect that because my video is taller than the output profile, OpenShot would have to scale it down slightly to fit it in the frame, making it narrower than the output frame.

Both the scaling and the fact that it doesn't reach full width could cause distortion, so to avoid that problem I'd probably set the Scale parameter to None (making it the same _width_ as my output profile), then Transform my video to shift it vertically, so that nothing critical was being cut off at the top/bottom of the frame.
