### ISSUE TITLE
Title 3D halo zoom out does not fit the text well

### ISSUE THREAD

**Issue by Sefran007** [OpenShot/openshot-qt#2091]
**Describe the bug**
Title 3D halo zoom out does not fit the text well with multiline text.

**System Details (please complete the following information):**
1) Manjaro Linux 4.17.17-1-MANJARO #1 SMP PREEMPT x86_64 GNU/Linux
2) Installation method Pacman/Yaourt
3) Openshot 2.4.2
4) melt 6.10.0
5) Blender 2.79 (sub 0)

**To Reproduce**
Generate title 3d halo zoom out with text title:
"My principal title
Subtitle
Author"

**Expected behavior**
http://sefran007.free.fr/wp-content/uploads/TitleFileName0175.png

**Screenshots**
None

**Logs**
None

**Additional context**
I add this with halo_zoom_out.py for correct placement text for rendering.
[halo zoom out.zip](https://github.com/OpenShot/openshot-qt/files/2372341/halo.zoom.out.zip)

```
# Text of halo zoom out
bpy.context.scene.objects.active = bpy.data.objects["Font"]
bpy.data.objects["Font"].select = True
# Mode object
bpy.ops.object.mode_set(mode='OBJECT')
# Center axes of text
bpy.ops.object.origin_set(type='ORIGIN_GEOMETRY')
# Set position of axe x and z to 0
bpy.data.objects["Font"].location[0] = 0.0
bpy.data.objects["Font"].location[2] = 0.0

#Possibility to set camera view to object text size
#bpy.ops.view3d.camera_to_view_selected()
```

**Comment by peanutbutterandcrackers** [comment]
I hope these changes will work with different profiles well (with varying aspect ratios and everything). This is awesome! Please do submit a PR soon so that we can test all of these out. And while making a PR, please do separate your PRs into separate branches according to topics. Like, all these "does not fit the text well" could be grouped into a single branch and a single PR (but maybe with different commits so that each one can be reverted if so required? I don't know) so that it'll be manageable for the reviewers and testers as well. This is epic!
