### ISSUE TITLE
Title 3d picture_frames_4.xml broken to open files images

### ISSUE THREAD

**Issue by Sefran007** [OpenShot/openshot-qt#2096]
**Is your feature request related to a problem? Please describe.**
Title 3d picture_frames_4.xml broken to open files images from os system.

**Describe the solution you'd like**
When i whant use title 3d blender_listview_new.py for generate slide of pictures i can't load pictures.
We need specific tag for pictures.

**Describe alternatives you've considered**
I revolve problem with changing code from openshot interface file openshot_qt/windows/views/blender_listview_new.py.
[blender_listview_picture.zip](https://github.com/OpenShot/openshot-qt/files/2384332/blender_listview_picture.zip)

I had function xml picture for use like this :
file picture_frames_4.xml ->

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE openshot-effect>
<effect>
 <title translatable="True">Picture Frames (4 pictures)</title>
 <description translatable="True">Picture Frames (4 pictures)</description>
 <icon>picture_frames_4.png</icon>
 <category>Video</category>
 <service>picture_frames_4.blend</service>

 <param name="file_name" type="text" title="File Name" description="">
  <default>TitleFileName</default>
 </param>

 <param name="picture_files1" type="picture" title="Picture 1 Path" description="">
  <values>
            <value name="/Bad_Path_File/goodpicture.png" num="0"/>
            <value name="/Good_Path_File/badpicture.png" num="1"/>
            <value name="goodpicture.png" num="2"/>
            <value name="/Good_Path_File/goodpicture.png" num="3"/>
            <value name="/Good_Path_File/badpicture.png" num="4"/>
        </values>
        <default></default>
 </param>

    <param name="picture_files2" type="picture" title="Picture 2 Path" description="">
  <values>
   <value name="" num=""/>
  </values>
        <default>/Good_Path_File/goodpicture.png</default>
 </param>

    <param name="picture_files3" type="picture" title="Picture 3 Path" description="">
  <values>
   <value name="" num=""/>
  </values>
  <default></default>
 </param>

    <param name="picture_files4" type="picture" title="Picture 4 Path" description="">
  <values>
   <value name="" num=""/>
  </values>
  <default></default>
 </param>

 <param name="start_frame" type="spinner" title="Start Frame" description="">
  <min>1</min>
  <max>1</max>
  <default>1</default>
 </param>

 <param name="end_frame" type="spinner" title="End Frame" description="">
  <min>230</min>
  <max>230</max>
  <default>230</default>
 </param>

 <!-- SPEED -->
 <param name="animation_speed" type="dropdown" title="Animation Length" description="">
  <values>
   <value name="Default" num="1"/>
   <value name="2X" num="2"/>
   <value name="3X" num="3"/>
   <value name="4X" num="4"/>
   <value name="5X" num="5"/>
  </values>
  <default>1</default>
 </param>
</effect>

```

**Comment by Sefran007** [comment]
Very better patch
[blender_listview_picture.zip](https://github.com/OpenShot/openshot-qt/files/2383554/blender_listview_picture.zip)

With updated Title 3D Picture frame blender plugin
[picture frame.zip](https://github.com/OpenShot/openshot-qt/files/2383558/picture.frame.zip)

**Comment by Sefran007** [comment]
Need this patch https://github.com/OpenShot/openshot-qt/issues/2095 for working

**Comment by Sefran007** [comment]
With updated Title 3D Picture frame blender plugin
[picture frame.zip](https://github.com/OpenShot/openshot-qt/files/2383614/picture.frame.zip)

**Comment by ferdnyc** [comment]
I've been trying to follow the suggested changes in the patches scattered around these reports (actually, just #2095 and this one, which @Sefran007  indicated consolidates the other four issues linked to), so I extracted the attached files and checked them in on a new `issue-2096` branch in my fork, so that I could examine them in the context of the existing source tree.

I still don't really follow a lot of it, as the changes to the existing source — the ones in `blender_listview.zip` above, particularly — are extensive and I'm not entirely grasping what they do. But if anyone more familiar with the blender-related code wants to take a look at the patches/edits provided here, it's all (I believe, unless I missed anything) consolidated as commits on this branch:

https://github.com/ferdnyc/openshot-qt/tree/issue-2096

**Comment by ferdnyc** [comment]
OK, now I'm starting to get some of it, I think. (Correct me if I get any of this wrong, please, @Sefran007 , I'm trying to explain your code as best I understand it. Obviously, you'd know better than I do how it works.)

@Sefran007 exended the Animated Title editor pretty extensively to support media file selection when building titles. The only title file changed to take advantage of the new code so far is "Picture Frames 4", which now allows the user to select the image files used in the title animation.

![screenshot from 2018-09-24 09-44-12](https://user-images.githubusercontent.com/538020/45955693-93e98600-bfde-11e8-89c4-db596111d429.png)

It's definitely interesting... I'm not sure how I feel about the image selection, and I definitely wouldn't label the selections "Picture N Path" if you're choosing and displaying the actual image file. It would just be "Picture 1", since the user doesn't ever get to actually see the path to the file, they just see the image. Admittedly, that's minor.

A somewhat bigger concern is how much space the picture fields take up, now, what with each one being formatted as a 1-picture list container. I wonder if there isn't some way to take advantage of the container, and just show the four pictures in the _same_ list instead of four separate lists? Then it could just be "Pictures".

Also, one question so far: Why are you intentionally disabling the native file chooser dialog, and forcing the default Qt file chooser? Since the rest of OpenShot uses the native dialogs (on supported systems), it seems confusing to the user if they're suddenly presented with a different file chooser for these files.

**Comment by Sefran007** [comment]
For qt api, It's just than for me it's more easy. 
I'm not a great developper :-)

If for you it's better with openshot api do it :-)

It's just API than i need to do port of somes fun blender example to generate new title 3d.
and also to prepare the future version 2.8 of Blender.

Thanks for this great software

**Comment by Sefran007** [comment]
Also i have also the idea to transform somes blender plugins to scripts API that can mix.
Future features may be.

**Comment by ferdnyc** [comment]
Closing as unactionable, as @peanutbutterandcrackers indicated a PR would be considered for merge.
