### ISSUE TITLE
Problems with animated titles.

### ISSUE THREAD

**Issue by Watashifriki** [OpenShot/openshot-qt#2116]
Hello.
Iam testing what OpenShot offers and i have tried to do an animated title, just for watching hownice they are. But when i choose some of the animated titles offered by OpenShot i get a warning window. I have instaled Blender at C:\Program Files\Blender Foundation\Blender. If i write this path in the preferences window the warning window says that blender is requires, as if i didn't have installed it.
But if in the Blender path i write C:\Program Files\Blender Foundation\Blender\blender.exe, a black window with a prompt is opened and stays as waiting for some commands (but i can't write anything) and when i close that window appears a warning saying that No frame was found in the output from Blender.

How can i solve this problem?

**Comment by speedytechdev** [comment]
@Watashifriki Sorry to get to you so late. Can you fill out the information below to make it easier for us to fix the issue.

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**
Add any other context about the problem here.
