### ISSUE TITLE
Videogrep Feature implementation

### ISSUE THREAD

**Issue by raj6996** [OpenShot/openshot-qt#2174]
https://github.com/antiboredom/videogrep
Developer made only Mac apps, I have Windows OS, so I need to add this option to this editor, CLI was not working for me: https://github.com/antiboredom/videogrep/issues/60. 
Also Visual Editing is more applicable than Command line Editing.

**Comment by ferdnyc** [comment]
Considering OpenShot doesn't even support subtitle tracks, or any textual metadata associated with media files, this would be a pretty major undertaking. Like many video-prep tools, videogrep feels most useful as a tool to employ _before_ importing media into OpenShot.

If the author added the ability to export multiple separate clips, instead of just a single supercut, then that collection of clips would be ready-made for importing into OpenShot. That'd actually make videogrep and OpenShot a pretty natural pairing, in fact. But OpenShot doing the work of parsing the subtitles/transcripts and creating the clips itself? Well... not impossible, but like I said, it'd require a _lot_ of enhancement.

**Comment by raj6996** [comment]
Okay, it completely revamp openshot after implementing videogrep or similar feature, as videogrep author neither respond my issue nor fixed windows issue. MacOSX/Linux(maybe works fine videogrep), so windows no option. will you fix it upper issue within windows? thanks.
