### ISSUE TITLE
Better Transform -- Add Rotation Ability! D:

### ISSUE THREAD

**Issue by astraldata** [OpenShot/openshot-qt#2175]
**Is your feature request related to a problem? Please describe.**
Need a fast/intuitive way to handle transform rotation visually (rather than having to go through Properties dialogue.)

**Describe the solution you'd like**
Transform should allow you to change rotation value when cursor is near the corners of transform boundaries (but not actually touching them).

**Describe alternatives you've considered**
Holding ALT or SHIFT to transform rotation (instead of position) via the corner handles and center pivot.

**Additional context**
http://goinkscape.com/3-ways-to-rotate-in-inkscape/
![image](https://user-images.githubusercontent.com/13861559/46268722-acd3c900-c501-11e8-894a-390e88dff124.png)

**Comment by ferdnyc** [comment]
I think it's a great suggestion, it makes total sense to me that rotation be part of the transform interface. It's a natural fit.

I'd propose a _slightly_ different interface, since Inkscape's is (a) multi-modal, and (partly because of that) (b) somewhat complex and daunting. More complex than necessary , too, since OpenShot only supports center-pivot rotation (at least currently) — and already places a center-point handle on the clip in the Transform interface. So if this is how Transform currently looks when activated:

![transform-currentinterface](https://user-images.githubusercontent.com/538020/46352807-abe98700-c628-11e8-85a6-9a67a58c2f1f.png)

(aside: I never noticed how hard it can be to see those blue handles, on brighter video clips.)

I'd suggest we add a "lever" to that central pivot, extending away from it a short distance in the vertical direction, with another, smaller handle on the end. Grabbing _that_ handle and dragging clockwise or counterclockwise will increment/decrement the Rotation parameter, spinning the video around the center pivot point.

So, instead of the above, Transform now comes up like this:

![transform-rotationhandle](https://user-images.githubusercontent.com/538020/46352970-097dd380-c629-11e8-9200-38d6f7d23395.png)

(I picked yellow to differentiate it from the blue controls — OpenShot's interface already has WAY too much blue decoration, IMHO — and it's only a rough sketch, obviously, but you get the idea.)

And you'd end up with this, if you grabbed on to the yellow circle at the end of the "lever" and dragged it to the right about 45°. (We'd have to figure out how that translates into linear movements, but you'd want to reach at least 90° before you go to the end of the preview area, even if the drag was completely horizontal.)

![transform-rotationhandle_rotated](https://user-images.githubusercontent.com/538020/46353165-87da7580-c629-11e8-97d8-02c94b85b8e1.png)

Note that this is merely a suggestion, same as @astraldata's, inspired by their excellent idea and thrown out there for comment or criticism from anyone interested. There's no timeframe or expectation for such a feature being developed, in any form, unless someone decides to work on it and provides patches to implement it in the code.

**Comment by ferdnyc** [comment]
Oh, heh. This is actually long since fixed, OpenShot 2.5.1-dev has had interactive rotation since the advent of the new Transform interface that was merged in PR #3366 . Closing as delivered!
