### ISSUE TITLE
Te software constantly crashes

### ISSUE THREAD

**Issue by Yiorgoseressios** [OpenShot/openshot-qt#2186]
The (Not Responding) message at the upper left corner is what I get all the time. Especially when I tried to remove the random animation on a 40 photo project. It's a pity for such a nice software.

**Comment by speedytechdev** [comment]
Hi, Could you fill this out it makes it easier for us to work out what is wrong.


**Describe the bug**
A clear and concise description of what the bug is.

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**
Add any other context about the problem here.

**Comment by Yiorgoseressios** [comment]
I work with windows 10 64bit
Open shot 2.4.3

Selecting multiple files. 
Right click.
Select "animate"
Select "No Animation"

Please let me explain. After I added all the photos in my project I decided to add fade and random animation. So I selected them all and with right click I asked the effects to be added at entire project. Then I realized the random animation didn't fit my project and I tried to rove it the same way I added it. Didn't work and the software constantly crashed. Now removing the effect photo by photo works but you understand it takes a lot of time. There is a certain possibility that I did something wrong as I'm new at the Open Shot.
Please notice that all 40 photos I'm working with are less than 1mb size.
Thank you in advance for your help.

**Comment by speedytechdev** [comment]
Thank you for bringing this to our attention. We will ask if we need more information and will work as hard and as fast as possible to sort this issue out. Thank you for helping us good day/afternoon or night.
