### ISSUE TITLE
Garbage

### ISSUE THREAD

**Issue by ghost** [OpenShot/openshot-qt#2189]
Spent a couple of hours making a video. All I did was add audio and text over the footage.
I put everything in place. I watched it over to make sure everything was timed right.

Everything was saved. I'd opened it up a couple of times having taken breaks and all...

And then when it exports it doesn't look right at all. It's as if the clips had scrambled. I open the project file again, same thing. Everything was jumbled and half of the text I'd added was no longer there. It'd show the box but not the text. 

Haven't been able to produce a single video yet with this awful software and after uninstalling it, I never will.

Windows 10, Asus, 8G of ram and all that other useless nonsense.
Just updated the software today.

**Comment by speedytechdev** [comment]
@TyraWadman We are sorry about the terrible experience you have had with our software. If you still willing to help sort out the issue can you please fill out the information below.

**Describe the bug**
A clear and concise description of what the bug is.

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**
Add any other context about the problem here.
