### ISSUE TITLE
open shot crashes after a few seconds

### ISSUE THREAD

**Issue by VicoFM** [OpenShot/openshot-qt#2194]
lunch.exe stop workin (openshot crashes)

**System Details (please complete the following information):**
 - Operating System / Distro: windows 7
 - OpenShot Version 2.4.3

in error details shows this

  Nombre del módulo con errores:	libopenshot.dll
  Versión del módulo con errores:	0.0.0.0
  Marca de tiempo del módulo con errores:	5ba69d8b
  Código de excepción:	c0000094
  Desplazamiento de excepción:	00072cec
  Versión del sistema operativo:	6.1.7601.2.1.0.256.48
  Id. de configuración regional:	2058
  Información adicional 1:	0a9e
  Información adicional 2:	0a9e372d3b4ad19135b953a78882e789
  Información adicional 3:	0a9e
  Información adicional 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by speedytechdev** [comment]
Hi @VicoFM we are missing some key bits of information from you can you please fill in the section below. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behaviour**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**
Add any other context about the problem here.
