### ISSUE TITLE
crashes frequently

### ISSUE THREAD

**Issue by gamernoplay** [OpenShot/openshot-qt#2195]
I was about to finish editing my short film and suddenly it crashed and I lost all of my hardwork, i've spent hours editing on my project. Please fix it.Thanks.

**Comment by speedytechdev** [comment]
Hi @gamernoplay sorry about that. If you have autosave on it should reopen the project when you open Openshot again. If you could fill out the information below we might be able to fix the issue.

**Describe the bug**
A clear and concise description of what the bug is.

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behaviour**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**
Add any other context about the problem here.

**Comment by peanutbutterandcrackers** [comment]
First and foremost, if you aren't using the latest version of the program, you might want to upgrade to the latest `2.4.3` as of today. If a crash occurs even there, you might want to [attach the logs](https://gist.github.com/peanutbutterandcrackers/d84c257e74b72d8b06b4daffaebc5a14) so that we can help you out.
