### ISSUE TITLE
audio issue 2.4.3 - Fade causing missing/distorted audio

### ISSUE THREAD

**Issue by seema84** [OpenShot/openshot-qt#2220]
Windows 7
OpenShot Version 2.4.3

1. set a clip with and a audiotrack
2. set a audio fadeout at the end
3. export this project with 60 fps (or more than 30)

result: the half audio track is missing (not only the fadeout at end)

export with 30 fps works without this problem

**Comment by DylanC** [comment]
@seema84 - I will test this soon. Thanks.

**Comment by bobcrikey** [comment]
@DylanC just as a side note to this dylan, i did some more animation work today and discovered
apon export the audio started off playing well and just faded out on its own and i didnt put a fade effect
in and the audio went really quiet, i tried this on both linux and win 10 same thing, 

i dont know whats going on with 2.4.3 
cheers mate
bob
@seema84 sorry to come into your question/problem but iv been experiencing serious audio probs,

**Comment by DylanC** [comment]
@bobcrikey No problem. I will be testing this one soon. (today)

**Comment by mikelacsa** [comment]
Details from issue [2232](https://github.com/OpenShot/openshot-qt/issues/2232):

Bug

I have literally just downloaded OpenShot, and was experimenting with some video footage I have. At work, I use Camtasia, which was why I liked your user interface, as there are similarities. However, as soon as I dropped a fade-in onto my clip, and pressed play, everything stuttered until the fade-in was finished, then it was fine again. I have plenty of memory, plenty of disk space, and a fast machine, so this should not be happening. I have also tried multiple changes to the OpenShot preferences, including even increasing the allowed memory cache to 10GB, but all to no avail. Can anyone explain why this is happening please, and if there is a solution?

System

MackBook Pro, Intel i7 Quad Core 2.2GHz, 16GB RAM, 750GB SATA HDD, OSX El Capitan 10.11.6, Intel HD Graphics 3000 512 MB (17" display). OpenShot version 2.4.3.

To Reproduce

Drag & drop a fade transition onto a video clip, then play from before the fade.

Expected Behaviour

What should happen, is everything just plays nice & smoothly, but what does happen, is that playback stutters badly, for the duration of the fade, then becomes smooth again immediately after the transition finishes.

Additional Context

I have not tried other transitions, but I'm going to guess that it won't just be the fade it applies to.
N.B. I notice that someone has posted the same issue with a Windows version (#2219), so it would appear to be an issue across platforms.
