### ISSUE TITLE
DVD menu

### ISSUE THREAD

**Issue by Jade123456789** [OpenShot/openshot-qt#2227]
I'm looking for a cross platform open-source program that can burn a DVD to run on a DVD player connected to a TV. It must be able to do the following:
1. Cover image
2. Thumbnail menu to chapters
3. Place time markers

I can make the cover image the screenshots with OpenShot, but I can't combine all 3. Every chapter could be a OpenShot project, but how to manage it at a higher level?

There are some discussions on the OpenShot forum, but none suggest a cross platform program and for me it must work on both Windows and OSX. And also I see no forum register option to join those discussions.

**Comment by peanutbutterandcrackers** [comment]
I think what you are looking for is [Open DVD Producer](http://opendvdproducer.jonata.org/) or  [DVDStyler](https://www.dvdstyler.org/en/); the latter has been "criticized [for] the inclusion of adware in the installer (and the obfuscation of the "opt-out" option) in recent versions", however.

I am afraid OpenShot might not be what you are looking for at all.

If you want more control over the cover image for your DVD, you might want to try out [GIMP](https://www.gimp.org/).

Hope that helps.

Closing this as answered. Please feel free to re-open if you like.

**Comment by Jade123456789** [comment]
Why close  this post and assume OpenShot is not for me? Even the makers of OpenShot have been thinking about adding this functionality. I already have been working with OpenShot and taught my mother-in-law some stuff on her Win laptop. Hence it has to been Win/Mac. For her end goal a DVD menu is preferred. The thumbnails I can make with the "save current frame" option in OpenShot.

The tip for the first link I will definite try out, but the 2nd link is for a Win/Linux trial version.

**Comment by DylanC** [comment]
@Jade123456789 - I don't think realistically Openshot will plan to add this feature. DVD's are not going to be around much longer I think. I can't remember the last time I went out to buy a DVD, its been years and years ago.

I think for this feature using a dedicated tool like @peanutbutterandcrackers suggested would be much better.

**Comment by peanutbutterandcrackers** [comment]
@Jade123456789 - I think what is necessary for us to understand is the culture and tradition in which [Free Software](https://en.wikipedia.org/wiki/Free_software) (Libre Software) like OpenShot comes from. And there is this philosophy, [Unix Philosophy](https://en.wikipedia.org/wiki/Unix_philosophy) that Free Software Developers adhere to. And one tenet of Unix Philosophy is that "make your program do one thing, and one thing only, and make it do said thing well". Thus, the established standard/best practice is to have the program do only one thing. That is why OpenShot doesn't work with titles itself but rather uses InkScape, another Free Software to do it, because that is what InkScape was designed to do. But then again, what the user can do with InkScape inside of OpenShot is pretty limited, and if any good tweaking and manual adjustments are required, the user has to go and use the advanced editor (which basically just opens up Inkscape). Similar with Blender and 3D animation. OpenShot is created to one thing and one thing only - edit videos.

While it is possible to integrate ODP within OpenShot, or at least have a plug-in feature that will let the users themselves integrate whatever they want into OpenShot, I think it will be a long time before that will be done.

But then again, if the maintainer decides to put in ODP into OpenShot by default, this begs the question - why not HandBrake? Why not slowmovideo? Why not vid-stab? Why not GIMP? Why not G'MIC? And next thing you know, we end up with a bloated software. Which is not what OpenShot strives to be. It is trying to be an easy to use, yet robust NLE for everyone.

Also, regarding the Blender and InkScape integration in OpenShot, there are a lot of issues regarding that, too. Tons of rough edges that need to be polished. So, integrating any other program into OpenShot isn't a breeze. Even if it were, you would have to launch ODP all over again if you wanted to do anything serious.

On a brighter side, since OpenShot is a community project, you, sir, could document your work-flow using HandBrake > OpenShot > ODP and perhaps we could add it into our wiki. That would be a tremendous help. You could even consider making YouTube Tutorials regarding this and we could have a separate page in our wiki dedicated to creating DVDs with OpenShot.

We're all in this together. :)

Here is an probably unrelated (kinda') but interesting video: https://www.youtube.com/watch?v=tc4ROCJYbm0

**Comment by Jade123456789** [comment]
I agree to a certain extent to what you say, but although OpenShot is quite a nice program it lacks in certain areas. I haven't used the Inkscape feature yet and I also don't see myself making Blender templates anytime soon.

For my my goals there's input: a DVD -> Handbrake -> OpenShot. Then after finishing there's output: OpenShot -> Open DVD Producer. I haven't use the latter yet and the turtorial will have to wait till I'm more experienced.

For my exercise I have taken an already finished ballet performance and I want to re-edit it. The DVD with menu was given by a third party that recorded the performance and took raw photos. The photos were adjusted and cropped partly by me.

I don't really like the menu and learning OpenShot gave me insight how he made it. Unfortunately I don't have his project files and he probably would have made it in Premiere. Nor do I know if I had them could I convert them for OpenShot. So, I need to clip, maybe split the audio, add green screen animations/screens, etc.

I didn't know the other programs you mentions, but can't GIMP things be done by Inkscape. I personally would use a different program. I just looked what vid-stab is and I might be useful for people without a gimbel. I can see the use of macros in OpenShot, but I'm not familiar wih g'mic. My standard macro would be sort all imported videos, insert them in track 2 and have them perfectly transitioned in 3-4 seconds with a start fade + audio increase and an end fade out and audio decrease.

There must have been a poll of what people would to have and some of them are on the planning board. I'm also thing about subtitles or comments.

**Comment by peanutbutterandcrackers** [comment]
Hmm... there wasn't really a poll or anything. But if you still think this is worth keeping so that the community (or a fork) can further look into it when the right time comes, I am glad to leave this open.

Subtitles are also another popular request which will be looked into; but currently the dev team is busy mostly tackling the bugs and on other must-have features. So, let's see how that goes.

Often, in many Open Source projects, a section of community might want something which the maintainers (and others of the community) might not agree to; this usually leads to a [fork](https://en.wikipedia.org/wiki/Fork_(software_development)). Maybe some fork of OpenShot might want to look into this, too.

Either ways, for now I am re-opening this issue. But I still, personally, do not agree with what might be another step in [software bloating](https://en.wikipedia.org/wiki/Software_bloat), while still being open to the possibility that this is what OpenShot's Asia community might want. :)

**Comment by Jade123456789** [comment]
To avoid bloating is it possible to make a clever shell for my programs that is adjustable, so people can use their favorite ones? So basically it is a button bar on your desktop. You drag your program link in a button slot and lock all buttons option. And if this works put the bar as a small window in OpenShot.

**Comment by peanutbutterandcrackers** [comment]
I wonder if it isn't as easy as that... I have been helping out with OpenShot for months now, and have been actively checking the code base, testing new features, applying patches and customizing by mixing several different forks and yet I still do not understand how this thing exactly works...

Still, thank you for loving and supporting OpenShot. It seems that you are a new user so I think [this guide](https://gist.github.com/peanutbutterandcrackers/f0f666243133e0ed25abbc12a4ba23d7) would be of great help for you in learning all the nuances of OpenShot. :)

**Comment by Jade123456789** [comment]
I just tried Open DVD Producer and I hated it! No templates and after 30 minutes I managed to make a button menu, saved the project and all buttons gone. Also when moving to a different tab everything disappears. Only your video files remain. The button menu making is also very tedious and can't even copy & paste one. I will definitely look for something else. 

What I want is the following:
- add video files (mp4, mkv) that are already clipped at the right positions
- add a background file (jpg) that is like a wallpaper pattern
- add a cover image & add some text on top of it or add a complete image with text
- automatically create pages with preview screen buttons (choose 3, 6 or 9 per page)
- edit the titles of each preview (in case file name were chosen as titles)
- automatically ad previous and next page buttons with multiple pages.

If this is not possible cross platform any Mac version will do.

**Comment by peanutbutterandcrackers** [comment]
Ah! So there's [DVDStyler](https://www.dvdstyler.org/en/) too (which might be more suited to your needs, then). If none of them work for you, perhaps you'd like to file an issue. Here is [OpenDVDProducer's GitHub Page](https://github.com/jonata/opendvdproducer).

An Open Source Software only gets as better as the community makes it. And since DVDs have been falling out of favour (mostly) in the west, perhaps it is up to Asia's community to make sure these Free DVD creators will be in development.

Hope that helps! :+1:
