### ISSUE TITLE
Smallest video format available?

### ISSUE THREAD

**Issue by t3nchi** [OpenShot/openshot-qt#2243]
**My Question:**
I'm trying to downsize my movie collections. But after editing the movies by slicing the parts I don't like, the sliced movie became a lot bigger in size. Could you please tell me the smallest  480p or 720p video format available? Thanks.

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**Screenshots**

**Comment by DylanC** [comment]
@t3nchi - That is a difficult question. I'm afraid I wouldn't know myself. @peanutbutterandcrackers @N3WWN - Do ye guys know of a 480p or 720p profile that would render the smallest file sizes?

**Comment by baptx** [comment]
Related: https://github.com/OpenShot/openshot-qt/issues/2318

**Comment by DylanC** [comment]
@ferdnyc - I'm struggling to find someone who can answer this.. any ideas? 😆

**Comment by ferdnyc** [comment]
Unfortunately, that's not really an answerable question as-is, since the video's size isn't governed by _format_ as much as it's governed by _quality_ settings.

The most **efficient** of modern codecs, meaning best quality:bitrate ratio, is going to be x265. (Aka HEVC, "High-Efficiency Video Codec" — one of those rare occasions when naming something after a quality actually means it _has _that quality, not the opposite. Looking at you, "Quality Inn".) If your player supports decoding x265 video (and your graphics hardware supports decoding it in hardware, which only fairly new graphics cards will) then that's likely to be the best choice. However, OpenShot doesn't currently have any x265 encoding presents. (Note: It probably should.) It can probably be manually configured to encode x265, but I've never tried it. Not sure if anyone has.

If x265 isn't on the table for any of a number of reasons, your best bet is going to be x264. (aka AVC, "Advanced Video Codec", which USED to be true, until further advancements like x265 eclipsed it. Today, not that advanced, but still very good and with excellent hardware support.) It's also the same codec the original files were almost certainly encoded with. x264-encoded video is going to be basically the same size whether it's in an MP4, MKV, or whatever other container, that's pretty much immaterial. So it really all comes down to bitrate.

There's also the question of audio, which is admittedly tiny compared to video no matter what. (My 1080p movies typically have 5.1-channel 48kHz AC-3 audio streams @ 640 kb/s, and still the audio is only 5%-6% of the total file size. Of course, the total file size for a 1080p feature-length movie can be > 10 GB, because the video bitrate is over 10 Mb/s.) Still, you want to be careful that you're at least preserving the same number of channels as the original file.

Re-encoding the video and audio is never ideal, but when you're using OpenShot to chop a file up it's unavoidable. What I'd generally recommend is using a tool like [MediaInfo](https://mediaarea.net/en/MediaInfo) to examine the original file (switching to its HTML output mode for the most detail), looking specifically for key data about the streams: 
* Video Format (but it'll be AVC > 90% of the time)
* Video Frame rate (as a fraction, something like 24000/1001 which is 23.976 FPS)
* Video Bit rate (in kb/s or Mb/s).
* Audio Channels (2, 6, or 8)
* Audio Sampling rate (48kHz or 44.1kHz)
* Audio Bit rate (in kb/s)

Then when it comes time to Export, whichever output preset you choose as a starting point, switch to the Advanced tab and use the Profile, Video Settings, and Audio Settings subtabs to match the original configuration. Every single parameter I listed above is directly settable through the Export > Advanced tab. 

OpenShot's presets tend to err on the side of excess: Low is basement quality, while High is excessively high quality, which means excessively large file sizes. Medium... is middle-of-the-road, but depending on the original file's quality will most likely make it either much larger, or much worse looking. Whereas the intent of High is very much to sacrifice disk space for quality. If you want to go in the opposite direction, without the files looking _terrible_ (which they will if you pick Low), I'm afraid your best option is to manually configure the Export settings so they approximate the input.

**Comment by peanutbutterandcrackers** [comment]
I guess @ferdnyc's answer is the best one.

However, @t3nchi, if you want to downsize your video collection to 480p, and are using a GNU/Linux machine, please feel free to use [this script](https://github.com/peanutbutterandcrackers/chiyoko). It is very generic, but does the job. I downsized some hundreds of GB of lossless avi files into 40 or so GB of file using the script. Perhaps it'll be of some help to you too.

Closing this for now. If you need any further assistance, please do feel free to comment and/or re-open. There might be some other batch-processing programs too, that I may not be aware of, however. But as long as you keep all your 'i-need-to-downsize-this' movies in a single folder, and give the script that folder, it should do the job for you.

**Comment by ferdnyc** [comment]
OpenShot is definitely not the right tool to use for _merely_ reencoding videos unedited. that script is a great example of Excessive Python Use, sice it basically boils down to the this shell script:
```bash
mkdir -p converted
for file in *.mp4 *.mkv *.avi *.mov *.wmv; do
  ffmpeg -loglevel quiet -i ${file} -s hd480 -c:v libx264 -crf 23 -c:a aac -strict -2 \
  converted/${file%.*}.mp4
done
```

(Yeah, the script can process a directory filled with a mix of images and videos together, but... why would anyone actually want to do that?!? To me it seems like more of a bug than a feature.)

But @t3nchi mentioned editing out parts of the videos first, in which case a simple conversion script won't suffice. For that scenario... OpenShot probably **IS** one of the easier ways to edit out _pieces_ of a video, then join the rest back together into one file, all in one step. Other tools like [VidCutter](https://github.com/ozmartian/vidcutter) can chop up a video _without_ reencoding (if you only cut on keyframes), but then you'd still have to reassemble the pieces afterwards using a different tool. And if you **do** also want to reencode at reduced quality/filesize, then you need _another_ step for that.

**Comment by peanutbutterandcrackers** [comment]
@ferdnyc - lol That was exactly what I wanted the script to do. Had too many random JPEGs of huge size that I was too attached to delete but too indifferent to probably even look at so that was the solution.
