### ISSUE TITLE
v2.4.3: default title name overwrites old ones...

### ISSUE THREAD

**Issue by valterfukuoka** [OpenShot/openshot-qt#2247]
**Describe the bug**
Creating a new title, the default title auto naming is not incrementing from the last number...

**System Details (please complete the following information):**
 - Operating System / Distro: Debian 9 Stretch, x86/64
 - OpenShot Version [e.g. 2.4.3 app image for linux]

**To Reproduce**
1. open new project
2. create 2 new titles
3. close openshot
4. run openshot again, open the project
5. try to add some more titles...

**Expected behavior**
if the last created auto name title is "2", then the new one is expected by be "3"...

**Screenshots**

![overwrite-a](https://user-images.githubusercontent.com/5293980/47060958-805ec300-d20a-11e8-8bf5-34f294505ecb.png)

![overwrite-b](https://user-images.githubusercontent.com/5293980/47060963-86ed3a80-d20a-11e8-8488-0407e731bf89.png)

Thanks,
Valter Fukuoka

**Comment by DylanC** [comment]
@DerGenaue - Can you have a look at this? In #2042 did you cater for this scenario?

**Comment by DerGenaue** [comment]
Nope;
the underlying issue is the one I have described in #2041 :
OpenShot has a temporary working directory for all the assets and another directory right next to the project file.
Upon saving, all relevant assets are moved from the temp directory to the project dir.
This, unfortunately also means that creating new assets will ONLY CHECK IN THE TEMP dir and thus not consider any files in the project dir.
