### ISSUE TITLE
Future wishes

### ISSUE THREAD

**Issue by Jade123456789** [OpenShot/openshot-qt#2249]
I'm a new user to OpenShot and I want to know what you guys think what you would like to see in OpenShot. This is my list that might already be mentioned elsewhere, but I also want to see what kind of users we have and their needs. All I seek has to be open source cross platform!

I'm 55 years old graphic designer using a Mac and I recently taught my 69 mother-in-law to work with OpenShot on her new Win10 laptop. So, my knowledge is limited and to enlighten me I decided to re-edit a ballet performance DVD with menu. And everything I seek has to be cross platform open source. Also to help her I made the User-Guide of OpenShot into a printable PDF, which she printed out.

I used Handbrake to convert vob to mp4, which was a lot faster than VLC Player (I also didn't know you could convert them in it). It worked well in OpenShot except the video clip on the track was stretched. I fixed it with properties layout "show all (distort)". And later I will use Open DVD Producer to make the menus.

I'll probably use a Blender template for the title and a credits animation for the end. If there are any users that made their own ones let me know. I'm also thinking of making an animation of curtains with Blender, but  I don't know if there is a tutorial to make Blender templates to use in OpenShot.

I am also thinking about subtitles and/or comments. I probably can make fixed ones using jpgs with a green screen and a chroma effect and place them in a specific time frame. I also want a credits animation at the end. is there a program to create soft subtitles?

And adding a semi transparent watermark in a corner might need an opacity property. I also have this idea  where I want the background chroma-keyed and the foreground as well. Normally I would use a single chroma effect for the background, export it, import it again and do a new chroma effect for the foreground. Or is that possible to do at once using 2 different colors? The result is a video background and a different animated video foreground.

**Comment by peanutbutterandcrackers** [comment]
I think I can offer a few help here:

1. [This zero to hero OpenShot guide](https://gist.github.com/peanutbutterandcrackers/f0f666243133e0ed25abbc12a4ba23d7) will help you out a lot.
2. [This video shows a workaround for subtitles in OpenShot for now](https://www.youtube.com/watch?v=nNSf7CMFFWY).
3. [This video shows how rolling-credit animation can be achieved in OpenShot](https://www.youtube.com/watch?v=Mu_LdG_Tnpc); please note - it shows OpenShot1.x series. But the concept is similar for OpenShot 2.x series, esp. once you go through the guide mentioned above.
4. If you are going to use pictures for subtitles, you should probably use `.png`s instead of `.jpg`s as `.png`s support transparency.
5. It is indeed possible to drop more than 1 chroma key effects into a clip. I reckon that you could have some key out a certain colour while others to key out others.
6. Semi-transparent watermark can be achieved by adjusting the `alpha` property of the watermark image clip. `alpha` is the Opacity property. Once you go through the guide mentioned in `1`, you should be able to leverage all that OpenShot has to offer.

Also, on a personal note, if you are teaching your 69 year old grandma, something like [Elementary OS](https://elementary.io/) might be more user-friendly than Microsoft Windows 10.
Also, how did you make a pdf of the OpenShot user guide? I'm curious. May I see the pdf please?

Hope you create amazing videos using OpenShot, good sir!

**Comment by Jade123456789** [comment]
Before I started with OpenShot I saved the the 5 tutorial videos and recreated the exercise files. My mom's laptop came with Win10 installed. i also watched a Win10 quick tutorial as my latest Windows experience was Win7. Thx for links. I'll properly look at them later. As fir point 4 I tested a png with black text and in OpenShot the whole screen was black.

I have to test it properly, but let's say I have an image with circle in blue and a background in green. And in each of the shapes I want a different video, which I put on below tracks. The chroma effect on the the top track 3, but how do I tell OpenShot chroma effect 1 is for track 2 below and effect 2 is for track 1 bottom? I could use a mask (which I still have to learn), but I plan to have the top track be an animation instead of an image.

With ILL I made the guide from the web pages. I haven't figured out how to pm you and then I can send you a wetransfer link.

**Comment by peanutbutterandcrackers** [comment]
> As fir point 4 I tested a png with black text and in OpenShot the whole screen was black.

That is because 1. OpenShot Renders Transparency as black. 2. And your text was black on top of black. However, if you use another clip below the track where the `.png` file is put, you should be able to see the black title, and the clip below too. PNGs!

> Is it possible to slow the movie down, reverse it (if I only have an opening animation and I want a closing one), or to put a part in loop (like the curtain is moving a bit closed)?

Yes! Just right click the clip, Time > Normal > Backward > 1x. [Slower/Faster in the same general area]
![screenshot at 2018-10-18 19-52-05](https://user-images.githubusercontent.com/26764547/47160314-60fd8e00-d30f-11e8-9d7f-18b71ad41c88.png)

> I have to test it properly, but let's say I have an image with circle in blue and a background in green. And in each of the shapes I want a different video, which I put on below tracks. The chroma effect on the the top track 3, but how do I tell OpenShot chroma effect 1 is for track 2 below and effect 2 is for track 1 bottom? I could use a mask (which I still have to learn), but I plan to have the top track be an animation instead of an image.

I must admit, I do not understand what you are trying to say. But I would suggest you use [GIMP](https://www.gimp.org/)'s [foreground select tool](https://www.youtube.com/watch?v=uhRGix-x5Mg&t=368s) to separate the blue circle from green background and export 2 separate `.png`s with transparency and import them into openshot.

Ah! wait, I understand it now. What you need to do is apply 1 chroma key effect (say for making a video appear in the background. Make sure you leave 1 track empty in between the two tracks (the one being chroma keyed and the background video). In middle of the two, put the other video that you want to appear in the circle, and use a [mask](https://www.youtube.com/watch?v=Hd9k3x0diOo&t=1s) --- you can create the mask in GIMP using a screen-capture of the project (generated by the screen-capture tool in OpenShot - the camera icon below the video preview) --- to mask the other video (that you want to show in the circle) in. Please note that you might have to figure out how to use mask properly here (I don't know much about masks either - haven't really worked with them). In theory, this should give you the result you are looking for. But there's quite a bit of learning that you are going to have to do. Also worth noting is the fact that if you want the video (that you want in the circle) to be circular (or something similar) you might have to tweak the clip's properties (scale and stuff) to fit your needs. The Zero to Hero OpenShot guide should be a lot of help here.

Good luck!

**Comment by Jade123456789** [comment]
I just tested it and a png with a red circle on a transparent background on the above track shows a red circle on the bottom background. And the same with a black circle.

What I tried to do is the following with a red circle on a blue background. With chroma key 1 I make the blue background transparent and on that result I want to do a chroma key2, which is impossible as the lowest track is blocked by the middle unchanged track. The simple way of doing this is export the 2 tracks and import the result on which you add chroma key 2. For a simple non moving image a mask could do, but I like to keep it simple.

I have a transition in mind where dancers are the background. Then for example a vertical rotating circle fades in (circle - elipse - thin elipse - elipse - circle) with the next dance act in it. The background dancers fade and the circle becomes full screen.

I'll make the rotating circle animation first, then put that on top of dancers 2, chroma keying and exporting. Now I put that result on the top track, dancers 1 on the middle track and dancers 2 copy unchanged at the bottom. So when dancers 1 fade out animation dancers 2 + unchanged dancers 2 will both be visible and it will look like the circle animation disappears. After fade out of dancers 1 is complete I can stop the dancers 2 animation on the top track.
