### ISSUE TITLE
Animation requires left/right center option

### ISSUE THREAD

**Issue by andrewcharnley** [OpenShot/openshot-qt#226]
A minor issue, I can set the animation to bottom edge to center and then use gravity to pull left, but it make sense to have a left edge to center left edge that does this operation in one go.

**Comment by Kagetsuki** [comment]
@andrewcharnley I think that may be confusing when you also consider you can set coordinate offsets. Positioning is a little too CSS like as it is - with multiple conditions stacking and modifying each-other. I think adding multi-operation magic to the mix could lead to a lot of headaches and issues with confused people.

What I DO think we should have is the ability to create positioning profiles or templates. EG if you are always positioning an overlay element in the same place you currently have to remember all the position and sizing settings and manually re-enter them. If we could save them to a profile or at least copy them in one shot that would be pretty handy - and that would essentially give you the functionality you're looking for because you could just save a center-pulled-left profile and re-apply it to whatever you need to.

**Comment by andrewcharnley** [comment]
Or perhaps a start/end screen box where you can click one of the 8 positions?

**Comment by Kagetsuki** [comment]
@andrewcharnley That would be handy.
