### ISSUE TITLE
[Minor] Moving Images Is Laggy

### ISSUE THREAD

**Issue by MrTeeXD** [OpenShot/openshot-qt#2290]
**Describe the bug**
When you want to Transform the image of video clip, it will lag and its impossible to smoothly move the clip or image.

**System Details (please complete the following information):**
 - Operating System / Distro: [Windows 10]
 - OpenShot Version [2.4.3 Latest Daily Build]

**To Reproduce**
1. Go to your video clip
2. Right Click and select Transform
3. See error by moving the image or Video Clip

**Expected behavior**
It should not be laggy when the image or clip is being moved

**Screenshots**
None

**Logs**
None

**Additional context**
This is in all the Openshot versions

**Comment by peanutbutterandcrackers** [comment]
I think this issue has more to do with the transform tool rather than the lag. I think the transform tool needs to be polished a little more, overall. For the time being, I find it that adjusting the key-frames manually from the properties tab is the best way to go about making size changes.

If you do not mind, I think this can be closed (and the topic followed on either A. Preview-related topic and B. Transform-tool-related topic)

Thank you!
