### ISSUE TITLE
Dropping and exporting a video doesn't export any audio with it

### ISSUE THREAD

**Issue by Nanashi3891** [OpenShot/openshot-qt#2294]
**Describe the bug**
Simply dropping a video in, trimming it and then exporting it at a lower quality than the original seems to remove the audio or at least the audio isnt being exported

**System Details (please complete the following information):**
Windows 7, Latest version for windows 2.4.3 
**To Reproduce**
Drag and dorp a video (.mp4)
Trim it (possibly dont need to, havent tested)
Export it
Load video and there is no audio

**Expected behavior**
I expected that I could simply export the video and keep the audio

**Additional context**
Sorry if this has been covered, tried searching but there are too many issues with "audio" to look through them all

**Comment by peanutbutterandcrackers** [comment]
The audio is there but your media player is unable to decode the stream. Please try using VLC Media Player instead. Also, you could use [HandBrake](https://handbrake.fr/) to transcode your render so that all media players might be able to play the sound. This is a known issue and will, hopefully, be addressed in the next release.

Hope that helps.

Closing for now. Please feel free to comment/re-open as needed.
