### ISSUE TITLE
Import video or audio files

### ISSUE THREAD

**Issue by FrankDP** [OpenShot/openshot-qt#2295]
**Describe the bug**
When I try to import a video or audio files, the program closes.
Files are not imported

**System Details:**
 - macOS 10.13.6
 - OpenShot Version 2.4.3

**To Reproduce**
1. Go to File
2. Click on Import file
3. Select video or audio files
4. Click on Open
5. See error

**Comment by PVH-GiantGuy** [comment]
I just installed OpenShot on my iMac, running macOS 10.13.6. Built a project file. OpenShot launches, goes thru Tutorial. I can import photos, but when I try to import audio or video files (I tried .mp4 and .wvm files) the program closes. No error message; the program simply closes. Any suggestions? Anybody?

**Comment by PasGG** [comment]
Same problem. 
Thanks in advance for your help.

**Comment by Freimann1** [comment]
My unscientific check on the most recent outstanding issues seem to be 2.4.3 simply cannot import any mp4 video files, OS or Windows.  I use Windows and I can import audio files.

I got round inability to import mp4s by changing them to TS files. But after editing it cannot be exported as any of the formats supported.

**Comment by peanutbutterandcrackers** [comment]
This certainly is strange. Could you please [attach the logs](https://gist.github.com/peanutbutterandcrackers/d84c257e74b72d8b06b4daffaebc5a14) as well, so that the devs can figure out what is wrong here?

**Comment by DylanC** [comment]
Dup of #2114

**Comment by Freimann1** [comment]
I need to figure out how to find the logs.
But this is what I have found.
For my 2.4.1 Openshot, it can always import TS files ( as a result of start and stop recording an MP4 with VLC). It won't import most MP4s directly.  But once in a while it does. But size/high pixel are not the issue. Of the few times I manage to export as a MP4 after editing a TS file in Openshot, Openshot can now import the MP4!!

**Comment by ferdnyc** [comment]
OK, so there's clearly something different between the MP4 file(s) you were trying to import originally, and the one written by OpenShot. That difference may be the key to tracking down this problem.

Aside from the logs that keep getting requested on these reports (which are found, on Windows, in `C:\Users\<username>\.openshot_qt\`, the filenames are `openshot-qt.log` and `libopenshot.log`), one thing that would be helpful is a MediaInfo report for both the file that _can_ be imported, and the file that _can't_. Because, "an MP4 file" is about as broad a category as "a Blu-Ray disc" or "a flash drive" — the contents could be almost _anything_.

If you download and install [MediaInfo](https://mediaarea.net/en/MediaInfo), then you can open any media file with it to generate a profile of the format/contents. 
1. Load `somefile.mp4` into MediaInfo
1. Switch to "Text" mode in the "View" menu
1. Copy-and-paste all of the data there into a text editor
1. Remove any sensitive data (filename, title/author metadata, etc.)
1. Save the profile as a text file, `somefile.mp4.txt` or `somefile-mediainfo.txt` or whatever.

Doing one of those for, at least, a file that _does_ crash OpenShot, and the MP4 OpenShot wrote that **doesn't** cause it to crash, and then attaching the files to this report (if they have `.txt` extensions you can just drag-and-drop as many as you have into the same comment) would be immensely helpful.

**Comment by Freimann1** [comment]
I typically download a video file and its corresponding audio file separately and merge them into a single MP4 using VLC. All of the MP4s merged this way are rejected by Openshot.

General
Complete name                            : G:\Library Video\Combo flv and mp3\Camila Cabello Havana.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (mp41/avc1)
File size                                : 98.9 MiB
Duration                                 : 3 min 44 s
Overall bit rate                         : 3 687 kb/s
Encoded date                             : UTC 2018-11-18 00:44:42
Tagged date                              : UTC 2018-11-18 00:44:42
Writing application                      : vlc 3.0.4 stream output

Video
ID                                       : 2
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, RefFrames               : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 3 min 44 s
Bit rate                                 : 3 500 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Variable
Frame rate                               : 29.970 (29970/1000) FPS
Minimum frame rate                       : 29.412 FPS
Maximum frame rate                       : 30.643 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.056
Stream size                              : 93.5 MiB (95%)
Writing library                          : x264 core 148
Encoding settings                        : cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x3:0x13 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=18 / lookahead_threads=3 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=25 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=abr / mbtree=1 / bitrate=3500 / ratetol=1.0 / qcomp=0.60 / qpmin=10 / qpmax=51 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00
Language                                 : English
Encoded date                             : UTC 2018-11-18 00:44:42
Tagged date                              : UTC 2018-11-18 00:44:42
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
Codec configuration box                  : avcC

Audio
ID                                       : 1
Format                                   : mp3 -FE
Codec ID                                 : mp3 -FE
Duration                                 : 3 min 44 s
Duration_FirstFrame                      : -1 ms
Bit rate mode                            : Constant
Bit rate                                 : 192 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 44.1 kHz
Bit depth                                : 16 bits
Stream size                              : 5.15 MiB (5%)
Language                                 : English
Encoded date                             : UTC 2018-11-18 00:44:42
Tagged date                              : UTC 2018-11-18 00:44:42
mdhd_Duration                            : 224967

*********************************************************************************
If I play around with VLC and its "red button" to trim the video and export it, it turns an MP4 like the one immediately above into a TS file and the TS file is always now accepted by Openshot.

General
ID                                       : 61067 (0xEE8B)
Complete name                            : G:\Library Video\Combo flv and mp3\Candy Dulfer Crazy.ts
Format                                   : MPEG-TS
File size                                : 537 MiB
Duration                                 : 4 min 36 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 16.3 Mb/s

Video
ID                                       : 100 (0x64)
Menu ID                                  : 1 (0x1)
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.1
Format settings                          : CABAC / 3 Ref Frames
Format settings, CABAC                   : Yes
Format settings, RefFrames               : 3 frames
Format settings, GOP                     : M=1, N=12
Codec ID                                 : 27
Duration                                 : 4 min 36 s
Bit rate                                 : 15.3 Mb/s
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Variable
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Stream size                              : 504 MiB (94%)

Audio
ID                                       : 200 (0xC8)
Menu ID                                  : 1 (0x1)
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : 6
Duration                                 : 4 min 36 s
Bit rate mode                            : Constant
Bit rate                                 : 192 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 44.1 kHz
Frame rate                               : 28.711 FPS (1536 SPF)
Bit depth                                : 16 bits
Compression mode                         : Lossy
Delay relative to video                  : 12 ms
Stream size                              : 6.33 MiB (1%)
Service kind                             : Complete Main

Menu
ID                                       : 32 (0x20)
Menu ID                                  : 1 (0x1)
Duration                                 : 4 min 36 s
List                                     : 100 (0x64) (AVC) / 200 (0xC8) (AC-3)
Service type                             : advanced codec HD digital television

But I have never been able to export this TS file in any format by Openshot.  A file is created with literally a few bites in it. The blue bar that is supposed to indicate the progress in exporting never budges from 0%, let alone reaching 100%

*******************************************************

The only alternative is to import the video file and audio file separately, line them up along parallel tracks and export as MP4. This MP4 is accepted by Openshot if you re-import it.
I notice this is now huge ... is it un-compressed? Does that mean Open shot cannot take compressed files.

Please note my Openshot never crashes. It just sits there and says the file is not a valid image, audio or image file.

General
Complete name                            : G:\Library Video\Combo flv and mp3\Candy Dulfer Crazy.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 506 MiB
Duration                                 : 4 min 36 s
Overall bit rate                         : 15.4 Mb/s
Writing application                      : Lavf57.41.100

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.1
Format settings                          : CABAC / 3 Ref Frames
Format settings, CABAC                   : Yes
Format settings, RefFrames               : 3 frames
Format settings, GOP                     : M=1, N=12
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 4 min 36 s
Bit rate                                 : 15.0 Mb/s
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 30.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.543
Stream size                              : 500 MiB (99%)
Writing library                          : x264 core 148 r2665M a01e339
Encoding settings                        : cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=12 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=0 / weightp=2 / keyint=12 / keyint_min=1 / scenecut=40 / intra_refresh=0 / rc_lookahead=12 / rc=abr / mbtree=1 / bitrate=15000 / ratetol=1.0 / qcomp=0.60 / qpmin=2 / qpmax=30 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00
Codec configuration box                  : avcC

Audio
ID                                       : 2
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : ac-3
Duration                                 : 4 min 36 s
Bit rate mode                            : Constant
Bit rate                                 : 192 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 44.1 kHz
Frame rate                               : 28.711 FPS (1536 SPF)
Bit depth                                : 16 bits
Compression mode                         : Lossy
Stream size                              : 6.33 MiB (1%)
Service kind                             : Complete Main
Default                                  : Yes
Alternate group                          : 1

*******************************************

Thanks

**Comment by ferdnyc** [comment]
Ohhh-kay. There's actually a lot of good information here, more than enough to make some determinations about the issues you're experiencing. Let's go in order through the data you provided...

### File 1
> General
> Complete name : G:\Library Video\Combo flv and mp3\Camila Cabello Havana.mp4
> Format : MPEG-4
> 
> Video
> Format : AVC
> Format/Info : Advanced Video Codec
> Format profile : High@L4
> Codec ID : avc1
> Codec ID/Info : Advanced Video Coding
> Duration : 3 min 44 s
> Bit rate : 3 500 kb/s
> Width : 1 920 pixels
> Height : 1 080 pixels
> 
> Audio
> Format : mp3 -FE
> Codec ID : mp3 -FE
> Duration : 3 min 44 s
> Duration_FirstFrame : -1 ms
> Bit rate mode : Constant
> Bit rate : 192 kb/s
> Channel(s) : 2 channels
> Sampling rate : 44.1 kHz
> Bit depth : 16 bits

The problem here is definitely the MP3 audio. VLC is great as a media player because it's so forgiving, you can throw pretty much anything at it and it'll just work out what to do with it. It's less amazing as an encoder for that exact same reason — it's willing to do pretty much anything, even things that it probably shouldn't.

MP3-in-an-MP4-container isn't technically _illegal_, but it's a highly atypical format that's definitely not well-supported by ffmpeg/OpenShot. In my experience, it's also a recipe for problems. Even where it is supported (because, like I said, VLC will play basically _anything_ that it can find some way to interpret as an A/V stream), you'll usually end up with issues like the audio drifting out of sync with the video, or dropping out after a certain point, etc.

You say you download the audio and video streams for these files separately — is the audio _originally_ in MP3 format when you download it, or is VLC reencoding it to MP3 when it combines the two streams?

* If the audio is originally in some other format, and VLC is _converting_ it to MP3, you absolutely want it to not to that. AVC video in an MP4 container is almost always paired with AAC audio, and if VLC is going to be converting to any format, that's the one it should use. Anything else is just creating unnecessary headaches, when you're working with MP4.

* If the audio is originally in MP3 format, and there's no option to get it in any _other_ format (preferably AAC), then you **want** VLC to convert it to AAC while it's creating the combined MP4. Normally it's better not to reencode, of course, but like I said — MP3 audio and the MP4 container don't really mix.

If you use some _other_, more forgiving container format, that's a different story. Take the [`youtube-dl`](https://rg3.github.io/youtube-dl/) command-line tool, for instance. (Its function/purpose is hopefully self-evident in the name.) It has the ability to automatically do the same sort of thing you're doing: Pull down the separate DASH parts for a YouTube video — because these days HD content is pretty much exclusively served as separate audio and video parts, rather than as a single muxed stream — and then recombine them into a single video file. It'll accept both the video and the audio stream in whatever format YouTube is willing to serve up — AVC, WEBM, 3gp, or FLV video; AAC, MP3, M4A, or even OGG  audio — and have no issues combining them, because it uses MKV as the container format.

Matroska has proven to be the VLC of media containers, in the sense that you can stuff pretty much anything into it in any combination, and as long as the player/decoder supports both the audio and the video codec it'll probably still work. Nearly every other container format has fairly narrow rules about what video formats and what audio formats are supported, and in what combinations. 

So, if your media parts come to you as AVC video and MP3 audio, and those are your only choices, another option would be to combine them into an .MKV file, instead of MP4. That's likely to be much more compatible with... well, with everything actually, OpenShot included.

### File 2
> General
> Complete name : G:\Library Video\Combo flv and mp3\Candy Dulfer Crazy.ts
> Format : MPEG-TS
> 
> Video
> Format : AVC
> Format/Info : Advanced Video Codec
> Format profile : High@L4.1
> Codec ID : 27
> Duration : 4 min 36 s
> Bit rate : 15.3 Mb/s
> Width : 1 280 pixels
> Height : 720 pixels
> 
> Audio
> Format : AC-3
> Format/Info : Audio Coding 3
> Commercial name : Dolby Digital
> Codec ID : 6
> Duration : 4 min 36 s
> Bit rate mode : Constant
> Bit rate : 192 kb/s
> Channel(s) : 2 channels
> Sampling rate : 44.1 kHz
> Bit depth : 16 bits

The reason OpenShot is able to read this file isn't that it's a `.TS` file, per se — it's that you've reencoded the audio as AC-3, which is a much better supported format. Creating the original MP4 (File 1) with AVC video + AC-3 audio would also have a much better chance at being compatible with OpenShot, than the AVC+MP3 version.

> But I have never been able to export this TS file in any format by Openshot. A file is created with literally a few bites in it. The blue bar that is supposed to indicate the progress in exporting never budges from 0%, let alone reaching 100%

An export attempt with debugging enabled in OpenShot's Preferences might provide some details on why this is failing (logs of the export process would be in the `libopenshot.log` file), but I _suspect_ the problem here is the **other** thing that re-encoding as a `.TS` file adds:

> Menu
> ID : 32 (0x20)
> Menu ID : 1 (0x1)
> Duration : 4 min 36 s
> List : 100 (0x64) (AVC) / 200 (0xC8) (AC-3)
> Service type : advanced codec HD digital television

...My guess is, OpenShot/ffmpeg doesn't know how to handle the Menu stream in the `.TS` file (well, I _know_ it doesn't know how to handle menu streams), and the export process is probably getting tripped up by it.

> The only alternative is to import the video file and audio file separately, line them up along parallel tracks and export as MP4. This MP4 is accepted by Openshot if you re-import it.
> I notice this is now huge ... is it un-compressed? Does that mean Open shot cannot take compressed files.

Not uncompressed, just encoded to prioritize video bitrate (~ quality, loosely) over file size. Your `.TS` file is the same, in fact it's actually larger:

#### File 2 (`.TS` export from VLC)
> Format : MPEG-TS
> File size : 537 MiB
> Duration : 4 min 36 s
> Overall bit rate mode : Variable
> Overall bit rate : 16.3 Mb/s

#### File 3 (OpenShot MP4 Export at High quality)
> Format : MPEG-4
> Format profile : Base Media
> Codec ID : isom (isom/iso2/avc1/mp41)
> File size : 506 MiB
> Duration : 4 min 36 s
> Overall bit rate : 15.4 Mb/s

As a broadcast format, MPEG-TS has no reason to encode for filesize efficiency, and every reason _not_ to conserve bandwidth on the encoding. Since the content is meant to be transmitted over a pipe with a fixed capacity (the broadcast carrier frequency, or the HDMI cable that connects the TV to a cable box, broadcast receiver, and/or media player), encoding more efficiently would just mean that more of the available bandwidth is going unused, and therefore being wasted. (The highest bitrate available for Blu-Ray is something like _FORTY-FIVE_ Megabits/sec, which is how a 2-hour movie can end up taking up 100 GB of space on the disc.)

OpenShot's "High" output quality sets the video bitrate to 15 Mbps, which matches the recommended bitrate for full-HD (1080p) video uploaded to services like YouTube, Vimeo, and etc. (Actually, Vimeo's recommendation is 20 Mbps, and I believe OpenShot's Vimeo preset uses that bitrate for High quality.)

Since your original source video has a _much_ lower bitrate:
> Bit rate : 3 500 kb/s
there's absolutely no benefit to exporting from OpenShot at High quality, unless you've added animated titles, effects, or other features that would benefit from the additional bitrate. But assuming you're just looking to export at a quality similar to the original, using OpenShot's Medium quality will reduce the bitrate to 5Mbps, much closer to the 3.5Mbps of the original file.

But that's all completely unrelated to the import issues, the problem with the first file has nothing to do with compression/bitrate, it's almost certainly the MP3 audio payload.

**Comment by Freimann1** [comment]
Thank you ferdnyc. You are right on the money on many scores.

I didn't realize MP3 does nto work well in a MP4 container. I did two things per your suggestion.
(1) I tried converting the MP3 to AAC using iTune. Despite what many Youtube tutorials say on this topic or even the drop-down menu from iTune says it is converting to AAC, my iTune converst it to an M4A file. But merging the MP4 and the video file now onto a MP4 container is perfectly acceptable to Openshot.
(2) I didn't realize I can download the Youtube audio part of the video either as MP3 or M4A but looks like all I need is to repeat Step (1). I need to try first to confirm.

And yes, I found that Aviddemux can merge an AVC video with MP3 and output as .MKV file. That too is acceptable to Openshot.

Thanks again.

**Comment by ferdnyc** [comment]
> I didn't realize MP3 does nto work well in a MP4 container. 

Yeah, that's just hard-won experience more than anything else, honestly — from long before I'd ever even heard of OpenShot. The combination has never caused me anything but problems. It may be that it's _possible_ to combine the two, by encoding the MP3 content Just So™ in a way that won't piss off the MP4 demuxer, but it's very clear that the MP3 format is much broader and more complex than whatever that narrow standard is (if it even exists), and in the general case MP3 is a pretty reliable method for getting MP4 loaders to crap themselves.

> I did two things per your suggestion.
> (1) I tried converting the MP3 to AAC using iTune. Despite what many Youtube tutorials say on this topic or even the drop-down menu from iTune says it is converting to AAC, my iTune converst it to an M4A file. But merging the MP4 and the video file now onto a MP4 container is perfectly acceptable to Openshot.

Excellent. That M4A file probably _is_ AAC encoded, TBH — MediaInfo could tell you for sure. Even in the audio context, MP4 is just a container format, not a media codec, so the audio inside that M4A has to be encoded with _something_ — it's possible for it to be something other than AAC (AC-3 and ALAC are both supported as MP4/M4A payloads), but here again the default and the safe assumption is AAC.

The file-naming thing... is sort of weird and arbitrary, to be honest, and poorly defined. Some software makes the distinction between `.M4A` to represent an audio stream inside an MP4 container (with no video), and `.AAC` to indicate that the file contains just the raw AAC audio stream, with _no_ container — which won't necessarily be recognized as playable audio by "media player" type software, since those applications typically expect a container format, not a raw audio stream. **But**, other software focuses only on the codec, not the container, and will call an AAC audio stream inside an MP4 container an `.AAC` file. 

**\*shrug*** "The nice thing about standards is that you have so many to choose from." –[Andrew Tanenbaum](https://en.wikiquote.org/wiki/Andrew_S._Tanenbaum)

> (2) I didn't realize I can download the Youtube audio part of the video either as MP3 or M4A but looks like all I need is to repeat Step (1). I need to try first to confirm.

If the audio and video streams you're working with are literally YouTube videos (or, the DASH streams they're composed of), I really can't recommend `youtube-dl` highly enough. I wasn't kidding when I said that it does this same sort of thing, in fact it takes care of _all_ the heavy lifting and, when `ffmpeg` is available to it, makes everything completely automatic.

On Windows, same as on Linux, if a build of [`ffmpeg.exe`](https://ffmpeg.zeranoe.com/builds/) is in the `PATH`, [`youtube-dl.exe`](https://rg3.github.io/youtube-dl/download.html) requires _nothing_ other than a YouTube video ID — it'll query the available formats, automatically select the highest-quality video and audio streams available, download both DASH parts separately, launch `ffmpeg.exe` to combine them, and delete the DASH components once `ffmpeg` has saved a video file containing both parts re-muxed together.

Take the standard HD test video, [Big Buck Bunny](https://www.youtube.com/watch?v=aqz-KE-bpKQ) — which is now on YouTube in 4K resolution (video ID `aqz-KE-bpKQ`)...
```winbatch
C:\Users\ferd\Downloads>echo %PATH%
C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\Wind
owsPowerShell\v1.0\;C:\Program Files\Windows NT\Accessories\;C:\Users\ferd\AppDa
ta\Local\GitHubDesktop\bin;C:\Users\ferd\AppData\Local\atom\bin;C:\Program Files
\ffmpeg-4.1-win64-static\bin;

C:\Users\ferd\Downloads>ffmpeg -version
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 8.2.1 (GCC) 20181017
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig
--enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfr
eetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb
 --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --en
able-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-lib
wavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --en
able-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enab
le-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enab
le-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --ena
ble-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable
-avisynth
libavutil      56. 22.100 / 56. 22.100
libavcodec     58. 35.100 / 58. 35.100
libavformat    58. 20.100 / 58. 20.100
libavdevice    58.  5.100 / 58.  5.100
libavfilter     7. 40.101 /  7. 40.101
libswscale      5.  3.100 /  5.  3.100
libswresample   3.  3.100 /  3.  3.100
libpostproc    55.  3.100 / 55.  3.100

C:\Users\ferd\Downloads>youtube-dl aqz-KE-bpKQ
[youtube] aqz-KE-bpKQ: Downloading webpage
[youtube] aqz-KE-bpKQ: Downloading video info webpage
WARNING: Requested formats are incompatible for merge and will be merged into mk
v.
[download] Destination: Big Buck Bunny 60fps 4K - Official Blender Foundation Sh
ort Film-aqz-KE-bpKQ.f315.webm
[download] 100% of 1.54GiB in 08:44
[download] Destination: Big Buck Bunny 60fps 4K - Official Blender Foundation Sh
ort Film-aqz-KE-bpKQ.f258.m4a
[download] 100% of 29.15MiB in 00:04
[ffmpeg] Merging formats into "Big Buck Bunny 60fps 4K - Official Blender Founda
tion Short Film-aqz-KE-bpKQ.mkv"
Deleting original file Big Buck Bunny 60fps 4K - Official Blender Foundation Sho
rt Film-aqz-KE-bpKQ.f315.webm (pass -k to keep)
Deleting original file Big Buck Bunny 60fps 4K - Official Blender Foundation Sho
rt Film-aqz-KE-bpKQ.f258.m4a (pass -k to keep)

C:\Users\ferd\Downloads>dir "Big Buck Bunny 60fps 4K - Official Blender Foundati
on Short Film-aqz-KE-bpKQ.mkv"
 Volume in drive C has no label.
 Volume Serial Number is 787D-9E57

 Directory of C:\Users\ferd\Downloads

10/26/2018  03:03 PM     1,681,537,938 Big Buck Bunny 60fps 4K - Official Blende
r Foundation Short Film-aqz-KE-bpKQ.mkv
               1 File(s)  1,681,537,938 bytes
               0 Dir(s)   9,972,617,216 bytes free
```

Notice, the _only_ command of any significance there is `youtube-dl aqz-KE-bpKQ` — that's everything `youtube-dl` needs to work everything out for itself, to automatically download and assemble the video with that ID at the best possible quality. (It's also possible to limit the quality it'll download, if for example you don't _actually_ want to pull down the video as a 1.6 GB file in 4K resolution even though it's available.)

But by default, it just Does The Right Thing™ for best quality with zero input from the user ­— no muss, no fuss.

![screenshot 2018-12-01 14 31 34](https://user-images.githubusercontent.com/538020/49332895-78bd6880-f583-11e8-8f9c-cbe757b884ad.png)

> And yes, I found that Aviddemux can merge an AVC video with MP3 and output as .MKV file. That too is acceptable to Openshot.

Avidemux is an excellent tool for this sort of stuff. It's still my go-to for any sort of video conversion, _especially_ when I want to avoid re-encoding one or more of the streams. I still keep HandBrake handy for when avidemux inevitably fails me (because I learned long ago that anything that depends on ffmpeg's moving-target APIs **will** break from time to time), but those instances are becoming less and less common.

Three years ago was one of them, since in the beginning Avidemux didn't handle DASH streams well at all. But I [reported those issues](https://avidemux.org/smif/index.php/topic,16405.0.html) and they mostly got addressed pretty quickly, the avidemux developers tend to stay pretty on top of things.

> Thanks again.

Not at all — happy to help, and glad it worked out! 

I will try to look into that issue you had exporting from the `.TS` file — like I said, I _think_ it was probably the menu stream that threw OpenShot, but just because a file contains an unrecognized/unsupported stream is no excuse for OpenShot to completely fall apart trying to process that file. Ideally it would simply ignore the unrecognized stream, and get on with its business.

**Comment by LWFlouisa** [comment]
Currently working out a fix as far as the audio itself. I'll edit this post when I figure it out.

**Comment by ferdnyc** [comment]
?

Should I have my Junior Filmmaker Secret Decoder Ring at the ready?
