### ISSUE TITLE
Audio mix corrupted on export

### ISSUE THREAD

**Issue by novakrob** [OpenShot/openshot-qt#2299]
Hello.

Description of issue:
I have just one video file which I don't edit at all, just mute the original audio.
Than I have 2 layers with different audio tracks (mp3).
When I play in preview everything is good. After exporting there is a gap between audio tracks. (no matter if HD 1080p, 720p or VGA, medium or high quality)
I tried to put audio to just one layer with some transition, but result is worst than first export.

Expected behavior:
Crossfading audio working without unexpected ending of first track earlier. Export result is the same like preview.

System: Win10, OpenShot 2.3.4 updated today. Prev. version same behavior.

**Comment by speedytechdev** [comment]
Hi @novakrob could you take a screenshot of the timeline, send a copy of the film and the crash logs, please.

**Comment by novakrob** [comment]
Hello @speedytechdev. You can download a cut from video i was talking about at this link http://www.uschovna.cz/zasilka/FZCE2CJBLUNJLGI3-JEI/.
Version without automatic generated transitions:
![timeline_01](https://user-images.githubusercontent.com/38833612/47669905-3aabde00-dbac-11e8-8778-1cc59a088bac.PNG)
Version with transitions:
![timeline_02](https://user-images.githubusercontent.com/38833612/47669987-6cbd4000-dbac-11e8-87ac-01ed412b14b5.PNG)
First try was made like this:
![timeline_03](https://user-images.githubusercontent.com/38833612/47670131-c58cd880-dbac-11e8-9925-4841fc2c8a32.PNG)

I don't get any crash PopUps...all works fine. Or if you have any crash logs saved automaticly, just let me know where I can find them.

**Comment by novakrob** [comment]
> Hi @novakrob could you take a screenshot of the timeline, send a copy of the film and the crash logs, please.

Hello @speedytechdev. I can see you have not downoladed the file yet. Do you need anything else to help investigate the problem?

**Comment by speedytechdev** [comment]
@novakrob Hi sorry I am been very busy let me take a look quickly and see if we can fix this issue for you.

**Comment by speedytechdev** [comment]
Can you tell me what time in the film the audio has problems because I can't find it.

**Comment by speedytechdev** [comment]
I hear some cracking around 50 secs and from 58 to 01:01 it is silent but that is because of the transition. I am sorry but I don't see the problem unless that is it or you sent me the wrong file?

**Comment by novakrob** [comment]
No, the file is correctone. The silence is the issue. There is silence even in case there is no transition. Export looks the same in timeline with transition or without (both timelines added to this ticket before, see the pictures).
Expected behavior is to mix the audio by fading out first and fanding in second track. But the first end by fade out before the second track start. They should cove each other. And this can not be done with track in different layers, same layer with transition, same layer without transition.
When I play it in preview, audio is mixed properly, so why there is a difference in export?

**Comment by novakrob** [comment]
![image](https://user-images.githubusercontent.com/38833612/48318190-f1707b00-e5fc-11e8-969d-9644bfd96965.png)
This is the waveform of exported audio "Road trip 01 cut without transitions".

**Comment by novakrob** [comment]
![image](https://user-images.githubusercontent.com/38833612/48318267-1a454000-e5fe-11e8-8589-944c9460fc00.png)
Expected mixdown of audio track is like this.

**Comment by novakrob** [comment]
Hope this optical explain is better. I can confirm, that preview is like second and expected beahvior. But real export is done like first case.

**Comment by speedytechdev** [comment]
So is it not fading correctly?

**Comment by novakrob** [comment]
Yes, the fade out occurs before it is set in timeline. so next song can start. It look like in exporting there is no possible to mix two tracks when first is fading out and second is starting in same time. As you can see in waveform from exported video, first track is starting to fade out befere is set in timeline and silence is visible for a while and then second track starts. Start of second track is on right time from timeline. Fading out previous track is adjusted automaticly. But only in export, not in preview. Is there any different engine when exporting or what cause this difference?

**Comment by speedytechdev** [comment]
I think the same engines run it. I need to do some tests to prove that it is a bug. Thanks for bringing up the issue I will let you know if I need anything or the situation changes.

**Comment by speedytechdev** [comment]
@novakrob I have confirmed that the Transition effect is delayed.
![image](https://user-images.githubusercontent.com/40452959/48318627-5e6d2a80-e668-11e8-80a5-9621b1ca2d6d.png)

**Comment by speedytechdev** [comment]
https://jumpshare.com/b/RDCiea1E6Ukdq7fP7q7E

**Comment by speedytechdev** [comment]
@DylanC This is a confirmed bug

**Comment by novakrob** [comment]
Hello @speedytechdev and @DylanC. I’m just asking for any news about this bug. Have You found any solution? Do You know when We can expect fixed version?

**Comment by novakrob** [comment]
Hello guys. How is it going with this bug? Any progress? I’m a bit sad about the time it takes. Tought it could have a solution after 9months. 😔

**Comment by ferdnyc** [comment]
@novakrob

I'm not up on the full history here, but a couple of points:
1. Transitions are purely _visual_ effects. They have no bearing on audio. So, there's no reason to be worrying about transitions with audio-only tracks.
2. If you had keyframe positions shifting between preview and export, my very strong suspicion is that you were working with the project profile set to a different frame rate than you were exporting at. (Frame rate doesn't affect the audio _per se_, but until very recently it **DID** affect how keyframe positions were mapped to time indexes in the export, and exporting at a frame rate other than the project rate wasn't supported in OpenShot 2.3.x (or even 2.4.1/2.4.2). 

If that was the issue, then OpenShot 2.4.4 should solve the problem for you, because export at a frame rate different from the project profile is now fixed.

AFAIK there's no specific bug related to this issue that anyone is working on, so I don't expect there will be any status updates forthcoming. But my recommendation is to give the 2.4.4 release a try, see if it clears up the problem. 

If it _doesn't_, and you still experience issues with the new version, best thing would be to file a new issue using the Bug Report template, provide the requested details, and indicate that the problem exists in the most recent release. A bug report from 2.3.4 just isn't likely to get worked on anymore.

Installers can be downloaded from https://openshot.org/download/
