### ISSUE TITLE
can´t get the right aspect ratio

### ISSUE THREAD

**Issue by Lurchiloo** [OpenShot/openshot-qt#2303]
can´t get 16:9 output from 16:9 source

**My Question:**
Hello folks,

i got some videos archived from my DV cam in 16:9 ratio. I tried now several output formats but everytime i get the output in 4:3 ratio. I don´t know what i do wrong.

thanx in advance

**System Details**
 - Operating System Windows 10
 - OpenShot Version 2.4.3

**Screenshots**
![vlcsnap-2018-10-29-23h40m18s462](https://user-images.githubusercontent.com/43119480/47685468-e79b5080-dbd6-11e8-80bc-16c4ffe75c3e.png)
![vlcsnap-2018-10-29-23h41m11s321](https://user-images.githubusercontent.com/43119480/47685486-f08c2200-dbd6-11e8-934d-f22002502d4b.png)

**Comment by peanutbutterandcrackers** [comment]
Please [create a custom profile](https://www.openshot.org/static/files/user-guide/profiles.html#custom-profile) that fits your needs (or choose an existing profile that has 16:9 aspect ration - if that exists).

On second thought, it is strage. Because it says the default profile's DAR is 16/9. Hmm... Perhaps you might want to set the resolution to be equivalent with your footage too, while creating said custom profile. [MediaInfo](https://mediaarea.net/MediaInfo) might be your friend in that regards.

Hope that helps!

**Comment by jjensenlcn** [comment]
Same thing here, can't get 16:9 in preview or export
Tried stock profile matching vid no dice.

**Comment by peanutbutterandcrackers** [comment]
@jjensenlcn - Again, I suggest that you try using a custom profile: https://www.openshot.org/static/files/user-guide/profiles.html#custom-profile Hope that helps!
