### ISSUE TITLE
Video Preview Stops Working After Moving Timeline Play-head

### ISSUE THREAD

**Issue by PrimordialHelios** [OpenShot/openshot-qt#231]
I recently installed Openshot 2.0.7 on Windows 10 Home x64, and after starting a project, importing a video, and dragging it onto a track, I pressed play on the preview. After that, I moved the play-head on the timeline, and tried to play the preview again, but the preview didn't play. The video and audio didn't work, and the play-head didn't move even after clicking play multiple times.

**Comment by Kagetsuki** [comment]
I just encountered this problem when I imported a video with a varied frame rate. Can you give this a shot:
1. (assuming you have ffmpeg) run `ffmpeg -i originalvideo.mp4 -r 30  newvideo.mp4` (replacing file names of course)
2. delete the original clip from the project, add the new clip you just converted

It looks like there are several other issues here that are due to VFR and I have a suspicion this is one of them.

**Comment by jonoomph** [comment]
Please retest with our latest daily build, and reopen this issue if the problem still occurs. We've made a ton of improvements to Windows and the stability of OpenShot, and I think you will find it's been fixed. Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. Thanks!
