### ISSUE TITLE
no color picker

### ISSUE THREAD

**Issue by czesio86** [OpenShot/openshot-qt#2326]
**Describe the bug**
Strange issue in ppa version (doesn't matter if it's stable or not) I got "poorer" select color menu(e.g.in chroma key); and missing "pick screen color" only basic and custom colors.
But ond downloadable standalone version color menu
looks way "advanced" and there is "pick screen color"

**System Details (please complete the following information):**
 - xubuntu 18.04
 - OpenShot 2.4.3 from openshot.developers/ppa

Probably that is issue with diferent build of python used by my system and standalone binary wich I guess got one build in.

**Comment by peanutbutterandcrackers** [comment]
On my Linux Mint 19 machine which uses the ppa as well, there seems to be no problem.
![screenshot at 2018-11-27 14-36-14](https://user-images.githubusercontent.com/26764547/49069657-e8fd7e80-f251-11e8-9d07-19fdb459e226.png)

Is it working now? Or does the problem still persist?

@ferdnyc could be able to give some insight into this...

**Comment by ferdnyc** [comment]
\*nod* If your Qt install is set up for native dialogs you'll get the native color picker. In Gnome 3.30 on my Fedora 29 installation, that means this one:

![image](https://user-images.githubusercontent.com/538020/49340993-35abd580-f615-11e8-9733-ee0fc6718758.png)

In theory we could disable use of native dialogs when we launch the color picker, specifically. Which might be prudent,  because in this one instance Qt's actually tends to be far better than the native alternatives.

**Comment by czesio86** [comment]
You mind reader;-) That's exacly what "the issue" is looking like. To be
honest I thought it is something like that but I'm not a programer and my
know-how is limited.

niedz., 2.12.2018, 14:34: Frank Dana <notifications@github.com> napisał(a):
