### ISSUE TITLE
Video Error

### ISSUE THREAD

**Issue by ShockedCoder** [OpenShot/openshot-qt#2329]
[Proof #2.zip](https://github.com/OpenShot/openshot-qt/files/2554038/Proof.2.zip)
[My Proof.zip](https://github.com/OpenShot/openshot-qt/files/2553905/My.Proof.zip)

**Describe the bug**
A video error that literally bugs me. The 18 sec video i created keeps on glitching. I even checked the original videos and there were no problems

**System Details (please complete the following information):**
 - Windows 10
 - OpenShot Version [2.4.3]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**
I don't know how to write this down so i just made a video... hehe...

**Comment by DylanC** [comment]
@Unknown1Coder0 - What do you mean by "glitching"? Is it the audio or video you are talking about?

**Comment by Unknown1Coder0** [comment]
1.Did you even look at my proof? they are mp4. 2.Both video and audio.

**Comment by peanutbutterandcrackers** [comment]
Thank you for the video.

I think this problem is just the preview-cache issue. It is not really an issue. It's just not generating the cache fast enough.

To fix this, you could try increasing the cache size by going to `Edit` > `Preferences` > `Cache` and setting the cache limit to a higher value. If you have an SSD, I would also suggest changing the cache mode to disk and changing the image quality to a much lower value. Playing around with the parameters there should give you a good result. Hopefully.
![screenshot at 2018-11-27 09-27-13](https://user-images.githubusercontent.com/26764547/49057546-2f3de800-f228-11e8-9d6c-cfad650bbdb7.png)

Hope that helps!
