### ISSUE TITLE
Can't Seem To Open Project Files

### ISSUE THREAD

**Issue by NewbieToOpenShot** [OpenShot/openshot-qt#2353]

**Comment by speedytechdev** [comment]
Hi, @NewbieToOpenShot we need more information to be able to help you. Could you please fill out the information below.

**Describe the bug**
A clear and concise description of what the bug is.

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**
Add any other context about the problem here.

**Comment by peanutbutterandcrackers** [comment]
I wonder if `View` > `Views` > `Simple View` is what you are looking for.

Closing this as inactive and ansered. Please feel free to re-open/comment, etc.

**Comment by MarKeremid** [comment]
> I wonder if `View` > `Views` > `Simple View` is what you are looking for.
> 
> Closing this as inactive and ansered. Please feel free to re-open/comment, etc.

Definitely that helps a lot! 10x for your time!
