### ISSUE TITLE
Transparent Preview Background

### ISSUE THREAD

**Issue by MisterTeeXD** [OpenShot/openshot-qt#2364]
**Is your feature request related to a problem? Please describe.**
I wonder if its possible to have a transparent background of the preview as well as transparent videos

**Describe the solution you'd like**
I want to add a transparent background in my videos

**Describe alternatives you've considered**
None

**Additional context**
This is a Made up image : 

![png preview](https://user-images.githubusercontent.com/37266538/48643805-67078d00-e9e9-11e8-972b-6beca4a38c41.png)

**Comment by ferdnyc** [comment]
I am not aware of any transparency support in the commonly-used video codecs. Transparency in video is mostly done via chromakey ("greenscreen"/"bluescreen" effects).

[This SuperUser Q&A](https://superuser.com/questions/746232/why-are-there-no-video-formats-that-support-transparency) goes into some detail on the issue. But, in short, transparency isn't a feature of the optimized video codecs you'll find out "in the wild", it's only present in some high-bandwidth raw production video formats. Video codecs (the ones used for consumer/delivery encoding) are concerned with the _rendering_ of the final image. They need to know how to draw each pixel, so they can do it in the most efficient way possible. Transparency explicitly _doesn't_ give them that information, which destroys their ability to compress and optimize their output. That makes transparent video suitable only for intermediate/composite elements, not final rendering.

If you want to achieve transparency using full-motion video, use a solid-color background and apply chromakeying. If you're doing it within OpenShot, you can apply the "ChromaKey" Effect to your clips to turn the selected color transparent.

**Comment by peanutbutterandcrackers** [comment]
While transparent backgrounds aren't the thing, yet, I kinda' want the "make transparency appear as a checker-board" with in the project itself button/preference somewhere. Would come in handy, esp. if I am dealing with something like all-black images (as overlays) in my project.

**Comment by ferdnyc** [comment]
But there _isn't_ any background transparency — the default background really _is_ black. Again, the video encoder (even the previewer) can't encode with transparency, there has to be **something** to render for each pixel. You could just as easily place an image of a checkerboard pattern (or any other background) on Track 0, since that's exactly what the fake-"transparency" feature would be doing anyway, even if it hid that from the user.

Here, I created this with `convert -size 1920x1080 tile:pattern:checkerboard background.png`:

![background](https://user-images.githubusercontent.com/538020/49066398-f6cde800-f1ee-11e8-9b82-fdf1686825dd.png)

Download it, drop it on track 0, and you've got your non-black background image.

**Comment by ferdnyc** [comment]
The reason I would be against this being an OpenShot feature, though, is that a checkerboard background  is understood to imply _real_ transparency, and it would be misleading to show it when that's **not** the case.

In other words, if the OpenShot interface looked like @MisterTeeXD 's mockup and you pressed "Encode", you'd _expect_ OpenShot to output a transparent video. But it won't. It'll output a big black rectangle. Users would be understandably confused and annoyed by that.

Whereas, if you stick a background image on Track 0 and press Encode, you'd hopefully expect that the resulting video will contain that same background image — even if it's an image of a checkerboard pattern.

**Comment by peanutbutterandcrackers** [comment]
Yes, I understand. It's just that while creating complex effects (like the one I used during my 'Meet-Tux' video) it is quite confusing to have it all look black when you need to see which areas are actual blacks and which are overlay blacks.

Thank you for the convert command. I didn't know about that. Now I'll use it for the time being.

Perhaps a button in the preference that says something like show checker-board instead of black for transparency in the project (NOT REAL TRANSPARENCY) will be of help, a button that is fairly hidden. Or, perhaps there could be some other pattern that won't be associated with actual transparency but will allow the users to see exactly how things are. Just a thought.

For the time being, your command + the `End` parameter from the properties dialogue should make my work a lot more easier. Thank you.

**Comment by ferdnyc** [comment]
Oh, I don't disagree that the display of clip boundaries could be improved. Whenever a clip is selected that's smaller than the output frame, it should be outlined in the preview, the same way Gimp outlines layers that are smaller than the image dimensions.
