### ISSUE TITLE
replace placeholder with Cloud API

### ISSUE THREAD

**Issue by ORECHN** [OpenShot/openshot-qt#2372]
Hi all,
Is it possible to create a slideshow video with placeholders (images and texts) with the desktop app? (to create a kind of "template")
After that - is it possible to import the template project to the Cloud and dynamically replace the placeholder images and dummy texts with "real" images and texts via REST API? 

thx
ORE

**Comment by ferdnyc** [comment]
No, certainly not, at least as a _video_ file. A rendered video file is just a sequence of frame images, the individual elements that went into that video no longer exist as discrete entities; there's nothing left to replace.

Something like that would have to be rendered on-the-fly. That's _possible_, using things like Flash or perhaps SVG animation, but it would require advanced multimedia / web authoring software to create, not traditional video production/rendering software. Something like Dreamworks would be my first guess at what might be capable of producing the necessary structure/code. You could also, potentially, do it directly on the HTML5 Canvas, but then you'd have to do any animation/motion-effects as CSS animations. Again, you're in Dreamworks or similar web-authoring territory.

**Comment by ferdnyc** [comment]
> Something like ~Dreamworks~ would be my first guess at what might be capable of producing the necessary structure/code. You could also, potentially, do it directly on the HTML5 Canvas, but then you'd have to do any animation/motion-effects as CSS animations. Again, you're in ~Dreamworks~ or similar web-authoring territory.

...Dream**WEAVER**, dummy. [Adobe Dreamweaver](https://www.adobe.com/products/dreamweaver.html). 

(Though I'm sure Dreamworks SKG could produce it, too, if you paid them $2 million.)

**Comment by ferdnyc** [comment]
Another possibility is something like [Adobe Animate](https://www.adobe.com/products/animate.html), which is apparently what became of the old Flash authorware, now that it can create a lot more than just .SWF and .FLV files. (If there are workable freeware equivalents to Dreamweaver and Animate, I don't know of them. Doesn't mean there aren't, though.)

**Comment by ORECHN** [comment]
Hi Frank, thanks for the info.
Unfortunately, I did not write clearly enough.
I wanted to import the openshot project file (Json) into the cloud, not the generated video. I thought that is possible.
The video should finally be generated via the Cloud API.

**Comment by ferdnyc** [comment]
Oh! Oh, I see.

Hmm. In _theory_ you could create a "template" project file, then modify the project data dynamically through any means you wanted — I've been known to fiddle with `.osp` file contents by hand in a text editor, as well as programmatically via `sed` regexps and the like. As long as the structure is kept correct, OpenShot will load it.

Doing the _rendering_ would still require loading the modified file back into OpenShot and performing the export by hand, though. There are no automation or batch-processing features currently present in the OpenShot desktop application that could be accessed by another process or script running externally.

It would be _possible_ to write something like that _separate from_ the OpenShot application, say as a C program linked with `libopenshot`. (Though, you'd have to reimplement all of OpenShot's side of the rendering process.) Or even in Python, using the `openshot` module. 

If you wanted to do _that_ (the Python one), you could probably save some reinvention of various wheels if you started by taking all the parts of the OpenShot application code concerned with managing project data (most of `src/classes/`), plus the Export code in `src/windows/export.py` — particularly the `Export` class's `accept()` method — to drive the rendering. Basically just jettisoning all of the GUI-related parts would pare that down to a "render-video-from-JSON-project" program that could, with some additional structure implemented to replace the GUI, be run on a cloud server. _Theoretically._ 

But no matter how you approached it, you'd have to build the actual automation parts from scratch, since none of that is currently supported in the OpenShot application.

**Comment by peanutbutterandcrackers** [comment]
Hey there,

I haven't really followed the conversation (sorry to barge in) but I wonder if [this](https://github.com/OpenShot/openshot-qt/issues/2404) might be of any help.

Thanks!
