### ISSUE TITLE
How to insert title in the front?

### ISSUE THREAD

**Issue by musicfreund** [OpenShot/openshot-qt#2394]
How can I move the whole movie to the right if I want to insert the title in front?

**Comment by peanutbutterandcrackers** [comment]
This one is a bit tricky. If your whole project is already done and contains a lot of clips and is fairly complicated, you might be better off creating a separate openshot project for just the titles, exporting it in the same profile as the movie (with the same container: i.e. .mkv, .mp4, etc) and then using something like [avidemux](http://fixounet.free.fr/avidemux/). If that is not the case you could probably also try selecting all the clips, and nudging them (using shift + arrowed) keys. But this is extremely time consuming as each 'nudge' will only move the clip by half-a-frame.

@N3WWN - Is there any way to set the nudge to something else, manually, good sir? Just curious.

**Comment by N3WWN** [comment]
Right now, nudging only works for objects that are selected (either single or multiple clips), IIRC.

What I would suggest is to add your titles to an empty track (or add new track(s) for your titles) that is above or below all of your other tracks, get the duration of the titles set or at least set the end of the last item in the title section where you want it, zoom out so you can see the entire project at once (make sure you can see all of the tracks, too), then do a box select with a click and drag of the mouse (starting in a non-clip portion of the timeline, such as an empty are on a track or the "dead space" or "gutter" between the tracks) and select every item that is not part of the titles at once.  If you have *every* item that needs to be shifted selected, you can then click and drag the entire project up and down the timeline.  If you have snapping enabled, you should be able to snap the first clip of the group that you're moving to the end of the last title clip.  

If you need to fade between the title portion and the existing video portion, say with a 1 sec fade, you could create a temporary clip 1 sec earlier than the end of the titles and snap the first clip of the group to the end of that clip, then remove the temporary clip.

Depending on how many clips, keyframes, effects, titles, etc you have, this can take quite a while, especially if you have a large number in your `Preferences` for the `History Limit`.  

The default value of 20 means it could take a long time to move all of these items if you have a lot of them.  I like to set my `History Limit` down to something like 5.  The reason for this is that every item that is moved in your selected group is added to the undo history and the undo history, right now, stores undo histories recursively.  Off the top of my head, I believe it ends up being factorial in nature, so an undo of 5 results in about 120 total entries in the undo history... a value of 10 would be about 3.6 million entries and the default of 20 is mind-bogglingly huge!  The way the history is pruned reduces the actual number of entries, again IIRC, so 20 isn't going to exhaust all of your RAM and storage space if you do this, but you get the idea.

Before doing this, you may want to close out of OpenShot and create a backup of your `.osp` file so that you can copy it back over the original in order to undo the move if things go awry.

**Comment by peanutbutterandcrackers** [comment]
Possibly related to #753?

@musicfreund - Please follow the advice given by the awesome N3WWN above.

Closing this issue for now. Please follow the discussion over at #753 if you are interested. And please do continue to love and support OpenShot! :+1:

**Comment by peanutbutterandcrackers** [comment]
Assigning label 'worked-around' so that N3WWN's suggestion can be looked up easily.
