### ISSUE TITLE
I can not run Inkscape inside Openshot

### ISSUE THREAD

**Issue by raulet27** [OpenShot/openshot-qt#2399]
**My Question:**

Hello, good afternoon, I have a problem in OpenShot and I want to put subtitles with a small outline in the letters and for that I need to use Inkscape.

I installed it (Inkscape), I copied the path where "C: \ Program Files \ Inkscape" is and I have put it in the "preferences" section but it does not run.

I've also tried to put the end .exe but nothing either.

Someone could help me?

Thank you very much and have a good day :)

**System Details**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**Screenshots**

**Comment by raulet27** [comment]
Operanting System: Microsoft Windows 10 Home 64 bits
OpenShot Version: 2.4.3

**Comment by peanutbutterandcrackers** [comment]
Could you please try using a [daily build](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914) of OpenShot? A change has just recently been merged that makes it possible for one to browse to the exact InkScape executable in the system (instead of just  typing it in). That should work.

Please do let us know how it goes. If it doesn't work, we might have to work on that a bit more.

Thanks!

**Comment by DylanC** [comment]
@raulet27 - I would recommend a daily build. As @peanutbutterandcrackers stated. It has a browse button to find the .exe and set the correct path for you.

**Comment by raulet27** [comment]
It works for me, I just downloaded the 32 bit version, thanks for the help,
it's a luxury that you answer so fast :)
