### ISSUE TITLE
Chinese Translation not showing in AppImage

### ISSUE THREAD

**Issue by bostontrader** [OpenShot/openshot-qt#2402]
**My Question:**
Hello Folks,

On the one hand I see [reference to a chinese translation](https://translations.launchpad.net/openshot/2.0/+translations), but on the other hand, under preferences -> General -> Language, I don't see any choice for Chinese.  Am I blind?  Does this not actually exist?  Grateful for any clues for getting a Chinese language edition of this.  Thanks.

**System Details**
 - Operating System / Distro: Ubuntu 17.10
 - OpenShot Version: OpenShot-v2.4.3-dev1-1542712310-31e9e7b6-750d7a3f-x86_64.AppImage

**Comment by bostontrader** [comment]
A clue...
I see that the program is looking at the LANG env variable as part of its determination as to which language to use.

On my system LANG=en_US.UTF-8 and the default language is English, but I don't have any choice for Chinese in the settings.

If I set LANG=zh_CN.UTF-8 then the default language is Chinese, but there's still no choice for Chinese in the settings.

So I guess this is a reasonable work-around, but it would be nice to have it in the list of choices.  I'd do a pull request for this but I don't know enough about your code, python, or QT to even be dangerous and this is probably pretty easy for those in the know.

**Comment by peanutbutterandcrackers** [comment]
I have already pinged someone who knows all this. We should have some further clues. Hopefully we'll be able to fix this in the later releases.

**Comment by ferdnyc** [comment]
My installed OpenShot from Fedora (actually rpmfusion) packages also includes Chinese translations, though that probably isn't surprising since I maintain those packages. I'll take a look at the AppImage and see if they're missing for some reason.
![screenshot from 2018-11-27 03-29-53](https://user-images.githubusercontent.com/538020/49068661-48797100-f1f5-11e8-8d4a-c03fac5bf0aa.png)

I do notice that the Chinese translations aren't working when selected from the command line, though — i.e. if I run `openshot-qt -l zh_CN` the interface is still in English, so that's apparently a bug. But if I select the `zh_CN` language option in Preferences and restart, the interface does properly come up in Chinese. (Well, I'm assuming, since I don't read Chinese.)

**Comment by ferdnyc** [comment]
Interestingly, in the AppImage, _listing_ the languages from the command line causes a **crash** before it reaches the Chinese translations...
```console
$ OpenShot-v2.4.3-dev1-1542369142-31e9e7b6-750d7a3f-x86_64.AppImage --list-lang
Loaded modules from current directory: /tmp/.mount_FkoYGA/usr/bin
Supported Languages:
         en_US  U.S. English
           ady  
[...]
            uk  Українська
            uz  Ўзбек
            vi  Tiếng Việt
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/cx_Freeze-4.3.4-py3.4-linux-x86_64.egg/cx_Freeze/initscripts/Console.py", line 27, in <module>
  File "openshot_qt/launch.py", line 109, in <module>
    main()
  File "openshot_qt/launch.py", line 83, in main
    exit()
NameError: name 'exit' is not defined
```

However, they are included and present, and it **DOES** work (there) to _load_ them from the command line. So, that's at least a workaround, for the time being. Running the AppImage from a shell terminal as:
```console
$ OpenShot-v2.4.3-dev1-$UUID-x86_64.AppImage -l zh_CN
$ OpenShot-v2.4.3-dev1-$UUID-x86_64.AppImage -l zh_TW
$ OpenShot-v2.4.3-dev1-$UUID-x86_64.AppImage -l zh_HK
```
will work to launch OpenShot with the interface translated for the specified Chinese locale.

I'll look into why the AppImage is not showing them in the Preferences window, or listing them with `--list-languages`. ...And also why `openshot-qt -l zh_CN` _doesn't_ work in my Fedora builds.

**Comment by DylanC** [comment]
@bostontrader @peanutbutterandcrackers @ferdnyc - Marking this as more of a bug than a question. I can confirm, still an issue in v2.4.4 AppImage.

**Comment by ferdnyc** [comment]
@DylanC 
> I can confirm, still an issue in v2.4.4 AppImage.

Yeah, same here, right down to `--list-languages` not _showing_ the Chinese scripts, nor are they in the Language selector in Preferences, but you can still activate any of them from the command line via `OpenShot-v2.4.4-x86_64.AppImage -l [zh_CN | zh_TW | zh_HK]`. And I still have _no idea_ why that's happening.

On the plus side, `/usr/bin/openshot-qt -l [zh_CN | zh_TW | zh_HK]` **DOES** work in my Fedora 2.4.4 builds, so whatever was going on there at least that's cleared up now.

I wonder if the AppImage issue could be due to the age of the bundled Qt? 

I know that's my go-to theory for everything and it probably isn't fair to automatically blame every problem on old software, but in this case... i18n for (especially) Asian scripts isn't exactly a feature that's been around forever, and it _is_ Qt 5.2.1! Obviously the Chinese languages _work_, because the system translation files are present (meaning they were included with the Qt distribution), and they can be force-loaded manually... but something seems to be screwing with their detection for whatever reason.

#### And the rest...

As a random, only-tangentially-related aside, it looks like we're still having issues with the two Portuguese scripts as well. (So, this AppImage thing with the Chinese scripts is by no means the only issue with translations, and the problems definitely can't be **entirely** blamed on Qt 5.2.) 

I don't know which ones actually _work_ correctly or incorrectly in various circumstances, but I notice that in the AppImage, **both** `pt` and `pt_BR` identify themselves as "Português Do Brasil", whereas in my installed Fedora build they _**both**_ identify as "Português"! 

 \*sigh\* Is it too much to ask that things at least _break_ the same?
