### ISSUE TITLE
Playback lags in editor

### ISSUE THREAD

**Issue by rufford155** [OpenShot/openshot-qt#2407]
Playing back my short video within the program is very jerky and sound is intermittent.

But my exported .avi file plays perfectly !

How can this be ?

**Comment by speedytechdev** [comment]
Hi, @rufford155 we know about this issue. This is on our list of things to fix but thanks for letting us know.

**Comment by DylanC** [comment]
@rufford155 - What spec is your PC?

**Comment by rufford155** [comment]
My laptop is not high spec but I don't believe that's the issue.
Playback is fine in every other editor I've tried, this is maybe the eighth.

**Comment by peanutbutterandcrackers** [comment]
This is a known issue and work is being done to fix it (see https://github.com/OpenShot/libopenshot/pull/179). Since this issue does not provide any further details, and the issue is already one that is being worked upon, I shall proceed to close this one. Please do look forward to the future releases. Things will be a whole lot better!
