### ISSUE TITLE
Resolution dropped and everything zoomed in

### ISSUE THREAD

**Issue by torpedoboy49** [OpenShot/openshot-qt#2414]
how do you zoom out/ change resolution of openshot itself (not the video)?

**Comment by speedytechdev** [comment]
Hi, @torpedoboy49 could you send me some screenshots, please. Also what version of Openshot are you using?

**Comment by speedytechdev** [comment]
@torpedoboy49 If you don't answer soon I have to close this issue sorry.

**Comment by juanbosh** [comment]
same issue, but i dont know if is because the theme is not working properly or the resolution doesnt, but i install the driver nvidia on ubuntu 18.04 and the problem persist in version 2.4.1

**Comment by speedytechdev** [comment]
@juanbosh Do you think it is the Nvidia driver or Ubuntu?

**Comment by juanbosh** [comment]
I read something but i dont know how to fix it, i think is the configuration of the video, i explain me, i think is because i m using the hdmi  port out, and the configuration of my tv, or the linux isnt reconitze by the program. because i supose that, version 2.4.3 download with the same configuration of video works fine. at the end. i ll have to work with this vesion and pray to no change the configuration in the news versions ...
