### ISSUE TITLE
Everytime I try and export it freezes at the same percentage and then crashes?????

### ISSUE THREAD

**Issue by hypercompl3x** [OpenShot/openshot-qt#2417]
**Describe the bug**

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.1]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Additional context**

**Comment by speedytechdev** [comment]
Hi @hypercompl3x could you fill out this information please or we have no idea how to help you. Thanks

Describe the bug
A clear and concise description of what the bug is.

System Details (please complete the following information):

Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
OpenShot Version [e.g. 2.4.1]
To Reproduce
Steps to reproduce the behavior:

Go to '...'
Click on '....'
Scroll down to '....'
See error
Expected behavior
A clear and concise description of what you expected to happen.

Screenshots
If applicable, add screenshots to help explain your problem.

Logs
If you are experiencing a crash, please collect and attach logs of the problem.

Additional context
Add any other context about the problem here.

**Comment by hypercompl3x** [comment]
Operating System / Distro: Windows 10
OpenShot Version 2.4.3
To Reproduce
Steps to reproduce the behavior:

Go to export
Click on mp4 h.264, 720p 30fps
Scroll down to export
See error
Expected behavior: Freezes at 14.7% then says not responding and quits.

**Comment by speedytechdev** [comment]
This is a common problem with exporting at h.264. Like this [2371](https://github.com/OpenShot/openshot-qt/issues/2371)
