### ISSUE TITLE
Change property without setting keyframe

### ISSUE THREAD

**Issue by stefan-reich** [OpenShot/openshot-qt#2420]
**Describe the bug**
I want to change a clip property such as ScaleX without generating an animation

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
Peppermint Linux 8
 - OpenShot Version [e.g. 2.4.1]
2.4.3

**To Reproduce**
Add a video clip to timeline.
Slice off the beginning.
Try to change property ScaleX.
Now it always makes a keyframe, and when I say "remove keyframe", the value of ScaleX is reverted.

**Expected behavior**
Properly remove keyframe, but keep new value

**Comment by ferdnyc** [comment]
That's not possible, the value adjustment will always be applied as a keyframe. It's inherent in the animatable properties that their value adjustments are stored in keyframes.

The secret is in where you set it. If you make the adjustment at the _very first_ frame of your clip, the parameter won't be animated — it'll be set by the first keyframe to whatever value you select, and then because there are no other keyframes to further adjust the parameter, it will hold on the same value throughout the rest of the clip.

**Comment by stefan-reich** [comment]
OK. The thing is, it didn't seem to work.

If the clip starts at 2:00 and I put the timeline pointer (?) at 0:00 for setting the value - is that supposed to work? 'cause it didn't...

It neither worked when the clip was at 0:00 and the pointer at 0:00 too.

It only worked when I added the clip again from the videos list.

So it seems slicing a clip was what caused the problem setting the value.

I can make a video demo if you like.

**Comment by ferdnyc** [comment]
"Remove Keyframe" is somewhat broken in that if you use it on a clip that only has one setting for a value, that value is returned to 0 instead of to its default/initial value. 

Like, for instance, if you do this...
1. Place a Clip on the Timeline
2. Select the Clip
3. Right-click on "Scale X"
4. Choose "Remove Keyframe"

..."Scale X" will become `0` throughout the duration of the clip, which is wrong. Same thing with "Enable Audio/Video" (which also become `0`, instead of resetting to `-1`), etc. So, to avoid that issue, don't use "Remove Keyframe" to remove the last keyframe of a clip. 

It's implicit that all clips are created with a keyframe at their first frame, containing all of the default values for all properties. (OpenShot unfortunately has some special-casing so that it doesn't _display_ that keyframe as a keyframe even if you adjust it, but it's still there.) Deleting that last keyframe for any property will **remove** the default value, which is rarely what you want.

Or to put it another way: "Remove Keyframe" shouldn't be used as a shorthand for "Reset Value", as that's not how it works.

Most (all?) properties **are** resettable throughout a clip, though. Right-clicking on the clip and choosing the appropriate menu option, such as "Fade > No Fade", "Animate > No Animation", etc., will set the corresponding properties back to their default at the first frame of the clip, and clear any adjustment keyframes throughout the rest of the clip. "Layout > Reset Layout" is the option to reset the "Scale X" and "Scale Y" properties for a clip, along with "Gravity" and possibly some others.

**Comment by stefan-reich** [comment]
I just didn't get it to work. I don't know how people use this software. I just want to set properties quickly without generating any keyframes at all. I'm currently using OpenShot 1.4.3 again.

**Comment by Linrono** [comment]
I was working on a project with this software for the first time and I also ran into this problem and it took me a very long time to fix it, and then, after hours of rendering, it turns out it wasn't even fixed. 

I tried to set properties without animations five times in my project. Putting the Playhead at the beginning of the clip did not work for me, it would still show an animation. I figured out a work around, you cannot have the Playhead on the clip when editing the properties. I would have to move the Playhead to the left of the clip a significant distance and then edit the clip's properties. Sometimes it would actually set the value without a Keyframe as far as I could tell (the property wasn't blue or green it was the regular color, most likely as described by @ferdnyc ). Other times, the animation would happen before the clip was actually shown (assuming the clip wasn't at the beginning of the Timeline) so it wouldn't be visible in the end product. 

I got this to work on my clip at the beginning of the project, but it only lasted for the first rendering. Every subsequent rendering ended up with the animation, which I didn't realize because I thought it was fine since the first render was correct (I was trying to render with different encoding options to find optimal settings). The other four times in the project I used this method worked like a charm though.

If the Keyframes are mandatory, that is fine, but there needs to be a clear way to edit them. I could not find any way to change them, just delete them. I could see the Keyframes on the clip in the Timeline (the little green tick marks) but I could not find or edit their values. If there is an easy way to find or edit these values, please let me know.

**Comment by stefan-reich** [comment]
> If the Keyframes are mandatory, that is fine

I don't see how that's fine. 99% of the time you want to set properties without keyframes (adjust volumes, screen positions etc).

**Comment by Twenkid** [comment]
Hi, @Linrono
> If the Keyframes are mandatory, that is fine, but there needs to be a clear way to edit them. I could not find any way to change them, just delete them. I could see the Keyframes on the clip in the Timeline (the little green tick marks) but I could not find or edit their values. If there is an easy way to find or edit these values, please let me know.

I've encountered similar issues, I think the keyframe system is cumbersome, it would be great if there's a view where you could simply edit keyframes per selected video, if without graphs, just with plain numbers in listboxes, comboboxes, text fields, simple script - numbers, simple syntax.

As of now I think you could edit each keyframe by precisely scrolling the time pointer - when it matches the green mark of the keyframe, the property item becomes marked as well, indicating there is a keyframe at that position. When you modify these properties, that affects the values of the keyframe. Also there's right click which opens a menu regarding the curve of the animation, which I think is computed between two keypoints. Beginning and ending(?) seem to be default keyframes

I agree with @stefan-reich and Linrono, that often what's needed is just a constant value for the whole clip.

**Comment by scottgigante** [comment]
FWIW, on 2.4.4 if I navigate to the start of a clip with the marker arrows and set a property, it still creates a keyframe -- after I set it the first time there appears to be no possible way to set the base property value.

**Comment by ferdnyc** [comment]
@scottgigante That's because you're not _creating_ a keyframe, when you set a property that way — you're _modifying_ the initial keyframe for that property. In the current Timeline setup every clip is imported with a keyframe at the first frame that contains the value of that property. That keyframe controls the property value for the entire duration of the clip, unless more keyframes are added to modify the value.

OpenShot does a little special-casing so that any single-keyframe property doesn't show the interpolation mode selector or interpolation highlighting, because those things have no meaning unless you have _two_ or more keyframe points. (In fact, you can even right-click on the value at that first frame and select "Remove keyframe" — which OpenShot will happily do, wiping out the keyframe data and zeroing the property, which is fine if it's something like 'Location X' or 'Shear X', not so great if it's 'Scale Y' that defaults to 1.) 

So, not only is there always a keyframe at the first frame of a clip, but there _needs_ to be, because the only way to adjust the property value is to edit that point or add additional points. (The exception are the non-keyframable properties like Gravity, Volume Mixing, Wave Color / Waveform, etc. Those values are not stored in keyframe lists.)

This _does_ mean that there's no way to return a property to its initial value after modifying it, and that's one of several reasons we've been discussing changes to the way things currently work. (OpenShot/libopenshot#370) I absolutely agree the existing property system is not ideal.

But, as far as the way things _do_ currently work, keyframes are always there, and the properties' values are stored _only_ in those keyframes. There is no alternative, because there is no other place where those values are or can be stored.

**Comment by scottgigante** [comment]
Okay, so the issue I had was actually that I _thought_ my cursor at the start of the clip when I was actually a tiny bit off. This caused me setting the properties that should have been set on the first frame to actually be on maybe the second or third frame, introducing the interpolation infrastructure. Trap for new players, I suppose.

**Comment by ferdnyc** [comment]
@scottgigante Yeah, the fiddly positioning is definitely one of the issues with the current setup. One **#PROTIP** I can offer: Once you select the Clip you want to modify values for, you can use the Previous / Next Marker controls (the navigation arrows on the toolbar directly above the Timeline, aka <kbd>Ctrl</kbd>+<kbd>←</kbd> and <kbd>Ctrl</kbd>+<kbd>→</kbd> in the default keybindings) to jump to the first or last frame of the clip — the Playhead will seek to those positions as if they're markers, in addition to whatever other actual markers you may have set (if any).

So, when applying first-frame adjustments it's a good idea to use Prev / Next Marker to make sure you're right at the start of the clip.

**Comment by direc85** [comment]
I just downloaded OpenShot and tried to whip up a quick test video. Crossfading videos is simple, but I hit a wall when I tried to simply create text to bottom left corner. I created a title item, set the font and text and added it to project files. I could not figure out any better bay to do it, so here is my method of simply moving the text from the center to left corner - essentially moving the clip position to down and left:

- Set the cursor in the middle of the clip so I can see the text on top of the video
- Open clip properties
- Set X and Y position to desired values
- Take note of the values
- Right click X and Y, remove keyframes
- Move the cursor before the clip
- Set the X and Y position values

The method @ferdnyc just introduced me to - Ctrl+←- likely works exactly the same as my method above, but that must be done before setting fade in, or you can't actually see the text you're placing. This makes order of operations critical, which can be confusing for beginners. Thank you for the explanation too, that was actually helpful in understanding the way OpenShot works.

If I may propose a workaround/solution? Right clicking a value in the properties menu - such as X and Y pos, or any other animatable property I guess - should contain an option "Apply to whole clip" which first removes any existing keyframes of said property, and then applies the setting to the first frame of the clip. Or, perhaps, "Apply from beginning" which just applies the current value to the first frame of the clip, and if we are exactly at a keyframe, deletes it. That way any other keyframes of said property already set within the clip are preserved.

Thanks!

**Comment by WhymustIhaveaname** [comment]
I also want and need this funtion.

**Comment by bugsbycarlin** [comment]
I also want and need this function. It's a bad user experience on complex videos.

I agree with this specific request: "Right clicking a value in the properties menu - such as X and Y pos, or any other animatable property I guess - should contain an option "Apply to whole clip" which first removes any existing keyframes of said property, and then applies the setting to the first frame of the clip"

**Comment by TheSlider2** [comment]
Tried to use this tool a few months ago to crop / resize old family VHS recordings and kept running into this issue.
I need to see what is being croped since the first seconds of each clip is a black screen so I move the track to the middle of the clip. Crop, resize. Only to notice there is an animation.
This is backwards to what other tools do. Why is there not at least a feature to "set this value as default" effectively converting it to a gray value ?

It's so frustrating to use, i'm not sure i'll recommend this tool even for simple operations.

**Comment by JacksonRG** [comment]
@TheSlider2 
ferdnyc's comment explains how to set a 'default'` value by setting it at the beginning of the clip.
https://github.com/OpenShot/openshot-qt/issues/2420#issuecomment-562916205

Thinking in terms of keyframes is the main difference from photo-style editing to video-style. Sounds like you're already solving this the way I would. Skipping to what you want to crop, and finding the needed crop value.

We are currently considering different ways to visualize keyframes, and 'apply from the beginning' might be an enhancement we add. But either way, a user has to remember to set that value from the start of the clip because values have to be able to change over time.

**Comment by JacksonRG** [comment]
I'll make a note that this could be explained more in our startup tutorial... The idea of keyframes, and how all values are set with them. :thinking:

**Comment by TheSlider2** [comment]
Hey. Thanks for the reply.
ferdnyc's comment provides a less annoying solution to the steps direc85 and I have gone through but you can imagine how frustrating it is to not be able to set the values while seeing the result in the preview. So a feature to make this more intuitive would be nice indeed.

**Comment by nen2a** [comment]
Doing the markers to go to first keyframe and now when adjusting location it adjusts both X/Y at the same time for who knows what reason. I don't think I'll be using this software anymore until this is changed please just let us edit properties without creating animations by default.

**Comment by openingapps** [comment]
Wow!  They CLOSED this issue.  I hope someone re-filed, because it certainly is a big pain.

In the meantime, make sure to read the comment from ferdnyc (December 7, 2019)!!   This at least makes the work-around tolerable.

**Comment by OverLordGoldDragon** [comment]
Dealbreaker. Otherwise a decent editor - switched to VideoPad.

**Comment by Colorjet3** [comment]
This thread is so long so I'll get right to the point.  This is very simple and works great once you understand how the product works (this is true to any product).  I started using OpenShot with version 2.5.1 in Windows environment and I am currently running v3.0.0 (the latest DEV Daily build).

The creation of Animation is an awesome feature and yet frustrating if you don't understand how OpenShot and keyframes work.  Here is how it works:
1.  Import an image file.
2.  Drag it onto a Track.
3.  Select the clip on the track and ensure that the playhead is positioned at the left edge of the clip.  This is the key to avoid animation at this point.
4.  Right click on the clip and select Properties.
5.  From the Properties page change Scale X & Scale Y to .5.
6.  You will note that the image gets smaller in the preview window.
7.  When you play it it will be at that scale for the entire clip (no animation).
8.  Delete this clip from the track and drag it again onto the timeline.
9.  Select the clip and position the playhead in the middle of the clip.
10. Right click, select Properties, and change Scale X & Scale Y to .5.
11. Move the playead at the beginning of the clip (left most edge) and click play.
12. Watch the clip animate from scale value of 1.00 to .5 as it reaches the middle point and maintain that.  This is an awesome feature.
13. Now, let's say you don't want to animate but rather go from 1.0 scale to .5 just like that.
14. Delete this clip.
15. Drag it again onto a track.
16. Select it and move the Playhead in the middle of the clip.
17.  Right click and select Properties.
18.  Now, before you do anything else you need to freeze those keyframes to avoid animation.
19.  For both Scale X & Y, right click on the value of 1.00 and select "Insert Keyframe".
20.  Click on your image to ensure it is select.
21.  Using the keyboard press CTRL+right arrow key combination to nudge the playhead by 1 frame to the right.
22.  Now to into the Properties and Change Scale X & Y values to .5.
23.   Move the playhead to the beginning of the clip and press Play.
24.   You will note that the scale stays at 1.0 (no animation) and then when it reaches the middle point where you set the .5 scale value, it abruptly changes the scale and it stays at .5 until the end.

Once you get this concept you can introduce animation at certain points in a clip (video or image).

I hope this sheds some light on the subject and I would like to hear if this makes sense or if you need further clarification.

**Comment by MetalSlime0** [comment]
> introduce animation at certain points in a clip

But that's not what we people want to do. We want to set, for instance, the scale for the entire clip. And have it work for the entire clip, even if we change where the clip starts. A keyframe at any point in the clip doesn't work with that.

It's kind of boggling my mind how people aren't getting that there's actually a problem here that makes the software kind of unusable for some pretty reasonable use cases.

**Comment by krazyjakee** [comment]
@Colorjet3 your response boggles the mind. Essentially you're saying "get gud" and a 24 step guide to achieve what should be default behavior. Notice on step 3 how the user should have pixel perfect precision and in practice, it's not realistic.

To set a new key frame you should hold ctrl and modify properties, otherwise it should set the properties for the entire slice.

This wouldn't even be a breaking change.

Sadly this is a deal breaker for me, I'm out.

**Comment by Colorjet3** [comment]
Hello @MetalSlime0 and @krazyjakee.  I am a volunteer tester and a user of Openshot.  Even though you have indicated that this is a deal breaker I would really like some feedback what exactly you are seeing what the issue is and what is the solution that you are seeking.

As you can tell this thread is from 2018.  I started using Openshot for just a little bit over 2 years.  I still consider myself a novice video editor and still learning what Openshot can do, can not do, what it does that is good and what it does that is bad.  Lot's of room for improvements as way too many hands were in the pot previously causing some bad code, bad implementation, lack of testing, etc.

If you guys are willing to start a new thread with a clear description of the issue and some suggestions of what the solution you ar seeking that would be greatly appreciated.

The Openshot development team is very small and very dependent on volunteers. There is a renewed effort for more structured approach to moving Openshot forward.   I directly work with the development team and get their attention to what you may consider to be a bug, a bad implementation, enhancement, etc.

If you do decide to start a new thread, then thank you in advance!

I wish you the best of luck with your projects.

**Comment by MetalSlime0** [comment]
Hi @Colorjet3, I only used Openshot for an hour or so before I ran into this issue and eventually gave up, so I don't even remember it super well. I was looking for a way to scale a video clip that I wanted to overlay on top of another clip, and I couldn't find a way to scale it that didn't introduce a keyframe. IIRC it would have unchanged scale up until the frame I changed the scale on, and then it would use the scale I wanted. I could put the keyframe on the first frame of the clip, except that I needed to be able to adjust the first frame of the clip afterwards, with the scale active, to see if it was overlaying properly. In reality I was changing more properties than just scale, so this became too frustrating.

I agree with @krazyjakee that setting a keyframe should be an *alternate* method of setting properties, not the default. But it's also possible there's another solution to this problem that I was just totally missing, in which case the discoverability of that feature is the real issue.

Edit: Also, having to have the playhead at the beginning of the clip is not an acceptable solution in all cases, because you might be setting the values based on what the clip looks like halfway through.

**Comment by Colorjet3** [comment]
Hello @MetalSlime0.  Thank you for your reply.

What I am finding out, specially using other video editors, that there are multiple ways of accomplishing certain effects between editors, and then to add to the complexity, multiple ways withing the same video editor.  Each product has their architects and they take different approaches.

For example, I mention the playhead needed to be at the beginning is because if you have it positioned deeper into the video or image, you get this animation effect.  This drove me crazy until I understood how it worked and it is one of the strengths of Openshot.  And, of course, you are still able to make changes at different frames without having to animate.

I'll give you an example,
1.  You have an image that is 10 seconds in duration, and at the 5 seconds marker you want make it smaller (50% smaller).
2.  You would drag the image on a track.
3.  Position the playhead at the 5 seconds marker.
4.  Find the Scale X & Y properties, right click on them and Choose to "Insert Keyframe".
5.  You would then Right click on the Scale X & Y values and choose Constant.
6.  This would lock the first 5 seconds of the clip to be at Scale 100% for both X & Y.
7.  Now, while the playhead at the 5 seconds location, double click on each Scale X & Y and change the value from 1.00 to .5.
8.  Move the playhead at the beginning of the image and click play.
9.  You will not the image at 100% scale until you reach the 5 seconds marker and then the rest abruptly changes to 50% scaling.

You can do this with other attributes as well (location, rotation, shear, etc.) and they all work the same way.  Additionally, sometimes you want to animate the scaling and Openshot does that for you automatically.  So for the above example, if you skip steps 4-6 and execute steps 7-9 you would automatically achieve Scaling animation until you reach the 5 seconds marker and then it stays at 50% for the rest of the clip.

Honestly, I found Openshot to be one of the easiest video editors, for a beginner who didn't know anything about video editing, including the lingo (it took me forever to understand what a keyframe is...LOL!).  What became very frustrating was the constant bugs, half-baked implementation, and QA.  All that is changing with the new approach to structured development cycle and QA.

Fixes and enhancements never come fast enough with a small team and I am trying to do my part (as a volunteer...) to move the project in the right direction.

Version 3.1.0-release-candidate is in-progress going through the -Release-Candidate test plan as we speak. It will be soon released as production release.  Even if you don't want to use it for your everyday video editor, feel free to give it a shot.  We need more users and testers and feedback to continuously improving the product.

Take care!

**Comment by krazyjakee** [comment]
> Move the playhead at the beginning of the image

You are asking for Pixel perfect precision from the customer here and when there are hundreds of clips, you just end up with artifacts and bugs in the output video.

**Comment by OverLordGoldDragon** [comment]
> The Openshot development team is very small and very dependent on volunteers

Yes, hopefully no one here is dismissive of that. But that doesn't excuse OpenShot being dismissive of user complaints, which appears to be what's happening.

To pin it back on the user is a non-starter. QoL is a basic spec. I'm a software engineer and I've designed things more complex than this software - if it's too much for me, what of the layman?

**Comment by Colorjet3** [comment]
Hell @OverLordGoldDragon Agreed on being dismissive of user complaints.  This is no longer the case and the queue of bug fixes and enhancements is long and more gets added all the time.

Also, I didn't mean "To pin it back on the user..." on purpose.  I was merely stating that as a user there is always the initial getting to know the product as different software achieve similar functions in different ways.

**Comment by OverLordGoldDragon** [comment]
> dismissive of user complaints. This is no longer the case

Good! Then it'd help OpenShot to reopen this Issue so we don't think it's being ignored, which will also stop some of the comments.

**Comment by openingapps** [comment]
Hi Colorjet,

Please go back and read the comments from ferdnyc.  They are excellent, and they describe everything you need to know.  The thing that makes this openshot's behavior a royal pain is that setting a keyframe at the beginning of a clip is really, really difficult to do in the GUI.  Without this the following tip from ferdnyc, it is next to impossible to put the keyframe in exactly the right place.  But not everybody has read this hint!

Perhaps you just need a mode (a default mode?) where keyframes near a clip's start are pushed on top of the start.  My guess is that this is usually what people want.

ferdnyc's tip:

Yeah, the fiddly positioning is definitely one of the issues with the current setup. One #PROTIP I can offer: Once you select the Clip you want to modify values for, you can use the Previous / Next Marker controls (the navigation arrows on the toolbar directly above the Timeline, aka Ctrl+← and Ctrl+→ in the default keybindings) to jump to the first or last frame of the clip — the Playhead will seek to those positions as if they're markers, in addition to whatever other actual markers you may have set (if any).

So, when applying first-frame adjustments it's a good idea to use Prev / Next Marker to make sure you're right at the start of the clip.

**Comment by thomasvjohansen** [comment]
really needs an animation on animation off button...

**Comment by TheSlider2** [comment]
Replies use different use cases making this request fail to reach an common understanding as sometimes you actually need to see some other part of the clip than the first frame.
Let's describe a few test cases so that we can focus on the issue.

Here was my own from back when I was editing VHS recordings where the first few seconds were often a blank screen with no visual clues as to what was going on and where I had to move the playhead ahead before doing adjustments (cropping, resizing, etc...). So, I needed to be able to edit the first keyframe of the clip while looking at a preview a few seconds ahead.

At the time I had no idea each clip had an initial keyframe and while that makes sense in some ways, It only made my issue aggravating.
Surely, this is not a problem if the first frame was representative of the whole clip and you can select it easily but in some cases, it isn't.

Here is one idea of what I call an intuitive way of fixing the issue : Open the properties of the clip at any given position, do the changes and hit some button "apply to whole clip".
I'd assume this would also help to fix mistakes made to other keyframes without having to reimport the whole clip and start over.

That being said, I second @thomasvjohansen with an "animate" button or checkbox toggle in a disabled state by default so that no additional keyframes are generated and only the first one is changed wherever the playhead is since I doubt making clip animations is what people do most of the time.

Thoughts ?

**Comment by Colorjet3** [comment]
I have assigned this to the lead developer (@jonoomph).  Ultimately, he is the one that will need to review and then approve/disapprove.  I definitely understand the situation and playing with other video editors I see exactly what @TheSlider2 has summarized as well.

With that said, I am not a developer and I don't fully understand the complexity of changing something like this and the greater impact on coding and other testing that is needed not to further break the product.  Like I said, I'll leave it for the lead developer to decide.

**Comment by FeldrinH** [comment]
Is there any update on this?

I just downloaded the latest version of OpenShot for the first time, tried to line up some clips and then discovered that because I had been moving around the timeline while tweaking positions I had accidentally created a bunch of keyframes and had to to do a bunch of tedious cleanup. That is to say, this issue is still very relevant.

**Comment by Colorjet3** [comment]
Hello @FeldrinH.

Here is an update:
1.  OpenShot will still create keyframes if the playhead is positioned anywhere other than the beginning of a clip.  This is one of its strenghts providing animation out of the box.
2.  All tutorials and OpenShot User Guide are very clear on this.
3.  Controlling the behavior of "Animation" is in the queue and has been for some time.  There is a v3.4.0-Release-Candidate that is currently going through testing and getting close to production release.  However, this change is slated for v3.5.0- (no ETA at this time).

v3.4.0-Release-Candidate update:
1.  You can adjust inserted keyframes using the mouse.  Select a clip so the keyframes are visible and adjust them as needed.
2.  You can adjust keyframes on multiple clips at once.
3.  If you select multiple clips, you can right click any of the selected clips, then click on "No Animation" and that should remove most animation.  There is a bug where the Rotation animation does not get removed and will need to be reset manually.

**Comment by FeldrinH** [comment]
It's great that there's some movement on this. I do want to push back a little on this though:

> OpenShot will still create keyframes if the playhead is positioned anywhere other than the beginning of a clip. This is one of its strenghts providing animation out of the box.

I would agree that this is a strength if there was a way to turn it off. Unfortunately there (currently) isn't, so for users that just want to reposition things, not animate, this is more likely to be an annoyance. If I want to set the position/rotation/scale of things based on something that appears later on in a clip then I can't do my positioning with the playhead at the beginning of the clip, because the thing that I want to reference for positioning isn't visible in the clip yet.

> 3. If you select multiple clips, you can right click any of the selected clips, then click on "No Animation" and that should remove most animation. There is a bug where the Rotation animation does not get removed and will need to be reset manually.

With this "No Animation" option, does it also disable automatic keyframe creation for that clip, or does it just remove existing animation?

**Comment by Colorjet3** [comment]
I hear you.  No, "No Animation" is not a preference setting.  I just mentioned it as an option for you to quickly clear unintended animation on multiple clips.

Hopefully, in v3.5.0, an option, in Edit | Preferences, will be available where you can change the behavior of the "Animation".  It will most likely be on by default but a user can disable that.

Additionally, I am hoping that the lead developer will provide a quick way to enable/disable this feature during editing a project.

Appreciate the feedback.
