### ISSUE TITLE
Project somehow corrupted: cannot move clips within the timeline

### ISSUE THREAD

**Issue by techman84** [OpenShot/openshot-qt#2430]
**Describe the bug**
After working for a while on a specific project, somehow, it stopped to work properly. Issues are the following:
- cannot move clips in timeline (drag and drop doesn't work);
- markers doesn't work;
- prev/next marker function doesn't work.

**System Details (please complete the following information):**
 - Windows 10
 - OpenShot 2.4.3

**To Reproduce**
Difficult to say what combination of steps I done to reach this situation.
Creating a new project works, so the issue is due to something wrong in the specific .osp file.
This is the project file, so that it can be debugged:
https://www.dropbox.com/s/mx47738vmrprree/Test%20project.osp?dl=0

**Screenshots**
I made a screencast of the issues:
https://youtu.be/nXZ-XJCG0do

**Comment by speedytechdev** [comment]
Hi, @techman84 this is a very strange bug. Could you put the files used in your movie also in the dropbox, please.

**Comment by techman84** [comment]
@speedytechdev I uploaded the source files involved:
https://www.dropbox.com/s/rnyg56124fh2ytx/Source%20videos.zip?dl=0

The project I shared you before ("Test project.osp"), it's a copy of my original project, in which i deleted some segments in the timeline to simplify the tests.
I also share the original project, when I realized about the issue:
https://www.dropbox.com/s/lqld0it3j44kyk1/Led%20Cucina.osp?dl=0

**Comment by speedytechdev** [comment]
@techman84 Sorry to get back to you so late. Have you tried the daily build?

**Comment by s2software** [comment]
@speedytechdev I've just tested with today's daily build, but didn't solved the issue.

**Comment by speedytechdev** [comment]
Ok, It says I am still missing files. Are you sure you sent everything? One other thing do you have the crash logs?

**Comment by s2software** [comment]
@speedytechdev I checked the .osp (the json structure inside) and there was something messy: relative and absolute paths together. I replaced all with relative paths. Here the zip with source videos + project with relative paths ready to open without any "missing" message:
https://www.dropbox.com/s/6bwk6cxtr0n50a1/OpenShot%20issue%20project.zip?dl=0

**Comment by speedytechdev** [comment]
@s2software I just tested it and that was really weird. It might sound like a dumb question but did you try and make a new project?
![image](https://user-images.githubusercontent.com/40452959/49843634-bd1ef300-fe24-11e8-84fe-a8500e4689b1.png)

**Comment by s2software** [comment]
If I start a new project from scratch it works. But the original "bugged" .osp has many segments and didn't wanted to remake that editing work again. Is there any procedure to import segments in another empty project?

**Comment by techman84** [comment]
@speedytechdev If I start a new project from scratch it works. But the original "bugged" .osp has many segments and didn't wanted to remake that editing work again. Is there any procedure to import segments in another empty project?

**Comment by speedytechdev** [comment]
@ferdnyc or @peanutbutterandcrackers Would any of you know?

**Comment by ferdnyc** [comment]
Oh! Well, that was easy.

Right at the start of the file, the markers list is... wrong. Here's the `json_pp` reformatted version:
```json
  "markers" : [
      null,
      null,
      null,
      {
         "position" : 163.8637,
         "id" : "TBZDMZMCPN",
         "icon" : "blue.png"
      },
      {
         "icon" : "blue.png",
         "id" : "2VUBYQN42P",
         "position" : 23.3900333333333
      },
      {
         "icon" : "blue.png",
         "position" : 21.9886333333333,
         "id" : "ONSPFH2JXY"
      },
      {
         "icon" : "blue.png",
         "position" : 22.3890333333333,
         "id" : "NOK70IDY5P"
      },
      {
         "id" : "LIAPQM53SG",
         "position" : 195.7956,
         "icon" : "blue.png"
      },
      {
         "id" : "2A65ZHFNOB",
         "position" : 195.7956,
         "icon" : "blue.png"
      }
   ],
```

Markers is not supposed to contain `null` values. Not sure how that happened, actually if you have the logs available from when this file was saved and stopped working that could be helpful. (Multiple markers in the exact same location isn't great, either, though OpenShot probably doesn't prevent that unfortunately.)

I'll fix up the markers list, check for any other issues, dump the undo history, and hopefully should be good to go.

**Comment by techman84** [comment]
@ferdnyc Good! It works! Thank you so much.
So now that I know what's wrong in the .osp, I'm going to fix also the original project.
(For the log, if it's generated in debug mode, I'm afraid I don't have it.)

**Comment by ferdnyc** [comment]
> @ferdnyc Good! It works! Thank you so much.
> So now that I know what's wrong in the .osp, I'm going to fix also the original project.

@techman84 
Yeah, just finding `"markers"` in the .osp and removing the `null, null, null,` at the start should fix it up, without even having to reformat the file (since by default it's all saved as one very, very long line).

If you have _performance_ issues even after doing that, removing the contents of the `"history"` key would be the way to go. That's a lot harder to do without running it through something like `json_pp` to convert to a multiline format. (And that's fine to do, OpenShot can read reformatted files just as well as unformatted ones, as long as the content is valid.)

> (For the log, if it's generated in debug mode, I'm afraid I don't have it.)

Logs are _always_ written to the `.openshot_qt` directory (`C:\Username\.openshot_qt\openshot-qt.log` on Windows, as well as `openshot-qt.log.1`, `.log.2`, etc...) They contain far _more_ information in debug mode, but it's entirely possible that some message was logged even in normal mode that might help explain the file damage. 

It's a long shot, as there might not be any useful information in there (hard to say without already knowing how/_why_ it happened, which of course is exactly what we're trying to determine), or it might have happened long enough ago that the message long since been aged out of the log files on disk. But, if they're available it might tell us something.

Not a huge priority. Glad to hear you're back on track with the project.

**Comment by techman84** [comment]
@ferdnyc If it's necessary, I found the log written in 6 December after the issue happens:
https://www.dropbox.com/s/tp4neaxc0c2cn2w/openshot-qt.log.zip?dl=0
I don't know if it's useful, since it seems not to have timestamps ad the beginning of lines.

**Comment by ferdnyc** [comment]
> I don't know if it's useful, since it seems not to have timestamps ad the beginning of lines.

That's OK. Timestamps wouldn't mean anything to me anyway,  since I have no frame of reference for any of the events that occur in there. The messages are in order from earliest to latest, that's all that matters.

There doesn't _appear_ to be anything in there relevant to the bug, but it was always a long shot. Appreciated all the same.

**Comment by kollontai1918** [comment]
Hey! 
I've got a pretty similiar problem as described above: apparently there is a bug in my .osp file which causes some issues.. setting a new marker works, but: 

- I can't move the clips in the timeline

- adding new clips to the timeline causes troubles 

- the split-tool doesn't work 

I tried to start a new project where everything works as it should. 
Unfortunately my coding skills are hardly existent but it would be a lot of lost time if I had to start again (as I can't copy the clips to a new project). 

Can anybody have a look on the file? That would be great! I made a screencast and will upload the file.

[OpenShot_Project.zip](https://github.com/OpenShot/openshot-qt/files/3297676/OpenShot_Project.zip)

**Comment by SuslikV** [comment]
@kollontai1918 Please, attach your OpenShot's log-files as well.

**Comment by SuslikV** [comment]
Maybe it is too late but this is your file that should work OK, I think:

about 234KB to download, CRC of the zip archive MD5:B9FA0B8BD4E8A0D2822129D8C7296EFA
[Bourne_trailer_repaired.zip](https://github.com/OpenShot/openshot-qt/files/3304282/Bourne_trailer_repaired.zip)

I found that it fails because of two "null" objects in the "effects" section (at line 287962, 288700).
Maybe some other parts corrupted too, I really don't know. Say if it works well for you.

**Comment by joshseagull** [comment]
I have the exact same issue. I was trying to follow what you guys dude to fix it, but I have no knowledge in coding, so I was pretty confused. Any help would be really appreciated.

**Comment by jorisvial** [comment]
> I have the exact same issue. I was trying to follow what you guys dude to fix it, but I have no knowledge in coding, so I was pretty confused. Any help would be really appreciated.

It does not require any knowledge in programming.
Here are the steps that worked for me:

1. Make a copy of the project file (copy/paste the .osp file anywhere, in case you mess up the original file)
2. With a text editor, open the original project file (.osp). If you are on Windows, try to use something else than notepad otherwise it will be difficult to read (syntax may be broken). I recommend using https://notepad-plus-plus.org/download/v7.7.1.html.
3. Once you opened the file using the text editor, find the following text ```null,```
4. Delete all the lines containing ```null,```, for example:
```
// BEFORE
    "effects": [
        null,
        null,
        {

// AFTER
    "effects": [
        {
```
5. Save the file and try to re-open the project using OpenShot

Did the trick for me without loosing any data.

**Comment by joshseagull** [comment]
> > I have the exact same issue. I was trying to follow what you guys dude to fix it, but I have no knowledge in coding, so I was pretty confused. Any help would be really appreciated.
> 
> It does not require any knowledge in programming.
> Here are the steps that worked for me:
> 
> 1. Make a copy of the project file (copy/paste the .osp file anywhere, in case you mess up the original file)
> 2. With a text editor, open the original project file (.osp). If you are on Windows, try to use something else than notepad otherwise it will be difficult to read (syntax may be broken). I recommend using https://notepad-plus-plus.org/download/v7.7.1.html.
> 3. Once you opened the file using the text editor, find the following text `null,`
> 4. Delete all the lines containing `null,`, for example:
> 
> ```
> // BEFORE
>     "effects": [
>         null,
>         null,
>         {
> 
> // AFTER
>     "effects": [
>         {
> ```
> 
> 1. Save the file and try to re-open the project using OpenShot
> 
> Did the trick for me without loosing any data.

Deleting all the nulls didn't work, but deleting the nulls in the example you gave prompted me to locate all the files I used in the video and then it worked! Thank you so much for you help, I really appreciate it!
