### ISSUE TITLE
Project Files need Folders

### ISSUE THREAD

**Issue by hesco** [OpenShot/openshot-qt#2436]
**Please fill out this template** 

**Is your feature request related to a problem? Please describe.**

I find it frustrating to sort through a growing number of clips in my 'Project Files', when I'd like distinct clip bins or perhaps hierarchical file directories to help organize them.  

**Describe the solution you'd like**

**Describe alternatives you've considered**

In the Project Files view, I would urge a context menu option to create a folder, into which project files could be moved or imported.  

**Additional context**

**Comment by peanutbutterandcrackers** [comment]
True. Kdenlive has something similar. So, I'd totally get behind this.

For the time being, I have been using 'tags' on a very few of the project files to get by. First, I go to 'Details view' instead of the default thumbnails view, and then I edit the 'tags' head and then when I search for certain tags, I get the required files. Hope that'll be a temporary work-around for now.
