### ISSUE TITLE
{{GetTrackName(layer).layer.number}} instead of track Number

### ISSUE THREAD

**Issue by Haroldgomez777** [OpenShot/openshot-qt#2439]
**Deleting tracks added a new track with {{GetTrackName(layer).layer.number}}** 

**Deleted some tracks added a new track new track which shows {{GetTrackName(layer).layer.number}},**
Deleted some tracks added a new track new track which shows {{GetTrackName(layer).layer.number}},
This new track is not deletable

**System Details (please complete the following information):**
 - Linux / fedora 29: [e.g. Windows 10, Linux Mint 17.1]
 - 2.4.3 [e.g. 2.4.3]

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'open shot'
2. Click on 'Track '
3. Delete track continuously, Add new track

**Expected behavior**
{{GetTrackName(layer).layer.number}} should not be there.
Track number should be there.

**Comment by peanutbutterandcrackers** [comment]
@ferdnyc - **Sees 'Fedora'** *calls you*

**Comment by ferdnyc** [comment]
There's no way this is just a Fedora bug, simply because it was reported on Fedora. Try reproducing in Ubuntu or Mint or whatever, I'm sure you'll see the same bug. (I'm actually the worst person to look at this, because I _am_ also running Fedora. What this needs is confirmation on a different distro/OS.)

If I'm interpreting the report correctly, it's saying that deleting _all_ of the Timeline tracks, (a) is possible, and (b) causes the next track added after that to be created in a broken state.

Deleting the last track on the Timeline shouldn't be permitted. That's the bug.

**Comment by jonoomph** [comment]
I can not reproduce this error on Ubuntu or Windows. If you are seeing {{GetTrackName(layer).layer.number}}, that might indicate that Angular has experience some syntax issue and broke (since that is what should be replacing the track name).
