### ISSUE TITLE
Openshot 2.4.3 crashes when I try to add a video or audio file on my MacBook pro

### ISSUE THREAD

**Issue by Daleil** [OpenShot/openshot-qt#2446]
**Please fill out this template** 

**Describe the bug**
The Openshot Screen disappears completely when I try to add a video or audio file on my MacBook pro. 
**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]MacOS High Sierra Vers.10.13.6
 - OpenShot Version [e.g. 2.4.3]2.4.3

**To Reproduce**
1. Go to '.Openshot..'
2. Click on '..the green cross to import file..'
3. Scroll down to '.desktop to find the file and click 'open'...'
4.Openshot disappears and closes itself  See error

**Expected behavior**
I expected the jolly file to upload into openshot as it did in the previous version before I updated it.
**Screenshots** Hard to get a screenshot of a disappearing window mate.... hellooo...

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem. Have no idea where to find a log of this problem.

**Additional context**
Add any other context about the problem here. I may well be sent off to the funny farm soon as this is driving me nuts.

**Comment by speedytechdev** [comment]
Hi @Daleil you need to fill out the template please or we can't help you. Please let us know if you get stuck.

**Comment by Daleil** [comment]
Ok I filled out the template two days ago but have heard nothing back.  Have I done this incorrectly?

**Comment by speedytechdev** [comment]
No, If you have provided as much information as possible then you should be fine. We just have a lot of issues to deal with and sometimes we can't test all the issues because maybe we need a mac or etc.

**Comment by peanutbutterandcrackers** [comment]
@Daleil - Hey there. Could you perhaps create a screencast of OpenShot crashing? We could go further from there.You could use [VLC Media Player](http://www.videolan.org/) to [record your screen like so](https://www.youtube.com/watch?v=H-6gxvBBEiw). Even if we do not figure out a solution (which, I must admit, we might not), this might serve as a good reference for the devs to fix this issue.
Also, I would advise you to [attach the logs](https://gist.github.com/peanutbutterandcrackers/d84c257e74b72d8b06b4daffaebc5a14) for both libopenshot and openshot-qt (that would be libopenshot.log and openshot_qt.log) with the screencast itself. I would also advise you to insert the video in the comments as a GIF using [gifcurry for Mac](https://github.com/lettier/gifcurry#i-use-mac-apple) as such (instead of uploading the video somewhere else and attaching the link here):

![meet tux](https://user-images.githubusercontent.com/26764547/48016787-a1a13800-e154-11e8-9f1d-bfe2a64a6ad4.gif)

**Comment by bruss77** [comment]
Hi, when import the file video .mov, .mpeg the program it's abnormal close. This is system log
Dec 27 23:36:36 iMac launch[2401]: assertion failed: 16G1710: libxpc.dylib + 74307 [ABC3BB29-BCE6-3E50-8A71-4E56AEE28991]: 0x89
Dec 27 23:36:36 iMac com.apple.xpc.launchd[1] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for integer: _DirtyJetsamMemoryLimit
Dec 27 23:36:36 --- last message repeated 1 time ---
Dec 27 23:36:36 iMac com.apple.xpc.launchd[1] (com.apple.auditd[2414]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.auditd
Dec 27 23:36:45 iMac com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000010.launch-mac.sh[2401]): Service exited with abnormal code: 4

**Comment by ghost** [comment]
this issue is still persists

**Comment by Colorjet3** [comment]
Hello @adrakdavinchi It is time to upgrade to v3.0.0 and give that a try.  Not much development is going into 2.4.3.
