### ISSUE TITLE
Openshot will speed up after unplugging my headphones

### ISSUE THREAD

**Issue by CharleeLol** [OpenShot/openshot-qt#2509]
basically what will happen is i will be editing a video and when i plug out my headphones and play it again, the little thing that you can move around will go really fast and i don't know how to slow it down, in the end i just have to close openshot without saving my project and then restart editing the video i was just editing

**Comment by speedytechdev** [comment]
Hi @CharleeLol could you fill out the missing information so we can help you thanks.

**System Details (please complete the following information):**
 - Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
 - OpenShot Version [e.g. 2.4.3]

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Logs**
If you are experiencing a crash, please collect and attach logs of the problem.

**Video Profile**
If the problems you are experiencing are known to be, or may possibly be, related
to a specific format video file being used in OpenShot, please consider generating
a [MediaInfo](https://mediaarea.net/en/MediaInfo) profile and including it with your
report. Select View > Text from the menu to bring up a plaintext report, and attach
or paste it into this report. (If copy/pasting, consider adding the profile as an
additional comment after you post this initial report.)

**Additional context**
Add any other context about the problem here.
