### ISSUE TITLE
About the covering order of tracks

### ISSUE THREAD

**Issue by wxy555123** [OpenShot/openshot-qt#2517]
I want to know How to change the covering order of tracks, let lower "layer number" tracks cover the higher "layer number" tracks ? 
Is there a simple way to implement it?

Thank you !

**Comment by peanutbutterandcrackers** [comment]
You probably mean moving the lower tracks above the upper tracks... sadly, OpenShot does not have that feature yet. We will need a contributor to submit a PR adding that feature...

Hope that answers your question.

**Comment by peanutbutterandcrackers** [comment]
@wxy555123 - Wow. That is great! Thank you! We are in need for more contributors like yourself.

I'm sorry. I don't have any insights regarding this. Perhaps @DylanC might be able to help you out.

Just a minor thing, in case you haven't noticed already - which I believe you have, but just on the off chance - you'll have to branch from the `develop` branch and not from the `master` one (OpenShot is using git-flow for development) and make your changes and submit PR against the develop branch. Some contributors often make their changes in their develop branch rather than on a separate branch, which would make the process a lot easier for everyone.

All the very best. I'd love to see this new feature in OpenShot, myself. :+1: You're awesome :100:

**Comment by wxy555123** [comment]
I have found key position by using regex searching. 
You need to modify the relation operator in this function: 
`$scope.project.layers = $scope.project.layers.sort(function(a,b)`

o(￣▽￣)ｄ
