### ISSUE TITLE
Video Export 720p mp4 progress at 47% after 7 hours

### ISSUE THREAD

**Issue by xetra11** [OpenShot/openshot-qt#2519]
**Please fill out this template** 

**Describe the bug**
I recorded an ingame video with NVidia Experience and it was saved as mp4. I placed it into Track 1 of Openshot and added a simple intro text. I pressed export and it started verrryyyy slowly. I went to sleep and on the next morning it only was about 47% finished.
**System Details (please complete the following information):**
 - Windows 10
 - OpenShot Version 2.4.3
 - System Details: https://www.file-upload.net/download-13462768/DESKTOP-H3D5LKE.html.html (CPU-Z Snapshot)
 - CPU Intel i9 7900X
 - 32GB DDR4 

**To Reproduce**
1. Simply export a recorded ingame video as mp4 and 720p on my system

**Expected behavior**
export at normal speed

**Comment by tscizzle** [comment]
I'm having the same issue when rendering a simple video, on a Lenovo Thinkpad, using Ubuntu 18.04.1.

Using a quality of High, it only made it to 33.2% before it stopped progressing, and then crashed a few minutes later. I tried a quality of Low, and it made it much further, about 82%, and then crashed suddenly.

Is that expected? And are there different computers that should be able to handle the rendering load?

**Comment by nanohtpc** [comment]
same here, 2 machines, 2 versions, same files....

i think it could be a windows update thing...

**Comment by YFLooi** [comment]
While this is not a solution, I did find a workaround. 

In the Export menu, bring up the 'Advanced' tab, pop open 'Video Settings' and set the Bit Rate. The default of '15.00 Mb/s' gave me about 0.1% video every 30 minutes. I got decent video with 8.00 Mb/s and a much shorter **total** exporting time of 30 minutes. This was with about 2 GB of gaming footage taken with nVidia's GeForce Experience.

I have attached a screenshot as a guide.
![bitrate](https://user-images.githubusercontent.com/40136494/62040407-2a548c80-b22c-11e9-9b1c-8dbf554ec261.JPG)

**Comment by ferdnyc** [comment]
@YFLooi 

What you found is not so much a workaround, but an alternate path to the solution.

The bitrate field in the Advanced tab corresponds to the Quality setting in the Simple tab. "High" is 15Mbps for most presets that accept HD video, "Medium" is 5Mbps, and "Low" is 384kbps. So, if you want to export at a lower video bitrate, I'd suggest using the "Medium" quality setting.

**Comment by mikelacsa** [comment]
From gulrez2019 of issue 2524

Getting hang, launch.exe failed to start. Everything works fine until I export the video, everytime when export reaches 25% it got hanged and don not respond. Windows gives message launch.exe failed to start
A clear and concise description of what the bug is.

System Details (please complete the following information):

Operating System : Window 7]
OpenShot Version : 2.4.3
To Reproduce
Steps to reproduce the behavior:

Go to '...'
Click on '....'
Scroll down to '....'
See error
Expected behavior
A clear and concise description of what you expected to happen.

Screenshots
If applicable, add screenshots to help explain your problem.

Logs
Description:
A problem caused this program to stop interacting with Windows.

Problem signature:
Problem Event Name: AppHangB1
Application Name: launch.exe
Application Version: 0.0.0.0
Application Timestamp: 00000000
Hang Signature: 3d79
Hang Type: 0
OS Version: 6.1.7600.2.0.0.256.1
Locale ID: 1033
Additional Hang Signature 1: 3d79b9d90986516dde940a4757b40f19
Additional Hang Signature 2: 9411
Additional Hang Signature 3: 94118edeb17c58ac1fe99157b73375b2
Additional Hang Signature 4: 3d79
Additional Hang Signature 5: 3d79b9d90986516dde940a4757b40f19
Additional Hang Signature 6: 9411
Additional Hang Signature 7: 94118edeb17c58ac1fe99157b73375b2

Video Profile
If the problems you are experiencing are known to be, or may possibly be, related
to a specific format video file being used in OpenShot, please consider generating
a MediaInfo profile and including it with your
report. Select View > Text from the menu to bring up a plaintext report, and attach
or paste it into this report. (If copy/pasting, consider adding the profile as an
additional comment after you post this initial report.)

Additional context
Add any other context about the problem here.
