### ISSUE TITLE
Critical: timeline navigation segmentation fault

### ISSUE THREAD

**Issue by andrewcharnley** [OpenShot/openshot-qt#252]
Fedora 24 up to date, latest master branch or dnf provided (2.0.7)

Start new project, try to adjust timeline using slider.

Segmentation fault (core dumped)

**Comment by jeffgdotorg** [comment]
Hi @jonoomph , you and I chatted about identical symptoms (also on Fedora 24)  during TXLF.

ISTR you suggested trying the latest AppImage build; I now find that those builds get a segmentation fault on my system before the GUI even launches. Preliminary poking indicates the crash may be in the AppImage loader rather than the OpenShot distribution inside. I haven't worked out how to get a core despite having `ulimit -c unlimited` set.

I've also tried uninstalling all the RPMs, building libopenshot-audio and libopenshot from top-of-master source, and running openshot-qt from master with those installed in /usr/local. No segmentation fault, but it won't start as I seem to be missing some ZMQ-related Python dep:

```
[jeffg@monkeyfaced openshot-qt]$ ./src/launch.py 
Loaded modules from current directory: /home/jeffg/git/openshot-qt/src
      logger:ERROR Traceback (most recent call last):
      logger:ERROR   File "./src/launch.py", line 53, in <module>
      logger:ERROR from classes.app import OpenShotApp
      logger:ERROR   File "/home/jeffg/git/openshot-qt/src/classes/app.py", line 40, in <module>
      logger:ERROR from classes import info, settings, project_data, updates, language, ui_util, logger_libopenshot
      logger:ERROR   File "/home/jeffg/git/openshot-qt/src/classes/logger_libopenshot.py", line 31, in <module>
      logger:ERROR import openshot
      logger:ERROR   File "/usr/lib64/python3.5/site-packages/openshot.py", line 28, in <module>
      logger:ERROR _openshot = swig_import_helper()
      logger:ERROR   File "/usr/lib64/python3.5/site-packages/openshot.py", line 24, in swig_import_helper
      logger:ERROR _mod = imp.load_module('_openshot', fp, pathname, description)
      logger:ERROR   File "/usr/lib64/python3.5/imp.py", line 242, in load_module
      logger:ERROR return load_dynamic(name, filename, file)
      logger:ERROR   File "/usr/lib64/python3.5/imp.py", line 342, in load_dynamic
      logger:ERROR return _load(spec)
      logger:ERROR ImportError
      logger:ERROR :
      logger:ERROR /usr/lib64/python3.5/site-packages/_openshot.so: undefined symbol: _ZN8openshot9ZmqLogger4PathENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

I hope some of this is helpful.

**Comment by andrewcharnley** [comment]
Python 3 in Fedora 24 is unstable, openshot isn't the only program to exhibit issues with it. Indeed pitivi also segments. I had no problems with F23.

**Comment by jeffgdotorg** [comment]
Yes, as I mentioned to Jonathan when we spoke, I've also had problems on this system when I tried pitivi. And kdenlive. So very likely something outside his control.

**Comment by andrewcharnley** [comment]
Same, kdenlive included. In fact the only video "editor" currently working on F24 is Blender. Cinerella crashes too.

**Comment by andrewcharnley** [comment]
Now fixed in current Fedora 24 update.
