### ISSUE TITLE
Open Shot startet nicht unter W10

### ISSUE THREAD

**Issue by Mannfredoit** [OpenShot/openshot-qt#2522]
Open Shot startet nicht!
Nach Aufruf erscheint eine Fehlermeldung siehe Anhang.
Wer kann helfen?????

**Comment by peanutbutterandcrackers** [comment]
Hey there,

Sorry for the inconvenience.

You might have to wait for a newer version of OpenShot for now.

I have to close this issue because 1. we don't have a German speaking volunteer to help us out and 2. This issue does not provide us with any details of the issues being observed - no system specs, no logs, no screenshots, etc.

Please do feel free to follow up in this closed issue with any details that you can provide. Closing this for now.
