### ISSUE TITLE
Importing sequence of images takes too much time

### ISSUE THREAD

**Issue by PASTJL** [OpenShot/openshot-qt#2557]
Openshot Daily Build
Windows 10 64 Bits i5 / SSD 8Go RAM
Importing png images as a sequence takes a long time ( 250 image takes almost 5 mn)

**Comment by bobcrikey** [comment]
yes i have to agree, its the same on both linux and win 10 versions , its slow at importing an
image in comparrison with kdenlive which instantly creates a video file from the image sequence,
no waiting no delay.

Alas i brought up this very subject along time ago but it wasnt fixed can still take up to a min 
before a video is created not good.
but im hoping one day it will be fixed in openshot.

cheers 
 bob

**Comment by devel-andro** [comment]
I have the same issue.

I tried to import 1000 photos, jpegs, already resized to 1080p to make a quick sequence movie, but the import took 2.5 hours, and after selecting all images and trying to add them to the timeline, it took more 2 hours after it crashed.

Also the importing task it seems that is done in the main thread, which blocks everything.
