### ISSUE TITLE
EXPORT WITH BLACK VIDEO

### ISSUE THREAD

**Issue by peanutbutterandcrackers** [OpenShot/openshot-qt#2574]
@Carloceruti - Please open issues here and not on the wiki (it's okay, you just got a little confused). Thank you. :)

**Comment by Carloceruti** [comment]
Thank you, sorry!

**Comment by Carloceruti** [comment]
I have a problem. I made several videos exporting without issues. I always modified the same .osp file, so I didn't changed any settings in the file. With the last two videos exported in .h264 and there are black screens. The problem appears to be just on some layers, the one with more content. I can hear audio and the logo on the top layer is still visible. 
I thought it was due to framerate but it happens also in different cuts of the same original video.

**System Details**
 - Operating System / Distro: [lubuntu 18.1]
 - OpenShot Version:  [2.4.3]
