### ISSUE TITLE
NVIDIA GPU Acceleration

### ISSUE THREAD

**Issue by MyerFire** [OpenShot/openshot-qt#2582]
_**I KNOW THIS HAS BEEN ASKED BEFORE**_
**My Question:**
Does OpenShot support NVIDIA GPU acceleration?

I've done research about this and all the threads route back to the same, unanswered (or not clearly answered) threads.

**System Details**
 - Windows 10 Build 17763.rs5_release.180914-1434
 - OpenShot Version 2.4.3

**Comment by peanutbutterandcrackers** [comment]
There are branches in which hardware acceleration is being worked upon, but they are just works in progress. You can take a look at them here: https://github.com/OpenShot/openshot-qt/tree/hardware-support and here: https://github.com/OpenShot/libopenshot/tree/hardware-support

Also, because OpenShot is Free Software (not freeware), and relies only on Free and Open Source software/drivers to get things done, it is questionable as to how effectively OpenShot will be able to work with Nvidia's GPU (they are not known to be very friendly with the FLOSS community).

Hope that answers your question. Closing.
