### ISSUE TITLE
How do I create a video loop?

### ISSUE THREAD

**Issue by Bsalo** [OpenShot/openshot-qt#2588]
**Please fill out this template** 

**My Question:**
How do I create a video loop so the video will run endlessly?

**System Details**
 - Operating System / Distro: Windows 10
 - OpenShot Version 2.4.3

**Screenshots**

**Comment by DylanC** [comment]
@Bsalo - I don't think Openshot has such a feature (yet).

**Comment by David263** [comment]
I wonder if it could be added? Looping helps align video and audio better than wiping, and it has other uses, too. I see you have Menu > Help > Ask a question. Perhaps this suggestion goes there?

**Comment by caiodev** [comment]
It should be nice if OpenShot had a tool to make a certain video loop n times. Like a Text Field to tell the program to loop that specific video for like 30 times. Like those 10 hour videos on youtube

**Comment by David263** [comment]
Yes, although you can probably achieve this by copying the video to the clipboard and then pasting it 30 times. I would think it rare that you need a programmable repeat many more times than that.

And even nicer would be the ability to loop over the **playback** with a given speed. Looping is perfect for locating just the right point for a splice (edit).

**Comment by caiodev** [comment]
The problem with copying and pasting is that when you paste something it is not aligned exactly at the end of the previous thing you pasted. So, you have to manually realign all things you paste and imagine those 10 hour compilations. It would be insane realigning a video of 30 seconds until you have 10 hours. And even if you create a video of 1 hour first for example and then paste it 10 times. It would really be time wasting. Anyways, I hope a feature like that makes into the stable client

**Comment by shadyshrif** [comment]
I agree this features is needed. I have a logo animation video in the corner of my video and I want to keep it repeating all the video. If that animation is 3 seconds and my video was 10 minutes then I have to copy and paste more than 200 times :(

**Comment by CarlosMatador137** [comment]
It wouldn't take quite that long if you simply do a copy and paste function of the whole content after each cleanup of the connection. Then it's a simply power of 2 function. You'd only have to copy 8 times and then trim off the excess. 0:03, 0:06, 0:12, 0:24, 0:48, 1:36, 3:12, 6:24, 12:48. Now your 3 second video is 10 minutes long. Now the real problem is trying to do this with e 30 second video and making it 10 hours long - not because of the copy/paste work, but because of the total file size and how long that would take to export!

**Comment by Colorjet3** [comment]
I am a volunteer and this is the 2nd time I am seeing this request (not sure where I saw the other one).  Based on the how OpenShot works, not sure how this would be implemented.  What solutions have you guys thought of?  Provide some solutions and I will submit an enhancement request so that the lead developer can review and then approve/reject it.  If approved, then it will make it in the enhancement queue.

Regarding copy/paste.  If you has something that you want to loop without having the "loop" feature, you don't have to copy something say 200 times if that is what you need to do.  Here is how you can expedite the process:

1.  Drag your file from the "Project Files" onto a track.
2.  Click on the clip on the track, Copy and Paste.  Do this 5 times.
3.  Have all the clips snapped together.
4.  Now select all 5 and Copy.  Pasting now will create 5 at a time.  If you just do the paste once so now you have 10 clips snapped together, then select all 10, Copy, and now you only need to paste 20 times.

If you download the latest dev daily build #12980, as of this writing, there is a new feature where you can remove gaps between clips:
Option 1 - right click on a Gap between two clips and select Remove Gap.
Option 2 - Right click on the Track number (for example, Track 5, and you will have the "Remove All Gaps" option.  This works per track only.

This feature is not in the production v3.2.1 release.

**Comment by CarlosMatador137** [comment]
That assumes the remove gap feature works perfectly, and that you don't want to cross fade the loop. But I haven't used the remove gaps feature.

Regarding the copy paste though, it still makes sense to do one copy and the select all and copy each time. It's counter intuitive but the fastest answer if you're having to do any clicking on between pastes and not just spamming the (Ctrl+) v key.
