### ISSUE TITLE
Where are temporary render files stored?

### ISSUE THREAD

**Issue by SudoCerb** [OpenShot/openshot-qt#2602]
**Where are temporary render files stored?**

**System Details**
 - Operating System / Distro: Linux - Ubuntu 18.10
 - OpenShot Version 2.4.2

So I was busy rendering a video and OpenShot **completely** locked up my computer to the point where basic I/O (toggling Caps Lock took 30 seconds) became impossible.

I left it for about 10 minutes before doing a hard power cut and now I want to clear out any files that have been left behind (good housekeeping etc) before I re-attempt an export.

Please help!

Thanks

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Does Openshot store temp render files?

**Comment by DylanC** [comment]
@ferdnyc - Same question as I posted above?

**Comment by ferdnyc** [comment]
Well... the render process isn't really very cached, `libopenshot` renders directly to the destination file, so the only thing that would likely be lying around would be a partial export, in whatever location it was being saved to.

Things like the _preview_ cache are stored in the user's `.openshot_qt` dir ($HOME/.openshot_qt` on Linux), along with all of the other working files — some of which (PNG exports of SVG titles, animated title frames from blender, etc.) would count as working files for the render process, in a sense.

All of that's cleared out each time OpenShot creates or loads a project, normally, so all you'd need to do to clear it would be to open a project file.

However, in this case because there was a crash, launching OpenShot would probably (hopefully) cause it to attempt crash recovery. (Which, unless you have a save of your project file in its most recent state, you'd probably want to have happen.) In that case, the working files would still be there to back up the recovered project. So, if you wanted to start from a "clean slate", you'd want to let the recovery process happen, then either "File > New Project..." or "File > Open Project..." to clear out the working space and set it up for the new/loaded project.

And if you wanted to start from a _really_ clean slate, renaming or deleting `$HOME/.openshot_qt` will completely clear out everything — including your settings, any profiles you've created, etc. Scorched-earth type of stuff.

But there's very little chance that's going to affect anything (unless the export problem was a settings issue), because aside from things like animated titles OpenShot really doesn't use any sort of "pre-render" cache to begin with. Not for video, anyway.

**Comment by ferdnyc** [comment]
Forgot to mention @SudoCerb in my reply.

**Comment by SudoCerb** [comment]
@ferdnyc thanks so much for the detailed reply! This will definitely help me. Cheers!
