### ISSUE TITLE
Possible to copy and paste the clip properties from the first clip to others?

### ISSUE THREAD

**Issue by RussellofSpring** [OpenShot/openshot-qt#2630]
**Question:**
A clear and concise question, with enough context and explanation for people to answer it.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your question. You can include screenshots by
copy/pasting them here, dragging-and-dropping into this form, or clicking below and loading
images saved to your computer. All images are public, so please don't post screenshots
containing personal information.

**Comment by DylanC** [comment]
@ferdnyc - Umm, any ideas on this?

**Comment by ferdnyc** [comment]
I guess the first thing I wonder is "which properties?", since there's not a _lot_ to go on here, but really I don't think it would change the answer all that much.

Generally... I don't believe there's any way to easily mass-duplicate parameters, unfortunately. Not through the GUI, anyway. It could theoretically be done with the "Copy > Keyframes" functionality in the Clip menu (depending on the parameters, maybe), but then you'd have to open the menu of each individual target Clip and click "Paste", one by one by one. The keyframe copy/paste functionality isn't integrated with the system clipboard (it uses its own), so <kbd>Ctrl</kbd>+<kbd>v</kbd> won't "Paste" copied keyframes on even a single Clip, never mind multiple Clips.

Mass adjustment of clip parameters in the project file could be done more easily, possibly even using a text editor's find/replace functionality to automate it, but it'd require very careful editing to ensure the file isn't corrupted.

**Comment by RussellofSpring** [comment]
Most of my slides are smaller than the default project setting I have.  If I enter new horizontal and vertical sizes to make them bigger, the result is a zoom in which I don't want.  So a pix that is 2560 x 1440 displays as I want it, while most of my other pix are 2592 x 1944.  If I put that smaller pix on the timeline and alter the Scale x and Scale y so that the pix fits the frame the result is that the pix starts off with the original size and then zooms to fit.  Basic question is, do I need to resize all my pix before importing them into OneShot, or can I choose a parameter, copy it and paste to multiple pix?  Or am I doing something basically wrong?

**Comment by ferdnyc** [comment]
@RussellofSpring Aha, I understand better now. Well, there are two different things going on here:

> Most of my slides are smaller than the default project setting I have. If I enter new horizontal and vertical sizes to make them bigger, the result is a zoom in which I don't want. So a pix that is 2560 x 1440 displays as I want it, while most of my other pix are 2592 x 1944. If I put that smaller pix on the timeline and alter the Scale x and Scale y so that the pix fits the frame the result is that the pix starts off with the original size and then zooms to fit. 

The reason that's happening is because you're creating a **keyframe** with the new size, somewhere other than on the first frame of the clip.

Parameters in OpenShot aren't static settings for the clip. Each parameter can have different values at different points (in time) along the length of the clip, which allows them to animate so that they change as the video plays. Because of that, the position of the Playhead is critical when adjusting Clip parameters — whatever frame the Playhead is positioned on, the parameter value will be updated _at that frame_, creating what's called a "keyframe". And if the parameter value at that keyframe is different than previous (or subsequent) keyframes, OpenShot will "interpolate" between the two values, which just means that the parameter will gradually change from the initial value at frame A to the new value at frame B, over the course of all the frames between A and B.

When you need to adjust the _initial_ values for Clip parameters, you want to make sure that the Playhead is positioned on the very first frame of the Clip. (The easiest way to do that is to select the clip, then use the Previous Marker / Next Marker arrows on the Timeline toolbar to move the Playhead. It'll snap to the left edge of the selected clip, which is its first frame.) There's an implied keyframe at that point which contains all of the Clip's initial parameters. So, when you make parameter adjustments to the _first_ frame of a clip, you'll update the starting values in that keyframe instead of creating a new one, and the (new) values will apply to the entire length of the clip — unless you add additional keyframes to change them later on.

By setting new ScaleX/ScaleY values at the Clip's first frame, they'll take effect across the entire clip with no zooming.

> Basic question is, do I need to resize all my pix before importing them into OneShot, or can I choose a parameter, copy it and paste to multiple pix? Or am I doing something basically wrong?

Once you have an image set up the way you want it (with new ScaleX/ScaleY values set on the first frame of the Clip), you _could_ then duplicate that to other Clips this way:
1. Select the correctly-configured Clip
1. Open its menu and choose "Copy > Keyframes > Scale" (or "Copy > Keyframes > All")
1. Open the menu for a different clip, and choose "Paste"
1. Use "Paste" on any additional clips to apply the same adjustment

You'd have to do the Paste operations one Clip at a time, but that'd work to duplicate the Scale values. Obviously, it's best to make absolutely sure that the values are correct on the source clip, and that they're applying correctly to the target Clip(s), before applying them to too many other clips, and if you're updating a _lot_ of Clips you should save the project file occasionally along the way.

Now... all that being said, it still might be _better_ to resize your images outside of OpenShot, if you know you're going to want them displayed at a certain fixed size. Having OpenShot scale the images itself will increase rendering time (and it'll take longer _every_ time you render the project), and you'll have to wait until the video renders to see how they look when they're scaled. If you end up deciding that you want to crop any of them differently or anything like that, using the Scale parameters in OpenShot is kind of a tedious and clunky way to go about that.

Using an image manager (like GThumb, Shotwell, etc.), a command-line image processor (like ImageMagick) if you're handy with the command line, or even the GIMP which does have some batch tools, adjusting all of the images the way you want them is a lot easier because those tools are designed to do exactly that. And doing it that way, you could simply drag-and-drop the resized images into OpenShot, not have to worry about adjusting parameters, and the video rendering process will be faster because it doesn't have to do all that scaling.

Up to you, of course, but I'm a big proponent on using the right tool for any specific job. OpenShot is a much better video-editing tool than it is an image-resizing tool. But,as I detailed above, it's definitely _possible_ to do everything in OpenShot if that's your preference. Good luck!

**Comment by RussellofSpring** [comment]
Great response and very good advice.  I used to work with Premiere Pro when I was working, but now I'm retired the cost of annual subscription to something like Premiere is ludicrous and not able to be justified so One Shot is an excellent solution to my rather infrequent video editing needs.

One thing I've noticed is that I'm editing to a long music bed (about 10 minutes) and after a few editing sessions I've noticed that the audio gets corrupted slightly (dropouts etc) which can be fixed by simply deleting the entire audio track and replacing it with the original again.  Assume that it is just a bit of a failure to be able to handle all the video changes of pix and superimposed graphics throughout.  It is a lot of processing that needs to happen.

But I will now try and resize my stills before importing them into One Shot.  Many thanks for the good advice.

**Comment by DylanC** [comment]
@ferdnyc - Wow, you should start writing some books ferd. Your knowledge on all of this is outstanding! :+1: 

@RussellofSpring - Glad to hear you got sorted. Ferd is the real deal for answering questions in the most comprehensive manner. If you are looking for something to Batch process images there is a neat tool inside PhotoFlare to do it:  https://photoflare.io/documentation/automate-batch/

My documentation needs improvement for sure. Its looking sparse but you get the idea... and yes this is a shameful self promotion of my project. :rofl:
