### ISSUE TITLE
Openshot won't open my .OSP files

### ISSUE THREAD

**Issue by zsalah2133** [OpenShot/openshot-qt#2639]
I was editing a video for a school project in Openshot, and when I finished for the day, I saved my project to a .osp file, closed the program, and left. The next day, I tried to open up my file to work on it, but the file won't open. There are no error messages or anything; nothing happens at all when I select the file.

**Comment by speedytechdev** [comment]
Hi @zsalah2133 this is very odd. Could you make a folder that includes all the photos,videos,sound and etc used in the video. Also, include the osp file and send this to me, please.

Also to make sure, are you using the latest stable build?

**Comment by ferdnyc** [comment]
Closing due to lack of response.

If I had to _guess_ at what was happening, it's possible that @zsalah2133 accidentally saved an empty project file at some point. (Which is totally possible; for one thing you can always "Save As..." a project even when there's nothing in it.) It could be that file that's loading, instead of the one with the actual project data in it. 

Loading an empty project will give the appearance of nothing happening, since... well... nothing **is** happening.
