### ISSUE TITLE
Typo in OpenShot_website (django)

### ISSUE THREAD

**Issue by sveinki** [OpenShot/openshot-qt#2643]
**Description:**

In the PO-file with the website strings at https://translations.launchpad.net/openshot/website/+translations:

#: default/templates/default/issue.html:102
msgid "Enter a breif description of the issue"
"breif" --> "brief"

I report this here at GitHub, because my other similar report on launchpad has been dealt with, but is still marked as NEW: https://bugs.launchpad.net/openshot/+bug/1724917

**Comment by ctsdownloads** [comment]
Thank you for alerting us to this.

**Comment by ferdnyc** [comment]
Hmm. I guess we should create a tag for website issues. I've been mostly trying to avoid dealing with them here, since there's no site code in the repo and nothing we can do about website issues from here. But without any other place to report them, they keep finding their way here. And "interface" isn't really accurate (though it's the best option of the current set), in the sense of it having anything to do with the OpenShot GUI.

**Comment by ferdnyc** [comment]
Created!
