### ISSUE TITLE
OpenShot segfaults on start on Kubuntu 18.10

### ISSUE THREAD

**Issue by Fritigern** [OpenShot/openshot-qt#2645]
**Describe the bug:**
OpenShot will not start on Kubuntu 18.10 w/ Backports. Tried with stable as well as with the daily.
Stable gave a different error but still refuses to start. Reporting against daily.

**Steps to reproduce the behavior:**
1. Install OpenShot daily
2. Attempt to start either by click the icon in your launcher/start menu, or enter ```openshot-qt``` in a terminal
3. Immediate segfault.

**Expected behavior:**
Heh, I kinda expected Openshot to start. LOL

**System Details:**
- OpenShot Version: 2.4.3+dfsg2+1032+201902142319~ubuntu18.10.1
- Operating System / Distro: Kubuntu 18.10, with backports enabled.
- Qt5 version: 5.11.1+dfsg-7ubuntu2 (this is the version on libqt5core5a)

**Log Files:**
Only openshot-qt.log is created but remains empty (0 bytes).

**Exception / Stacktrace:**
Complete output follows:
```
$ openshot-qt 
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/openshot.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /usr/local/lib/python3.6/dist-packages/PyQt5/Qt/lib/libQt5Core.so.5: version `Qt_5.11' not found (required by /usr/lib/python3/dist-packages/_openshot.cpython-36m-x86_64-linux-gnu.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/openshot-qt", line 11, in <module>
    load_entry_point('openshot-qt==2.4.3.dev3', 'gui_scripts', 'openshot-qt')()
  File "/home/balaam/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/balaam/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/home/balaam/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/home/balaam/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/openshot_qt/launch.py", line 55, in <module>
    from classes.app import OpenShotApp
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/app.py", line 41, in <module>
    from classes import info, settings, project_data, updates, language, ui_util, logger_libopenshot
  File "/usr/lib/python3/dist-packages/openshot_qt/classes/logger_libopenshot.py", line 31, in <module>
    import openshot
  File "/usr/lib/python3/dist-packages/openshot.py", line 17, in <module>
    _openshot = swig_import_helper()
  File "/usr/lib/python3/dist-packages/openshot.py", line 16, in swig_import_helper
    return importlib.import_module('_openshot')
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /usr/local/lib/python3.6/dist-packages/PyQt5/Qt/lib/libQt5Core.so.5: version `Qt_5.11' not found (required by /usr/lib/python3/dist-packages/_openshot.cpython-36m-x86_64-linux-gnu.so)
Segmentation fault (core dumped)
```
---
**Addendum**
Although this may not at all be useful, I would like to mention that on my system, the full output generated by the latest stable release is as follows:
```
$ openshot-qt 
Compiled translation resources missing!
Loading translations from: /usr/lib/python3/dist-packages/openshot_qt/language
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
free(): invalid pointer
Aborted (core dumped)
```

**Comment by eszlari** [comment]
Have you tried the flatpak version?

https://flathub.org/apps/details/org.openshot.OpenShot

**Comment by Fritigern** [comment]
I did not try the (unofficial) flatpak, nor the official appimage. My experiences were only with the stable and daily PPAs.

**Comment by Fritigern** [comment]
**UPDATE:**
Issue still present in the 2.4.4+dfsg2+1039+201903210812~ubuntu18.10.1 nightly.

New info:
- The official appimage works fine, the reported issue is consistently an issue with versions installed from PPA.
- The terminal output (of the nightly) has changed slightly to the following:
```
$ openshot-qt 
Loaded modules from installed directory: /usr/lib/python3/dist-packages/openshot_qt
corrupted size vs. prev_size
Aborted (core dumped)
```

**Comment by ferdnyc** [comment]
@Fritigern 

It's been a few months, I see... sorry we weren't able to offer more help with this. I don't think any of the "regulars" here runs Kubuntu at all. 

That the issues only occur for you with the PPA builds certainly sound like a packaging/dependency issue, though. It's a tricky problem because the AppImages work for you (so it's clearly not an general issue with OpenShot itself), and the PPAs work for plenty of other users running Ubuntu or Mint (so it's clearly not an issue with the PPAs generally) — but they weren't working for you. It could come down to different library versions between the AppImages and the PPA, different compiler options used to build libopenshot or its dependencies, or something else entirely.

That `corrupted size vs. prev_size` message is a sign of memory-access violations, same as `free(): invalid pointer`. (Not the same error, but both come from glibc and are caused by pretty similar bugs in C/C++ code.) It's certainly _possible_ it was coming from libopenshot, in which case current builds may work since we have fixed quite a few memory leaks and other bugs over the past few months. Or maybe it was coming from one of the other library dependencies, good chance it's been found and fixed by now if that's the case.

I don't know if you're still tracking this issue or interested in tracking it, but I'll keep it open a bit longer in case there are any updates. If you could test the latest builds and update us about whether this is still occurring, that'd be helpful. If this is still an ongoing problem, I'm also wondering if reporting this in Launchpad might get it some attention from people with more expertise in troubleshooting issues related to apt and PPA packaging. Sorry again that we couldn't be of more help.

**Comment by Fritigern** [comment]
I had uninstalled OpenShot because if I can't use it, why keep it?
I have just installed OpenShot again and found that it now works for me again.
Since my last update, I upgraded Kubuntu to 19.04 (Disco Dingo) so there may be something that has changed there. Or it may be that one of the fixes to the memory management of OpenShot (or one of its libraries) has caused my issue to be fixed. 

I consider this issue to be resolved. I can now take to translating the UI to Dutch again :-)

**Comment by ferdnyc** [comment]
> I had uninstalled OpenShot because if I can't use it, why keep it?

Understandable, and that's exactly why I asked the question in the way I did.

> I have just installed OpenShot again and found that it now works for me again.

Thanks for taking the time to test, that's great news!

> I consider this issue to be resolved. I can now take to translating the UI to Dutch again :-)

We look forward to your contributions. :smile:
