### ISSUE TITLE
Local fonts (~/.local/share/fonts) ignored

### ISSUE THREAD

**Issue by wrogner** [OpenShot/openshot-qt#2647]
**Describe the bug**
Local fonts (~/.local/share/fonts) ignored

**Steps to reproduce the behavior:**
1. Put font file into ~/.local/share/fonts
2. Check with LibreOffice (select font)
3. Openshot -> Create Title -> select font
4. Can't select local user fonts

**Expected behavior**
Font can be selected

**Mitigation**
Copy ~/.local/share/fonts/MyFont.ttf /usr/share/fonts/truetype/MyFont.ttf
Relaunch Openshot -> Create Title -> Select Font MyFont (works)

**System Details**
- OpenShot Version: 2.4.3
- libopenshot Version:  0.2.2
- Platform: Linux-4.18.0-15-generic-x86_64-with-Ubuntu-18.10-cosmic
- Processor: x86_64
- Machine: x86_64
- Python version: 3.4.3
- Qt5 version: 5.2.1
- PyQt5 version: 5.2.1
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: en_US.UTF-8
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.4.3-dev3-1550173236-62fa7176-2f74da2f-x86_64.AppImage

**Log Files**
- http://logs.openshot.org/xpuadhm8xa427p41l41hw16up55z56a9/openshot-qt.zip
- http://logs.openshot.org/xpuadhm8xa427p41l41hw16up55z56a9/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
Screenshot on HiDP Display hard to read

**Comment by ferdnyc** [comment]
@wrogner I only just saw this, sorry. The font list we show is just whatever Qt's built in font dialog brings up, to my knowledge we have no control over the contents of the list. I imagine this issue is unique to the AppImage builds, any distro package versions will use the native system font dialog by default, which should include local fonts. 

Using OpenShot installed from a package (via the official PPA, perhaps), rather than the AppImage, is probably the best solution to making local fonts available. I don't expect this will be solved in the AppImage.
