### ISSUE TITLE
Portrait Profile

### ISSUE THREAD

**Issue by biodapesada** [OpenShot/openshot-qt#2649]
**Question:**
With the popularization of the vertical format in mobile devices, some works in the portrait format appear. I tried to create a custom profile for a 720x1280 project, with the 9x16 aspect ratio. Is that correct?

When I select the profile created, it does not work. What am I doing wrong?

Below is the profile configuration file:

```
description=HD 720 Portrait
frame_rate_num=30000
frame_rate_den=1001
width=720
height=1280
progressive=1
sample_aspect_num=1
sample_aspect_den=1
display_aspect_num=9
display_aspect_den=16
```

**System Details:**
- OpenShot Version : 2.4.3
- Operating System / Distro: Windows 10n.

**Comment by DylanC** [comment]
@N3WWN - This is a good question for you I think. (when you have the time)

**Comment by N3WWN** [comment]
It's been a while since I looked at portrait profiles, but if I recall correctly, the preview will always show widescreen, but the video should render properly.  At least that's the behavior I recall.  

Looking at the profile that you created, it looks correct.

Have you tried exporting the video to see if it does honor the custom profile during final output?

**Comment by DylanC** [comment]
@biodapesada - Follow the answer above provided by @N3WWN
