### ISSUE TITLE
Memory leak on Linux Openshot-qt 2.4.3 during video preview

### ISSUE THREAD

**Issue by NelloDraws** [OpenShot/openshot-qt#2654]
**Describe the bug:**
When I press play on the timeline to start the video preview Openshot's memory usage will continue to increase during playback until the memory is at capacity and the system locks up.

**Steps to reproduce the behavior:**
1. Add a video file to the timeline
2. Press play

**Expected behavior:**
The memory usage should not continue to increase until the system locks up.

**System Details:**
- OpenShot Version 2.4.3
- 4.20.13-arch1-1-ARCH

**Log Files:**
In the attached log file openshot-qt.log.1 I had opened a project that was a minute long. I spliced up a 1080p60fps 30mb clip so that the timeline had 40 elements in it. After watching the video preview of this project my system's memory usage was at 99% with the swap filling up (when I had 44 elements in the timeline my system locked up.)

In openshot-qt.log.2 I added a single 30 minute video file to the timeline. It was a 1080p60fps 700mb clip. After watching it for 7 minutes with the video preview Openshot's memory usage was at 90% and climbing. I stopped it before it locked up.

[openshot-qt.1.log](https://github.com/OpenShot/openshot-qt/files/2924631/openshot-qt.1.log)
[openshot-qt.2.log](https://github.com/OpenShot/openshot-qt/files/2924632/openshot-qt.2.log)

**Comment by Quix0r** [comment]
Same issue under Debian here. Linux version 4.16.0-2-amd64 (debian-kernel@lists.debian.org) (gcc version 7.3.0 (Debian 7.3.0-23)) #1 SMP Debian 4.16.16-2 (2018-06-22)

**Comment by Quix0r** [comment]
Here it happens when I edit a property, e.g. "End" value for transmission (which is not updated when I use the slider btw.) or just save it. Also tried with disk cache but no avail.

**Comment by Alayan-stk-2** [comment]
I encountered the same memory leak with 2.4.4 on Linux Mint 18.3.

I have been forced to regularly close openshot before reopening it in order to get memory usage down.

**Comment by Quix0r** [comment]
But sometimes it seems to work? It then can run for hours on full performance and with no freezes.

**Comment by Losmen** [comment]
Same Problem on Windows 7 version 2.4.4.

**Comment by ferdnyc** [comment]
2.4.4 had a pretty serious memory-consumption issue that was only diagnosed and corrected shortly after the release, it's possible that it affected 2.4.3 as well.

The pathology we _know_ about involved the export process, but it's conceivable it impacted previewing as well. The issue was that OpenShot's memory consumption would grow for each element present on the Timeline, with none of that memory being reclaimed until the entire export process completed (if it ever did manage to complete) — so that's pretty consistent with what the OP reported.

Point is, _those_ memory-consumption issues were corrected in OpenShot/libopenshot#240. (With OpenShot/libopenshot#237, OpenShot/libopenshot#236, and OpenShot/libopenshot#233 also correcting smaller leaks, all post-2.4.4 release.) All in all, by November a repeat of my earlier tests on the export process (detailed at length in #2811) showed tat memory usage during export [was **significantly** reduced](https://github.com/OpenShot/openshot-qt/issues/2811#issuecomment-559217766).

All of these changes are incorporated into the Daily Build versions since they were applied, and all are part of the current 2.5.0 release candidate builds (which are also listed under Daily Builds at https://openshot.org/download/).

If anyone experiencing memory-consumption issues in _any_ part of OpenShot would be willing to test whether they still experience the same issues with the release candidate (in particular), that'd be a huge help.

Due to the significant changes coming in 2.5.0 with the way project asset files like thumbnails and generated titles are stored, when testing 2.5.0-rc I recommend working on a _copy_ of your OpenShot 2.4.4 projects. While 2.5.0 should have no problems loading older files, projects saved in 2.5.0 may not always be 100% compatible with 2.4.4 and older versions ­— everything major should still work, for the most part, but ancillary things like clip thumbnails and etc. may not be recognized properly. So it's best to keep copies of your 2.4.4 project files just in case you need to downgrade for any reason.

**Comment by Quix0r** [comment]
I see an update to 2.5.x here. I hope it got fixed because that memory-zombie was really not nice to have around.

**Comment by jakebesworth** [comment]
Same issue here: https://github.com/OpenShot/openshot-qt/issues/3592

**Comment by MiguelCuestaM** [comment]
Same issue on Arch Linux, and it had worked just fine for a while
