### ISSUE TITLE
Powerpoint title slide in openshot

### ISSUE THREAD

**Issue by Dalachod** [OpenShot/openshot-qt#2661]
I want to import a powerpoint title slide in openshot but its not compatable, any suggestions on ways to work around or alternatives?
Title slide formating on openshot itself is too limited..

**Comment by N3WWN** [comment]
You are correct that PowerPoint slides saved in their native format are not compatible as they are a proprietary slide deck storage format.  

What you can do is open your slide(s) in PowerPoint and use Export to save the slide(s) that you want to use in OpenShot as PNG (or another standardized image format).  

I prefer PNG, personally, since transparency can be retained, although I'm not sure if PowerPoint uses transparency or not.

You may want to look into InkScape as an alternative to the internal OpenShot title editor.  InkScape is the "advanced editor" for OpenShot titles and is another Open Source project.

**Comment by DylanC** [comment]
Closing as answered.
