### ISSUE TITLE
Step by frame (left / right) does not actually step by frame

### ISSUE THREAD

**Issue by grinapo** [OpenShot/openshot-qt#2681]
**Question:**
Left/Right is supposed to step by frame. I have a stop-motion video, 66 frames total, 6 fps. 
Left/Right actually step by "imaginary frame at 30 fps" or something like that.

**Possible answer:**
Openshot converts source video into target format and fps immediately and not really editing the source (fromat). 

It seems not to be possible to pick source format as project format (if it's not in the presets) nor using source frames as [real] source.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 2.4.3
- Operating System / Distro: Linux debian/sid

**Comment by DylanC** [comment]
@peanutbutterandcrackers  @N3WWN - I'm a bit confused reading this. Makes any sense?

**Comment by grinapo** [comment]
Can I unconfuse it somehow? I have loaded a 6fps file and left/right requires 3-4-5 moves to actually step a (6 fps) frame, or in other words I have to press left ~4 times to see any change.

**Comment by N3WWN** [comment]
@grinapo You are correct;  OpenShot's frame movement is based on the project profile framerate, not the framerate of the source video(s).  

Since the profile is likely 30 FPS, it will take approx 5 frames on the timeline to see a change of 1 frame in a 6 FPS clip.  

The reason is that the project framerate, if set to 30 FPS, displays one frame for every 0.033s on the timeline.  Importing a 6 FPS project, which normally displays one frame every 0.167s, results in each imported frame being scaled ~5.06x to play at the same rate.

If you'd like to have the entire project to use a 6 FPS framerate, you can create a custom profile: 
https://www.openshot.org/static/files/user-guide/profiles.html#custom-profile

**Comment by grinapo** [comment]
@N3WWN Thanks, I was suspected that. 
My original problem, however, was the lack of feedback: I was oblivious that an empty project would not "use" the first import's attributes, or at least pop me up a warning that frame conversion is being applied. Until I started searching I wasn't aware of the conversion, and someone with less experience may have hard time to figure it out. This entry may help.
Or a popup about the conversion of the input may do so as well, or a warning that someone try to import a fire with incompatible attributes.
Thanks!

**Comment by DylanC** [comment]
No problem @grinapo. @N3WWN - Thanks again!
