### ISSUE TITLE
Openshot 2.4.4 Some title text colours display wrong after changing via the Openshot title editor

### ISSUE THREAD

**Issue by davlaw0902** [OpenShot/openshot-qt#2697]
Title text colour is wrong in some titles after changing it via the Openshot title editor

1. Start Openshot.  
2. Click on 'Title ->Title'
3. Titles template chooser opens. Choose 'Film rating 1' title. (Applies to all 'Film rating' and 'Creative Commons' titles)
4. Click on 'Text Colour'
5. Choose a text colour e.g. #0000ff (blue)
6. Click OK

The title viewer should display the text as blue.
On the default green background, it displays as orange.
If you click 'Save', the title is saved with orange text and the text shows as orange in the Project Files area and when the title is added to a track.

Edit the title to change the text to orange and it displays as blue.
Edit the title to change the text to yellow and it displays as light blue.
Black, white and some other text colour changes display as expected but several are wrong.

If you create then edit a title, choose a text colour and then click on the 'Use Advanced Editor' button, this opens Inkscape with the file temp.svg and the text colour is always correct within Inkscape.

However, within the Openshot title editor, the text colour is wrong and it saves with the wrong text colour.

Background colours appear to work as expected however, depending on the chosen background colour, different text colours are displayed.
For instance, select a white background colour.
Change the text colour to blue (#0000ff).
Text will display as red.
The text previously displayed as orange against a green background. 

There is no issue with Openshot 2.4.3 titles.
They work as expected.

**System Details**
- OpenShot Version: 2.4.4
- libopenshot Version:  0.2.3
- Platform: Linux-4.13.16-041316-generic-x86_64-with-LinuxMint-19-tara
- Processor: x86_64
- Machine: x86_64
- Python version: 3.4.3
- Qt5 version: 5.2.1
- PyQt5 version: 5.2.1
- Qt Detected Languages: ['en-GB', 'en']
- LANG Environment Variable: en_GB.UTF-8
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.4.4-1553153174-d04a71ee-fbfac789-x86_64.AppImage

**Log Files**
- http://logs.openshot.org/4zyqauvr7535po4gt2ss35eftj8bcr48/openshot-qt.zip
- http://logs.openshot.org/4zyqauvr7535po4gt2ss35eftj8bcr48/libopenshot.zip

**Comment by ferdnyc** [comment]
@jonoomph 
Initially I could not reproduce, with OpenShot 2.4.4 on Fedora 29 installed from RPM Fusion.

However, I **CAN reproduce** with both the AppImage mentioned above, and the latest `OpenShot-v2.4.4-dev1-1554580857-101f25a7-7001b687-x86_64.AppImage`. Several of the Title Editor templates are chroma-inverting certain color elements.

It's _possible_ an issue with the ReSVG build in the AppImages is to blame, since my installed OpenShot doesn't use ReSVG. But if so, it's likely been fixed, so updating ReSVG may be all that's needed.


[TitleFileName-1.svg.txt](https://github.com/OpenShot/openshot-qt/files/3077232/TitleFileName-1.svg.txt)

I built the latest ReSVG 0.6.1 from git, and its `rendersvg` tool renders the above SVG file in blue-on-green, as expected, and as it displays in any image viewer. That's also how it imports into OpenShot 2.4.4 on Fedora.
```console
$ git clone https://github.com/RazrFalcon/resvg.git; cd resvg
$ rustup override set nightly  # Some dependencies use experimental features
$ cargo build --features qt-backend
$ cd tools/rendersvg; cargo build --features qt-backend
$ cd ../../target/debug
$ mv /tmp/TitleFileName-1.svg.txt /tmp/TitleFileName-1.svg
$ ./rendersvg /tmp/TitleFileName-1.svg /tmp/TitleFileName-1.png
```

![TitleFileName-1](https://user-images.githubusercontent.com/538020/56091233-37668f00-5e7a-11e9-902b-a595106b73f4.png)

But if you load that same SVG into any of the recent AppImage builds, it will display the text orange-on-green.

**Comment by ferdnyc** [comment]
Curiouser and curiouser!

I thought to test this on the Windows build of 2.4.4, which also includes ReSVG, but on _that_ platform the color inversion is not present. So this appears to be an issue with the Linux AppImage build's SVG support, specifically.

![image](https://user-images.githubusercontent.com/538020/57042050-a6d9ce00-6c31-11e9-9c10-82f3511d3d71.png)
