### ISSUE TITLE
Track area too small in Simple View

### ISSUE THREAD

**Issue by DylanC** [OpenShot/openshot-qt#2704]
This is the view by default when I open the AppImage.
OS: Ubuntu 18.04/Pop OS. 64bit

![default_simple_layout](https://user-images.githubusercontent.com/4488048/54865305-7b72e200-4d5b-11e9-9ad7-75a565ff6952.png)

**Comment by bowmanhost** [comment]
I get the same behavior using OpenShot-v2.4.4-x86_64.appimage under Manjaro.

The default lower edge of the track area is rather far from the bottom of the application window under both the Simple and Advanced Views.

The track area can be dragged lower using the handles that appear below the track area.

**Comment by N3WWN** [comment]
I can confirm this with OpenShot-v2.4.4-x86_64.appimage on Fedora.    The blank area at the bottom shows up every time I launch OpenShot.

The Mac OSX .dmg for 2.4.4 does not exhibit this issue.

**Comment by bowmanhost** [comment]
I have become interested in potentially contributing to OpenShot development as I have just recently begun learning Qt and have been looking for a project to get started with. All that to say, I am brand new to open source development.
I am trying to see if I can shed any light on this bug. So if I post anything that makes no sense, please let me know :)
When I launch `$ ./OpenShot-v2.4.4-x86_64.appimage ` one of the output lines is: `QMainWindow::addDockWidget: invalid 'area' argument`

Does this relate to this code in 'main_window.py'?
```
    def addDocks(self, docks, area):
        """ Add all dockable widgets to the same dock area on the main screen """
        for dock in docks:
            self.addDockWidget(area, dock)
```
I am not sure if the 'addDocks' method is related to this bug or not.

Note. If there is a better way for me to ask for help in trying to assist in tracking down this bug, please let me know!

**Comment by ferdnyc** [comment]
@bowmanhost  (...three weeks later...)

> When I launch `$ ./OpenShot-v2.4.4-x86_64.appimage ` one of the output lines is: `QMainWindow::addDockWidget: invalid 'area' argument`
> 
> Does this relate to this code in 'main_window.py'?

That's a likely source for the log message in question. To be honest I'm not immediately sure, there are a few possible scenarios that come to mind, but in all likelihood it's probably pretty harmless. Regardless...

> I am not sure if the 'addDocks' method is related to this bug or not.

Definitely not.

Here's where we have to get deep into the weeds on OpenShot's rather unique relationship with the Qt window layout and UI framework.

The basic structure of the OpenShot application window (its size and shape, the menubar, main toolbar, status bar, and collection of docks contained within it) is defined within `src/windows/ui/main_window.ui`. Fairly standard for a Qt application.

What's _less_ standard is the fact that _only_ the basic structure is defined in the UI file. None of the design, appearance, state, or interactivity of any of the GUI components is present there, or in other data files typical of a QtWidget-based GUI application. 

I won't try to puzzle out the reasons for that (mostly because I had nothing to do with making any of those choices, so I don't really know how they came about) but from a _technical_ standpoint, there is one primary factor that continues to be relevant: The AngularJS-based Timeline interface.

Because the Timeline is implemented in a third-party JavaScript framework, its interface can't be tied in to Qt _directly_. And since **most** of the OpenShot interface centers around this Timeline that Qt doesn't know anything about, there's a lot of bridging that has to happen because every stick and pebble of that interface ends up needing to be constructed, "by hand", from within the code on both sides of the bridge. Which is why `src/windows/main.py` is > 2500 lines, and there's another 2000+ lines of JavaScript in `src/timeline/` just to enable the Timeline interface, _**not** even counting_ the jQuery and Angular library files.

So, anyway, in terms of the issue at hand, the application window layout is all managed at just a couple of spots in the code, and they're right here:

https://github.com/OpenShot/openshot-qt/blob/d8db1a3ac054b72f5dc659274de4eb9ae7312dd0/src/windows/main_window.py#L1877-L1880

https://github.com/OpenShot/openshot-qt/blob/d8db1a3ac054b72f5dc659274de4eb9ae7312dd0/src/windows/main_window.py#L1896-L1899

Everything that makes the Simple View or Advanced View appear as it does has been encoded into those two crazy-long strings. I wrote up an explanation of just what's happening there and how you'd go about changing it last year, in this comment over in my fork: https://github.com/ferdnyc/openshot-qt/issues/6#issuecomment-434242316  (The previous discussion there might also be of some interest.)
