### ISSUE TITLE
Color range settings for output?

### ISSUE THREAD

**Issue by SuslikV** [OpenShot/openshot-qt#2711]
**Question:**
Is there way to flag the video with the used output color range, color transfer, primaries, matrix etc. or feature not implemented yet?

**System Details:**
- OpenShot 2.4.4 (OpenShot-v2.4.4-1553153504-d04a71ee-fbfac789-x86_64 / March 20, 2019, 9:44 p.m.)
- Windows 7, 64-bit

------------
**Edit:**
With PNG images from the:
https://obsproject.com/forum/resources/obs-studio-color-space-color-format-color-range-settings-guide-test-charts.442/

I always get BT.601 for my 1280x720 MP4 videos created with OpenShot and I don't know how to change this. YouTube expects BT.709 right now (even if video not flagged).

**Comment by ferdnyc** [comment]
@SuslikV 
I've spent the day (OK, now two days) trying to wrap my brain around this issue. Now, you obviously understand this stuff _far better_ than I do, so please bear with me, as I'm _sure_  I have some things wrong. But I'm hoping you can help me get a better understanding of how we **should** be handling this stuff.

> YouTube expects BT.709 right now (even if video not flagged).

Do you have a source for that? The only info I can find alternately recommends 4:2:0 or 4:2:2 color subsampling (depending whether you're reading their [general format advice](https://support.google.com/youtube/answer/1722171?hl=en) or their [music video creator help](https://support.google.com/youtube/answer/6039860?hl=en)), but they _never_ mention any specific color profile — and the Music Video Creator stuff is **very** technical.

But the larger issue is that, at least from my understanding, the `colorspace`, transfer chracteristics (`color_trc`), and `color_primaries` video options are purely _advisory_ — they're part of [Annex E of the H.264 standard](file:///home/ferd/Dropbox/Tech/T-REC-H.264-201704-I!!PDF-E.pdf), the "Video usability information" section — and are only meant for documenting the parameters of the encoded video content. 

`x264 --fullhelp` says the following:
> Video Usability Info (Annex E):
> The VUI settings are not used by the encoder but are merely suggestions to the playback equipment. See doc/vui.txt for details. Use at your own risk.

and [that `doc/vui.txt` file](https://code.videolan.org/videolan/x264/blob/master/doc/vui.txt) explains (to paraphrase) "you should set these if you know the details, but better to leave them unset than set them wrong" and claims that they don't know of any player that attempts correction based on them. In fact, I've seen claims on the net that they're completely ignored **everywhere**, though my own tests didn't bear that out.

With VLC playing directly to VDPAU, the set of available output formats becomes much more constrained (my GT 710 only cost $50), but using OpenGL or software rendering I found that the tagging made more of a difference. Interestingly, FFMpeg's own `ffplay` _really_ doesn't care about tags. Or about subsampling — it always outputs 4:2:0, so I had trouble even detecting the subsampling changes until I switched from `ffplay` to VLC. 

On YouTube, the effect of the tags was... unpredictable. But it's hard to say for sure, as I started running into trouble trying to A/B test various combinations. YouTube started rejecting new tests as duplicates of earlier uploads, and of course it doesn't tell you _which_ earlier upload...

Anyway, on to my tests, in the hopes that you can help me get a better understanding of how we can best approach all this.

I decided early on to eliminate OpenShot from the mix entirely, because ultimately we're at the mercy of FFMpeg and whatever it can do, we can do. (If we find the right way to do it.) So i wanted to get a handle on how video generated by FFMpeg and uploaded to YouTube is processed. I'm not sure I succeeded in gaining any better **understanding**, though maybe you can help with that.

I used your `1280x720_chroma_subsampling_test_chart.png` to generate a bunch of different 15-second videos, and uploaded them to YouTube. You can see them all in this playlist. (it's Unlisted, but should be viewable by anyone who has the link — let me know if you have any problems accessing it) The command line used to produce each file is in its description.

https://www.youtube.com/playlist?list=PLHAD75fuLWMMK26x-yWTHPn3fIvXUc2Nj

In basically every case (when it comes to the 4:2:0 videos, anyway), the video
as it displayed on YouTube seemed largely to match what I was seeing in VLC.

At every step, what I saw matched the _tests_ in your chart, and seems to bear
out the note on your OBS post about ffmpeg always using BT.601 by default. The
only way I could convince it to output a video that _tested_ correctly for
BT.709 (based on matrix tests at the bottom or left of the image, depending on the pixel format used) was to apply a video filter `-vf scale=out_color_matrix=bt709`.

And what concerns me is... those (ostensibly "correct") files were the only ones that passed the chart tests, but they don't seem to be the best-looking ones.

For instance, these are details from the file I filtered into BT.709. Doing that was the only way to get the bottom matrix check to match the right-hand reference, and it does indeed match. But the colors don't strike me as particularly spectacular, nor do the letters look especially good.

![Colorspace yuv420p filter709untagged 1](https://user-images.githubusercontent.com/538020/56393637-1350d800-6203-11e9-9c59-bf5beab084e0.png) 
![Colorspace yuv420p filter709untagged 3](https://user-images.githubusercontent.com/538020/56393648-1946b900-6203-11e9-9c84-15d5d2ebc464.png) ![Colorspace yuv420p filter709untagged 4](https://user-images.githubusercontent.com/538020/56393650-1ba91300-6203-11e9-9505-1cbe7974291b.png)

OTOH, here are some details from the file I let ffmpeg convert without the filter to change colorspace, but tagged explicitly as BT.601 using `-colorspace smpte170m -color_trc smpte170m -color_primaries smpte170m`:

![Colorspace yuv420p tagged601 1](https://user-images.githubusercontent.com/538020/56393709-3f6c5900-6203-11e9-8e76-5692c585ee96.png)
![Colorspace yuv420p tagged601 2](https://user-images.githubusercontent.com/538020/56393727-48f5c100-6203-11e9-868f-79dcf37b3298.png)
![Colorspace yuv420p tagged601 3](https://user-images.githubusercontent.com/538020/56393737-4abf8480-6203-11e9-9127-234d7c40321c.png)


And these are from one I left untagged. I'm not seeing a big difference, but they both look pretty OK to me:

![Colorspace yuv420p untagged 2](https://user-images.githubusercontent.com/538020/56393774-57dc7380-6203-11e9-9027-f8987a1438c0.png)
![Colorspace yuv420p untagged 1](https://user-images.githubusercontent.com/538020/56393789-5c089100-6203-11e9-8d6b-bc25c603902e.png) ![Colorspace yuv420p untagged 3](https://user-images.githubusercontent.com/538020/56393792-5dd25480-6203-11e9-96b1-478d7f18ccf0.png)


Finally, these are from the version I encoded without the `-pix_fmt yuv420p` argument, meaning FFMpeg chose 4:4:4 automatically. I also didn't apply any tagging. Yes, this fails the _test_ for color matrix (the chart shows it as "BT.601 matrix over BT.709 source"), but I'm not sure I see where that's detrimental to the actual output quality.

![Screenshot from 2019-04-18 13-09-02](https://user-images.githubusercontent.com/538020/56393811-6b87da00-6203-11e9-86a8-1b593bc7b9ed.png)
![Screenshot from 2019-04-18 13-09-31](https://user-images.githubusercontent.com/538020/56393815-6f1b6100-6203-11e9-934f-5381c43b0006.png)
![Screenshot from 2019-04-18 13-09-41](https://user-images.githubusercontent.com/538020/56393822-72aee800-6203-11e9-8634-dbac491af790.png) ![Screenshot from 2019-04-18 13-09-18](https://user-images.githubusercontent.com/538020/56393828-75a9d880-6203-11e9-807f-7eea4380e35d.png)


As I said, I'm mostly just trying to understand the issue here. But if the solution to getting "correct" BT.709 output is to apply the swscale filter to our output, that seems like a non-starter.

**Comment by SuslikV** [comment]
##About YouTube##
As soon as 4:2:0 chroma subsampling was mentioned - there is no space left for BT.601 (because it is too old, and in 601 recommendations there is no info about 4:2:0 - only 4:4:4 and 4:2:2, while 709 recommendations has info about 4:2:0).
My statement: "YouTube expects BT.709 right now (even if video not flagged)." only based on my own experience with YouTube. I'm from Ukraine, so its European servers is closer to me than any others. I don't think that the raw video that I upload to service is transferred to USA and only than it re-encoded to 240p, 360p, and so on.
Also, you give me a video list from which I can say that the processing of the colors is almost similar (and I assuming that these videos was processed by USA servers).
As far as I understand, the main agreetment on BT.709 exactly was to simplify/unify the exchange of videos (between NTSC vs PAL/SECAM traditions), and not the only move to adopt the new green phosphor of CRT displays in 90-s.

##About FFmpeg##
When the test charts were made (2016) I used FFmpeg like this (yuvj444p - with "j" was required to get PC range):
`ffmpeg -loop 1 -i "original.png" -c:v libx264 -t 10 -pix_fmt yuvj444p -crf 0 -color_range 2 -color_primaries bt709 -color_trc bt709 -colorspace bt709 out_colorspace_test444.mp4`
You may try your VLC Player with the video generated by FFmpeg command line, see above.

##About your screenshots of test charts##
I'm assuming that it was saved and displayed exactly the same, because I saw previously how screenshot of video footage can do its own conversion. On screenshots the main issue is color difference between the green and magenta (for example).
I see TV Range   green bar of BT.709 as -  14, 180,  14 (R,G,B) - let's assume it's OK.
I see TV Range magenta bar of BT.709 as - 179,  16, 181 (R,G,B) - and it's no bad, because the deference between the G and R,B is insignificant (180 vs 179).
But
I see TV Range   green bar of BT.601 as -   2, 155,  10 (R,G,B) - let's assume it's OK.
I see TV Range magenta bar of BT.601 as - 191,  42, 183 (R,G,B) - and it's bad, because the deference between the G and R, B is more than 10% (155 vs 191).
So, I see colors difference. It's not about display gamma, transfer characteristics, overall brightness, perception brightness, scale etc.  of the viewed image/device I'm using - it's about the color difference.
Of course, it is hard to notice, and it mostly visible in such synthetic images but... But it means that video is processed using wrong color matrix (different coefficients for green etc.).
Forget about the color spill, blur and some other artifacts.

##Conclusion##
If you are using modern hardware (not VHS) - use only BT.709 (no matter what size of video is). Era of BT.2020 (or newer) is close, but it will f... mixup the things again. So, in my videos, right now, I should has some tips how to decode it (and maybe, in far future, how to display it).

**Comment by SuslikV** [comment]
The https://github.com/OpenShot/libopenshot/pull/219 now answers to my question, so I will close it soon.

**Comment by ValZapod** [comment]
> 4:2:0 chroma subsampling was mentioned - there is no space left for BT.601

Absolutely false.

> yuvj444p

This was deprecate for 11 years. It will still work correctly but seriously?? Use  -vf scale=out_color_matrix=bt709:out_range=pc,format=yuv420p -color_primaries bt709-colorspace bt709 -color_trc bt709 -color_range pc
