### ISSUE TITLE
Crash on project open if Transition file not exist anymore

### ISSUE THREAD

**Issue by SuslikV** [OpenShot/openshot-qt#2735]
**Describe the bug:**
Crash on project open if Transition file not exist anymore

**Steps to reproduce the behavior:**
1. Add custom file PNG to "\transitions\extra\" folder
2. Use this new file in your project (add it to any track)
3. Save project, close editor
4. Remove the file added at p1 (or rename it)
5. Start application and load the project saved at p3
6. Application will crash

**Expected behavior:**
Application should warn user that the resource is missing.

**System Details:**
- OpenShot 2.4.4 (OpenShot-v2.4.4-1553153504-d04a71ee-fbfac789-x86_64 / March 20, 2019, 9:44 p.m.)
- Windows 7, 64-bit

**Project file to reproduce the use:**
[OpenShotCrashTest.zip](https://github.com/OpenShot/openshot-qt/files/3073077/OpenShotCrashTest.zip)
(unpack and try to open the _CrashTest01.osp_; the missing file named "my_transition.png")

**Comment by ferdnyc** [comment]
While I suspect this is still the case, with the current transition handling, it's _somewhat_ mitigated by the fact that it's now possible to use Project Files as transitions. So, the _safer_ way to make use of a custom transition (especially one that may be transient) would be to import it into Project Files, then select that imported file as the transition Source.

I agree the missing transition file shouldn't crash OpenShot, but since it's well-known that it deals poorly with missing files, it's safer not to use `.openshot_qt/transitions/` for non-permanent files. (Actually, it's safer not to use it at all.)
