### ISSUE TITLE
Split clips does not working

### ISSUE THREAD

**Issue by ghost** [OpenShot/openshot-qt#2737]
**Describe the bug:**
I am trying to cut mp4 file (one hour long) into small clips. I cannot work after 32 minutes of video's length (frame 43 000). Also preview video window (right click on mp4 video - select preview video) does not work after 43k frames.

I also search same issue on GitHub, but work-around does not work (setting more MB to cache, or lower preview quality).

**Steps to reproduce the behavior:**
1. Import mp4 file, long more then 32minutes
2. Click on 'Split clips'
3. Scroll after 32 minutes
4. Nothing is previewed

**Expected behavior:**
Working preview.

**System Details:**
- OpenShot Version 2.4.4.-dev1
- Operating System / Distro: Windows 10

**Comment by SuslikV** [comment]
'Split clips'? Do you mean option _Slice -> Keep Both Sides_ - it slices the source clip at current position into two separate clips (still aligned in timeline)? I can slice even bigger clips... Something special about your file? Can you remultiplex it into .mp4 with FFmpeg first, and only then add it to openshot?

**Comment by jnez** [comment]
I mean this split function:
<a href="https://ibb.co/nnZsHy5"><img src="https://i.ibb.co/nnZsHy5/clips.png" alt="clips" border="0"></a>
(import video, right click and choose: split clips)
It works - I made 5 clips, but after 32minutes of main file, it does not working. I cannot continue to made 6th clip. Preview is freeze. When I go back before 32 minutes of this main video file, it works- preview is working.

My video was: 
=====================================================
Codec 4CC:		H264
Image Size:		1280 x 720
Aspect Ratio:		1:1 (1:1)
Frame Rate:		23.981 fr./s
Total Duration:	00:55:23.529

I change codec through Avidemux to DivX (FFmpeg I cannot use, because there was warning about bad resolution and framerate...). And now it is:

Video
=====================================================
Codec 4CC:		DIVX
Image Size:		1280 x 720
Aspect Ratio:		1:1 (1:1)
Frame Rate:		23.975 fr./s
Total Duration:		00:55:23.529

And still not working. Seems to be problem OpenShot editor, not codec...

**Comment by SuslikV** [comment]
Oh, I see. Just add your file to any Track, move timeline cursor to desired position, right-click over it _Slice -> Keep Both Sides_ - you have two clips in the track that can be moved to any position/track, may has own properties and so on.

Like this (see picture below the spoiler):
<details>
  <summary>Click to expand</summary>

![Openshot Split vs Slice bug](https://user-images.githubusercontent.com/19683044/56093691-1fb7f680-5ecc-11e9-9c04-bb548cc7c1ca.png)

</details>

The mentioned bug is only related to _Project Files_ dialog widget not to tracks _Timeline_.

**Comment by jnez** [comment]
THX for this work-around!

**Comment by Erikcht** [comment]
It is not working for me too

**Comment by SuslikV** [comment]
@Erikcht You need to update your program to the latest daily build, because the fix was here: https://github.com/OpenShot/openshot-qt/pull/2832 and was merged to develop branch long time ago.
