### ISSUE TITLE
[Question] Delete key frame?

### ISSUE THREAD

**Issue by csmith262** [OpenShot/openshot-qt#2744]
Is there a way to delete a keyframe?   Thx.

**Comment by SuslikV** [comment]
Clarify it, please. What do you mean by "keyframe"? You need some special effect in your video?

**Comment by csmith262** [comment]
If I created a several key frames on a clip (shown as green tics), then decide I want to remove one, how do I do that?

**Comment by SuslikV** [comment]
Navigate timeline cursor to the desirable animation key (use left/right arrows on keyboard to move frame-by-frame). As soon as the background color of the the animated property of the clip will turn into green color (make sure that you can see required property and its value, and it is not selected, because otherwise the selection has blue color background and you can miss the green - it will be overwritten by selection color) - right click over the selected property name and choose - _Remove Keyframe_. At the same position couple of frames can be animated (for the selected clip they has blue background color for the names in Properties)...

**Comment by csmith262** [comment]
@SuslikV, thanks for the tutorial, didn't see these steps in the user guide, maybe I overlooked them.

So far, I like OpenShot... :+1: ).   Been trying out several video editors, there is one that crashes too often, another plays well on Linux, but not Win.  Never have done PyQt, only C\C++ and Qt for work.
