### ISSUE TITLE
OpenShot bug report tool gives wrong location of log files in Windows

### ISSUE THREAD

**Issue by David263** [OpenShot/openshot-qt#2757]
**Describe the bug:**
OpenShot bug reports give wrong location of log files in Windows.

**Steps to reproduce the behavior:**

From OpenShot website:
1. click Support
2. click Report a Bug
in steps 1 and 4, the given paths do not exist (no such directory)

**Expected behavior:**
I expected a directory that exists.
C:/Users/USER/.openshot_qt does not exist for my USER name.

**System Details:**
- OpenShot Version 2.4.4
- Operating System: Windows 10

**Log Files:**
Well, um...

**Exception / Stacktrace:**

**Screenshots:** (Optional)

**Comment by SuslikV** [comment]
And where is your `openshot-qt.log` file located then?

**Comment by ferdnyc** [comment]
@David263 That's very strange, because it's where those files _should_ be. The only thing I can think of is that OpenShot wasn't running with permission to write files to that location, in which case it wouldn't be able to save logs (or settings, or any working files...) The daily build versions (and the next release) do a check for that problem on startup, and warn the user instead of continuing to run.

But if the log files aren't there, they very likely aren't anywhere, unless your system has some sort of unexpected configuration for where `%USERPROFILEDIR%` is located. (Possible, especially if it's a machine on a school or corporate network).

Anyway, the information shown is correct for 99.9% of users, closing this as one of those "can't account for _every_ possible variation in users' local setup" things.
