### ISSUE TITLE
How to fast forward more than x16 (f.e. x32 or x64)?

### ISSUE THREAD

**Issue by kriekos** [OpenShot/openshot-qt#2766]
**Describe the bug**
Twice fast forward on same clip gets as result a slice.

**Steps to reproduce the behavior:**
1. Click on Time > Fast > Forward > x16
2. Click on Time > Fast > Forward > x2

**Expected behavior**
Fast forward x 32

**System Details**
- OpenShot Version: 2.4.4-dev1
- libopenshot Version:  0.2.3
- Platform: Windows-10-10.0.17134
- Processor: Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
- Machine: AMD64
- Python version: 3.6.4
- Qt5 version: 5.9.1
- PyQt5 version: 5.9
- Qt Detected Languages: ['nl-NL', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.4.4-dev1-1556832014-8fb72aae-9a1a6093-x86_64.exe

**Log Files**
- http://logs.openshot.org/aiha1satgqrni9l9z0vsfmx2ct1trk60/openshot-qt.zip
- http://logs.openshot.org/aiha1satgqrni9l9z0vsfmx2ct1trk60/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Comment by SuslikV** [comment]
Try to set _Time_ property of the selected clip at the given _Timeline_ position to the last frame value (number of frames in the fragment, - info about frames available at _Project Files -> File Properties-> Frame Settings_). Then cut off unneeded part of the video clip (that is now on the right of the _Timeline_ cursor current position)

More info is here:
https://github.com/OpenShot/openshot-qt/issues/1538

**Comment by kriekos** [comment]
> Try to set _Time_ property of the selected clip at the given _Timeline_ position to the last frame value (number of frames in the fragment, - info about frames available at _Project Files -> File Properties-> Frame Settings_). Then cut off unneeded part of the video clip (that is now on the right of the _Timeline_ cursor current position)
> 
> More info is here:
> #1538

Thx, I tried it a million times but it doesn't work for multiple clips. I asked more help at #1538. But could you so be so kind to elaborate on what you set on the info about frames? Can't find the _Frame Settings_.

**Comment by SuslikV** [comment]
The _Project Files_ section (where all project's files lies) has own right-click menu, and there is file properties you asked about. But as soon as the file is single one and was sliced to many - you don't need this section of properties.

The fast/slow forward still has bugs in OpenShot. The x32 forward is huge number. If you need time-lapse software better look for other solutions.

**Comment by kriekos** [comment]
I'm making a 2hr video into a 10min video. Some parts are regular speed, some up to x64. Here is a summary (that I made base on, among others, #1538.

[2019.04.03 v5.xlsx](https://github.com/OpenShot/openshot-qt/files/3204343/2019.04.03.v5.xlsx)

You think tame laps software is better suited for this?

**Comment by crgarcia12** [comment]
When I do Fast Forward 16x, and then again 16x.. the second one simply trims the video

**Comment by Colorjet3** [comment]
Most likely a bug and will need to be confirmed by the lead developer.

This video shows you how to set custom speed.  The video is about custom speeding up but I am sure it can be used for slowing down as well:  https://www.youtube.com/watch?v=RAyydiE6Xno&list=PLqq8viq6f2kdP2q_qM4i4W4imHmGwasGG&index=29

**Comment by Clasyc** [comment]
Off topic, but why is something like changing time speed implemented in such a difficult way from a UX perspective? If there are options like 2x, 4x and so on, then clearly there's no technical challenge in adding a simple user-defined multiplier for time speed. I sincerely don't understand such strange constraints.

**Comment by Colorjet3** [comment]
Hello @Clasyc

1.  The ability to input a custom speed is in the queue for an enhancement.  It is up to the lead developer when to implement it so no ETA.
2.  However, if you download the latest dev daily build of v3.5.1 from openshot.org/download/#daily you will note that you can easily change the speed of a clip by:
a.  Drag your video onto a track and select it.
b.  From the timeline toolbar there is now a "Clock" icon.  Click it once and you will enable "Enable Timing".
c.  Once it is enabled, you can grab the right edge of the clip and stretch it (slow motion) or shrink it (fast motion).
d.  Don't forget to click the "Clock" icon again to disable the option when done with it.

I hope this helps.

You can use the new feature combined with the presets as well.  For example, you want to fast forward something slightly more than 2x.  First go ahead and set the 2x and now use the "Enable Timing" option to further decrease/increase the speed.

There is still room for improvement here because in my example if I want to achieve 3x how do I know that I achieved it using this method.  The "Time" attribue in the Property window doesn't tell you much either.

For now, you have a way to make your own variable speed.
