### ISSUE TITLE
Export with the same video format as the input clip 

### ISSUE THREAD

**Issue by lagagain** [OpenShot/openshot-qt#2788]
**Describe the new feature:**
How about this [issue](https://bugs.launchpad.net/openshot/+bug/1166169/) at launchpad.

> One of the most basic uses of a video editor is to just trim a part of a clip or to rotate it. This is much harder than it needs to be in openshot.
> 
> If there is only one clip imported, then the export format should be the same format as the input clip. This default can of course be changed should the user wish to, but having this default will make openshot much easier for beginners and more practical for at least some intermediate users.
> 

I have the same problem, but I hadn't found any solutions.

**Describe the solution you'd like:**
More easily create a custom profile by right click clip file, and use the profile.

**Describe alternatives you have considered:**
or easily copy file profile to the clipboard, create custome profiles and reopen application by self.

**Comment by SuslikV** [comment]
It will require to implement the profile change on the fly first.

**Comment by N3WWN** [comment]
Keep in mind that the clip will likely be re-encoded regardless of the profile due to the nature of libopenshot.  

For trimming only, there are other tools which are better suited to the task;  I personally will use ffmpeg with the `-c copy` parameter on the command line for such things since it copies the audio and video streams instead of re-encoding them.

Rotation can sometimes be handled in metadata by some tools, which would not require re-encoding, but definitely would in OpenShot.  I say sometimes because support for video orientation specified in the metadata has varied support between tools/players.

**Comment by lagagain** [comment]
I have this question because I want to merge two or more file and cut some section. Although I set the profile with same as video profile, the output which is played in the player doesn't look like the original video.

And then, I do my jobs with kdenlive which is another software.

**Comment by dailytabs** [comment]
Very strange that I cannot easily preserve the original video size. Well, not strange, just very stupid.

**Comment by crolt** [comment]
I'm becoming crazy to set the output format after the rendering, to view the video in the same way of the original one. Even if the originale frame format is 720x576 (source from TV with a Pinnacle dongle for recording), I'm able to enlarge it with VLC and view it in a 16:9 format with the horizontal completely fullfillinf the screen. Why the ouput must be cutted also horizontally even setting the Video Profile at 1920x1080 16:9? But I suppose it's a matter not of rendering, because even the preview is similar to a 4:3 instead of a 16:9...

**Comment by jtwebman** [comment]
I wish at least that there was a custom setting where I could just set each one myself and maybe even create a profile. This is a bummer as I started to like this tool.

**Comment by rcorsari** [comment]
Hello
did any of the developers thought about a feature like "export video with original aspect" 
so same resolution and same everything?
thank you

**Comment by Flexmaen** [comment]
This would really be all I need!
Last time I just needed to do a quick fix on a single video (which still needed new rendering).
After export it was either 16:9 instead of 4:3 or it was 4:3 and shrinked with black borders.
I had no clue how to get the same video out as I loaded in.

Can it be so difficult to just export the same format, same resolution, same aspect ratio and same fram rate, like the video already had?
