### ISSUE TITLE
[Request] Delete track's empty beginning command

### ISSUE THREAD

**Issue by radeksvarz** [OpenShot/openshot-qt#2789]
Having a very long clip (more than 1 hour) I clipped some 5 seconds at around minute 40. That was far away on the timeline and it is tedious to move such subclip to the beginning using drag and drop at the x seconds zoom. 

When I zoomed out the 5 secs short clip was too small to properly drag it. Actually I even rather resized the clip by mistake.

I would ideally right click into the empty space and issue the delete empty space command.

As discussed here: https://www.reddit.com/r/OpenShot/comments/bntd6y/how_to_move_clip_to_the_beginning_of_the_track/

**Comment by ferdnyc** [comment]
@radeksvarz Mmm, that's a good idea. Audacity has a whole host of Align Track functions that let you move selections around in different ways.

![Audacity-AlignTracks-Menu](https://user-images.githubusercontent.com/538020/61611930-207aca00-ac2b-11e9-9b29-99af5ef7b854.png)

We _do_ have an alignment feature right now, but it only works on multiple Clips. If you select two or more clips on the OpenShot Timeline, both of their menus are extended with options to Align > Left or Align > Right. Selecting either will shift all of the Clips' start boundaries to match the earliest one, or all of their end boundaries to match the latest one, respectively.

So, one possibility might be that we could extend the Align feature to _single_ Clips as well, at least for Align Left, and have it shift the clip to `00:00:00` on the Timeline. Things like "Align > Start to Playhead" and "Align > End to Playhead" sound like they'd be handy as well, and should also be workable for both single and multiple selections.

I'm not so sure about the "right click on silence" part of the proposal, because silence isn't (currently) something you can interact with in OpenShot — it's literally the absence of anything to interact with, in fact. And by the same token, you can't really "delete" _nothing_ (in the OpenShot model, anyway).

In Audacity you can select time ranges, even if they contain nothing but silence, and deleting a selected range _can_ shift anything past it left on the timeline. (There's actually a preference that controls that behavior.) 

But OpenShot doesn't handle selection in terms of time ranges. Selections have to involve one or more Clips and/or Transitions. So any features for repositioning elements on the Timeline are much more easily conceived (and coded) in terms of _those_ (currently-selected) elements. That's why I think additional alignment features/modes might be a better approach than trying to make the empty Timeline spaces interactive.

I can't make any promises about availability or timeframe, but would a single-clip "Align" option be a workable solution for you?

**Comment by radeksvarz** [comment]
@ferdnyc "Align" option would make it work. 

Just a food for thoughts - interaction with silence (empty) space also makes sense - in the future you might want to run the generator of video / audio towards that particular time range to fill it in.

**Comment by ferdnyc** [comment]
@radeksvarz A fair point. And in a sense, anytime you add an object to the timeline you're interacting with its empty spaces... it's just that right now, "insert here" is the only type of interaction we have.

Fortunately, a feature of that sort would still qualify as an "insert here" action. And more importantly, would still rely on a timeline object being created/modified, rather than a **non**-object being deleted (which was the real sticking point).
