### ISSUE TITLE
Best way to build for Linux?

### ISSUE THREAD

**Issue by stefan-reich** [OpenShot/openshot-qt#2793]
Hi, I read that the AppImage is possibly not optimal? Please advise, thanks.

**Comment by SuslikV** [comment]
https://github.com/OpenShot/openshot-qt/wiki/How-to-compile-Libopenshot
this is the link to FAQ, where you'll find link to google docs, there you'll find some building instructions.

**Comment by peanutbutterandcrackers** [comment]
@stefan-reich - If you're using Ubuntu (and friends), this might be of much help: https://www.openshot.org/static/files/user-guide/developers.html
If you're using any other distro, please document your process so that others might be able to compile it easily. Hope you'll be making some PRs soon. :)

@SuslikV - Hey there! Thank you for helping out in the forums. You are awesome. :)

**Comment by DylanC** [comment]
Answered.
