### ISSUE TITLE
Positions of snapped clips on Timeline change, when dragging/snapping at different zoom levels

### ISSUE THREAD

**Issue by udippel** [OpenShot/openshot-qt#2808]
#1041 might be related?
I had a very coarse timeline to add clips sequentially. They snapped to the end of the previous one(s) properly. In the end, I noticed that the final clip as rendered was vastly out of sync immediately after the first clip transition. 
I redid the whole lot, with the coarse timeline. Then I zoomed in to a timeline of a few seconds and found a huge overlap of the clips at their transition points. I snapped the clips back to just the respective end of the previous clips, showing no transition in this case, just snapping. The final result was quite in sync. 
Since I did it twice, I dare to report here, that - contrary to what I had assumed - the snapping of clips one after the other depends on the displayed timeline. I for one consider this behaviour wrong. I my opinion the timeline ought to be just a helper for me, and not influence the editing behaviour.

**Comment by SuslikV** [comment]
The problem is in webkit module that used in OpenShot, I think. Because the same _Timeline_ opened in chrome window (for debug) acts without issue and snapping to edges doesn't depend on zoom level of the _Timeline_ (as it happens in OpenShot itself).

Yeah, it's annoying issue, because you need to zoom-in to maximum to align all objects correctly. I don't know other workaround.
And it seems that this behavior wouldn't change any time soon. I tested against Qt 5.12.3  and webkit 5.212.0alpha2, angular 1.7.8 on Windows - and behavior is the same. By the way, it not always happens, the precision and irrational numbers seems to be a key to the issue itself, but I may be wrong, of course.

**Comment by ferdnyc** [comment]
@SuslikV 

> The problem is in webkit module that used in OpenShot, I think. Because the same _Timeline_ opened in chrome window (for debug) acts without issue and snapping to edges doesn't depend on zoom level of the _Timeline_ (as it happens in OpenShot itself).

How can you tell? Snapping positions didn't start changing for me until I'd zoomed OpenShot out to around 480 seconds — the debug interface doesn't zoom out nearly far enough to test that.

I suspect the issue is with the logic that maps screen coordinates to timeline locations (in seconds), which is (necessarily) dependent on zoom level. The GUI will return drop positions in terms of interface pixel coordinates, which OpenShot then uses its current `pixels_per_second` value to translate into a timeline position. When you're zoomed out far enough, that conversion loses precision.

There's also the fact that the "end" location of a clip isn't necessarily the same as the start of the next frame following it, and OpenShot will always try to map clip positions onto frame boundaries. So, there's the potential to introduce imprecision there, too.

Still, it's definitely a bug that snapping is zoom-dependent.

**Comment by ferdnyc** [comment]
When snapping is active, WebKit constrains the drop position of the dragged element to the snapline X coordinate, but AFAIK it still does that in pixel coordinates, meaning the precision is still dependent on the zoom level.

The solution will probably involve some additional logic in the drop processing, where we check whether the drop was performed with a snapline active. If it was, then we override the drop position, ignore the pixel coordinates, and instead just set it equal to the exact timeline position of the other timeline element (the one being snapped to). That should be zoom-proof.

Handling drops where the _end_ of the dragged element was snapped to something may present additional challenges... or maybe not, I have to think on that.

**Comment by ferdnyc** [comment]
This one still really needs to be solved, too.
