### ISSUE TITLE
Autoduck filter for audio

### ISSUE THREAD

**Issue by RafaelLinux** [OpenShot/openshot-qt#2813]
**Describe the new feature:**
I ask about this in reddit, but maybe this is the correct place. I'm surprised with OpenShot. It has features I didn't imagine. The fact of using third party GNU software like blender or inkscape it's a really great idea for users that know how to use that potential. I miss a great feature in all NLE about audio, is the audio "autoduck" functionality.  "Auto Duck"  ‘ducks’ the level of the sound automatically by mixing two audio tracks: A background music and the voice of the narrator.
Take a look to [this video](https://www.youtube.com/watch?v=vNReOdVrWEQ) if you don't know what's is the great audio filter.
Is available in Audacity but I need to do the process OUT of the video editor and incorporate the result to the project. 

**Describe the solution you'd like:**
Use Audacity (as Blender, in background, or even opening Audacity) to use the Autoduck functionallity

**Describe alternatives you have considered:**
Incorporate the code that makes "autoduck" of Audacity in OpenShot.

**Comment by ferdnyc** [comment]
@RafaelLinux I believe at least _similar_ functionality can be achieved in OpenShot, by setting your clips' Volume Mixing property to "Reduce". (The other options are "None" — the default — and "Average".)

If you do give that a try, please let us know whether it's sufficiently equivalent to the requested functionality, or what's lacking that makes it an inadequate substitute.

**Comment by RafaelLinux** [comment]
I tried with "Reduce". I assign it to my video clip and just below the video track I put my audio (mp3) background music. But seems it have no effect. Even more, there is no any kind to control on the way and how the music should decrease its volume. So in my experience, the option you mentioned doesn't works like "autoduck".

**Comment by ferdnyc** [comment]
@RafaelLinux and @zefram-cochrane

I decided to science this. Experiment time! Off to Audacity to create a couple of files:

* A 620Hz sine wave at 0.8 amplitude for 5 minutes
* Pink noise at 0.5 amplitude, for 2 minutes

I exported those both to WAV and loaded them into OpenShot. Then I started experimenting.

What I discovered is that I should've recommended "Average" for at least _one_ of the tracks. (Not very intuitive labels, but that's a side issue.) With two tracks set to "Reduce", as you say there appeared to be no effect. But when I brought "Average" into the mix, things started happening.

The top track in this screenshot is my OpenShot export audio (the structure for which I'll describe in a moment) imported back into Audacity, below it is the raw 620Hz sine wav file for comparison/reference purposes.

![Screenshot from 2019-07-31 21-54-33](https://user-images.githubusercontent.com/538020/62260250-4d736d80-b3df-11e9-906d-7205d2459e8e.png)

The project was set up with the sine wave file playing for the length of the export. Left alone, the upper track would've been identical to the lower one. However, because I set the sine wave clip's Volume Mixing to "Average" and then overlaid other clips, that wasn't the case.

* The yellow-highlighted region is where I overlaid the pink noise clip with _its_ Volume Mixing set to "Average" as well. 
* The green-highlighted area is the same clip again overlaid on top of the sine wave, but this time with its Volume Mixing set to "Reduce".

As you can see, in both cases the volume level for the background sine wave was automatically ducked to make room for the pink noise, in different proportions depending how its own mixing option was set.

Give it a try, I think you'll find it works reasonably well. The effect may not be very adjustable beyond the two options, but it's definitely there and seems at least somewhat serviceable.

Accessibility and discoverability are still concerns, granted.

**Comment by mikelacsa** [comment]
@RafaelLinux is this still an issue if you use the latest daily build?

**Comment by RafaelLinux** [comment]
Sincerely, I only check your workaround on latest week of september, but it doesn't nothing. There was no difference when I experimented with my real audio files (music background and vocal speech). I haven't had time to save and capture the result, that's why I didn't reply, but in my test, it does nothing  :(

**Comment by ferdnyc** [comment]
So, I did some more experimentation, along with reading through the libopenshot source code, and I now have a much better understanding of how the volume mixing selections work.

> but in my test, it does nothing :(

It definitely doesn't do _nothing_, though it's a much more subtle effect than an autoduck, and will often be inaudible except when it's needed. The OpenShot volume mixing is much more geared towards preventing clipping and distortion, vs. altering the mixdown with noticeable volume changes.

Here's what the three Volume Mixing selection mean, for each track they're set on:
* **None** — Does what it says on the tin; the clip audio is played at the chosen volume level, unaltered
* **Reduce** — Blindly reduces the clip's volume to 77% (why 77%? I guess because they had to pick _some_ number), "hoping it will prevent exceeding 100% (but it is very possible it will)". That's a direct quote from the source comments. This mode is very stupid and nobody should ever use it.
* **Average** — Divides the clip's volume by the combined total volume of all playing clips — it literally averages the volume among the clips. So, this can get a bit complicated:
  * If two clips are playing at `1.0` volume and they're both set to `Average`, both clips' volume will be set to `0.5`.
  * If two clips are playing at `1.0` volume and only _one_ is set to `Average`, **that** clip's volume will still be set to `0.5`, but the other clip's volume will remain at `1.0`. So, the total volume for the track will be `1.5`, and clipping could still theoretically occur.
  * If two clips are playing, one at `1.0` and the other at `0.5`...
    * With both set to `Average`, their volume will be `0.667` and `0.333`, respectively — the second clip's volume will _still_ be half of the first clip's (they're reduced proportionally), but their total volume will not exceed `1.0` and no clipping is possible.
    * With only one clip set to `Average`, its volume will be `0.667` or `0.333` (respectively), while the _other_ clip's volume will remain at either `1.0` or `0.5` (respectively). As you can see, in both cases clipping is still _theoretically_ possible (total volume is `1.333` or `1.167`), but it's highly unlikely since the clips would have to simultaneously hold at peak output levels, basically.

Oh, and _neither_ "Reduce" nor "Average" do anything at all unless `max_volume` is over 1.0. That's mean to protect the situation where only one clip is playing audio, but it also means that if you have two clips playing and both are at reduced volume already, they'll effectively auto-disable themselves.

So, that's how that works.

I do think there's room for a fourth mode (or a new third, because "**Reduce**" is stupid and lame and should go away), call it "**Duck**", that attempts to overbalance the audio _away_ from that track when `max_volume` exceeds `1.0`. Or maybe even two new modes, "**Duck**" and "**Goose**", where "Duck" heavily _reduces_ the volume of a track when other tracks are playing, and "Goose" actually _raises_ a track's volume when there is competing audio.

Their formulas could maybe be something like:
```c++
if (source_clip->mixing == VOLUME_MIX_DUCK && max_volume > 1.0) {
    // The volume will be reduced proportional to the count of full-volume tracks (or equivalent)
    volume = volume * ( 0.5 / max_volume );
    // If max_volume is 2.0, the clip's volume will be set to 25% of its original level
    // If max_volume is 3.0, it will be set to 16.67% of its original level
} else if (source_clip->mixing == VOLUME_MIX_GOOSE && max_volume > 1.0) {
    // The volume level will be increased proportionally by 10% of the max_volume
    volume += (volume * (0.1 * max_volume))
    // max_volume = 1.5 : raise 50% clip to 57.5%, raise 100% clip to 115%
    // max_volume = 2.0 : raise 100% clip to 120%, raise 50% clip to 60%
    // max_volume = 2.5 : raise 50% clip to 62.5%, raise 100% clip to 125%
    // max_volume = 3.0 : raise 100% clip to 130%
}
```

The "duck" reductions, especially, might be a bit severe. The effects would have to be tested after implementation, and values tweaked as needed.

**Comment by ferdnyc** [comment]
Keep in mind when reading all those numbers, also, that OpenShot's volume levels (like most audio-processing software) are logarithmic in scale — starting at "100%" (full) volume, a reduction to "50%" is actually barely noticeable, whereas the drop to 25% is at least twice as severe, and "15%" is quickly approaching "barely audible" territory.

**Comment by RafaelLinux** [comment]
That way doesn't works exactly as "autoduck". It's a pity OpenShot can't implement autoduck Audacity code. I though it could be easy to migrate algorithm.

**Comment by RafaelLinux** [comment]
Well, that filter is not implemented. Maybe this should be a Feature Request
