### ISSUE TITLE
No audio when using Bluetooth Audio Devices

### ISSUE THREAD

**Issue by Bagonzo** [OpenShot/openshot-qt#2820]
**Preamble:**
The bug has similar characteristics to ones that were already reported but I did not see this issue reported on the latest Daily Build (2.4.4-dev2)

**Bug:**
There is no audio output when playing though an external audio peripheral. But, if the audio device is connected before launching the application, an error message pops up on opening the application.

**Steps to reproduce the behavior:**
1. Connect your external Bluetooth audio device (before opening the application)
2. Open OpenShot Video Editor

**Expected behavior:**
A pop-up appears with an error message saying that the input and output devices don't share a common sampling rate, and also asks the user to fix it. (WTF)

**System Details:**
- OpenShot Version: 2..4.4-dev2
- Operating System / Distro: Windows 10

**Screenshot:**
![Screenshot (14)](https://user-images.githubusercontent.com/49718181/58758106-1e05c900-8534-11e9-812f-91f3b3234362.png)

**Comment by SuslikV** [comment]
The bluetooth devices all different. One can use input and output simultaneously - other not.

General audio settings in Windows is under the speaker's icon right-click menu _Playback Devices > (Device Name) > Properties > Advanced tab > Default Format_ section. (same path for recording devices).

**Comment by ferdnyc** [comment]
Yeah, this was something @jonoomph had to add in the libopenshot-audio upgrade to JUCE 5, because prior to that message being added, there was no indication at all why audio wouldn't work sometimes — it just wouldn't work, because (for reasons that make no sense to **_us_**, either, trust me) JUCE can't open an audio device for output if the input is configured with a different sample rate. Even though we're explicitly requesting 0 input channels!

As @SuslikV says, the sample rate settings are in the Windows control panel. Because we don't handle input devices at all, it's not something we could easily fix on the user's behalf. The best recourse for the moment appears to be displaying that message, though I suppose we could try to give the user more information on _how_ to fix the issue.

**Comment by ferdnyc** [comment]
@Bagonzo : Out of curiosity, is that a screenshot of your _entire_ screen? It looks like you might be getting hit by the DPI scaling bug, if so, because the interface is HUUUUUUUGE!

**Comment by SuslikV** [comment]
@ferdnyc dpi scaling is not a bug. Whole application is designed to work with only standard monitor as it was in 90-s.

**Comment by ferdnyc** [comment]
@SuslikV 

Correct DPI scaling is a feature. The DPI scaling _bug_ occurs in some Qt applications (OpenShot being only one among them), usually due to misdetected screen dimensions on the host system. The lack of accurate size information causes Qt to scale the application interface up to comical sizes appropriate for a phone-sized HiDPI device, instead of a standard ~HD-resolution desktop/laptop screen it's actually rendering to.
