### ISSUE TITLE
Question: merging/joining audio and video track in a single "virtual" clip (opposite of Separate Audio)?

### ISSUE THREAD

**Issue by sdaau** [OpenShot/openshot-qt#2830]
**Question:**
Let's say, I have a video-only clip, and an audio only-clip. Typically, if I want to sync them, I have to use one track for each clip - that is, one track for the video, and one for the audio (which is also the arrangement if you have a video-merged-with-audio clip, and then you click Separate Audio - except with Separate Audio, you at first get clips overlaying each other on a single track, and then you need to move those clips manually in individual tracks):

![openshot-av](https://user-images.githubusercontent.com/26737749/59160140-0b126c00-8ad3-11e9-9c50-843f4458933a.png)

Then, I can reposition the audio clip (that is, move it left/right), until the audio is synced up with the video. So far, so good.

However, if after this, I'd like to cut up the "joined" video and audio clips - then I have to choose Razor Tool, then click once on the video clip to cut it, then click once more on the audio clip to cut it, then also click on each clip if I want to delete them etc.

What would be far easier in this case, is to declare the video-only track and the audio-only track as a "virtual" "joined" or "merged" video&audio clip, so that I get only single track used in the GUI, in which I'd need to click only once in the clip, so I simultaneously "razor cut" both the audio and the video clip at the same time position.

Of course, I could basically render a video-and-audio output once the audio-only and video-only clips have been synced, and then conveniently cut this rendered version - but then I'll obviously experience loss of quality, since whatever video compression I use, will be applied twice (once to generate the "merged" clip, and once more in the final export of the cut-up "merged" clip).

Is there, possibly, a feature like this in OpenShot already?

**System Details:**
- OpenShot Version: `OpenShot-v2.4.4-x86_64.AppImage`
- Operating System / Distro: Ubuntu 18.04

**Comment by SuslikV** [comment]
Group sources clips (or link them) isn't implemented yet, As far as show/hide from rendering any _Track_.

**Comment by ferdnyc** [comment]
@sdaau 

Although right now grouping of tracks is not a feature, there are a couple of optimizations that make the process you describe significantly easier:

1. Instead of using the Razor Tool, position the Playhead at the point you want to cut, then choose "Slice > Keep Left Side" or "Slice > Keep Right Side" from the clip's menu, to save the extra step of deleting the side you don't want.
2. For Cutting _multiple_ tracks in alignment, if you select all of the tracks you want to cut, then right-click _**on the Playhead "handle" itself**_, you'll find a single menu option: "Slice All", with the same "Keep Left Side" and "Keep Right Side" options. That'll perform the equivalent of a Razor Tool operation on _every_ selected track that the Playhead is currently positioned over.
