### ISSUE TITLE
Openshot audio not in sync issue

### ISSUE THREAD

**Issue by JustaKing4** [OpenShot/openshot-qt#2838]
I have windows 10. I'm trying to export an edited video which i added audio and video to, but each time i export it, the audio is out of sync. I checked the FPS and other info and it matched the original video and i tried several players to make sure that wasnt the problem. I have edited several other videos the exact same way without having this problem.  Does anyone have any ideas how to fix this? If you need more info, just let me know. Thanks for any help with this.

**Comment by SuslikV** [comment]
It should be linked here, I think: https://github.com/OpenShot/openshot-qt/issues/1290

Also, please, can you confirm that the behavior of the desync is the same to the (you may try the sample file linked in the thread too): https://github.com/OpenShot/openshot-qt/issues/2828#issuecomment-500698612 ? It is important info because it is not clear what kind of desync you experience.

**Comment by JustaKing4** [comment]
#2828 seems to be the same as my problem, yes. Sound is happening a few seconds after it is supposed to be. I have also read the #1290  post and seems like the same issue, but I have not been able to fix it on my end yet.... a lot of the talk is pretty technical and some of it I don't understand completely. really would like to understand and fix it though.

**Comment by SuslikV** [comment]
@JustaKing4 the `nonetype object has no attribute get` error is different issue and it is not related to the desync, I think. Do you got this error just from start of the application, and not by opening OpenShot's project files?

**Comment by JustaKing4** [comment]
Yes, everytime i start the application. I did not move the orginal project files at all. 

⁣Get BlueMail for Android ​

**Comment by SuslikV** [comment]
I think, OpenShot's log-files may help a bit. Can you post at least _openshot-qt.log_?

**Comment by JustaKing4** [comment]
Ok, i will trt to find it

⁣Get BlueMail for Android ​

**Comment by DylanC** [comment]
@JustaKing4 - Did you manage to find the logs?

**Comment by mikelacsa** [comment]
@JustaKing4 to guide you with getting the logs, please follow the instructions from this link:

https://www.openshot.org/issues/new/

**Comment by JustaKing4** [comment]
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/3703134/libopenshot.log)


i have already stated that I redid the entire project and would most likely not be using openshot any further, since this is keeps happening. I will, however, still post those logs if it can help anyone else experiencing the same issues. I have tried posting the openshotqtlog files in different formats but the page will not allow me to attach or drag and drop it at all. Says file not supported, even though it should be a txt file..

**Comment by ferdnyc** [comment]
> I have tried posting the openshotqtlog files in different formats but the page will not allow me to attach or drag and drop it at all. Says file not supported, even though it should be a txt file..

Yeah, sorry, GitHub can be weird about those things sometimes. There must be characters in your log that cause it to be identified as something other than plaintext, which can happen. Unfortunately, `libopenshot.log` contains no information that's of any use regarding this bug. (I'm not sure `openshot-qt.log` will, either, but there's more of a chance.)

The surest thing you can do to ensure that GitHub will accept files is place them inside a zip file, then attach / drag _that_ to a comment — GitHub will always accept zip attachments, as long as they're under... I forget if it's 2 MB or 10MB in size, either way it's more than enough for posting logs.

**Comment by ferdnyc** [comment]
Even more useful than logs, really (as I said, I'm doubtful there will be anything at all of use there) would be a set of sample files to reproduce the problem: A source video file, a project file, and the settings used in the export dialog that result in an out-of-sync export.

The sample input file can be small, it only needs to be a few seconds long (preferably, in fact), just enough to confirm the problem. But because of GitHub's size limits, that'd probably still have to be shared from cloud storage (Dropbox / Google Drive / etc.) or uploaded to a file-sharing service like MegaDrive or Hightail (formerly YouSendIt).

**Comment by ferdnyc** [comment]
> Also, if i look at the videos that i added info, it say 29.20 framerate. There is no option to export at that framerate?

Most likely that means the input video framerate is 29.97, but there's a time adjustment somewhere that causes it to average out differently. That may very well be the source of the sync problems.

Exporting at 29.20 fps wouldn't fix the sync issues, and would just create a file with a weird framerate that would probably break lots of other things. Plus, like I said, it's not the **real** framerate anyway, it's just the average across the file — meaning there's a chunk of weirdly-timed data (right at the beginning of the file, probably), followed by a normal 29.97 fps video.

A lot of real-time recording devices (cameras, stream recorders, etc.) capture their video and audio inputs out of sync, and they deal with it in different ways. The _really_ good ones do the work of syncing up the streams before encoding, and still generate a correctly-synchronized output file. Others know the data will be out-of-sync, so they insert the appropriate metadata into the output file that says, "delay audio by XXX milliseconds" or "shift audio forward by YYY ms" or whatever. (It's usually the audio that gets adjusted relative to the video.) Players are able to pick up on those notations and make the necessary adjustments.

And then there are other devices, and whatever created your source files most likely falls into this category, that aren't as well-behaved. Instead of providing the necessary information to properly sync up the files they output, they just leave weird gaps at the beginning of the file that _happen_ to have the effect of syncing up the contents. But correct sync is almost a _side-effect_, really, and that's where trouble starts because it's often **only** possible play the file in sync if you start at the beginning. Obviously that can be a problem for editing. (But the same issue can show up in video players too, where the file plays fine if you start it from the beginning, but when you try to start playing from the middle it'll be out of sync. Sometimes even just skipping forward or backwards during playback will cause it to lose sync.)

You mentioned in #1290 that the sync issues didn't occur when exporting to MOV, which makes me even more convinced about the nature of these sync issues because MOV files are _notorious_ for causing all kinds of sync issues in various players. The format supports lots of weird timing that wouldn't be legal in other types of media file, and OpenShot probably just reproduces that when encoding to MOV, but isn't making the necessary conversions properly when it encodes to some other format.

**Comment by JustaKing4** [comment]
so how would i fix that sync issue? if its the fault of the recording device...just get a better device...?  and i apologize to all for the long time responding..i got wrapped up in something else. I found out that the audio, as i think you mentioned was messing with the sync, so i messed with it, but never got it to work all the way to perfection. Also i now have a new problem..... I know, i keep saying i wont use openshot anymore but it actually is a good program and i know it well now, so its convenient to use.... but so frustrating with these errors.... now i encountered the nontype error just like last time after a crash with OpenShot, but it will not allow me to export the file to anything. it just sits at 0% and never moves.  if i look at task manager it says it is using 0% of the memory so i assume it is freezing but i can still cancel it and close it or continue working after that. I can send someone a file if need be, but i need exact instructions on the files you need and whatnot, because last time i was told to get some files that didnt seem to be there...or maybe i just dont know what i'm doing, which is most likely the case.

**Comment by JustaKing4** [comment]
is there a folder that saves the recent project data? when the program crashes it can be recovered even though I never saved it, so I'm assuming it is saved somewhere, but I cannot find the folder to relaunch it because the last time it crashed and I reopned it, it did not automatically reload and recover the last project. how can i manually force it to do this?

**Comment by SuslikV** [comment]
@JustaKing4 The backup handling was changed in recent versions of OpenShot (look for all `.osp` files on your PC). Some sync issues were fixed in most recent build of OpenShot, just try to update your version to most recent one.

The error in export you mentioned is just because you run out of memory (RAM) - the solution is to simplify the project if it is too complex for your PC.

**Comment by JustaKing4** [comment]
Thanks, that helped a lot. I was able to recover it and finish the project *thumbs up*

**Comment by SuslikV** [comment]
> ...but after i updated it there was no problem.

then the version you are used was way too old. OpenShot has daily builds for test purposes: https://www.openshot.org/download/#daily

**Comment by internationils** [comment]
Hello, I have the same issue with OpenShot version 2.5.1-dev2 (under Ubuntu Focal).
I have a video mp4 (capture from Logitech Brio) and an audio mp3 from different sources, sync them perfectly in OS, but when exporting to an mp4 the sound is off by close to a second. I'm happy to experiment and to help debug this. Please let me know if you would like me to open a new issue instead of continuing this thread.

**Comment by JustaKing4** [comment]
> Hello, I have the same issue with OpenShot version 2.5.1-dev2 (under Ubuntu Focal).
> I have a video mp4 (without audio, capture from Logitech Brio) and an audio mp3 from different sources, sync them perfectly in OS, but when exporting to an mp4 the sound is off by close to a second. I'm happy to experiment and to help debug this. I've opened a new issue to not mix it with this one.

Dont know if your issue is the same but i found that if i changed the audio output numbers before exporting, it fixed my issue.  Try to get it as close to the same number as the source material you used. My project has multiple sources with different outputs so it really messed with it.

**Comment by internationils** [comment]
@JustaKing4 what audio numbers do you mean? In the advanced settings on the export windows?

**Comment by JustaKing4** [comment]
> @JustaKing4 what audio numbers do you mean? In the advanced settings on the export windows?

Yep.

**Comment by internationils** [comment]
Thanks, will try. The weird thing is that it even _starts_ out of sync immediately, even though in the OS playback it is completely in sync (and drifts off a tiny bit over the 30 minutes)...

**Comment by JustaKing4** [comment]
> Thanks, will try. The weird thing is that it even _starts_ out of sync immediately, even though in the OS playback it is completely in sync (and drifts off a tiny bit over the 30 minutes)...

Yes, same thing happened to me. I tried many different formats and different audio, resolutions, etc. They all came out with different results but all were messed up in some way. Best result i could find was matching up most of the info to the majority of the source material or as close as i could get to a median number for the audio.
