### ISSUE TITLE
Desync between time freezes in software and exported video

### ISSUE THREAD

**Issue by Balthier64** [OpenShot/openshot-qt#2840]
Hello, 

I'm experiencing a video desync between the video preview in Openshot and the final video in VLC.

To be more accurate, I have cut my video into 49 parts, and for each part I froze the end of the clip for 2 seconds, and added a 2-second title on each frozen picture - in order to display the names of the 49 people appearing in the video with a 2-second freeze on each person.

That video clip was supposed to be the ending credits of a 35-minute video ; the rest of the video is perfectly sync.

The problem is that when I export the whole video in 30 fps, the rest of the video is perfectly sync, but this part is delayed by 1 second. That means that both the freezes and the titles are delayed by - it seems - 1 second exactly. I've tried editting this ending video alone on a separate file, but the same issue when exporting still occurs.

Would you have a solution for me please? Thanks in advance !

**Comment by SuslikV** [comment]
Audio delayed from the video, you mean? Zoom _Timeline_ to maximum and look if your files aligned well.

**Comment by Balthier64** [comment]
The audio is sync with the video, no problem with audio. I have zoomed to maximum, and in Openshot, the 2-second freezes correspond perfectly to the 2-second titles on them. But when exporting, the freezes and titles are delayed 1 second later in the video...

Le 19 juin 2019 à 11:15, SuslikV <notifications@github.com<mailto:notifications@github.com>> a écrit :


Audio delayed from the video, you mean? Zoom Timeline to maximum and look if your files aligned well.

**Comment by SuslikV** [comment]
Please, make screenshot of the _Timeline_ area when the clip that is has 2-sec freezes is selected (red borders) and at least one title clip is visible.

**Comment by Balthier64** [comment]
[image1.jpeg]

Le 23 juin 2019 à 07:19, SuslikV <notifications@github.com<mailto:notifications@github.com>> a écrit :


Please, make screenshot of the Timeline area when the clip that is has 2-sec freezes is selected (red borders) and at least one title clip is visible.

**Comment by SuslikV** [comment]
Please, check if image is available for view/download (you can use google-drive links or similar services if image is too big)

**Comment by Balthier64** [comment]
https://ibb.co/xG5c1kW

**Comment by SuslikV** [comment]
Hmm, I cannot reproduce the issue. If the clip plays in the _Preview_ well - it exported into video in the same way. What is your output format, settings? I exported to MP4 with `18 crf` to _Bit Rate/Quality_ , there is no issues.

What happens if you:
1) add single video file to OpenShots's Timeline;
2) place the timeline cursor at any position inside the clip;
3) right-clip over the clip and chose: _Slice>Keep Left Side_;
4) right-clip over the clip and chose: _Time>Freeze>2 seconds_;
5) click main menu _Edit>Preferences_;
6) set _General tab>Image Length (seconds)_ to 2 and hit Enter button on keyboard;
6) click main menu _Title>Title_;
7) choose template named _Bar 3_ and click _Save_ to close the titles window;
8) drag-n-drop new title file from the _Project Files_ list of OpenShot into _Timeline_ next to the timeline cursor position, one track above the clip (title should snap to the right edge of cursor or to the cut point of the clip);
9) place the timeline cursor at any position inside the clip (left to the previous position);
10) click on the clip (make only it selected);
11) right-clip over the clip and chose: _Slice>Keep Both Sides_;
12) click and hold left mouse button to make rectangle selection of the right clip and title clip (yellow color while selecting) and move the both clip+title to the right about 10 seconds or more;
13) click on the clip that lies left to the timeline cursor (make only it selected);
14) right-clip over the clip and chose: _Time>Freeze>2 seconds_;
15) click main menu _Title>Title_;
16) choose template named _Bar 3_ and click _Save_ to close the titles window;
17) drag-n-drop new title file from the _Project Files_ list of OpenShot into _Timeline_ next to the timeline cursor position, one track above the clip (title should snap to the right edge of cursor or to the cut point of the clip);
18) same as in p.12 move both clip and title on the right to the clip that is on the left (start of the second clip should snap to first one);
19) click Ctrl+E (export menu should open)
20) choose _Target_: MP4 (h.264), _Advanced tab>Video Settings>Bit Rate/ Quality_ type `18 crf` instead of default bitrate.
21) click _Export_ button and when task finished - playback the exported file.

Are the titles in sync with the frozen frames?

**Comment by mikelacsa** [comment]
@Balthier64 are you still having this problem?

**Comment by Balthier64** [comment]
Haven't tried for a while, but last time I tried, I still had it...

Le 1 oct. 2019 à 20:53, mikelacsa <notifications@github.com<mailto:notifications@github.com>> a écrit :


@Balthier64<https://github.com/Balthier64> are you still having this problem?

**Comment by mikelacsa** [comment]
I see. Thanks @Balthier64. Did you try it with the latest version/daily build?

**Comment by mikelacsa** [comment]
No response 7 days after being labeled "needs info". Closing the issue.
