### ISSUE TITLE
Crashes when exporting

### ISSUE THREAD

**Issue by ZechnasMaou** [OpenShot/openshot-qt#2842]
**Describe the bug:**
I tried to export the project I need (which is 3 minutes and 4 seconds long with audio) thrice and it crashed at 24.0% everytime and the mp4 files that were created won't play and pops up a message.
I also tried to export the same video but without audio and it still crashes at 24.0%

I tried exporting an audioless 31 second project and it exported successfully. I also tried exporting the same 31 second project but with audio and it exported successfully as well. It also exports successfully when I tried a minute long video.

**Steps to reproduce the behavior:**
1. Open or make a 3 minute video.
2. Export the video.
3. The video crashes somewhere in the middle.

**Expected behavior:**
Export is successful and the resulting mp4 file is working as it should.

**System Details:**
- OpenShot Version 2.4.4
- Windows 10

**Log Files:**
There are no .log files in the .openshot_qt folder.

**Screenshots:**
![Screenshot (95)](https://user-images.githubusercontent.com/52270308/60242977-cb78bc00-98e9-11e9-9a4a-ef44c08d90c6.png)
![Screenshot (96)](https://user-images.githubusercontent.com/52270308/60243179-33c79d80-98ea-11e9-9927-49e407e28056.png)

**Comment by ZechnasMaou** [comment]
I tried to export it again and it crashed at 24.0% once more.

**Comment by SuslikV** [comment]
Probably, your issue was already solved (if it was caused by abnormally high RAM consumption), but you need to try one of the _daily builds_ of the OpenShot (https://www.openshot.org/download/). If it fails to start, try at least, this old automation build of the OpenShot (7zip archive, JUST FOR TEST! Unpack it to different folder, despite the file name says 2.1.0 it is only last available tag from the branch I used to compile the application) - https://ci.appveyor.com/project/SuslikV/openshot-qt/builds/25124962/artifacts

**Comment by mikelacsa** [comment]
@ZechnasMaou have you tried the latest daily build?

**Comment by mikelacsa** [comment]
No response 7 days after being labeled "needs info". Closing the issue.
