### ISSUE TITLE
Title text is outlined

### ISSUE THREAD

**Issue by danielrcollins1** [OpenShot/openshot-qt#2843]
**Describe the bug**
Title text is outlined

**Steps to reproduce the behavior:**
1. Create a title, e.g., "Standard 1"
2. Note that text is outlined.

**Expected behavior**
Text should not be outlined.

**System Details**
- OpenShot Version: 2.4.4
- libopenshot Version:  0.2.3
- Platform: Windows-7-6.1.7601-SP1
- Processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
- Machine: AMD64
- Python version: 3.6.4
- Qt5 version: 5.9.1
- PyQt5 version: 5.9
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.4.4-dev2-1561536327-a8d545ea-9b278998-x86_64.exe

**Log Files**
- http://logs.openshot.org/dwaerdbudok1o0we1oktmjbe4ubczypu/openshot-qt.zip
- http://logs.openshot.org/dwaerdbudok1o0we1oktmjbe4ubczypu/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.
 
Standard 1 title text appearance in v.2.4.3:
![StandardTitle-2 4 3](https://user-images.githubusercontent.com/36377602/60369232-ed913d80-99c0-11e9-9b75-46d93efab9b1.png)

Standard 1 title text appearance in v.2.4.4:
![StandardTitle-2 4 4](https://user-images.githubusercontent.com/36377602/60369235-f08c2e00-99c0-11e9-9b7e-f86e93dc1316.png)

**Comment by ferdnyc** [comment]
@danielrcollins1 

Believe it or not, the text was _always_ outlined — you just couldn't see it properly before.

The change from 2.4.3 to 2.4.4 was the replacement of the SVG renderer being used in OpenShot. 2.4.3 and below used Qt's built-in QtSVG, which is a very feature-limited implementation of SVG that was only ever intended for rendering simple things like icons and user interface decorations.

The Standard 1 title template in 2.4.4 (_all_ of the title templates, actually) is identical to the 2.4.3 version, and it was always **supposed** to look like it does in 2.4.4. It was just never displayed properly before, because QtSVG didn't support all of the stylistic features used on the fonts in the title templates. You're seeing it correctly for the first time.

If you want non-outlined text, I'd suggest using a template like Gold 1, 2, 3, etc. (You can customize the text color to whatever you like.)

(Your report does  call attention to an issue that needs to be addressed with 2.4.4, though: We need to re-generate the title template preview images, since they're still showing old, incorrectly-rendered 2.4.3-style previews of the templates, which are no longer accurate representations.)

**Comment by SuslikV** [comment]
@ferdnyc ReSVG has its own disadvantages. Can you check if the https://github.com/OpenShot/openshot-qt/issues/2809 affects you too (and caused by ReSVG library)?

**Comment by danielrcollins1** [comment]
@ferdnyc 

Well, that's pretty confusing, because when I load a template such as Standard 1 into the InkScape advanced editor, there is also no outline shown there, either. 

Unfortunately I had a format for a video series I was making using a particular font, for which the Gold template format is simply too small to render properly. If I had any recommendation, it would be to change or make very simple "Standard" templates without the outlining.

**Comment by ferdnyc** [comment]
@danielrcollins1 
> Well, that's pretty confusing, because when I load a template such as Standard 1 into the InkScape advanced editor, there is also no outline shown there, either.

Actually, there is.

The problem is, Inkscape by default loads SVG files in against a white background. But if you go into File > Document Properties...,  and enable Background: Checkerboard background, Standard_1 turns into this:

![image](https://user-images.githubusercontent.com/538020/60839097-584d3080-a19a-11e9-89eb-004211937b22.png)

Anyway, I've started PR #2855 to remove the outlines from some of the title templates that people are used to seeing rendered _without_ outlines, so that things continue to look the way users are used to.

**Comment by mikelacsa** [comment]
@danielrcollins1 is this still an issue after you installed the latest daily build?

**Comment by ferdnyc** [comment]
There is no difference in the current builds vs. this report, as #2855 is still open.

**Comment by danielrcollins1** [comment]
> 
> 
> @danielrcollins1 is this still an issue after you installed the latest daily build?

@mikelacsa Still same issue (white border around text, e.g. in Standard 1 title) with daily build OpenShot-v2.4.4-dev2-1570002441-b7c96ffe-f17a7ed4-x86_64.exe (64-bit), Oct. 1, 2019, 9:51 p.m.

**Comment by jonoomph** [comment]
Maybe it's just me, but I like the outlines. :grimacing: As mentioned previously, they were always intended to be there... even though they were not being correctly rendered in older versions of OpenShot. I'm a bit conflicted on this one.

**Comment by jonoomph** [comment]
Okay, here is what I've decided to do (so far). I've merged @ferdnyc PR, which removes many of the strokes, so we are consistent with older versions of OpenShot (and Inkscape will be consistent with how OpenShot displays them). I've also modified a few more of the titles, where readability or contrast was too lacking, and tried to carefully add back in a few outlines/strokes (but with much less emphasis). I think it's a good compromise, and all of the titles have improved readability... I believe. 

If there are still titles which don't look readable or need changes, lets open up a different issue for them. Thanks again!
