### ISSUE TITLE
Exported Video Almost 5 Times Larger Than Original After Just Muting PART of the Audio, and the Audio Didn't Even Mute! Now the OSP File Won't Open!

### ISSUE THREAD

**Issue by Bananasaurus** [OpenShot/openshot-qt#2866]
**Question:**
 It took me 24 hours to export a 3 hour video in which all I did was mute parts of the audio where a copywritten song was. But the original video is 3.87 GB while the exported video is 18.8 GB. The resolution and FPS are both the same - 1080p, 60 FPS. It's MP4.

What happened? Is this a bug or something can can be fixed in future versions?
Anything I can do to make the video file size smaller? 

**Describe the bug:**
- Openshot DIDN'T Mute the Audio: The exported video doesn't have the audio muted in the part I wanted (or at all).
- It showed up as muted in the project file before I closed Openshot, but not the finished/exported video.
- I was unable to even save the OSP files in the Video folder for some reason, so I saved them in Downloads and then moved them to Videos.
- Now when I try to open Openshot, and then open the OSP file project from the file, Openshot says it doesn't exist. Opening it from "Recent Projects" doesn't have the keyframes where the audio should be muted.
- Moving the OSP to the Downloads folder, I'm able to open the file but audio seems to be randomly missing/choppy in weird areas.

**Steps to reproduce the behavior:**
1. Unknown, other than exporting the video yourself.

**Expected behavior:**
1. A slightly larger (not FIVE TIMES) file size
2. Actually muting the audio as it did in the preview/project. 
3. Before closing Openshot, the audio was muted and I saved the project as an OSP file. Now when I try to open the project from the file, Openshot says it doesn't exist. Opening it from "Recent Projects" doesn't have the keyframes where the audio should be muted.
4. Opening via Recent Projects or from Downloads says the video is 720p, 30FPS, when it's not. It's 1080p, 60 FPS. 
![image](https://user-images.githubusercontent.com/51284286/61177315-f32d7c80-a597-11e9-98b9-289245f71cea.png)
![image](https://user-images.githubusercontent.com/51284286/61177347-bada6e00-a598-11e9-88bc-f64aec1f8e66.png)

**System Details:**
- **OpenShot Version:** 2.4.4
- **Operating System / Distro:** Windows 10, version 1803

**Comment by ferdnyc** [comment]
@Bananasaurus OK, there are a few things going on here, I'll try to tackle at least some of them one-by-one:

> But the original video is 3.87 GB while the exported video is 18.8 GB. The resolution and FPS are both the same - 1080p, 60 FPS. It's MP4.
> 
> What happened? Is this a bug or something can can be fixed in future versions?
> Anything I can do to make the video file size smaller?

The resolution and frame rate may be the same, but the bitrate is not.

OpenShot has three Quality modes for export: Low, Medium, and High. The bitrate of the original video is not taken into account (because it could differ greatly, for projects with multiple clips.) The default when manually setting Export parameters is High, and for MP4 profiles that's 15Mb/s... which is _**high**_ (as you discovered), but yields the maximum possible quality. 

It's actually possible to export at any bitrate you please by typing it into 'Video Settings > Bit Rate / Quality" in the Advanced tab of the Export dialog. But if you don't go that route, you'll want to use Medium, which is 5 Mb/s — higher than your original video (3.1 Mb/s) but not excessively so.

Adding more user-friendly control over things like bitrate settings is definitely on our wish list.

> * Openshot DIDN'T Mute the Audio: The exported video doesn't have the audio muted in the part I wanted (or at all).
> * It showed up as muted in the project file before I closed Openshot, but not the finished/exported video.

I don't know what to tell you about that. I would expect that anything done in the project would be reflected in the export. The fact that you had trouble saving the project, and then didn't see the muting in the project when you reopened it, makes me think that the keyframes weren't there when the export was done, either, but I really have no explanation for how that would've happened.

> I was unable to even save the OSP files in the Video folder for some reason, so I saved them in Downloads and then moved them to Videos.

Without more info on what prevented you from saving the file in your Video folder, I can't even really guess about why that might have happened. You should be able to save OpenShot project files anywhere on disk, as long as you have write permission to the folder. What happened when you tried to save to the Video folder?

As you discovered, right now moving OpenShot project files on disk after saving them is generally not a good idea, because they store the location of any media files used _relative_ to the save location. Which means if you move the project file, you need to move the other files as well, and they need to be in the same relative location. Personally I don't like that setup, and feel there are better approaches, but I've lost that argument. It's usually best to keep a project file and all the media it uses together in the same folder, or even to create one for each project so you can keep everything in there. You'd want to move the media files to the project folder _before_ importing them, and import from that folder only, so that the location will be stored correctly.

> Before closing Openshot, the audio was muted and I saved the project as an OSP file. Now when I try to open the project from the file, Openshot says it doesn't exist. Opening it from "Recent Projects" doesn't have the keyframes where the audio should be muted.

If opening a project from "Recent Projects" gives you something _different_ than opening one via a different method, then you have more than one project file saved. The opening process is exactly the same no matter how it's done. My guess would be that the project file listed in "Recent Projects" is one that doesn't have the audio keyframes (and maybe is the one that the export was done from) 

> 4. Opening via Recent Projects or from Downloads says the video is 720p, 30FPS, when it's not. It's 1080p, 60 FPS.

Ah, I see the confusion there. There's... well, in some ways there's a simple explanation for that, in other ways I don't know what to make of it.

When you're working in OpenShot, the Timeline for your project is set up using a Profile that defines the default video parameters for the project output. You can set your overall default profile in the Preferences ("General" tab), but for new users it's set to HD 720p @ 30 fps. New projects are created with the user's default profile, but it can be changed for each project. (The filmstrip icon on the toolbar, between Import Files and Fullscreen, lets you set the current project profile.) Whatever profile is currently selected for the project is shown in the titlebar of the OpenShot application, as a reminder of the current settings.

Your project was set up using the default 720p profile, it sounds like, and I assume the name of the project file was "may 31st 2019 stream"? That's why you see this in the label for the audio stream:

> may 31st 2019 stream [HD 720p 30 fps] - OpenShot Video Editor

That's just the application title, the same thing you'd see in the titlebar of the application when you have your project loaded.

But what I don't have an explanation for is why that label would be showing on what I assume is your _original_ video file, the 1920x1080 @ 60fps video with the 3.1 Mb/s bitrate, since presumably that file wasn't created by OpenShot.

Regardless, if the file you exported was also 1920x1080 @ 60fps, then I assume when you went into the Export window you selected 1080p HD for the output resolution and 60fps for the frame rate, which is why the export would've been done using those settings. _But_ that doesn't change the project profile, so that's why you still see "[HD 720p 30 fps]" in the label. When you open any of the project files, I'm sure it'll show the same thing in the window title.

We usually recommend working on projects using the same profile that's intended for the final export, since certain assumptions that get built into the project data are based on that profile — most especially, the frame rate, since keyframes are set at frame intervals using the current project rate. 

The fact that the frame rate was different between your project data and your export format _may_ be the reason why the audio muting was lost, it's possible exporting at a **higher** fps than the project data caused the keyframe data to be incorrectly translated to the higher frame rate. Without more information it's hard to say for certain, but that's one possibility.

> Moving the OSP to the Downloads folder, I'm able to open the file but audio seems to be randomly missing/choppy in weird areas.

OpenShot doesn't store any media data in the project file itself. (It works from your original files and needs to be able to access them anytime you're working on a project, which is why the location of the project file is so critical.) It also doesn't change your original files in any way, ever. The only files it ever modifies are the project files, any inputs you create (things like title images or animated title sequences), and then the final project output videos you export.

So, if you're having issues with preview playback from a project that was fine before, it's most likely just an issue with OpenShot's application resources being fragmented or occupied by old data. I'd suggest completely closing out OpenShot, as well as any other programs that may be running and consuming a lot of memory or CPU, or even better restarting the computer, and then loading up the project again. That usually improves OpenShot's responsiveness considerably.

You should also make sure that you have plenty of free space on the drive where OpenShot's working directory is stored (it's in your user home directory), especially after saving a nearly 20GB video file!

**Comment by SuslikV** [comment]
Summarizing the info posted above:
1) In _Export Video>Advanced tab>Video Settings>Bit Rate/Quality_ field type `18 crf` instead of `15.00 Mb/s` (or whats ever) for lower size and same quality.
2) Set _Export Video>Advanced tab>Profile_ to value same to your current project (look at the application's header - there is name of the current profile in the square brackets next to the project's name).
3) Make unique folder for each of your projects and store the project's files in it.
4) See p2.

**Comment by Bananasaurus** [comment]
Ok, I'm gonna test a some of these out, @ferdnyc - give me a bit, though, because I'm recovering from surgery and already encountering issues. So far I've figured out that Windows Defender blocks saving, editing, or usage in protected folders, including Pictures, Videos, Dekstop, and Documents. On top of that, I was unable to add Openshot to my trusted programs because my anti-virus, Bitdefender, blocks access to even doing THAT. I had to find tutorials on how to add Openshot to the trusted programs, so that finally allowed me to save projects in Videos.

However, upon attempting to move the projects, I clicked on the project file when the dialog box opened, yet Openshot then stated the file didn't exist and it vanished from the File Explorer while within the dialog box... only for me to go outside of Openshot to double-check it was still there, and yep, it was.

So, I tried moving the ORIGINAL video into the folder i wanted to save projects in, and did not move any file/folder that was created upon saving the OSP or exporting a short sample clip used to experiment with this. The files created by exporting was a folder titled "thumbnail" and I kept it there. Re-opening the OSP after closing Openshot, the keyframes themselves were gone but the areas where I muted the audio was still muted.

- **A)** Moving project files (OSP) should not make an issue where Openshot is able to see the file, then clicking on it makes Openshot say it doesn't exist, then Openshot makes them "disappear" from within the file explorer only within the program despite it still being there when I went to the folder outside of Openshot. The only file CREATED when saving an OSP file is the file itself, it makes ZERO sense that I am forced to not only keep the file in place, but to keep the original source material in the same folder as well.

- **B)** Why even allow us to save a file anywhere else, other than the source file's location, if that's the case?

- **C)** Key frames should still show up and be editable upon re-opening a project file. What is the point of saving a project file if we're unable to edit it? It's as if we exported it and are working on a source file. That ALSO makes zero sense.

- **D)** Defaulting the program to open in 720p, 30 FPS and then allowing us to export it in whatever quality choose makes no sense. Having to change the profile we are working Openshot in and then restart the program just to work on what we want to export the file to is just... Well, again, it makes no sense.

- **E)** What is with the INSANE export times??? It's taking over 20 hours to export a video that is 4 ghz/s - far, far less than the previous quality, and yet the same amount of export time. Why? I know my computer is terrible, so of course it's gonna take a while to process things, but no other program I've evr used has taken this long, much less for a video that is less than triple the quality I did previously.

I'm sorry if I'm being overly harsh, here. I'm obviously no programmer and this program offers a lot, much less for a free program. I appreciate the in-depth explanation and ability to speak with those involved with the project, as well. Thank you for your help. I'm going to keep testing things and hoping for the export to finish to see the product (whether it actually muted things, whether audio is jumpy/muted in random places, and what the file size is, etc). Please stay tuned and don't close the issue! :)

**Comment by SuslikV** [comment]
>... I'm not entirely sure what "crf" ...

Main developer decided to not use another field for quality setting (if supported by encoder) and thus reused the field of bitrate to be able to set the quality of encoding instead of strict bitrate setting. "CRF" itself stands for _Constant Rate Factor_. Affects quality during encoding. Take values from `0` - lossless (almost, in current implementation of OpenShot), to `63` - the worst quality. Values from 18 to 23 is suitable for HD and FullHD content. For example, in FFmpeg the syntax for the option is a bit different - the `crf` comes first and value is next. The value preserved when _Export Video_ dialog remains open (of course you can create your own _Target_ presets based on `presets\format_mp4_x264.xml` file from the OpenShot's folder and use them instead).

**Comment by Bananasaurus** [comment]
Nice, thank you. Using all these tips I've finally reduced the file size somewhat. The issue of how long exporting takes, even for users with vastly better computers than I have (I've spoken to a few users of Openshot on the video editing subreddit and they all complain of the same thing but have better specs)... THAT still exists.
Even lowering the quality like this doesn't have much of an impact. Any suggestions? I recently re-discovered the editor called VideoPad and the export times are far, far less, even for the same exact video - but there aren't as many things I can do with it, I don't think.

**Comment by SuslikV** [comment]
Not much you can do right now. In OpenShot was only implemented two types of the output processing: draft (preview) and final (export) quality. The last one uses slow preset from encoder to get quality in cost of speed. This can't be changed by user. Maybe later, when export options will be extended to actual level of the encoder capabilities, you'll be able to speedup process a bit. Some development decisions doesn't allow hardware accelerated render and uses slowest techniques for hardware accelerated encoding (and this wouldn't be changed anytime soon).

**Comment by sj-on** [comment]
> Ok, I'm gonna test a some of these out, @ferdnyc - give me a bit, though, because I'm recovering from surgery and already encountering issues. So far I've figured out that Windows Defender blocks saving, editing, or usage in protected folders, including Pictures, Videos, Dekstop, and Documents. On top of that, I was unable to add Openshot to my trusted programs because my anti-virus, Bitdefender, blocks access to even doing THAT. I had to find tutorials on how to add Openshot to the trusted programs, so that finally allowed me to save projects in Videos.
> 
> However, upon attempting to move the projects, I clicked on the project file when the dialog box opened, yet Openshot then stated the file didn't exist and it vanished from the File Explorer while within the dialog box... only for me to go outside of Openshot to double-check it was still there, and yep, it was.
> 
> So, I tried moving the ORIGINAL video into the folder i wanted to save projects in, and did not move any file/folder that was created upon saving the OSP or exporting a short sample clip used to experiment with this. The files created by exporting was a folder titled "thumbnail" and I kept it there. Re-opening the OSP after closing Openshot, the keyframes themselves were gone but the areas where I muted the audio was still muted.
> 
> * **A)** Moving project files (OSP) should not make an issue where Openshot is able to see the file, then clicking on it makes Openshot say it doesn't exist, then Openshot makes them "disappear" from within the file explorer only within the program despite it still being there when I went to the folder outside of Openshot, then not being able to open the file at _all._ The only file CREATED when saving an OSP file is the file itself, it makes ZERO sense that I am forced to not only keep the file in place, but to keep the original source material in the same folder as well.
> * **B)** Why even allow us to save a file anywhere else, other than the source file's location, if that's the case?
> * **C)** Key frames should still show up and be editable upon re-opening a project file. What is the point of saving a project file if we're unable to edit it? It's as if we exported it and are working on a source file. That ALSO makes zero sense.
> * **D)** Defaulting the program to open in 720p, 30 FPS and then allowing us to export it in whatever quality choose makes no sense. Having to change the profile we are working Openshot in and then restart the program just to work on what we want to export the file to is just... Well, again, it makes no sense.
> * **E)** What is with the INSANE export times??? It's taking over 20 hours to export a video that is 4 ghz/s - far, far less than the previous quality, and yet the same amount of export time. Why? I know my computer is terrible, so of course it's gonna take a while to process things, but no other program I've evr used has taken this long, much less for a video that is less than triple the quality I did previously.
> 
> I'm sorry if I'm being overly harsh, here. I'm obviously no programmer and this program offers a lot, much less for a free program. I appreciate the in-depth explanation and ability to speak with those involved with the project, as well. Thank you for your help. I'm going to keep testing things and hoping for the export to finish to see the product (whether it actually muted things, whether audio is jumpy/muted in random places, and what the file size is, etc). Please stay tuned and don't close the issue! :)
> 
> @SuslikV
> 
> > In Export Video>Advanced tab>Video Settings>Bit Rate/Quality field type 18 crf instead of 15.00 Mb/s (or whats ever) for lower size and same quality.
> 
> Does that 18 crf count for all my projects, or just this specific one? I'm not entirely sure what "crf" even stands for since I can't find it on Google, and I'm a dunce. I know what Mbs/s is now, though.

I had the same issue when I started using Openshot for video editing. Combining two videos of size x and y would generate a file [exported video] with size much larger than x and y combined. The software is good, no doubt. But I switched to Kdenlive because of the above issue.
Hope it is resolved by now. Or will be in the future.😅

**Comment by nedjo** [comment]
I had this issue too and resolved it following the advice from @ferdnyc, [above](https://github.com/OpenShot/openshot-qt/issues/2866#issuecomment-511163115):

> It's actually possible to export at any bitrate you please by typing it into 'Video Settings > Bit Rate / Quality" in the Advanced tab of the Export dialog

Before I did this my export size was many times that of the original video, which had been 27.2 MB. Following these steps got me an export of 28.2 MB with no reduction in quality vs. the original as far as I could tell--very acceptable, particularly considering I'd added titles (subtitles) throughout the video.

Here are my specific steps (I'm on Ubuntu):

1. __Find properties of original video__. In the file browser (Nautilus), right click the video file, choose "Properties", and click the "Audio/Video" tab. For "Video", this shows dimensions, codec, framerate, and bitrate. Also note the values for audio.
1. __When exporting, use the "Advanced" tab to select settings that match those of your original video__. These are the steps I took:
    * On the "Simple" tab:
        * Leave "Profile" at "all profiles".
        * For "Target", choose the codec that matches the one for your original video.
        * For "Profile", choose one that most closely matches the one for the original video.
    * Click "Advanced". On the "Advanced" tab:
        * Click "Profile" and edit the settings there (width, height, etc.) to match as closely as you can those of your original video.
        * For each of "Video settings" and "Audio settings", edit the values to match those of your video and audio original. At a minimum, edit the "Bit rate".
    * Click "Export video".
