### ISSUE TITLE
ModuleNotFoundError: No module named 'openshot'

### ISSUE THREAD

**Issue by cminghao** [OpenShot/openshot-qt#2875]
`ModuleNotFoundError: No module named 'openshot'`

Having spent a two days or more on this issue in libopenshot and having solved it (hopefully), I did not forsee it having such an impact on openshot-qt.

When trying to use `python  >>>> import openshot` after libopenshot it fails, however by doing `python openshot.py` in the directory of where `openshot.py` and `_openshot.pyd` is I believe i got it to install properly as I did not encounter any error.

After all that I moved onto `openshot-qt`, everything was going well(thought there isn't much) till I tried to use python `src/launch.py` I get the error

```
C:\MSYS\msys\1.0\home\openshot-qt>python src/launch.py
Loaded modules from current directory: C:\MSYS\msys\1.0\home\openshot-qt\src
Traceback (most recent call last):
  File "src/launch.py", line 103, in <module>
    main()
  File "src/launch.py", line 96, in main
    app = OpenShotApp(argv)
  File "C:\MSYS\msys\1.0\home\openshot-qt\src\classes\app.py", line 64, in __init__
    from classes import settings, project_data, updates, language, ui_util, logger_libopenshot
  File "C:\MSYS\msys\1.0\home\openshot-qt\src\classes\logger_libopenshot.py", line 31, in <module>
    import openshot
ModuleNotFoundError: No module named 'openshot'
```

is there a way to use `python openshot.py` instead of `import openshot` ?

I'm using Windows 10 with python 64-bit

**Comment by ferdnyc** [comment]
@cminghao 

Sorry, I've been embroiled in other things and haven't been keeping up with your posts well, I apologize for that.

If you have a _working_ `openshot` Python module, meaning one where loading `openshot.py` succeeds, it's able to internally import `_openshot.pyd`, and you can run (say) `print(openshot.GetVersion())` in Python after the openshot module loads, then you _should_ be able to run OpenShot itself by doing the following:

#### In a Bash-style Unix-syntax terminal
```sh
cd /path/to/cloned/openshot-qt
PYTHONPATH=/path/to/the/bindings/for/lib/openshot src/launch.py
```

#### In a Windows Command Prompt terminal:
```cmd
cd C:\Place\Where\You\Have\Checked\Out\openshot-qt
set PYTHONPATH=C:\Wherever\The\Bindings\Live\For\Lib\Openshot
python3 src\launch.py
```

...This is theoretical, because I've never _tried_ that on Windows, but it's how I run devel versions of OpenShot all the time.

(On Windows, it might be an even simpler matter of just dragging all of the necessary DLLs, modules, etc, together into the same directory, and running OpenShot from there; Windows tends to like that.)

**Comment by ferdnyc** [comment]
The other thing you can try, on Windows — I know, because this I _have_ done — is start by installing OpenShot from the official installer, then just overwrite whatever parts of the `C:\Program Files\OpenShot Video Editor\` contents you want to update with your own, newer versions of the same files. 

Now, here again a caveat: I've done that plenty with the _Python_ sources for openshot-qt, on Windows. But I've never HAD a self-compiled set of libopenshot DLLs, to try it with the library pieces. I guess whether it would work comes down to how closely your own builds match the way the official binaries are built.

**Comment by ferdnyc** [comment]
**UPDATE:**

> If you have a _working_ `openshot` Python module, meaning one where loading `openshot.py` succeeds, it's able to internally import `_openshot.pyd`, **and you can run (say) `print(openshot.GetVersion())` in Python after the openshot module loads**, then you _should_ be able to run OpenShot itself by doing the following:

Make that "and you can run `print(openshot.GetVersion().ToString())` after the module loads (and you get `0.2.3` for an answer)".

**Comment by ferdnyc** [comment]
> The other thing you can try, on Windows — I know, because this I _have_ done — is start by installing OpenShot from the official installer, then just overwrite whatever parts of the `C:\Program Files\OpenShot Video Editor\` contents you want to update with your own, newer versions of the same files.

One other caveat with this approach: There are version dependencies between the various pieces that come into play. The libopenshot-audio, libopenshot, and openshot-qt Python sources packaged together in the OpenShot 2.4.4 release installer are all synced up, they use the same versions of all their various APIs. 

If you try to update _just_ the openshot-qt Python sources to the latest git commits, and run them against the libopenshot{,-audio}.dll files from the 2.4.4 installer, OpenShot will crash because the new Python code is looking for updated API calls that were added to the libraries after 2.4.4 was released. (That's true on Windows, Linux, Mac, everything.)

If you try to update libopenshot.dll and the `openshot` Python bindings to versions built from the latest `libopenshot` commits, and try to run the OpenShot 2.4.4 release Python code with those updated DLLS, OpenShot will crash because the 2.4.4 Python code doesn't know about those new APIs that were added recently, so it doesn't know how to communicate with a more recent libopenshot.

...You get the idea. Point is, if you _do_ try to work off an installer build and update it, either start from the most recent Daily Build installer (so that the versions of the files you install are already API-compatible with the code in the project's current GitHub source trees), or you have to update _all three_ of the OpenShot project pieces together, since trying to mix and match APIs across a few months' worth of development is guaranteed not to work.

**Comment by cminghao** [comment]
@ferdnyc Not a problem, please don't apologize for that, you replying and answering my questions are already a huge help to me and I really can't thank you enough for your help!!

despite having what I **hope** is a working `openshot` Python module (due to seeing this 
 ```
extension module '_openshot' loaded from 'C:\\msys64\\usr\\lib\\python3.7\\site-packages\\_openshot.pyd'
 extension module '_openshot' executed from 'C:\\msys64\\usr\\lib\\python3.7\\site-packages\\_openshot.pyd'
import '_openshot' <_frozen_importlib_external.ExtensionFileLoader object at 0x0000000002d25690>
```

and not having an error. I can't seem to run `print(openshot.GetVersion().ToString())` neither with being in `Python` nor being outside of `Python` using `python print(openshot.GetVersion().ToString())`

OK,DESPITE ALL THAT, IT WORKS, IT FINALLY WORKS
```
cd C:\Place\Where\You\Have\Checked\Out\openshot-qt
set PYTHONPATH=C:\Wherever\The\Bindings\Live\For\Lib\Openshot
python3 src\launch.py
```
this was able to work even though `print(openshot.GetVersion().ToString())` was not able to.

thank so much @ferdnyc ! 

if I were to choose to use the other method of using the OpenShot from the official installer, would I be able to package it for others to use? and what if I wanted to add things onto it that would not require the libraries,would that be possible?

**Comment by ferdnyc** [comment]
> if I were to choose to use the other method of using the OpenShot from the official installer, would I be able to package it for others to use? and what if I wanted to add things onto it that would not require the libraries,would that be possible?

_Possible_, certainly, with a little effort. I don't know that working **from** the installer packages would allow you to _create_ an updated installer package, I have a feeling what's in there is too "cooked" already. But it should be very feasible for you to build your _own_ installer packages from the source tree, and if you've managed to _build_ working copies of libopenshot and libopenshot-audio on Windows, then packaging them together with OpenShot itself should be relatively easy. 

You'll first need to install and configure the rest of the OpenShot dependencies. (Things like PyQt5 and etc. But as OpenShot's remaining dependencies are all Python modules, that's _way_ easier than dealing with compiling the DLL pieces.)

Then you'll need the tools to do the actual packaging, of which there are only two hard requirements:
* `cx_Freeze`, which again is a Python module and pretty easy to obtain and install
* InnoSetup, which compiles the actual installer binaries used to distribute OpenShot. That's even _easier_, as InnoSetup is a well-organized, _ancient_ project with all of its kinks long since worked out several times over. (It lives at http://www.jrsoftware.org/ )

With those pieces available, you can see all of the steps the official builders run by looking at two files... well, maybe three total, all of them here in the `openshot-qt` repository:

First is `.gitlab-ci.yml`: That's is the master control script for the GitLab builders which produce the official OpenShot installer packages. There are sections for both 64-bit and 32-bit Windows in there. There's a lot of, like I said, "build system automation" in there that you can ignore, things like fetching Git tags to automatically name files, etc. That's al process stuff you don't need to bother with, if you're just looking to hand-roll an OpenShot package.

https://github.com/OpenShot/openshot-qt/blob/248fcce490f341d0839c4952229ab24070649f6e/.gitlab-ci.yml#L80-L90

Basically, out of all of that, the last two lines are the only ones you care about... and you can only directly use the first one. 

Running `python3 freeze.py build` from a cloned copy of this repository **_should_** net you a "frozen" (collected into a self-contained folder) copy of the OpenShot application and all of its dependencies, if you have those dependencies installed and available in the places where it expects to find them. 

Once OpenShot is frozen, then `build-server.py` uses InnoSetup to create the redistributable installer package.

As I said, you can't _run_ `build-server.py` because it's built with dozens of assumptions about what it's supposed to be doing and the environment that it's running in, assumptions that are only valid when you're running on @jonoomph 's server.

But you can read through it, see the steps it takes to create the package, and work out how to run the necessary ones locally to get a similar result. And it's actually fairly well commented, too! (You don't have to pretend not to be surprised, **I'm** surprised.)

These bits are important...

https://github.com/OpenShot/openshot-qt/blob/248fcce490f341d0839c4952229ab24070649f6e/installer/build-server.py#L404-L430

These, not so much. (You _can_ install Verpatch and use it to set the metadata on the OpenShot executable, but it will affect literally nothing if you DON'T do that, and in fact we only started doing it a month ago.)

https://github.com/OpenShot/openshot-qt/blob/248fcce490f341d0839c4952229ab24070649f6e/installer/build-server.py#L436-L451

Now, back to important again, as it actually runs InnoSetup...

https://github.com/OpenShot/openshot-qt/blob/248fcce490f341d0839c4952229ab24070649f6e/installer/build-server.py#L453-L478

And back to less important, though whether it's actually important that the packages you generate be cryptographically signed is between you and anyone who might have to decide whether they're brave enough to run an unsigned installer on their system.

https://github.com/OpenShot/openshot-qt/blob/248fcce490f341d0839c4952229ab24070649f6e/installer/build-server.py#L480-L498

And from there on it goes back to unimportant, as the rest of the code is all about publishing and announcing the new build, which is stuff you completely don't have to care about. Basically, if you get to this point, you're done and should have a shiny, new OpenShot installer `.exe`!

**Comment by ferdnyc** [comment]
@cminghao 
> I can't seem to run `print(openshot.GetVersion().ToString())` neither with being in `Python` nor being outside of `Python` using `python print(openshot.GetVersion().ToString())`

In case you're curious, or for future reference, or whatever, I finally did clue in to what was going on here. It's a fairly straightforward quirk of Python's namespacing and module hierarchy, completely normal once you're familiar with how all that works (and awake enough, apparently).

Actually, last things first: 
```sh
python3 print(openshot.GetVersion().ToString())
```
That could never work, because the `openshot` module is never imported in that scenario. You can't make any references to `openshot` until after you've done the import.

The form of that command that _**would**_ be expected to work is:
```sh
python3 'import openshot; print(openshot.GetVersion().ToString())'
```
(Parentheses are typically interpreted specially by any command shell in use, so I'd be pretty surprised if that command succeeded _without_ enclosing the Python code in quotes.)

But more importantly (and more interestingly), the reason that _this_ didn't work for you:
```python
python3 openshot.py
>>> print(openshot.GetVersion().ToString())
```
is because, when you _execute_ `openshot.py`, you're effectively running the Python interpreter **inside** the module, and therefore inside its _namespace_.

Normally, when you import a Python module, the interpreter takes all of the symbols (classes, methods, etc...) and places them all inside a namespace that has the same name as the package being imported, rather than polluting the global namespace where your code runs.

But when `openshot.py` _is_ the code running in the global namespace, that encapsulation isn't done and all of its symbols live at the global level, same as if you'd done `from openshot import *`. (Which was super common Python code, back in the day, before everyone got clued in to how evil it is and stopped making excuses for anyone terrible enough to still be writing code that way.)

The other thing that's tricky about running `python3 openshot.py` is that the module code isn't written to be run directly, so all it does is exit immediately. You'll end up right back at your shell prompt. But Python has a solution for that, in the form of the `-i` flag:
> ```
> -i     : inspect interactively after running script; forces a prompt even
>          if stdin does not appear to be a terminal; also PYTHONINSPECT=x
> ```

So, the thing that _could_, _should_, and **_would_** have worked, for testing the Python bindings by running `openshot.py`, is this:
```python
python3 -i openshot.py
>>> print(GetVersion().ToString())
0.2.3
>>>
```

Because you're running _inside_ the `openshot` namespace, in that instance, you reference its contents directly instead of prefixing them with the imported namespace tag.

**Comment by cminghao** [comment]
@ferdnyc I see, thank you for taking time to reply and help me solve the problems! that should be all for now (and hopefully for quite awhile), once again, thank you very much for your help! it is really appreciated!
