### ISSUE TITLE
Crash occuring when trying to edit geforce experience video files after using razor tool

### ISSUE THREAD

**Issue by Prisonfish1** [OpenShot/openshot-qt#2896]
**Describe the bug**
Anytime i try to edit footage recorded using nividia geforce experiences shadow play 1440p 60 fps audio rate 48000 mhz the program struggles from the beginning i have set the defaults to match this to no avail. After any action is completed however for example cutting a track the whole program crashes after i try to move past the cut section. The playback fails and then when you try to move the track it freezes and or crashes.

steps toe repeat
1. open any file from geforce experience
2. add it to the track
3. cut the track anywhere
4. try to watcvh playback after the cut area 

**Expected behavior**
I expected like all the other videos i do from my regular webcam i could cut and splice clips quite easily the program works perfectly using clips from streamlabs obs currently it is only the files from nvidia geforce experience

**System Details**
- OpenShot Version: 2.4.4
- libopenshot Version:  0.2.3
- Platform: Windows-10-10.0.17763
- Processor: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
- Machine: AMD64
- Python version: 3.6.4
- Qt5 version: 5.9.1
- PyQt5 version: 5.9
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.4.4-dev2-1564165829-769efd87-574877b9-x86_64.exe

**Log Files**
- http://logs.openshot.org/rcgalbsrnx0o3j9troaotz92l320fp6f/openshot-qt.zip
- http://logs.openshot.org/rcgalbsrnx0o3j9troaotz92l320fp6f/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by SuslikV** [comment]
Can you make new short sample file (few seconds) that still causes crashes and share it (google drive link, for example)? I want to reproduce the issue on my end.

**Comment by ferdnyc** [comment]
@Prisonfish1 Yeah, like @SuslikV says a sample file would be helpful, since like you say other files work fine, so there must be something different about the files produced by GeForce Experience, specifically. 

If the file size is small enough (has to be under 2 MB, I think?) you can even just place the video in a ZIP file and attach it directly to an issue comment.

(However, providing a sample that's under that limit may be difficult, because apparently the files produced by this software are HELLISHLY large. The logs indicate the 28-second capture you imported was 126 MB!?! Wow. So, an offsite file-locker or sharing service is probably the best option.)

Without a sample file to examine, _offhand_ the only thing that immediately jumps out at me is that the file's frame rate is detected as `25005000:416743` fps, which is a weird figure that works out to be just _slightly_ over `60` fps. (it's `60.14533` fps, to be precise.) So, it's _possible_ that's causing OpenShot some issues, though certainly it isn't supposed to be **crashing** no matter what kind of file is imported.

**Comment by ferdnyc** [comment]
Oh, I know you said you matched defaults to the file format, but one other thing just to double-check: In OpenShot's "Preview" preferences, you have the "Default Audio Sample Rate" set to 48 kHz (48000 Hz), correct? 

That's not a per-project setting like the video Profile is, and the OpenShot default-default is 44.1 kHz, so I wanted to make sure. Trying to resample the audio _could_ theoretically be a source of crashes. (But, again, it **shouldn't** be, and if that's the issue then it's still a bug on our end.)

**Comment by Prisonfish1** [comment]
Hey guys i will work on getting you a sample.
Not going to lie my knowledge is pretty basic in this area so if you could tell me exactly what you need me to do would be great i can send you one of the files i was trying to work on via dropbox or something like that.
As for the audio i set the default in the preferences menu to 48000mhz

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ferdnyc** [comment]
> Not going to lie my knowledge is pretty basic in this area so if you could tell me exactly what you need me to do would be great i can send you one of the files i was trying to work on via dropbox or something like that. 

That's basically all we need, exactly that. We just need any file that shows the symptoms you described, where OpenShot will crash when Previewing / scrubbing after you've sliced the clip. 

To keep download times/sizes reasonable, the smaller the better. If you have (or can create) an especially short capture from GeForce Experience, so the file size is only a few megs or tens of megs, that'd be ideal. (And if not, even the 126 MB file shown in your logs would be fine. Hey, it's your Dropbox allocation, not ours! :wink: )

Just create an "anyone with this link can view" shareable link (which you can do from Dropbox's web interface, and I'm sure in the Windows tool as well), and post the URL here. Since that link will then be public, whatever video you select also shouldn't include any private or sensitive information. You should assume that it could potentially be viewed by anyone.

**Comment by Prisonfish1** [comment]
I tested this file it doesnt play up as bad as the larger ones but still after cutting using the razor tool and then deleted the forward section playback goes very jumpy and then when i tried to cut it a 2nd time with playback still running i got the not responding cue. also when i closed it the program went not responding for a short period. Watching task manager as i do this it goes from using roughly 40 percent processor power to well over 90

https://www.dropbox.com/s/ic87a0oauw7fr0w/Sample%20for%20openshot.mp4?dl=0
[https://www.dropbox.com/temp_thumb_from_token/s/ic87a0oauw7fr0w?preserve_transparency=False&size=1200x1200&size_mode=4]<https://www.dropbox.com/s/ic87a0oauw7fr0w/Sample%20for%20openshot.mp4?dl=0>
Sample for openshot.mp4<https://www.dropbox.com/s/ic87a0oauw7fr0w/Sample%20for%20openshot.mp4?dl=0>
Shared with Dropbox
www.dropbox.com


________________________________

**Comment by ferdnyc** [comment]
Perfect, thanks! I edited your comment slightly, just to change the URL to end in `?dl=1` instead of `?dl=0`. That'll tell Dropbox to serve the file for direct downloading, instead of viewing it in the browser. And download it I have.

...Wow. I see what you mean. I placed the clip on a track in the timeline, performed a "Slice: Keep Both Sides" on it, and now if I try to Preview the entire timeline, OpenShot is _not_ having it. It's completely unable to get past the slice point. OpenShot didn't **crash** for me (on Linux), but the CPU load spiked to maximum and the preview playback froze completely until I hit Stop, so it didn't really have any better luck than you were having.

No solutions yet, but yeah I'm definitely seeing the same problem. It looks like OpenShot's unable to play the file starting from any frame except the first. (Which is what the right-hand side of any Slice operation is, a clip that doesn't start from the first frame.)

Flagging as a bug, most likely in the FFmpegReader component.

**Comment by Prisonfish1** [comment]
Ok no worries. Happy i was able to help you guys find something. Let me know when i is resolved love the fornat of openshot and i will keep using it for the streamlabs recordings for now i have had to use videopad for these geforce clips. But would definitely prefer going back to openshot.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by SuslikV** [comment]
@ferdnyc , any special about the file? Did you try to wait for a time that required to playback the file from the start to the cut point?

**Comment by ferdnyc** [comment]
> Did you try to wait for a time that required to playback the file from the start to the cut point?

I did, at least (somewhat longer, even), but it didn't appear that OpenShot was ever going to find its way to the requested start point.

> any special about the file?

Nothing _immediately_ obvious, other than the high (a) resolution, and (b) frame rate, which makes for a taxing decode even under ideal conditions.

Also, because it's a live-source capture, my _suspicion_ is (though I haven't examined the structure yet to confirm) that the videos contain **NO** keyframes after the first frame, since the on-the-fly encode process wouldn't lend itself to constructing full frames while furiously slapping them down into the stream, nor would it be possible to perform the contextual analysis that's typically used to choose which frames those keyframes should be located at. The video is also very probably lacking any real index to speak of.

My suspicion is that it's the lack of index and/or keyframe points that's causing OpenShot to fail when it attempts to start playback from a non-first-frame position. Though, if that's the case, like I said: Our bug. If nothing else, it _**should**_ be able to to what you implied: simply start playing from the first frame, discard all of the ones that come before its target position, and pick up when it hits the right spot. That's not working, despite the fact that these files are only a few seconds long..

**Comment by Prisonfish1** [comment]
Hi i was just wondering if there has been sny luck on the front of this issue. And if its been implemented to a daily version or anything. The current software i have had to use in the meantime over openshot is no ehere near as good. And much more time consuming

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ferdnyc** [comment]
@Prisonfish1 

I'm afraid there hasn't been any progress, sorry. To be perfectly honest, I wouldn't expect that there will be a fix for this coming anytime very soon. 

I could lie and string you along and just keep saying, "Oh, yeah, any day now!" but I'm not gonna do that to you. The reality is, it's an issue for which there doesn't seem to be any obvious simple/immediate solution, and it only affects a very small percentage of OpenShot users who are importing video from one specific piece of software. And, given that we currently have 676 open issues...

I'm very glad you checked back in, though, because I did mean to update you on that, and there's also a workaround that I'd meant to offer you, but then forgot.

If you _do_ want to use your GeForce Experience videos with OpenShot, and you're able to spare a little extra disk space (and time), one option would be to transcode them to a more standard format that OpenShot handles better.

A tool like [HandBrake](https://handbrake.fr) can do this very capably, and even makes it easy to set up the parameters of the conversion, save them as a preset, and then process multiple files, or even entire directories full, in batch mode without user intervention.

I loaded the sample video you sent into HandBrake, opened their Production > Production Standard preset as a starting point, lowered the Rate Factor from 10 (excessive) to 18, lowered the audio bitrate from 320kbps to 192kbps (same as the source), and then had it convert to H.264+AAC in an MKV container. The file size was 80MB, only 10MB more than the original (raising the Rate Factor slightly higher would've gotten it even smaller). And importing that cleanly-indexed and structured MKV into OpenShot shows none of the same playback issues as the original file, even when slicing and moving Clips' starting frame.

It's not an _ideal_ option, but it's a very workable one, and probably the only solution available for at least the very near future. Apologies again for that.

**Comment by Prisonfish1** [comment]
Honestly mate the temporary fix i can give a go. It sounds similar to my own dodgy stop gap of using videopad to render the videos and then loading those videos into openshot.

I definitely understand its a small issue on the list mate cheers for the suggestion

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by SuslikV** [comment]
@Prisonfish1 can you share the file sample again?

**Comment by ferdnyc** [comment]
@SuslikV https://drive.google.com/file/d/1Yv3jL7Q3hp7acVyNgyNT3NJ-CFaKXnYN/view?usp=sharing

**Comment by SuslikV** [comment]
Where exactly I should slice the mentioned .mkv file to reproduce the issue?

**Comment by ferdnyc** [comment]
Wait, MKV? I may have shared the wrong file, it should be an MP4. That may be my "fixed" version. Let me take a look...

**Comment by ferdnyc** [comment]
Yup, sorry. This is the original file:

https://drive.google.com/file/d/1nhC_KnXpO_rKL03jecwvo7Hv_NnbvdDq/view?usp=sharing

I split it roughly in the middle, when I tested, using "Slice > Keep both sides". The difference in preview playback between the first segment and the second was _pronounced_.

**Comment by SuslikV** [comment]
I see now. This is seeking algorithm problem - it works, but very very slow (about 10-15 sec per 3 frames, so if you wish to playback at the middle - you have to wait for a long).

Specific of the file:
1) File uses large version of box of samples offsets (`co64`) that is not typical for such small file (less then 4GB) but it's quite normal.
2) The number of samples per chunk (one interleave) is high - about 60 samples of one track and only then 60 samples of next track and so on. It's normal too but not in OpenShot...
3) Some samples has insignificant variations of delay (sample delta) - this results in variable frame rate. Generally, that may cause sync issues.

The p.2 causes problems in OpenShot seeking algorithm - you need to wait until all required frames will be cashed in OpenShot.

**Workaround:** remultiplex the file again into .mp4 container with FFmpeg or any tool that uses it (like _Remux Recordings_ option from OBS Studio application). The resulting file should playback well in the OpenShot.
