### ISSUE TITLE
OpenShot really doesn't like scaling down (big) images during preview playback

### ISSUE THREAD

**Issue by jarlarntzen** [OpenShot/openshot-qt#29]
My recent MacBook Pro starts huffing and puffing **quite a bit** when trying to play back even a single 2000x3000px image without any effects, transitions or similar. Now, OpenShot even seems to have hung while playing back this single image.

Incidentally, nice images for any use (CC0) are readily available at http://www.unsplash.com 

Smaller images and videos work a lot better.

**Comment by jarlarntzen** [comment]
**OpenShot 2.0.5 on Ubuntu 14.04 LTS**:
Timeline playback performance is improved from 2.0.4 when playing my slideshow test case with 8 png-images fading in-out and zooming in. There seems to be little penalty in playback rate with these images. I'll try again with some larger images.

**Comment by jarlarntzen** [comment]
**OpenShot 2.0.5 on Ubuntu 14.04 LTS:** Still doesn't like scaling down big pictures (like those found on http://unsplash.com ). Timeline playback is very slow, about 25% and pretty jerky, especially during transitions. Even showing a single image without any transitions brings down the playback speed to about 50%.  Images are typically ~5000x3500px.

**Comment by jonoomph** [comment]
This is a known issue at the moment. The original image is cached in memory, but it's copied and scaled on each frame. If I resize the original image first (before caching), then zooming into the image will become fuzzy, etc... Or a better example, if you have a super tall SVG (i.e. credits graphic), and you want to animated it moving up on the screen, we need to keep the original size.

So... maybe we need an additional setting on an image clip... about the maximize size... or something like that. Not sure. =)

**Comment by jarlarntzen** [comment]
How about determining the largest scale the image will be during the animation and then scale down to that. Anyway, I thought OpenGL took care of scaling...? I'm sure I do not really understand this well enough.

**Comment by NValerij** [comment]
The same problem with FullHD video from GoPro. Preview is not usable at all =(
May be it is possible to create parallel low-resolution photo/video for preview-only...

**Comment by skoam** [comment]
Openshot is nearly unusable right now to edit a 1080p video. The preview is way too slow. It worked fine in 1.4.3 - what happened here? I was looking forward to use the 2.0.7. version, but it seems I'll need to go back to my constantly crashing old version because of this.

I'm using mp4 h264 files. I double checked and they work very well in 1.4.3. I'm tried the AppImage and the PPA Version, without any difference on Linux Mint 17.

**Comment by kpouget** [comment]
this is still a big issue for me with the up-to-date version of Archlinux repository ...

         app:INFO openshot-qt version: 2.1.0
         app:INFO libopenshot version: 0.1.2
         app:INFO platform: Linux-4.7.2-1-ARCH-x86_64-with-arch
         app:INFO processor: 
         app:INFO machine: x86_64
         app:INFO python version: 3.5.2
         app:INFO qt5 version: 5.7.0
         app:INFO pyqt5 version: 5.7

**Comment by jonoomph** [comment]
Please retest with our latest daily build. We've optimized large images and playback for HD content, as long as you set your preview profile to a smaller size (720 for example). If you have issues that are not related to scaling down huge images, please file new bugs. Thanks!

Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot.

**Comment by skoam** [comment]
Hey @jonoomph - thank you for your update on this. I recently discovered that the laggy playback (and overall bad performance) was caused by the video files I was using. I recorded them with an unlimited bitrate, creating files with 40k+ and 80k+ kbit/s bitrate. This caused the many crashes and horrible performance in the video editor. This could be worth another ticket, even if I think that it would be enough to have a warning message for such files.
