### ISSUE TITLE
Audio issues when previewing

### ISSUE THREAD

**Issue by sledgehogrc** [OpenShot/openshot-qt#2910]
New user to openshot using the latest version. I'm importing MP4 files from a yi lite action came and also from my pixel 2 phone. Whenever I try to preview my video, the audio is played back as nothing but a low buzzing sound. Any way to fix this issue? Do I have to separate the audio from the video file before importing somehow? My exported video comes out fine but it's hard to edit properly when I can't hear the audio being played while doing so. 

Please let me know what info you may need to help troubleshoot this issue. Thanks.

**Comment by ferdnyc** [comment]
@sledgehogrc 

You don't mention what OpenShot version, OS, or audio output device you're using so it's difficult to say where the issue might be, but if the export comes out with uncorrupted sound then the issue you're experiencing must be related to OpenShot's connection to your system's sound hardware.

I would suggest downloading the latest Daily Build release for your operating system from https://openshot.org/download/ . (Click on Daily Builds to see the list, newest builds are on top — if you're on Windows be sure you pick the correct 32-bit or 64-bit release to match your installed Windows version.) Audio device selection has been added to the Preferences since the last OpenShot release (2.4.4), it's possible that you simply need to select the correct sound output in order for OpenShot to preview correctly.

**Comment by sledgehogrc** [comment]
I'm using 2.4.4, 64-bit version on windows 10 64-bit. I only see audio options for output files in preferences. I don't see any preference options for selecting audio device, only default sample rate and default audio channels.
Even when I export a video with fine audio, I re-open Openshot, import the same exact video I just output from it, and it still does nothing but buzzing static for the audio in the preview.

**Comment by sledgehogrc** [comment]
NVM I figured it out. I had to set the audio channels to 7.1 while using my headphones. Not sure why though as any plain 2ch stereo file of any type plays normally in them with exception to preview videos in this program alone. Maybe something to look into fixing in the future?

**Comment by ferdnyc** [comment]
> I'm using 2.4.4, 64-bit version on windows 10 64-bit. I only see audio options for output files in preferences. I don't see any preference options for selecting audio device, only default sample rate and default audio channels.

Correct, the audio device selection features were added recently, since 2.4.4. That's why I suggested trying the Daily Builds, which have the newest features being developed for the next release.

> Maybe something to look into fixing in the future?

Way ahead of you, that's why device selection was added. :wink:
