### ISSUE TITLE
Weird behavior with Ctrl + Right Click after selecting multiple items on timeline

### ISSUE THREAD

**Issue by hb20007** [OpenShot/openshot-qt#2911]
**Describe the bug:**
After selecting multiple items on the timeline using `Ctrl`, if right click is pressed while still holding down `Ctrl`, the context menu which appears is slightly different than the one which appears if `Ctrl` was released before the right click. In the former menu, the `Copy` option expands to give options for `Clips`, `Effects` and `Keyframes`. In the other right-click context menu, the `Copy` option does not expand and its functionality is to copy the clips.

The **main problem** is that the version of the context menu which appears while holding `Ctrl` doesn't properly support copying multiple clips. When selecting `Copy` > `Clips` and then pasting, only the last element selected is copied and pasted, instead of all of the elements.

While the other right-click menu can be used to copy multiple items on the clipboard, this is a problem because, for instance, I wasn't aware that there is a different context menu if `Ctrl` is not held down. I tried copying several items on the timeline using `Copy` > `Clips` and it wasn't working, which made me think that OpenShot is incapable of copying and pasting multiple items on the timeline.

I personally think it's confusing that two different context menus exist, especially since they are very similar.

**Steps to reproduce the behavior:**
1. Select multiple adjacent items on the timeline by clicking them while holding `Ctrl`.
2. While still holding down `Ctrl`, and with the cursor still on the last item you selected, right click.
3. Select `Copy` > `Clips`.
4. Go to an empty area on the timeline, right click, and select `Paste`.
5. You will notice that only the last clip you selected was copied, instead of all of them.

**Expected behavior:**
All the clips should have been copied. Also, if the developers agree, there shouldn't be 2 different context menus in the first place.

**System Details:**
- OpenShot Version: 2.4.3, still present on 2.4.4
- Operating System: Windows 10

**Comment by ferdnyc** [comment]
@hb20007 Hmm, I'm not seeing the same behavior you describe. It's possible this is an OS difference in how they handle multiple-selection and/or mouse clicks combined with modifier keys, since I'm on Linux and you're on Windows.

...Actually, no, wait, I am. But only if I right-click too quickly, it's not a persistent thing, it's just a momentary delay in reconfiguring the menu that the user can jump in front of if they're quick enough, looks like.

What's _supposed_ to happen when you right-click with multiple clips selected is, you get the multi-selection context menu, which is most easily identified by the presence of "Align" as the second item. (Currently alignment is a feature that only applies to multiple clips, though there has been some discussion (#2789) of ways it could be made useful for single clips as well.) 

That's _meant_ to be true regardless whether you're holding down any keys, and for the **most** part it is — with one small exception that I'll explain in a moment. (That exception would still qualify as a bug, though, IMHO.)

The other context menu you describe, with the Copy option containing submenus of different types of clip parameters (Effects, different sets of Keyframes, etc...), is only _intended_ to be displayed when a single clip is selected, because we don't currently support copying parameters from more than one clip at a time. (TBH I don't see how that could ever be supported, it's a nonsense action that would have no possible "correct" effect.)

So, you should never see _that_ single-clip context menu, if you have multiple clips selected.

The one time it **DOES** have the potential to appear even though multiple clips are selected is _immediately_ after the second clip has been added to the selection. If the user follows their <kbd>Ctrl</kbd>-click with an immediate right-click, the context menu won't yet have been reconfigured for multiple clips, and the single-clip context menu will be shown. But that appears to be true whether or not <kbd>Ctrl</kbd> is also held down; it's about the timing of the click, not the modifier key.

But after that first incident, or after enough of a delay (less than a second) for OpenShot to catch up to the fact that the selection contains multiple items, right-clicking with _or without <kbd>Ctrl</kbd> reliably brings up the multi-clip, "Align"-containing version of the context menu.

Let me know if what you're seeing differs from my explanation, but my testing seemed to pretty reliably play out as I've described here.

And, like I said, the "delay" in the context menu adapting to multi-selection is definitely still a bug.

**Comment by ferdnyc** [comment]
ARRRGH. No, OK, it's _slightly_ more stupid than that. Wow, this is pretty silly.

It turns out, there's no time limit to how long the single-item context menu will come up, with or without control, if you follow the <kbd>Ctrl</kbd>-click that added it to the selection with subsequent right-clicks on that same clip. (Again, with or without control.) Until you move off of that clip and right-click somewhere _else_ on the timeline, OpenShot will still act as if there's only one clip selected.

But move the mouse off of that second-added, multi-selected clip, and right-click on any _other_ clip (whether it's selected or not, whether you're holding <kbd>Ctrl</kbd> or not), and you'll get the multi-selection context menu. After that point, you can then get the same context menu right-clicking on the clip that was previously the problem, too — with or without <kbd>Ctrl</kbd> held down.

So, definitely more of a bug than I'd previously described. But, the workaround is simply to right-click some clip **other** than the last one you added to the selection. (Yeah, it also hits multi-selections of more than two clips. However many you select, right-clicking the last one after <kbd>Ctrl</kbd>-clicking it does not show the correct menu.)

**Comment by ferdnyc** [comment]
(Not that our <kbd>Ctrl</kbd>-selection logic works properly even if you _ignore_ this newly-discovered bug. It has several long-standing issues, including the fact that <kbd>Ctrl</kbd>-clicking on _selected_ clips fails to **UN**-select them. So, you can only ever add clips to a multi-selection, but not remove them. It's kind of a mess, honestly.)

**Comment by hb20007** [comment]
@ferdnyc Thanks for figuring out when it happens exactly, it's good to know the workaround while this issue exists.

**Comment by ferdnyc** [comment]
Reopening, this is still a bug and it still exists.

**Comment by ferdnyc** [comment]
_(_ @rexdx _added in #3619: )_

2.5.1 Win10

Open Openshot; import two media files; add both to timeline
Select one clip, so that it is outlined in red.
Right click the other clip, and choose Remove Clip
Both clips are removed.
In every other case I know in Windows (eg particularly the File Explorer), right click would deselect the first clip, and only the second clip would be removed.

Not a disaster, as it can be undone, but it is a fault I think, if the claim is 'easy to use'.
