### ISSUE TITLE
Video Corruption on Imported Blender RAW AVI

### ISSUE THREAD

**Issue by snetting** [OpenShot/openshot-qt#2917]
**Describe the bug**
Video Corruption on Exported Blender RAW AVI

**Steps to reproduce the behavior:**
1. Export RAW AVI from Blender
2. Import to OpenShot
3. Add clip to Track
4. Hit play (preview) or export video
5. Corruption appears mid way during playback.

This does not happen on every exported Blender RAW AVI but on the files it does, it happens consistently and at the same point.
The RGB colour channels appear to start playing back with significant offsets.

Problem files play back correctly with VLC and other video players, although VLC reports the index file is missing (always the case with Blender exports).

**Expected behavior**
A file exported from Blender should import and play as expected.   

**System Details**
- OpenShot Version: 2.4.4-dev2
- libopenshot Version:  0.2.3
- Platform: Linux-5.1.11-200.fc29.x86_64-x86_64-with-fedora-29-Twenty_Nine
- Processor: x86_64
- Machine: x86_64
- Python version: 3.4.3
- Qt5 version: 5.2.1
- PyQt5 version: 5.2.1
- Qt Detected Languages: ['en-GB']
- LANG Environment Variable: en_GB.UTF-8
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.4.4-dev2-1564785878-90a56104-f17a7ed4-x86_64.AppImage

**Log Files**
- http://logs.openshot.org/w3qoaw4aw3lc83p3tt7npbswiix8zcam/openshot-qt.zip
- http://logs.openshot.org/w3qoaw4aw3lc83p3tt7npbswiix8zcam/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
To be attached in Github

**Comment by snetting** [comment]
![openshot-pre-issue](https://user-images.githubusercontent.com/7632526/62422237-cad8ff80-b6b7-11e9-908d-d60fc0e1e522.png)
![openshot-post-issue](https://user-images.githubusercontent.com/7632526/62422239-ce6c8680-b6b7-11e9-83ac-d3c8076823ff.png)
The problem video file is >700MB compressed but can be made available if required.

**Comment by ferdnyc** [comment]
Hmmm. I'm afraid those screenshots aren't really helpful, since I have no idea what the video's _supposed_ to look like at that point.

But, a few questions:

* What are the parameters of your input file? resolution, frame rate, etc.
* Is your project profile in OpenShot set to the same parameters?
* Have you tried exporting the video as AVI Jpeg? Does it show the same errors?

> Problem files play back correctly with VLC and other video players, although VLC reports the index file is missing (always the case with Blender exports).

_**Is**_ it? I exported both AVI RAW and AVI Jpeg clips with Blender 2.79b (installed from RPM Fusion on Fedora 30), and VLC had no problems with those files. In fact, if I load them with `vlc --verbose=2 filename.avi`, the logging output includes:

> [00007f7f50015240] main input source debug: creating demux: access='file' demux='any' location='/var/tmp/logotest_raw0001-0020.avi' file='/var/tmp/logotest_raw0001-0020.avi'
> [00007f7f50c27dd0] main demux debug: looking for demux module matching "avi": 55 candidates
> [00007f7f50017390] avi stream debug: <list 'AVI '>
> [00007f7f50017390] avi stream debug: <list 'hdrl'>
> [00005644f54b16f0] dbus interface debug: Getting property Metadata
> [00007f7f50017390] avi stream debug: <list 'strl'>
> [00007f7f50017390] avi stream debug: </list 'strl'>0
> [00007f7f50017390] avi stream debug: </list 'hdrl'>0
> [00007f7f50017390] avi stream debug: skipping movi chunk
> [00007f7f50017390] avi stream debug: </list 'AVI '>0
> [00007f7f50017390] avi stream debug: no more data at 55299084
> [00007f7f50017390] avi stream debug: * LIST-root size:55299084 pos:0
> [00007f7f50017390] avi stream debug:     + RIFF-AVI  size:55299076 pos:0
> [00007f7f50017390] avi stream debug:     |   + LIST-hdrl size:2004 pos:12
> [00007f7f50017390] avi stream debug:     |   |   + avih size:56 pos:24
> [00007f7f50017390] avi stream debug:     |   |   + LIST-strl size:116 pos:88
> [00007f7f50017390] avi stream debug:     |   |   |   + strh size:56 pos:100
> [00007f7f50017390] avi stream debug:     |   |   |   + strf size:40 pos:164
> [00007f7f50017390] avi stream debug:     |   |   + JUNK size:1804 pos:212
> [00007f7f50017390] avi stream debug:     |   + LIST-movi size:55296404 pos:2024
> <b>[00007f7f50017390] avi stream debug:     |   + idx1 size:640 pos:55298436</b>
> [00007f7f50c27dd0] avi demux debug: AVIH: 1 stream, flags  <b>HAS_INDEX MUST_USE_INDEX </b>
> [00007f7f50c27dd0] avi demux debug: stream[0] rate:1000000 scale:100000 samplesize:0
> [00007f7f50c27dd0] avi demux debug: stream[0] video(    ) 1280x720 24bpp 10.000000fps
> 

I don't know that that's _definitely_ the issue, but it's certainly _possible_ that loading an unindexed file is causing the issues you're seeing.

Regardless, one option would be to use something like  [avidemux](http://avidemux.sourceforge.net/) or [HandBrake](https://handbrake.fr/) to convert the AVI RAW video to a better-supported format, like x.264 MP4 or MKV. Then you shouldn't have any issues with missing indexes, and OpenShot may handle the file better.

I converted my tiny (20-frame) Blender AVI RAW test export into a 10-bit H.264 MKV using HandBrake, and not only did the video still look pristine, but the file size was reduced from 56 MB to 109 Kb. (Those numbers and units are not typos. :grinning: )

**Comment by ferdnyc** [comment]
Oh, and I forgot to also mention:

In order to analyze the AVI RAW issue itself, we'll probably need logs of the export process with debugging turned on, to see if libopenshot logs any messages of value while it's processing those frames.

The instructions for collecting logs in debug mode can be found [in the User Guide](https://www.openshot.org/static/files/user-guide/contributing.html).

**Comment by SuslikV** [comment]
@ferdnyc the header of the Guide that has info about the "debug mode" is named: `Please download our latest daily installer`.

**Comment by snetting** [comment]
The video shown in the screenshot is only a spinning green cube.  The second screenshot shows (what should be) the same image but with what appears to be huge RGB offsets.   On playback (in OpenShot) it randomly flicks between the correct and offset images.   When I have time I'll try the suggestions above and report back. Thanks for the update.

**Comment by mikelacsa** [comment]
@snetting are you still experiencing this issue after using the latest daily build?

**Comment by mikelacsa** [comment]
No response 7 days after being labeled "needs info". Closing the issue.
