### ISSUE TITLE
Remove mandatory '#' from HTML color fields (2.2.4 Windows)

### ISSUE THREAD

**Issue by DaddyWarcrimes** [OpenShot/openshot-qt#2920]
This is but a minor inconvenience and point of confusion. 

**Describe the new feature:**

In title editor, text color and background color HTML hex values should not require user to input '#' in the first position.

**Describe the solution you'd like:**
Field should allow '#', or appropriate hex characters to be entered in the first position of the field. If the first character is not '#', it should automatically add it on loss of focus.

**Describe alternatives you have considered:**
or
2. Make '#' permanent in the field and not allow user to delete it.
or
3. Have the '#' in the field title (e.g. "HTML: #") 
or
4. Issue a clear warning when the user tries to enter inappropriate characters (e.g. "the first character in this field must be '#'").
or
5. Remove the '#' entirely and only allow hex characters.

![Capture](https://user-images.githubusercontent.com/4444646/62437351-672af280-b708-11e9-9127-73bfe9d64c2b.PNG)

**Comment by SuslikV** [comment]
Color picker is part of the Qt (third party software used in OpenShot).
Standard dialog in Windows has no this field at all.
The enhancement requires custom Qt widget to be implemented - it will take a lot of effort to be done. I don't think that this needs any attention from the developers of the OpenShot.

Similar Qt issue:
https://bugreports.qt.io/browse/QT3DS-3275

**Comment by ferdnyc** [comment]
Yeah, we have absolutely no control over that dialog, it's Qt-standard.

I'm actually surprised at the way they implemented it. Since the field is for an "HTML" color value, you'd _expect_ that any format would work — including `rgba(255,255,255,1)` or even just "`white`", if you wanted the color `#ffffff`. But the only alternative form that actually does work is `#fff`.

However, if _they_ hadn't constrained the field, and allowed truly free-form input, it **could** actually work like that. So, that's actually a good demonstration of the dangers inherent in making assumptions about your users' input.

Regardless, closing because the request is beyond our ability to fulfill, sorry.

**Comment by DaddyWarcrimes** [comment]
Thanks all the same.
