### ISSUE TITLE
Interlaced video import or export not supported (displayed/encoded as Progressive)

### ISSUE THREAD

**Issue by lucaetere** [OpenShot/openshot-qt#2922]
![adva](https://user-images.githubusercontent.com/53849689/62596139-9c576080-b913-11e9-81be-17a8d4345b0a.png)
advanced tab property bug

export file 29.97 hd interlaced (59.94I),mpeg2
but the result file is Progressive!!!

even if I clicked on interlaced =YES on adavnced tab of the export file window

**System Details**
- OpenShot Version: 2.4.4

- Platform: Windows2016 std

**Log Files**
included and uploaded

**Comment by lucaetere** [comment]
moreover

it did not embed the CC eia-708 from the source file

**Comment by ferdnyc** [comment]
At least on the face of it, confirmed. Exporting a project set up with the "HD 1080i 25fps (1920x1080)" profile — set in both the project and the Export dialog's Simple tab — and using the "MP4 (h.264)" target, results in an output video with Progressive, non-interlaced frames, when checked with MediaInfo.

Caption embedding, I don't believe we support, sorry. But the field order thing is most definitely a bug.

**Comment by ferdnyc** [comment]
Tried switching to "AVI (mpeg4)" and "AVI (mpeg2)" as the target, no change. Still a Progressive-scan output video.

**Comment by ferdnyc** [comment]
Looping in @jonoomph and @eisneinechse, because after a quick grep through the `libopenshot` code, I am not finding _any_ code that would seem to handle interlaced output in `FFmpegWriter`. 

Like, **at _all_**. 

...Can that possibly be right?

**Comment by ferdnyc** [comment]
@lucaetere also provided this screenshot, showing an imported video with interlaced fields being interpreted as Progressive-scan by OpenShot.

![62604176-10046800-b92a-11e9-9688-19e83fafa9ac](https://user-images.githubusercontent.com/538020/62635506-d02b8980-b905-11e9-91c5-2e6a53ff5710.png)

**Comment by ferdnyc** [comment]
To be honest, @lucaetere , I suspect it's been so long since anyone's even tried to use interlaced video with OpenShot, that at some point support for it broke and you're just the first one to notice.

**Comment by lucaetere** [comment]
I see @ferdnyc , interlaced video are a standard in TV broadcast. and this is the usage I would do of this software.
Hope this may be fixed soon
Thanks

**Comment by ferdnyc** [comment]
> I see @ferdnyc , interlaced video are a standard in TV broadcast.

In like the 1980s! :laughing: (No, I know it is still used, though it's much less common since full-HD broadcasts and digital streaming became commonplace.)

> Hope this may be fixed soon

I wouldn't want to get your hopes up for "soon", to be perfectly honest. Especially since it's been broken for... well, a long time, anyway. I'm not sure interlaced export _ever_ worked. And so far it's only come up twice in three years.

(It looks like I was wrong about yours being the **first** report about it, looking at #482 — though I'm not sure the nature of the report was fully understood at the time, since the user kept referring to "deinterlaced" video when they wanted to output _interlaced_ video.)

**Comment by eisneinechse** [comment]
Unfortunately I am still not quite back to speed but that should be fixed and I will look into that.
Unlike North-America HD was not (is not?) fast established in Europe because the improvement in quality between PAL and HD is far less obvious as between NTSC and HD. (Well, I like the 30Hz or 30000/1001 Hz way better than 25 Hz because of the stress for the eyes). I am no longer living in Europe so I can't really say how common PAL still is but I wouldn't be surprised if it is still everywhere. Therefore, interlace might still be very important.

**Comment by ferdnyc** [comment]
I am happy to leave that in your capable hands, for whenever you're able! Certainly the best chance @lucaetere has of getting a timely resolution on this. Thanks.

**Comment by lucaetere** [comment]
Hello is this problem fixed?
thanks

**Comment by ferdnyc** [comment]
@lucaetere Nope, as you can see PR #312 is still open (un-merged). And that only addresses the import side of things, @eisneinechse has been unavailable lately and hasn't gotten to look at the export side.
