### ISSUE TITLE
Creating a new Preset

### ISSUE THREAD

**Issue by cminghao** [OpenShot/openshot-qt#2924]
Having seen the presets available in OpenShot, I would like to know if it is possible to adapt MXF files to xml or create new presets for use in OpenShot to allow for more options and flexibility on the video exports? however, being new to this I do not know if its possible due to the libraries/codecs that are used.

**Comment by ferdnyc** [comment]
@cminghao 

I know next-to-nothing about the MXF file format other than what you'd glean by reading the Wikipedia article about it (as I just did), but FFmpeg supports demuxing of the MXF container and as you can see from the last screenshot in #2922 MXF import is working. (_interlaced video_ import appears to be broken, but that's a separate issue and not confined to MXF.)

As far as extending export to add flexibility, in general that's not the easiest prospect, for a number of reasons. Some of those are bad and/or fixable, some are beyond our control. One of the biggest beyond-our-control reasons is the structure of ffmpeg itself. because ffmpeg is itself a modular library (collection of libraries, really), even though it _seems_ like it can do "anything and everything" and is highly flexible, the reality is that its own configuration is highly specialized and exactly the opposite of flexible. 

Here's just one example:

Trying to create an AVC/AAC interlaced-scan test file with command-line `ffmpeg`, so that I could import it into OpenShot and confirm the import bug in #2922, a few minutes' googling finally led me to the `-x264opts tff=1` command line option. All of my _other_ attempts (`-field_order tt`, `-vf setfield=tff`, `-vf interlace=merge`...) failed to work, because when encoding H.264 ffmpeg uses `libx264`, and it has its own option for encoding interlaced video — an option that only applies when using the output video codec `libx264`, and won't work for any of the other codecs!

So, even implementing support for something as ostensibly-generic as interlaced video output potentially requires special-casing of the parameters for _each_ individual codec. (And explains why our support for interlaced video export is broken, since the special-case processing for _that_ option doesn't appear to be present in `libopenshot`.)

I'd love it if OpenShot supported a "generic" configuration where you could add "basically anything" to the export parameters, and have those parameters apply even if they're not directly supported and the export code knows nothing about them. That'd make our lives _so much easier_! 

But because:
* ffmpeg's is extremely quirky, in terms of configuration
* it's three levels removed from the user (openshot-qt → libopenshot → ffmpeg)
* its response to _invalid_ options, typically, is to **crash** (even if they're perfectly valid in other situations!)
* OpenShot prioritizes user-friendliness over technical flexibility

the export configuration process is an unexpectedly complex beast, and _each_ supported option usually requires quite a bit of code to implement that support, unfortunately.

(Integrating that code into OpenShot itself can also, at times, become a somewhat [contentious](https://github.com/OpenShot/openshot-qt/pull/2860) process. But that's a separate issue.) 

Sorry, got a bit long-winded, but I hope it's some help in answering your question. Let me know if there's anything that isn't clear or that I didn't cover, or feel free to close this issue if you have everything you need.

**Comment by lucaetere** [comment]
Hello @ferdnyc 
below 6 profiles MXF (5 interlaced,1 progressive) tested via command line, that we would like to insert into OpenShot, is that possible?


-ProfileHR_1_Id=MPEG_30  (imx30  mxf wrapper)
-ProfileHR_2_Id=MPEG_50  (imx50  mxf wrapper)
-ProfileHR_3_Id=XDCAM-HD_50mbps_720p_50   (mxf)
-ProfileHR_4_Id=XDCAM-EX_35mbps_1080i_50  (mxf)
-ProfileHR_5_Id=XDCAM-HD_50mbps_1080i_50  (mxf)
-ProfileHR_6_Id=XDCAM-HD_35_50i           (mxf)

-ProfileHRVideo_1_Cmd=-vcodec mpeg2video -r 25 -pix_fmt yuv422p -b: 30000k -intra -flags +ildct+low_delay -dc 10 -rc_init_occupancy 2000000 -rc_buf_aggressivity 0.25
-ProfileHRAudio_1_Cmd=-acodec pcm_s24le -ar 48000 -ac 2
-ProfileHRVideo_2_Cmd=-vcodec mpeg2video -r 25 -pix_fmt yuv422p -b: 50000k -intra -flags +ildct+low_delay -dc 10 -rc_init_occupancy 2000000 -rc_buf_aggressivity 0.25
-ProfileHRAudio_2_Cmd=-acodec pcm_s24le -ar 48000 -ac 2
-ProfileHRVideo_3_Cmd=-vcodec mpeg2video -f mxf -pix_fmt yuv422p -vtag xd5c -b:v 50000k -minrate 50000k -maxrate 50000k -bufsize 8000k -bf 2 -non_linear_quant 1 -flags +ildct+ilme -top 1 -dc 10 -intra_vlc 1 -qmax 3 -lmin "1*QP2LAMBDA"  -rc_max_vbv_use 1 -rc_min_vbv_use 1 -g 1
-ProfileHRAudio_3_Cmd=-acodec pcm_s24le -ar 48000 -ac 2
-ProfileHRVideo_4_Cmd=-vcodec mpeg2video -f mxf -pix_fmt yuv420p -b:v: 35000k -minrate 35000k -maxrate 35000k -bufsize 8000k -bf 2 -non_linear_quant 1 -flags +ildct+ilme -top 1 -dc 10 -intra_vlc 1 -qmax 3 -lmin "1*QP2LAMBDA" -rc_max_vbv_use 1 -rc_min_vbv_use 1 -g 12
-ProfileHRAudio_4_Cmd=-acodec pcm_s24le -ar 48000 -ac 2
-ProfileHRVideo_5_Cmd=-vcodec mpeg2video -f mxf -pix_fmt yuv422p -vtag xd5c -b:v 50000k -minrate 50000k -maxrate 50000k -bufsize 8000k -bf 2 -non_linear_quant 1 -flags +ildct+ilme -top 1 -dc 10 -intra_vlc 1 -qmax 3 -lmin "1*QP2LAMBDA"  -rc_max_vbv_use 1 -rc_min_vbv_use 1 -g 12
-ProfileHRAudio_5_Cmd=-acodec pcm_s24le -ar 48000 -ac 2
-ProfileHRVideo_6_Cmd=-vcodec mpeg2video -f mxf -pix_fmt yuv422p -b:v: 35000k -minrate 35000k -maxrate 35000k -bufsize 8000k -bf 2 -non_linear_quant 1 -flags +ildct+ilme -top 1 -dc 10 -intra_vlc 1 -qmax 3 -lmin "1*QP2LAMBDA" -rc_max_vbv_use 1 -rc_min_vbv_use 1 -g 12
-ProfileHRAudio_6_Cmd=-acodec pcm_s24le -ar 48000 -ac 2

**Comment by lucaetere** [comment]
-b:

**Comment by lucaetere** [comment]
✌️   = : v  with no space obviously

**Comment by ferdnyc** [comment]
I've got you on that, GitHub Flavored Markdown syntax for fenced code blocks (similar to HTML PRE) is a line of three \` characters before and below. I'll edit your comment to protect the text.

**Comment by ferdnyc** [comment]
Bah. Of course, now it's not wrapped. :stuck_out_tongue_closed_eyes:

**Comment by lucaetere** [comment]
Hi, can we have an update over this?
thanks

**Comment by lucaetere** [comment]
any update ?
