### ISSUE TITLE
My video transformation slowly resets as the video moves on,

### ISSUE THREAD

**Issue by TheBlaziking** [OpenShot/openshot-qt#2926]
**Describe the bug:**

**Steps to reproduce the behavior:**

**Expected behavior:**

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.
Log files can be found in your HOME/.openshot_qt/ folder. Please compress or zip
the log files (as they can become quite large).

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please
attach a small snippet of the exception here, but please keep it as small as
possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them here, dragging-and-dropping into this form, or clicking below and loading
images saved to your computer. All images are public, so please don't post screenshots
containing personal information.

**Comment by SuslikV** [comment]
Your transformation starts far earlier then you think. You need to look at all green or blue color properties of the selected object in Timeline: each blue means that property is animated, each green means that the new value of animation was set exactly in this place (frame) - this is animation key.

**Comment by TheBlaziking** [comment]
So how do I fix it from regenning itself over time? Since it only has happened on one video out of four I edited and I don't know why,

**Comment by ferdnyc** [comment]
@TheBlaziking 

If a clip's parameters change over time, it's due to the fact that there are multiple Keyframes set on the video at different points along its runtime.

I have to make a few assumptions here about what you're _intending_ to do, since there isn't a lot of detail in your report. So, apologies if I get anything wrong, and please do correct me so that we can more fully understand your situation and help you better. 

1. It sounds like your intention is to set up Transform parameters at the start of a clip, and have them remain static for as long as it's on screen?

1. In order to do that, you need to make sure that you apply the Transform to the very **first** frame of the clip, and that it's the **only** frame where any of those parameters are set.

1. If the parameters are drifting, then as @SuslikV said there must be another keyframe set somewhere later in the clip, which would be indicated by a small green mark along the bottom edge of the clip.

1. Regardless, it's not really important that you _locate_ it, since it's probably quickest to simply remove any extra keyframes. This _will_ also remove your initial Transform setting, so you'll have to apply it again, but doing it this way will guarantee there won't be any drift. Here's what you do:

    1. Click on the clip to select it. You'll see the locations of any keyframes appear as those green marks along the bottom edge.
    1. Position the Playhead (red line) at the very _first_ frame of the clip. The easiest way to do that is, after you've selected the clip, use the Previous Marker / Next Marker arrows on the Timeline toolbar, or their keyboard shortcuts (<kbd>Ctrl</kbd>+<kbd>←</kbd> / <kbd>Ctrl</kbd>+<kbd>→</kbd>, by default), to position the playhead at the left edge of the clip. It'll snap to either end of the selected clip.
    1. Open the clip's menu, and choose Layout > Reset Layout. That will clear away _all_ keyframes for positioning/sizing (Transform) parameters and reset the clip to its initial default position.

1. Now, if you reapply your Transform settings with the playhead positioned at the first frame, and _only_ there, the settings will apply for the entire length of the clip and there won't be any drifting.

The most important thing to remember is: _always_ make sure you know where the playhead is positioned when making any parameter adjustments to your clips. Adjustments will always be applied at the current playhead location. If it isn't on the first frame, then you'll be creating an animated transform, which sounds like it's not what you want. (But if you ever do want that, now you'll know how to make it happen!)

**Comment by ferdnyc** [comment]
(Technically the playhead can also be positioned anywhere _before_ the first frame of a clip, and adjustments will be applied to the first frame. So, some people just leave the playhead sitting all the way at the start of the timeline when they make their adjustments. While that does work, I don't recommend it, since it's too easy to get careless about positioning that way. Better to get in the habit of **always** checking — even double-checking! — that the playhead is positioned on the frame you want to adjust, even when it's the first frame.)

**Comment by TheBlaziking** [comment]
I move my playhead as I edit though, that's how I noticed what it's doing. Plus it's only happened on the one video so far, isn't there just a way to lock your transformations once done?

**Comment by ppoffice** [comment]
I tried to add multiple "freeze" timing effect on a slice and this issue also happens to me. My previous edits are all messed up when I open the same project for the second.

**Comment by mikelacsa** [comment]
@ppoffice can you send us your system details please? Also, log files will greatly help fix this issue. Can you send us a fresh copy of your log files? Follow the instructions from this link:

https://www.openshot.org/issues/new/

**Comment by ppoffice** [comment]
@mikelacsa I'm sorry I uninstalled OpenShot a long time ago and the log files are not available anymore. This problem occurs both under Windows 10 and Ubuntu 18.10, and I think it has to do with OpenShot's design but not the system. I think this is related to the issue discussed here: https://github.com/OpenShot/openshot-qt/issues/1438#issuecomment-385132805

**Comment by mikelacsa** [comment]
I see. Thanks @ppoffice
