### ISSUE TITLE
Slice not frame accurate

### ISSUE THREAD

**Issue by lucaetere** [OpenShot/openshot-qt#2927]
- OpenShot Version 2.4.4]

tried to slice 1 file (actually many)  with bars at start and at bottom. ( bars +video content+ bars or titles)
Result file contains 2 unwanted frames at mark in and 2 at mark out.

**Comment by lucaetere** [comment]
If logs are needed i can reproduce the issue. But you can replicate easily.

**Comment by ferdnyc** [comment]
@lucaetere 

Logs likely aren't necessary, at least not at this point.

First question: Is your project set up with a project profile that matches the frame rate of the input video? Slice (like all of OpenShot) will work at the frame rate configured for the project, so if you're importing video at a different frame rate and trying to slice it, the mismatching frame rates will definitely throw things off.

Beyond that, OpenShot's current slicing code includes a bit of wiggle room that @jonoomph  introduced because ffmpeg itself can't always be relied on for strict frame accuracy, especially working with compressed video (as most of our users are). Frame-accuracy is a hard thing at the best of times. (You can read the saga of my own encounters with the slicing code [starting from this comment](https://github.com/OpenShot/openshot-qt/pull/1384#issuecomment-373998661) on my old PR #1384.) OpenShot makes no promises about strict frame accuracy.

If you're working with _uncompressed_ video, as I believe you are, it's entirely possible that the "wiggle room" I mentioned in the slicing code is also _sabotaging_ the frame-accuracy for your videos. FFmpeg probably **could** be relied upon to be frame-accurate, when editing broadcast-format media, but we don't trust it to be since most of the time the input is compressed video from consumer-level codecs, where frames tend to be all over the place regardless.

Our primary audience isn't the broadcast industry, though, so optimizations and concessions have been introduced that may work counter to the needs of that audience. I can't say I personally feel that's the wrong decision, although it wasn't my decision.

**Comment by SuslikV** [comment]
@ferdnyc to be honest, if there is issue with slicing then it definitely algorithm issue. I couldn't imaging that Adobe for example can say that it is normal thing for their soft. Also, OpenShot never do lossless edit - it always works with uncompressed frames. When user preview the image at slicing point - there only one frame. Steps to reproduce the issue is important anyway.

**Comment by ferdnyc** [comment]
> @ferdnyc to be honest, if there is issue with slicing then it definitely algorithm issue.

Then feel free to fix the algorithm and prove me wrong.

> I couldn't imaging that Adobe for example can say that it is normal thing for their soft. 

Nor can I. Pay me $17 million, it won't be normal in OpenShot, either. Otherwise, that comparison is meaningless.

> Also, OpenShot never do lossless edit - it always works with uncompressed frames. When user preview the image at slicing point - there only one frame. Steps to reproduce the issue is important anyway.

Yes, but it _retrieves_ those frames from ffmpeg, and sometimes the frame requested is **not** the one it produces. That was my conclusion after extensive testing, see (again) [this comment](https://github.com/OpenShot/openshot-qt/pull/1384#issuecomment-373998661) and following ones for the whole story. (Or jump right to the conclusions outlined in detail at [this comment](https://github.com/OpenShot/openshot-qt/pull/1384#issuecomment-374603337).) Adobe also doesn't use ffmpeg to drive their decoder, and like I said there, ffmpeg _itself_ doesn't promise strict frame accuracy, especially when decoding compressed video using a consumer codec that's not designed for editing, which is the type of input OpenShot is primarily designed to accommodate.

**Comment by ferdnyc** [comment]
(The difference between slice preview and the results of a slice operation is, the preview shows the results of the stream decoded from the first frame. When the slice is performed, the start frame of the clip is _moved_ to that frame, which can sometimes have the side-effect of changing what frame appears at that point in time. From my conclusions-comment:

> Even if I _manually_ adjusted the Start parameter of a clip, and explicitly _**typed in**_ a Start value of "0.80" seconds exactly, the clip would start with frame 19 when it should be 20. "0.76" would also get me frame 19, and "0.84" would get me frame 21. Consistently, _every_ time. I could get it to show me frame 20 by typing in "0.81" or "0.82" or "0.83", but for that particular video, never "0.80". 
> 
> (If I started the video from frame 1, then at 00:00:00:20 on the timeline sure enough it _would_ show me frame 20. Ditto if I started it from 0.76s and moved one frame forward. It was only when the starting point was exactly where frame 20 was _supposed to_ be, that it showed me the earlier frame. ...And frame 20 is only an example, BTW. This happened with some other frames as well, but so far I haven't been able to detect a pattern.)
> 
> So, that's where I'm at with that. It seems like the frames coming in from the decoder are just sometimes not where they should be. Which... maybe it is, maybe that's the nature of the beast. I mean, `ffmpeg` itself makes no bones about it. In its manpage, the start-position flag `-ss` is documented thusly (emphasis mine):
> 
> > When used as an input option (before "`-i`"), seeks in this input file to position. **Note that in most formats it is not possible to seek exactly,** so ffmpeg will seek to the closest seek point before position.  When transcoding and `-accurate_seek` is enabled (the default), this extra segment between the seek point and position will be decoded and discarded. When doing stream copy or when `-noaccurate_seek` is used, it will be preserved.

**Comment by SuslikV** [comment]
> ...and explicitly _**typed in**_ a Start value of "0.80" seconds exactly,..

I, personally, never tried to insert time into OpenShot and even I don't know what format is (I have some guess of course, but only pro users can use this right). It is so unintuitive, that I hardly believe that user opened this thread have been used this method of addressing.

I'm not going to proof you or anybody, if I'll find a solution I will make PR to share it.
And I think, Adobe didn't start from $17 million ^_^

**Comment by lucaetere** [comment]
Hello

> _First question: Is your project set up with a project profile that matches the frame rate of the input video?

YES

> _If you're working with uncompressed video

My Video is NOT uncompressed is wrapped in MXF

FFMpeg can retrieve the start time and end time with frame accuracy when transcoding a new file. I know and I use other SDK that do let me do it.

This feature is very basic and must be accurate. How can I extract a scene from a videoclip if the result file will have the first frames of the previous one?

I am not comparing this software with Adobe, I need this bug fixed, because we are talking about a bug.
thanks

**Comment by SuslikV** [comment]
Probably, you are not using latest build of OpenShot or your FFmpeg is not 4.x (linux user?).

**Comment by lucaetere** [comment]
I use ver 2.4.4, is there any other build? like a nightly or a beta?
I am a Windows user

**Comment by SuslikV** [comment]
Daily Builds button: https://www.openshot.org/download/

**Comment by lucaetere** [comment]
I retested with different files and formats, using the 2.4.4 official (no daily build), slicing is almost ok.
It is ok for MP4, it takes my settings, like bitrate and start time , end of mark is +1 frame.
For mpeg2 it never applies the custom settings (like bitrate)
Moreover , my first file tested a 1080i59.94@29.97 fps with CC608 embedded still is wrongly sliced. So i assume the issue is limited to some kind of files (ntsc with cc embedded) )

**Comment by mikelacsa** [comment]
@lucaetere are you still experiencing this issue?

**Comment by lucaetere** [comment]
export For mpeg2 it never applies the custom settings (like bitrate)
for mp4 is almost accurate, not frame acurate
can you do a test using Mpeg2 and change the custom settings?

**Comment by mikelacsa** [comment]
Have you tried it with the latest daily build?

**Comment by mikelacsa** [comment]
@lucaetere Have you tried it with the latest daily build?

**Comment by johnmendonca** [comment]
I seem to have a similar problem.  I am editing just one file, cutting out sections and combining the remaining sections.  At each junction point, there is a flash of one frame, and that frame is the very first frame from the source video (same as the thumbnail showing in the timeline).  If I could just make that frame black instead that would be fine with me.

I am on Linux Mint 20 (ubuntu) using the 2.5.1 AppImage and ffmpeg 4.2.4

Here is the info from the source file via ffmpeg:

```
Input #0, matroska,webm, from '2020-07-28.mkv':
  Metadata:
    ENCODER         : Lavf58.29.100
  Duration: 02:31:36.02, start: 0.113000, bitrate: 2503 kb/s
    Stream #0:0: Video: h264 (High), yuv420p(progressive), 1280x720 [SAR 1:1 DAR 16:9], 29.97 fps, 29.97 tbr, 1k tbn, 59.94 tbc
    Metadata:
      VARIANT_BITRATE : 2602481
      DURATION        : 02:31:36.020000000
    Stream #0:1(eng): Audio: aac (LC), 48000 Hz, stereo, fltp (default)
    Metadata:
      COMMENT         : English
      DURATION        : 02:31:35.922000000
```

**Comment by InklingGirl** [comment]
This still seems to be the case.
