### ISSUE TITLE
Can't import PNG image sequence at all

### ISSUE THREAD

**Issue by nijiawen** [OpenShot/openshot-qt#2947]
**Describe the bug:**
When I try to import a sequence of images as a clip, I get the "...is not a valid video, audio, or image file" error. I've tried making sure the first file number is less than 100 (currently, it's "p080.png"); trying different file formats (JPG, direct from camera then image magick mogrified to 1440x1080; camera RAW converted to PNG in RawTherapee, then again mogrified for file size; and JPG direct from camera with no resizing); and different versions of Openshot (2.4.3 and 2.4.4). Also, a different sequence of images from the same camera opens as an image sequence just fine. The files all seem just fine when I open them in an image viewer, and it's a little hard to believe that three different image processing paths all resulted in images that my image viewer shows as fine but which Openshot can't handle. This also worked fine in even earlier versions of Openshot.

**Expected behavior:**
Image sequence should be properly recognized and imported as a clip.

**System Details:**
- OpenShot Version 2.4.3 and 2.4.4
- Operating System / Distro: Linux Mint 19.1

**Comment by ferdnyc** [comment]
@nijiawen 

I haven't looked at the image sequence code in a while. (To be perfectly honest with you, it's not my favorite feature, as I feel it's clunky and fragile... as you've discovered.) It appears, from some quick testing right now, that while OpenShot will _recognize_ an image sequence as long as the starting index is < 100, sequences still effectively have to start at 0/1 or the import attempt will subsequently fail. If you have OpenShot running in a terminal, such that its STDERR is visible, you'll see an error message from FFmpeg on the console, e.g.:

> `[image2 @ 0x558199663580] Could find no file with path '/var/tmp/testframes/frame%02d.png' and index in the range 0-4`

So, the solution is simply to renumber all of your image files to be 0- or 1-based. Since you're on Mint this should be fairly easy. I'm sure there's a clever way to do this all in one go, but I don't feel like thinking of it right now and this will serve. I'd suggest using it on a copy of your image files in a separate directory, just in case.
```sh
for num in $(seq 0 9); do mv p08${num}.png p00${num}.png; done
for num in $(seq -w 090 179); do mv p${num}.png p0$((num - 80)).png; done
for num in $(seq 180 999); do mv p${num}.png p$((num - 80)).png; done
```

That'll renumber `p080.png` through `p999.png` as `p000.png` through `p919.png` respectively; you can adjust the stopping point (`999`) if your sequence ends earlier.

**Comment by ferdnyc** [comment]
(The starting-index flexibility in OpenShot is so that, if you have the sequence `p000.png` through `p090.png`, the sequence will be discovered whether you choose `p000.png`, `p007.png`, or `p087.png` as the import file. But it doesn't change that the _first_ file still has to be `p000.png` – `p004.png`, for FFmpeg to recognize it.)

**Comment by ferdnyc** [comment]
I'm going to close this, as the issue was with the numbering of the files (which is out of our control, since it's an FFmpeg limitation), and renumbering should solve the problem. Feel free to reopen if it doesn't.
