### ISSUE TITLE
openshot audio error please fix the following error and restart OpenShot The input and output devices don&#39;t share a common sample rate! (Give your bug report a descriptive title)

### ISSUE THREAD

**Issue by rrxjuggler** [OpenShot/openshot-qt#2957]
**Describe the bug**
OpenShot Launch Error

Produces the messages at launch time:

openshot audio error please fix the following error and restart OpenShot The input and output devices don't share a common sample rate!

**Steps to reproduce the behavior:**
1. Launch OpenShot
2. See error

**Expected behavior**
OpenShot should launch without error

**System Details**
- OpenShot Version: OpenShot-v2.4.4-dev2-1566992561-f8c180c1-f17a7ed4-x86_64
- libopenshot Version:  0.2.3
- Platform: Windows-10-10.0.16299
- Processor: Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.4.4-dev2-1566992561-f8c180c1-f17a7ed4-x86_64.exe

**Log Files**
- http://logs.openshot.org/be0c0cas20m4sza8jxajsve22emkffna/openshot-qt.zip
- http://logs.openshot.org/be0c0cas20m4sza8jxajsve22emkffna/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by ferdnyc** [comment]
@rrxjuggler This is generally-speaking a system configuration error: it means that the Windows Audio settings for your input and output audio device don't match. I can only give you the process to fix it in Windows 7 because I don't have access to a Windows 10 machine, but hopefully it's somewhat similar. 

In Win7, right-clicking on the volume control in the system tray would let you open a list of "Playback devices" or "Recording devices", each list has a default device and each device has a Properties window. In the Advanced tab of that window is the setting for the "Default Format" of the device, and if those formats don't match you'll see that error when starting OpenShot. Here are the Properties for the "Speakers" playback device and "Line In" recording device on a Win7 machine, for example:

![image](https://user-images.githubusercontent.com/538020/63995575-06a09280-cac7-11e9-8732-0275e69f454d.png)

Changing either device's Default Format to match the other one would clear up this error.

Same issue as #2820, but not really a duplicate because the conditions are different.

**Comment by ferdnyc** [comment]
(I've decided it really is a duplicate, ultimately, at least from our perspective.)

**Comment by rrxjuggler** [comment]
That was exactly the problem and it works great now. Thanks so much!

**Comment by ferdnyc** [comment]
I've applied a patch to the JUCE audio library that's reported to fix this issue, and Daily Build versions starting from the Nov. 13 2019 builds should no longer have this problem. The new installers:

* https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.4.4-dev2-1573705363-c2713520-12a15298-x86_64.exe
* https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v2.4.4-dev2-1573705361-c2713520-12a15298-x86.exe
