### ISSUE TITLE
When you close your project, the default titlename can be overwrite existing files from the project before you closed it

### ISSUE THREAD

**Issue by rohezal** [OpenShot/openshot-qt#2961]
When you save, close your project, the default titlename can be overwrite existing files from the project before you closed it.

I added the timestamp to the default title name to avoid overwriting it by accident.

openshot_qt/windows/title_editor.py

import time

Change Line 214:

self.txtFileName.setText(_("TitleFileName-%d") % i)

to

self.txtFileName.setText(str(int(time.time())) + "-" +
_("TitleFileName-%d") % i)

**Comment by ferdnyc** [comment]
Hmm. I'm trying to understand what's getting overwritten where. The title editor _attempts_ to protect against filename clashes (though it could probably do it in a better way, TBH.)

Can you provide steps to reproduce the _problem_? Then we can try to find a solution that covers all cases.

**Comment by rohezal** [comment]
Can I just upload a file I made? My use case is educational videos- If you want to reproduce it:

Don't name any titlename, just use the default name.

Create a new project. Add some titles over some images / videos. Save the project. Close the application. Open the application, add more image and more titles. Save and close the project. Now you should have overwritten the old titles.

Maybe you keep the counter how often you have created a new title in RAM and if you close the program you close it, it resets to 1? 

I would recommend use a timestamp by default and maybe set the default file name to the text of the title, if no title is provided.

**Comment by ferdnyc** [comment]
@rohezal 

Uggggh. OK, now I think I'm beginning to understand. You're talking about the case where you save _multiple_ project files to the same directory, say `/tmp/all_my_OSPs`. 

If those projects both contain title files with the same filename, e.g. `TitleFileName-1.svg`, then they will both save that title file into the same `/tmp/all_my_OSPs/assets/` directory, and when the second project is saved, **\*bam\***, there goes the title file for your first project. Silently and without warning, no less.

Yeah, that's bad. That's **very bad**. And I suspect it could potentially become bad for more things than just the title SVG files, too — some time in the future, if not today. (Not the Blender dirs, they're generated from UUIDs. But, should the statistical nigh-impossibility occur that two projects generate the same thumbnail file name, now one of them's got a wrong thumbnail because that too got trampled.)

The **_real_** problem, ultimately, is the shared asset directories. Projects' files shouldn't get thrown together just because they happen to be saved to the same directory. 

I think, rather than timestamping the SVG filenames, what I'm going to do is take a page from Audacity with its `filename.aup` + `filename_data/...` storage model — except, the OpenShot data dir for `filename.osp` will be called `filename_assets`, to avoid any possible clashes with same-named Audacity projects.

So, in the new model, two OpenShot projects saved to `/tmp/all_my_OSPs/` would be stored like this:

* `/tmp/all_my_OSPs/project1.osp`
* `/tmp/all_my_OSPs/project1_assets/`
    * `/tmp/all_my_OSPs/project1_assets/TitleFileName1.svg`
    * `/tmp/all_my_OSPs/project1_assets/thumbnail/`
        * `/tmp/all_my_OSPs/project1_assets/thumbnail/T455452.png`
* `/tmp/all_my_OSPs/project2.osp`
* `/tmp/all_my_OSPs/project2_assets/`
    * `/tmp/all_my_OSPs/project2_assets/TitleFileName1.svg`
    * `/tmp/all_my_OSPs/project2_assets/thumbnail/`
        * `/tmp/all_my_OSPs/project2_assets/thumbnail/TAF78ED.png`
    * `/tmp/all_my_OSPs/project2_assets/$SOME_BLENDER_UUID/`
        * `/tmp/all_my_OSPs/project2_assets/$SOME_BLENDER_UUID/animated_title_name.py`

...and so on.

No more separate `thumbnail` and `assets` dirs with no obvious relationship to the project files that generated them, no more commingling and potential collisions for different projects' asset files. I think it'll just be cleaner all around. And loading old projects with the old layout will be no problem, they'll just get stored into the new directory layout the next time they're saved.

CC: @jonoomph
