### ISSUE TITLE
track's thumbnail is missing.

### ISSUE THREAD

**Issue by cminghao** [OpenShot/openshot-qt#2966]
I was loading a project from a translated path of a shared network folder when I realized if I were to attempt to load a project that was saved in the folder of the translated path the thumbnail that should show up in the track disappeared. If I were to transfer the project onto my desktop and try to open it from there it shows me that the video file that is in the project is missing and proceeds to enter a loop of asking me to find a file that isn't anywhere.

**Comment by cminghao** [comment]
I thought the issue was fixed but apparently seems to be a weird bug that appears inconsistently.

**Comment by ferdnyc** [comment]
@cminghao Yeah, unfortunately right now moving project files from one disk location to another does not work correctly. #2976 is the first step of an effort to try and change that, though that PR alone is not a complete fix. And, in fact, I'm concerned there could even be new issues introduced, when dealing with network shares. (Mostly because the code is currently untested in those environments. In fact it's currently untested on Windows, period.)

But I'm interested in figuring out what may be causing the _existing_ code to fail, in your environment. Most likely there's a bad assumption in the code, or something we failed to account for when working with network paths.

What currently happens (or is supposed to happen) with project files is
1. On save, OpenShot's working files for things like thumbnails, title SVGs, and blender animations are copied to the same location on disk where the project file is being stored. 
    
    If you save a project file as `C:\Temp\MyVideo.osp`, the thumbnail directory for the project will be copied to `C:\Temp\thumbnail`, any title SVGs will be copied to `C:\Temp\assets\`, and any Blender output directories (which are named with GUIDs) are copied to `C:\Temp\`.
    
1. As this is done, the paths in the project data for any files in the temporary directory are updated to the new locations. Interestingly enough, though, this _doesn't_ include the thumbnail paths — exactly the ones you're having trouble with. Those are always assumed to be relative to the user's `.openshot_qt` directory. (Hence the next step.) 
    
1. When `C:\Temp\MyVideo.osp` is loaded again, the directory `C:\Temp\thumbnail` (that is, a directory `thumbnail` with the same parent directory as the `.osp` file) is looked for, and if it exists, any existing `%USERDIR%\.openshot_qt\thumbnail` is deleted and `C:\Temp\thumbnail` is copied in its place.

I would've guessed that the third step, the copying of the `thumbnail` dir from the save location back into the `.openshot_qt` directory, is the one that's failing. But you say that the _project file_ **can** be saved on the network share, as long as the import file is local? That's quite confusing, because import file paths shouldn't really affect thumbnail handling. ("shouldn't")

Specific details would be helpful. Honestly right now it's hard for me to even know what questions to ask, especially as I don't have access to a system where I could replicate an equivalent setup. If you could provide logs from OpenShot after loading a project file where the thumbnails don't get restored, that may be helpful. (See https://github.com/OpenShot/openshot-qt/blob/develop/CONTRIBUTING.md for instructions, but please **don't** turn on debug mode.)

I'd also be curious to see/know:
* An `.osp` file that contains media files imported from a network path, to see how they're being stored in the file
* whether a `thumbnail` directory is actually created at the location of the project file, when the project is saved to a network share
* what the contents of that `thumbnail` folder are
* whether those contents are transferred back to `%USERDIR%\.openshot_qt\thumbnail` on project load

**Comment by cminghao** [comment]
@ferdnyc after a few days of testing the things I have observed are as follow:
a thumbnail folder with the related thumbnails is created at the folder at which the project is saved at, in it consists of the thumbnail of the file tree as well as track, however upon opening the project the track's thumbnail goes missing despite all the thumbnails being copied correctly into the .openshot/thumbnail folder, HOWEVER there are cases which the track's thumbnail do not actually go missing and open up as intended but the number of times this occurs seems to be completely random(which probably is not, I just can not seem to pinpoint the reason it happens) and uncommon. There are also times when opening the project the thumbnails of the file tree copies correctly but the track's thumbnail is not copied, simply manually copy-pasting the thumbnail fixed the issue instantly but this only occurred once or twice throughout all my testing.

while trying to figure out if it is a code issue I checked out the import file thumbnail's path to double checked if it saved the correct path. It did, there was no issue with the saving of the project, the path of the thumbnail was correct, even upon opening of the project the path was accurate, yet for some reason the track's thumbnail does not show up, while the project was open I checked the path and there was no change.

Having thought that the issue was the translated pathing, I tried to change the code to reflect the thumbnail in .openshot/thumbnail but the thumbnail does not show up either, however if the thumbnail is generated on load then I didn't really expect it to show up as i tried that method after the load as I do not know if it is possible to specify the location of .openshot/thumbnail before it is created. But it brings me back to the one time I was able to copy-paste the thumbnail and got it to show up in the project, not entirely sure if it actually happened as I was unable to recreate the situation.

But since the file tree's thumbnail is able to load in every situation I am quite confused as to why this happens, if the reason was the inability to read the translated file path (\\folderA\B) then technically the file tree's thumbnail should not be able to load as well, since it does load I am kind of forced to assume that the issue is the track's inability to somehow read the file path and retrieve the required thumbnail.

I tried playing around with the codes and attempted a force reload of the track's thumbnail after the load and changing of the thumbnail into the one that the file tree uses, it did not work although I could not figure out if it was due to the code or it just does not work even when reloaded.

The only reliable work around I found was to copy the project and thumbnail folder with the related thumbnail into a folder on the local disk and open the project from there. That allowed for everything to open smoothly and correctly.

I am sorry, I am unable to post logs due to certain reasons.

**Comment by ferdnyc** [comment]
@cminghao 

Thanks for the info.

The only difference I can think of that may be relevant is, when copying the thumbnails _out_ to the project folder, we create the directory using `os.mkdir`, then use a file glob to individually copy each file with `shutil.copy`:
https://github.com/OpenShot/openshot-qt/blob/4431bd5c0af4ca705b4e958c193513be749e6bf3/src/classes/project_data.py#L787-L793

But then when copying the files back _into_ the local cache, we just grab the entire directory with `shutil.copytree`:
https://github.com/OpenShot/openshot-qt/blob/4431bd5c0af4ca705b4e958c193513be749e6bf3/src/classes/project_data.py#L365-L373

The difference between those two methods may explain why the copy-out works, but the copy-in is unreliable. Perhaps there's some sort of permissions issue, or it could simply be that Python's `shutil.copytree` is unreliable when copying from network shares on Windows.

PR #2976 currently doesn't change anything about the project-file _**loading**_ process, so if that's the part that's failing then it's unlikely the PR will improve things unfortunately. However, @jonoomph is working on a new method of managing thumbnails in general (that's less dependent on copying thumbnail caches everywhere), so if that pans out then hopefully this will no longer be an issue.

There's also the fact that `shutil.copytree` uses `shutil.copy2` as its copy function, by default — it's possible we'd get better results until `shutil.copyfile`, which doesn't attempt to preserve any metadata or file attributes from the source file in the destination. That's an easy enough change to make, too.

I don't know if you're even tracking this anymore @cminghao , but if you'd be willing to test a very small change:
```diff
diff --git a/src/classes/project_data.py b/src/classes/project_data.py
index 053e8221..bc52b479 100644
--- a/src/classes/project_data.py
+++ b/src/classes/project_data.py
@@ -370,7 +370,7 @@ class ProjectDataStore(JsonDataStore, UpdateInterface):
                 shutil.rmtree(info.THUMBNAIL_PATH, True)
 
                 # Copy project thumbnails folder
-                shutil.copytree(project_thumbnails_folder, info.THUMBNAIL_PATH)
+                shutil.copytree(project_thumbnails_folder, info.THUMBNAIL_PATH, copy_function=shutil.copyfile)
 
             # Add to recent files setting
             self.add_to_recent_files(file_path)

```
(In other words, add `, copy_function=shutil.copyfile` to the `shutil.copytree()` that imports the thumbnail files from the network path.)

I'm curious whether that would make any difference.
