### ISSUE TITLE
Openshot 2.4.4 incorrectly exports vertical video

### ISSUE THREAD

**Issue by sknaumov** [OpenShot/openshot-qt#2969]
**Describe the bug:**
Vertical video looks very small, with big black frames around all edges. Original video has black frames only from left and right of the video and looks about 2 times bigger.

**Steps to reproduce the behavior:**
1. Create custom profile with the following content:
```
description=Vertical 1080p 30fps
frame_rate_num=30000
frame_rate_den=1001
width=1080
height=1920
progressive=1
sample_aspect_num=1
sample_aspect_den=1
display_aspect_num=9
display_aspect_den=16
```
2. Change OpenShot profile to the custom one, restart OpenShot.
3. Import original video into new project.
4. Export video with default settings.

**Expected behavior:**
Get the same video as original one.

**System Details:**
- OpenShot Version 2.4.4
- Windows 10

**Screenshots:**

Original:
![vlcsnap-2019-09-03-01h03m47s966](https://user-images.githubusercontent.com/1166661/64134464-c9017980-cde6-11e9-8eaf-a7a0374bf124.png)

Exported from OpenShot with default HD 1080p 1920x1080 profile.
![vlcsnap-2019-09-03-01h12m46s894](https://user-images.githubusercontent.com/1166661/64134611-1205fd80-cde8-11e9-88e5-e64bae2acb0e.png)

Exported from OpenShot with custom vertical profile:
![vlcsnap-2019-09-03-01h02m56s763](https://user-images.githubusercontent.com/1166661/64134468-d0c11e00-cde6-11e9-856a-3c134ab3bad5.png)

**Comment by SuslikV** [comment]
Try to save your project file (.osp) and then load it again (use new empty folder for the project's file).

**Comment by sknaumov** [comment]
@SuslikV Just tried it. Unfortunately, it doesn't work, even if empty directory is used to save the project file.

**Comment by sknaumov** [comment]
It looks like I found the root cause: video file that came from my Huawei P30 has 1920x1080 dimensions even though it is oriented vertically. Somehow VLC and other media players still open it properly, but OpenShot can't detect this irregularity. I reencoded the file using `ffmpeg.exe -i Orig.mp4 -vf scale=1080:1920 Out.mp4` and now I see proper video preview and proper exported video.

Could OpenShot automatically detect and apply a workaround for such cases?

**Comment by SuslikV** [comment]
Short file sample is needed to test it out (about 2 seconds is well enough).

**Comment by sknaumov** [comment]
Sample video attached.

[VID_20190904_105737.mp4.gz](https://github.com/OpenShot/openshot-qt/files/3573389/VID_20190904_105737.mp4.gz)

**Comment by SuslikV** [comment]
Without linked changes I can't find suitable workaround. (you can apply changes manually, just locate required file in your application's folder).

More over even if you apply the changes to `classes/project_data.py` you still need to perform next additional steps:
1. Make sure that clip is added to the _Timeline_
2. Set scale property of the selected clip to _None_
3. Resize (scale up or down) the _Video Preview_ window by mouse - actual area of the movie should resize, not only window background. You may make the window float to drag it by the corner
4. The image should update to cover the whole window.

There were number of optimization in the rendering code, so it wasn't well tested and this caused the problem.

**Comment by ferdnyc** [comment]
> It looks like I found the root cause: video file that came from my Huawei P30 has 1920x1080 dimensions even though it is oriented vertically. Somehow VLC and other media players still open it properly, but OpenShot can't detect this irregularity. I reencoded the file using `ffmpeg.exe -i Orig.mp4 -vf scale=1080:1920 Out.mp4` and now I see proper video preview and proper exported video.
> 
> Could OpenShot automatically detect and apply a workaround for such cases?

In a _sense_ it does, in that if you import a vertical video in typical phone/tablet format (which is a horizontal video with metadata that defines an initial rotation), OpenShot will detect that and import the video already-rotated. (So, the video will load with `Rotation = 90.0`, for example.)

The problem is that a horizontal video rotated 90° isn't _really_ the same thing as a video with swapped dimensions. OpenShot's rotation _in general_ is currently quite naive, and doesn't account for how rotation (any rotation) alters the dimensions of the video image.

Even though the video is rotated, it still has `width = 1920` and `height = 1080` instead of vice versa, and OpenShot makes decisions for things like scaling based on the _unrotated_ dimensions. That's why if you load a vertical video into a horizontal profile, the top and bottom are cropped off. But if you load it into a vertical profile, it only occupies around half of the frame.

If your output profile is the same size as your input video, as @SuslikV indicated setting `Scale = None` _can_ prove a reasonable workaround. (And with PR #2975 merged to fix that render-setup bug, it'll even preview properly. Though even in OpenShot 2.4.4, the preview is only wrong initially. If you move the playhead around — or even better, move the _clip_ around to force OpenShot to regenerate all of the cached preview frames — it sorts itself out.)

Still, it would be far better if libopenshot was smarter about rotation and how it affects the source video, which is the focus of OpenShot/libopenshot#322.

**Comment by SuslikV** [comment]
@ferdnyc I'm going to fix some _Preview File_ bugs (so that it start acting same to the regular _Video Preview_) first. That will show number of optimization assumptions that was just dead code and do nothing good. I think these changes will be important, because the Painter transform related on geometry of the source and its currently visible size. Issues are not only in rotation but in whole transform. I need a bit more time for it to complete. Then, it would be nice to see new actual transform formulas and calculations.

**Comment by sknaumov** [comment]
@SuslikV BTW, maybe it deserves standalone issue, but I also had problems with inaccuracy of exported video dimensions when tried to merge it wtih 1080x1920 picture. You can see it at the very end of my resulting video when transformation from video to picture is in progress. IIRC I had to use 1082x1920 picture to minimize the effect and make it appear on up/down edges. With 1080x1920 picture the issue was on the left edge: https://www.youtube.com/watch?v=R6NvCqXmVJg

**Comment by ferdnyc** [comment]
@sknaumov You're talking about the very end section, where it fades from video to the title card?

![image](https://user-images.githubusercontent.com/538020/64485516-db692200-d1ef-11e9-8875-b477fa4e6302.png)

I'll be honest, I've gone over that fade several times, using different YouTube views, even at half speed, and I'm not really seeing the issue. So I guess it minimized pretty well! (Or I'm blind.)

If your image is exactly the size of your output frame, though, it's probably worth trying `Scale = None` on the image, as well. Especially when combined with a video that uses larger dimensions. (Because remember, OpenShot still thinks the video is `1920 × 1080`.) OpenShot's auto-scaling may be messing itself up in that kind of situation. 

But, using a slightly-larger-than-frame image as a workaround makes a lot of sense (and would be the next option anyway, if `Scale = None` failed), good call on that.

**Comment by SuslikV** [comment]
@ferdnyc I think, he says about two bright horizontal lines (1-2 pixels height) at top and at the bottom of the image, when transition is almost complete (you can notice that this bright lines is just background video that is still running behind the black image with the text that simply covers the video). YouTube player shades the top and bottom of the footage when playback controls are active, thus it is harder to notice them when you looking for it :)

**Comment by ferdnyc** [comment]
Ah, OK. I do see that. (Viewing the video in non-theater mode (which is actually better for vertical video, size-wise) didn't help either, since it uses a white background.) Maybe 2px on the top, and not even a full 1px on the bottom — it's more like half a line of pixels, at the bottom left edge.

The interesting thing about that is, I'd expect a `1082 x 1920` image to _cause_ the problem, more than _minimize_ it, since with `Scale = Best Fit` OpenShot would typically scale the image to be slightly shorter than `1920px` tall. I'm curious what the `1080x1920` image looked like. (Or maybe it showed lines on the _sides_, instead?)

Yeah, I'm definitely leaning back towards `Scale = None` as a first choice. `Scale = Stretch` _might_ also work, but if it distorted the image at all, text tends to look _really_ bad when it deforms due to non-uniform scaling.

There's also another, simple workaround for the issue (not that it wouldn't be better to solve it, of course): If the title card were placed on the track _below_ the video, and then the video faded **out** instead of the title card fading in, that would eliminate any bleed-through from under the image.

**Comment by sknaumov** [comment]
Yes, exactly, with 1080x1920 picture I had vertical bright line from the video on the side.

I created the picture using GIMP.
