### ISSUE TITLE
Feature to save as transition, animation properties for importing it later

### ISSUE THREAD

**Issue by darshitvvora** [OpenShot/openshot-qt#2971]
**Question:**
Is there a way to save properties of a video and reapply later to other project by importing it?

**Comment by ferdnyc** [comment]
@darshitvvora Not as such, no, sorry.

Depending what properties you're talking about, one possibility might be to flip things around in how you approach it:

1. Start by loading the _old_ OpenShot project, containing the clips that have properties you want to duplicate
2. Import your _new_ file(s) into that project and place them on the timeline
3. Use the Copy options in the context menu of the old clip(s), to duplicate whatever properties you want to reuse (You can Copy either Effects, or various groups of Keyframes.)
4. Paste those properties onto your _new_ clip(s)
5. Remove any old files from the timeline, and from the Project Files
6. Save the project under a new name

That'd effectively achieve the same thing, or as close as is currently possible with OpenShot.

**Comment by darshitvvora** [comment]
@ferdnyc  - Thanks for the workaround. But this seems little tedious to do. I am looking for saving the properties set in properties tab of any video, audio, image or transition. If there would have been a button to export and save property of file and restore it later than it would be much much useful. It would be great if we can ad this feature

**Comment by ferdnyc** [comment]
> @ferdnyc - Thanks for the workaround. But this seems little tedious to do. I am looking for saving the properties set in properties tab of any video, audio, image or transition. If there would have been a button to export and save property of file and restore it later than it would be much much useful. It would be great if we can ad this feature

The problem is that each clip's properties are specific to the clip in question, as well as to the project configuration under which they're created.

You certainly wouldn't want to copy item-specific parameters like duration, start/end time, etc. from one clip to another. Nor would many of the other configurable properties (scaling, transformation, etc.) be applicable to a clip that has different specifics, or to a clip in a project that's configured for a different profile. 

(An example: If your clip contains keyframes at `00:00:09` and `00:00:10` seconds that set up a 1-second-long fade to black, that's great when you're working with a clip that's 10 seconds long. But it wouldn't be very useful to apply those same keyframes to a 5-second clip. Or to a 20-second clip.)

I'm not really clear on precisely what data you _would_ like to export, but doing it in a way that could subsequently be applied to a clip in a different project would likely be a much more complex task than it may initially seem.
