### ISSUE TITLE
Make sure copied files actually have write permissions in ~/.openshot-qt

### ISSUE THREAD

**Issue by peti** [OpenShot/openshot-qt#2972]
openshot-qt copies all kinds of Python or SVG files into a temporary location, i.e.`~/.openshot_qt/blender/8f9c347a-ce4e-11e9-b006-a4c3f0b51071/lens_flare.py`. Now, on the NixOS those files are installed with `0444` permissions. The originals have no `+w` bit -- and consequently the copy lacks that permission and cannot be used properly by the edit. This trivial problem breaks the title generator on NixOS, among other things (https://github.com/NixOS/nixpkgs/issues/48591).

Would you consider adding code into oneshot-qt that simply performs a `chmod u+w` on the newly created temporary file after copying it?

**Comment by ferdnyc** [comment]
@peti The interesting thing is, we're not creating that file as a copy of the source. We're reading the source file into memory, then writing it out to a newly-created file. If that's being created read-only, I suspect it probably has something to do with the umask on your system. (Out of curiosity, are the `.png` files created by Blender also read-only?)

Whatever the reason, I've submitted #2973 with a change to explicitly set write permission on the generated `.py` file after it's created. That should hopefully ensure that the file is made writable on all three OSes.

**Comment by ferdnyc** [comment]
Here's a download link for an AppImage build of OpenShot with the change from #2973 included — would you be able to give that a try, and confirm that it solves the permission problem?

https://drive.google.com/open?id=13gApYowpKKmJkJQ5W0vq3VROmCGPxg3P

You may have to do a `chmod +x OpenShot-v2.4.4-dev2-1567520928-f8c180c1-f17a7ed4-x86_64.AppImage` on the downloaded file, to be able to run it.

**Comment by ferdnyc** [comment]
I should mention, the change in #2973 only affects the Blender `.py` scripts, currently. The SVG titles, those **are** created as copies. But if this works for the `.py` files, the same fix should work for them as well.

**Comment by ferdnyc** [comment]
Aagh! Never mind, I was wrong. We _do_ copy the file first, before modifying it.

But that actually makes things even easier, we can use Python's `shutil.copyfile()` instead of `shutil.copy()`, to copy the file _without_ duplicating its permissions. Ignore that AppImage, I'm going to update the PR to fix both the animated and still title file copying.

**Comment by ferdnyc** [comment]
OK, #2973 should now fix both the `.svg` files and the `.py` files. Don't worry about testing it, though, as the AppImage won't be a valid test anymore ­— its template files are most likely not set read-only.

However, if you want to attempt a local fix, the fix is as simple as changing `shutil.copy()` to `shutil.copyfile()` in both `openshot_qt/windows/views/blender_listview.py` and `openshot_qt/windows/title_editor.py` in your OpenShot install.

**Comment by peti** [comment]
I applied the patch in NixOS (https://github.com/NixOS/nixpkgs/commit/d7bbcdf274eaa3de1f813f391b64626b2f87bc49) and the new version appears to work fine. Thank you very much for the quick fix!

**Comment by ferdnyc** [comment]
Glad to hear that worked! Reopening this only because the fix hasn't gone in yet on _our_ end; GitHub will auto-close when the PR gets merged.
