### ISSUE TITLE
removing the end time in the properties

### ISSUE THREAD

**Issue by Foadsf** [OpenShot/openshot-qt#2974]
in the properties section, there is a `duration` property which is not editable and an `end` property which actually is the duration. It makes sense to remove the noneditable duration. and then have one `start` (rename `position`) and one `duration` (or `end`) both editable.

**Comment by ferdnyc** [comment]
@Foadsf 

I'd have to disagree with that. All of the properties are useful in their own way, at least in certain circumstances. You've also wrongly stated the meaning of some of the properties:
* **`Start`**: The starting point of the clip _within the source video_. Will often be `0.00`, unless the starting frame has been adjusted to a later point.
* **`Position`**: The location on the timeline where the clip's starting point is located.
* **`Duration`**: The length of the clip on the timeline, computed by subtracting `Start` from `End`. Not directly modifiable, because it's adjusted by moving either `Start` or `End`.
* **`End`**: The end point of the clip _within the source video_. Will be equal to `Duration` only when `Start` is `0.0`. Will be equal to `Position` + `Duration` only when _both_ `Position` and `Start` are `0.0`.

Dragging the clip's left edge modifies `Start`. Dragging the right edge modifies `End`. Either will also modify `Duration`. Dragging the entire clip left or right on the track modifies `Position`.

**Comment by ferdnyc** [comment]
(The reason that you'd want to be able to see the `Duration`, even though you can't edit it directly, is: Sometimes you need to crop a clip or some music out of a larger file, to fill a certain length of time. You might want it to _start_ from a certain point, or the important thing might be that it _ends_ at a certain point, but above all it has to be a certain length. So, after setting either `Start` or `End` to the chosen point, you'd want to see the duration as you adjust the other end of the clip to make it fit.)

**Comment by Foadsf** [comment]
I think if the `duration` were editable it would be more comfortable. The stupid thing is that I hadn't seen `start` at all 🧐. My bad. On a side note sorting the properties alphabetically is not the most intuitive. I would put the relative properties next to each other in a retractable subcategory. Like Blender does. 


**P.S.1.** I followed you on Twitter. Would be great if you were more active there.
**P.S.2.** I became a mini Patreon of OpenShot yesterday. Thanks for your great work. ❤️

**Comment by ferdnyc** [comment]
> I think if the `duration` were editable it would be more comfortable. 

Personally I'm not **completely** opposed to the idea (though I don't know what @jonoomph or the other developers' take on that would be), my only concern is what exactly editing `Duration` should imply? Because it changes as the _result_ of so many other actions, which one of those should the user expect to happen when they edit it directly? Does it change the `End` value, or the `Start` value, or even the speed of the clip? 

(Our current facilities for changing clip speed are woefully inadequate as it is, so it's unlikely `Duration` edits could be tied to that. But, that's what some users would probably expect.)

Right now our property relationships are pretty well-defined (if maybe not always completely _obvious_), there's really not much ambiguity or multiple possible interpretations of an edit even where other properties change as a side-effect. 

I think editable `Duration` would have to be accompanied by some facility for "freezing" certain properties, so that they wouldn't be modified when changing others. Which would be great to have, sure — patches welcome!

> On a side note sorting the properties alphabetically is not the most intuitive.

I don't disagree with you there, they could use some sort of grouping or categorization. The properties are supplied by libopenshot, the OpenShot frontend pretty much just takes whatever it gets handed back and loads it into the Property List table. It'd be better if libopenshot provided more structure. It's also not a priority, unfortunately.

**Comment by Foadsf** [comment]
Another point is that the `end` property does not represent the end position, but the duration!

**Comment by ferdnyc** [comment]
@Foadsf 

Not true. Like I said:
> * **`End`**: The end point of the clip _within the source video_. Will be equal to `Duration` only when `Start` is `0.0`.

**Comment by ferdnyc** [comment]
`End` is important because sometimes you have a raw source clip with a lot of extraneous footage, but you know the "out" point for the segment you want to use is at a certain time index. (Maybe it's the end of an introduction to some other video, or something.) So you set `End` to that time, and then you can adjust the length as needed by moving the clip's `Start` time, and it'll still end on that "out" mark.

**Comment by ferdnyc** [comment]
I'm going to close this, since hopefully I've explained why we consider the End property to be useful / important. 

Editable Duration could still be filed separately as a feature request, though.

(The organization of the Properties table, there's definitely an open Issue already for that somewhere... though I apologize that I don't have a reference handy.)
