### ISSUE TITLE
Explain playhead/keyframe positioning better (see comment)

### ISSUE THREAD

**Issue by RationalMagic** [OpenShot/openshot-qt#2990]
(Original issue title: **Cannot Enable Audio of an Entire Clip**)

I cannot enable audio in the preview section of Openshot Video Editor. I am aware the steps to enable audio are: 
1) open clip properties 
2) set Enable Audio value to 1.
This method only enables audio during a single key frame of the entire clip, as if I were adding a transition effect that only lasts for a single frame. In all my searches I have not found a way to change the properties of an entire clip. This seems to work differently in version 2.4.4 of Openshot which I am running. Please help me resolve this incredible frustrating and simple issue.

**Comment by RationalMagic** [comment]
The issue resolved itself the 5th time I opened Openshot and tried doing the exact same thing...

**Comment by ferdnyc** [comment]
@RationalMagic I'm going to quote from the OpenShot manual, **NOT** as an "RTFM" sort of response, but more to reference something that _we_ need to highlight much more prominently, and do a better job of communicating in both (1) the documentation and (2) the interface. Because, issues like yours _almost_ always have the same solution:


(From [Clips > Properties](https://cdn.openshot.org/static/files/user-guide/clips.html#properties) in the [OpenShot User Guide](https://cdn.openshot.org/static/files/user-guide/index.html), emphasis added:)
> Below is a list of clip properties which can be edited, and in most cases, animated over time. To view a clip’s properties, right click and choose Properties. The property editor will appear, where you can change these properties. **Note: Pay close attention to where the play-head (i.e. red playback line) is. Key frames are automatically created at the current playback position, to help create animations.**

As I say, my point here is not that you should've known that, it's that it SHOULD be in flashing 2"-tall letters at the top of the Clips chapter, or something, rather than buried halfway down the page at the end of a paragraph.

The manual also fails to explain:
1. If you wish to set clip-**wide** properties, the adjustment needs to be made only at the **first** frame of the clip, which contains an implied keyframe for every one of the listed properties. As long as any property has **only** a single value set at the first frame, it will hold for the entire length of the clip. Adjusting a value anywhere _other_ than the first frame adds a second keyframe (the first being the implied one at the start), and at that point the property is interpolated between those two points.
2. Rather than "paying close attention" (what does that even _mean_?), you should **ensure** that you adjust clip-wide properties from the first frame of the clip, by selecting the clip and using the Previous Marker / Next Marker controls (either the arrows on the Timeline toolbar, or the <kbd>Ctrl</kbd>+<kbd>←</kbd> and <kbd>Ctrl</kbd>+<kbd>→</kbd> keyboard shortcuts) to move the playhead to the start of the clip. Both the left and right edges of the selected clip are treated as markers, and Previous Marker / Next Marker will seek the playhead to them.

As I said, that's _usually_ the source of this type of report, hope it helps. If you find it _doesn't_, and can reproduce the conditions under which something works incorrectly, please definitely let us know.

**Comment by ferdnyc** [comment]
I'm going to close this, since there's been no further response and I believe it's been answered. Feel free to reopen, though.

**Comment by ferdnyc** [comment]
Actually, I take that back, I'm going to tag it for documentation improvement.
