### ISSUE TITLE
Can't cancel rendering generation animation title

### ISSUE THREAD

**Issue by mouarfff** [OpenShot/openshot-qt#3001]
When i launch rendering animation title, i can't cancel it.

I must wait or kill the programm

**Comment by ferdnyc** [comment]
@mouarfff That's been fixed in the development code (81ad4b10), the fix is in the Daily Builds and will be part of the next OpenShot release.

(Note that the Daily Builds require upgrading to Blender 2.80, which is _not_ compatible with OpenShot 2.4.4. So, something to be aware of when considering a version switch.)
