### ISSUE TITLE
Cannot drag and drop a file from the project files into the timeline (Give your bug report a descriptive title)

### ISSUE THREAD

**Issue by Gaivotas** [OpenShot/openshot-qt#3027]
![Openshot](https://user-images.githubusercontent.com/42721253/66167246-7e675d00-e631-11e9-9b1b-305ed996b3b5.PNG)
**Describe the bug**
Cannot drag and drop a file from the project files into the timeline

**Steps to reproduce the behavior:**
1. Import mp4 file into the project files panel
2. Drag it into one of the tracks
3. While dragging you can see that the forbidden icon is shown while you are dragging the video. You can right click and add it to the tack and if I press play I can see the video but don't see it in any of the tracks.

**Expected behavior**
Be able to drag a file into one of the tracks

**System Details**
- OpenShot Version: 2.4.4-dev2
- libopenshot Version:  0.2.3
- Platform: Windows-7-6.1.7601-SP1
- Processor: Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.4.4-dev2-1570002441-b7c96ffe-f17a7ed4-x86_64.exe

**Log Files**
- http://logs.openshot.org/2j0tbc6gt6f5lczhja3x10pybsh15mt5/openshot-qt.zip
- http://logs.openshot.org/2j0tbc6gt6f5lczhja3x10pybsh15mt5/libopenshot.zip

**Exception / Stacktrace**
**Screenshots** (Optional)
```No stacktrace found in log files```
![Openshot](https://user-images.githubusercontent.com/42721253/66167275-9939d180-e631-11e9-9c1a-54cd460462db.PNG)

**Comment by ferdnyc** [comment]
Hmm. There are a few odd things going on here.

The drag fails because:
```
  exceptions:ERROR Unhandled Exception
Traceback (most recent call last):
  File "C:\Program Files\OpenShot Video Editor\windows\views\timeline_webview.py", line 2666, in dragEnterEvent
    self.addClip(data, pos)
  File "C:\Program Files\OpenShot Video Editor\windows\views\timeline_webview.py", line 2732, in addClip
    top_layer = int(self.eval_js(JS_SCOPE_SELECTOR + ".GetJavaScriptTrack(" + str(position.y()) + ");"))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
I'm guessing, if JavaScript isn't returning a value, then it's probably being called with an empty trying, which means `position.y()` is most likely `None`. But why that's happening on this drag... uncertain.

Then the automated error tracking fails to properly record that exception, because:
```
     metrics:INFO Track exception: [200] http://www.openshot.org/exception/json/ 
| *failed-recording-exception*: Control/space characters not allowed 
(key=b':1:Windows-2.4.4-dev2-TypeError: int() argument must b')
```
So we don't even get data when this happens, looks like.

Then, later, when the project file is being saved:
```
   json_data:ERROR Error while converting absolute paths to relative paths:
 path is on mount 'D:', start on mount 'C:'
```

I'm honestly amazed _that_ hasn't come up sooner. I'm pretty sure it _used_ to work (it **must** have), but at some point apparently it broke. On Windows, it's impossible for some paths to be relative, because they're not on the same drive. It doesn't _look_ like that's what's breaking the drag, though, as it wouldn't be using relative paths.

Just in case, though, you might try moving your video file to the `C:` drive @Gaivotas. It's possible that will fix the drag & drop. (And if it does, please let us know, because we'll need to unbreak the drag handling.)

Oh, on this:

> You can right click and add it to the tack and if I press play I can see the video but don't see it in any of the tracks.

According to the logs, the file was added to `'layer': 5000000` (man, ambitious naming there), which corresponds to Track 5, the one _above_ the visible area in your screenshot. If you scroll up, are you sure it's not there? We haven't had any reports of clips being created on the timeline _invisibly_. I won't say it's not possible but I'd want to make really sure first.

**Comment by Gaivotas** [comment]
Thanks for your quick feedback.
In relation to:

> Just in case, though, you might try moving your video file to the C: drive @Gaivotas. It's possible that will fix the drag & drop. (And if it does, please let us know, because we'll need to unbreak the drag handling.)

I tried to move (and create a brand new project) to C: drive and I had the same issue, but while copying my working folder, the first thing I did was to open the file doing a double click, and... it worked as it should. Then I dug a bit more and created the following scenarios:

- Scenario 1
1.  From the Start->All Programs->OpenShot 
2. Add a video to the timeline (new project)
Result: Doesn't work the drag & drop, but if I right click the video and add it it works, but not visible in the timeline. I know that because I press play and it plays.

- Scenario 2
1. In the file explorer, double click on the file
Result: No problem, it works.

I tested both from C: and D: drives.

In relation to:
> According to the logs, the file was added to 'layer': 5000000 (man, ambitious naming there), which corresponds to Track 5, the one above the visible area in your screenshot. If you scroll up, are you sure it's not there? We haven't had any reports of clips being created on the timeline invisibly. I won't say it's not possible but I'd want to make really sure first.

Well, I can see the video in the timeline when opening the project with double click, otherwise nothing is shown.

**Comment by ferdnyc** [comment]
@Gaivotas Thanks, still digesting all of that, it's a strange problem. But new Daily Builds are being generated again, so I might be able to get you a build with more logging output if need be.

...One last test, if you don't mind?

Many people don't even realize you can do this in OpenShot, I've discovered, but: What if you drag a video file from the Windows Explorer, _**directly**_ onto OpenShot's timeline? Does that work?

(What's _supposed_ to happen: The file gets added to the timeline and placed on the Project Files list at the same time. So, that's the definition of "works", for this scenario.)

**Comment by Gaivotas** [comment]
Dragging from the Windows Explorer works fine as well, I can see the video in the project files & timeline. The definition passes the test.

**Comment by ferdnyc** [comment]
Huh. OK, that's interesting.

Well, I'm going to try to get some changes committed to the development tree, to at least fix that data-collection error on the traceback, and possibly do more useful logging of the _internal_ drag & drop process. Hopefully that'll give us a better picture of what's going on there.

While I'm getting that together, though: juuust for the sake of completeness, could I ask for _one_ last quick test? When you have a file that's been added by dragging from Explorer to the Timeline (so it exits, visibly and correctly, on both the Project Files list and the Timeline), what happens when you _then_ drag **that** file from Project Files to the Timeline? (Attempt to add a second clip of the same file.)

I'm expecting it probably won't make any difference (OpenShot still fails to execute the drag operation), but it would be really interesting if anything _was_ different.

**Comment by Gaivotas** [comment]
Sure.

Steps:
1. If I drag a video from the Windows Explorer into the timeline it words fine (as described before). 

2. Doing step 1. and then if I drag another instance of that video from the Project Files into the timeline again it won't work. 

3. Doing step 1, then trying to add another video to the Project Files and then add it to the timeline - work as well.

4. Dragging a video from the Windows Explorer into the Project Files and then drag it to the timeline - Doesn't work.

Let me know if you need more tests.

**Comment by Colorjet3** [comment]
This has been fixed since.
