### ISSUE TITLE
After download and installation on OSX 10.9, App will not start

### ISSUE THREAD

**Issue by pinnaclesystemsgroup** [OpenShot/openshot-qt#3032]
**Describe the bug:**
/Users/USER/.openshot_qt/libopenshot.log files not created

FSPathMakeRef(/Users/***/Applications/Open Video Editor.app) failed with error -43.

**Steps to reproduce the behavior:**
1. Download OSX daily build from website
2. Open downloaded .DMG file
3. Right click program icon on Applications folder (app does not start)
4.  Attempt to start app from command line using terminal
"open -a ~/Applications/Open\ Video\ Editor.app "

5. Program exits with error below:
FSPathMakeRef(/Users/****/Applications/Open Video Editor.app) failed with error -43.

**Expected behavior:**

App should open the initial video editor window

**System Details:**
- OpenShot Version 2.2.4: {{ log_context.openshot_qt_version }}
- Operating System MacOSX 10.9+
**Log Files:**
None created

**Exception / Stacktrace:**

**Screenshots:** (Optional)

**Comment by ferdnyc** [comment]
@pinnaclesystemsgroup 

Error 43 is "file not found", it _seems_ like `$HOME/Applications/OpenShot Video Editor.app` doesn't actually exist.

The filename is also wrong, at least in your step 4. (That may just be a typo here — but if it's not, then it would definitely be the problem.) The correct command should be:
```sh
open -a ~/Applications/OpenShot\ Video\ Editor.app
```

Just to clarify, you wrote:

> Right click program icon on Applications folder (app does not start)

...I'm not sure I'm following about the right-click, but what you're _meant_ to do is drag the OpenShot icon into the Applications folder. That will copy it from the DMG to your computer. ("Installing" it, as much as MacOS applications have an installation process.) Then it can be launched from your Applications folder.

Can you confirm that the icon for OpenShot is present when you open your Applications folder (without the DMG mounted)? And what happens if you click on it there?

**Comment by ferdnyc** [comment]
@pinnaclesystemsgroup 

Just wanted to get an update, are you still having troubles getting OpenShot to install?

**Comment by mikelacsa** [comment]
No response more than 7 days after being labeled "needs info". Closing ticket.
