### ISSUE TITLE
Bytewidth assertion error when importing a JPEG file

### ISSUE THREAD

**Issue by Zverik** [OpenShot/openshot-qt#3044]
**Describe the bug**
When adding a big JPEG file as an image sequence, OpenShot crashes with an assertion.

**Steps to reproduce the behavior:**
1. Open the app.
2. Right click in the media panel and import this jpeg: http://not.textual.ru/zverik/2/5/pres-0.jpg
3. Click "yes" on "import as sequence"

**Expected behavior**
The image is added to the media panel.

**System Details**
- OpenShot Version: 2.4.4-dev2
- libopenshot Version:  0.2.3-dev1
- Platform: Linux-5.3.5-200.fc30.x86_64-x86_64-with-fedora-30-Thirty
- Processor: x86_64
- Machine: x86_64
- Python version: 3.7.4
- Qt5 version: 5.12.5
- PyQt5 version: 5.13.1
- Qt Detected Languages: ['ru-RU']
- LANG Environment Variable: ru_RU.UTF-8
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.4.4-dev2-1570846513-febc2fbc-f17a7ed4-x86_64.AppImage

**Log Files**
- http://logs.openshot.org/hy11jdf90684iasift0xccpr2y4ewr9h/openshot-qt.zip
- http://logs.openshot.org/hy11jdf90684iasift0xccpr2y4ewr9h/libopenshot.zip

**Exception / Stacktrace**
```/lib64/libc.so.6               abort                                    0x127  [0x7f8afa634895]
/lib64/libavutil.so.56                                                  0x2a634  [0x7f8ae4caa634]
/lib64/libavutil.so.56                                                  0x2a8d0  [0x7f8ae4caa8d0]
/lib64/libavutil.so.56         av_image_copy                            0x54  [0x7f8ae4cab1c4]
/lib64/libopenshot.so.17       openshot::FFmpegReader::GetAVFrame()     0x187  [0x7f8ae66221d7]
/lib64/libopenshot.so.17       openshot::FFmpegReader::CheckFPS()       0xf8  [0x7f8ae6622d18]
/lib64/libopenshot.so.17       openshot::FFmpegReader::UpdateVideoInfo() 0x208  [0x7f8ae6623c68]
/lib64/libopenshot.so.17       openshot::FFmpegReader::Open()           0x113e  [0x7f8ae66253fe]
/lib64/libopenshot.so.17       openshot::FFmpegReader::FFmpegReader(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) 0x4e1  [0x7f8ae66279a1]
/lib64/libopenshot.so.17                                                0x3dd21  [0x7f8ae65bad21]
/usr/lib64/python3.7/site-packages/_openshot.so                                          0xdd6f5  [0x7f8ae67b76f5]
/lib64/libpython3.7m.so.1.0    PyCFunction_Call                         0x103  [0x7f8afa3cec93]
/lib64/libpython3.7m.so.1.0    _PyEval_EvalFrameDefault                 0x661e  [0x7f8afa43ea8e]
/lib64/libpython3.7m.so.1.0    _PyEval_EvalCodeWithName                 0x2f0  [0x7f8afa3ef080]
/lib64/libpython3.7m.so.1.0    _PyFunction_FastCallDict                 0x2ee  [0x7f8afa3f071e]
/lib64/libpython3.7m.so.1.0    _PyObject_Call_Prepend                   0x66  [0x7f8afa3c49c6]
/lib64/libpython3.7m.so.1.0                                             0x1362e3  [0x7f8afa3ff2e3]
/lib64/libpython3.7m.so.1.0    _PyObject_FastCallKeywords               0x117  [0x7f8afa4001c7]
/lib64/libpython3.7m.so.1.0                                             0x...

**Comment by ferdnyc** [comment]
Hmm... I'm confused, are you importing a _single_ image, or an image sequence? Are there other files in the same directory named `pres-1.jpg`, `pres-2.jpg`, etc...? Are those other files different _sizes_ (dimensions), by any chance?

If you actually want to import just a single image, you should click "No" when it asks if you'd like to import an image sequence, since when multiple images are imported as a sequence they're expected to all be individual frames of the same moving image.

It's _FFmpeg_ (`libavutil`) that's crashing, not OpenShot or even libopenshot, and my **guess** is that it's crashing because it was supplied with an invalid set of image sequence frames.

**Comment by Zverik** [comment]
Okay, I discovered what an image sequence is. I indeed have 39 images named `pres-0.jpg`, `pres-1.jpg`, ..., `pres-10.jpg` etc. They all have exact same parameters as the one linked: 3307×1860 8-bit. Three of them are 256-bit gray, others are sRGB. I've uploaded the whole directory to http://tile.osmz.ru/slides-openshot-test.zip

I realized I don't need to import a sequence and should have clicked "no" indeed. But this is still a bug, so I leave it here.

**Comment by ferdnyc** [comment]
@Zverik Thanks, the image archive was extremely helpful. 

I've tested and can confirm the crash, which as suspected is due to grayscale images being mixed in with the color ones. Removing or replacing those three images with equivalent 3-channel color files allows the set to be successfully imported as an image sequence.

While we'd _like_ to fix this, realistically I don't think we can. Detecting that the images don't all have the same number of channels (or that they're not all the same size, or don't match up in any of the other ways that matter) would require OpenShot to load and examine each of the images in the image sequence, which it does not do — it simply passes  the set of files to ffmpeg for processing.

That ffmpeg crashes on a malformed set is unfortunate, but largely beyond OpenShot's control I'm afraid. Perhaps it'll get fixed on the ffmpeg side of things, so mismatched frame lists are handled more gracefully.

**Comment by Zverik** [comment]
Thanks for researching the issue, Frank!
