### ISSUE TITLE
Semi-Automatic Snapping (Condensing) of Blank Gaps and Better Indication of Gaps

### ISSUE THREAD

**Issue by Twenkid** [OpenShot/openshot-qt#3057]
**Describe the new feature:**

(Semi-)Automatic Condensing (I see you call it "snapping") of segments without laborious select-drag-drop when blank gaps are present. That's important especially when the gaps are a few frames long and are visible only in big zoom or after rendering.

Possibly, a more easily visible marker on the timeline when there are gaps (e.g. a line with a contrasting color) or a view which shows the gaps only (in time or/and ~frames),

**Describe the solution you'd like:**
1. A button, a menu, selection of a region/set of segments to be condensed etc.
2. An option, when calling the rendering dialog, if blank gaps are present, to warn about them and offer solution.
3. A clear indication on the timeline or another view of the timeline displaying the blank gaps between segments (video, titles). At best the indication shouldn't be dependent on the zoom factor of the timeline, which is important especially for long videos with many segments. Also, more clear indication when there are overlapping segments without transition, which again sometimes happens 
 undesirably.

**Describe alternatives you have considered:**
The alternative is to carefully review the whole zoomed timeline for tiny gaps.

**Comment by ferdnyc** [comment]
Yeah, that's fair. I _wouldn't_ call _this_ "snapping" only because the snapping feature we already have (the blue line that appears when moving a clip near to the edge of another clip, or a marker position, or the playhead) **DOES NOT** prevent this issue, as you've discovered. (In a sense it's partly responsible for it.) Even with snapping enabled, two clips that are snapline-aligned in a zoomed-out state may not end up immediately adjacent, something that can only be discovered by zooming in closely.

Snapping is all about proximity during a drag-and-drop, and warping mouse movements to pull dragged objects into visual alignment

The snapping issue is bug #2808, and this is _largely_ a duplicate of that bug. And as I said there, IMHO the solution is for snapping to get **fixed** so that it _actually_ does what it currently only gives the _impression_ it's doing: places the dropped clip in alignment with another timeline element. **Exact** alignment, not merely "visual" alignment. (A fix that would make it no longer dependent on zoom level.)

However, the suggestions of offering a visual "gap indicator", as well as a menu option to eliminate those gaps, are interesting. Mostly because those features would cover situations that currently **wouldn't** be addressed even if drag-and-drop snapping were working correctly — for instance, when you delete a clip from the Timeline, and then have to close that gap by shifting other clips. There are situations like that where it might conceivably be _easier_ to use a menu option, instead of dragging clips.

So, I think what I'm going to do is mark this as a duplicate of #2808 (and I'd encourage you to Subscribe to that issue as well, to follow progress regarding the snapping fix), _BUT_ I'll leave this issue open as an enhancement request, since #2808 is strictly about fixing the snapping bug.

**Comment by ferdnyc** [comment]
(**Note to project members**: Despite the 'duplicate' label, please DO NOT close this issue. Explanation in my previous comment.)

**Comment by Twenkid** [comment]
Thanks!

> However, the suggestions of offering a visual "gap indicator", as well as a menu option to eliminate those gaps, are interesting. Mostly because those features would cover situations that currently wouldn't be addressed even if drag-and-drop snapping were working correctly — for instance, when you delete a clip from the Timeline, and then have to close that gap by shifting other clips. There are situations like that where it might conceivably be easier to use a menu option, instead of dragging clips.

Yes, this is a common situation, to which I also refer.

* As of "snapping" - I initially called it "condensing", but referred to "snapping" due to the tooltip of the magnet icon etc.
