### ISSUE TITLE
No fonts in animated title box

### ISSUE THREAD

**Issue by mouarfff** [OpenShot/openshot-qt#3063]
When i use the animated title box, I have only Bfont and WenQuanYiMicrohei fonts when i want to choose it...

I have a  lot of fonts in c:\windows\fonts and all of my system recognize.

I'm in windows 10 last update and 2.4.4-dev2-1571901451)

**Comment by ferdnyc** [comment]
Yeah, this comes down to a limitation of Blender's [font system](https://docs.blender.org/manual/en/2.80/modeling/texts/selecting_editing.html#loading-and-changing-fonts), in that it doesn't have any support for using system fonts. It can only use fonts which are loaded directly from disk, as individual files. If you were to load one of the `.blend` files directly into Blender, you'd see the same thing: The only font choice is the built-in default 'BFont`, and adding any other options requires loading _four_ different fonts from disk, for each of the four basic styles (Regular, Bold, Italic, and Bold-Italic).

![Screenshot from 2019-11-02 19-58-55](https://user-images.githubusercontent.com/538020/68078373-52afd200-fdab-11e9-9d24-9edef9c4472e.png)

In fact, if you were to try the 'WenQuanYiMicrohei' font or any of the other fonts listed there (some title templates also include various styles of 'FreeSans' and 'FreeMono'), you'd probably find that they don't actually _work_.

Since they don't have the location of the font on disk to pass to Blender, when it attempts to load the alternate font it'll fail and the text won't be rendered. (A message "Error: Unable to pack file, source path 'FreeSansBold' not found" would be output on the console, if you were running it directly.)

Honestly I'm not sure why those font lists are in the interface, I can only assume it was an attempt at a feature that didn't pan out. But I have no idea why they weren't removed, if that's the case.

Using a user-supplied font file _might_ be possible, though it would have to be supplied as an actual file, which we'd have to store somewhere Blender could access it. I have some concerns about the permissions/security implications there, since we'd just be handing a file path to the Blender Python script. But it would be the only option for making this work, with Blender's current font support.

I'll mark this as an enhancement request and leave it open, so that we at least keep track of it.

**Comment by mouarfff** [comment]
Thanks for your information, it's so strange for me blender can't see basic fonts...

**Comment by ferdnyc** [comment]
\*nod\* It surprised me as well. Looking into it more, I _think_ it comes down to the way Blender's font rendering works, which is totally unlike pretty much any other application.

When most software needs to render text in a particular font, the process is fairly similar regardless of application or OS. (As long as you think about it in the _simplest_ possible terms, which I am...):
1. The application coordinates with the font system to define parameters for font selection
1. It passes the text to be rendered to the font system, and one of two things happens
    1. Either it gets back a set of character glyphs representing that text, which it then draws
    1. Or, it asks a layout engine to render the text for it, and gets back what's essentially a bitmap image representing the rendered text

Qt's `QPainter::drawText` is how they implement 2.2 for Qt applications, and they also have a `QRawFont` class that lets you get slightly more down-and-dirty with the actual font glyphs in a manner closer to 2.1. 

However they utilize font data, all of those processes are inherently two-dimensional — as fonts _**are**_ inherently 2D, and so their rendering systems are 2D processes. Blender doesn't work that way, because it wants to see its world in three dimensions.

(`QRawFont` does also allows you to work with font data in a more Blender-like fashion, loading a font from memory or from disk _instead of_ using installed system fonts,. But that's going in the wrong direction for our purposes.)

But nothing in Qt's entire font system allows you to get at the font _files_ that make up the system fonts, and that's typical of operating system font APIs. For an application developer, it's considered a feature that you don't have to worry about things like font file management.

Blender needs to get at those files, though, because like I said how it works with fonts is completely different.

When Blender loads a font from disk, it converts each of the individual glyphs contained into a separate 3D shape. So, what _used_ to be a 2D font becomes a huge library of solid models. Then, when it's asked to lay out some text, it does all the work of selecting each individual character-shape model and placing it in the scene.

(In fact, as that Blender doc I linked to notes, it doesn't _have_ to use a traditional font at all — Blender's "font" system can work with **ANY** collection of 3D objects, including things were never letters to begin with. The ability to convert from TrueType and OpenType font data is really just a special-case convenience.)

Doing it the way they do means a lot more work for Blender, since it can't lean on the services provided by the operating system. But, in return for that extra work, their method means that each of the glyph-shapes are able to be manipulated _individually_ in 3D space. That's what allows Blender to do things like this, that would be much more difficult if the entire text were a converted 2D layout returned by a standard font system:

![Blender Tutorial clip](https://user-images.githubusercontent.com/538020/68517987-eb38cd00-0257-11ea-99af-f102993f08be.gif)

(That's the tail end of [this YouTube tutorial](https://www.youtube.com/watch?v=P-LXFn6xVzc) on creating the effect in Blender.)

I don't doubt that this _could_ be solved in a way that works **with** the operating system font support. But it would take a fair amount of work for the Blender developers to make that happen, and I guess it hasn't been a priority so far.

**Comment by mouarfff** [comment]
Ok :(
i'm frustrated, but i understand ... lol

need to recreate a lot of different fonts for that ?

there is not way to directly download another preset of 3d fonts in blender and use them in openshot ?

**Comment by mikelacsa** [comment]
@mouarfff unfortunately, there's none at the moment.
