### ISSUE TITLE
When open a project, i loose location of animated titles created

### ISSUE THREAD

**Issue by mouarfff** [OpenShot/openshot-qt#3067]
When i re-open a saved project with animated titles created and placed in the sequencer, openshot re-ask me to locate files.
It doesn't recognize locations, but there are still in the project library list and i have to replace them in the sequencer.

windows 10 pro 64bits
OpenShot-v2.4.4-dev2-1571901451-3f5370a8-0eb5fb46-x86_64

**Comment by ferdnyc** [comment]
@mouarfff Yeah, apologies, that's a bug I had fixed a _while_ ago and submitted as part of my PR #2976. I didn't expect that PR to end up on hold as long as it did.

Since #2976 is still not in a state to be merged, I've separated out the image sequence (including animated title) recovery fix as #3068, and I'll get it committed tonight if possible. Once it's merged, new Daily Build versions should no longer have that issue.

**Comment by ferdnyc** [comment]
Daily Builds starting from this version should no longer experience this issue:

**OpenShot-v2.4.4-dev2-1573190672-c2713520-0eb5fb46-x86_64.AppImage**
**OpenShot-v2.4.4-dev2-1573190797-c2713520-0eb5fb46-x86_64.dmg**
**OpenShot-v2.4.4-dev2-1573190799-c2713520-0eb5fb46-x86_64.exe**
**OpenShot-v2.4.4-dev2-1573190799-c2713520-0eb5fb46-x86.exe**

Since it looks like there's currently an issue updating the Daily Build page at https://openshot.org/download/, you can download the same installers from the bottom of the list at https://github.com/OpenShot/openshot-qt/releases/tag/daily

**Comment by ferdnyc** [comment]
> Since it looks like there's currently an issue updating the Daily Build page

Never mind, whatever was happening has cleared up. https://openshot.org/download/ can once again be used to download Daily Builds, including the ones listed above.

**Comment by mouarfff** [comment]
thx very much !
