### ISSUE TITLE
Play the Exported Video Button or Play Automatically after the operation is done

### ISSUE THREAD

**Issue by Twenkid** [OpenShot/openshot-qt#3076]
**Describe the new feature:**
A button to directly preview the exported video after the operation is done. Possibly an option/checkbox to play it automatically. 

**Describe the solution you'd like:**
A button in the export dialog. A checkbox for Play Automatically.

**Comment by ferdnyc** [comment]
Hmm... Our video playback support is, as you've probably noticed, "somewhat poor", so playing the video in OpenShot would likely be less than ideal. (And lead to performance problems for the open editing session, too.)

We could possibly add an option to automatically launch the exported file in the OS's default application. Or to open the export destination path in a file manager window.

**Comment by Twenkid** [comment]
Yes, I also meant to play it by a system's player - Shell execute etc., that's the easiest way and namely that "somewhat poor" internal playback with bad performance on slower machines*  is the reason for the need of many test exports and for external review... (Where other issues exist for that use case, if not fixed in a daily build - not-storing the latest export setting, thus a need to set them again each time).

Couldn't the preview be improved? If it's impossible to make a big progress (I noticed recently OpenShot is in Python, if that's the reason), I request another feature - generation of buffered short previews for review (they could played by external, like just System("ffplay path.mp4")  and a (semi-) automatic generation of proxy videos with the editor.

That goes also with another feature - the project may have not one, but two or three profiles: one for editing, one for test exporting and one for final production. I'll open another issue.

**Comment by ferdnyc** [comment]
> Yes, I also meant to play it by a system's player - Shell execute etc., that's the easiest way and namely that "somewhat poor" internal playback with bad performance on slower machines* 

Let' not kid ourselves, Preview performance is bad even on fast machines.

> Couldn't the preview be improved?

One hopes, or we're really in trouble.

> If it's impossible to make a big progress (I noticed recently OpenShot is in Python, if that's the reason),

Not particularly, no. OpenShot _is_ written in Python, but **lib**openshot is C++ (for exactly that reason), and the preview is displayed in a Qt widget that's part of the library; it gets loaded into the OpenShot Qt interface on launch.

The primary issue is that OpenShot's preview player isn't actually playing _video_. (In fact, in its current design it **can't** play video directly, which is another reason for the lack of internal export-review.) Because the previewer needs the **processed** Timeline results, and it processes the video frame-by-frame-by-frame as 2D images, it both creates and consumes the exploded series of frame images that _make up_ the input video(s). (Each of which is possibly manipulated to apply adjustments, effects, compositing of titles, images, or other videos, etc. on its way to becoming the final output frame that's displayed in the preview viewer, or exported to the output video.)

> I request another feature - generation of buffered short previews for review - they also could be played by an external player, like just System("ffplay path.mp4") - and a (semi-) automatic generation of proxy videos with the editor.

Well, to an extent the same issue arises there: Because OpenShot effectively only uses the input video as a source of frame images, proxy videos offer limited benefit. It's still going to have to explode the proxy into frames, same as the original. (Though  in some cases a proxy format may be more conducive to that, granted. Especially compared to a live-captured video stream that may not be well-indexed or even correctly formatted.)

Given that the preview (and export) ultimately needs frames instead of a video stream, though, it may make more sense to just generate and cache reduced-{size,quality,detail,etc.} frame images directly from the source video, instead of mucking around with transcoding and storing an additional copy of the _video_ in a slightly modified form., t's still going to have to be split apart for processing frame-by-frame.

> That goes also with another feature - the project may have not one, but two or three profiles: one for editing, one for test exporting and one for final production. I'll open another issue.

Hmm. Having "scratch" export presets I can see the utility of, but the idea of a separate "edit profile" that's different from the final production output is a worrying one. A project should be set up with a profile that represents the final video that will be exported from it, at least as closely as possible. The idea that you can create a project with a (presumably-reduced-quality) profile and then "upgrade" it for the final export isn't really something I'd expect to work well in OpenShot, nor would I expect that it'd be supported in the future.

Things like frame rate mapping and video scaling make it _possible_ to export at a different profile than the project profile, but that'll never work as well as an export using parameters that the project data is already aligned to. That's especially true when exporting at a _higher_ profile than the project data was set up for.

**Comment by Twenkid** [comment]
Thanks for the answers,

> The primary issue is that OpenShot's preview player isn't actually playing _video_. (In fact, in its 
current design it **can't** play video directly, which is another reason for the lack of internal export-review.) Because the previewer needs the **processed** Timeline results, and it processes the video frame-by-frame-by-frame as 2D images, it both creates and consumes the exploded series of frame images that _make up_ the input video(s). (Each of which is possibly manipulated to apply adjustments, effects, compositing of titles, images, or other videos, etc. on its way to becoming the final output frame that's displayed in the preview viewer, or exported to the output video.)

I understand that it's supposed to play processed frames when previewing in real time (that's also a reason for pre-rendered previews when the effects are too demanding), but they could still be prerendered and buffered and the performance seems low even if previewing plain videos without any effects, and simple effects shouldn't be so heavy IMO.  That's why sometimes I pre-preview outside the editor, check approximately where I have to cut etc.

As of plain videos, overlying tracks IMO shouldn't add too much overhead, unless there is alpha blending, only one frame is on top.

Simple effects as color correction could also be very fast with shaders.

> > I request another feature - generation of buffered short previews for review - they also could be played by an external player, like just System("ffplay path.mp4") - and a (semi-) automatic generation of proxy videos with the editor.
> 
> Well, to an extent the same issue arises there: Because OpenShot effectively only uses the input video as a source of frame images, proxy videos offer limited benefit. It's still going to have to explode the proxy into frames, same as the original. (Though in some cases a proxy format may be more conducive to that, granted. Especially compared to a live-captured video stream that may not be well-indexed or even correctly formatted.)

I haven't tried that idea of manual proxy yet, have to check and see, it should save on test-export time as well.

But is that frame "exploding" really so costly? Even 480p/5 Mbps is as costly as 1080p/28Mbps raw MTS, or similar bitrate but with more frequent keyframes and lighter format like XVID vs AVCHD?

...

BTW, another work-around - sometimes when scrabbling over the video timeline, OpenShot doesn't respond for a while, there's high CPU load etc. Sometimes that happens when automatically saving the project (seems quite demanding?). However I guess in other cases it is because the program is trying to decode all the frames in between(?) - allocating a lot of memory, "hurted" by new keyframes and re-computing the changes etc., trying to decode the audio etc. (if you you don't read it all in WAV for an easier access?).

I think that struggle can be reduced by carefully watching the real performance and adapting the attempts to extract and render the frame to that performance. That could be adjusted manually as well. 

If the system discovers that the PC can't preview all the frames with a reasonable speed, it may just **reduce the speed of sampling or stop sampling until the pointer stops for a given period of time -** the user may get a notification or indication that the editor is struggling.   (Or you do it like that anyway?)

It may also use lower resolution pre-extracted frames.

> Given that the preview (and export) ultimately needs frames instead of a video stream, though, it may make more sense to just generate and cache reduced-{size,quality,detail,etc.} frame images directly from the source video, instead of mucking around with transcoding and storing an additional copy of the _video_ in a slightly modified form., t's still going to have to be split apart for processing frame-by-frame.

OK, that's for the proxy, for the short regions previews they don't have to be in low resolution. They may be in max, played by ffplay or whatever, those files would be in a temp folder. I use a small RAM disk for such needs. 
 
> > That goes also with another feature - the project may have not one, but two or three profiles: one for editing, one for test exporting and one for final production. I'll open another issue.
> 
> Hmm. Having "scratch" export presets I can see the utility of, but the idea of a separate "edit profile" that's different from the final production output is a worrying one. A project should be set up with a profile that represents the final video that will be exported from it, at least as closely as possible. The idea that you can create a project with a (presumably-reduced-quality) profile and then "upgrade" it for the final export isn't really something I'd expect to work well in OpenShot, nor would I expect that it'd be supported in the future.

IMO different profiles for *test* reviews or *test export* and for production exports, respectively maybe having a button/preset for "test", is namely for not messing up the "official" project profile and for quickly switching between them, like Debug and Release.
