### ISSUE TITLE
freezing on import of videos

### ISSUE THREAD

**Issue by aldobrus** [OpenShot/openshot-qt#3077]
on trying to import video nothing happens, the cursor still moves but I am not able to select any thing.
I have left it for over an hour but video still does not load.
when trying to close open shot system reports openshot is not responding.

**Comment by Twenkid** [comment]
Would you specify what exact video files - just one file or many, with the menu "Import" or by drag-drop, what's the format, what is the size of the video etc., what version of OpenShot in what Operating system? Did you try opening other video files in other formats and did you get the same result?

**Comment by mikelacsa** [comment]
@aldobrus please follow this format so we can help you better:



**Describe the bug:**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior:**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior:**
A clear and concise description of what you expected to happen.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.
Log files can be found in your HOME/.openshot_qt/ folder. Please compress or zip
the log files (as they can become quite large).

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please
attach a small snippet of the exception here, but please keep it as small as
possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them here, dragging-and-dropping into this form, or clicking below and loading
images saved to your computer. All images are public, so please don't post screenshots
containing personal information.
