### ISSUE TITLE
Better re-use of functionality already present in libopenshot, use public API

### ISSUE THREAD

**Issue by musteresel** [OpenShot/openshot-qt#3089]
There seems to be code in Openshot-qt which does the same as the code in libopenshot, or even worse breaks any abstraction the classes of libopenshot (should) provide

Example Keyframe rescaling:
   - https://github.com/OpenShot/openshot-qt/blob/develop/src/classes/project_data.py#L399
   - https://github.com/OpenShot/libopenshot/blob/develop/src/KeyFrame.cpp#L887

This was mostly possible to happen because, in this case with `Keyframe`, there member `Points` (a vector of points) was public accessible. [I'm about to change this.](https://github.com/OpenShot/libopenshot/issues/370)

I'm not familiar enough with the rest of the code base (yet) to know whether there are more such cases or if it's just the keyframes, but generally speaking I think delegating more work which is really "domain knowledge" (scaling keyframes definitively is) to libopenshot is the right approach; OpenShot-qt is after all basically a "user interface".

For the keyframe case I hope we can find a solution that shifts the modification of the points to libopenshot but remains "pythonic" to use from OpenShot-qt!

**Comment by musteresel** [comment]
Ok, seems like I've missed an important aspect here: `some_keyframe["Points"]` *doesn't* access the once public member `Points` ... you're working mostly with the Json representation of Keyframes.
Updates seem to go via the timeline ([here](https://github.com/OpenShot/openshot-qt/blob/ad1df9e86b7a839a2438ed47f2c0b7bf34c7c76a/src/classes/timeline.py#L86)) and then (on the C++ side are passed via Timeline -> Clip [ -> Effect ] -> Keyframe, all in the `SetJson` / `SetJsonValue` functions.

This is good because it means me changing the public interface doesn't break much on the side of openshot-qt.

This is bad because it means `Keyframe::SetJsonValue()` needs to be a lot more complex in order to detect changes (or no changes) as fast as possible.

`grep`ing for the names of the public API of `Keyframe` in the openshot-qt source gives these locations as possible uses / conflict points:

**`AddPoint()`**
~~~
openshot-qt/src/classes/project_data.py:661:                            brightness.AddPoint(1, trans_begin_value, openshot.BEZIER)
openshot-qt/src/classes/project_data.py:662:                            brightness.AddPoint(round(trans.length * fps_float) + 1, trans_end_value, openshot.BEZIER)
openshot-qt/src/windows/add_to_timeline.py:331:                brightness.AddPoint(1, 1.0, openshot.BEZIER)
openshot-qt/src/windows/add_to_timeline.py:332:                brightness.AddPoint(round(min(transition_length, end_time - start_time) * fps_float) + 1, -1.0, openshot.BEZIER)
openshot-qt/src/windows/views/timeline_webview.py:278:        brightness.AddPoint(1, 1.0, openshot.BEZIER)
openshot-qt/src/windows/views/timeline_webview.py:279:        brightness.AddPoint(round(transition_details["end"] * fps_float) + 1, -1.0, openshot.BEZIER)
openshot-qt/src/windows/views/timeline_webview.py:344:            b.AddPoint(1, 1.0, openshot.BEZIER)
openshot-qt/src/windows/views/timeline_webview.py:345:            b.AddPoint(round(duration * fps_float) + 1, -1.0, openshot.BEZIER)
openshot-qt/src/windows/views/timeline_webview.py:2760:        brightness.AddPoint(1, 1.0, openshot.BEZIER)
openshot-qt/src/windows/views/timeline_webview.py:2761:        brightness.AddPoint(round(10 * fps_float) + 1, -1.0, openshot.BEZIER)
~~~

**`GetInt()`, `GetLong()`, `GetValue()`** (these remain, so no issues here)

**`Json()`**:
~~~
openshot-qt/src/windows/views/timeline_webview.py:2773:            "brightness": json.loads(brightness.Json()),
openshot-qt/src/windows/views/timeline_webview.py:2774:            "contrast": json.loads(contrast.Json()),
~~~

I'm leaving this issue open because there's still the idea to reuse functionality (example scaling keyframes) which is already present in libopenshot.  Since most (almost all?) of the timeline / clip / keyframe configuration seems to be handled as Json on the side of openshot-qt this is would be a *huge* change though. Probably not worth it.

**Comment by ferdnyc** [comment]
> `grep`ing for the names of the public API of `Keyframe` in the openshot-qt source gives these locations as possible uses / conflict points

Mmm... _possible_, but it turns out none of them are.

Every one of those lines of code is related to the creation of Transitions, which makes sense because Transitions are _entirely_ defined by OpenShot — libopenshot knows nothing about them, as such.

OpenShot creates a Transition as a special-case of the Mask effect with a certain set of parameters applied so that OpenShot will execute the effect on the Timeline, outside of Clip boundaries. (The only time, in OpenShot, that an Effect is created on the Timeline directly rather than being passed to a Clip, even though libopenshot fully supports all effects existing as their own Timeline objects unattached to any individual clip.)

So, effectively, OpenShot is setting those things as if they were being chosen by the user; think of it as OpenShot running a macro, in a sense. The end result is an Effect configured a certain way, which is then passed to libopenshot, but that particular configuration of the Mask effect is defined and implemented entirely on the OpenShot side of the divide.

**Comment by musteresel** [comment]
> but it turns out none of them are.

Huh? At least the use of `AddPoint` in `src/classes/project_data.py:661` **definitively** is a call to `openshot::Keyframe::AddPoint` (from libopenshot), no? In the line directly preceding that line the "brightness" variables is set to `openshot.Keyframe()`: https://github.com/OpenShot/openshot-qt/blob/develop/src/classes/project_data.py#L659

> Every one of those lines of code is related to the creation of Transitions, which makes sense because Transitions are entirely defined by OpenShot — libopenshot knows nothing about them, as such.

Yeah, but the code (OpenShot) calls the Python API of libopenshot, no? That's what I mean .. if I change `openshot::Keyframe::AddPoint` (libopenshot) then this will affect the positions here where `AddPoint` is called, too.

**Comment by ferdnyc** [comment]
@musteresel My apologies, I don't think I'd followed what you were asking. It's been so long since I last came into contact with the suggestion that there could be any code abstractions to break. (Or at least, that there might be any left which haven't already been steamrolled over so many times, they're the approximate thickness an IBM hardware user's manual pages ca. 1995.<sup><b>\*</b></sup>)

Yes, OpenShot's breaks every possible abstraction in libopenshot's public API, and a few more it didn't even know about.

1. The Transition code, alone, uses `openshot.Keyframe()` to create its keyframe data, then loads it into its project store by requesting the JSON representation of the resulting vector. Presumably that's because it leverages Keyframe's automatic adjustment of the Bezier curve handles.

2. Most of the Clip code just calls `openshot.Point()` to generate individual points, then retrieves their JSON serialization to store in the project data.

3. And then, just for fun, there's the properties model code, which screams "I CAN DO IT MYSELF!!" like a petulant toddler, flips libopenshot the bird, and just manipulates the local JSON serialization "by hand", without using **any** of the library API, because... I guess **#YOLO**, probably? `¯\_(ツ)_/¯`

https://github.com/OpenShot/openshot-qt/blob/2ad18546677d3513affca58e975eefde35cf1692/src/windows/models/properties_model.py#L435-L489

That includes modifying both coordinate data and interpolation parameters, as well as both deleting _and_ creating new points — by just populating a minimal Python dict and tacking it onto the Python-side `clip.data[property]["Points"]` list, this time 'round, rather than calling `openshot.Point()` to generate the serialization.

If there's any bright side to this, it's that it would _probably_ be pretty trivial to replace all of the `openshot.Keyframe()` / `openshot.Keyframe.AddPoint()` calls the Transition code uses with calls to `openshot.Point()` instead. That'd at least decouple the OpenShot code from libopenshot's Keyframe API. 

`openshot.Point()`, though, appears 80 times in the source, so that one's in there pretty good.

\* – (_Very_ thin. Literally tissue-paper thin.)
