### ISSUE TITLE
Start and End of Clip commands as Symbols - when the clip is resized, Recompute the keyframes

### ISSUE THREAD

**Issue by Twenkid** [OpenShot/openshot-qt#3091]
**Describe the new feature:**
Currently when applying Volume - Fade In/Out, animations or whatever at the Start or End of the clip as the commands suggest, the program adds keyframes, but when the clip is resized - which is supposed to happen in an editor - the position of the keyframes is not adjusted and these volume or animation settings are now wrong. The operation with keyframes in Openshot seems cumbersome (AFAIK), it would be convenient to have a list or something for easy remove etc., so the simplest usually is to revert all fades (Reset Volume) and apply them again, which is a lot of precise clicks. Also, these Fade-in-out are frequent operations, often coming together, when editing with many segments which have variability in the sound - a general idea, what about a flying:

 **Toolbox palette with numerous common commands, accessible in one click without opening a context menu?** They would be applied on the selected clip.

**Describe the solution you'd like:**

I suggest that these fades be special and relative to the actual current start-end of the clips and thus recomputed on each new edit.

**Comment by ferdnyc** [comment]
Yeah, I always liked the interface in... I think it was Sony Vegas?... where every element on the timeline had permanent fade handles attached at both ends, on the inside edge.

Dragging the handle towards the _center_ of the clip would extend the fade-in at the start (or fade-out at the end) and make it more gradual. But it was anchored to the end of the clip — kind of like our transitions should be — and was defined only in terms of its width, meaning some number of seconds (or a fraction) after the start of the clip, or before the end. (And its curve, which I think was adjustable somehow.)

Defining it that way meant that moving the clip, resizing the clip, trimming the clip... almost any operation you could perform, the fade wasn't affected. The only exception was if you trimmed the clip at a point _inside_ the curve area... which IIRC probably chopped the clip down as well, so that its inside edge remained at the same point in the video, and the curve just got steeper due to the shorter fade time.

Only somewhat annoying thing about it was that when a clip had no fade applied, you'd sometimes try to grab its edge to resize it, and you'd end up accidentally dragging the fade handle instead. But it wasn't like that happened often, and being extra-careful usually helped you avoid it.

The designers at Sony Creative Software (as it was known back then) had a habit of coming up with clever UI innovations, though. I'm pretty sure it was SoundForge that first added resizable scrollbar handles, which is one of those things... it doesn't _sound_ all that useful in the abstract, but trying it first-hand completely blows your mind. Scrollbar resizing is quite simply one of the most effective and natural zoom controls a linear editing interface can have. ...Somehow!

(...We should really see about adding that feature, too, come to think of it.)
