### ISSUE TITLE
Openshot closes/crashes when opening .osp file.

### ISSUE THREAD

**Issue by JCHappyDude** [OpenShot/openshot-qt#3096]
**Describe the bug**
.osp file closes Openshot when trying to load it from within the app or windows 10 Explorer.

**Steps to reproduce the behavior:**
1. Try and get Blender to work by installing different versions of Blender (for Animated Titles) and Openshot but kept getting an error message about 'could not render the first frame' and mentioning above the need to use at least version 2.80 of blender (was using v2.81, but also tried 2.8 as well as 2.79 and 2.79b with earlier versions of Openshot)
2. Found that latest and older 32bit versions of Openshot fixed the error message issue and got the 3d titles to start rendering but was too slow for my liking so canceled render. Tried older 32bit versions of Blender to see if it was faster but was not so kept closing before any finished rendering. Basically a lot of installs and uninstalls, including with latest 32bit and 64bit Daily Builds of Openshot.
3. I gave up on trying to get 3d animated titles to work and went back to the latest main 64bit Openshot build and tried to open .osp project file I was working on. 

**Expected behavior**
I try to open the .osp file in Openshot or Windows Explorer but the app hangs for a bit and then closes down Openshot every time now no matter which version of Openshot I try. Deleting the Openshot_qt folder doesn't help either. The .osp file and the video clips used for the project are still in the same directory they were in before. I also used several 2d titles in the project and in the same video channel as the main video clips when I was originally editing the project before all this occurred, which seemed to also make the preview playback a bit slow and jumpy.

**System Details**
- OpenShot Version: 2.4.4
- libopenshot Version:  0.2.3
- Platform: Windows-10-10.0.18362
- Processor: AMD64 Family 21 Model 2 Stepping 0, AuthenticAMD
- Machine: AMD64
- Python version: 3.6.4
- Qt5 version: 5.9.1
- PyQt5 version: 5.9
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.4.4-dev2-1574518199-d539e468-12a15298-x86_64.exe

**Log Files**
- http://logs.openshot.org/6v8xkybke1t3sf9az7det4xumq5zc6kj/openshot-qt.zip
- http://logs.openshot.org/6v8xkybke1t3sf9az7det4xumq5zc6kj/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by ferdnyc** [comment]
@JCHappyDude Indeed, Blender support was unfortunately broken (entirely) in the Daily Build releases of OpenShot for about a week recently (#3099). That issue's been fixed (#3100), and newest Daily Build releases are compatible with Blender 2.80 / 2.81+. (**Only** — nothing earlier, due to incompatible Blender changes.)

As far as the issues with your project files, there have been fairly significant changes to the way OpenShot manages project data recently, and while we've attempted to keep the format compatible with earlier versions, it's possible that the `.osp` file you created in a recent `2.4.4-dev2` won't load in `2.4.4` release due to unexpected issues with those changes.

The only thing I can really think to suggest is, now that Blender support is fixed, your existing project file should be loadable in the newest Daily Build versions (anything after November 26). To continue using OpenShot `2.4.4` release, though, it may be necessary to start over with a new project file I'm afraid.

(That file _will_ also be compatible with the **newer** version, if you decide at any time after that to update OpenShot. It's only going in the other direction, taking a file created in the latest development code backwards to an earlier OpenShot version that isn't 100% reliable.)

The rendering process to generate animated titles is definitely a time-consuming one, Blender is tuned for power and quality far more than it is for speed. That doesn't change a whole lot from release to release or architecture to architecture I'm afraid, it's just the speed Blender works at.

However, the Daily Build versions do now include an experimental preference to enable Blender's GPU rendering engine, which we're hopeful could give users with more powerful graphics cards a nice speed boost. (I'd actually be interested in hearing feedback from anyone who tries that feature out on Windows, as far as I know it hasn't been tested there.)

I'm going to close this since the issues encountered have been resolved in more recent development builds.
