### ISSUE TITLE
Making project file cross-platform and making it easier to move projects around.

### ISSUE THREAD

**Issue by SteveBaker** [OpenShot/openshot-qt#3097]
It's annoying that project files can't be transferred between Windows and Linux.

The problems seem to relate to the fact that full pathnames are used thoughout the project file. 

That's annoying anyway because it means that I can't easily rename the directory that contains all of the files that belong to my project...but it also means that paths to places like .openshot_qt are absolute (and different for each OS).

Would it be possible to have an option to store all of those paths relative to a pair of base directories (eg A  "MyProject" directory) and have the system deduce where the .openshot_qt folder is each time it's run.

That would be backwards compatible with existing project files if those locations defaulted to the empty string. Then it's just a matter of resolving the forward/reverse slashes thing - which ought to be rather easy.

**Comment by ferdnyc** [comment]
@SteveBaker Good news! Since the merge of commit 75aa03f two weeks ago, OpenShot uses a new file-management model that's much more project-centric.  What we call "assets" (meaning,  anything created for a project,  like title files and animated titles) are stored in the same location as the project file itself,  in a folder named `Project File Name_assets`. The `.openshot_qt` dir is mostly just used as a settings and scratch dir.

You'll still have to manage your **own** media files (the ones you import,  rather than generate), but if you keep them either in the same folder as the project file, or in a subfolder inside that one,  you should be able to migrate project data between locations — or even accounts/systems — just by making sure to keep the `.osp` file, its `_assets` folder,  and any imported media files together and in the same location relative to each other.
