### ISSUE TITLE
Now doesn't work with Blender 2.81

### ISSUE THREAD

**Issue by Ruadh495** [OpenShot/openshot-qt#3098]
It appears Blender has got ahead of Openshot again...

The problem with Blender 2.80 was fixed but I have Blender 2.81 and there's a problem with that. Animated titles returns: no frame found in the output from Blender

**Comment by speedytechdev** [comment]
Hi @Ruadh495 could you please use the template. We are missing important information about the bug-like what version you are on and more. The template can be found below.

**Describe the bug:**
A clear and concise description of what the bug is.

**Steps to reproduce the behaviour:**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior:**
A clear and concise description of what you expected to happen.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.
Log files can be found in your HOME/.openshot_qt/ folder. Please compress or zip
the log files (as they can become quite large).

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please
attach a small snippet of the exception here, but please keep it as small as
possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them here, dragging-and-dropping into this form, or clicking below and loading
images saved to your computer. All images are public, so please don't post screenshots
containing personal information.

**Comment by Ruadh495** [comment]
Thanks, I've opened it again using the bug report tool (that didn't work last night either). Hopefully that provides the information. Also hoping it's just my system not more general (Blender problem?)
