### ISSUE TITLE
Animated titles not working with Blender 2.81

### ISSUE THREAD

**Issue by Ruadh495** [OpenShot/openshot-qt#3099]
**Describe the bug**
Animated titles not working with Blender 2.81

**Steps to reproduce the behavior:**
1. Go to "titles"
2. Click on 'animated titles'
3. Chose any template and click on it
4. See error "No frame found in output from Blender"

**Expected behavior**
Invoke Blender 2.81 using the path given in preferences to create an animated title

I have reinstalled Blender and verified the file path. Openshot was working with Blender 2.79 until I installed yesterday's daily build, which blocked Blender 2.79 without solving the problem with Blender 2.81. 

**System Details**
- OpenShot Version: 2.4.4-dev2
- libopenshot Version:  0.2.3-dev1
- Platform: Windows-10-10.0.17763
- Processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.4.4-dev2-1574518199-d539e468-12a15298-x86_64.exe

**Log Files**
- http://logs.openshot.org/vk94xie1ro89e9igh41hcz4ub3zo7lgz/openshot-qt.zip
- http://logs.openshot.org/vk94xie1ro89e9igh41hcz4ub3zo7lgz/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Ruadh495** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/58194409/69631638-07a17b80-1046-11ea-91dd-80986995ee28.png)
![Screenshot (4)](https://user-images.githubusercontent.com/58194409/69631655-0c662f80-1046-11ea-928f-6fcc67e4f6a1.png)

Screenshots showing error message and path from the Blender shortcut (which works).

**Comment by ferdnyc** [comment]
@Ruadh495 
Apologies, I'd meant to look into this last night when I saw the first report, in fact I even downloaded 2.81... and then I got sidetracked dealing with post-Fedora 31 upgrade issues and ultimately fell asleep. Now I have to rebuild my local libopenshot (all new library versions, due to the upgrade) before I can even _run_ OpenShot... but that'll be done in a few moments.

Point is, I'll take a look when I can, which will probably be in the next hour or two. I'm sure it's not just you — Blender probably made some change from 2.80 that we have to adapt to. But I also doubt it's anything major, shouldn't take too long to fix.

**Comment by ferdnyc** [comment]
Well, this was my fault as it turns out — a fix I'd made last week broke not just Blender 2.81 support, but Blender support in general. The issue had nothing to do with 2.81, it was probably just a coincidence that you encountered it when upgrading.

Anyway, it's fixed now in the repo, I'm _hoping_ updated Daily Builds should be available shortly, though the issue from a couple of weeks back that broke those may have resurfaced again. I'll let you know in a few minutes, either way.

**Comment by ferdnyc** [comment]
@Ruadh495 
Well, that was a lie, wasn't it? The Daily Builds _were_ offline again, but @jonoomph has fixed them, and the new Daily Builds dated November 26 (or later) have Blender compatibility restored for versions 2.80+ (including 2.81). Sorry about that, and thanks for reporting!

**Comment by Ruadh495** [comment]
Just checked on the latest daily build and it's working fine. Thank you.
