### ISSUE TITLE
Quality of Life Improvements for Importing and Exporting

### ISSUE THREAD

**Issue by TharenaMelishka** [OpenShot/openshot-qt#3113]
Some form of in-program memory for things all over would be nice.
* Remember the last directory you used for importing or being able to set a default directory for importing.  
* Remember the last directory you used for exporting, or again being able to set a default directory for export.  
* I'm going to re-second the request #1586 from MAY 2018...  it's sitting open with no replies.  With the following addition -- even just remember last EXPORT selection would be nice.  Exporting in a different format that you're viewing in would be handy, instead of having to tweak the format every time, since in order to view any time lapsed footage I have to drastically drop the profile just to get it to pretend to play (and I gave it 3gb to play with in the settings....)
* Remembering the CASE SENSITIVITY of your file on export  --- When I go to export this is one of my largest rage moments.... WHY can't it remember case sensitivity?

**Describe the solution you'd like:**
The directories shouldn't be horribly hard to implement, drop them into the preferences window and string it into the commands where applicable.. 
Case sensitivity is a matter of better string management, iirc, but I'm a novice programmer..
Since it's been on the back burner for a year and a half I'm guessing remembering the export selection (as compared to the working selection) must be tougher to implement.  

**Describe alternatives you have considered:**
Rage, frustration and other programs that have this already built in? .... 

Thanks oodles!

**Comment by ferdnyc** [comment]
> * Remember the last directory you used for importing or being able to set a default directory for importing.
> * Remember the last directory you used for exporting, or again being able to set a default directory for export.

Import path has been remembered since OpenShot 2.4.2. Export path memory was added four years ago.

Note that both of them are _per project_, which is even more flexible really (since different projects may use different directories), but it does have the disadvantage that each project starts back at the default user home directory. Also, because they're stored in the project file, you have to save your project after or they won't be retained. So for instance, after you export, save the project (again) to store the default export path for that project.

If you want to set user-wide defaults for either or both paths, admittedly it's not particularly user-friendly but with the current Daily Builds you have the option to create a user default project file in `$HOME/.openshot_qt/default.project`. That default project can have those paths already set.

So you'd just make a copy of [_default.project](https://github.com/OpenShot/openshot-qt/blob/0b77a93f67d623eab7a8126b05fd4f76deca5c4a/src/settings/_default.project) and fill in the path strings, e.g.:
```json
{
  "id": "T0",
  "fps": {
    "num": 24,
# (...more_of_the_file)
  "export_path": "/home/ferd/Documents/Videos",
  "import_path": "/home/ferd/Videos",
# (...the_rest_of_the_file)
}
```

> * Remembering the CASE SENSITIVITY of your file on export  --- When I go to export this is one of my largest rage moments.... WHY can't it remember case sensitivity?

That's already fixed in the Daily Builds (as of #3052), project file names are no longer modified in any way.

**Comment by TharenaMelishka** [comment]
Thanks!  I use different directories for my projects, but they all live in the same root directory location, so this will let me skip a few of the harder hunting steps to get to that directory.  <3  

Looks like there's a couple new toys in the daily builds, as I just acquired the latest.  Thanks again!
- Mel

**Comment by nanohtpc** [comment]
I got a problem..

As the text reads, i inserted the lines, but when trying to load OPENSHOT, the program won´t start, if i remove them, then it starts, what i´m doing wrong???

**Comment by ferdnyc** [comment]
@nanohtpc What OS are you using? If you're using Windows, you probably have to write the paths either with double backslashes, or with forward slashes instead of backslashes. (Python supports forward slashes for Windows paths.)

So, you could use either one of:
* `"C:\\Users\\username\\Videos"`
* `"C:/Users/username/Videos"`

Both of those **should** work, though honestly I haven't tested it on Windows.

**Comment by ferdnyc** [comment]
The other thing you can do is:
1. Create a new project
1. Import a file from the directory you want to make default
1. Save the project
1. Open up the saved `.osp` file in Notepad, and just copy the `"import_path"` line from that file.

**Comment by ferdnyc** [comment]
Oh, yes, and it wasn't even on @TharenaMelishka 's list, but #3088 finally fixed the issue where the export filename would have its extension doubled, if your output filename already included the extension. Now it'll only add one if the filename doesn't already end with it. (That _was_ really annoying, and I thought I'd fixed it months ago, but apparently not.)

**Comment by nanohtpc** [comment]
will test this...

**Comment by mikelacsa** [comment]
@nanohtpc have you tried @ferdnyc 's solution?

**Comment by ferdnyc** [comment]
> Also, because they're stored in the project file, you have to save your project after or they won't be retained. So for instance, after you export, save the project (again) to store the default export path for that project.

I recently made some more improvements to how the undo/redo tracking handles path updates, in fact.

* As of PR #3112 OpenShot no longer creates an undo history event for every `import_path` update. (Those were causing each Project File import to require _two_ Undo operations in order for it to be reversed: The first undo would do nothing but invisibly reverse the change to `import_path` (even if there was no change), and then a _second_ undo would actually remove the imported file. That'll no longer  happen, and a single undo will reverse a single import.)
* OpenShot also no longer clears your Redo list when it's processing changes that don't affect the history. (Like an export operation, or a change in the Timeline zoom.)
* Last but not least, whenever you _export_ a video the project data is marked as  having unsaved changes. That's meant to act as a reminder to save the project file after exporting, so that it gets updated with the new value for `export_path`.
