### ISSUE TITLE
Imported video with a non-square Pixel Aspect Ratio gets distorted, has to be manually scaled

### ISSUE THREAD

**Issue by ramoka5** [OpenShot/openshot-qt#3117]
**Question:**
I'm working with input video format of 720x576 and I'm not able to export the result with the same format. It is change to 4:3 format insted. Is there any option to force the result to 16:9 instead of 4:3? see attached work screen

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 2.4.4
- Operating System / Distro: Windows 10

**Screenshots:** (Optional)
![image](https://user-images.githubusercontent.com/58661641/70391787-3bcb5380-19d9-11ea-9498-2301ea6ae0a6.png)

**Comment by ferdnyc** [comment]
@ramoka5 

Yeah, it looks like we're not applying the pixel aspect ratio to the imported video.

Fortunately, there are two easy solutions to this:

1. Since you're working with a 16:9 output profile, if you change the Scale mode of the video from "Best Fit" to "Stretch", OpenShot will automatically fit it to the output frame, which should make it the correct size.

2. Or, you can correct it manually. A pixel aspect ratio of `64 : 45` works out to `64 ÷ 45 = 1.422222`, so you can adjust the video's Scale X property to `1.4222` to give it the correct dimensions. (The Scale X control _looks_ like it can't go higher than `1.00`, but if you double-click on the slider it'll let you manually type in a value, and it'll accept larger numbers like `1.42`.)

**Comment by ferdnyc** [comment]
Still, it looks like this is a bug in the import file handling, so I'm going to tag it as such.

**Comment by Triangulix** [comment]
Hi
I just noticed the same or a very similar problem with version 2.4.1.
I'm trying to join the VOB files of a DVD to one long video. The DVD uses 720x480 resolution but has non-square pixels so the player has to stretch the video to 16:9. The aspect ratio ist correctly encoded in the VOB files.

For export I selected "DV/DVD Widescreen (720x480)" on the "Einfach" tab and on the "Erweitert" tab the correct aspect ratio of 16:9 is displayed.
But on export OpenShot ignores these settings. It encodes the video with the right resolution of 720x480 but sets the aspect ratio information of the video to 4:3 which leads to a too narrow image on playback.

I don't want to loose image information. Therefore stretching the videos to make them look right on 720x480 with 4:3 aspect ratio is not a usable workaround.

**Comment by itagagaki** [comment]
Hi
I had the exact same issue as #3429.
Are there any plans to resolve this issue?
I'm using OS 2.5.1 on Windows 10 Pro 20H2 x64.

**Comment by JacksonRG** [comment]
@itagagaki Have you checked if this issue exists in the current daily build?

**Comment by agilmor** [comment]
This seems like a duplicate of the older #1774 and newer #3429. All of them closed.
I'm facing it 2.4.3 in Ubuntu.
The Stretch workaround is good enough for me, though.
Thanks!

**Comment by Triangulix** [comment]
I already forgot about OpenShot and this bug. I don't care for software that doesn't get basic features like aspect ratio fixed.
