### ISSUE TITLE
another "invalid load key" bug (urgent)

### ISSUE THREAD

**Issue by Jorji-Costava** [OpenShot/openshot-qt#3126]
[MSS_Trailer.zip](https://github.com/OpenShot/openshot-qt/files/3969142/MSS_Trailer.zip)
here's the file that won't open for some reason. please someone help, this video is immensely important to me, I need to be able to finish it
i have the most recent version of openshot as given in the bug report section of the website, and i'm also incredibly nervous about this. if I have to restart then that's several weeks of work gone

**Comment by SuslikV** [comment]
You may try this file: 
[MSS_Trailer_repaired.zip](https://github.com/OpenShot/openshot-qt/files/3973022/MSS_Trailer_repaired.zip)

No guaranty that it will work. The project file is damaged a lot. Make backups during your work.

Info. The file damage is quite similar to: https://github.com/OpenShot/openshot-qt/issues/3123 (zeros  fill)

**Comment by ferdnyc** [comment]
> Info. The file damage is quite similar to: #3123 (zeros fill)

It sure is. And just like #3123, the file is _huuuuuuge_.

HOWEVER, this file does present a new wrinkle, one that is (I'm sorry to say) bad for @Jorji-Costava , but potentially helpful for us: It contains no `"history"` block. At all. The zero-fill in this case starts right in the project data. Which means:

1. The bad news, for @Jorji-Costava , is that @SuslikV 's repaired file won't be **completely** intact — it can't be, as part of the project data structures is missing. Hopefully it's somewhat salvageable, but in this case real data was lost.
2. For us, though, what this tells us is that this problem has nothing to do with the history-saving feature. It's clearly a general error that can strike during any save operation on a large-enough JSON output file (where "large enough" is truly _immense_ — the **intact** part of this particular file is over 235,000 lines of data! In #3123 the (intact) non-history content was 112,000 lines long.

It seems like there's an issue with serializing massive data structures to disk in Python, possibly in the `json.JsonEncoder` class, or it could even be a lower-level memory-management/access issue impacting the in-memory project data, where the `JsonEncoder` can't even get to the data to serialize it.

In both #3123 and this issue, the projects consisted primarily of massive amounts of still images, while video/audio content made up little (#3113) to none (#3126) of the project media. We've always known that OpenShot's still-image handling is relatively inefficient compared to its video handling — look no further than the memory-consumption issue reading frames from still-image readers (OpenShot/libopenshot#327) — but now it seems that may even be impacting the integrity of project data.

**Comment by ferdnyc** [comment]
Hmm. In fact, the way we write project data to file is, we generate the _entire_ contents of the file in-memory as a `str` object, process it<sup>*</sup> to convert all of the pathnames to relative paths, _then_ write that string to file:
https://github.com/OpenShot/openshot-qt/blob/cf9721a40d9d830f6d710eae3e70f6298bc0d79a/src/classes/json_data.py#L145-L153

As project file data grows, that becomes a less and less workable approach. We may have to come up with something different that allows us to serialize directly to the output file, even if it means implementing a custom encoder that does the path-replacement on the fly.

\* — (Process it as one giant string, no less! `convert_paths_to_relative()` just does a regular-expression substitution across the entire string containing the serialized JSON data, which for extremely large project data structures like these is _hellishly_ inefficient, compared to writing a custom encoder that knows how to parse and manipulate data keys that contain pathnames.)

cc: @jonoomph

**Comment by SuslikV** [comment]
@ferdnyc in which cases data can be zeroed? Is there evidence that previous session of OpenShot (when the project file was actually saved) was error free?

**Comment by ferdnyc** [comment]
> @ferdnyc in which cases data can be zeroed?

I mean... it _should_ **never** happen. Really, there are no conditions, or at least it's not expected that should happen — but it's happening anyway, so it would appear there are **unexpected** (and therefore unknown, so far) conditions that can lead to this issue.

I don't actually think it's the _data_ being zeroed at all, though — if it were, then the file would be serialized properly, just with blank data. The failure appears to be happening in the _output_ of the JSON data — and in fact, given that the files are created to hold a **larger** block of text than they ultimately do, it seems likely that the error is in the process of taking the formatted, in-memory serialized string data and storing it to file.

> Is there evidence that previous session of OpenShot (when the project file was actually saved) was error free?

Not as such, no... and it would be good to get the `openshot_qt.log` file(s) from at least one of @Jorji-Costava , @deanl3, @briannamu to look for information on what may have led to this. If, indeed, there is anything logged — there may very well not be, especially since it appears like the save process terminates without finishing, and we wouldn't log any error until (unless) we caught an Exception raised by `File.write()` which it probably isn't getting to either.

In fact... I wonder if the problem could be that OpenShot is (accidentally) terminating **itself** before the file is completely written to disk? Or even just crashing itself during the exit process, leading to the `File.write()` getting prematurely aborted?

@Jorji-Costava , @deanl3, @briannamu : If you can remember, or even just your best guess, how did you save the project, the last time you saved from OpenShot before this happened? In particular, do you generally do a **File > Save Project** / <kbd>Ctrl</kbd>+<kbd>s</kbd> to save, and then quit OpenShot? Or do you quit the program, and then do the save from the "Unsaved Project" dialog right before exit?

Could be that when a big save is occurring after we've already started exiting the application, we end up destroying some of the data structures before the save process is done with them. (A _possibility_... I'm not too sold on it being the right answer to this, at least not yet.)

**Comment by Jorji-Costava** [comment]
oh sure, here's those files
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/3975222/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/3975223/openshot-qt.log)
The fixed version works! thanks so much!

I usually ctrl + s to save, it usually takes a while after i've added a lot of individual assets (about 30 seconds, maybe a minute), the last time I saved, I just copy/pasted a group of six or eight frames and called it a night.

**Comment by Jorji-Costava** [comment]
oh yeah, I cleared them and tried reopening the broken version of the osp file and uploaded the new ones since that's what I was told to in the bug report section of the site to reduce unnecessary information

**Comment by SuslikV** [comment]
I think, you was asked about the log-file at the time of the previous OpenShot run (before you noticed the error on opening), but as soon as logs where cleared... I don't think that it will help a lot. Yeah, instructions can be read in different ways ^_^

**Comment by Jorji-Costava** [comment]
good thing i didn't clear recycle bin then, here's the correct ones
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/3975450/openshot-qt.log)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/3975451/libopenshot.log)

**Comment by ferdnyc** [comment]
@Jorji-Costava Thanks! Immensely helpful.

...Oh, wow. TBH, I'm not sure what this means, but it _definitely_ means **something**: Your _log file_ is showing the same corruption as the project file! It looks like OpenShot ran into the same issue when writing the _logs_ to disk!

![image](https://user-images.githubusercontent.com/538020/71054366-c15cab00-211f-11ea-8e78-ef0d9111cb7a.png)

That's right after the file-save operation that presumably resulted in the corrupted project file. Here's the plaintext version of that same section of the logfile:
```
     updates:ERROR Couldn't apply 'update' to update listener: <classes.project_data.ProjectDataStore object at 0x000000000fac4fd0>
'NoneType' object has no attribute 'update'
 main_window:INFO updateStatusChanged
project_data:INFO Saving project file: C:/Users/Aaron/MSS_Trailer.osp
 main_window:INFO Saved project C:/Users/Aaron/MSS_Trailer.osp
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@      launch:INFO ------------------------------------------------
      launch:INFO    OpenShot (version 2.4.4)
      launch:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.4.4
         app:INFO libopenshot version: 0.2.3
         app:INFO platform: Windows-10-10.0.18362
         app:INFO processor: AMD64 Family 21 Model 2 Stepping 0, AuthenticAMD
         app:INFO machine: AMD64
         app:INFO python version: 3.6.4
         app:INFO qt5 version: 5.9.1
         app:INFO pyqt5 version: 5.9
   json_data:ERROR Couldn't load user settings file: Expecting value: line 1 column 1 (char 0)
    settings:ERROR Error loading settings file: Couldn't load user settings file: Expecting value: line 1 column 1 (char 0)
    language:INFO Qt Detected Languages: ['en-US']
    language:INFO LANG Environment Variable:
    language:INFO LOCALE Environment Variable:
    language:INFO OpenShot Preference Language: Default
project_data:INFO Setting default profile to HD 720p 30 fps
         app:INFO Setting font to C:\Program Files\OpenShot Video Editor\images\fonts\Ubuntu-R.ttf
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
         app:INFO Setting custom dark theme
```

Other interesting things:
1. The next run of OpenShot after this "event", as you can see in the logs above OpenShot failed to read the **PREFERENCES** file as well!! Presumably because an attempt at saving it was being made (along with the others) at program exit, and it suffered the same zero-byte-fill corruption as the other output files we see here.

1. OpenShot doesn't actually fail to load the project file on the next run (it doesn't even try), it's not until a couple of restarts later that it starts logging "invalid load key" errors.

1. In between there's an attempt at restoring a crash-recovery backup, but so far it doesn't _look_ like that's significant to me.

1. These lines right before the zeroed bytes in the logfile are certainly worth looking into:
```
     updates:ERROR Couldn't apply 'update' to update listener: <classes.project_data.ProjectDataStore object at 0x000000000fac4fd0>
'NoneType' object has no attribute 'update'
```

**Comment by SuslikV** [comment]
Also, the `project_data` at the `E238h` (or line 100) has extremely huge `['history']` key value, about 21.5 MBytes. Hardly believable that it isn't caused some kind of errors during logging (the value is OK in the log! ) but do it for the project saving only.

**Comment by ferdnyc** [comment]
@SuslikV 
> Also, the `project_data` at the `E238h` (or line 100) has extremely huge `['history']` key value, about 21.5 MBytes.

Mmm. Once upon a time, briefly, when the history-discard logic was in place to combat the exploding-history bug (#2400), I had also added code to compute and log the size of history data structures — not in the file itself, but in _memory_, which I thought was extremely useful for getting a better picture of the issue.

Especially since the in-memory size can be considerable. As I note in https://github.com/OpenShot/openshot-qt/pull/2400#issue-233408909 one 12.3 MB project file (which at the time sounded extreme, size-wise) ended up blowing up to consume **105 MB** of memory just for the undo/redo data.

Unfortunately, that baby went with the bathwater, so the `total_size()` code is no longer present in `classes.conversion`.
