### ISSUE TITLE
3D animated titles

### ISSUE THREAD

**Issue by Geo34980** [OpenShot/openshot-qt#3149]
Hi!

I want to use the 3D Anmated Titles model "Star Wars" but the list of names I want to display is far longer than the one contained in the model hence the animation is stopping before the end of the list. Is there any way to increase the number of frames ?

Can we run the .py file generated for this purpose in my directory ~/.openshot_qt/blender out of OpenShot once I have modified the number of frames in it.

Likewise, is there any way to create a new animated title from scratch or existing model, no "new title" button?
I am running OpenShot on Ubuntu 18.04

Thanks for your help.

Georges

**Comment by ferdnyc** [comment]
@Geo34980 

> I want to use the 3D Anmated Titles model "Star Wars" but the list of names I want to display is far longer than the one contained in the model hence the animation is stopping before the end of the list. Is there any way to increase the number of frames ?
> 
> Can we run the .py file generated for this purpose in my directory ~/.openshot_qt/blender out of OpenShot once I have modified the number of frames in it.

That's unlikely to work, as the number of frames stored in the Python script is matched to the length of the configured animation in the Blender file it "drives". Increasing the frame count in the Python script would generate more frames, but all of the added ones would most likely be the same as the final frame of the configured animation — nothing would move past that point.

I see two options for how you could approach this:
1. You'd have to open the `.blend` file for the animation (`spacemovie_intro.blend`, in this case) in Blender, and extend the length of the animation there, first.
    
    (And then you'd probably also have to edit the... well, if you wanted to make it work from within OpenShot you'd actually have to edit the `spacemovie_intr.xml` file that defines the animation parameters for the editor window, to increase the `end_frame` maximum value. The Python script is just a template, values like frame numbers are inserted when it's generated.)
    
    Though you could theoretically generate it with the _wrong_ values, and then edit it by hand afterwards. Still, editing the XML is just as easy, and solves the problem better and more permanently.

2. Probably easier, TBH: With a little finessing and careful editing, it shouldn't be too hard to generate _two_ (or even more) animation sequences, then splice them together so they appear as one continuous sequence. SpaceMovie _in particular_ should lend itself really well to that kind of thing, especially if you optimize your content a bit to make it workable.

    In particular, breaking the text into sections, with gaps between them, would not only provide points where an edit could be hidden, but it's a kindness to the audience as well, since it gives them moments to catch up with the reading, find their place again if they lost it, or just distract themselves briefly without missing anything.

    (The Clip cropping features may also come in handy here, because to shorten the gap when joining the two animations, you may want to have the tail end of an earlier sequence still moving off into the distance, while the start of the following sequence is overlaid on just the **bottom half** of the frame.)

> Likewise, is there any way to create a new animated title from scratch or existing model, no "new title" button?

No, sorry. Because of the difficulties inherent in option 1, basically. The animations are all based on preconfigured Blender projects, fairly complex ones in many cases, and beyond the limited configurables built into them and exposed in the Animated Title editor UI, the only way to really make modifications is using Blender itself.

(And then those modified files, unless they're very carefully edited to implement all of the same configurable parameters in the same way, would no longer be controllable by the code in OpenShot, which has a lot of expectations built into it regarding how the `.blend` files are set up.)

**Comment by Geo34980** [comment]
@ferdnyc 
Thanks for your detailed answer I will use your option 2, which I initially wanted to avoid, but it sounds the most practicable thing to do.
Best Regards,
Georges
