### ISSUE TITLE
Split Clip Dialog: Moving the play head while the video is playing stops play

### ISSUE THREAD

**Issue by xaptronic** [OpenShot/openshot-qt#3159]
When I'm using the Split Clip dialog I have the video playing so I know where I am. Since I'm splitting, I tend to want to move the play head around to find a particular section. Moving the playhead while the video is playing in this dialog stops the play back so I have to press play again. It would be nice if the play head would continue from where I drag the play head to unless I explicitly click pause.

**Comment by SuslikV** [comment]
Better not use this functionality at all. It is bugged a bit. I prefer the _Slice_ at current position directly in the _Timeline_ (right-click menu, the Timeline's cursor is over the clip).

Anyway, you may try to modify the source code of the program by yourself (I'm using _notepad++_ application for this purpose), the file `windows/cutting.py`:
https://github.com/OpenShot/openshot-qt/blob/1ec4d24b2be002eb20513fa8a4c148d30c6e4587/src/windows/cutting.py#L219-L227
just comment out the line 224, the `self.btnPlay_clicked(force="pause")` to `#self.btnPlay_clicked(force="pause")`, the start of the code lines should keep alignment:
```
    def sliderVideo_valueChanged(self, new_frame):
        if self.preview_thread and not self.sliderIgnoreSignal:
            log.info('sliderVideo_valueChanged')


            # Pause video
            #self.btnPlay_clicked(force="pause")


            # Seek to new frame
            self.preview_thread.previewFrame(new_frame)
```
or remove this lines completely:

```
    def sliderVideo_valueChanged(self, new_frame):
        if self.preview_thread and not self.sliderIgnoreSignal:
            log.info('sliderVideo_valueChanged')





            # Seek to new frame
            self.preview_thread.previewFrame(new_frame)
```

Because this is Python - all changes will apply on the next startup of the program.

**Comment by xaptronic** [comment]
Thanks for your suggestion, I'll take a crack at it.
