### ISSUE TITLE
Use color scheme from theme to shade the track / timeline area

### ISSUE THREAD

**Issue by allsey87** [OpenShot/openshot-qt#317]
The current UI in track / timeline area of the main window is distracting for users at the moment. A significant improvement would be using the color scheme from selected theme to shade this area of the main window

![example](https://cloud.githubusercontent.com/assets/3796345/18296709/f772be68-74ee-11e6-9266-2139239b38b9.png)

**Comment by peanutbutterandcrackers** [comment]
This happens when one chooses 'humanity' as the theme. Using 'humanity dark' will turn everything into a decent dark-themed UI. However, I do believe this needs to be sorted out too. It'd be cool if the timeline looked like everything else when the theme is set to 'humanity'.

@ferdnyc - Perhaps you'd like to take a look at this, too, good sir? o.O

**Comment by ferdnyc** [comment]
I don't disagree with the suggestion, but since the timeline is rendered using Qt's HTML canvas, it's not subject to the same styling as the rest of the interface. All of the QtStyle code that decorates the Qt widgets would have to be reimplemented in the CSS/JavaScript code that draws the timeline, to make it theme-aware.

A theme-aware timeline would be _nice_, no argument. But since it's purely a cosmetic change, compared to other issues that need to be addressed it just isn't a priority. I don't expect it will happen anytime soon, sorry.
