### ISSUE TITLE
Make available a callback python function to preprocess the frames

### ISSUE THREAD

**Issue by kleysonr** [OpenShot/openshot-qt#3173]
I work with Deep Learning and Computer Vision.

I would like to do some preprocessing on the frames on-the-fly before show them.

Then, I would like to implement some python function that receive the current frame and return another pre-processed frame. Then I could integrate the OpenShot with DL and CV algorithms.

The callback function should be called while previewing as well as saving the video.

**Comment by ferdnyc** [comment]
@kleysonr 

Hmm. Interesting problem! The immediate hurdle I can see in doing something like that is the fact that, while the Python bindings allow Python code to interact with libopenshot, there really isn't much support for _libopenshot_ interacting with **Python** code. All of our data-passing between the two language environments is done using JSON serializations, and as you can imagine things like entire frame buffers really don't scale.

The _**easiest**_ way to implement this, off the top of my head, would be in libopenshot as an Effect. You could attach that to any part of the Timeline, and it'd have access to do exactly as you say: Get frame images passed to it as they're constructed, make modifications, and return the modified frame back to the Timeline. That's the exact description of an Effect.

Currently the only implementation for Effects is the C++ API in libopenshot. Effects _are_ exposed to the Python bindings, but I'm not sure it would work trying to involve Python, even with a C++ "shim" (effectively)... handing frames off to the Python side of the equation during processing would be a tightrope act. **Out**-of-band, you could hack something up (as we have in OpenShot, basically), but we tend not to involve the Python side of the world in the actual decode/encode process, since it has more than enough bottlenecks as it is.

Of course, you could _easily_ do this from the Python side of things, if you drive it yourself on a frame-by-frame basis, and use intermediate disk files to pass the actual image data back and forth. For instance, here's code I wrote literally this afternoon, to benchmark frame-retrieval speed on the Timeline:
```python
#!/bin/python3

import timeit
from random import randrange
import openshot

# Define test parameters
tests = [
    {"desc": "GetFrame(47).Save(/dev/null)",
     "iter": 50,
     "rep": 20,
     "s": 'f = t.GetFrame(47); f.Save("/dev/null", 1.0)',
     "b4": "",
     },
    {"desc": "GetFrame(random).Save(/dev/null)",
     "iter": 50,
     "rep": 20,
     "s": 'frame = randrange(1, 300); f = t.GetFrame(frame); f.Save("/dev/null", 1.0)',
     "b4": ""
     },
]

# Set up testing environment
with open('LayerAlphaTest2.osp') as infile:
    json = "".join(infile.readlines())

t = openshot.Timeline(
    1280, 720, openshot.Fraction(16, 9),
    48000, 0, openshot.LAYOUT_STEREO
)
t.SetJson(json)
t.Open()

# Execute timing runs
for (n, i) in enumerate(tests):
    print("Test {}: {}, {} repetitions, {} runs".format(n, i["desc"], i["iter"], i["rep"]))
    tick = timeit.Timer(i["s"], setup=i["b4"], globals=globals())
    res = []
    for x in range(0, i["rep"]):
        res.insert(0, tick.timeit(i["iter"]))
        print(res[0], end=" ", flush=True)
    res.sort()
    print("\nMin: {}\n".format(res[0]))

t.Close()
```

That loads an OpenShot project file into an `openshot.Timeline` object (which handles creating the necessary `openshot.FFmpegReader`s for the video files imported into the project), then performs a series of `openshot.Timeline.GetFrame()` requests by frame number, and then (because it's just benchmarking) tells the Frame object to "save" its image data to `/dev/null`.

The tricky thing, I think, would be if you wanted to get at the _actual_ image data from the Python side — to say nothing of passing it back after modification.

Aside from the JSON serializations, all of our data passing from libopenshot to OpenShot is done using disk files as an intermediate step, rather than passing the data in memory. That's why objects like `openshot.Frame` have `Save()` methods (and the related `Thumbnail()` — OpenShot's PyQt5 interface uses them to request image data from the library, in the form of a filesystem path that it's written to. The Python code then loads that image from disk.

Getting data out that way would certainly be easy enough. (It's demonstrated right there in my code above, just replace the `/dev/null` path to `openshot.Frame.Save()` with a disk location.) It wouldn't be very efficient, though. (You can also do the same thing from the `openshot.Reader` classes, if you want to do all of the processing yourself and don't need the Timeline involved, but that doesn't change the data-passing situation.)

There's also the further complication that loading the modified images back into libopenshot would probably require wiring up a `QtImageReader`, since we don't currently have any API to _load_ an `openshot.Frame` directly from disk. (You can pass image _data_ to it either in `QImage` form or as raw bytes, using `openshot.Frame.AddFrame()`, but first the data has to get read into the library from somewhere. You've got the same problem of the Python/C++ divide making it difficult to move raw pixels directly between the two environments without some intermediary storage location.)
