### ISSUE TITLE
Reproducible builds

### ISSUE THREAD

**Issue by DaniellMesquita** [OpenShot/openshot-qt#3176]

**Comment by ferdnyc** [comment]
Were... you... planning to _expand_ on that, at all?

(I mean, the Travis builds are reproducible, it's just the distributed installers / AppImages that aren't. ...You could _perhaps_ argue that they ARE, it's just that they can only be reproduced on one specific set of custom-configured GitLab runners. You could **also** argue that doesn't count, especially because THEIR configuration is impossible to reproduce. And I would agree.)
