### ISSUE TITLE
File Stitching without rendering

### ISSUE THREAD

**Issue by TharenaMelishka** [OpenShot/openshot-qt#3183]
At the moment I find OpenShot can't easily handle a quantity of files in the timeline, especially if you do any time dilation or other "complex" edits on any segment, so I am editing each segment of perhaps a 5 segment video (Intro, 3 segments, conclusion) in it's own project file, rendering that file, then importing it into a master project to be.... re-rendered.  :P   

Time Dilated segments are individually edited in their own project file, rendered, and then the render is injected into the segment, and then..... rerendered 2x by the time it hits final product.  

Is there a way to just stitch the rendered files together without having to re-render a render?

**System Details:**
Irrelevant to question 

**Screenshots:** (Optional)
Irrelevant to question

**Comment by ferdnyc** [comment]
@TharenaMelishka 

Yes, but not with OpenShot.

For joining together multiple segments of a longer video without re-encoding, my recommendation is [Avidemux](http://fixounet.free.fr/avidemux/), which is _excellent_ for that job. It has a "Copy" mode which simply _**re**_-muxes existing video into a longer package, and it's very fast and completely lossless.

A couple of caveats:
1. The segments have to be exactly the same codec, resolution, etc. and ideally the same bitrate or other encoding parameters. (This is where OpenShot's constant-bitrate output is actually a boon, because as long as all exports are done with the same settings, they'll join together perfectly.
1. It takes a bit of planning to ensure that the points where the files are joined will be invisible, but that's very possible by using either black frames, a title or other still image, or a scene change. (Think of it like being a projectionist in an old, multi-reel cinema.)
1. The reason for the previous point is, when using Copy mode all of Avidemux's filters and processing are disabled — any sort of editing would require a re-encode.

The last restriction would apply to OpenShot, which is why it doesn't have any such mode. There are better tools for this job, Avidemux being IMHO the best of them.

To join videos, the process is simple:
1. Open the first section in Avidemux
1. Set your Output Format, and make sure Video Output and Audio Output are both set to Copy
1. Choose **File > Append** from the menu (or hit <kbd>Ctrl</kbd>+<kbd>A</kbd>) to load each additional segment in order
1. When everything's loaded, just hit **Save** (<kbd>Ctrl</kbd>+<kbd>S</kbd>) to write out the stitched-together video, which will be written as fast as your system can copy the data, basically.

If you're working with Matroska (`.mkv`) video, specifically, [MkvToolNix](https://mkvtoolnix.download/) can also do the same thing, and in some ways it's actually easier because you can see a list of all the loaded parts to be assembled. But it's very specific to MKV files, whereas Avidemux is very codec/container-flexible. (Except for a couple of odd holes. Like Ogg Theora, which for some reason it's never supported. And I'm not sure it handles FLAC audio, either.)

**Comment by SuslikV** [comment]
Batch the rendering of `.osp` files into one movie is nice feature. I think it was mentioned before but in some different way. Hope, it will be possible sooner or later. I see it as: _Add .osp files to the Timeline_ new feature request. With the `start`, `end`, `position` and `track's number` override (shift) adjustment before all clips added.

Meanwhile, as possible workaround I can imagine only the export of the project into the EDL files and import each Track manually later. Thus making the final project to render all in once. Not all features supported yet (transitions, effects etc. unavailable) and it is unknown is it ever will.

The mentioned renderless join of the video files has no place in OpenShot.

**Comment by ferdnyc** [comment]
> Batch the rendering of `.osp` files into one movie is nice feature. I think it was mentioned before but in some different way. Hope, it will be possible sooner or later. I see it as: _Add .osp files to the Timeline_ new feature request. With the `start`, `end`, `position` and `track's number` override (shift) adjustment before all clips added.

Mmm, that's an interesting idea, and I agree there are all sorts of reasons it would be a nice feature to have, but it doesn't really address _this_ problem where, as @TharenaMelishka says,
> OpenShot can't easily handle a quantity of files in the timeline, especially if you do any time dilation or other "complex" edits on any segment

The ability to assemble a larger project out of smaller sub-projects would be fine, but the end result can still be the same: A project that's too complex for OpenShot to work with, or to export all in one fell swoop. As we beat back the memory requirements of the export process and get OpenShot's resource consumption more under control, hopefully its ability to handle larger and more complex projects will increase, but there will always be something too ambitious for it to handle using the available system resources. (Unless we get to the point of supporting networked render farms or something.)
 
> The mentioned renderless join of the video files has no place in OpenShot.

Yeah, I tend to agree, at least _as such_, only because — like I said, **far** better tools already exist.

The way can envision something like it **possibly** being supported in OpenShot is in the form of partial pre-renders. At some point down the road, if we implement a feature where the user can ask for **parts** of their timeline to be rendered into the final export format, then just like it currently does with the preview cache, OpenShot should be able to track which of those pre-rendered sections are still valid, and automatically incorporate them into the final export instead of needing to render those sections again.

But just as with the preview cache, the management of the pre-renders would be completely automatic, with OpenShot storing them in a cache area under its own control. So they wouldn't exist as "files" per se, at least not in the sense that the user names them, loads them, or has direct access to them.

**Comment by TharenaMelishka** [comment]
I do like the option of batch rendering OSP files, with the idea that you could use fade transitions or something between them.  How cool would that be?  :)  Of course, expecting a 12 hour render time as part of that deal should be par for the course... The trick for me is still the WORKING memory.  Making small changes in a larger single project can be ... painful.  Multple images in a slide show format with transitions (what I'm working on now) is a very good example of working memory pain.  Having to close OS and re-open it to actually effectively clear undo histories and whatnot is just part of the process at this point.

I'm not upset with file stitching itself not being a part of OpenShot, I just wanted to know if I was missing something.  Should I be closing this and file the batch rendering of the OSP files as an enhancement issue instead, referencing this issue, or do you guys have a process in place for this?

**Comment by ferdnyc** [comment]
@TharenaMelishka Whoops, sorry, meant to respond to this sooner.

> Should I be closing this and file the batch rendering of the OSP files as an enhancement issue instead, referencing this issue, or do you guys have a process in place for this?

Oh, there are already multiple open issues on that topic, including (from a quick scan) at least #2452 #1698 #1230 #729.

As such, I'm going to close this as answered, I think the existing bugs track the remainder of the issue(s) raised. Thanks!
