### ISSUE TITLE
Built in Install .. Scripting? For version updates.

### ISSUE THREAD

**Issue by TharenaMelishka** [OpenShot/openshot-qt#3204]
Nothing on installing // installation issues

**Describe the new feature:**
-- Built in removal of old Program Files / Openshot Video Editor directory before installing new version?
-- Program Interior updating option (check for new updates / download / install in program gui) with option for using daily builds or most recent stable build

**Describe the solution you'd like:**
As above.  With the capacity to preserve all settings, including default directory usage (see current working solution in #3113, which currently gets destroyed every version upgrade).

**Describe alternatives you have considered:**
Installing and open shot NOT even starting up after installing new daily build... so I did it manually.  I also created a batch file / local exe to fix the settings files, with a stored copy in my workspace directory to restore my settings.

-- I also created a batch / exe to delete my log files on the regular... would be nice if there was a context option for that, too.

Thanks oodles y'all

**Comment by ferdnyc** [comment]
Just going to jump in real quick on one point...

> As above. With the capacity to preserve all settings, including default directory usage (see current working solution in #3113, which currently gets destroyed every version upgrade).

...Does it?! You're talking about the user default project functionality described in https://github.com/OpenShot/openshot-qt/issues/3113#issuecomment-562764488, correct?

...Are you editing the `_default.project` file inside the OpenShot _program_ directory, the one stored at... um... I'm not sure exactly, but somewhere under `C:\Program Files\OpenShot Video Editor\...`? If so, that's the problem — sorry, I probably wasn't clear enough there.

What you should do to create a user default project is make a _copy_ of that file, and save it in your user directory as `%USERPROFILE%\.openshot_qt\default.project` (So, typically something like <code>C:\Users\<var>username</var>\.openshot_qt\default.project</code>.) Then, you make your changes to that copy, not the original file.

If you do that, the data saved there will override the `_default.project` file in the OpenShot installation directory, and your modifications won't (shouldn't!) get overwritten on upgrades. There aren't meant to be **ANY** volatile or customizable files in our `Program Files` directory. (If there were, we'd need to store them in `C:\ProgramData\`, instead.) That way, there's nothing to worry about preserving.

**ALL** user-customized files, including settings and custom {profiles, transitions, etc...} belong somewhere in `%USERPROFILE%/.openshot_qt/`; that segregation is very intentional.

**Comment by TharenaMelishka** [comment]
See... now that makes sense.  I just went to where I found the file and changed it in place (running programs as admin so I could save) ... I had to turn batch files into executables so I could run them as admin to get around the freaking program blocking that Program Files has built into it.  

FYI default install directory for _default.project is C:\Program Files\OpenShot Video Editor\settings\

I'll copy my shiny shiny default project into .openshot_qt instead.  I am saving backups of both files though, just in case.  :P 

Bless you.  I'm an idiot, and this saves some sanity.

**Comment by ferdnyc** [comment]
On this point:

> -- Program Interior updating option (check for new updates / download / install in program gui) with option for using daily builds or most recent stable build

One reason we haven't done a lot to develop a feature like that is, it's hard to make "feel right" in a cross-platform way.
* Windows would have to download a new installer and launch it for you, at which point OpenShot would also have to quit itself so that the install could proceed. The user would need to respond to the UAC prompt authorizing the installer to run as Administrator, and then they'd have to go through the installer prompts as usual.
    InnoSetup installers do have some features for doing updates to existing installs, though honestly we've never even tried using them because it would just be twice the configs. (The installer still needs to have the _install_ mode for new users, regardless, and in the most brute-force sense that covers updates as well.)
* Linux, we have two completely separate paths:
    - Users who are running from an AppImage, which executes in a readonly environment and _can't_ update itself. (It's not really "installed" per se, anyway.)
    - Users who are running from packages provided by their distribution (or other packaging group), installed using a package manager which generally has its own update functionality built in.
* macOS... I'm really not sure how you'd do updates there, since the whole "drag this icon to the Applications folder" process is still the norm for _installs_, and that's how OpenShot is installed from its DMG file.)

We actually do have new-release **notifications** built into OpenShot — a toolbar icon will link you to the download page, when an update is available. It's just that recently we've been releasing so infrequently, nobody's seen it in forever... which is also the reason update functionality hasn't really been that pressing of an issue.

And on the other side of the coin, "Daily Builds" are actually a misnomer at this point, because a new set of packages gets built for **every** code change that's checked in — whether that means once every few days, or 15 times in one day. (And it tends to be kind of either/or on those two extremes, since a lot of our code merges happen all at once when @jonoomph goes through the list every once in a while.) So, realistically I can't imagine anyone would really WANT to be automatically updated (or even notified) _every_ time there's a new build ­— it would just get annoying. We'd have to provide some sort of "check for updates weekly/monthly/whatever" throttling if we were to offer any sort of automated Daily Build updating, which is of course doable.

Sorry, mostly just thinking out loud now. I definitely agree better update functionality would be nice to have, though unfortunately our current release process is so frustratingly manual and involved that I'm not sure automating the _user_ end of it would really work — not without better automation for the _project_ end of it, first.

**Comment by TharenaMelishka** [comment]
Re: throttled Daily Build updating:
I don't know about how others use the project, but for me, a configurable (day/time to check in a week, like Thursday at 9am) weekly update check in the daily builds would be awesome.  I try not to update during a single episode production, (because who needs to blow up their project mid-stream), just between weekly episodes. 

Again, enhancement suggestion, I know there's hurdles to jump before it gets anywhere, and really how much of a priority is it?  :)   I hadn't considered how hard that would be to do cross platform.  Chaos! :P
