### ISSUE TITLE
Incorrect output after update [letterbox]

### ISSUE THREAD

**Issue by dpw146** [OpenShot/openshot-qt#3225]
**Describe the bug**
after latest update, all video output is being put in "letterboxes" no matter the aspect ratio or the resolution chosen. raw footage is recorded at 2560x1080 (21:9) and I output via YOUTUBE HD settings with the advance settings altered to the given resolution and aspect ratio. This has worked fine previously but is now creating files that are int he correct resolution but the video has black bars top and bottom no matter what settings are used.

**Steps to reproduce the behavior:**
1. output video as YOUTUBE HD 
2. Click on advanced and change resolution to 2560x1080 and aspect ration to 21:9
3. output file

**Expected behavior**
I don't understand why this letter boxing is happening when the input video and output resolution match I expect the video to be the correct resolution with no black bars.

**System Details**
- OpenShot Version: 2.5.0-dev1
- libopenshot Version:  0.2.4-dev1
- Platform: Windows-10-10.0.18362
- Processor: AMD64 Family 16 Model 10 Stepping 0, AuthenticAMD
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.0-dev1-1581584036-99fda013-836e49fa-x86_64.exe

**Log Files**
- http://logs.openshot.org/dj14qusz8hsk79ckbuljy08qo9zq8egx/openshot-qt.zip
- http://logs.openshot.org/dj14qusz8hsk79ckbuljy08qo9zq8egx/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

![Capture](https://user-images.githubusercontent.com/61025042/74466570-629d7e80-4e8f-11ea-87c7-3df8658f8e7a.JPG)

![Capture2](https://user-images.githubusercontent.com/61025042/74467066-4ea64c80-4e90-11ea-8fcd-106e282329d8.JPG)

**Comment by SuslikV** [comment]
You are using:
2560x1080p input, about 64:27; 59.94
2560x1440p profile, 16:9; 23.98
1920x1080p output, 16:9; 23.98

It can't be rendered other way. Previously OpenShot had number of bugs where some profile settings wasn't apply and the display info didn't reflect actual settings.

By default, any imported footage when added to the _Timeline_ scaled to _Best Fit_ (look at the _Scale_ property of the added clip). You may want to adjust this to `None`.


Unfortunately, the YouTube presets in OpenShot is out of date. **Set everything manually**. Keep the fps settings unchanged from source to export.

https://support.google.com/youtube/answer/1722171

* While you using aspect close to 21:9, you need to create your own file in `profiles` folder of OpenShot (it will be deleted during update of the program - just keep copy of it). For this purpose copy existing `qhd_1440p_5994` file (same folder) and rename it to `uwhd_2560x1080p_5994` open in text editor (I'm using Notepad++) and replace the data with this one:
```
description=2.5K UWHD 1080p 59.94 fps
frame_rate_num=60000
frame_rate_den=1001
width=2560
height=1080
progressive=1
sample_aspect_num=1
sample_aspect_den=1
display_aspect_num=21
display_aspect_den=9
colorspace=709
```
Choose this `2.5K UWHD 1080p 59.94 fps` as Preview Profile in OpenShot Preferences. Restart application if needed.
* Use Profile `All Formats` (in Export)
* Use `CPU MP4 (h.264)` as target
* Use Video Profile this new `2.5K UWHD 1080p 59.94 fps`
* To get variable bitrate use `18 crf` in the _Bit Rate_ field (instead of the `bitrate Mb/s`) of _Advanced_ tab - this will make variable bitrate video
* Leave audio settings as _Audio Codec_ `aac`, _Sample Rate_ `48000`, _Channels Layout_ `Stereo`, _Bit Rate_ 192kb/s (or 256)

Unfortunately, you need to set this settings again and again during each export (bitrate/quality). This part of the program is still under the development.

**Warning.** As soon as 21:9 is far from 2560:1080 then OpenShot Transform will calculate everything according to the profiles aspect ratio!!! Small black bars still can appear at top and bottom. Thus `Best Fit` at _Scale_ is recommended - it will wash out your image because it uses only Bilinear filtering and scaling will take only few pixels in the area. But you have chosen this path yourself - better use recommended settings of YouTube for recordings. Also, try other software that handles 2560x1080 better than OpenShot currently.
