### ISSUE TITLE
"Add to timeline" dialog contains no files or only one

### ISSUE THREAD

**Issue by PontiacCZ** [OpenShot/openshot-qt#3240]
**Describe the bug:**
The "Add to timeline" (CTRL + W) dialog contains no files or only one depending on how you select files in the "Project Files" window.

**Steps to reproduce the behavior:**
1. download these two free videos in FullHD:
    - [Golden Gate Bridge](https://www.pexels.com/video/golden-gate-bridge-at-san-francisco-1994828/)
    - [Burning Charcoal Fire](https://www.pexels.com/video/burning-charcoal-fire-854692/)
2. import then into OpenShot 2.5.0 by dragging
3. activate the OpenShot app but don't click on any of the two files. Press CTRL + A to select them and then press CTRL + W - "Add to timeline" dialog appears
4. there are no files in the dialog. It looks like this:

![image](https://user-images.githubusercontent.com/9153595/75114557-3637ee00-5657-11ea-902a-7957d58a9854.png)

5. return back to the Project Files window. Now click the Golden Gate video and then, with SHIFT, the Fire video. They're both selected so they should both go into the "Add to timeline" dialog, right?
6. press CTRL + W. There is only the first selected video (Golden Gate) there. The same happens if you select the Fire video as first - then only the Fire video is present there:

![image](https://user-images.githubusercontent.com/9153595/75114595-a21a5680-5657-11ea-819c-6830bf0779df.png)

**Expected behavior:**
All selected videos should be displayed in the "Add to timeline" window

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 2.5.0
- Operating System / Distro: Windows 10 Pro x64

**Comment by ferdnyc** [comment]
Hmm. I couldn't immediately reproduce the bug as reported, but there _is_ something weird going on with selection in the Project Files list and Add to Timeline. You can see here that, after selecting all videos in the list, I _deselected_ the first one — but it was still on the list when I opened the dialog. (That's an easier problem to work around, since you can always use the :heavy_minus_sign: icon to remove the extra video from the list, but it still points to a bug in how the selection list is handled.)

![Screenshot from 2020-02-23 10-58-50](https://user-images.githubusercontent.com/538020/75115367-c5c7a780-562b-11ea-89ee-e1f9e93ec288.png)

**Comment by nanohtpc** [comment]
same problem here.... it only happens when you used the keyboard shorcuts....

**Comment by SuslikV** [comment]
Small update. Info for the developers.

The <kbd>Ctrl</kbd>+<kbd>A</kbd> selects all indexes not only first column rows for QListView.

For the Thumbnails view:

- Mouse selection - 0,0; 1,0; 2,0...;
- <kbd>Ctrl</kbd>+<kbd>A</kbd> selection - 0,0; 0,1; 0,2; 0,3; 0,4; 0,5; 1,0; 1,1...; - all six columns indexes same as in Tree/Details view)

I can forget this, so as remainder: selection algorithm in OpenShot only requires row to get the selected item (file).

The PR will be a bit later.
