### ISSUE TITLE
open my .osp project is impossible

### ISSUE THREAD

**Issue by EZ57** [OpenShot/openshot-qt#3246]
**Describe the bug:**
When I want to open an .osp project, I get an error message like "something.jpg or mp3 or mp4... cannot be find". All my files are in the same folder to avoid pb like this. I had pb with diacritics letters I have solved, but I still can't open all of my projects. 

**Steps to reproduce the behavior:**
1. Click on the .osp project, no matter in which folder your project is located.
2. Openshot is opening
3. Get this message
4. 
![image](https://user-images.githubusercontent.com/61429560/75200786-ed6f5a80-5766-11ea-90a2-43f61498d338.png)

**Expected behavior:**
Open my .osp files without pb. 

**System Details:**
- OpenShot Version 2.5.0
- Operating System Windows 10

**Comment by SuslikV** [comment]
That only means that **path has non-English letters**. If you have username in Windows that has non-English characters then you are in trouble... The only workaround I know - is to make changes to the OpenShot files `src/classes/json_data.py` and `src/classes/thumbnail.py` as mentioned here: https://github.com/OpenShot/openshot-qt/pull/3229/files 
This may solve the problem with the newly created project files, but old one - is gone for you (the repair process is cumbersome and requires `.osp` files to be manually edited, with notepad++ or similar way).

The OpenShot v2.5.0 corrupts the `.osp` files by making them **not readable forever** (and not compatible with the v2.4.4). You need to **use previous copy** of the `.osp` you have saved last in v2.4.4 (the back up file, I hope you have make them). Otherwise, **no projects saved in OpenShot v2.5.0 will work** (without mentioned patch). If Auto-saving feature is enabled in OpenShot's _Preferences_ then it again will do more harm than good for your project files.

Please, follow General Rules:
1) Make the backups of the project file time-to-time when you are working on something huge.
2) Do not update software until current project is done.

**Comment by SuslikV** [comment]
Please, attach your OpenShot's log-file to confirm the issue (compress it into `.zip`).

**Comment by ferdnyc** [comment]
The OpenShot 2.5.1 release (now available at https://openshot.org/download/) contains a fix for the project-file encoding bug present in OpenShot 2.5.0. The new release will also recognize and auto-repair damaged encoding, when opening OpenShot 2.5.0 project files.

All OpenShot 2.5.0 users are strongly urged to upgrade to OpenShot 2.5.1 ASAP. After upgrading, it's further recommended that you open any projects previously saved from OpenShot 2.5.0 and re-save them, which will correct any encoding issues that may be present.
