### ISSUE TITLE
[2.5.0] Importing 240 FPS footage is reported as 999999 instead of 240000

### ISSUE THREAD

**Issue by mkarg** [OpenShot/openshot-qt#3257]
**Describe the bug:**
The FPS of imported 240 FPS footage is reported as 999999 instead of 240000.

**Steps to reproduce the behavior:**
1. Import 240 FPS footage
2. Display file properties

**Expected behavior:**
Displays 240000 1001.

**Actual behavior:**
* 240 FPS: Displays 999999 1001 (but JSON view actually says 240000)
* 30 FPS: Display 30000 1001 (and JSON view says 30000 1001)

**System Details:**
- OpenShot Version [e.g. 2.4.3]: [2.5.0]
- Operating System / Distro: Windows 10

**Log Files:**
N/A

**Exception / Stacktrace:**
N/A

**Screenshots:** (Optional)
N/A

**Comment by SuslikV** [comment]
Please share the file sample (short one) to test with.

**Comment by ferdnyc** [comment]
@mkarg 

> * 240 FPS: Displays 999999 1001 (but JSON view actually says 240000)

Well, that's definitely odd/wrong, yeah! Must just be a GUI bug, if the JSON is correct. Is it actually _`999999`_ (six digits), or just _`99999`_ (5 digits)?

If it's only showing five `9`s, the issue is almost definitely that `240000` is simply too large for the field. But if it's showing `999999` instead of `240000`, then I'm completely at a loss.

> * 30 FPS: Display 30000 1001 (and JSON view says 30000 1001)

This one, though, I think is probably correct. 30000:1001 is actually a _very_ common frame rate for broadcast media, as it's the frame rate video cameras have traditionally shot at: 29.97 FPS.

([Here's a page that includes a video explainer](https://www.diyphotography.net/camera-shoots-29-97fps-not-30fps-doesnt-really-matter/) as to the hows and whys 29.97 became the "standard" NTSC frame rate, but really it's not important. What is important is that it's not _quite_ 30 FPS, but still quite correct. It would be odd if an erroneous frame rate displayed that figure exactly, I'd expect more random-looking numbers.)

"Real" 30 FPS didn't become common until HD formats like ATSC came around, for the most part. The de facto standard for web video was 25 FPS, pre-HD, and film has been shot at 24 FPS for quite some time.

Which leads us to the other common frame rate you'll see in the wild, 24000:1001 AKA 23.976 FPS. Which I believe is 24 FPS film converted to video, maybe? Or it's something to do with PAL.

**Comment by oupala** [comment]
Hi, I encountered the same issue with *OpenShot-v2.5.1-x86_64.AppImage*.

I tried to download the last daily build and it seems that the bug is fixed altough I had to delete and to import the movie again. The daily build I used is *OpenShot-v2.5.1-dev2-daily-7481-42f9aeec-92ff6084-x86_64.AppImage*.

I hope this comment can help. And I'm looking forward to see a new release of OpenShot.

**Comment by oupala** [comment]
I'd like to see this issue re-opened. Would stale bot do it for me?

**Comment by JacksonRG** [comment]
@oupala we can reopen it if there's something we need to fix. But as I understand it, this issue is fixed in the daily build, and thus, the fix will be included in the next stable release.

**Comment by oupala** [comment]
I tought that it was a good idea to re-open this issue so that the issue can get *more attention* and may be checked by other people than me before the next stable release.

**Comment by JacksonRG** [comment]
That makes sense. I can make sure this gets tested as we prepare a release candidate.

**Comment by Colorjet3** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Importing 240 FPS footage is reported as 999999 instead of 240000](https://trello.com/c/Mn7ZBo9z/85-importing-240-fps-footage-is-reported-as-999999-instead-of-240000)
