### ISSUE TITLE
The export of an accelerated video shows the wrong position in the movie.

### ISSUE THREAD

**Issue by RobTranquillo** [OpenShot/openshot-qt#3260]
**Beschreiben Sie den Fehler**

The export of an accelerated video shows the wrong position in the movie.
The preview in the program still showed the correct position.

**Schritte zum Reproduzieren des Verhaltens**
1. Import movie. Infos from VLC:

*.mkv
Codec: H264 - MPEG-4 AVC (part 10) (avc1)
Videoauflösung: 1920x1080
Bildwiederholrate: 60.002400
Ausrichtung: Oben links
Grundfarben: ITU-R BT.709
Farbübertragungsfunktion: ITU-R BT.709
Farbraum: ITU-R BT.601 Bereich

Codec: MPEG AAC Audio (mp4a)
Kanäle: Stereo
Abtastrate: 44100 Hz
Bits pro Sample: 32

2. cut out a part of it and move it to the start point (left border of thetimeline).
3. Accelerate it four times.
4. Play it. It shows the correct part (with the correct speed)
5. Export it to h264 with preset "HD 1080p 50fps (1920x1080)"
6. play in vlc or other player, it show the wrong part of the Video

**Erwartetes Verhalten**

It should export the same part of the vIdeo like i see in the preview.

**Systemdetails**
- OpenShot Version: 2.5.0-dev1
- libopenshot Version:  0.2.4-dev1
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['de-DE', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.0-dev1-1582842112-4f591c7b-beb3a4b2-x86_64.exe

**Logdateien**
- http://logs.openshot.org/p6wqzshyjx4qjv1206w9w5xp6t25nyr0/openshot-qt.zip
- http://logs.openshot.org/p6wqzshyjx4qjv1206w9w5xp6t25nyr0/libopenshot.zip

**Ausnahme / Stapelverfolgung**
```No stacktrace found in log files```

**Bildschirmfotos** (Optional)

Please have a look to the bug i file on your website, because there is a link to  a nextcloud with more material;

1.) my input video.
2.) The export of the wrong part.
3.) And a recording in which I reproduce the whole bug.

Thanks

**Comment by RobTranquillo** [comment]
I updated the issue above with the exact name of the preset i use: "HD 1080p 50fps (1920x1080)".

And, with further experimentation I found out that with the default preset - HDV 720p 30fps, the **correct range is exported**.

The preset "HDV 1080 25p 1920x1080 (1920x1080)" produces the same error as the first reported faulty preset "HD 1080p 50fps (1920x1080)", but with a still different section of the video.

**Comment by N3WWN** [comment]
This may be due to a known issue where keyframes don't scale properly if the project profile is changed after adding keyframed items... or the export profile is not the same as the project profile.  

This was listed as fixed in issue #1034 but the commit wasn't readily available.

But, for clarification, are you saying that a project created with the "HD 1080p 60fps (1920x1080)" profile does not export properly at "HDV 1080 25p 1920x1080 (1920x1080)" or 
"HD 1080p 50fps (1920x1080)" but _DOES_ export properly at "HDV 720p 30fps"?  

If that's the case, perhaps there's an issue with scaling to "uneven" fractional frame rates.

i.e. 60 fps -> 30 fps (0.5x frame rate) works but 60 fps -> 25 fps (0.41666...x frame rate) and 60 fps -> 50 fps (0.8333...x frame rate) doesn't.

**Comment by RobTranquillo** [comment]
> This may be due to a known issue where keyframes don't scale properly if the project profile is changed after adding keyframed items... or the export profile is not the same as the project profile.

The scecond one is the issue in my case.

> But, for clarification, are you saying that a project created with the "HD 1080p 60fps (1920x1080)" profile does not export properly at "HDV 1080 25p 1920x1080 (1920x1080)" or
> "HD 1080p 50fps (1920x1080)" but _DOES_ export properly at "HDV 720p 30fps"?
> 
> If that's the case, perhaps there's an issue with scaling to "uneven" fractional frame rates.
> 
> i.e. 60 fps -> 30 fps (0.5x frame rate) works but 60 fps -> 25 fps (0.41666...x frame rate) and 60 fps -> 50 fps (0.8333...x frame rate) doesn't.

All I can say is that I used the default profile ("HD 720p 30 fps (1280x720)"), imported my files (which are 1920x1080, 60fps) and tried to export them with the default "HD 1080p 50fps (1920x1080)" preset.

In the meantime, I'm also exploring that the exact same problem (accelerated clips show wrong areas) occurs when a different profile is selected. In detail:
1) My project with the profile "HD 720p 30 fps (1280x720)" and 1080p@50fps material in it.
2) Change the profile to "HD 1080p 50fps (1920x1080)".
3) While preview, accelerated parts that show the wrong area.

Hope it helps.
Best

**Comment by User4martin** [comment]
From what I understand (roughly), on the following example:
origin 60 fps
profile 30 fps

Any data added (latest when added to timeline, maybe earlier) is prepared/pre-calculated to 30 frames. (in this case, every 2nd frame gets thrown out)

Side-effects include that if later more frames are needed, they are not avail, and frames will be duplicated instead. But that is not the main issue here.

When setting a clip to 8X, then the Time property for each output frame is set to the input frame that will be mapped to this frame.

Now the problem arises if the final render uses a diff fps (eg 50 fps). Fill-frames will be generated.

But something else must be happen (or missing).

In the example for the accelerated clip the first frame's time may be 3000 (pointing to the 3000th frame of the input), the 2nd frame's time would be 3008 (8 frames further at 8X).

What happens if I render at 50 fps (for a project with profile 30fps)?

1) 
Does the origin/input get re-mapped to 50 frames (every 6th frame thrown out)?
In that case the Time values would need to be remapped too. each: t = t * 50 / 30 ?

or
2)
Is the previously down-graded 30fps input still used, and some frames are duplicated?
In this case I do not see why the wrong time-span is embedded, unless the TIME values are re-mapped, while they should not?

**Comment by SuslikV** [comment]
@User4martin clip always has FPS of the Timeline (no matter what source is). All other manipulations with the time are based on this (Timelines FPS) of the clip. Fast/slow forward uses frames (Timeline's values) as base during the animation creation (not time in seconds!), thus strange things happens...
