### ISSUE TITLE
Arbitrary clip speed setting?

### ISSUE THREAD

**Issue by nettoyeurny** [OpenShot/openshot-qt#327]
I've been looking for a way to set arbitrary clip speeds (e.g., play a clip at 1.5x the regular speed, not just the powers of two that are available through the Time context menu). I believe this option existed in OpenShot 1.3, but it seems to be gone now. I'm using OpenShot 2.1.0 on Mac OS X and Linux. Any advice would be appreciated!

**Comment by jonoomph** [comment]
This can be achieved by manually setting a Time keyframe. Take a look at what keyframes are added when you use the context menu presets (2x, 4x, etc...), using the Properties view. Good luck.

**Comment by ckdanny** [comment]
When I changed the time, there is nothing happened. The duration is no change.
But I use the default one (e.g. 2x from right-click menu, the duration will change) 
![Uploading 2016-11-23 15_13_27-Untitled Project [HDV 720 24p] - OpenShot Video Editor.png…]()

May I know if I can change the speed dynamically?

**Comment by JoeHonk** [comment]
I have this same issue in OS2. OS1 had the speed setting that could be set to a specific value.  If I wanted to render a time-lapse video to the same length as an external audio source, I could simply calculate the length of the video divided by the length of the audio, and enter that number. In OS2 it would appear that this method is more complex, but may allow more precision. A more detailed way to perform this is OS2 would be appreciated.  
![image](https://cloud.githubusercontent.com/assets/19998583/25672497/6a0a545c-2ff9-11e7-8e01-1cac36b6e7b2.png)

**Comment by Noino** [comment]
> This can be achieved by manually setting a Time keyframe. Take a look at what keyframes are added when you use the context menu presets (2x, 4x, etc...), using the Properties view. Good luck.

Clearly there is a major usability issue here, and instead of actually telling us how the program works, you come across as arrogantly giving the obvious hint and telling people go figure it out dumdum, because is sure aint obvious how the time property works on first glance.

So, heres the gist of it:

Say you have a clip that is 37.2 seconds long at 30 frames per second and you want to speed it up by 1.5x. To accomplish this you need to:
* set the End property to 37.2/1.5=**24.8** seconds
* set your timeline cursor before or at frame 1 of the clip and insert a keyframe for the time property with the value **1**
* set your timeline cursor at the last visible frame of the clip (at 24.8 seconds) and insert a keyframe for the time property with the value 37.2*30=**1116**, aka. the total number of frames in the clip. Also, be sure to use precision here, setting the timeline cursor after the clip will select a frame after 24.8 seconds even though the timeline only shows you 24.8 seconds worth of clip on it.

**Comment by stevoisiak** [comment]
If the method to adjust video speed has changed, the tutorial on OpenShot's website should be updated.

https://www.openshot.org/blog/2009/07/16/slow-it-down-no-wait-speed-it-up/

**Comment by ironbelly** [comment]
Yep, agree across the board with the last 2 points.  Why not just have a custom speed option somewhere, this seems insane that the only solution is the one generously provided by Noino above.  Pulling out a calculator to manually figure out the frames need to accommodate a custom speed?  What sadist comes up with this kind of thing?

**Comment by ferdnyc** [comment]
> If the method to adjust video speed has changed, the tutorial on OpenShot's website should be updated.
> 
> https://www.openshot.org/blog/2009/07/16/slow-it-down-no-wait-speed-it-up/

@Stevoisiak 

That's not a tutorial. It's a development blog post containing a preview of an in-development feature, from _ten years ago_. Ultimately the feature that made it into the final release took a completely different form, so nothing there has any applicability to OpenShot 2.4.x. But scrubbing the internet, or even just the project blog, of every old reference to something that was subsequently changed... that just feels like an awful lot of work.

The actual documentation on the Time features is in the [User Guide](https://cdn.openshot.org/static/files/user-guide/clips.html#preset-menu), and is admittedly _extremely_ spare. (Pull requests welcome!) But it doesn't contain any wrong/misleading information, because the manual is at least "sorta" kept up to date.

**Comment by Stevoisiak** [comment]
> That's not a tutorial. It's a development blog post containing a preview of an in-development feature, from _ten years ago_. Ultimately the feature that made it into the final release took a completely different form, so nothing there has any applicability to OpenShot 2.4.x. But scrubbing the internet, or even just the project blog, of every old reference to something that was subsequently changed... that just feels like an awful lot of work.

@ferdnyc That blog post is the [first result](https://user-images.githubusercontent.com/1330770/62805783-06f8cf80-babf-11e9-8b82-b82ed2a2af86.png) when searching how to speed up a clip in OpenShot. I hadn't realized the feature was implemented differently. If a more accurate guide is available, it may be worth adding a note linking to it.

**Comment by k3wals** [comment]
Rather than dealing with the cryptic properties setting of the clip within OpenShot, I chose to hack the project file (.ods) and adjust the clip end point time value. I haven't noticed any negative side-effects although my project is very basic.

In my case, I had to speed up a clip so I'm not sure if similar process would work for slow down.

1. Import clip and place into timeline, align start of clip.
2. Extend the clip first to go beyond how much you need to extend. Right click on clip and _Time>Slow>Forward>1/2x_ (This seems to enable the "Time" property from the default 1.0 value)
3. On another track (different clip), I created a volume keyframe (with no actual change) in the spot I want my clip to end.
4. Close OpenShot
5. Open *.ods file in NotePad++ (helps to have [JSON-Viewer](https://github.com/kapilratnani/JSON-Viewer) plugin)
6. Find the volume keymarker value that you set in step 3. 
Ex. _clips>0>volume>Points>1>co>X>**1061**_
7. Now find the time (ending) parameter for the clip you want to adjust. 
Ex. _clips>1>time>Points>1>co>X:**1584**_
8. Change **1584** to value you found in Step 6 (**1061**) and save file.
9. Reopen Openshot and project and trim away excess to allow for Openshot to change the Duration parameter to be correct.

**Comment by arroos** [comment]
Here's a simpler way that borrows elements from k3wals and Noino's replies.

1. Right click the clip and select Time/Normal/Forward/1x to enable Time key-frames.
2. Right click the clip and select Properties to enable the properties screen.
3. Move the cursor to the last frame of the clip and note the value of the Time property.
4. In the properties browser, change the End property to set the length of the clip to whatever you want it to be (making it longer will slow it down, shorter will speed it up). 
5. Move the cursor to the last frame of the clip.
6. In the properties browser change the Time property back to the value noted in step 3.

Done!

Note that changing the speed of a clip can introduce audio artifacts.

**Comment by cnovel** [comment]
I don't really care about hacks our whatever. OpenShot is branded as "wonderfully simple and powerful". Having to deal with keyframes, noting timeproperty value, changing end value isn't what I call "wonderfully simple". It should be possible to specify a speed factor (1 being normal speed, 0.5 50% slower and 2 twice the speed) in a field and having all these values computed by the software.

**Comment by L3P3** [comment]
I think if you "resize" a clip by dragging one of its horizontal edges, this time scaling should be done automatically. It would be simple to implement that, I am very sure. I could do that but have not worked with the OS code before and have no time right now. Maybe someone here has the time to do it. Maybe I try to implement it later and do a pull request then... It is a very crucial feature I think.

**Comment by maboleth** [comment]
> I don't really care about hacks or whatever. OpenShot is branded as "wonderfully simple and powerful". Having to deal with keyframes, noting timeproperty value, changing end value isn't what I call "wonderfully simple". It should be possible to specify a speed factor (1 being normal speed, 0.5 50% slower and 2 twice the speed) in a field and having all these values computed by the software.

Absolutely. There goes my uninstall and trying other software.

**Comment by alexmojaki** [comment]
> Absolutely. There goes my uninstall and trying other software.

@maboleth I'm interested to hear your findings...

> I think if you "resize" a clip by dragging one of its horizontal edges, this time scaling should be done automatically.

This also seemed like the obvious solution to me, but I suppose dragging already adjusts the point where a clip is sliced from a larger clip. Perhaps holding down a modifier like Ctrl would be the best UI?

**Comment by alexmojaki** [comment]
> Perhaps holding down a modifier like Ctrl would be the best UI?

Well I've switched to Kdenlive, it's going great, and I was pleasantly surprised to find that this is *exactly* how it works there. Used it a bunch.

**Comment by ahmedam55** [comment]
Thanks for the help @arroos !

**Comment by Jossnaz** [comment]
> Here's a simpler way that borrows elements from k3wals and Noino's replies.
> 
> 1. Right click the clip and select Time/Normal/Forward/1x to enable Time key-frames.
> 2. Right click the clip and select Properties to enable the properties screen.
> 3. Move the cursor to the last frame of the clip and note the value of the Time property.
> 4. In the properties browser, change the End property to set the length of the clip to whatever you want it to be (making it longer will slow it down, shorter will speed it up).
> 5. Move the cursor to the last frame of the clip.
> 6. In the properties browser change the Time property back to the value noted in step 3.
> 
> Done!
> 
> Note that changing the speed of a clip can introduce audio artifacts.

doesnt work

when moving to last frame the time frame is already set to be the number from step 3 but nothing moves

**Comment by OpenSauce04** [comment]
> 
> 
> > Here's a simpler way that borrows elements from k3wals and Noino's replies.
> > 
> > 1. Right click the clip and select Time/Normal/Forward/1x to enable Time key-frames.
> > 2. Right click the clip and select Properties to enable the properties screen.
> > 3. Move the cursor to the last frame of the clip and note the value of the Time property.
> > 4. In the properties browser, change the End property to set the length of the clip to whatever you want it to be (making it longer will slow it down, shorter will speed it up).
> > 5. Move the cursor to the last frame of the clip.
> > 6. In the properties browser change the Time property back to the value noted in step 3.
> > 
> > Done!
> > Note that changing the speed of a clip can introduce audio artifacts.
> 
> doesnt work
> 
> when moving to last frame the time frame is already set to be the number from step 3 but nothing moves aka the video just freezes for the extra amount of time added

Same here

**Comment by Jossnaz** [comment]
@OpenSauce04 
I switched to
Kdenlive
as mentioned by @alexmojaki 
you can slow down the clip with ctrl + click and drag just like he mentioned

**Comment by OpenSauce04** [comment]
> @OpenSauce04 
> I switched to
> Kdenlive
> as mentioned by @alexmojaki 
> you can slow down the clip with ctrl + click and drag just like he mentioned

So did I. It really is just a baseline feature

**Comment by PaddleStroke** [comment]
I totally agree with what has been said. 
After 2 days using OpenShot and being neck deep in an edit, I realise that I'm stuck because of that missing speed feature.
It kind of feel like a feature which should implemented ten years ago. And from what I read it was actually implemented ten years ago.

**Comment by DableUTeeF** [comment]
> 
> 
> > Perhaps holding down a modifier like Ctrl would be the best UI?
> 
> Well I've switched to Kdenlive, it's going great, and I was pleasantly surprised to find that this is _exactly_ how it works there. Used it a bunch.

This really solve my problem.
Thanks.

**Comment by L3P3** [comment]
I went over to shotcut, it works very well.

**Comment by doctormo** [comment]
I'm stuck having to reprogram openshot instead of do video work. Which is a terrible shame.

**Comment by quasilyte** [comment]
OpenShot is getting on par with GIMP at being unpleasant to use for me. :)
Having to use a calculator every time I want to speed something up by x3 or x1.5 is annoying; and it's also error-prone as the method will slightly differ for an entire clip and portion of it (might also depend on the position of the clip, but I'm unsure). A software like OpenShot should handle this complexity for the user in my opinion.

**Comment by Colorjet3** [comment]
Hello @quasilyte Agreed regarding the complexity of calculating the customized "speed".  All I can tell you is that there is a ticket in the queue to enhance this process.  What I can not provide is an ETA on the enhancement.

**Comment by rwilbur** [comment]
I also agree this would be a wonderful thing to have. As it stands now this makes it difficult enough to use that OpenShot is pretty much a non-starter for me to use for video editing.
