### ISSUE TITLE
Fast-Forward is rendered from incorrect location (property from previous clip on timeline)

### ISSUE THREAD

**Issue by User4martin** [OpenShot/openshot-qt#3274]
I have a project where I select part of the input video (h.265 4K at 60 frames/sec): 
"split - keep both" on either side of the desired block.
I then set the speed to fast forward 8X.

The resulting clip has 
- a start time of 416.92 (just before the 7th minute) 
- and end time of 431.42
That makes about 15 seconds, which is the time it takes at 8X (At normal speed it is 2 minutes).
- The "Time" property is 10,355.00

The preview (albeit slow) shows the correct content.

When I render the video, the result contains incorrect data.
Instead of the selected time part, it shows an earlier part (starting at around 5:30 of the original video).

5:30 is the start of the **previous clip** on the same timeline (out of the same input file)

I have rendered the result as "mp4 h.265" HD720 30fps
I have also tried to render to 60 fps and gotten the same error.

**Comment by User4martin** [comment]
Introducing another clip (of the same input file) right before the fast bit does however not help. So maybe the 5:30 is coincidence.

**Comment by SuslikV** [comment]
> * The "Time" property is 10,355.00

This is animated property (it changes in time), so doesn't make sense until Timeline's frame mentioned at which this was taken. Navigate to the Start of the new clip and you'll find (Time property) what frame number of the clip (not file, because the clip has FPS of the Timeline) is mapped to the start point on the Timeline. Same to the End of the clip. Technical details is here: https://github.com/OpenShot/openshot-qt/issues/3254 (the only difference is that there slowing of the clip is used, math and logic is the same)

The issue looks similar to the: https://github.com/OpenShot/openshot-qt/issues/3260  Do you see it as same as your issue?

**Comment by User4martin** [comment]
It does indeed sound like #3260 (I searched for fast and speed, but not accelerated, so I did not see it).
So for now, this (my report) can be marked as duplicate.


I was able to reproduce this, verifying that it is based on the pre-selected ("Choose profile") and final frame rate (export dialog) being different.
