### ISSUE TITLE
MOV counterclockwise rotation

### ISSUE THREAD

**Issue by nicolesharp100** [OpenShot/openshot-qt#3286]
There appears to be a bug in OpenShot 2.5.1 for Microsoft Windows 10 that prevents rotating a MOV file by 90 degrees counterclockwise.  Rotating 90 degrees clockwise works, but cannot be repeated to reach a 270-degree clockwise rotation.  A workaround is to export the MOV file to MP4, and then rotate the MP4 file by 90 degrees counterclockwise.

**Comment by ferdnyc** [comment]
> There appears to be a bug in OpenShot 2.5.1 for Microsoft Windows 10 that prevents rotating a MOV file by 90 degrees counterclockwise. Rotating 90 degrees clockwise works, but cannot be repeated to reach a 270-degree clockwise rotation. A workaround is to export the MOV file to MP4, and then rotate the MP4 file by 90 degrees counterclockwise.

Hmm. I suspect it's not an issue with the MOV file itself, but rather with its intrinsic rotation. My guess is you've encountered our intrinsic-rotation bug (#2794). Most likely your original MOV file has a Rotation parameter set in its file metadata (you can check that by selecting File Properties for its entry in the Project File list, and opening the Output section of the dialog. In the JSON data there, the `"metadata"` section will probably contain a `"rotate"` key with a rotation value set. 

Here's an (abbreviated) example from a video I recorded vertically on my phone (only for testing purposes, I'm not a monster):
```json
{
  "channel_layout": 3,
  "channels": 2,
  "display_ratio": {
    "den": 9,
    "num": 16
  },
  "duration": 1.3226666450500488,
  "file_size": "4521614",
  "media_type": "video",
  "metadata": {
    "com.android.version": "7.0",
    "compatible_brands": "isommp42",
    "major_brand": "mp42",
    "minor_version": "0",
    "rotate": "90"
  },
```

Right now, OpenShot does unfortunately have a bug that prevents automatically-rotated videos from being _manually_ rotated back to their starting orientation. As you discovered, re-encoding the video to remove the built-in rotation serves as a workaround.

(If you'd be able to confirm that the original MOV file does have a `"rotation"` set in its metadata, that'd be helpful because then I can log this as a duplicate of #2794. Thanks!)

**Comment by SuslikV** [comment]
https://github.com/OpenShot/openshot-qt/issues/2794#issuecomment-493786881 (small value at _Rotation_ as quick workaround)

**Comment by ferdnyc** [comment]
Ah, yes! Also that. Forgot about that one, thanks @SuslikV
