### ISSUE TITLE
Not truly exporting in HD

### ISSUE THREAD

**Issue by cleveopiyo** [OpenShot/openshot-qt#3289]
I make NBA compilation videos where I compile a bunch of the best NBA plays for YouTube and when I export the videos with the YouTube HD setting in 720p and 30 fps it still comes out quite grainy and just does not look high quality. Is there a way this can be fixed or a different setting I need to be exporting in because I have even tried other HD settings and nothing is working

**Comment by ferdnyc** [comment]
First question, what are you using for source video? Your export can only look as good as the original source content, so you need to be sure you're working with the highest-quality input files possible.

Second, what profile setting are you using for your project — not the _export_ parameters, but the profile selected for the timeline you're editing on? (The profile is listed in the title bar of the OpenShot main window, or you can click the "Choose Profile" toolbar icon to bring up the selection dialog. If you want to export 720p @ 30fps, make sure you're editing your project in 720p @ 30fps to begin with.)

Last but not least, if you really want to maximize output quality (at the expense of _lots_ of disk space and a pretty slow encode), instead of selecting the YouTube HD target, select the generic MP4 output target, which exports at almost twice the bitrate of YouTube HD:

![image](https://user-images.githubusercontent.com/538020/76395511-daa37b00-634d-11ea-953e-3c2d99d994dd.png)

**Comment by SuslikV** [comment]
YouTube encoding profile is out of date in OpenShot. Follow the @ferdnyc recommendations and try to specify at the Advanced tab of the Export the quality as `18 crf` instead of bitrate. Screenshot of required field is in this post: https://github.com/OpenShot/openshot-qt/pull/2967#issue-313345975

**Comment by ferdnyc** [comment]
> YouTube encoding profile is out of date in OpenShot. Follow the @ferdnyc recommendations and try to specify at the Advanced tab of the Export the quality as `18 crf` instead of bitrate.

Hmm... that's an _option_, sure, but IIRC YouTube recommend fixed-bitrate encoding for files being uploaded to their service. "We'll take care of reencoding it for efficiency," is the impression I got.

(It's just that their recommended bitrates are something like 15 - 20 Mbps, depending on frame rate and resolution. Whereas our YouTube HD profile only goes up to 8 Mbps on "High". At least MP4 on "High" is 15 Mbps.)

**Comment by SuslikV** [comment]
>... YouTube recommend fixed-bitrate encoding

Maybe it was long time ago? When H.264 is in use the variable bitrate (I can say "no padding") is welcomed (the bitrate itself mentioned only for reference):
https://support.google.com/youtube/answer/1722171

**Comment by ferdnyc** [comment]
@SuslikV 

Huh, yeah that page has changed a _lot_ since I last looked at it. (Like a year-ish ago?)

At the time I was looking in the context of our 60fps and 4K profiles, which is when I discovered that our "High" bitrate for YouTube HD was far below the recommended bitrates (still something of a concern).

But now it seems they've embraced VBR, which makes sense, though they still recommend bitrate targets that are quite a bit higher than our output parameters, if users happen to be exporting at high resolution or FPS. Especially since their targets are VBR-based; exporting the same bitrate as CBR won't have the same overall quality.

...Still, for 720p 30fps SDR video, their recommended bitrate is only 5 Mbps, and our YouTube HD profile comes in at 8 Mbps on High quality mode, so that shouldn't have been an issue for @cleveopiyo regardless. Strange.
