### ISSUE TITLE
Mit dem hellen Theme, Spuren sind trotzdem schwarz...

### ISSUE THREAD

**Issue by accorinti** [OpenShot/openshot-qt#3325]
![screenShot](https://user-images.githubusercontent.com/10834155/77822906-4845fa00-70f7-11ea-852a-6f5fa01c6c95.jpg)
**Beschreiben Sie den Fehler**
Mit dem hellen Theme, Spuren sind trotzdem schwarz und die Knöpfe, um die Bereiche kleiner/größer zu machen unsichtbar

**Schritte zum Reproduzieren des Verhaltens**
1. Öffnen

**Erwartetes Verhalten**
S. oben.

**Systemdetails**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['de-DE', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1585351843-166f6938-232f3f79-x86_64.exe

**Logdateien**
- http://logs.openshot.org/b8ryqu1igucj60aukgmhjrdvamdn49rm/openshot-qt.zip
- http://logs.openshot.org/b8ryqu1igucj60aukgmhjrdvamdn49rm/libopenshot.zip

**Ausnahme / Stapelverfolgung**
```No stacktrace found in log files```

**Bildschirmfotos** (Optional)
![screenShot](https://user-images.githubusercontent.com/10834155/77822914-614eab00-70f7-11ea-8821-d216e50f18b8.jpg)

**Comment by SuslikV** [comment]
This is by design. No plans to change this (unfortunately).

**Comment by accorinti** [comment]
It is by design that you cannot see the buttons for making smaller/bigger the sections???

**Comment by SuslikV** [comment]
Absolutely.

**Comment by accorinti** [comment]
I hope someone with common sense is reading this and has at least an idea for a workaround.
Anyway, thanks for this super software and happy easter.

**Comment by SuslikV** [comment]
Qt has different styles per platforms. On Windows, by default there is no any sizing elements shown (only QSizeGrip for main window at the corner - other is dialog windows). All elements can be configured by stylesheets of Qt.

**Comment by accorinti** [comment]
Of course there are sizing elements shown on Windows...
![Clipboard01](https://user-images.githubusercontent.com/10834155/79065758-f5517280-7cb2-11ea-968a-39e370aff25a.jpg)

**Comment by SuslikV** [comment]
Feel free to report to Qt. Or maybe you wish this elements to be hidden for dark theme too?

**Comment by accorinti** [comment]
No, I would like to have them in the light theme... I think it's a bug that they are not visible, dont you think?

**Comment by SuslikV** [comment]
Only "Fusion" style (set for Dark theme) has this element.

**Comment by accorinti** [comment]
Nope, the light style has it too, you just cant see them, because they are white... But if I move around the mouse and search a while I can find them...
Come on, this is a little bug. On the light theme the elements should be black or at least grey.
![IMG_20200412_133256](https://user-images.githubusercontent.com/10834155/79067822-998ee580-7cc2-11ea-82a2-8afeaa7724c4.jpg)

**Comment by SuslikV** [comment]
You don't need to aim precisely at this point but whole edge (line) is interactive.

**Comment by ferdnyc** [comment]
@accorinti 

Oh, wow, the splitter grips (in particular) really are _invisible_ in the light theme on your setup, huh? They're kind of hard to see in the light theme on my Linux box, but they're still _there_.

I suspect this is a Windows theme issue, specifically, since Windows would presumably be using Qt's 'windows' style by default. The Linux default already is Fusion (which is why @SuslikV 's PR #3371 initially confused me, because on Linux it has absolutely no effect vs. the existing "Humanity" theme) so the results there are _slightly_ better.

Still not great, though, which appears to be a general issue when using standard Qt styles with light color schemes.

It's possible, at least under Linux, to force an application to run with any style you want by setting the environment variable `QT_STYLE_OVERRIDE` to the name of the desired style. (A list of available styles is shown in the `qtdiag` output, if that's available on the system. QtCreator will also show a list of styles in a submenu underneath Tools > Form Designer.)

Normally under Linux, like I said Fusion is the default, and with the light theme that looks like this:

![image](https://user-images.githubusercontent.com/538020/79334136-bbb87b80-7eed-11ea-8333-58fc756ba16b.png)

If you peer very, _very_ closely, and possibly zoom in a bit, you can eventually spot the splitter grips. (Just to the lower left of the "Timeline" dock titlebar, for example.) But they're still pretty missable.

If I use `QT_STYLE_OVERRIDE=windows` to launch OpenShot, though, I end up with _this_:

![image](https://user-images.githubusercontent.com/538020/79334279-fa4e3600-7eed-11ea-9343-e5f63e78fa3b.png)

As you pointed out, they've gone from "hard to find" to **completely** invisible.

Worst of all, it really does seem like that's Qt's _intent_ with their built-in styles, in recent releases. Here's what OpenShot looks like if I switch the base style for our "Humanity: Dark" color scheme over to `"windows"`:

![image](https://user-images.githubusercontent.com/538020/79338258-fb369600-7ef4-11ea-869f-77e669351021.png)

Just as invisible! It's only because we're _forcing_ the Fusion style, for the dark theme, that the splitter grips are visible at all.

I suspect this has everything to do with them moving away from the traditional QMainWindow interface — something there's even been discussion of eliminating from Qt6 entirely — and embracing their new QML / QtQuick interface paradigm and accompanying design language. The new paradigm is very much inspired by the mobile-device form factor and touchscreen-focused interactions, where the notion of having interface elements that you resize by dragging a visible divider between them would be completely alien. Sometimes things are resizable on a mobile device, but it's always by simply swiping in some direction or against some edge, not by dragging actual borders of things.

You can see the effects of that shift even in their [Style documentation](https://doc.qt.io/qt-5/gallery.html), which (in addition to being completely messed up, formatting-wise, clearly out of neglect) shows example windows without a single visibly-resizable element. Even the window corners have no resize triangles showing, in any of the displayed style versions.

All of which is to say: this is a deceptively tricky problem, and I am not entirely sure how we can best address it.

**Comment by ferdnyc** [comment]
Certainly, we could accept @SuslikV 's PR #3371, and add a theme option that forces Fusion style for the _light_ color palette as well. But that would have the effect of making your windows look like my _first_ screenshot rather than my second one (and/or yours), which I think we can all agree is really a negligible and insufficient improvement.

I've _long_ been in favor of eliminating the light theme entirely, given that our Timeline doesn't follow the theme changes (and isn't going to), and any theme other than "Humanity: Dark" is really pretty much unsupported.

I'm sorry to say you've only fed me more ammunition on that front, as I'm now even more convinced that it just doesn't make sense to offer the light theme option given that it fails to render the interface properly under any circumstances, really.

**Comment by SuslikV** [comment]
@ferdnyc on Windows, the  "Humanity" themes has bigger fonts. It is interesting why you didn't noticed this obvious difference on Linux.

**Comment by ferdnyc** [comment]
> @ferdnyc on Windows, the "Humanity" themes has bigger fonts. It is interesting why you didn't noticed this obvious difference on Linux.

Yeah, I don't know where that comes from, but the Linux version I run is an installed package built for Fedora, so the package has been streamlined to be compatible with native theming. (You'll notice the different icons, most obviously, but IIRC we also remove the bundled font(s).)

**Comment by ferdnyc** [comment]
The too-large (seems to me) dark theme fonts on Windows should be fixable, though. I'd recommend filling that as a separate bug. 

I actually don't recall seeing that on _Windows_, either, at least in my Win7 VM. So it may be an OS and/or graphics driver issue.

Or I may just be oblivious.

**Comment by ferdnyc** [comment]
Sorry, the close was a wrong-button click.

**Comment by SuslikV** [comment]
> Yeah, I don't know where that comes from...

It comes from https://github.com/OpenShot/openshot-qt/commit/34c0a290f38eaa5f79ae68b2d5bcf137dc8e1f1e where font size was forced to 10.5 for the first time. Making wrong assumption that all is equal across platforms.

**Comment by accorinti** [comment]
Can't you guys just program dark grey splitter grips in the light theme? 
It does make sense, doesn't it?
And I can't imagine it would take more time than it is taking to all of you answering this...

**Comment by ferdnyc** [comment]
> Can't you guys just program dark grey splitter grips in the light theme?
> It does make sense, doesn't it?
> And I can't imagine it would take more time than it is taking to all of you answering this...

Not easily, no. Unfortunately, that's one of the limitations of Qt-based GUIs. The interface design is defined programmatically by the Qt framework, and elements like the splitter grips are entirely controlled by the selected QStyle.

Overriding any elements of a QStyle is a fantastically complicated affair involving building a [`QProxyStyle`](https://doc.qt.io/qt-5/qproxystyle.html) that sits between the native QStyle and the widget classes. (Basically, adding even _more_ code to alter how the existing code computes interface parameters. That's a pain even in C++, and doing it from PyQt5 code (Python bindings to the native Qt C++ APIs) is a Herculean undertaking.

**Comment by SuslikV** [comment]
> Can't you guys just program dark grey splitter grips in the light theme?..

What I can - I already did: https://github.com/OpenShot/openshot-qt/pull/3371 - this is "Fusion" theme as is.

**Comment by ferdnyc** [comment]
^ Agreed. To the extent anything _can_ easily be done about this, that would be it. As you can see from my first screenshot, they're definitely still not _dark_ gray — in fact, they're very, very light, nearly invisible gray. But at least technically visible, as opposed to the native Windows themes where they're literally invisible.

Regarding #3371, @SuslikV , it makes sense to me, although I'm sort of inclined to just fix the "Humanity" (non-dark) theme — well, I'll leave comments there.

I did poke around at the font size thing a bit more, BTW. I see that both "Humanity" themes used a different font size for at least some elements, vs. "No theme" (or "Fusion", in the PR branch). But in a Windows 7 VM with a 1280x720 virtual screen, the difference was between "a perfectly reasonable size" (with the font setting) and "a tiny bit smaller — maybe even slightly too small, if anything" (without). Most likely that was the situation for whoever added that font setting in the first place. The difference was barely noticeable unless you were looking for it.

But you're absolutely right that it's a bad assumption to think that any specific selection of font size would be correct for all users across all OS types and releases, on all display sizes, etc. Especially when the _rest_ of our interface isn't implemented in device-independent units, so if things get scaled they should all get scaled proportionally. (Something a set font size, even in points, could interfere with.) That should just come out, in favor of more portable solutions to whatever issue it intended to address.

**Comment by SuslikV** [comment]
> The difference was barely noticeable unless you were looking for it...

You are blind if you didn't see the difference - look at the Dark theme screenshot posted in https://github.com/OpenShot/openshot-qt/issues/3325#issuecomment-612589466 if you don't see how big the letters are then... Compare size of the "Show All..." text and the Video Preview playback button.
