### ISSUE TITLE
cropping that changes the video size

### ISSUE THREAD

**Issue by antonkulaga** [OpenShot/openshot-qt#3329]
Cropping the video to change its size is a nightmare!
What I expect is intuitive function like in gimp or photoshop where I have the frame and get the size changed, while current way it is done is by editing properties and it does not suggest to change the video size at all. So, if I want to crop from widescreen to 4 x 3 I have to do a lot of tricks.

It is especially annoying as the preview mode does not show the real aspect ratios, when I select 4 x 3 preset for preview and reload the openshot it shows me widescreen :(
I use the latest ppa of openshot at linux mint.

**Comment by ferdnyc** [comment]
> What I expect is intuitive function like in gimp or photoshop where I have the frame and get the size changed, 

Part of the problem is that image editors use arbitrary output sizes, whereas OpenShot's (like any video editor) uses a fixed frame size. So, the "draw a box around what I want to crop" model tends to be a bad fit, even if you fix the aspect ratio. (Especially since you can't draw a box on _every_ frame of the video...)

> while current way it is done is by editing properties and it does not suggest to change the video size at all. So, if I want to crop from widescreen to 4 x 3 I have to do a lot of tricks.

You shouldn't have to, if your goal is simply fitting the video to the output frame. Cropping from a widescreen video, say 16:9 HD, to a 4:3 aspect ratio should be a simple matter of choosing the 4:3 project profile, then setting the clip's Scale property to "Crop". The video should be adjusted to fill the frame vertically, with the left and right sides cropped off in equal amounts.

If you want to pan the crop, you can use the LocationX property to shift the video left/right. (The values are in units of output frame widths, though, so you'll generally want something like ±0.01, ±0.02, etc.)

> It is especially annoying as the preview mode does not show the real aspect ratios, when I select 4 x 3 preset for preview and reload the openshot it shows me widescreen :(
> I use the latest ppa of openshot at linux mint.

I can't reproduce that, with OpenShot 2.5.1. Here's what I did:
1. Set up a project to use the profile "NTSC 23.98fps (720x486)"
1. Loaded and placed a 16:9 video
1. Set the clip to Scale: Crop
1. Saved the project
1. Quit OpenShot
1. Loaded the same project up again

Here's the result:
![image](https://user-images.githubusercontent.com/538020/77880254-3749d580-722a-11ea-94d9-be153ee40505.png)

Can you provide details on your OpenShot version, the exact profile(s) and video properties you're using, and what part of the above isn't working the same for you?

**Comment by ferdnyc** [comment]
@antonkulaga Are you still seeing issues with frame sizing, or can we close this?

**Comment by antonkulaga** [comment]
@ferdnyc I switched to HandBrake where this feature is implemented properly and I can get videos of any size in a predictable way and I can release the videos of the sizes I prefer (not only of the sizes in the list).
So, if you close this issue it means that you prefer to ignore that the very basic cropping feature does not work and people have to switch to other editors to do it properly.

**Comment by SuslikV** [comment]
> 3\. Set the clip to Scale: Crop

This is the most unnoticeable option ( _Scale_ ) that worsens everything when set to _Best Fit_ and it deeply integrated into "renderer" of the OpenShot. Hardly believable that this behavior will change soon.

**Comment by ferdnyc** [comment]
> So, if you close this issue it means that you prefer to ignore that the very basic cropping feature does not work and people have to switch to other editors to do it properly.

That's fine, although I'd argue you're not "switching to another editor", because HandBrake is not an editor.

But if your goal is simply to _resize_ a single video to fit a certain set of exact dimensions, you don't **need** an editor. You need exactly what HandBrake is: a transcoder/converter.

HandBrake is FAR better at that stuff than OpenShot, and always will be. By the same token, if you need to add titles or scene transitions to your video, HandBrake isn't going to be of any use at all.

HandBrake and OpenShot aren't in any sort of competition with each other. I personally use both programs frequently, and more besides — sometimes on the same project.

(HandBrake is great for prepping video clips to be loaded into OpenShot. Taking care of any format conversion or transcoding **before** importing clips is always recommended, because OpenShot isn't _for_ that. It works best when you import video clips that have already been processed into scene-ready elements.) 

My position has always been strongly against trying to make _any_ one tool fit every task.
