### ISSUE TITLE
i click on the video file, i click "time" then "fast" the "forward" then "x2" and it looks great when rendering but in the final product it is cut in halfGive your bug report a descriptive title

### ISSUE THREAD

**Issue by Zenaxia** [OpenShot/openshot-qt#3358]
**Describe the bug:**

**Steps to reproduce the behavior:**

**Expected behavior:**

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.
Log files can be found in your HOME/.openshot_qt/ folder. Please compress or zip
the log files (as they can become quite large).

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please
attach a small snippet of the exception here, but please keep it as small as
possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them here, dragging-and-dropping into this form, or clicking below and loading
images saved to your computer. All images are public, so please don't post screenshots
containing personal information.

**Comment by ferdnyc** [comment]
@Zenaxia Can you please provide the info requested in the bug report form? 

> **System Details:**
> 
> * OpenShot Version [e.g. 2.4.3]: 
> * Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

Also, when you say the export is "cut in half", do you mean that even _after_ the speed increase, only half of the video plays?

Meaning, for example, if you imported a 10-second video, then set it to Time > Fast > Forward > 2X so that it lasts 5 seconds played at double speed, when you exported the result was a 2.5-second video of only the first half?

**Comment by SuslikV** [comment]
More important is movie FPS and OpenShot's profile/export FPS. Because right now, the time "scaling" is based on frame numbers not on time in seconds.
