### ISSUE TITLE
Add "remove all keyframes" to property editor

### ISSUE THREAD

**Issue by fwolfst** [OpenShot/openshot-qt#3383]
**Describe the new feature:**
Related to https://github.com/OpenShot/openshot-qt/issues/2420 , sometimes I messed up with the keyframe thing (seen the PR for the curve editor, awesome! https://github.com/OpenShot/openshot-qt/pull/3084 ) and I want to delete all keyframes or set a value for the whole clip

**Describe the solution you'd like:**
A right mouse button on the value allows me to "remove all keyframes" (which to my understanding internally will create a keyframe at frame 1 with value 0 which is not always the greatest choice).

**Describe alternatives you have considered:**
Another helpful addition/solution would be to have the option (also right mouse click on property value) ~"make this value the only keyframe", which would remove all keyframes and add one at the current position with the current value.

Thanks for all your great work. I'd love to contribute differently but lack the (time and other resources-) budget.

**Comment by SuslikV** [comment]
Maybe "Reset to defaults"?

**Comment by fwolfst** [comment]
That sounds like a interesting option, too. Although then if you want to
edit the property for the whole clip, you would again have to go to frame 0
(which might be not representative, e.g. because of a fade-in, a logo, etc)
or delete the default keyframe.

**Comment by SuslikV** [comment]
Right now only _Animate > No Animation_ is present in right-click menu over the entire clip in the _Timeline_. It emulates similar "reset" for some of the options.

**Comment by MBB232** [comment]
Removing *all* animations is a bit crude if you have multiple animations on separate parts of the video (or combined)
The same thing happens when applying default animations to already modified properties. Like if you already set a location a bit out of the middle. 'transition from edge to center' replaces the end location to the center, rather then stopping on originally set position when sliding in. 
Where are the default transition effects stored, can they be modified for projects like other effects?

In the introduction description the was a menu option to choose the keyframe, but I do not see it in the current version
https://www.openshot.org/blog/2009/07/14/key-frame-awesome/
Clip properties>layout>Keyframe>end of clip


The green points are a bit too small to select, and sometimes keyframes are very close together. (Especially if you tried to change one but was a bit off, and accidentally created a new keyframe. ) 

Maybe an option can be made to "list all keyframes for clip/animation", so you can easily modify them and set some values the same as the previous while setting different values for other properties.
You would get a list of all keyframes on a clip in a row. Then you can apply changes on all those that you select, like removal, copy or change values. 

Because you may want to change the location of a clip (X/Y or scale values of all keyframes but not change their fade-in or volume aspects. 
Or you may want to clone an animation from one clip (or title card) to another, but not change the values for time/position because that second clip should pop up beside it a few moments later. 

Maybe allow im/export as CSV for advanced users so they can modify and move complicated transitions between projects? 

![KeyframeMockup](https://user-images.githubusercontent.com/62191951/79695199-d3895a00-8275-11ea-986d-d31ccbd97291.jpg)

**Comment by SuslikV** [comment]
@MBB232 

1.
> The same thing happens when applying default animations to already modified properties. Like if you already set a location a bit out of the middle. 'transition from edge to center' replaces the end location to the center, rather then stopping on originally set position when sliding in.

Similar to changes that was requested here: https://github.com/OpenShot/openshot-qt/pull/3206
(new animation didn't checks if keys already present in the range)

2.
> In the introduction description the was a menu option to choose the keyframe, but I do not see it in the current version

This is from from old OpenShot (linux only, v1.x ), later the application was rewritten completely.

**Comment by SuslikV** [comment]
I did "what you have" build for Windows, if you interested in (it includes "Curve Editor" in its current shape too).

Custom Windows (x64) build of the OpenShot v2.5.1-dev2:
https://ci.appveyor.com/api/buildjobs/wlfn4elxc47agn94/artifacts/OpenShot-WYH-v2.1.0-1739-g5f694ff9-win-x64-N542.7z
Unpack it to any new folder on your PC. Then run `openshot-qt.exe` from the unpacked folder.
The link will not be valid for long. CRC of the 7z archive above is MD5:E1C197E3F4DE183EF10C2EFF9D3F00A8 (about 111 MB to download).

The build includes all my own PRs, so it a bit ahead of the base project. Thus, OpenShot's project files created in this version may loose some features if they will be used in the regular OpenShot.

----------------

Because the build doesn't make a lot of changes to the base, some features may need your attention too.
- to disable auto-checking for updates (that is always enabled in OpenShot), find the `classes\version.py` file and change next code (with the _notepad++_ application, minimalist version):
```
def get_current_Version():
    """Get the current version """
    t = threading.Thread(target=get_version_from_http)
    t.start()
```
to:
```
def get_current_Version():
    """Get the current version """
    #t = threading.Thread(target=get_version_from_http)
    #t.start()
```
(two `#` were added). Don't forget to save changes.

- in main menu _Edit>Preferences>Debug tab_ make unchecked the _Send Anonymous Metrics and Errors_ - it is enabled by default by project owners. This is just to not spam them with the unneeded info.
