### ISSUE TITLE
Title editor shortcut (Ctrl+T) does not work...

### ISSUE THREAD

**Issue by jarlarntzen** [OpenShot/openshot-qt#34]
Title says it all, I think :)

Terminal output when pressing `Ctrl+T`
```
 main_window:INFO keyPressEvent: player.Position(): 1145
 main_window:INFO keyPressEvent: player.Position(): 1145
```

**Comment by olielvewen** [comment]
Hi,
I've just checked all shortcuts (only Fullscreen, for me another application is launched) and he works fine.
Could you give us more explanations about your distribtution, how do you have installed it, ....
Thanks.

**Comment by jarlarntzen** [comment]
I've tested this on:
**OSX El Capitan:** All shortcuts work.
**Ubuntu 14.04 LTS:** Ctrl+T, Ctrl+B doesn't work. I'll test the rest when I get back home.

**Comment by olielvewen** [comment]
I've tested there are few days ago this on :
Manjaro Linux : up to date (this one of the 18)
Linux mint 17.2 (based on Ubuntu 14.04 like you) and all works fine.
Hovewer, you should test all every day or near because Jonathan makes updates every day or two.
Looking your output, did have you using the player ? 
You have an hidden file on Ubuntu and he is localised at .openshot_qt. Could you send it here. 
Hovewer, before doing something with openshot-qt, remove it. It will be automatically created after and run all shortcuts tests. Like this we won't have all you have done since the beginning and it will be easiest for us to find this situation.
I suspect a issue with unity.

**Comment by olielvewen** [comment]
I've been able to reproduce it and I've understood why some shortcuts works or not.
All for me is in the Advanced View.
The filter from the Properties dialog seems to keep the focus.

<code>PLAY() on QTPlayer
 main_window:INFO updateStatusChanged
         app:INFO Process command-line arguments: ['src/launch.py']
 main_window:INFO updateStatusChanged
preview_thread:INFO onModeChanged
 main_window:INFO keyPressEvent: player.Position(): 1
 main_window:INFO keyPressEvent: player.Position(): 1
 main_window:INFO keyPressEvent: player.Position(): 1
libpng warning: iCCP: known incorrect sRGB profile
    uiparser:DEBUG UI version is 4.0
    uiparser:DEBUG uiname is Dialog
    uiparser:DEBUG toplevel widget is About

</code>

**Comment by jonoomph** [comment]
This is a bug in the menu support for Qt with Ubuntu (and certain Linux desktops that move the menu of Qt). Based on my research, it is fixed upstream and new distros don't experience this anymore (i.e. menu shortcuts not working). Thanks!
