### ISSUE TITLE
Property editor is not updating properties live when playing preview

### ISSUE THREAD

**Issue by mkarg** [OpenShot/openshot-qt#3404]
**Describe the bug:**
The property editor is not showing the property values of the current frame when playing the preview, but keeps showing the property values of the frame where the preview started. Once the preview stops, the property values are correctly updated. This is somewhat confusing, particularly when working with keyframed effects.

**Steps to reproproduce the behavior:**
1. Put some keyframes on your effect.
2. Run the playback the check the animation of they properties.

**Expected behavior:**
The properties editor shows the property values of the currently playing frame, hence updates frequently.

**System Details:**
- OpenShot Version 2.5.1-dev2
- Operating System Windows 10

**Log Files:**
N/A

**Exception / Stacktrace:**
N/A

**Screenshots:** (Optional)
N/A

**Comment by SuslikV** [comment]
It will slowdown OpenShot even more. Better to not make changes to this part of the code while properties models are created on the fly and rendering/creation is so complex (there is also filtering... hope you will not attempt to use it).

**Comment by mkarg** [comment]
Come one, this will definitively not slow down Open Shot in any way if we simply **discouple** the UI threads from the playback threads. Even my seven years old laptop has lots of empty CPU cycles in **preview** mode. So this is not a valid argument against this feature which is heavily useful for semi-pro usage.

**Comment by SuslikV** [comment]
OpenShot re-builds whole view model (by calling _update_model()_ method of the `properties_model.py`) and thus you see "updated" values in the table. You may comment out timer mentioned in: https://github.com/OpenShot/openshot-qt/pull/3203 , to see the effect (values will be updated on the fly). This is design flaw and there is nothing to fix. New code (feature request) is needed rather than "fix the bug".
