### ISSUE TITLE
After exporting a clip from a vertical video, the clip becomes narrower than the original video.

### ISSUE THREAD

**Issue by DDDXXX** [OpenShot/openshot-qt#3409]
**Describe the bug**
After exporting a clip from a vertical video using the same size, the clip becomes narrower than the original video (the width becomes smaller).

**Steps to reproduce the behavior:**
1. Import a vertical video. In this bug report, I used a 540*960 video.
2. Right click the video, click the "File properties" in the menu, view the information of this video. 
    I have to do this because OpenShot cannot set properties of the outputed clip automatically according to the original video.
2. Drap the video to timeline, and cut a clip.
3. Click the "export video" button in the toolbar, and in the opened dialog set the properties of the outputed clip manually using the information get early (same size as the original video).
4. After the clip is outputed, play it in VLC. BUT, BUT, BUT, It is much narrower than the original video!!! 
    I have worked on many vertical videos, most of them are mp4 files, and this bug exists for all these videos. So far, horizontal videos have rarely encountered this bug.

**Expected behavior**
The (display) size of the output clip should be correct.

**System Details**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['zh-CN', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1587624248-15c3efb7-26b7db94-x86_64.exe

**Log Files**
- http://logs.openshot.org/g2pbzkmyawus5jmcbc46paptwo5okc0o/openshot-qt.zip
- http://logs.openshot.org/g2pbzkmyawus5jmcbc46paptwo5okc0o/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)

1 Original video playing in VLC:

![openshot-0-originalvideo](https://user-images.githubusercontent.com/21323460/80295654-2481dc80-87a7-11ea-9365-96877dc2a4af.PNG)

2 Properties of the original video:

![openshot-0b-originalvideoinfo](https://user-images.githubusercontent.com/21323460/80295624-ed133000-87a6-11ea-8d61-e5195b81837b.PNG)

3. View properties of the original video in OpenShot:

![openshot-1-fileproperties](https://user-images.githubusercontent.com/21323460/80295708-a40fab80-87a7-11ea-860f-cb544ce52aa1.PNG)

4. Set properties of the outputed clip manually according to the original video:

![openshot-3-outputsettings](https://user-images.githubusercontent.com/21323460/80295712-abcf5000-87a7-11ea-9533-d56c3bb12fa7.PNG)

5. Outputed clip playing in VLC (narrowed):

![openshot-4-afterexport](https://user-images.githubusercontent.com/21323460/80295719-b7227b80-87a7-11ea-9d3c-c05e52e94c1c.PNG)

6 Properties of the outputed clip:

![openshot-5-infoafterexport](https://user-images.githubusercontent.com/21323460/80295720-bd185c80-87a7-11ea-8611-b01d86e34929.PNG)

**Comment by SuslikV** [comment]
Vertical videos not supported. Vertical profiles doesn't work as expected.

Long time ago (https://github.com/SuslikV/openshot-qt/commit/3420c262fd8624accba4fd09ed104ccdb20ca1fb etc.) I tried to solve this issue but dropped code changes because nobody needs it. Right now @jonoomph trying to make few changes to _Transform_ that should inherit all the bugs that the preview and export has ( https://github.com/OpenShot/openshot-qt/pull/3366 ) but this should solve some internal bugs of the _Transform_ controls drawing. Thus, don't expect for the solution in recent days/months/years.

The file sample (vertical video) to test with may be found here: https://github.com/OpenShot/openshot-qt/issues/2969#issuecomment-527790409

**Comment by DDDXXX** [comment]
> Vertical videos not supported. Vertical profiles doesn't work as expected.
> 
> Long time ago ([SuslikV@3420c26](https://github.com/SuslikV/openshot-qt/commit/3420c262fd8624accba4fd09ed104ccdb20ca1fb) etc.) I tried to solve this issue but dropped code changes because nobody needs it. Right now @jonoomph trying to make few changes to _Transform_ that should inherit all the bugs that the preview and export has ( #3366 ) but this should solve some internal bugs of the _Transform_ controls drawing. Thus, don't expect for the solution in recent days/months/years.
> 
> The file sample (vertical video) to test with may be found here: [#2969 (comment)](https://github.com/OpenShot/openshot-qt/issues/2969#issuecomment-527790409)

Thank you. But I think it is very easy to implement it, and it is incredible to not support vertical videos. So I strongly recommend to implement it in the near future.

**Comment by littlefico** [comment]
i had the very same problem
solution is very easy. you have to change the preview to vertical before you import (prog new start needed)
please check that
![openshot-qt_27_04_2020_09-50-02](https://user-images.githubusercontent.com/46540103/80347598-cd463f80-886c-11ea-844c-cb819103ee79.jpg)

**Comment by DDDXXX** [comment]
> i had the very same problem
> it seems that you have 16:9 as preview when you imported your video.
> solution is very easy. you have to change the preview to vertical before you import (prog new start needed)
> please check that
> ![openshot-qt_27_04_2020_09-50-02](https://user-images.githubusercontent.com/46540103/80347598-cd463f80-886c-11ea-844c-cb819103ee79.jpg)

Thank you very very much!! Good job! Perfect! I tried it with your method, the result is correct. Perfect!

**Comment by SuslikV** [comment]
@littlefico how did you fit your video into the output? I can only get right result with the _Scale_ set to  _None_ and input 1080p file + vertical 1080p profile. Everything else doing black bars.

**Comment by SuslikV** [comment]
@littlefico even with this video? https://github.com/OpenShot/openshot-qt/issues/2969#issuecomment-527790409

**Comment by littlefico** [comment]
no, because this video looks like a vertical one but in fact is not. (its dimensions are 1920*1080)
scale set to none is the only way to do it right with this one.
i made some real vertical videos so my way did it.
so there is no bug with the video from #2969 because you can easily set scale to none.

**Comment by SuslikV** [comment]
@littlefico OK. I think, your files has no orientation record in it, unlike the mentioned example file. This is why examples are important when reporting the issues.

**Comment by ferdnyc** [comment]
@DDDXXX @littlefico 

Hmm. Glad to hear that works to solve your problem, but you shouldn't need to change your _default_ profile in the Preferences like that every time you want to work with vertical video.

That setting only controls the _default_ profile that's selected for new projects automatically. But, every project has a profile setting, and you can change **that** at any time and without restarting.

The toolbar icon to set the project profile is the one that comes after "Import Files" (➕ sign) but before Fullscreen and Export (red circle) — it's the fourth one from the left, in this detail from @littlefico 's screenshot:

![image](https://user-images.githubusercontent.com/538020/80594125-6f426500-89f0-11ea-9def-6d0eed1ec32a.png)

You can also access the same thing from the File menu (the English label is "Choose Profile"), which has a default keyboard shortcut of <kbd>Ctrl</kbd>+<kbd>P</kbd>.

Using any of those options brings up the Choose Profile dialog, where you can set the profile for the current project:
![image](https://user-images.githubusercontent.com/538020/80594504-1e7f3c00-89f1-11ea-97f4-0038047eba39.png)

Rather than editing your default profile every time, it _should_ be sufficient to set the project profile to a vertical format before you import your media files. You'll see the preview aspect change to vertical when you do, same as always, and the window title will also update to show the currently-selected profile.

You definitely don't want to wait until you export to make your profile selection, that part of @littlefico 's advice is extremely important. But you shouldn't have to go through all that hassle with changing your defaults. Just set the profile for the current project before you import your vertical files.

If for some reason that _doesn't_ work, and changing your default is the **only** way to get vertical videos to format correctly, then please do let us know because it shouldn't be necessary to change your defaults like that.
