### ISSUE TITLE
Se cierra inesperadamente después de cambiar audio canales de 2 a 1

### ISSUE THREAD

**Issue by Oscar65** [OpenShot/openshot-qt#3411]
**Describa el problema**
Se cierra inesperadamente después de cambiar audio canales de 2 a 1

**Pasos para reproducir el comportamiento:**
1. Ir a Editar / Preferencias / Previsualización.
2. Cambiar Canales de audio predeterminados (de 2 a 1).
3. Guardar vídeo.
4. Abrir Open Shot.
5. Cambiar Cambiar Canales de audio predeterminados (de 1 a 2).
6. Abrir vídeo anteriormente guardado.
7. Pulsar play y se cierra insesperadamente.

Nota:
Si cambio channels de 1 a 2 en /tmp/Felicidades.osp no se cierra inesperadamente:
```
...
"sample_rate": 44100,
 "channels": 2,
 "channel_layout": 4,
...
```

**Comportamiento esperado**
Que no se cerrase y que se viera el video.

**Detalles del sistema**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Linux-5.6.6-arch1-1-x86_64-with-glibc2.2.5
- Processor: 
- Machine: x86_64
- Python version: 3.8.2
- Qt5 version: 5.14.2
- PyQt5 version: 5.14.2
- Qt Detected Languages: ['es-ES']
- LANG Environment Variable: es_ES.UTF-8
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1587624156-15c3efb7-26b7db94-x86_64.AppImage

**Archivos de registro**
- http://logs.openshot.org/kwtlkp2v0iucs6y3eseagoao1zkyszb4/openshot-qt.zip
- http://logs.openshot.org/kwtlkp2v0iucs6y3eseagoao1zkyszb4/libopenshot.zip

**Excepción / Rastreo de pila**
```/usr/lib/libopenshot.so.19     openshot::AudioReaderSource::getNextAudioBlock(juce::AudioSourceChannelInfo const&) 0x598  [0x7f41c3f3fa88]
/usr/lib/libopenshot-audio.so.7 juce::BufferingAudioSource::readBufferSection(long long, int, int) 0x61  [0x7f41c386ba71]
/usr/lib/libopenshot-audio.so.7 juce::BufferingAudioSource::readNextBufferChunk() 0x23c  [0x7f41c386bcdc]
/usr/lib/libopenshot-audio.so.7 juce::BufferingAudioSource::useTimeSlice() 0xa  [0x7f41c386bd7a]
/usr/lib/libopenshot-audio.so.7 juce::TimeSliceThread::run()             0x12d  [0x7f41c38c94cd]
/usr/lib/libopenshot.so.19     openshot::SafeTimeSliceThread::run()     0xa  [0x7f41c3fce8ba]
/usr/lib/libopenshot-audio.so.7 juce::Thread::threadEntryPoint()         0xcb  [0x7f41c38ce44b]
/usr/lib/libopenshot-audio.so.7 threadEntryProc                          0xa  [0x7f41c38ce56a]
/usr/lib/libpthread.so.0                                                0x946f  [0x7f41cfa5d46f]
/usr/lib/libc.so.6             clone                                    0x43  [0x7f41cff353d3]
/usr/lib/libQt5Gui.so.5        QPaintEngineExPrivate::QPaintEngineExPrivate() 0xb6  [0x7f41cb4164e6]
/usr/lib/libQt5Gui.so.5        QRasterPaintEngine::QRasterPaintEngine(QPaintDevice*) 0x21  [0x7f41cb4225d1]
/usr/lib/libQt5Gui.so.5        QImage::paintEngine() const              0x84  [0x7f41cb1bff14]
/usr/lib/libQt5Gui.so.5        QPainter::begin(QPaintDevice*)           0xb9  [0x7f41cb43af49]
/usr/lib/libopenshot.so.19     openshot::Timeline::add_layer(std::shared_ptr<openshot::Frame>, openshot::Clip*, long, long, bool, float) 0x1a29  [0x7f41c3faaca9]
/usr/lib/libopenshot.so.19                                              0xc1289  [0x7f41c3faf289]
/usr/lib/libgomp.so.1                                                   0x1aefe  [0x7f41c3b61e...

**Comment by Justin-CB** [comment]
Creo que este "bug" es relacionado a #3361 (OpenShot crashea al exportar cuando cambia "canales de audio" a Mono). Necesité usar OpenShot 2.4.4 para exportar con audio mono.
=================================================
This bug report translated to English:
OpenShot crashes after changing audio channels from 2 to 1
Steps to reproduce:
1. Go to Edit / Preferences / Preview
2. Change default audio channels (from 2 to 1)
3. Save Video
4. Open OpenShot
5. Change Change audio channels (from 1 to 2)
6. Open Previously Saved Video
7. Press play and it crashes
Note: If I change channels from 1 to 2 in /tmp/Felicidades.osp it doesn't crash:
`...
"sample_rate": 44100,
 "channels": 2,
 "channel_layout": 4,
...`
Expected Behavior:
OpenShot doesn't crash and displays the video.

System Details

OpenShot Version: 2.5.1
libopenshot Version: 0.2.5
Platform: Linux-5.6.6-arch1-1-x86_64-with-glibc2.2.5
Processor:
Machine: x86_64
Python version: 3.8.2
Qt5 version: 5.14.2
PyQt5 version: 5.14.2
Qt Detected Languages: ['es-ES']
LANG Environment Variable: es_ES.UTF-8
LOCALE Environment Variable:
Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1587624156-15c3efb7-26b7db94-x86_64.AppImage

Log Files

http://logs.openshot.org/kwtlkp2v0iucs6y3eseagoao1zkyszb4/openshot-qt.zip
http://logs.openshot.org/kwtlkp2v0iucs6y3eseagoao1zkyszb4/libopenshot.zip

Exception / Stack Trace 
`/usr/lib/libopenshot-audio.so.7 juce::BufferingAudioSource::readBufferSection(long long, int, int) 0x61  [0x7f41c386ba71]
/usr/lib/libopenshot-audio.so.7 juce::BufferingAudioSource::readNextBufferChunk() 0x23c  [0x7f41c386bcdc]
/usr/lib/libopenshot-audio.so.7 juce::BufferingAudioSource::useTimeSlice() 0xa  [0x7f41c386bd7a]
/usr/lib/libopenshot-audio.so.7 juce::TimeSliceThread::run()             0x12d  [0x7f41c38c94cd]
/usr/lib/libopenshot.so.19     openshot::SafeTimeSliceThread::run()     0xa  [0x7f41c3fce8ba]
/usr/lib/libopenshot-audio.so.7 juce::Thread::threadEntryPoint()         0xcb  [0x7f41c38ce44b]
/usr/lib/libopenshot-audio.so.7 threadEntryProc                          0xa  [0x7f41c38ce56a]
/usr/lib/libpthread.so.0                                                0x946f  [0x7f41cfa5d46f]
/usr/lib/libc.so.6             clone                                    0x43  [0x7f41cff353d3]
/usr/lib/libQt5Gui.so.5        QPaintEngineExPrivate::QPaintEngineExPrivate() 0xb6  [0x7f41cb4164e6]
/usr/lib/libQt5Gui.so.5        QRasterPaintEngine::QRasterPaintEngine(QPaintDevice*) 0x21  [0x7f41cb4225d1]
/usr/lib/libQt5Gui.so.5        QImage::paintEngine() const              0x84  [0x7f41cb1bff14]
/usr/lib/libQt5Gui.so.5        QPainter::begin(QPaintDevice*)           0xb9  [0x7f41cb43af49]
/usr/lib/libopenshot.so.19     openshot::Timeline::add_layer(std::shared_ptr<openshot::Frame>, openshot::Clip*, long, long, bool, float) 0x1a29  [0x7f41c3faaca9]
/usr/lib/libopenshot.so.19                                              0xc1289  [0x7f41c3faf289]
/usr/lib/libgomp.so.1                                                   0x1aefe  [0x7f41c3b61e...`
===============================
Translation of my Comment:
I think that this bug is related to #3361 (OpenShot crashes when exporting with "Audio Channels" set to Mono). I needed to use OpenShot 2.4.4 to export with mono audio.
