### ISSUE TITLE
Video Preview's bezels are too big.

### ISSUE THREAD

**Issue by AE720** [OpenShot/openshot-qt#3422]
I was unable to find this referenced. Apologizes if this has been mentioned already.

I'd like for the video preview to take over the gray bezel so I could see my work better. 

![image](https://user-images.githubusercontent.com/63013864/80613388-3c599a80-8a0b-11ea-8183-d6dc7fdd82bb.png)

I can resize the pane and that hides the gray bezel but that keeps the video preview the same size. I am unable to find any resize option if this already is in place.

Since I can pop it out and move it to another monitor, this isn't that much of an issue but it would help single monitor users to be able to stretch out the video across all of that bezel around it.

**Comment by ferdnyc** [comment]
@AE720 A couple of points/questions, just so I'm sure I understanding the request.

The aspect ratio of the video preview is fixed, so it's sized to whatever dimensions will fit in the available space, and there will only be window border if the _other_ dimension is oversized. (In effect, there isn't really any bezel at all. The video preview widget is only the black rectangle. it's just that, because it has a fixed ratio of width:height, it's centered in whichever dimension isn't currently limiting its size.)

Are you asking about having the preview extend into the gray borders around the widget on the left and right sides? If the preview were made wider without also increasing its height, either the video would be distorted because it's stretched horizontally, or the top and/or bottom of the frame would be cut off.
