### ISSUE TITLE
Snap to playhead when resize

### ISSUE THREAD

**Issue by maksun** [OpenShot/openshot-qt#3443]
**Describe the new feature:**
It should be great to able to snap to playhead when resize. I used it in the past on another software and it was really comfortable. Why not activate it on demand by clicking "Ctrl" or another relevant key.

**Describe the solution you'd like:**
Let's say you put the playhead at a specific position, you are clicking at the end (or beginning) of a clip to resize then when you are near the playhead it should be "magnetic" (the same way as when you are moving a clip then when you are near the playhead it is "magnetic").

**Describe alternatives you have considered:**
Put the playhead at a specific position then right click on the clip -> slice and keep right or left depending on the situation.

I hope my explanation is clear enough, if not do not hesitate to tell me.

Thank you.

**Comment by ferdnyc** [comment]
@maksun 

> **Describe alternatives you have considered:**
> Put the playhead at a specific position then right click on the clip -> slice and keep right or left depending on the situation.

I guess that's my first question: What's lacking in that, as an alternative?

The snapping functionality in OpenShot is mostly custom code, and fairly complex at that. This is largely due to internal complexities. Any interaction that straddles the barrier between the timeline JavaScript and the Python code that implements the rest of the interface becomes somewhat involved.

For dragging, it's fairly usable though there are some issues. (Precision is lost when zoomed out more than 2 or 3 steps, making the snapping unreliable.) Still, for close zoom levels, it works well enough and the performance is reasonable. That's mostly because the JavaScript can manage everything on its own once the drag operation is started.

For clip length changes (resizing), though, the Python code supplies necessary data, primarily the maximum length a clip can be resized to, which is used to control the resizing process. The JavaScript code (which implements snapping) can't manage the positioning entirely on its own during a length-change, like it can for a drag operation.

Snapping performance when resizing a clip would necessarily be worse than the current move-operation snapping, and it would suffer from the same precision issues when zoomed out. Whereas placing the playhead at the intended point and initiating a one-sided Slice operation is a quick operation, and it has no precision issues regardless of zoom level. The end result, in both cases, is exactly the same. (Even though slicing doesn't _feel_ equivalent to resizing, they're really pretty much interchangeable.)

I **_absolutely_** understand — and would even _agree_ — that just dragging a clip edge is convenient, and also feels like a more natural method of changing a clip's length than using the Slice actions. If there were no difference between them, and snapping could easily just be "switched on" for that mode... well, there'd be no need for discussion and I'd just be posting a "Sure, done!" comment instead.

But the reality is, snapping on resize is a complex feature to support in OpenShot. (That's the developers' problem, though. It's not something the users need to care about. What _is_ the users' concern, though, is whether the feature's performance will be adequate.)

While we'd certainly consider merging patches to add snapping-on-resize functionality if anyone wrote the code, it would also have to perform well enough to be usable, which is questionable.

**Comment by maksun** [comment]
@ferdnyc 

Thank you for the detailed feedback, I understand every words of it (meaning and dev constraints).

> "I guess that's my first question: What's lacking in that, as an alternative?"

 No lack as there is a really good workaround, as you guess here we are only talking about user experience (which I think is particularly important on video editing software).
