### ISSUE TITLE
Unable to Change Title Font

### ISSUE THREAD

**Issue by gwyngy** [OpenShot/openshot-qt#3445]
**Describe the bug**
Unable to change the title font. In my case it's Avant Garde SAP. Noticed that some other fonts also face the same issue. The font change only apply for a limited number of fonts in the entire font list.

**Steps to reproduce the behavior:**
1. Go to 'Title'
2. Click on 'Title'
3. Select 'Bar 3'
4. Select 'Change font'
5. Scroll to desired font, in this case 'Avant Garde SAP'
6. Select 'OK'
7. Select 'Save'

**Expected behavior**
The font is suppose to change to the newly selected font accordingly. However in my case it doesn't. Instead of Avant Garde, it is displaying Times New Romans (I think).

**System Details**
- OpenShot Version: 2.5.1-dev2 and 2.5.1
- libopenshot Version:  0.2.5-dev2
- Platform: Windows-10-10.0.17763
- Processor: Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1588204308-15c3efb7-26b7db94-x86_64.exe

**Log Files**
- http://logs.openshot.org/omht72it89vetmwr3t4a56hgfgy25vfp/openshot-qt.zip
- http://logs.openshot.org/omht72it89vetmwr3t4a56hgfgy25vfp/libopenshot.zip

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)

![OS_title bug](https://user-images.githubusercontent.com/64773578/80947235-47089b00-8e22-11ea-8aa5-933d1f2e4215.PNG)

**Comment by ferdnyc** [comment]
@gwyngy 

Basically, that means that the font is available to Qt for use on-screen, but not available for use in the title SVG file format. Most often that happens with bitmap fonts, though that's clearly not the case here. Avant Garde is one of the traditional 35 standard PostScript typefaces, though, so it's possible Avant Garde SAP is a PostScript font or uses some other format that's not compatible with SVG.

Unfortunately there's no way to have the Qt font dialog display only fonts that _work_ in SVG files (believe me, we've tried!) — heck, it can't really even KNOW which fonts are compatible and which aren't.

If you have a lot of incompatible fonts installed that cause a lot of hassle choosing fonts for OpenShot titles, the only thing I can think to suggest is using Inkscape to edit the titles (via the Use Advanced Editor button).

It won't make Avant Garde SAP or any other incompatible font somehow work in SVG files, but at least it should only display font choices that **are** usable.

Sorry, I realize that's not much help, but it's a limitation of doing the font selection from an external application (i.e. OpenShot), instead of one designed specifically around the features of the SVG format (e.g. Inkscape).
