### ISSUE TITLE
AppImage under KDE: resizing window doesn't update contents

### ISSUE THREAD

**Issue by luca76** [OpenShot/openshot-qt#3453]
Hello, I am running KDE (5.18.4) and downloaded AppImage.
The problem is when I resize the OpenShot window, it doesn't resize its contents
See the image. There's a big empty space below timeline

![immagine](https://user-images.githubusercontent.com/5095918/81054905-f21f6000-8ec7-11ea-8131-df2d5e7d5347.png)

**Comment by SuslikV** [comment]
Similar behavior was reported before: https://github.com/OpenShot/openshot-qt/issues/2704

**Comment by ferdnyc** [comment]
It looks like the layout has the Timeline dock in one of the left/right side panels — that's why there' a splitter handle _under_ it. If you drag the timeline dock by its titlebar from above that handle to below it, it'll be docked in the bottom section of the window, which should prevent this. (Weird that it happens anyway, but at least it should be easily worked around.)
