### ISSUE TITLE
X / Y Location values are reversed up in video properties

### ISSUE THREAD

**Issue by yukon2010** [OpenShot/openshot-qt#3468]
**Describe the bug:**
When you use manually adjust the properties of a video file, and you use "location X / Location Y" values, they are reversed.  Adjusting Y affects X axis, and vice versa.

**Steps to reproduce the behavior:**
1. Select properties on a video file
2. click on the Location X and adjust.  The video will move left or right (that is the Y axis)
3. click on the Location Y and adjust.  The video will move up or down (that is the X axis)

**Expected behavior:**
Adjusting Location X should move it up or down, and Location Y should move it left or right.

**System Details:**
- OpenShot Version 2.5.1
- Operating System / Distro: Windows 10

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.
Log files can be found in your HOME/.openshot_qt/ folder. Please compress or zip
the log files (as they can become quite large).

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please
attach a small snippet of the exception here, but please keep it as small as
possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them here, dragging-and-dropping into this form, or clicking below and loading
images saved to your computer. All images are public, so please don't post screenshots
containing personal information.

**Comment by SuslikV** [comment]
OpenShot uses right-handed coordinate system, Z from user, when objects displayed on the screen.

**Comment by ferdnyc** [comment]
Which is fairly standard, I think. When I open a new Blender default project, X axis translation moves an object laterally on the plane, the Y axis controls depth, and the Z axis is elevation. So, OpenShot's 2D coordinate system is the same, when viewed from above the plane looking down. (You can think of the layer stack as the Z axis, with objects placed on higher tracks stacking in front of lower ones.)

The one quirk is that the Y axis is reversed from what some people may expect, because the origin is in the upper left corner. So, negative Y translations move objects up, and positive ones move them down. But that's a Qt decision, it's just the way their layout system works.)

**Comment by ferdnyc** [comment]
A horizontal/vertical X/Y coordinate system with the origin in the upper left is also pretty standard for 2D graphics software, used by the GIMP and I believe Photoshop as well.

And you can think of the web's layout system the same, with `top` and `left` representing the Y and X offsets from the upper-left-corner layout origin. (Upper right corner in right-to-left languages.)
