### ISSUE TITLE
Alter behavior of TAB when going through property values

### ISSUE THREAD

**Issue by yukon2010** [OpenShot/openshot-qt#3469]
**Describe the new feature:**
When using TAB to go between settings on the PROPERTIES of an item, the TAB has to be pressed twice because it (needlessly?) selects the property name (which you can't change anyway).
So if i'm manually adjusting an X/Y value, such as CropX and CropY, you have to press tab twice to go between the two values (or shift-tab twice to go back)

**Describe the solution you'd like:**
Duplicate the functionality of the up/down arrow when TAB or SHIFT-TAB are pressed.

When you press tab, have it jump to immediately to the next property value that can be changed, and ignore the selection of the property name.

**Describe alternatives you have considered:**

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your request.

**Comment by XanderLeaDaren** [comment]
Related idea with Keyboard navigation through Properties items: #3452

**Comment by ferdnyc** [comment]
Tab navigation through cells of the TableView is set automatically by Qt, though, and I believe has accessibility implications for users who rely exclusively on keyboard navigation, so I'm a bit more reluctant to consider overriding that. 

I'll have to take another look at the accessibility documentation. OpenShot is already falling short of best practices in that domain, admittedly. I'd just hate to make things even _worse_.

Oh! Actually,  the #3452 idea reminded me why Tab navigation between cells is useful. There's a keyboard-only method of initiating edit mode on value-editable properties. (The ones that take a string or numeric value, not the ones that are only set by context menu selection — another thing that should be fixed.) It's a Qt standard keyboard shortcut that you can edit a table cell value by pressing <kbd>Space</kbd>, but only for the actively-highlighted cell.

You'll recall that <kbd>Space</kbd> is one of our play/pause toggles, though it doesn't work anywhere in the Properties table (because of Qt's override). Still, users (including me) will often forget and try to use it anyway. So it helps prevent accidental edits, when using row navigation or mouse selection, that to edit a property you have to _first_ hit <kbd>Tab</kbd> to switch columns, **then** press <kbd>Space</kbd> to activate edit mode.

**Comment by MBB232** [comment]
> and I believe has accessibility implications for users who rely exclusively on keyboard navigation, so I'm a bit more reluctant to consider overriding that.
> I'll have to take another look at the accessibility documentation. OpenShot is already falling short of best practices in that domain, admittedly. I'd just hate to make things even worse.

Reading though the many issues and your comments, you won't be bored any time soon 😃

I expect that jumping to non-editable text cells can be used in Text-to-speech applications. I would wonder *how many blind users would do video editing*, but then I knew a colorblind guy who did some pretty good color matching in image editing. 

For the medium visually impaired, I would imagine that being able to set a larger font size would be more important; especially the track time numbers are pretty small. 

Theoretically it would be a trade-off with with the psychically impaired, for who less clicks would be important. But as stated above, the up-down arrows already do that job. 

BTW, I did not know that SPACE worked to edit values, but indeed it does. F2 works as well. (At least in Windows 10)

Bigger (wider) interface buttons may be a win for everyone. (Unless you have them intentionally small to encourage hot-key use 😁 )
