### ISSUE TITLE
exporta un video distinto del que veo (Give your bug report a descriptive title)

### ISSUE THREAD

**Issue by Hapu-ar** [OpenShot/openshot-qt#3470]
**Describa el problema**
Exporto un video y es totalmente distinto del que veo!
Aca un zip con el directorio con el archivo osp, el directorio _assets y el resultado mp4
https://drive.google.com/file/d/1RknyJYMFO8gTW3B6E7MSJ3pdoJ-hVHkZ/view?usp=sharing

**Pasos para reproducir el comportamiento:**
1. Abro el archivo
2. Exporto la opción por default
3. Abro el mp4 y es distinto

**Detalles del sistema**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['es-ES', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build Installed: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1588953574-6e7ad231-a62505ca-x86_64.exe

**Archivos de registro**
- http://logs.openshot.org/yxq34oi7c7eblgvufwgx4hnhg1h6l0i7/openshot-qt.zip
- http://logs.openshot.org/yxq34oi7c7eblgvufwgx4hnhg1h6l0i7/libopenshot.zip

**Excepción / Rastreo de pila**
```No stacktrace found in log files```

**Capturas de pantalla** (Opcional)
Si se aplica, añada capturas de pantalla para ayudar a explicar el problema. Puede incluir capturas
copiando y pegando en GitHub o arrastrando y soltando en la página de GitHub. Todas las imágenes
son públicas y por tanto no debería publicar capturas que contengan información personal.

**Comment by SuslikV** [comment]
When you importing video that isn't matches current _Preview Profile_ of OpenShot - application sets _Time_ property to map each frame of the imported movie to the preview. This is done in frames numbers (not in seconds!), thus when you exporting with different profile - every timing is changing...

To workaround current behavior you can:
- set export _Video Profile_ to match Preview Profile (24 fps in your case).
- select new Preview Profile (the one you will export to) and redo all cuts again.
- select new Preview Profile (the one that matches FPS of the video source) and redo all cuts again and export with the same FPS profile. But because, it's 29.970 fps for your file, OpenShot may miss something during edits. Better to use 25/30/50/60 fps import/export until OpenShot will handle other formats better.
