### ISSUE TITLE
Video clips in portrait mode seem to use height as width and vice versa

### ISSUE THREAD

**Issue by alansharkey** [OpenShot/openshot-qt#3483]
WHen I import a video clip which I took in portrait mode, it chops the top and bottom of the video off as if it was taking the width parameter as the height and the height as the width.

I have verified this with a few phones and also the latest (May 11th) build.

Alan

**Comment by alansharkey** [comment]
An example file is here https://www.dropbox.com/s/azdtx5ugaqfxujw/Alan.mp4?dl=1

Alan

**Comment by ferdnyc** [comment]
Yeah, the issue is that those dimensions are _correct_ for the way nearly all phones implement portrait video.

When a phone-like device shoots video in portrait mode, what it _stores_ is a landscape video (1920 wide × 1080 tall, for example), with a 90° rotation embedded in the metadata.

Libopenshot recognizes and applies the rotation, but it treats the video as having its unrotated dimensions, which causes issues as detailed in OpenShot/libopenshot#322 (along with #2969 + others, in this repo).
