### ISSUE TITLE
Resize selected clip when moving back edge

### ISSUE THREAD

**Issue by guiljo** [OpenShot/openshot-qt#3504]
**Describe the new feature:**
When a clip is selected, moving its back edge should resize it and not the next one.
(somehow related to issue #1817)

**Describe the solution you'd like:**
Take into account which clip is already selected when resizing an edge - instead of resizing only front edges of clips.

**Describe alternatives you have considered:**
- Select clip
- Bring the playhead to its start for snapping
- Move the clip to another track at the same time frame
- Resize its back end
- Move it back to its original track

**Screenshots:** (Optional)
Clip 1 is selected:
![image](https://user-images.githubusercontent.com/13487812/82430580-cb4b5700-9a8d-11ea-9a09-f557e2ac8a3f.png)
Clip 2 gets resized instead:
![image](https://user-images.githubusercontent.com/13487812/82430601-d8684600-9a8d-11ea-9f4f-ece95810032a.png)

**Comment by ctsdownloads** [comment]
Thank you for the feature request, we always appreciate constructive feedback. Marked as an enhancement.

**Comment by SuslikV** [comment]
Steps to reproduce issue is not clear. If selected clip loses its selection by itself (without user interaction) then this is bug. I cannot reproduce this.

Linux? AppImage? What version of the application?

**Comment by guiljo** [comment]
Indeed this might be a bug, as you can resize the back edge of clip without a problem when there is no other clip next to it.

Version 2.5.1 on Windows 10

**Comment by SuslikV** [comment]
I see it now. It's jQuery object resizing. Its custom implementation in OpenShot has more bugs than this. Wouldn't be fixed soon.

The overlap of two objects shows that object on the top is always lies to the right in OpenShot's Timeline.
Usually, the jQuery takes into account order of the creation.
When hovering, the highlight shows that clip on the right is the object that will accept the resize action.

**Comment by ferdnyc** [comment]
Yeah, that's a long-standing visual bug with the Timeline drawing code. The glitch is, I believe, entirely visual -- while the object _appears_ to shrink slightly, it's not actually getting truncated. It's just being drawn too short. Zooming in/out one step and back again is one workaround to correct the size on screen.

**Comment by guiljo** [comment]
This issue is actually about clips which has previously been snapped to each other and therefore perfectly aligned, no visual trick in here, at least as far as I understand. 

@ferdnyc, maybe you are referring to other issues related to back edges of clips, such as #3502, #1817, or maybe to the display issue mentioned in #2808?

**Comment by ferdnyc** [comment]
Ohhhh, okay. I get it now. You're talking about the resize behavior on overlapping (or immediately adjacent) widgets.

Currently in OpenShot, when you have two clips occupying the same track area, the one that comes _later_ in the Timeline (the one to the right) is given a slightly larger `z-index` parameter than the one before it. This is done so that the later clip will _always_ appear in front of the earlier one, if the two clips are overlapped.

Selection doesn't affect this, for the same reason. (Otherwise, when you selected a clip, it would pop up in front of any unselected ones it overlapped. That's _usually_ the way you want draggable items to behave, but in terms of the OpenShot timeline it's wrong — the later clip should always appear in front of the earlier one, as that matches how the video will be rendered.

But you're right that it means whenever you have two clips next to each other, any attempts to grab at the shared edge will always give preference to the left edge of the clip on the right over the right edge of the clip on the left. And, again, selection doesn't affect it.

This might be tricky to fix. We'd either have to override the widget positioning code and roll (even more of) our own, or we'd have to create and destroy resize handles on the fly based on widgets' state and relationship to each other.

It's tempting to say that only selected objects should be resizable, since that would fix this, but it'd break things for a lot of users who are used to being able to grab the edge of an unselected widget and just start dragging.

**Comment by SuslikV** [comment]
> ...the later clip should always appear in front of the earlier one, as that matches how the video will be rendered.

Rendering has nothing to do with the user manipulations. This is two different things.

And bottom clip on the Track can be larger than the top one (on the same Track). Start position of the clip can define rendering order. Thus, single selected clip may pop up. If two clips co-exist (on the Track) then there is indeterminacy.
