### ISSUE TITLE
Advanced scaling on multiple videos modifies only one of them

### ISSUE THREAD

**Issue by Tzaphkiel** [OpenShot/openshot-qt#3572]
**Describe the bug**
Advanced modification of scaling and placement (layout) values on multiple selected clips (red) only modifies 1st one

**Steps to reproduce the behavior:**
1. add front and back videos to 2 tracks respectively
2. select videos in back track (above) 
3. right click and layout 1/4 size top-left
4. switch to advanced mode
5. change scale X and Y successively to .3

**Expected behavior**
All videos are resized accordingly

**Actual behavior**
Only first or last video is rescaled correctly...

**System Details**
- OpenShot Version: 2.5.1
- libopenshot Version:  0.2.5
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-GB', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Skipped this step

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/nofrkygfr4gevuf7gk1uicv7oou45w8e/openshot-qt.zip) (364 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by SuslikV** [comment]
Side note.
The Properties Model (displays `property = value` pair) is valid only for single item. No multiply selections can be displayed. Hard to say what should be modified and in which way (add, subtract, override etc.), because some properties can be already animated. Current _**Selection**_ name is displayed at the top of the list, so behavior is correct:

![OpenShot Properties Selection](https://user-images.githubusercontent.com/19683044/85230132-c8c67f00-b3f6-11ea-9b44-eb0f437a9875.png)

I assume you wish to force keyframe insertion to each selected item (if property exist in this item) when multiply items selected and only one is modified.

**Comment by ctsdownloads** [comment]
Thanks for filing this, marked for enhancement.
