### ISSUE TITLE
openshot theme

### ISSUE THREAD

**Issue by StephanKrauss** [OpenShot/openshot-qt#3584]
**Question:**
Hello,

there are other layout / theme versions for Openshot ?
I need a bright layout with a clearly visible button.

Best regards

Stephan

**System Details:**
- OpenShot Version latest OpenShot
- Operating System latest Linux Mint

**Comment by Joyen12** [comment]
I don't understand either why every video editor only have dark theme. I know it's trendy but they don't think about people who have eyes problem and really need a light/bright theme. I was checking open source project because I though they would allow this. Maybe you could create something to allow people to make their own theme. Or just do a quick bright theme, it will be better than nothing. I think it's very fast and easy for the original dev to add that. Just add a toggle button that switch between dark and bright. The first video editor which does that will increase is user base by a lot, that's for sure.

**Comment by Colorjet3** [comment]
Hello @Joyen12.  I will flag this as an enhancement request.  I believe the future UI will have this feature in it.

**Comment by crag2012** [comment]
I have just started using openshot and found the dark theme difficult and disappointed not to find a light theme

**Comment by Colorjet3** [comment]
Give this a try:
1.  In OpenSHot, go to Edit | Preferences | General tab.
2.  Change the Default Theme to Humanity.
3.  Restart OpenShot.

There is more work being done in this area but no ETA at this time.

**Comment by Colorjet3** [comment]
Hello @crag2012.  Any update on the "Humanity" theme?  Did it at least help a little bit for now?
