### ISSUE TITLE
i18n support for plural forms

### ISSUE THREAD

**Issue by gunchleoc** [OpenShot/openshot-qt#3589]
The zoom slider above the timeline has the following text:

`{} seconds`

The gd translation for "seconds" can change depending on the number, e.g.

```
1 diog
2 dhiog
3 diogan
20 diog
```

This also affects Slavic languages.

I am using a workaround `{} diog(an)` for now, which makes the UI ugly.

This seems to be the only string that needs plural forms, so no need to give it high priority.

**Comment by gunchleoc** [comment]
Translation catalog hasn't changed on Launchpad, so I'm assuming this hasn't been fixed.

**Comment by JacksonRG** [comment]
@gunchleoc the zoom slider has been reworked. I don't see text on it. So this may have been fixed.

**Comment by gunchleoc** [comment]
Here's the lines from the .pot file. I have redacted the file paths since it's configured to show the complete path including the local username.

```
#: src/windows/views/webview.py:802
#: src/windows/views/webview.py:2770
#: src/windows/main_window.py:2574
msgid "{} seconds"
msgstr ""
```
One of these 3 occurrences is still in the current source code:

```
        # Add Freeze menu options
        Time_Menu.addSeparator()
        for freeze_type, trigger_type in [
            (_("Freeze"), MENU_TIME_FREEZE),
            (_("Freeze && Zoom"), MENU_TIME_FREEZE_ZOOM)
        ]:
            Freeze_Menu = QMenu(freeze_type, self)

            for freeze_seconds in [2, 4, 6, 8, 10, 20, 30]:
                # Add menu option
                Time_Option = Freeze_Menu.addAction(_('{} seconds').format(freeze_seconds))
                Time_Option.triggered.connect(
                    partial(self.Time_Triggered, trigger_type, clip_ids, freeze_seconds, playhead_position))

            # Add menu to parent
            Time_Menu.addMenu(Freeze_Menu)
```
https://github.com/OpenShot/openshot-qt/blob/develop/src/windows/views/webview.py#L796

**Comment by ferdnyc** [comment]
Yeah, the zoom_slider value won't appear in the UI at all in future releases, but the freeze times are still countable strings subject to pluralization. Amazingly enough, it seems (from a quick scan of the translation master) those may be the **only** remaining translatable strings that require pluralization rules. I have to think that's due to conscious avoidance, for reasons I'll get back to.

Specific cases aside, plural translations _in general_ would obviously be a useful thing to support. Pluralization of values is a [dizzyingly complex subject](http://cldr.unicode.org/index/cldr-spec/plural-rules) from a global perspective.

English speakers are somewhat spoiled, since we generally have only two plural forms ("singular" and "all other"), with exceptions mostly being words that are their own plural (e.g. "sheep"). And that often leads to very limited consideration of plurals in code, because we tend to think of English as the center of the universe when (surprise!) it's not. 

(...Then again, the English rules for _ordinals_ are unusually complex, more so than almost any other language. That's mostly due to the "teens exception", which is the reason why our ordinals go 1<sup>st</sup>, 21<sup>st</sup>, 31<sup>st</sup>…; 2<sup>nd</sup>, 22<sup>nd</sup>, 32<sup>nd</sup>…; 3<sup>rd</sup>, 23<sup>rd</sup>, 33<sup>rd</sup>…; and 4<sup>th</sup>, 24<sup>th</sup>, 34<sup>th</sup>…, yet — as if that wasn't complex enough — it's 11<sup>th</sup>, 12<sup>th</sup>, 13<sup>th</sup>, 14<sup>th</sup>, etc. That's _weird_, and few other languages would put up with that sort of nonsense.)

Globally, though, [some languages use](https://unicode-org.github.io/cldr-staging/charts/37/supplemental/language_plural_rules.html) 4 or more [plural forms](https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html). Some also have different rules for fractional values or ranges. (English is one: A range of values **always** uses the plural form, even "0–1 days" or "0.5–1 days" or, heck, "1–1 days". But in Danish it's "0–1 dag" and "0.5–1 dag" vs. "0–2 dage" and "1–2 dage", arguably more consistent with their general plural rules for numbers.)

I looked into this some when it was first reported, and honestly, I'm not sure how or **if** it can be made to work, which is why I suspect some effort has been made — not entirely successfully — to avoid the issue. (I further suspect that the issue was considered "worked around" for the freeze actions, because the quantities used are 2, 4, 6, 8, 10, 20, and 30. Those all pluralize the same, **in English**. Which comes back to that whole "English is not the center of the universe" thing.)

Still, it's an issue that affects a remarkably small cross-section of our translatable strings, probably on purpose. If we were to create lots of pluralizable texts, then we'd have to support plural translation, and given how things are set up... we maybe _can't_?

Two things are working against us:
1. **Translation markup.** The translations are managed as Gettext-style translation masters in launchpad, but those are partly _translated_ (heh, no pun intended) master files. The actual translatable strings are extracted from the program source using a complex series of `xgettext` and `lupdate` commands.
    * `xgettext` extracts strings marked up as `_("SOMETHING TRANSLATABLE")`  from the source code, and creates a `.pot` translation master for those strings.
    * `lupdate` is Qt's standard extraction tool, used to extract strings marked `translatable` from the Qt `.ui` XML files (and other XML files, like effect definitions and title templates). `lupdate` produces `.ts` files, which are Qt translation source files.

    The `.ts` files are then consolidated, converted to gettext format, and combined with the `.pot` extractions to produce a single Gettext-format `OpenShot.pot` file which is uploaded to launchpad. There, a translated `OpenShot_XX.po` file is produced for each language `XX`. Those files are then downloaded, and they become Qt-standard `OpenShot_XX.qm` compiled translations... ... ... um, somehow? I'm not even sure exactly how that conversion is done. It's a part of the process that seems to be external to the repo, and presumably something @jonoomph has been doing manually.

    More importantly, the method by which _plural_ rules are specified differs quite a bit between Gettext translations and Qt translations, and it may not be easy to convert plural translations between the two formats.

    In theory, the PyQt5 tool `pylupdate5` could be used to extract messages from the Python source, instead of using `xgettext`. That would... probably make this a lot more workable, to be honest. But currently that's not how it's done. Changing tools will likely cause a **large** disruption in our translations, so I suspect there would understandably be pushback against any such change. Honestly it's extremely confusing that we're working with gettext-style translations at all, considering the code is Qt-based. AFAICT that's mostly a combination of inertia + launchpad preferring/requiring(?) gettext `.pot` files as translation masters.

2. **Applying translations.** Like I said, the actual translations are done using Qt's standard `.qm` files, which are managed by the `PyQt5.QtCore.QtTranslation` class which emulates Qt's own `QtTranslation` class. Even though the source code is marked up `_("TRANSLATABLE STRING")`, which is a gettext-style replacement, the function `_(arg)` is actually aliased to a call to `PyQt5.QtWidgets.QApplication.translate("", arg)`, which is to say, a `translate()` call with the context forcibly removed. (The stripping of all context from the translations is a separate, but related, issue.)
    
To support plural translations, we'd have to extend the semantics of the `_()` call to accept an integer keyword argument `n`, to specify the countable quantity to use in the translation. e.g:

```python3
# This
_("{} seconds").format(freeze_seconds)
# would become
_("{} second", n=freeze_seconds).format(freeze_seconds)
# or even better...
_("{second_count} second", n=freeze_seconds).format(second_count=freeze_seconds)
```
That would allow the Qt `translate()` function to return the proper plural form of "<var>n</var> second", assuming it _had_ a plural translation for that string. It would also, however, require us to have a translation file for **English** as well, with rules to translate `"<var>n</var> second" into "1 second" or "2 seconds"... for a given quantity <var>n</var>. That's something we've never had, so far, because it only applies to plurals.

I don't **believe** Gettext can extract `_("{} seconds", n=freeze_seconds)` or even just `_("{} seconds")` as a countable quantity, but that part may not matter since AIUI any translation can be made countable in gettext just by supplying multiple plural forms (please correct me if that's wrong). Countables would normally use printf-style `%d` or `%i` placeholders, in gettext, and maybe those would automatically be recognized. But when I tried it, though I'm not sure why, Python seemed to balk at these forms:
```python3
_("%d second") % freeze_seconds
_("%(seconds_count)d second") % (seconds_count=freeze_seconds)
```
...which is how it would have to be written (but with an added `n=freeze_seconds` argument), for countables using %-formatted strings. Nevertheless, like I said AIUI it's OK if Gettext doesn't automatically recognize countables, because when it extracts a message like this:
```po
msgid "{} seconds"
msgstr ""
```
A translator can make it countable by changing that to e.g.
```po
msgid "{} seconds"
msgid_plural "{} seconds"
msgstr[0] "{} seconds"
msgstr[1] "{} second"
msgstr[2] "{} seconds"
```
At least, I think that's the right form. Normally the first line would be `msgid "{} second"`, and that would be the string actually found in the source. But our source doesn't currently use singular forms to tag countable quantities, and the important part is that the `msgid` match what's actually found in the source code.

Even better would be to use Qt-style countable strings, which would use the form `"%n second"`. The Qt `translate()` function can automatically replace `%n` with the value of its `n` argument, so...
```python3
translate("", "%n second", n=1)  # => "1 second"
translate("", "%n second", n=5)  # => "5 seconds"
```
...assuming the proper translations are present in the `.qm` file.

I'll submit a PR extending `_()` to accept an optional `n=` argument — that can be done as a transparent enhancement, and it's definitely a necessary first step towards making this work. Then, we'll have to see if we can convince `xgettext` to do the right thing with `_("%n second", n=freeze_seconds)`, **and** whether we can get that properly triple-converted into the correct plural translations inside the `OpenShot_XX.qm` files.

**Comment by ferdnyc** [comment]
> That would allow the Qt `translate()` function to return the proper plural form of "n second", assuming it _had_ a plural translation for that string. It would also, however, require us to have a translation file for **English** as well, with rules to translate `"n second" into "1 second" or "2 seconds"... for a given quantity n. That's something we've never had, so far, because it only applies to plurals.

Correction, it appears the standard practice in Qt is to supply countable translations as e.g.
```python3
_("%n second(s)", n=freeze_seconds)
```
Presumably because using that form allows the code to gracefully fail, in cases where an English translation file is missing to supply the proper plural form.

**Comment by gunchleoc** [comment]
## Translation platform
How about moving translations from Launchpad to Weblate? https://docs.weblate.org/tr/latest/formats.html

Then the program would not need to do any conversions to gettext format any more, and translators who use weblate can simply pick the format they want when they translate offline. Also, the Weblate UI is vastly superior to Launchpad, e.g. Launchpad has no support for fuzzy matches.

If you don't want to host yourself, https://hosted.weblate.org/ should to fine.

## xgettext
For plural forms, xgettext expects:

`ngettext("{} second", "{} seconds", n)`

It has a `--qt` option though that could help https://www.gnu.org/software/gettext/manual/html_node/xgettext-Invocation.html

**Comment by ferdnyc** [comment]
> ## xgettext
> For plural forms, xgettext expects:
> 
> `ngettext("{} second", "{} seconds", n)`

Right, but that's when using the gettext library _for_ translation, which we're not.

> It has a `--qt` option though that could help https://www.gnu.org/software/gettext/manual/html_node/xgettext-Invocation.html

That only works with C++ source, not on Python.

As far as translation platforms, there's also Crowdin and a ton of other web-based options that are (IMHO) superior to Launchpad.

Translating with Qt Linguist, though (the Qt native translation platform) has some advantages of its own. For starters, it can show both source code context (for supported source files, of which Python is one thanks to Qt for Python) _and_ visual context, when translating UI files. It's kind of handy, when asked to translate "Video Only", to be shown context that makes it clear it's an export type:

![image](https://user-images.githubusercontent.com/538020/122316926-a290cd80-ceea-11eb-8d1d-f08e93a442ad.png)

It's even _more_ handy, when asked to translate "Developers", to be _shown visually_ that it's the label of a tab in the About dialog:

![image](https://user-images.githubusercontent.com/538020/122317124-ff8c8380-ceea-11eb-9485-66b1945fe8b5.png)

But Qt Linguist doesn't lend itself quite as well to crowdsourcing translations, seems like. Though, as far as web platforms go, Crowdin at least _does_ support management of translations in `.ts` files, rather than `.pot` files, so it's not out of the question that we could move to Qt's native translations with a platform switch. (Crowdin also supports funneling updates to Github project automatically — it has web hooks that can submit PRs whenever there are new translations. The migration of translations from Launchpad into the repo is _entirely_ manual, which seems tedious and unideal.)

**Comment by ferdnyc** [comment]
For the record, the interface screenshots I showed there are the result of extracting translations from the openshot-qt sources manually with:
```sh
cd openshot-qt/src/windows
pylupdate5 -tr-function _ -verbose ui/*.ui **/*.py -ts /tmp/openshot-qt.ts
```
(I'm running zsh where recursive globs like `**/*.py` are supported, that won't work in stock bash.)

Then, I opened `/tmp/openshot-qt.ts` in Qt Linguist.

When the translations are extracted using this command, which is approximately what we're currently using to extract Python source strings:
```sh
xgettext -o /tmp/openshot-qt.pot --keyword=_ `pwd`/**/*.py
```
Linguist can open the `.pot` file (if you first edit it to change the `CHARSET` to `utf-8`), and it can show the same source-code context. I haven't yet experimented with plural-form translations, extracted using either method.

**Comment by gunchleoc** [comment]
It would be interesting to test whether Crowdin will integrate the screenshots too. The way I usually work is to download and translate offline, so I can use a common translation memory for all my projects. My offline tool can't read .ts though, but I can get an XLIFF file from either Crowdin or Weblate in addition to the .ts file. Both have automated integration and an issue tracker, so both would work.

One thing that makes Crowdin a bit more unwieldy is that project managers have to add new locales manually, so translators have to start a discussion and wait. In Weblate, translators can just add the locale themselves and start translating immediately.

If you should go for Crowdin, make sure you absolutely [do NOT set the "update_option"](https://support.crowdin.com/configuration-file/#changed-strings-update) in the configuration file. It's currently causing a [major headache on the Mastodon project](https://crowdin.com/project/mastodon/discussions/34).

**Comment by ferdnyc** [comment]
Crowdin can definitely show _uploaded_ screenshots, though I don't know if it can automatically generate them. (In some ways, it's better if they're uploaded. Much of the OpenShot interface is generated from code, rather than the `.ui` files, so most elements — particularly in the main window — aren't visible in generated screenshots.)
