### ISSUE TITLE
Clip Properties: Volume Mixing - does it work?

### ISSUE THREAD

**Issue by rexdk** [OpenShot/openshot-qt#3598]
I'm trying to help improve the User Guide, currently by writing up clip properties. 

Volume Mixing does not appear in the current Use Guide. Issue 2813 discusses this property, and how it should work. My precis of that is:

-  None - allows the clip audio to play at the chosen Volume setting
- Reduce - plays the clip audio at 77% of the chosen Volume setting
- Average - divides this clip’s volume by the sum of the Volume settings of all clips. To average the sound from all clips, all clips must individually  be set to Average.

However when I try it on 2.5.1 Win 10, I can see and hear no effect. I have exported an mp4 with just sound (single musical notes) and the setting makes no difference to the waveform (examined in Audacity).

I have grepped the code for the code comment referred to in issue 2813, and it is not found.

Is this property intended to work, or should it be documented as inactive?

Many thanks

**Comment by rexdk** [comment]
I think the relevant code is in Timeline.cpp, in libopenshot. Here we have:
// Apply volume mixing strategy
	if (source_clip->mixing == VOLUME_MIX_AVERAGE && max_volume > 1.0) { .....

So, if the combined volume of all clips does not exceed '100%' (however that is defined), then there is no effect. That would explain what I've seen.

This issue can now be closed - thank you.

**Comment by ferdnyc** [comment]
@rexdk 

> I think the relevant code is in Timeline.cpp, in libopenshot. Here we have:
> ```cpp
> // Apply volume mixing strategy
> if (source_clip->mixing == VOLUME_MIX_AVERAGE && max_volume > 1.0) { .....
> ```
> So, if the combined volume of all clips does not exceed '100%' (however that is defined), then there is no effect. That would explain what I've seen.

Mmm, that's not quite it, though. The key point about that code (and the feature) is one of the things I cover in https://github.com/OpenShot/openshot-qt/issues/3256#issuecomment-596258966 — specifically, that the `max_volume` variable there (and, indeed, the entire volume-mixing feature itself) is only concerned with the volume **property** of the clips involved — it's not based on any sort of measured loudness level (nor do we ever measure the sound levels).

So, if you have two clips playing simultaneously without volume adjustment, both set to Average mixing, they'll both be reduced to volume = 0.5.

But here's the thing: Volume levels are measured on a logarithmic scale, so a reduction in volume from 1.0 to 0.5 is far from "half as loud" ­— you can try it for yourself with just a single clip, in fact. If you load a clip with audio onto the timeline, add a keyframe a few seconds in that sets `volume = 0.5`, then add another a few seconds farther down to set `volume = 1.0` again (so that there's a smooth, linear ramp down and back up again), what you'll probably hear is the levels dipping "a bit" in the very middle, but for most of the time there's hardly any audible change at all.

Only when it gets down around 0.6 or so will a volume reduction _start_ to become noticeable, really — although it will drop **precipitously** after that. 0.4 will sound significantly quieter than 0.5, and 0.25 _sounds_ closer to 10% of the full volume. Yay logarithms.

So, I've also found that it can be difficult to detect whether mixing is doing anything at all, in fact when discussing it we've often resorted to viewing waveforms in Audacity. The adjustments _do_ show up clearly there, since measuring and inspecting the volume levels tends to be much more accurate than trying to _listen_ for the changes. But the waveforms usually tell a pretty detailed story.

> This issue can now be closed - thank you.

Will do, although I just wanted to point out that you **can** also do that yourself, if you wish. The reporter of an issue always has the option to close it if they resolve it themselves. But I'll close this one now, thanks.

**Comment by rexdk** [comment]
@ferdnyc 
Glorious - thank you. I hadn't discovered how max_volume was calculated. Yes, I'm fairly well up on audio and logarithms; OpenShot simply adds volumes (or at least volume settings) together, which is correct I think, but the ear responds in a logarithmic way. I've understood the code better now you've given me the pointer :)
