### ISSUE TITLE
Cannot Open .osp file "invalid load key, '{'."

### ISSUE THREAD

**Issue by anubhavkhindri** [OpenShot/openshot-qt#3599]
I had an open shot file project and the next day I was unable to open it after my system shut down suddenly due to low battery! I tried reinstalling the program, but it still will not open. 

The message given when trying to open the file is:
![Capture](https://user-images.githubusercontent.com/67941689/86716507-e1fa3d00-c03e-11ea-93ec-b43f8900a653.PNG)

I had been working on this project since last 10 days, please help!

Openshot Version is 2.5.1
Windows 7

**Comment by anubhavkhindri** [comment]
[IVLOG_Ladakh2019_HRC.zip](https://github.com/OpenShot/openshot-qt/files/4882639/IVLOG_Ladakh2019_HRC.zip)

Here is the .zip file for my project.

Please help me out

**Comment by SuslikV** [comment]
Not much data is left in your project file. It is damaged a lot. Repaired one:

[IVLOG_Ladakh2019_HRC_repaired.zip](https://github.com/OpenShot/openshot-qt/files/4882688/IVLOG_Ladakh2019_HRC_repaired.zip)

about 26KB to download, CRC of the .zip archive MD5:988386393335AF145054759C128C3B7B

You may try to find some auto-backup copies on your PC (if any were made of course by "auto-saving" feature of OpenShot) - look for files with the `.osp` extension on the system drive.

Please, consider that next may become useful for you:

1. Make backup copies during your work.
2. Try to disable auto-saving feature of OpenShot (main menu _Edit>Preferences>Autosave tab>Enable Autosave_) - it can overwrite files silently and if something happens... you may get damaged file. Better to follow p.1, always.

Issue itself is similar to: https://github.com/OpenShot/openshot-qt/issues/3123 (zeros fill)

**Comment by anubhavkhindri** [comment]
Thank you so much I think 70% work is there.

**Comment by anubhavkhindri** [comment]
Where can i find auto backup copies?

**Comment by izzostar** [comment]
[Timmu 6.07.20nädalavideprojekt.zip](https://github.com/OpenShot/openshot-qt/files/4886933/Timmu.6.07.20nadalavideprojekt.zip)

Sorry to bother you again. Last thread was closed, so i thought i write here.
 This time no (auto)saved backups open either, so im in trouble.
Could you check the file and say if you see whats wrong with it. In a quik view myself did not see "zeros fill" in GHex, but its a long file.

By making backup copies you mean what? Save as new file? I was thinking autosave was good for that :(

**Comment by SuslikV** [comment]
@izzostar 
Repaired project file:

[Timmu 6.07.20nädalavideprojekt_repaired.zip](https://github.com/OpenShot/openshot-qt/files/4888313/Timmu.6.07.20nadalavideprojekt_repaired.zip)

about 303KB to download, CRC of the .zip archive MD5:D10B6C9020DE92B35E327430FF09BE76

BEFORE you will load the project - RENAME your titles files (SVG) so that it has no `"` (double quote marks) in it. When OpenShot will prompt the find file - look carefully at the names (sometimes there is no spaces in names, where `"` were).

**About issue itself**
Some titles files you made has double quotas in the name, like:
```
"blah-blah-blah".svg
```
that were saved in the project file as:
```
/"blah-blah-blah\".svg
```
obviously, the last one causes errors during project load.


**About backups**
I'm saving project files as name01, name02, name03 etc. (every 15-20 minutes or before huge changes) and working on the latest saved (nameXX). It is enough for my needs. Also, to not blow up saved files in size, caused by Undo history entries, that is always saved into the project file (what a stupid decision! It seems that only OpenShot doing it from all applications I know @jonoomph !!!), I'm clicking main menu _Edit>Clear History_ right before saving the file. So, I'm saving files when I'm sure that I will not try to undo any action. Anyway I can load previous version of the file if I need.

**Comment by SuslikV** [comment]
@izzostar Please, when saving files do not use `"` symbols in filenames even if system allows it.
