### ISSUE TITLE
My project files tab is missing

### ISSUE THREAD

**Issue by TheBigone0** [OpenShot/openshot-qt#3620]
The first time I opened open shot the project tiles tab was there but when I went to chrome, when I came back the tab was gone! Anyone know what I did to make it disappear?

**Comment by ferdnyc** [comment]
@TheBigone0 Hmm, strange, not sure what could've caused that. You can bring it back by right-clicking on any of the other dock tabs or titlebars. You'll see a menu listing all of the docks, with checkmarks to enable/disable each one.

**Comment by ferdnyc** [comment]
@TheBigone0 Sorry, I was mistaken. The dock tabs are one of the few areas you _can't_ click, to get the context menu. But if you click anywhere on the toolbar, the status bar — the "window surface" in general, basically — of the OpenShot window, you'll get a popup menu that lets you hide/show the various docks and toolbars.

I also just submitted #3622, which will add a **Docks** submenu to the main **View** menu, since that's a natural place people would generally look for such a list. Should've done that ages ago.
