### ISSUE TITLE
Openshot version 2.5.1 not able to find assets with foreign characters when opening a file from Openshot 2.4.x

### ISSUE THREAD

**Issue by giray** [OpenShot/openshot-qt#3624]
**Describe the bug:**
OpenShot 2.5.1 (OpenShot-v2.5.1-x86_64.AppImage) is not able to find assets of an .OSP file created in 2,4,3 (Ubuntu) with assets using foreign characters.

**Steps to reproduce the behavior:**
1. Create project using 'openshot-2.4.3'
2. Add Assets with names such as
- `intubated yaşlı.jpeg`
- `Hemşirenin Gizli Kamera Çekimleri.mp4`
3. Use assets and save project
4. Run OpenShot-v2.5.1
5. Open osp file
6. Get "`Missing File - intubated ya\u015fl\u0131.jpeg cannot be found`" message

Pointing to the directory where the asset resides does not resolve the issue

**Expected behavior:**
Expected to find assets even though they 
**System Details:**
- OpenShot Version : Ubuntu 2.4.3 to OpenShot-v2.5.1-x86_64.AppImage
- Operating System / Distro: Tested on ubuntu 20.04 and ubuntu 19.10

**Log Files:**
```
Loaded modules from current directory: /tmp/.mount_8XFKMA/usr/bin
         app:INFO ------------------------------------------------
         app:INFO             Sun Jul 26 09:42:16 2020            
         app:INFO               Starting new session              
         app:INFO ------------------------------------------------
         app:INFO             OpenShot (version 2.5.1)            
         app:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.5.1
         app:INFO libopenshot version: 0.2.5
         app:INFO platform: Linux-5.4.0-40-generic-x86_64-with-Ubuntu-20.04-focal
         app:INFO processor: x86_64
         app:INFO machine: x86_64
         app:INFO python version: 3.4.3
         app:INFO qt5 version: 5.2.1
         app:INFO pyqt5 version: 5.2.1
    language:INFO Qt Detected Languages: ['en-US']
    language:INFO LANG Environment Variable: en_US.UTF-8
    language:INFO LOCALE Environment Variable: 
    language:INFO OpenShot Preference Language: Default
project_data:INFO Setting default profile to HD 720p 30 fps
         app:INFO Setting font to /tmp/.mount_8XFKMA/usr/bin/images/fonts/Ubuntu-R.ttf
logger_libopenshot:INFO Connecting to libopenshot with debug port: 5556
         app:INFO Setting custom dark theme
QMainWindow::addDockWidget: invalid 'area' argument
     ui_util:INFO Initializing UI for MainWindow
 files_model:INFO updating files model.
transition_model:INFO updating transitions model.
effects_model:INFO updating effects model.
properties_model:INFO updating clip properties model.
transition_model:INFO updating transitions model.
 files_model:INFO updating files model.
 main_window:INFO InitCacheSettings
 main_window:INFO cache-mode: CacheMemory
 main_window:INFO cache-limit-mb: 250
 main_window:INFO Creating CacheMemory object with 262144000 byte limit
preview_thread:INFO QThread Start Method Invoked
preview_thread:INFO initPlayer
 main_window:INFO Clear all thumbnails: /home/giray/.openshot_qt/thumbnail
 main_window:INFO Clear all animations: /home/giray/.openshot_qt/blender
 main_window:INFO Clear all titles: /home/giray/.openshot_qt/title
     version:INFO Found current version: {"openshot_version": "2.5.1"}
 main_window:INFO updateStatusChanged
 main_window:INFO updateStatusChanged
         app:INFO Process command-line arguments: ['/tmp/.mount_8XFKMA/usr/bin/openshot-qt']
 main_window:INFO recover_backup
project_data:INFO Setting default profile to HD 720p 30 fps
preview_thread:INFO refreshFrame
preview_thread:INFO self.player.Position(): 1
video_widget:INFO Load: Set video widget display aspect ratio to: 1.7777777910232544
video_widget:INFO Set video widget pixel aspect ratio to: 1.0
 main_window:INFO updateStatusChanged
preview_thread:INFO onModeChanged
 main_window:INFO foundCurrentVersion: Found the latest version: 2.5.1
properties_model:INFO Update item: 
properties_model:INFO updating clip properties model.
preview_thread:INFO refreshFrame
preview_thread:INFO self.player.Position(): 1
    timeline:INFO Adjusting max size of preview image: PyQt5.QtCore.QSize(724, 407)
preview_thread:INFO refreshFrame
preview_thread:INFO self.player.Position(): 1
timeline_webview:INFO Qt Found!
timeline_webview:INFO $scope.Qt = true;
timeline_webview:INFO SetThumbAddress: http://127.0.0.1:54871/thumbnails/
timeline_webview:INFO SortItems
timeline_webview:INFO UpdateLayerIndex
timeline_webview:INFO UpdateLayerIndex
 main_window:INFO Clear all thumbnails: /home/giray/.openshot_qt/thumbnail
 main_window:INFO Clear all animations: /home/giray/.openshot_qt/blender
 main_window:INFO Clear all titles: /home/giray/.openshot_qt/title
project_data:INFO Setting default profile to HD 720p 30 fps
project_data:INFO Loading project file: /home/giray/Documents/CIS MEDYA PODCAST/Episode 001 - Jon Rapoport/CIS-episode001.osp
      assets:INFO Using existing asset folder /home/giray/Documents/CIS MEDYA PODCAST/Episode 001 - Jon Rapoport/CIS-episode001_assets
      assets:INFO Using existing asset folder /home/giray/Documents/CIS MEDYA PODCAST/Episode 001 - Jon Rapoport/CIS-episode001_assets
      assets:INFO Using existing asset folder /home/giray/Documents/CIS MEDYA PODCAST/Episode 001 - Jon Rapoport/CIS-episode001_assets
project_data:INFO checking project files...
project_data:INFO checking file /home/giray/Documents/CIS MEDYA PODCAST/Episode 001 - Jon Rapoport/Audio-Voice 009-2_sd.mp3
project_data:INFO checking file /home/giray/Documents/CIS MEDYA PODCAST/Episode 001 - Jon Rapoport/Audio-Voice 009_sd.mp3
project_data:INFO checking file /home/giray/Documents/CIS MEDYA PODCAST/Episode 001 - Jon Rapoport/Assets/christine-roy-ir5MHI6rPg0-unsplash.jpg
project_data:INFO checking file /home/giray/Documents/CIS MEDYA PODCAST/Episode 001 - Jon Rapoport/Assets/Laten_zien_en_vertellen (5).mp4
project_data:INFO checking file /home/giray/Documents/CIS MEDYA PODCAST/Episode 001 - Jon Rapoport/Assets/Laten_zien_en_vertellen.mp4
project_data:INFO checking file /home/giray/Documents/CIS MEDYA PODCAST/Episode 001 - Jon Rapoport/Assets/Laten_zien_en_vertellen (1).mp4
project_data:INFO checking file /home/giray/Documents/CIS MEDYA PODCAST/Episode 001 - Jon Rapoport/Assets/Laten_zien_en_vertellen (2).mp4
project_data:INFO checking file /home/giray/Documents/CIS MEDYA PODCAST/Episode 001 - Jon Rapoport/Assets/Laten_zien_en_vertellen (3).mp4
project_data:INFO checking file /home/giray/Documents/CIS MEDYA PODCAST/Episode 001 - Jon Rapoport/Assets/Laten_zien_en_vertellen (4).mp4
project_data:INFO checking file /home/giray/Documents/CIS MEDYA PODCAST/Episode 001 - Jon Rapoport/Assets/make it rain governor.jpeg
project_data:INFO checking file /home/giray/Documents/CIS MEDYA PODCAST/Episode 001 - Jon Rapoport/Assets/inrubation arkansas.jpeg
project_data:INFO checking file /home/giray/Documents/CIS MEDYA PODCAST/Episode 001 - Jon Rapoport/Assets/intubated ya\u015fl\u0131.jpeg
```

**Comment by ferdnyc** [comment]
@giray (I edited your report just to improve readability a bit. I fenced some of the filenames that contained special characters, and in particular I fenced the log output as a preformatted block so that GitHub doesn't mess with the line-wrapping. No content changes were made.)

**Comment by ferdnyc** [comment]
@giray Hmm, this is a strange one, as those escaped paths appear to be valid ASCII representations of Unicode in JSON, which means the Python `json.loads()` function we use to parse the project file _should_ be converting them. E.g:

```python3
>>> import json
>>> json.loads('{"path": "intubated ya\u015fl\u0131.jpeg"}')
{'path': 'intubated yaşlı.jpeg'}
```

So, if it's _not_ converting them, I can only think that the representation in the project data is different in some way that confuses `json.loads`, and they're only being restored to the "corrent" form _after_ they're loaded. (There is a bunch of data-fixup we do after the fact, when loading saved projects.)

Hmm. Some additional data would be extremely helpful here, and since you're on Linux it's simple to collect. Could you please post the output of this `grep` command on your original 2.4.3 project data (the `.osp` file that isn't being loaded properly):
```sh
grep '\"path\"' '/home/giray/Documents/CIS MEDYA PODCAST/Episode 001 - Jon Rapoport/CIS-episode001.osp'
```
I'm looking, specifically, for how the escaped Unicode characters are formatted _in the file_ — I don't think it can be as `\u####`, because if they were they'd be converted properly. There must be some other formatting in the file that only gets converted to `\u####` _after_ the data is loaded, at which point it's too late for the escapes to be substituted correctly

Once we have details on what the data looks like _in the file_, we can add correction logic **before** the data is read by `json.loads()`, so that it's interpreted properly.

If there are still issues with international character sets when loading 2.4.3 → 2.5.1, I'd definitely like to get them sorted out ASAP. We're hoping Debian will update their distro package (which is still on 2.4.3), so this could cause trouble for a lot of users still running 2.4.3 at the moment.

And I'm sure you'd like to be able to import your project, of course! Which should only take a quick, one-time `sed` command to repair, once I have that `grep` output and know what sort of formatting we can expect to find when loading 2.4.3 project data.

**Comment by MarcelWaldvogel** [comment]
I just ran into the same problem and my workaround was to open the `*.osp` file in an editor and replace the `\uXXXX` sequences with the actual character.

**Comment by MarcelWaldvogel** [comment]
To get this issue further, here is the relevant information from my `*.osp`. BTW: As 2.4.3 (at least on Ubuntu 20.04) outputs the JSON in a single line, `grep` is not very helpful. Here are some (typical) sample lines:

```JSON
"path": "2020 Er\u00f6ffnung Media/Some File Name - Commented.mp4",
"path": "2020 Er\u00f6ffnung Media/Logo-Something-1000.png",
"path": "2020 Er\u00f6ffnung Media/Some other File Name - Comment.mp4",
"path": "2020 Er\u00f6ffnung Media/Die gro\u00dfe W\u00f6stenei - Version f\u00fcr dich und mich.webm",
"path": "/home/marcel/SomeDir/OtherDir/NextDir/2020 Er\u00f6ffnung Something/2020 Er\u00f6ffnung Media/Logo-Something-1000.png",
"path": "/home/marcel/SomeDir/OtherDir/NextDir/2020 Er\u00f6ffnung Something/2020 Er\u00f6ffnung Media/Die gro\u00dfe W\u00f6stenei - Version f\u00fcr dich und mich.webm",
```
I found it interesting that some paths were absolute and some (for the same file!) were relative. In addition to replacing `\uXXXX` (see above), replacing all absolute by relative paths also results in a loadable project.

When opening the original file, OpenShot first asks for the "correct" location of the `png` file above, which is the first file with absolute path. It may be selected. According to the log, it will then auto-update the remaining absolute-path assets, however, it fails with the file with 3 `\uXXXX` escapes in the filename proper. This cannot be selected. Also, the file selector displays the `\uXXXX` as part of the name. This is consistent with @ferdnyc's statement that `json.loads()` is not converting the `\uXXXX` escapes.

However, why this should only happen for absolute paths is beyond me. Or does OpenShot treat absolute and relative paths different (and e.g. re-escapes absolute paths)?

**Comment by MarcelWaldvogel** [comment]
Just to be sure: `json.loads()` does decode the path, even though it contains the same escaped character multiple times (was just checking whether someone would have done a regular-expression replacement but forgot the `/g` modifier or made a similar mistake).

**Comment by MarcelWaldvogel** [comment]
Python's JSON module is definitely not the culprit:

```python
>>> c = open('file.osp').read()
>>> r'\u' in str(c)
True
>>> d = json.loads(c)
>>> r'\u' in str(d)
False
```

**Comment by MarcelWaldvogel** [comment]
My "make path relative" seems to have been a wrong lead. After looking into the code, [`replace_string_to_absolute`](https://github.com/OpenShot/openshot-qt/blob/develop/src/classes/json_data.py#L217) seems to be the culprit: It takes an (encoded) string which has been extracted using a regexp and encodes it again (using `json.dumps`), resulting in `\\uXXXX`, which `json.loads()` will not turn into the appropriate character, but just remove one of the backslashes.

If the directory path contains special non-ASCII characters, the path selector will help solve the issue, but if the file name proper contains them, it will not help. This is not a problem when reading 2.5.1-written files, as it uses UTF-8 when writing the JSON.

So the problem is only during the transition to 2.5.1 (ignoring 2.5.0 for now).

I suggest one of the following fixes:
1. (Cleaner) Do **not** do the relative->absolute path replacements on the file contents, but only after the JSON has been parsed.
2. (Less intrusive) JSON-decode the `path` string in `replace_string_to_absolute()` after it has been matched by the regexp in `convert_path_to_absolute()`. For this, the quotes would need to become part of the second match group, i.e., `path_regex` would now be `path_regex = re.compile(r'\"(image|path)\":.*?(\".*?\")')`
