### ISSUE TITLE
Transition: standard 'fade' is too fast

### ISSUE THREAD

**Issue by rexdk** [OpenShot/openshot-qt#3632]
I wish I was wrong about this...but:
The standard 'fade' transition happens over the first half of the transition only. It is complete by halfway through.

Thus if the user overlaps 2 clips by 4 seconds to get a slow fade, in fact the fade only lasts 2 seconds.
It's easy to verify using an all-white image and an all-black image, and checking the colour value from screenshots.

I don't know where to look in the code to verify this, but it looks to me as if the alpha of the first clip is adjusted pixel by pixel:
alpha = value + brightness (clamped to the range 0-1)
where brightness is the animated property of the transition, and value is the the value (HSV) from the transition mask (possibly lightness or intensity or something similar).

Workarounds:
1. double the length of the transition (yuck!) or
2. Set the final brightness keyframe to 0 (yuck!)
3. use the dissolve transition, or a custom transition with finer grain (hm)

I'm looking at this in a quest to help improve the user guide. I had already noticed that transitions were surprisingly quick, but thought it was me. Obviously this needs documenting for all but the most casual user.

With open source software, so often the documentation is ignored - but might I suggest that including documentation in the devlopment cycle would help prevent this sort of thing, because someone else is looking at any new feature and finding out how it really works (or doesn't). I've found more than a dozen bugs so far, as I've researched to improve the user guide.

One fix could be to use a new algorithm for the alpha, where half grey varies 1 to 0 over brightness 1 to -1. Then there could be a new transition "crossfade", using an all grey mask. The maths involves a division though (and a comparison), so there is more processing involved. It would also slightly change the behaviour of existing transitions. [ formula: alpha = (v<0.5) ? (b+2v)/(1+2v) : (b+1)/(3-2v) ]

win10 / 2.5.1 (both production version and daily build of 28July20)

**Comment by ferdnyc** [comment]
Yeah, this is #640 (and/or openshot/libopenshot#342, since that's where it would need to be solved). It has to do with how the "effect"-y transitions are implemented.

(Specifically: As grayscale animations that map to video mixing parameters. Black areas show one source video, white areas display the other source video, and gray areas mix the two together in proportion to the intensity.)

That's fine when your transition involves showing part of each source on the screen at the same time for the entire length of the effect (as in a wipe or pattern dissolve), but a _fade_ isn't really that at all.

I go into a (much) longer explanation at https://github.com/OpenShot/openshot-qt/issues/640#issuecomment-538781317 but basically there's no good way to implement a true fade using the transition machinery; they just aren't compatible. We either need to special-case it, or remove it from the transition list and offer some other method of doing fades.

(Keyframe animation on the Alpha parameter is by far the easiest way to do it _manually_, though that lacks the same UI visibility as a transition.)
