### ISSUE TITLE
Give me option to not generate thumbnail.

### ISSUE THREAD

**Issue by dailytabs** [OpenShot/openshot-qt#3643]
**Describe the new feature:**
I exported a video and a thumbnail directory was created. I did not ask for this and there were no options in the Export dialog to control this.

**Describe the solution you'd like:**
Give me an option.

**Describe alternatives you have considered:**
Delete the directory after it's created.

**Comment by dailytabs** [comment]
I think this actually came from me moving the project file... Don't care enough to verify, so just closing.

**Comment by ferdnyc** [comment]
@dailytabs What version are you running? Versions up to 2.4.4 would create "`thumbnail`" directories next to the project file, but since 2.5.0 a directory named <code><var>Project File Name</var>_assets</code> is created instead (so it's at least more obvious what it belongs to).

Export has never created any additional files, though; if something created a thumbnail directory for the exported video file, it wasn't OpenShot.
