### ISSUE TITLE
Need download for Windows 7 32-bit OS

### ISSUE THREAD

**Issue by jaykbwd** [OpenShot/openshot-qt#365]
The only downloads I can find on line are  for 2.1.0, but that wont run in a 32-bit environment. Where can I get a windows installer and version for 32-bit?

**Comment by jonoomph** [comment]
Currently OpenShot is only available for 64-bit versions of Windows. I might address this in the future and extend our Windows build environment to support both 32 and 64 bit builds, but the 64-bit version is much preferred, due to the larger amounts of RAM supported.

Just out of curiosity, how old of a computer are you using? Specs? Which version of Windows? Do you have a compelling case for releasing OpenShot on 32-bit Windows? I would love to be convinced. =)

**Comment by jaykbwd** [comment]
I don't know if there is a case for making OpenShot compatible with 32-bit. 
I use it on a Linux laptop, but wanted to use the same package at my church 
on a 2010-vintage Dell Vostro 220 desktop, with an Intel Core 2 running at 
2.93 GHz. It still has Windows 7 Home Premium as its OS.

Original email:
-----------------

**Comment by jonoomph** [comment]
Okay, thanks for the info. So, it looks like the Vostro 220 was released in 2008, and the Intel Core 2 should be 64-bit compatible. Here are a few workarounds:

1) Upgrade to a 64-bit version of Windows 7 (which might be a terrible idea, not sure) =)
2) Boot off a USB thumb-drive into Ubuntu, and use our AppImage on Ubuntu. Not ideal, but might work in a pinch.
3) Wait until I eventually configure an x86 32-bit build server... which might never happen (sorry).

Thanks and good luck!
-Jonathan

**Comment by repath** [comment]
I am getting error even I am using 32 bit version on Windows 10.,
most of the available version are for 64 bit.
can any one of you please help.

![open shot installation error](https://user-images.githubusercontent.com/24847308/54361025-24e71300-468c-11e9-92fa-2e072dfa99b1.PNG)
