### ISSUE TITLE
Stand-alone clip on timeline has incorrect length of ‘duration’ + 1 extra frame

### ISSUE THREAD

**Issue by patrasco** [OpenShot/openshot-qt#3656]
Frame by frame navigation on the timeline of a stand-alone clip counts one additional frame (than specified in properties duration). Snapping a new clip on the right edge, removes that extra frame.

This has been observed when placing a title with the same alignment and same duration on top of clip A. Both title and clip A show the same number of (incorrect) frames on the timeline. Adding a new clip B to the right of clip A removes one frame of A but (obviously) not of the title on the track above. The result is that the title now incorrectly extends for one frame over the newly added clip B.

Tested on version: 2.5.1-dev2

Test Procedure:
(1) Create new project, profile HD 1920x1080 / 25 fps (or any other frame count).
(2) Add media clip A onto an empty timeline and set Properties: ‘End’ = 1.00 (one second).
(3) Position the playhead at the beginning of clip A and move frame by frame on the timeline, counting the number of visible frames. The last visible frame of the clip on the timeline is counted at 26 (25 + 1) from the start.
(5) Place media clip B on the right edge of clip A (snapping = on).
(6) Position the playhead at the beginning of clip A and move frame by frame on the timeline, counting the number of visible frames. The last visible frame of clip A is now correctly counted at 25. The spurious frame has disappeared.

**Comment by ferdnyc** [comment]
OK, I can explain what's happening here. It's largely a question of semantics, but nothing is actually "changing size", though it's true things are not always as they appear.

As you say,
> The last visible frame of the clip on the timeline is counted at 26 (25 + 1) from the start.

That's position `00:00:01:00`, the 26th frame of a 25fps video in our 1-based frame numbering. Basically, the "end" value denotes the **start** of the final frame included in the clip; the actual video is longer by up to one frame-length.

When you snap two clips together, they get _overlapped_ by one frame, which is why it appears that the first clip has been shortened by one frame. You can observe this effect by adding a partially-transparent clip (such as one of the selections from the Emoji panel) on a track _above_ another video, then snapping its start to the end of the previous clip. What you'll see, going frame-by-frame, is the last frame of the first clip now has the first frame of the new clip overlaid on top of it. The same thing happens when you snap full-frame videos, it's just that the second clip completely obscures the first one.

AFAIK the overlapping is done because it tends to provide smoother transitions between clips, especially where the source videos may have different frame-rates from the project, each other, or _both_. OpenShot is not and has never claimed to be a precise, frame-accurate editor (something that's only possible when working with completely uncompressed video, realistically), and losing the odd final frame was judged preferable to possibly experiencing audio dropouts or even brief flashes of black screen between clips.

**Comment by ferdnyc** [comment]
Correction for the benefit of email followers, I updated my second-ish paragraph to read:

> That's position 00:00:01:01, the 26th frame of a 25fps video in our 1-based frame numbering. (There is no 00:00:01:00, 01:01 comes immediately after 01:25.) Basically, the "end" value denotes the start of the final frame included in the clip; the actual video is longer by up to one frame-length.

**Comment by ferdnyc** [comment]
And then updated it _again_ (oy) to read:

> That's position `00:00:01:01`, the 26th frame of a 25fps video in our 1-based frame numbering. (There is no `00:00:01:00`, `01:01` comes immediately after `00:25`.) Basically, the "end" value denotes the start of the final frame included in the clip; the actual video is longer by up to one frame-length.

**Comment by patrasco** [comment]
OK. Thanks. This makes sense. 

In the case of placing a title with the same alignment and same duration on top of clip A, then this solved it for me:
(1) Align a title above clip video A on track 1.
(2) Snap video clip B to right right of clip A. Clip B overlaps clip A by one frame.
(3) Create a short 'empty' clip with full transparency or a short fade transition clip.
(4) Snap the empty clip to the right of the title. This clip will overlap the title also by one frame.

**Comment by jimdi** [comment]
same problem with 1 extra frame at the start of clip. wher crop some video from middle of video

on preview can't see that frame - all ok, it appers only when export result
