### ISSUE TITLE
Thumbnail in the project files not updated when the original image-file has changed

### ISSUE THREAD

**Issue by ccvca** [OpenShot/openshot-qt#3687]
**Describe the bug:**
When the original image file changes the thumbnail is not regenerated. (I haven't check the additional cached attributes)

**Steps to reproduce the behavior:**
1. Add image to the project files
2. Replace the image file in the directory
3. Thumbnail is still the old image

**Expected behavior:**
Updated thumbnail for the updated file.

**System Details:**
- OpenShot Version [e.g. 2.5.1]: 2.5.1
- Operating System / Distro: Windows 10

**Ideas for a solution**

- Add "Reload from Disk" to the right click menu to update all cached properties
- Store a sha-hash of the file and compare this hash to the hash of the file on the disk
- Store Change-Dates and compare these dates when loading the project
- Detect file system changes for live updates (e.g. https://docs.microsoft.com/en-us/windows/win32/fileio/obtaining-directory-change-notifications)

**Comment by ferdnyc** [comment]
@ccvca What happens if you go into the Properties of the Project Files entry for that media, and click "Update"?

(I'm not 100% sure whether that will refresh any already-created Clips based on that file. I think probably _not_... but, worth a try.)

**Comment by ccvca** [comment]
As I have a german interface in OpenShot so I'm 100% not sure, if I found the correct button:
![grafik](https://user-images.githubusercontent.com/3939648/91539971-6fa92900-e91a-11ea-8422-39e439b41fc1.png)
"Dateieigenschaften" 
![grafik](https://user-images.githubusercontent.com/3939648/91540002-7cc61800-e91a-11ea-8c77-88db73a0fee3.png)
"Aktualisieren"
But if it is the expected one, nothing visible happens and the thumbnail keeps the same.

**Comment by ferdnyc** [comment]
Urgh, yeah in English those labels seem a bit clearer, as they use:
![image](https://user-images.githubusercontent.com/538020/91616763-6937a300-e954-11ea-8559-8b7ed31dcc9b.png)

But it sounds like we're talking about the same one, yeah.

OpenShot doesn't generally support external modification of the project files while it has them  open. It's not just the thumbnails that don't update, if you were to edit a media file the changes wouldn't be reflected in the preview either, at least not the parts that have already been cached. 

I'll flag this as an enhancement request, it's not really a _bug_ technically since the expected behavior was never intended to be present. (Saving and reopening the project will cause all of the media files to be re-scanned, as a pretty painless workaround.)

**Comment by ccvca** [comment]
> Saving and reopening the project will cause all of the media files to be re-scanned, as a pretty painless workaround.
I can't confirm this, the cached preview image is not regenerated. It seems to be loaded from the thumbnail folder(, which make totally sense from a performance point of view in large projects).
