### ISSUE TITLE
Transition 'source' property should be read-only

### ISSUE THREAD

**Issue by rexdk** [OpenShot/openshot-qt#3698]
This is a rather minor issue. Currently the source property of a transition (that is, the file name) can be edited. On pressing 'Enter' it reverts to the old file name.

It doesn't do any harm, but is confusing - and should not be editable I think.

But I guess very few people know that it's there anyway.

Win10 2.5.1-dev2

**Comment by ferdnyc** [comment]
Hmm, I see what you mean — the Source is, of course, editable in the sense that you can right-click on it and choose any Project Files or Transitions item from the resulting menu. But the field can also be activated for text editing by double-clicking on it.

...I'm not sure that's entirely _wrong_, TBH. By which I mean, it may have potential uses. Say, if you wanted to copy the filename in order to search for it on the filesystem. Something like that.

As long as any edits to the field are properly ignored, and it seems like they are, there doesn't seem to be too much harm in it being accessible as a text-entry field as well. We _might_ be able to set the **contents** of the text field read-only, so the user can view and copy it without being able to change anything, but I'm a bit skeptical about Qt letting us do that since the double-click action is explicitly an "Edit cell" binding. Ostensibly-editable text fields that simply ignore any non-valid changes aren't entirely unheard of, either.

Still, if someone wanted to tackle it, and kept in mind the value of being able to access the text contents of the cell in a read-only fashion, it could make for a good first-time PR.

**Comment by rexdk** [comment]
@ferdnyc I thought I'd left an earlier comment on this, but it seems not to have appeared. Anyway, I was amazed and delighted to discover that the property could be edited by right clicking. That's why we need a better manual :). 

If we made it look read only, that would be wrong, as it isn't read only. It would simply have to fail to respond to a double click.

But there is another small issue, in that when you change the file using right click, the panel title does not change until it is re-opened. Small issues, so low priority.

**Comment by ferdnyc** [comment]
@rexdk 
> If we made it look read only, that would be wrong, as it isn't read only. It would simply have to fail to respond to a double click.

Well, that's the thing, failing to respond to a double-click is kind of the definition of read-only. Like I said, double-clicking means "edit value". 

Not all editable cells _do_ respond to double-clicking, of course. Double-clicking a property like "Audio Mixing", where only pre-defined values are valid selections, won't IIRC get you an edit field. But without that edit interface there'd also be no way to get to the Source field contents if you wanted to copy (or even just see) the path/filename.

> But there is another small issue, in that when you change the file using right click, the panel title does not change until it is re-opened. Small issues, so low priority.

Hmm... Panel _title_? Oh, you mean the label in the combo box at the top of the Properties panel, where you select which timeline element you're viewing properties for? Tsk, wish I could say that's surprising, but since that list is generated statically every time it's populated it makes sense it wouldn't track changes.

(Normally in Qt that list would be automatically populated by a data model, which would then automatically emit notification signals when anything is updated. It's quite a clever system, really. That we typically don't make use of.)

Another for the "good first issue" pile, though I can't tag this issue twice.
