### ISSUE TITLE
Position a clip using markers

### ISSUE THREAD

**Issue by 666fabulous666** [OpenShot/openshot-qt#3713]
This is related to topic #914 which has been closed and should be considered in my opinion.

Here is the use I have of markers: a lecture has been recorded, and I need to put the slides on the corner of the video, so I first put markers, and now I'd like to insert clips with a static image from one marker to the next one. I think there should be a simple way to do this, otherwise markers aren't really useful... It allows for moving the playhead at the position of the marker, so it is possible to set the beginning of the clip using 'add to timeline'. The problem is that there doesn't seem to be any way to do the same with the end of the clip (using snapping for instance).

Moreover the properties 'start' and 'stop' are not the time at which the clip starts and stops, but 'stop' stands for the duration I think and 'start' stands for something I don't really get. But in the software a variable probably sets the starting time and the ending time of clips no? Why not just giving the access to them for the user?

**Comment by ferdnyc** [comment]
@666fabulous666 

Yeah, the need for snapping on resize (for _both_ ends of a clip) is a real thing, that would be helpful to users.

Marker position snapping would also be helpful, however there's currently a workaround for that specifically _because_ the Playhead can be positioned on markers. The Playhead **does** provide a snapping position when moving clips.

I agree it would be more convenient if you didn't _have_ to take the extra step, but for the moment there's a usable workaround that lets you snap (indirectly) to a marker position: You just need to first position the Playhead at the marker you want to snap to.

Regarding "Start": The value for "Start" is the starting position _within_ a clip (expressed in seconds). So, if you had a 25fps video where you'd trimmed off the first 25 frames, its Start value would be `1.000`. The "End" value is, similarly, the end position "within" that clip. "End"  = "Start" + "Duration".

The value for the _location_ of the clip on the overall timeline is "Position", that's what you'd want to adjust to move a clip's starting point. There are a lot of samey values that had to be given distinct names, it's definitely not intuitive or obvious but they're at least unambiguous and consistent once you've got them sorted out.

There actually isn't any variable that stores the end position of a clip (on the timeline), though. Maybe there should be, but currently in the code it's always computed from "Position" + "Duration". In fact, when you drag the end of a clip what you're adjusting is _not_ the end-position, but rather the duration — those adjustments are always made relative to the "Position" (timeline-start-point) value. That does make right-edge anchoring/positioning somewhat inconvenient/troublesome, though.

**Comment by 666fabulous666** [comment]
Ok thank you @ferdnyc for your answer, this is good to have a better understanding of the values 'start', 'stop', 'position' and 'duration'. I confess it was a bit hard to guess, perhaps because the use I had doesn't lead to setting a starting position within a clip but on the overall timeline instead.

Also I insist on the fact that to me, the snapping option is a solution, but a more 'professional' user may prefer using shortcuts and numerical values avoiding the mouse whenever it is possible, so on a given track I think it is quite natural to ask a clip to last 'untill next marker' so that to chain the clips you just need to insert the next clip at the next marker's position, which is easy since the playhead has a nice shortcut to be moved from one marker another.

**Comment by ferdnyc** [comment]
@666fabulous666 

> Also I insist on the fact that to me, the snapping option is a solution, but a more 'professional' user may prefer using shortcuts and numerical values avoiding the mouse whenever it is possible, 

Well, understand that those users aren't our _primary_ focus. They're not unwelcome, either, but the goal for the OpenShot UI is to provide something usable by users _without_ experience using professional-grade editing suites — those people will invariably be disappointed by OpenShot's comparatively basic features, and lack of the kind of streamlining you're referring to in the interface. That's fine; OpenShot is meant to be something a user might use _before_ eventually outgrowing it to a more advanced tool, not something that can substitute for those tools.

> so on a given track I think it is quite natural to ask a clip to last 'untill next marker' 

Well, for doing _that_ specifically, there's already an easier way that doesn't involve any resizing at all (and can be done entirely with the keyboard) — you can use the Slice features.

For example, if you have a clip on the timeline that you want to end at a certain time (but currently runs longer), just position the Playhead at that end  time (using a marker or not), then activate the **Slice Selected - Keep Left Side** action (shortcut: <kbd>D</kbd>), and everything past that point will be removed so that the clip ends at the Playhead position. 

You can even slice multiple clips at once, as the action name implies. Or, you can use **Slice All - Keep left Side** from the Playhead context menu (or <kbd>Ctrl</kbd>+<kbd>L</kbd>) to do the same thing to all clips touching the Playhead, without having to select them first.

> so that to chain the clips you just need to insert the next clip at the next marker's position, which is easy since the playhead has a nice shortcut to be moved from one marker another.

Assuming you've already sliced your other clips (and you don't need them overlapped), you don't even really _need_ a marker for that. Prev/Next Marker will also stop at both edges of any selected clips, so you can seek to end points even without explicitly setting markers.

**Comment by 666fabulous666** [comment]
This is a really helpful answer @ferdnyc  thank you!
