### ISSUE TITLE
NoneType object is not subscriptable

### ISSUE THREAD

**Issue by Squidsheep** [OpenShot/openshot-qt#3719]
My project file has been effected by the "NoneType object is not subscriptable" issue which has apparently been fixed before hand. Before the file was inaccessible, I was mid project when I was suddenly unable to add files. I saved and quit, and now can't open the file.

Is there any method to repair the file?
[Metal Gnome Solid V.zip](https://github.com/OpenShot/openshot-qt/files/5213412/Metal.Gnome.Solid.V.zip)

**Comment by ferdnyc** [comment]
Ugh, I can't believe it's been 24 days since you posted this.  I am _so_ sorry about that.

In case it's still useful, this updated `.osp` (renamed to `.osp.txt` for Github) should be fixed to prevent that error. It does still have external dependencies on the following files:

* `../gnome.png`
* `../MGSV_TPP_-_Chapter_1_Ending_Scene[Youtubetomp3.sc].mp4`

So before opening, you should rename the file to remove the `.txt` extension, and place it (back) in a location where those files are in the parent folder.

[Metal Gnome.osp.txt](https://github.com/OpenShot/openshot-qt/files/5337533/Metal.Gnome.osp.txt)

Your file actually contained issues that triggered a new, as-yet-undiagnosed form of the "NoneType object is not subscriptable" error that's still present even in 2.5.1 / the development tree, so I'll be opening a PR shortly with a fix for that. Thanks for reporting! And apologies again for the long response delay.
