### ISSUE TITLE
Arrow Keys not working in latest Daily Build

### ISSUE THREAD

**Issue by USATechDude** [OpenShot/openshot-qt#3760]
Operating System: macOS Catalina 10.15.7
OpenShot Version: OpenShot-v2.5.1-dev2-1602472203-414a2cda-12ddb3df-x86_64.dmg
System Specifications: MacBook Pro 16 (2019) / Intel i9-9880H @ 2.4 GHz / 16GB / 512GB / Radeon Pro 5500M 8GB

When trying to move the playhead one frame at a time, the arrow keys are not working.  I clicked on the blue top of the playhead and tried all of the function keys in combination with the arrow keys but I cannot move the playhead one frame at a time.

**Comment by ferdnyc** [comment]
In Linux, with the WebEngine backend, there are also problems though they're a bit different — I honestly thought I'd opened an issue already, but it looks like I only mentioned them in https://github.com/OpenShot/openshot-qt/pull/3604#issuecomment-661311371 I'll quote my report from there:

> #### Steps to reproduce:
> 1. Click somewhere directly on the timeline ruler, to position the playhead at the point clicked
> 1. Use <kbd>←</kbd> or <kbd>→</kbd> to scrub left or right on the timeline
> 1. Watch the preview update as expected
> 1. Click again to position the playhead, but this time click somewhere **inside** the _timeline tracks container_ — say, directly on a clip — instead of on the ruler.
> 1. Use <kbd>←</kbd> or <kbd>→</kbd> to scrub left or right on the timeline
> 
> #### Expected result
> * Same as step 3: The playhead moves, the preview updates, nothing else
> #### Actual result
> * **The tracks container side-scrolls** (and the playhead moves, but more slowly) — which quickly scrolls the playhead out of view, assuming a close enough zoom.
> 

WebEngine is proving frustratingly difficult to completely wrest keyboard control away from. (ISTR you also reported another issue related to mouse or keyboard actions in the Timeline? I'm sure it's all part of the same three-way OpenShot-vs.-Qt-vs.-WebEngine struggle for control of the user's input devices.)

As far as solving playhead positioning in the short term, we should probably just add a pair of _alternate_ keybindings for left/right frame-by-frame movement, since the arrow keys aren't 100% reliable on all systems.

**Comment by ferdnyc** [comment]
Possibilities that come to mind, off the top of my head (though I'd have to see which are already taken, I haven't checked:
* <kbd>[</kbd> and <kbd>]</kbd>  (Downside: Possibly not present on all keyboards?)
* <kbd><</kbd> and <kbd>></kbd>   (Downside: Requires shift)
* <kbd>,</kbd> and <kbd>.</kbd>  (Unshifted versions of the previous. Downside: confusing, probably QWERTY-centric.)
* <kbd>j</kbd> and <kbd>k</kbd>  (Downside: Crazy old-school, QWERTY-centric.)

One last option, if it would work, is this:
* <kbd>Alt</kbd>+<kbd>←</kbd> and <kbd>Alt</kbd>+<kbd>→</kbd> (or I guess <kbd>Option</kbd>+<kbd>←</kbd>/<kbd>→</kbd>, on the Mac keyboard)

We already have <kbd>Ctrl</kbd>+<kbd>←</kbd> and <kbd>Ctrl</kbd>+<kbd>→</kbd> bound to Jump to Start / Jump to End, but I think the <kbd>Alt</kbd> modifier versions are free.

Of course, that assumes it would even work. @USATechDude , do <kbd>Ctrl</kbd>+<kbd>←</kbd> and <kbd>Ctrl</kbd>+<kbd>→</kbd> still work to perform Jump to Start/End on the Mac, with 2.5.1-dev2? If they do, then there's a good chance that <kbd>Alt</kbd>/<kbd>Option</kbd> arrow bindings would as well.

**Comment by ferdnyc** [comment]
The Avidemux team used to use <kbd>[</kbd> and <kbd>]</kbd> as  their scrub bindings, but switched them to <kbd>Ctrl</kbd>+<kbd>PgUp</kbd>/<kbd>PgDown</kbd>. The impression I got was that the square brace bindings, while convenient on English keyboards, weren't that good a choice internationally, so that's why I'm unsure about those.

**Comment by ferdnyc** [comment]
Whoops, scratch <kbd>J</kbd> and <kbd>K</kbd>.

<kbd>K</kbd> is already an alternate Play binding, and <kbd>J</kbd> and <kbd>L</kbd> are Rewind / Fast-Forward bindings.

Looks like all the rest of the options I listed are _available_, though some of them still may not be very good ideas.

**Comment by USATechDude** [comment]
> Of course, that assumes it would even work. @USATechDude , do Ctrl+← and Ctrl+→ still work to perform Jump to Start/End Prev/Next Marker on the Mac, with 2.5.1-dev2? If they do, then there's a good chance that Alt/Option arrow bindings would as well.

I am not sure.  OpenShot v2.5.1-dev2 will not launch on my MacBook Pro 16 with macOS 11.0.1 (Big Sur) even after a complete rebuild of the operating system from scratch.

Update: OpenShot v2.5.1-dev2 (6028) kept crashing on my macOS 10.15.7 (Catalina) VM but I finally managed to load a project.  Using ⌘+Arrow Key does move between key frames, markers, and Start/End.  I remapped the Next Frame and Previous Frame keyboard commands to ALT+Right Arrow Key and ALT+Left Arrow Key, respectively.  These key mappings did not work.  I tried mapping the keys to > and < but those keys did not work either.

**Comment by USATechDude** [comment]
@ferdnyc 
I tried remapping Next Frame and Previous Frame keyboard shortcuts in v2.5.1 on my MacBook Pro 16, and I still could not use the keys to move the playhead one frame at a time.

**Comment by USATechDude** [comment]
@ferdnyc 
I found the Keyboard Viewer app in macOS 11.0.1 (Big Sur), and I verified that my arrow keys are working when I press them on my keyboard.  However, when I click the corresponding key on the Keyboard Viewer, the playhead moves one frame in the direction that I chose.  It seems that OpenShot is not handling the keyboard press but does handle the key signal from the Keyboard Viewer.

**Comment by gcleaves** [comment]
This is still a problem with the daily build as of Jan 25 2022
