### ISSUE TITLE
Can't import photo files, Old version did it without problems

### ISSUE THREAD

**Issue by Austtony** [OpenShot/openshot-qt#3788]
**Describe the bug**
I updated to new version and I cant import photos, I tried dragging and "import files' and doesn't work, it shows busy but after some time nothing is imported. 
The old version worked fine.

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Windows-10-10.0.18362
- Processor: AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-GB', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1603402769-07a447c9-78db4b94-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/0dr3dewoajirgym6wig5iigpvskyggut/openshot-qt.zip) (125 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Comment by ferdnyc** [comment]
@Austtony 

I took a look at your log file, and it appears that OpenShot isn't able to contact its built-in HTTP server to load the image thumbnails. (Because the interface is partly web-based, running in an internal web browser, the interface loads thumbnail images using local web requests.)

I'm not quite sure what the cause would be. There don't appear to be any errors logged other than the thumbnail request failures themselves. But something is interfering with the retrieval of those images.
