### ISSUE TITLE
Original video file remain locked on HDD after doing an export to another file and removing it from both timeline and project

### ISSUE THREAD

**Issue by mamworker** [OpenShot/openshot-qt#3791]
**Steps to reproduce the behaviour:**

1) Open a new project
2) Add one clip from the HDD to to the project (assume this is called 'original.mp4')
3) Drag that clip to Track 1
4) Use File | Export Project | export video to export the clip to 'new.mp4'

5) In file explorer, try to delete 'original.mp4' or move it to another location

   **Expected behaviour**
     The file 'original.mp4' cannot be deleted or moved as its open in Openshot. 

    **Actual behaviour**
     The file 'original.mp4' cannot be deleted or moved as its open in Openshot.

So far no problem, But,,,

6) Remove the clip 'original.mp4' from track 1
7) Remove the clip 'original.mp4' from the project

8) In file explorer, try to delete 'original.mp4' or move it to another location

   **Expected behaviour**
    The file  'original.mp4' can now be deleted or moved as it should no longer be open in Openshot
  
 **Actual behaviour**   BUG BUG BUG
       The file 'original.mp4' STILL cannot be deleted or moved, 
       OS says it is open in Openshot, but no files are showing in Openshot as they have all been removed in steps 6 and 7
       This issue persists even after waiting a reasonable time for the locks to release

**Workaround**

9) Close down Openshot entirely

10) In file explorer, try to delete 'original.mp4' or move it to another location
       **Expected behaviour**
        The file  'original.mp4' can now be deleted or moved as Openshot is no longer running
      **Actual behaviour**
      The file  'original.mp4' can now be deleted or moved 

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Windows-10-10.0.18362
- Processor: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-GB', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-1603697889-07a447c9-46debb51-x86_64.exe

**Comment by rexdk** [comment]
This has been discussed a couple of times here recently, but I can't find where. I understand that in essence Openshot keeps an undo history - even when the project is closed. So it thinks it needs to keep any file it has seen locked, in case an undo calls for that file again.

It is daft in my view, but it is by design. I guess people will keep reporting it as a bug until common sense prevails....  Sorry!

**Comment by ferdnyc** [comment]
It was discussed in #3435, and as I said in https://github.com/OpenShot/openshot-qt/issues/3435#issuecomment-716969048 it doesn't have anything to do with the undo functionality, and it's not intentional. It sounds like it may be a change that either Qt or Microsoft made, since it's only been reproduced so far by users running on Windows 10.

**Comment by ferdnyc** [comment]
I am curious about one thing, if @mamworker (or anyone else) could test it: After step 7 in your report, what happens if you select **File > New Project** in OpenShot? Does that release the file lock?

If so, then it could be that we're not doing something we should be, when we remove files from the Project Files list.

**Comment by mamworker** [comment]
I tried that just now.  I repeated steps up to step 7 so that I no longer had any clips showing in the timeline or project and clicked File | New project. 
I was asked if I wanted to save the current project. 
I clicked No but the file was still locked afterwards. 

Then I shut down the application (which released the lock as usual) and repeated the exercise from step 1, this time choosing Yes when asked to save the project. It saved a .OSP file - presumably with nothing in it as there were no clips in the project at this stage. But the original video file is still locked until I completely shut down.

Then as an experiment I started the application again and used File | open project to open the (empty?) project I had just saved. No clips were shown in the project box or the timeline as I expected but also no lock was put on the original video file either.

I guess this is to be expected as the project contained no files so it wouldn't have known which file to lock anyway.

Hope this helps

**Comment by ferdnyc** [comment]
@mamworker It does, actually, thanks very much! 

> Then I shut down the application (which released the lock as usual) and repeated the exercise from step 1, this time choosing Yes when asked to save the project. It saved a .OSP file - presumably with nothing in it as there were no clips in the project at this stage.

Unless you cleared it, the project file probably contained a project profile (your default one, unless changed), an import path (which is updated every time you import, to the imported file's parent directory), and the undo history for all of the actions you'd previously performed. But yeah, the fact that you can have an _empty_ timeline + project files list still treated as a project with data to save is one of the things that makes the persistent undo history a weird thing.

The fact that File > New Project didn't help either definitely absolves the undo history, it's cleared completely at that point. It also makes me even more convinced that something has changed in the underlying Qt/Microsoft code. Something seems to be holding file handles open that previously would have been released. Most likely, it's because there's either a Python object or a libopenshot C++ object somewhere that's not being garbage-collected as quickly as it used to be.

I'll see if I can reproduce this in a Win10 VM, if so I can look for some more clues. Thanks again.

**Comment by ferdnyc** [comment]
So, this is interesting:

1. Yes, easily reproduced with Win10 running in a VM on Linux
1. Importing a file _briefly_ opens it (almost too fast to catch), but that handle is immediately closed again, as it should be.
1. Opening a video or audio file in the "Split Clip..." interface opens it, but that handle is closed shortly after the window is closed. That's true whether or not a new Project File entry is created using the Split Clip tool.
1. Video & audio files are opened the moment they hit the Timeline, and seemingly stay open in the process _**forever**_ — no matter what. The only thing that closes a Timeline'd file handle once it's opened is reimporting the same file (which also creates a new handle to replace the destroyed one, so it doesn't actually get us anywhere).
1. In fact, adding a file to the Timeline, removing that Clip, then re-adding the file creates an _additional_ dangling handle to the same file which will also never close under any circumstances.
1. However, adding multiple clips for the same physical disk file does not create additional handles, even temporary ones, and even if those clips represent different Project Files entries.

So, for instance, this is how a session might play out:
1. import `video.mp4`
    * Total files: 1
1. Drag it to the Timeline
    * Total files: 1, total clips: 1, total handles: 1
1. Remove that Clip
    * Total files: 1, total clips: 0, total handles: 1
1. Add the file to the Timeline _again_
    * Total files: 1, total clips: 1, total handles: 2
1. Drag the file to the Timeline three more times
   * Total files: 1, total clips: 4, total handles: 2
1. Remove all of the Clips
   * Total files: 1, total clips: 0, total handles: 2
1. Open the file in Split Clip
   * Total files: 1, total clips: 0, total handles: 3
1. Close Split Clip without doing anything
   * Total files: 1, total clips: 0, total handles: 2
1. Open Split Clip again
   * Total files: 1, total clips: 0, total handles: 3
1. Create a new Project Files entry from part of the imported file
   * Total files: 2, total clips: 0, total handles: 2
1. Drag the new file to the Timeline
   * Total files: 2, total clips: 1, total handles: 3
1. Drag the original file to the Timeline
   * Total files: 2, total clips: 2, total handles: 3
1. Remove both file entries
   * Total files: 0, total clips: 0, total handles: 3

Nothing short of exiting the application will destroy those 3 dangling handles. Why? I still really don't know.

(...Hey, I said it was "_interesting_", not "useful" :roll_eyes: )

**Comment by ferdnyc** [comment]
Oh, wait! I do know. Because of _this_:

1. Import file, drag to Timeline, blah blah blah.
    * Total files: 1, total clips: 1, total handles: 1
1. Change the Duration of the clip by dragging its right edge
    * Total files: 1, total clips: 1, total handles: 2
1. Change the Start value of the clip by dragging its _left_ edge
    * Total files: 1, total clips: 1, total handles: 3
1. Remove the file
    * Total files: 0, total clips: 0, total handles: 3
1. Load a different file, place on Timeline
    * Total files: 1, total clips: 1, total handles: 3 file1, 1 file2
1. Screw around with it, moving it and dragging edges
    * (Eventually...) Total files: 1, total clips: 1, total handles: 1 file1, 2-4 file2

So, it's definitely the preview player instance. The culprit is at least _partly_ found right here:

https://github.com/OpenShot/openshot-qt/blob/925427d9d157d962efb2cca28cbfb18f4270028a/src/windows/preview_thread.py#L282-L292

Which is why the extra multiple handles for the removed clip eventually get closed. That still doesn't quite explain the _first_ (and still immortal) dangling handle, but it's a good bet it lives around that same part of the code.

**Comment by mamworker** [comment]
Looks like I've opened a can of worms here. 
Still, I always appreciate bug reports for the database software that I write (as I do love a challenge!), so I hope some good comes out of my post here and you enjoy sorting this bug out.
