### ISSUE TITLE
Dissolving Text does not fully dissolve, last worked in 2.4.4

### ISSUE THREAD

**Issue by sysopj** [OpenShot/openshot-qt#3858]
**Describe the bug**
Dissolving Text does not fully dissolve.  It finishes with many particles still on the last frame.  Last worked in 2.4.4 with Blender 2.79b.

**Steps to reproduce the behavior:**
1. Go to 'Title'
2. Click on 'Animate Title'
3. Scroll down to 'Dissolve Text'
4. Use defaults, or customize
5. See error

**Expected behavior**
The last frame of the animation should be blank.

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev2
- Platform: Windows-10-10.0.19041
- Processor: AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-6042-39b4aa97-2cb4eeff-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/ed9va5pw0cw5kyapbjeq1iaonoyqpf8n/openshot-qt.zip) (10 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)

**Comment by ferdnyc** [comment]
@sysopj This is still happening with the latest Daily Builds? I could've sworn I fixed that in #3749.

Or, oh, wait... I think I understand. The particles aren't fully clearing out of the scene, you're saying? Hmm. 

With the update to Blender 2.80, the Dissolve effect (and all of our particle-based effects) had to be massively reworked from their 2.7x versions. Most of that was later adjusted in #3353 and #3749.

But the end result of all those changes was that the dissolve effect's parameters went pretty much back to what they were under 2.7x. However, even in that release, technically the particle lifetimes didn't all expire until frame 140, whereas the animation ends at frame 128. So, I can definitely see how it's possible some particles would still be alive at the end.

I can shorten the lifetimes by 12 frames, so that the last remaining particles will all be sure to die out by frame 128, and we can see how that looks.

Do you have sample settings for the animation parameters, that would illustrate the problem? I don't doubt it happens with all settings to some degree, but the size of the text being rendered and other factors will affect this. I want to be sure I test with a setup that's relatively close to what you're reporting, so that I can see what you're seeing.


 of the effects had their particle lifetimes set to end before the last frame of the video. (They mostly had a lifetime of around 80 frames, so the ones that were created starting at frame 1 would be dead just a little over halfway through the rendered animation.)

Problem is, as of Blender 2.80, when particles died off in the scene they were _resetting_ to their initial position, meaning that a little more than halfway through the video, the text would **reassemble** itself as if the dissolve had never started running. So, I increased the particle lifetimes to keep them all alive throughout the entire render, ensuring that they wouldn't reset. But, that means they can now be visible on screen even at the end of the animation.

**Comment by sysopj** [comment]
Been a busy week, I have updated to 6120.  Using Blender 2.83 (2.9 doesn't work).  Default settings, no customization of the "Dissolving Text".  Last frame (127) is over 50% full of particles still. Frame 128 is black, thus suddenly just blanks out not dissolve out. Might need more than 128 frames to fully render.

I have tried other settings but have not found a working one, so I use an older version for now.

Frame 1:
![TitleFileName0001](https://user-images.githubusercontent.com/47713002/101233641-98507400-36fc-11eb-864b-76de338fae52.png)

Frame 127:
![TitleFileName0127](https://user-images.githubusercontent.com/47713002/101233636-8cfd4880-36fc-11eb-969f-a7f20f88ebd5.png)

Frame 128:
![TitleFileName0128](https://user-images.githubusercontent.com/47713002/101233652-a900ea00-36fc-11eb-840c-94299537fcfe.png)


Thank You for looking into this.

**Comment by ferdnyc** [comment]
@sysopj Perfect, thanks. I've made some adjustments to speed up the effect a bit and have the particles die off sooner, the animation should come to a natural end by around frame 124 now. (A few completely empty frames at the end will render almost instantly, and it allows more flexibility for how the animation is positioned on the Timeline.) 

I'm running a test render now, same all-defaults setup. If it comes out looking reasonable I'll post some frames and submit a PR to make that change.

In the meantime, I've tracked down the issue with using Blender 2.90+ to another Blender API change, some of the code we use in 2.83 with no problems isn't compatible with 2.90+. Looks like our scripts will have to be updated again. I'll start looking into that, and see if there's an easy way to support 2.8x and 2.9x simultaneously. I'd hate to have to do another hard version break like we had to with 2.80.

**Comment by ferdnyc** [comment]
Well, I was wrong about the Blender issue (I was looking at old code), but I had no problem using Blender 2.91 with OpenShot. I used it to generate this animation, in fact. 

This is Dissolving Text with full (but tweaked) default parameters, I've adjusted the animation to run quicker and to completely die off before the last frame. Here's an animated GIF conversion of the results. Let me know what you think, because PR #3897 will make this the new settings if merged.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/538020/101258210-02fab300-36ef-11eb-886b-ff5711d095c1.gif)


Oh, the "Zzzzzz...." in the lower-right corner at the end is an artificial delay I added to the GIF loop,  before it repeats — it's meant to signify that it isn't part of the animation, when you see "Zzzzz..." the title sequence has already completed and it's just waiting to start the loop over again.
