### ISSUE TITLE
Can't start up Appimage on Ubuntu 20.10

### ISSUE THREAD

**Issue by MakiWolf** [OpenShot/openshot-qt#3859]
**Describe the bug:**
Can't start up Appimage on Linux

**Steps to reproduce the behavior:**
1. Download AppImage
2. chmod a+x
3. ./OpenShot-v2.5.1-x86_64.AppImage

**System Details:**
- OpenShot Version: 2.5.1 
- Operating System / Distro: Ubuntu 20.10 and Fedora 33

**Screenshots:** 
![image](https://user-images.githubusercontent.com/73300633/99904037-c5e2f980-2cc8-11eb-8e5b-643d4907f778.png)

Also latest daily build can't start

![image](https://user-images.githubusercontent.com/73300633/99904105-25d9a000-2cc9-11eb-9096-110c62049c2e.png)

**Comment by ferdnyc** [comment]
@MakiWolf 

Yeah, sorry, the 2.5.1 release AppImage isn't compatible with Ubuntu 20.10 (or Fedora 33, or a few other recent OS releases), it turns out.

You _may_ be able to use the latest Daily Build version (from https://openshot.org/download/#daily), we've had conflicting reports on whether the new builds solve the issues — they do on Fedora 33, but one Ubuntu user reported no for 20.10. (It'd be great to have another data point on that, though.)

**Comment by soruk42** [comment]
The latest Daily works for CentOS 8 (OpenShot-v2.5.1-dev2-6045-39b4aa97-2cb4eeff-x86_64.AppImage), whereas the release one does not.

**Comment by gorghino** [comment]
OpenShot-v2.5.1-x86_64.AppImage **doesn't** start on Pop!_OS 20.10 (same import error as OP).
OpenShot-v2.5.1-dev2-daily-6605-f7472d5b-cdfe5a15-x86_64.AppImage doesn't either, aborting after creating the session.

**Comment by MakiWolf** [comment]
This issue also still exists also in new Ubuntu version 21.04.

**Comment by StarBootics** [comment]
I can confirm this issue also still exists also in new Ubuntu version 21.04.

Further more the "libopenshot.log" is not generated at all.

[openshot-qt.zip](https://github.com/OpenShot/openshot-qt/files/6444316/openshot-qt.zip)

**Comment by JacksonRG** [comment]
@StarBootics, If you have an old `~/.openshot_qt` file? If so, have you tried clearing it before starting the Appimage?
