### ISSUE TITLE
features that should be added to openshot

### ISSUE THREAD

**Issue by SirSandman-git** [OpenShot/openshot-qt#3895]
sound/audio effects. These can really help with making videos. Some would include: Pitch, echo, metallic, bit crusher, etc.

GIFs. I am never able to upload gif files so this can help with that.

Copy and pasting. Usually, my computer gets filled with files I use for edits but adding a copy and paste function would greatly help with that.

Filters. These would be like effects in a way, but you can put them over a video. Kind of like the wave and pixelate effect. These could also be dragged around to cover certain areas. Think: photo booth effects.

drawing. This allows you to draw something and then put it on screen, similarly to titles.

I don't expect these to be actually added, but these are things that would make the software have more content.

no alternatives 

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your request.

**Comment by Innitinnuit** [comment]
There is a copy and paste feature, although it's not in the 'Edit' menu as one would expect. Right click on the clip in the timeline > copy. It also allows you to copy effects there too. To paste right click in the timeline.

I tend to use Audacity for all my sound editing, even basic fading in and out because it's troublesome to get it accurate in openshot. Would be nice to have some more sound features within  OPS though, I agree.

Filters would be really nice. I  like that suggestion. Drawing too.

The new daily builds have an emoji section, which I find utterly baffling considering that suggestions such as yours aren't there.

**Comment by arvindnc** [comment]
Probably you can add something in the paste option like the one in the audacity which does a repetitive paste for 'n' number of times specified by the user. The effect name in audacity is called repeat.
