### ISSUE TITLE
Sound playback fails after audio file edited with SoundEditor

### ISSUE THREAD

**Issue by OpenShooter** [OpenShot/openshot-qt#3914]
This is some additional information to assist developers in tracking down previously-reported bugs in v2.5.1 with sound playback.
I created an audio file using Window Sound Recorder, which produced a .wma file. I added this to my video project, and it plays back more or less correctly.
I edited the file using Microsoft SoundEditor. The audio in the video project now doesn't play back correctly; it sounds like uh-silence-uh-silence-uh.
Using VLC, I got the media information, which is in the attached file. VLC plays back the audio file perfectly.
![OpenShot sound not playing](https://user-images.githubusercontent.com/74981577/101819963-c9ed8480-3ada-11eb-8e42-e17a860e3167.png)

**Comment by USATechDude** [comment]
Did you change the Audio Sample Rate of your default profile in the Preferences window of OpenShot?  OpenShot's default profile initially is 720p 30 fps @44100 Hz.

**Comment by OpenShooter** [comment]
At 11:08 AM 12/13/2020, you wrote:

>Did you change the Audio Sample Rate of your default profile in the 
>Preferences window of OpenShot? OpenShot's default profile initially 
>is 720p 30 fps <https://github.com/44100>@44100 Hz.

I don't understand why this would have any effect; my understanding 
is that this is the default output format.

My project has audio clips at 44100. When I added one at 48000, it 
doesn't play properly. Even if the audio sample rate applied to 
input, changing it wouldn't work.

I expect OpenShot to accept multiple video and audio formats as 
input, and produce a single audio and video format on output 
(export). Is that not how it works?

**Comment by USATechDude** [comment]
OpenShot should accept multiple source clips of different formats with different audio sample rates and export them into a single video clip.  On most of the supported operating systems, this feature works quite well. However, Windows is a unique creature all to its own.  The majority of the requests for support regarding audio issues that we receive are for Windows-based systems, not just because Windows is used on [approximately 90% of all PCs](https://www.educba.com/linux-vs-mac-vs-windows/) worldwide.

When I first started using OpenShot, I developed a routine that involved converting my source video clips to MP4 and my source audio clips to WAV before I imported them into OpenShot.  I didn't do this because of reading the [Reddit Community](https://www.reddit.com/r/OpenShot/) posts or the GitHub repository issues.  Through trial and error, I discovered that I achieved better performance by using those file types when I edited my projects.  Some people feel that using multiple programs to create a single project is a hassle (and IMO can be a hassle).  After joining the Reddit Community, I discovered that using multiple applications was an accepted standard practice among those who create videos regularly, especially those who monetize their videos.

I do know that the upcoming stable version will have some pretty major improvements to the audio system.  OpenShot is moving in a direction to provide more functionality with audio processing and we're anxiously waiting for the upgrades.  In the meantime, using a free audio editor [such as Audacity](https://www.audacityteam.org/) to import your clips and export the audio as WAV files should help clear up audio issues within OpenShot projects.

**Comment by OpenShooter** [comment]
At 01:11 PM 12/14/2020, you wrote:
>I do know that the upcoming stable version will have some pretty 
>major improvements to the audio system. OpenShot is moving in a 
>direction to provide more functionality with audio processing and 
>we're anxiously waiting for the upgrades. In the meantime, using a 
>free audio editor <https://www.audacityteam.org/>such as Audacity to 
>import your clips and export the audio as WAV files should help 
>clear up audio issues within OpenShot projects.

Thanks for the suggestions. After the WMA fiasco, I started using 
Audacity to produce the audio in WAV format; MUCH better than 
Windows' Sound Recorder and Sound Editor. My video clips are all 
MP4's produced by SnagIt (a screen capture pgm).

There are still major issue's with OpenShot's playback of video 
files; I sure hope they get that fixed in the next release. I tried 
one of the daily builds, but it just crashed.
