### ISSUE TITLE
Weird artifacts displayed on the right edge when using 4:3 video

### ISSUE THREAD

**Issue by DanPinGF** [OpenShot/openshot-qt#3915]
**Describe the bug:**
When using certain 4:3 videos in the timeline, weird and unusual artifacts are clearly on the right edge of the video. This is a recurring issue.

**Steps to reproduce the behavior:**
Use the 'Crop' effect to remove the artifacts on the right.

**Expected behavior:**
Normally the artifacts are not present in videos in all other aspect ratios.

**System Details:**
- OpenShot Version: 2.5.1
- Operating System / Distro: Windows 10 October 2020 Update

**Comment by ferdnyc** [comment]
@DanPinGF Most likely this isn't a consequence of 4:3 aspect video, exactly, but rather of video with an "odd" width. Some codecs expect video frame width to be a certain multiple of some value (2, 4, 8...). 

So if you have a video that's, say, `630px` wide, you'll get "noise" because it's being rendered at `632px` wide (a multiple of 8). But if the video was `640x480` (a 4:3 aspect resolution), it would render cleanly.

It's definitely a bug, no question, but for now the simplest workaround, as you found, is to crop off the extra width.

**Comment by DanPinGF** [comment]
@ferdnyc - Yup, and the noise can also be processed in the exported video, which is another thing you guys need to take care of.
