### ISSUE TITLE
Display / Show Waveform for audio clips does not persist

### ISSUE THREAD

**Issue by OpenShooter** [OpenShot/openshot-qt#3932]
OpenShot 2.5.1, Windows 7 64-bit

For audio clips, the Display / Show Waveform option selected in the context menu does not persist; this choice restored after a project is closed and reopened.

**Comment by stevekeiretsu** [comment]
Hello,

I recently discovered this software, and I love it, but this bug is kind of irritating.  (Really, the fact this is the most irritating thing I've found so far is a pretty huge compliment.)

I'm going to donate in a no-strings-attached kind of way, anyway, but just out of interest, is there any interest in sticking (modest) 'bounties' on issues?

**Comment by Colorjet3** [comment]
This has been fixed in v3.0.0
