### ISSUE TITLE
No audio on Video Preview

### ISSUE THREAD

**Issue by bryan610** [OpenShot/openshot-qt#3933]
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/5718700/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/5718701/openshot-qt.log)

Open a project
play video 
no audio is playing

Even if I change the preferences on the preview tab to a different Playback Audio Device, it still doesn't work.

Yes I can hear youtube videos and other audio on my machine.

**Comment by Vichu2005g** [comment]
I am encountering the same problem

**Comment by KADA23** [comment]
Hello, I have the same problem but Open shot cut the sound of my computer. 
(Its coming back when I uninstall it)

**Comment by USATechDude** [comment]
I know how cliché it is for a support person to say, "It's not our software," and hearing that can be downright maddening. But we have not modified OpenShot 2.5.1 (stable) since March 3, 2020. We've recently received a large number of requests for support regarding sound issues. Most people found resolution by updating their Windows 10 system to version **10.0.19042** (your `openshot-qt.log` shows that you are running Windows 10 version **10.0.17763**).

I had similar issues with my Windows 10 system. I updated the [October 2020 (20H2) Update](https://www.microsoft.com/en-us/software-download/windows10) and then updated my system with the [November 2020 Cumulative Update](https://support.microsoft.com/en-us/help/4586853/windows-10-update-kb4586853) and the [November 2020 Cumulative Update Preview](https://support.microsoft.com/en-us/help/4592438/windows-10-update-kb4592438).

After updating Windows 10, I downloaded a [free driver update tool](https://www.google.com/search?client=firefox-b-1-d&q=free+driver+update+tool) to check my system device drivers. I was surprised when the tool told me that 27 drivers needed to be updated on my system.

More options that may help:
- Download and install the [latest Daily Build](https://www.openshot.org/download/#daily) from our web server
- Uninstall OpenShot, delete the `C:\Users\(USERNAME)\.openshot_qt` folder, then reinstall OpenShot
- Download and install [PortableApps.com](https://www.portableapps.com/) and then download and run OpenShot 2.5.1 through their app
- Test the sound issue with a virtual machine. Both [VirtualBox](https://www.virtualbox.org/) and [VMware Workstation Player](https://www.vmware.com/products/workstation-player/workstation-player-evaluation.html) are free for personal use, and you can set up a fresh install of Windows 10 and see if the sound works in the virtual machine.
- If you use OpenShot intensively, you can set up a dual boot system and run Linux in a separate partition. OpenShot is developed primarily on Ubuntu and Fedora.
