### ISSUE TITLE
Browse for Inkscape and Blender binaries not working in macOS, Windows, and ChromeOS

### ISSUE THREAD

**Issue by USATechDude** [OpenShot/openshot-qt#3943]
This issue was reported in our [Reddit Community](https://www.reddit.com/r/OpenShot/comments/kl3lnk/no_file_type_appears_in_browse_to_link_inkscape/) on 28 December 2020.

**Describe the bug:**
When using the "Español de España (es)" language or a system that defaults to the "Español de España" language settings, OpenShot cannot locate the binary files for Inkscape or Blender in Windows, macOS, or ChromeOS.  The dialog box to locate the files opens, but files do not appear in the windows, only folders.

**Steps to reproduce the behavior:**
1. Launch OpenShot v2.5.1 or v2.5.1-dev2 on Windows, macOS, or ChromeOS
2. Open the Preferences window
3. Change the Language setting to **Español de España (es)**.
4. Close the Preferences window
5. Close OpenShot
6. Relaunch OpenShot
7. Open the Preferences window
8. Click either of the **Examinar...** buttons
9. Attempt to locate either the Inkscape or Blender binary files
    - In Windows, folders are visible, but no files appear
    - In macOS, folders and applications are visible, but all applications are grayed out and cannot be selected
    - In ChromeOS, folders are visible, but no files appear

**Expected behavior:**
In every language, the user should locate the binary files for Inkscape and Blender using the "Select executable file" dialog box.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: v2.5.1 (Windows, macOS, ChromeOS)
- OpenShot Version [e.g. 2.4.3]: v2.5.1-dev2 [6268] (Windows)
- OpenShot Version [e.g. 2.4.3]: v2.5.1-dev2 [6028] (macOS)
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]: Microsoft Windows [Version 10.0.19042.685]
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]: macOS Big Sur Version 11.0.1
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]: CloudReady 85.4.0 (Home Build) stable-channel

**Log Files:**
None

**Exception / Stacktrace:**
None

**Screenshots:** (Optional)
![Screenshot01](https://user-images.githubusercontent.com/65924242/103374959-739eb080-4a9e-11eb-9d27-6a78e656b51c.png)

**Comment by USATechDude** [comment]
A workaround to this issue is changing the Language setting in Preferences to **American English (en_US)**, relaunching OpenShot, locating the binary files, then changing the language back to Default, and relaunching OpenShot.

**Comment by ferdnyc** [comment]
Mm, that happens because the `OpenShot_es.qm` translation file contains this translation:
**Source string:** `All files (*)`
**Localized string:** `Todos los Archivos`

Unfortunately, the `(*)` controls how filename matching is configured for the dialog, so if it's left out the filename match is set the same as the description — in this case, "Todos los Archivos". Meaning, ony files with that name would show up in the dialog.

If there are other matching options in the combination box to the right of the filename field, changing what's selected there would probably be a workaround. But I suspect there won't be any other options, because we  haven't provided any. Unless maybe there's a default "All files" that's always added, perhaps. (In which case, we shouldn't be supplying that value _at all_, because the default will surely be localized already.)

The immediate fix is to correct the Spanish translation to `Todos los Archivos (*)`; longer-term, we should figure out whether we really need that to be a translated string.

**Comment by ferdnyc** [comment]
> Unless maybe there's a default "All files" that's always added, perhaps. (In which case, we shouldn't be supplying that value _at all_, because the default will surely be localized already.)

I don't know about it being automatically added, but sure enough the `qtbase_*.qm` files (the built-in Qt translations for the base modules) already contain translations for both `All files (*)` and `All Files (*)` in the QFileDialog context, so we should really be using those instead of translating the string ourselves.

#### Side note
(Interestingly enough, the Spanish translations for `All files (*)` and `All Files (*)` are _different_: `Todos los archivos (*)` vs. `Todos los ficheros (*)`, respectively. ...I'm not fluent enough in Spanish to know whether that makes sense or not, and why it would be the case.)

**Comment by ferdnyc** [comment]
> The immediate fix is to correct the Spanish translation to `Todos los Archivos (*)`; longer-term, we should figure out whether we really need that to be a translated string.

Actually, I determined that we definitely don't. So, #3947 will just remove the filter string from the dialog entirely, ensuring that it can't be mistranslated.
