### ISSUE TITLE
jump between keyframes

### ISSUE THREAD

**Issue by yosik50** [OpenShot/openshot-qt#3946]
**Describe the new feature:**
A keyboard shortcut to jump between keyframes

**Describe the solution you'd like:**
The ability to got next/previous keyframe of a property

**Describe alternatives you have considered:**
The only way to precisely be on a keyframe is to go frame by frame

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your request.

**Comment by USATechDude** [comment]
This feature already exists in the Daily Builds.  Use CTRL+Arrow Keys to jump between the markers and/or key frames.  You can download the latest Daily Build here:
https://www.openshot.org/download/#daily

**Comment by yosik50** [comment]
TY

**Comment by yosik50** [comment]
BTW, is the main download button pointing to the latest daily build?

TY

**Comment by ferdnyc** [comment]
@yosik50 No, the Download button always points to release versions. To download one of the Daily Builds you should select a file from the list on the left. (The newest are at the top.)

Arguably the Download button should be hidden, or otherwise de-emphasized, when displaying the list of Daily Build downloads. I can see how the current layout could be confusing.

**Comment by yosik50** [comment]
OK. TY
