### ISSUE TITLE
Blender 2.78 No Frame error

### ISSUE THREAD

**Issue by dante4478** [OpenShot/openshot-qt#396]
Hey guys, I'm new to openshot and I was trying to get Blender working with it but every time I try I get the "no frame was found in the output from blender" error. I am running on Windows 7. You guys get any ideas?

**Comment by mixedbredie** [comment]
I get the same error with Blender 2.78 and Inkscape 0.91 installed on Windows 7 64bit.  Have you got the paths to the Blender and Inkscape executables set in Preferences?
C:\Program Files\Blender Foundation\Blender\blender.exe
C:\Program Files\Inkscape\inkscape.exe

**Comment by dante4478** [comment]
Yep I have that setup properly. At this point though, I just learned how to
Blender to custom make all my intros. But if someone does have a solution,
it would be great to know.

**Comment by mixedbredie** [comment]
If I run the Blender files included with OpenShot from the command line and include the blend file and python script I get some more information back about where the error is.

    path/to/blender.exe -b path/to/file.blend -P path/to/python/script.py

Error is 'TextCurve' object has no attribute 'align'. Checking the Blender API docs (https://www.blender.org/api/blender_python_api_2_78a_release/bpy.types.TextCurve.html#bpy.types.TextCurve) you can see that it should be 'align_x' in the python script (I used the blur.py file as an example). If I make the change and save the file then run the Blur animated title from OpenShot, it works and Blender runs in the background generating the title (still crunching as I type).

So, I guess the problem here is the Blender devs updating their code and the OpenShot devs having to play catchup and make sure all the changes are propagated through all the files.  There may be more changes than just the 'align' to 'align_x'.

**Comment by janagyjr** [comment]
There may be, I saw the issue opened in #379 and tried your solution there. Did not work. Waiting on solution.

**Comment by jonoomph** [comment]
Please test again with the latest daily build of OpenShot. I've merged in changes to the text alignment, and updated the minimum version compatibility to 2.78. I've tested all animation on Linux, Mac, and Windows with Blender 2.78 and everything works great.

Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. _It might take a couple hours for the latest version to appear._

If you have other issues, please file additional bugs for each one. Thanks!
