### ISSUE TITLE
No titles_templates directory

### ISSUE THREAD

**Issue by gimpox** [OpenShot/openshot-qt#3961]
I have installed OpenShot just three days ago (Version 2.5.1 Linux).
There is no _.openshot_qt/title_templates/_ folder in my home directory, just the _title/_ folder. If I try to put an svg template there then it will be wiped out every time OpenShot starts.

I tried to manually create the _title_templates_ folder in _.openshot_qt/_ , and put my template there, but it is ignored by OpenShot.

**Comment by USATechDude** [comment]
OpenShot v2.5.1 does not use the `title_templates` folder, it was added later in the Daily Builds.  If you download and install the [latest Daily Build](https://www.openshot.org/download/#daily) you can use the `title_templates` folder as you intend.

**Comment by gimpox** [comment]
A similar bug was declared solved on July 2020 (see issue #3587). I have downloaded the appimage yesterday.
Are you sure that downloading the latest version will solve the problem?
(Should I delete the folder _.openshot_qt/_ before running the updated version of OpenShot?)

**Comment by USATechDude** [comment]
@gimpox 

> Are you sure that downloading the latest version will solve the problem?

No, I am not absolutely certain that using the latest Daily Build will resolve your issue. I do feel confident enough to recommend that you try.  If the Daily Build doesn't work out, you can always revert to the stable version.  Since you are using the AppImages, there isn't much risk to your operating system.  You just need the time to download and test.

> (Should I delete the folder .openshot_qt/ before running the updated version of OpenShot?)

Yes, I think that is a good idea since some settings carry over between the versions and (in rare circumstances) cause issues.
