### ISSUE TITLE
Keyframes on the first frame change after the first frame

### ISSUE THREAD

**Issue by Smiley-Riley** [OpenShot/openshot-qt#3966]
**Describe the bug**
When I try to add a keyframe to the first frame (e.g video comes in at 4:29) (I'll find this using ctrl back arrow) to set the values to something like scale x = 0.5  it'll say the keyframe is on the first frame, but when i play the video it has a little jitter as scale x goes from 0.51 at 4:29 to 0.5 at 4:30, At no point did have I set the keyframe to be 0.51 but it does for the first frame and I have no idea why

**System Details (please complete the following information):**
Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
Linux Ubuntu 19.04 OpenShot Version [e.g. 2.4.1]
2.5.1

**To Reproduce**
**Steps to reproduce the behavior:**
Add a video clip to timeline.
Slice off the beginning.
Change property of scale x on the first frame of the video

**Expected behavior**
There will be a little jitter as the scale changes from a different value that it should be to it's proper value from one hundredth of a second to the next

**Comment by ferdnyc** [comment]
@Smiley-Riley 

Hmmm. I don't doubt your experience, but I'm not immediately able to reproduce.

However, setting keyframes on sliced clips does have the _potential_ to behave weirdly, in theory, because the keyframes that previously existed in the "un-sliced" portion of the clip are still present, meaning that when you set a keyframe even on the first frame you're really adding a second keyframe (at least, the first one being at the original first frame), so therefore you're getting an interpolated value.

What sort of interpolation is your Scale_X = 0.5` keyframe using? If it's Bezier (curvy icon) or Linear (sloped icon), switching it to Constant (horizontal-line icon) might clear up the jitter, if it is indeed due to interpolation.

The other thing you could do, and this is more of a workaround, would be to set the Scale_X on the **real** first frame of the clip, before you slice it. That way it'll hold constant for the entire clip, guaranteed. That's a pain in the neck, I admit, but if it helps it would at least tell us where the values are coming from. (But as I said, I wasn't able to reproduce this so far, with either 2.5.1 or the latest development code.)

**Comment by ferdnyc** [comment]
I was just thinking about why you might be seeing this while I'm not, and I realized another possibility is that it only happens when there's a frame rate mismatch between the Timeline (the project configuration) and the Clip (the source video).

If you're dropping, say, a 24 fps video into a 30 fps Timeline, then a slice can be done at any of the Timeline frames (so, 30 positions per second), but many of those _won't_ be frame boundaries in the source clip. So, it could be that the Clip's "first frame" really starts inside the tail end of a previous frame, and therefore the keyframe parameter is starting off with the value from that previous frame, before the value you set is assigned once it hits the next frame boundary.

I'll try and experiment some with that kind of thing, see if I can confirm that theory. But, just for curiosity's sake, can you please let us know the frame rates of:
1. The file you're importing (visible by right-clicking on the Project Files item and selecting "Details...")
2. The project Timeline (visible in the OpenShot window title, or by opening the "Choose Profile"  dialog)

Thanks.

**Comment by ferdnyc** [comment]
> 1. The file you're importing (visible by right-clicking on the Project Files item and selecting "Details...")

Or even selecting "File Properties", when I'm remembering how things are actually named.

**Comment by fcjreed** [comment]
I believe you're on track with the fps matching. I recorded an initial video with 60 fps running on a 29.97 fps profile and it was changing throughout the entire clip. I then recorded another video at 29.97 fps and ran that on the 29.97 fps profile and had no issue.

**Comment by fcjreed** [comment]
This also might be a side effect but sometimes the scaling doesn't occur during live preview as well. If I pause the preview add a new keyframe and marker to workaround the issue and then hit play, the scaling doesn't show. However, if I move back to the marker with the new keyframe, it does show the scaling. So it can be misleading. Sorry if it's unrelated.

**Comment by Smiley-Riley** [comment]
@ferdnyc 

> I was just thinking about why you might be seeing this while I'm not, and I realized another possibility is that it only happens when there's a frame rate mismatch between the Timeline (the project configuration) and the Clip (the source video).

The profile in openshot is 1080p at 29.97fps and the source video(s) are shot at the same rate (29.97fps) So I don' think that would be the case

>What sort of interpolation is your Scale_X = 0.5` keyframe using? If it's Bezier (curvy icon) or Linear (sloped icon), switching it to Constant (horizontal-line icon) might clear up the jitter, if it is indeed due to interpolation.

This one's weird but setting it to constant somehow makes it worse in the sense that in linear it jitters a tiny bit (x = 0.51 to 0.5) but in constant it goes from the full x value (x = 1) to 0.5 between the frames

I will try your fix of setting the keyframe before the cut and report back whether it works or not.
Thanks for your time!
