### ISSUE TITLE
Keyframes need work to really finish this brilliant video editor

### ISSUE THREAD

**Issue by nigel-aves** [OpenShot/openshot-qt#3975]
This issue has been raised before,Issue #689, but it was closed out, which I think was wrong.

I've only been using Openshot-qt for a day now, and once you get used to the way the interface works its a brilliant design, not overly complex, but you are able to do a lot of good editing in it. Except when it comes to keyframes, and they let things down.

1/ I can find no way to move a keyframe.  You should just be able to select it and then drag to where you need it.

2/ Can find no easy way to delete a keyframe. You should just be able to select it and hit the delete key.

3/ This might be a bug. I found Copy >> keyframe >> list of options. I select All on a clip that had one user defined keyframe. But I have not been able to paste it. Nothing happens.

It should be possible to, select keyframe and then paste it where you need it.

In the #689 someone mentioned that Adobe use a separate "space" with the clip, displaying the keyframes. I use Vegas Video and that does exactly the same thing. Which makes using keyframes a lot simpler and easier.

![image](https://user-images.githubusercontent.com/33691546/105435513-b75a8500-5c1a-11eb-9359-92ebed87a206.png)

**Comment by rexdk** [comment]
Yes, you can't move a keyframe - which I agree would be very welcome.

You can delete a keyframe by right cliicking the property and choosing 'remove keyframe'.

Copy keyframes works for me. It only copies the clip properties keyframes, not effect/transition keyframes, so 'all' is misleading.
From https://www.drking.org.uk/osg/clip_presets_menu.html:
"For keyframes, Paste will appear when you right click on another clip. If selected, the copied keyframes will be pasted."

Keyframes have recently been made more visible, bigger and extending lower (in the experimental daily builds)

**Comment by jjhaggar** [comment]
I think this feature proposal is still relevant. Moving and deleting keyframes are the only features that I really miss on this otherwise great software. Copying and pasting keyframes would also be nice, but they are probably not so vital.
Would be possible to add these features in the future? (move/delete/maybe copy&paste) Could we maybe reopen this issue? I haven't found any other open issue that adresses this (issue #689 does it but it's also closed due to inactvity).

**Comment by Colorjet3** [comment]
v3.4.0-Release-Candidate has the feature where it allows you to adjust the keyframes (move them left/right).  However, the Delete option is not there yet.

Copying keyframes, at least most of them, has been there for sometime now and more enhancements in v3.4.0-Release-Candidate.  The way this works is:

1. Drag 2 emojis onto a Track. 
2. Make changes to the first clip by adding Effects and some animation.
3. To Copy the Effect(s) and/or animation (other keyframes), right click the first clip, Highlight Copy and note the Effects and Keyframes options.
4. Select Effects.
5. Now select the 2nd clip, right click on it and Paste or CTRL+V.
6. You have the same option with the Keyframes.

Further Enhancements in the future will be:
1.  The ability to select which Effects you want to copy.  At this time it is all or nothing.  Obviously it is easy to delete an Effect from the 2nd clip.
2.  For Effects, it would be nice to have the ability to select which keyframe(s) you want to copy instead of individual or All.  For example, if I have animated the Location, Shear, and Scale, but I don't want to copy them all but only Location and Scale.  This enhancement would allow me to select Location and Shear only.

V3.4.0-Release-Candidate can be found at openshot.org/download/#daily.  It is going through testing right now and a few bugs have been found that the lead developer is working on fixing before it is ready for production release.
