### ISSUE TITLE
Cracking noise when exporting to mp4 

### ISSUE THREAD

**Issue by Lotusallen** [OpenShot/openshot-qt#3980]
Basically I am editing myself speaking on a video and taking out sections and joining several clips of this video together.  When I play it in the program it is fine but when exported there is a cracking noise briefly on each cut. I have tried changing each clips audio to 40 % but it made no difference. I am using v2. 5.1

**Comment by rexdk** [comment]
If you haven't softened the audio transitions between clips you might well get some noise - with any programme. Although Openshot is not the best at handling this sort of thing.

My advice would be to fade each clip's volume in and out - probably adding the keyframes manually. Quite a palaver though if there are a lot of them.

Another option would be to export with the crackles, edit in Audacity to remove them, and then re-edit the video using the new single sound track

Hope that helps

**Comment by Bill-ColeUS** [comment]
I wanted to merge 20 videos together to make a single video without "gaps" between the videos. Having read that OpenShot is a great program, I decided to do it all there. Once exported, 15 out of the 20 merged videos have cracking noises around the point of their merge.

A total and complete let down by OpenShot, since it can't do the most basic thing, merge some videos together. 

Off to find a decide piece of software and avoid this piece of garbage...

**Comment by Lotusallen** [comment]
I had a similar problem.  I gave up and tried flowblade which works.  I did my editing on this and it was fine. I also tried shotcut which appears to work as well. Unfortunately I just had to give up on OpenShot.
