### ISSUE TITLE
Openshot 2.1+

### ISSUE THREAD

**Issue by ShadowenTheGrey** [OpenShot/openshot-qt#399]
To add new transitions/masks the documentation seems to suggest using import mask/transition, but this menu is missing, in both the windows (2.1.0) and linux (2.1.0) version of openshot..   But  is present in the1.4.3 version.

From the only documentation I am able to find

           "To add a custom transition or mask, select File > Import New Transition"

If it's been moved, it should be made more obvious as to where.

**Comment by jnmacias** [comment]
True, I was having the same issue but luckly you can import the transitions to C:\Users\[Your User]\.openshot_qt\transitions in windows or /home/[User]/.openshot/transitions on linux.

I still can't make masks. When I add the transition and right click on it the "type" property is missing. I'm thinking in download an old version on openshot because my project relies strongly on masks. 

I hope eventualy they add the option again.

**Comment by jreynojustin** [comment]
OpenShot is now in Version 2.2 if you are still noticing issues in the latest version please re-open this issue letting us know.
