### ISSUE TITLE
OpenShot

### ISSUE THREAD

**Issue by FawkeyGuy** [OpenShot/openshot-qt#3996]
**Describe the bug:**
Ich schreibe auf Deutsch.
Ich habe bisher nochnicht mit OpenShot (kurz: OS) gearbeitet, kenne jedoch Premiere Elements recht gut.
Bei OS sind mir bisher folgende Fehler bzw. fehlende Funktionen aufgefallen:
- Es gibt keine Titelzeile wie allgemein üblich und damit auch nicht die Schaltflächen Minimieren, Verkleinern und Beenden
- Der Ton eines Videos ist nicht bearbeitbar, sondern kann lediglich angezeigt werden (was sehr lange dauert)
- Eigene Schnittprofile bzw. Assets sind schwer bis gar nicht erstellbar
- Dei Funktionen Ein- und Ausblenden lassen sich nicht konfigurieren (Bezierkurve usw.)
- Es fehlen Bildmasken u.Ä., mit denen sich z.B. Teile des Bildes kaschieren lassen
- Die Anzeige der Eigenschaften bringt das Programm oft zum Einfrieren
- OS hängt sich gelegentlich während des Starts auf und gelegentlich auch während der Arbeit
- Das Programm braucht exrem lange, um ein bestehendes Projekt zu laden, sofern es nicht vorher abstürzt
- Abgeschlossene Projekte behalten eine Löschsperre und werden nur sehr zögernd freigegeben (manchmal erst nach mehreren Neustarts)
- Die optische Abgrenzung der einzelnen Fenster ist kaum sichtbar: alles wird hellgrau dargestellt
- Das Programm blockiert Scrollen auf der Zeitleiste bzw. benötigt erschreckend viel Zeit dafür, wenn es doch einmal klappt
- Die Funktion 'Kopieren' wird angeboten, die dazugehörigen Funktionen 'Ausschneiden' und 'Einfügen' bzw. 'Löschen' jedoch nicht
- Einzelbildschaltung ist nicht möglich

**Steps to reproduce the behavior:**

**Expected behavior:**

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]
2.5.1
**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by moreaki** [comment]
This is an annotated and "Deepl" assisted translation:

> I write in German.
> I have not yet worked with OpenShot (OS for short), but I know Premiere Elements quite well.
> With OS, I have noticed the following errors or missing functions so far:

1. There is no title bar as usual and therefore no Minimize, Zoom Out and Exit buttons.
2. The sound of a video is not editable, but can only be displayed (which takes a long time)
3. Own editing profiles or assets are difficult or even impossible to create
4. The fade in and fade out functions cannot be configured (Bezier curve etc.)
5. Image masks etc. are missing, with which e.g. parts of the image can be concealed
6. The display of properties often causes the program to freeze
7. OS hangs occasionally during startup and occasionally also during work
8. The program takes an extremely long time to load an existing project, unless it crashes first
9. Completed projects keep a delete lock and are released only very hesitantly (sometimes only after several restarts)
10. The visual delimitation of the individual windows is hardly visible: everything is displayed in light gray
11. The program blocks scrolling on the timeline or takes an alarming amount of time to do so, if it works after all
12. The function 'Copy' is offered, but the corresponding functions 'Cut' and 'Paste' or 'Delete' are not available
13. Single image switching is not possible

This is a first attempt at dissecting this wealth of information, so it might be more useful for the developers to tackle the raised concerns:

1. Since it's unclear which Operating System (which normally is OS) you are using and since you also do not provide a screenshot, it's hard to gauge the extent of your claim towards a bug. On my Apple macOS OpenShot I do have those buttons and functionalities: 
<img width="910" alt="image" src="https://user-images.githubusercontent.com/1086603/107344753-19dccd80-6ac3-11eb-806b-396e7255d440.png">
2. Can you be more specific what you expect? This is a video editor, which has the following audio features:
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/1086603/107345502-ea7a9080-6ac3-11eb-8089-354d5770ddc1.png">
3. Can you elaborate if it's just difficult (maybe due to the lack of experience or documentation) or impossible?
4. Would this help? [https://cdn.openshot.org/static/files/user-guide/animation.html#bezier-presets](https://cdn.openshot.org/static/files/user-guide/animation.html#bezier-presets)
5. Do you mean something like this: [https://www.youtube.com/watch?v=RAUbbkd4wBE](https://www.youtube.com/watch?v=RAUbbkd4wBE)
6. Can you please provide steps to reproduce this?
7. Can you please provide steps to reproduce this and your hardware/operating system/configuration information, along with logs?
8. If it crashes, attach the log files. If it takes a long time (which I cannot reproduce), try to be more specific
9. I have quickly browsed through the source code that deals with project related operations, and didn't immediately find any delete lock. Care to explain or provide some steps to reproduce this behaviour? 
10. The theming definitely lacks in UX aspects found in other tools. Do you have constructive suggestions?
11. The more I read about your input, the more I feel that your system is really slow. But you're absolutely correct, the scrolling needs major improvement. I run this on a MBP 2020 with 64GB RAM and 8TB SSD and the thing is laggy as hell when scrolling. Not so with other video editing tools on macOS.
12. Very confusing input, since they clearly are there: 
<img width="165" alt="image" src="https://user-images.githubusercontent.com/1086603/107355521-dd639e80-6acf-11eb-88ae-5d70f941e3f8.png">
13. This I do not understand.

I'm afraid that unless you provide more information, your input is not helping much so far.
