### ISSUE TITLE
Running terminal command after exporting

### ISSUE THREAD

**Issue by MatteoGheza** [OpenShot/openshot-qt#4011]
**Describe the new feature:**
Running a custom terminal command after video exporting (ex. for uploading video via ftp, sending a notify, shutting down the computer,...)

**Describe the solution you'd like:**
A text boxt in the "advanced" section for running custom terminal commands

**Describe alternatives you have considered:**
- Using only OpenShot Cloud (almost impossible)
- Using a custom python script for pressing gui buttons (very difficult for beginners)

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your request.

**Comment by MatteoGheza** [comment]
OpenShot is full of bugs and unresolved issues and feature requests.
Now I'm using Olive Video Editor, since it's much better!

**Comment by JacksonRG** [comment]
@MatteoGheza I'm sorry this enhancement didn't get more attention. It's a nice idea, but we devs only have so much time, and must prioritize what improvements will have the greatest impact on the editor.

We are nearing a new stable release, which will include countless bug fixes and improvements that have been made since our last release, and I encourage you to try out the daily build until then. And either way, I'm glad you've found an editor that fits your needs. If you no longer want to see this enhancement made to openshot, I can close the issue for you

**Comment by MatteoGheza** [comment]
@JacksonRG I'm sorry, it was just a provocation.
I just wanted to see if the reports were read by someone.
To be honest, I still prefer to use OpenShot.
Olive is really fast, but it's difficult to use and it's currently unstable (for example, I had to run a video render 4 times because it crashed).
The nodes editor (used by Olive) isn't very beginner-friendly, and OpenShot has more features than Oive, for example dozens of different effects and transitions.

I am still interested in using OpenShot and I understand that bug fixing in such large projects takes a lot of time.

**Comment by MatteoGheza** [comment]
Thanks for your work developing OpenShot!
I hope that a new version will be released soon, since OpenCV features are awesome!
In the next week, I'll try to implement this feature.
