### ISSUE TITLE
Import image as sequence ignore most of the images

### ISSUE THREAD

**Issue by rexdk** [OpenShot/openshot-qt#4032]
This is simply reporting the bug reported in #3585, which was closed by the stalebot

The bug is unresolved.

Openshot is sadly riddled with bugs, and there are not enough people to deal with them. I have found a great many bugs, but as the stalebot closes bugs irrespective of whether they have been solved or not, I have given up reporting them. The bugs are a real usability issue for me.

I'm very grateful for the time people put into this project, and I have created some good videos - for free.

**Comment by Ramon-1** [comment]
This issue it's a true annoying failure. Yesterday i've delete logs and downloaded  and instaled daily compilation and the issue were gone.

**Comment by discgolfer5000** [comment]
This issue happens to me also with OpenShot versions 2.5.1 and 2.6.0 on Windows 10. I've done complete uninstalls and manual file removals.

The last 8 frames are static in the OpenShot preview, scrubbing frame by frame, and in the exported video, but not in the source clip or frames.

It happens whether I import my source clip as an mp4, mkv, or a png image sequence of 120 frames.

I tried a different free and open source video editor and the same clips/frames worked fine there, so the issue is within OpenShot.

Issues #2435, #2609, #3585, #4032 all appear to be the same, some of which have auto-closed while unresolved.

**Comment by ingus-t** [comment]
This bug is still happening on Openshot 2.6.1 [stable], on Windows 10.
I tried the latest daily build as well: OpenShot-v2.6.1-dev-daily-9246-f29ce408-2b8b05c7-x86_64.exe

In my case, I have 8 images labeled 001.png, 002.png, 0.03.png ... Last 3 images are not loaded in the sequence.
I tried renaming all the images to a1.png, a2.png, etc. No change, the last 3 images were not loaded.

I'm adding a download link to 3 test cases:
t1_1_5_w_6_8_dw - test case 1, images 1-5 are loaded, the rest are not 
t2_1_6_w_7_9_dw - test case 2, images 1-6 are loaded, the rest are not (Note - image 6 is a copy of 4. I copy/pasted it, and then renamed, and that made it load.)
t3_1_2_w_3_8_dw - test case 3, images 1-2 are loaded, the rest are not. Note:

1. this folder was a copy/paste from test case No 1. Initially, images 1 to 5 loaded successfully.
2. I renamed images 6 to 8, adding a letter in the end.
3. After that, only images 001.png and 002.png load successfully.

After the import, I checked which images were loaded successfully by going forward 1 frame at a time.

Another issue, that could be related:
I'm not getting the second popup when I import a sequence. I mean the second pop up from here:
https://www.openshot.org/blog/2011/01/19/image-sequence-magic-auto-detection/
Most of the time, this second popup is not appearing, but it did appear when I started working on my project.

After I've dragged the image sequence onto a track, doing right click --> properties does nothing. I can't access sequence properties.

I hope this is helpful.
[test_cases.zip](https://github.com/OpenShot/openshot-qt/files/8239822/test_cases.zip)
