### ISSUE TITLE
I have some files wich i can't remove from my hardrive after have modified it with openshot with release and preview version

### ISSUE THREAD

**Issue by axalox** [OpenShot/openshot-qt#4033]
**Describe the bug:**

I have some files wich i can't remove from my hardrive after have modified it with openshot with release and preview version

**System Details:**
- Operating System Windows 10

**Log Files:**
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/6057843/libopenshot.log)

[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/6057844/openshot-qt.log)

**Screenshots:** (Optional)

![image](https://user-images.githubusercontent.com/32990916/109431493-38b9ea00-7a07-11eb-8bb0-006f161f05c8.png)

![image](https://user-images.githubusercontent.com/32990916/109431540-70289680-7a07-11eb-9dd4-3a85aff3b626.png)

2 files wich can't be opened or deleted ?

**Comment by rexdk** [comment]
If you close Openshot the problem should resolve. Openshot behaves very strangely with files, unlike other programmes, but I think the behaviour is by design.

**Comment by axalox** [comment]
Hello it's me again ;)

I have again the same problem, but for the name i have put a smiley like this `:)` at the end of the file name.
Maybe this is the problem ?

Openshot doesn't say anything, but the ghosts files don't have the smiley.

**Comment by rexdk** [comment]
Windows doesn't like a file name including a colon ':'  
I don't know how Openshot tries to handle that - normally you'd just get an error message until the file name was valid, but maybe not here.

**Comment by axalox** [comment]
Hello again

No I didn't get any error message for the name of the file.
I don't understand why i can't remove theses files now ?

**Comment by ferdnyc** [comment]
> Does Openshot does something for protect files when it work on it ?

It doesn't, no. (Not once you exit the program, anyway. It does prevent deleting files it has open _while_ it's running, sometimes.)

Turns out, it just creates broken files that confuse Windows, under these circumstances.

I tried to re-create your test, first by trying to save my project file as `My Smiley file, see :).osp`. Because we use the Windows file-save dialog to do that, I was correctly prevented from using that name. With a nice error message telling me why, even:

![Screenshot from 2021-03-04 22-12-38](https://user-images.githubusercontent.com/538020/110062695-c105fb00-7d37-11eb-9978-da3216fb97a0.png)

But then I went into Export, where we _don't_ use the standard Windows save dialog, for Reasons™. (Bad reasons. Totally wrong reasons.)

Because we don't use the save dialog, Export was happy to let me name my export file `My smiley file, see :).mp4`, and it went full steam ahead with exporting to that name.

Because the name is invalid, what was _actually_ created on disk was a file named `My smiley file, see ` (Complete with a space at the end, because it got cut off at the colon), which Windows is now completely unable to delete because it won't even admit the file exists.

![image](https://user-images.githubusercontent.com/538020/110063078-7b95fd80-7d38-11eb-9567-2dbf671b90a1.png)


```dos
C:\Users\ferd\Documents>dir
 Volume in drive C has no label.
 Volume Serial Number is 787D-9E57

 Directory of C:\Users\DP\Documents

03/04/2021  10:14 PM    <DIR>          .
03/04/2021  10:14 PM    <DIR>          ..
11/19/2020  10:21 AM               641 .vsconfig
11/19/2020  12:51 PM    <DIR>          gammaray-2.11.2
01/05/2021  08:13 AM    <DIR>          GitHub
03/04/2021  10:13 PM                 0 My Smiley File, see
03/04/2021  10:14 PM            26,780 My Smiley Project.osp
03/04/2021  10:14 PM    <DIR>          My Smiley Project_assets
02/25/2021  08:27 AM    <DIR>          PowerShell
12/01/2020  06:13 AM    <DIR>          Qt Creator
11/10/2020  06:31 AM             1,463 teevey-Win10vm.ppk
11/10/2020  06:31 AM               480 teevey-Win10vm.pub
12/01/2020  06:02 AM    <DIR>          Visual Studio 2019
09/23/2020  06:13 PM    <DIR>          WindowsPowerShell
               5 File(s)         29,364 bytes
               9 Dir(s)  11,227,492,352 bytes free

C:\Users\DP\Documents>del "My Smiley File, see "
Could Not Find C:\Users\DP\Documents\My Smiley File, see
```

The export also didn't _write_ anything into that file — as you can see, it has a size of 0 bytes; it's completely empty.

Here's what you _can_ do, @axalox, to delete those files. (And, let me be clear, this is _crazy_ and should not be necessary.)

1. Open up a Command Prompt window
2. `cd` to the directory where those files are stored
3. use `dir /x` to display the list of files _with_ their short names
4. Use the _short_ filename to delete the file in question (using `del`)

For example, my undeletable file has a short name of `MYSMIL~1`:
```
dos
C:\Users\DP\Documents>dir /x
 Volume in drive C has no label.
 Volume Serial Number is 787D-9E57

 Directory of C:\Users\DP\Documents

03/04/2021  10:14 PM    <DIR>                       .
03/04/2021  10:14 PM    <DIR>                       ..
11/19/2020  10:21 AM               641 VSCONF~1     .vsconfig
11/19/2020  12:51 PM    <DIR>          GAMMAR~1.2   gammaray-2.11.2
01/05/2021  08:13 AM    <DIR>                       GitHub
03/04/2021  10:13 PM                 0 MYSMIL~1     My Smiley File, see
03/04/2021  10:14 PM            26,780 MYSMIL~1.OSP My Smiley Project.osp
03/04/2021  10:14 PM    <DIR>          MYSMIL~2     My Smiley Project_assets
02/25/2021  08:27 AM    <DIR>          POWERS~1     PowerShell
12/01/2020  06:13 AM    <DIR>          QTCREA~1     Qt Creator
11/10/2020  06:31 AM             1,463 TEEVEY~1.PPK teevey-Win10vm.ppk
11/10/2020  06:31 AM               480 TEEVEY~1.PUB teevey-Win10vm.pub
12/01/2020  06:02 AM    <DIR>          VISUAL~1     Visual Studio 2019
09/23/2020  06:13 PM    <DIR>          WINDOW~1     WindowsPowerShell
               5 File(s)         29,364 bytes
               9 Dir(s)  11,245,858,816 bytes free

C:\Users\DP\Documents>del MYSMIL~1

C:\Users\DP\Documents>dir
 Volume in drive C has no label.
 Volume Serial Number is 787D-9E57

 Directory of C:\Users\DP\Documents

03/04/2021  10:28 PM    <DIR>          .
03/04/2021  10:28 PM    <DIR>          ..
11/19/2020  10:21 AM               641 .vsconfig
11/19/2020  12:51 PM    <DIR>          gammaray-2.11.2
01/05/2021  08:13 AM    <DIR>          GitHub
03/04/2021  10:14 PM            26,780 My Smiley Project.osp
03/04/2021  10:14 PM    <DIR>          My Smiley Project_assets
02/25/2021  08:27 AM    <DIR>          PowerShell
12/01/2020  06:13 AM    <DIR>          Qt Creator
11/10/2020  06:31 AM             1,463 teevey-Win10vm.ppk
11/10/2020  06:31 AM               480 teevey-Win10vm.pub
12/01/2020  06:02 AM    <DIR>          Visual Studio 2019
09/23/2020  06:13 PM    <DIR>          WindowsPowerShell
               4 File(s)         29,364 bytes
               9 Dir(s)  11,242,176,512 bytes free
```

**Comment by ferdnyc** [comment]
As for why the files can't be deleted from Windows... I'm not sure. Honestly, that seems like a bug in NTFS (Microsoft's disk filesystem), because if a file can be created with a particular name it should be able to be deleted again using that same name.

There's no protection on the file that prevents its erasure, it's just that the name is somehow tripping Windows up. Probably due to the space on the end. But like I said, since it managed to **_create_** the file in the first place...
