### ISSUE TITLE
Crashing when video is beeing exported EVERYTIME

### ISSUE THREAD

**Issue by adamlukacka** [OpenShot/openshot-qt#4046]
no matter which format I was trying to export did crash closing the program, it didn't work on PC (WIN8) or Mac (Big Sur)

using the current version 2.5.1

**Comment by audreane20** [comment]
Same here

**Comment by Rstation4** [comment]
I too am having issues with  2.5.1 and it being usntable, crashing and sometimes freezing my desktop pc completely. I have used OpenShot few years ago but I think I need to abandon it because it just does not work well. On top of that my videos get really bloated in file size.

There needs to be a complete overhaul or something because if it was like this in the past with issues then I don't see it in the near future to improve. I do hope they take these issues and feedback seriously, because I'm not willing to waste any time with this anymore.

consider the alternatives: https://itsfoss.com/open-source-video-editors/

**Comment by DanPinGF** [comment]
If OpenShot crashes that way, #4202 might be to blame; you're probably using an OpenShot with a shattered 'Blur' effect.

**Comment by DanPinGF** [comment]
@speedytechdev - We've also got a #1197 and #4319 ex-Machina here. And someone's probably gonna have to add a '🔥 hot' label to this issue, if it is affecting everyone using the Windows version.
