### ISSUE TITLE
HELP !!!! 

### ISSUE THREAD

**Issue by ninjap2727** [OpenShot/openshot-qt#4052]
Openshot just saved a new file on top of my project, that I spent 12 hours making today
I just can't breathe, can't do anything anymore, I am petrified. Openshot refuses to open the saved file (I did a backup a couple of hours ago) saying "missing key". 

Please please help me, I can't face doing it all again :(( 

working on MacBook Pro updated with Catalina. 

thank you !!!!!

![Screenshot 2021-03-19 at 20 35 27](https://user-images.githubusercontent.com/80984105/111834110-69e55600-88f3-11eb-8231-2b3df9e37a50.png)

**Comment by ninjap2727** [comment]
[Court métrage 1 Toxiques entre amis (version 2).osp.zip](https://github.com/OpenShot/openshot-qt/files/6173774/Court.metrage.1.Toxiques.entre.amis.version.2.osp.zip)

**Comment by ferdnyc** [comment]
@ninjap2727 

Here's a ZIP file containing a version of your OSP with the JSON error repaired. The problem was in this line of text:
```json
"path": "@assets/title//"j'ai un cancer de la gorge\".svg",
```
Which I corrected to:
```json
"path": "@assets/title//j'ai un cancer de la gorge.svg",
```
That correction _may or may not_ be exactly right, depending what the filename of the title SVG actually is in your project's `assets/title/` folder. But worst-case, the project won't be able to open that one title file. If that happens, I can re-correct the data to the correct filename.

We'll also need to figure out what in our export process caused the bad filename to be written out, so information as to the exact filename as it appears on disk would be helpful even if this replacement file works. (If the filename actually does contain double quotes, then I suspect I know what happened.)

[Court.metrage.1.Toxiques.entre.amis.version.2.osp.zip](https://github.com/OpenShot/openshot-qt/files/6174341/Court.metrage.1.Toxiques.entre.amis.version.2.osp.zip)

**Comment by USATechDude** [comment]
Just on the odd chance that the file fix from @ferdnyc does not work, you can also try looking in your ~/.openshot_qt recovery folder to see if there is a recent enough backup of your file to save you from having to restart.
- Open the Finder
- Press **Shift +⌘+G** to open the Go to Folder window.  
- In the field under Go to the folder: type **~/.openshot_qt** then click **Go**.
- Open the **recovery** folder
- Look for a file beginning with your project's name then look for the most recent version
- Open the OSP file to see how much of your project was saved

**Comment by ferdnyc** [comment]
Also good advice, though in this case my concern is that, because this is an export bug on our part, every recovery file since that SVG was added will likely have the same damage.

**Comment by ferdnyc** [comment]
Looking at this again, I'm almost certain that the filename _**does**_ contain double quotes, and the correction should actually be this:
```json
​"​path​"​: ​"​@assets/title/\"​j'ai un cancer de la gorge\​"​.svg​"​,
```

I'll put together another zip file with that version of the correction once I get back to my computer. Give me 15 minutes or so.

**Comment by ninjap2727** [comment]
OMG @ferdnyc I just can't thank you enough for trying ! Currently downloading and will get back to you ASAP !!

 @USATechDude thank you heaps also ! Will deffo give a try to this option if the Zip doesn't give any exploitable data....

Thanks a lot for getting back to me in such a quick time, both of you rock !! Checking it now, fingers crossed.... awww (-__-°)

**Comment by ninjap2727** [comment]
Ok, so as previously said by @ferdnyc : Openshot can't find this subtitle ("J'ai...) No idea why, honestly I can't recall having done any file deletion or move during the time I worked on that project. It sounds like the software crashed out randomly without me making any awkward request. 

Now trying @USATechDude option. Fingers still tightly crossed...!

**Comment by ninjap2727** [comment]
Ok so I've tried both of your techniques now, as said @ferdnyc the recovery files are forwards dated as it is the new projet I started remaking a few hours after having lost the complete work... I don't dare to click on any; but for sure I lost the project around 8PM and recovery files are starting from 10.30PM... Well, I am starting to think that I better restart from the scratch before the creative ideas vanish, thank you both heaps for supporting and providing these options !! You are great :) PS. also good to know the access to the recovery folder, can be extremely helpful in the future !
