### ISSUE TITLE
how to delete audio

### ISSUE THREAD

**Issue by Haikyuusimp** [OpenShot/openshot-qt#4060]
i would like to delete the audio so that i can put music in  my video but i dont know how to

**Comment by ferdnyc** [comment]
@Haikyuusimp 

You'll need to change the "Enable Audio" property for the clip you want to silence from the default ("Auto") to "Off".

To be sure it takes effect over the entire clip, first position the playhead AT or BEFORE the first frame of the clip (left edge), and click the clip to select it (it'll be outlined in red).

Then, right-click on "Auto" next to "Enable Audio", and select "Off" from the menu. That'll silence the entire clip.

![Screenshot from 2021-03-24 21-48-55](https://user-images.githubusercontent.com/538020/112406623-e5c41180-8cea-11eb-8a73-4591f682260c.png)

You should use the menu to choose "Off", rather than dragging the mouse to change the value, because I just discovered there's a bug where dragging the slider can mess up the setting.

#### Details, if you're interested/curious, but not anything you really need to care about

The property takes an integer corresponding to the setting: `-1` for "Auto", `0` for "Off", and `1` for "On". But by dragging the slider, it's possible to set it to something like `-0.2` (which will still be treated as "Off") or `-0.9` (which will be rounded and treated as **"Auto"** even though it will _say_ "Off"). That's a bug we'll need to fix. The slider is supposed to correct the setting to a whole number no matter where you stop, but apparently that got broken somewhere along the way.

If you right-click and choose "Off", though, it'll be set to exactly `0` for sure.
