### ISSUE TITLE
Activating clip menu adds new clip unless mouse pointer is located very precisely.

### ISSUE THREAD

**Issue by AZGLi** [OpenShot/openshot-qt#4064]
**Describe the bug**
When attempting to activate the clip menu by clicking on the arrow icon, the menu records the command as open menu, add clip instead of just open menu. There is a small area where the menu works correctly and other areas where the icon will change color but the reported behavior happens instead of the menu opening.

**Steps to reproduce the behavior:**
1. Open OpenShot
2. Move the mouse to the down arrow icon in the upper left of a clip.
3. Click the mouse.
4. One of two behaviors will happen depending on mouse location; correct operation or error.

**Expected behavior**
Mouse position where the down arrow icon changes to white + mouse single left click opens menu

**System Details**
- OpenShot Version: 2.5.1-dev2
- libopenshot Version:  0.2.5-dev3
- Platform: Windows-10-10.0.19041
- Processor: AMD64 Family 21 Model 2 Stepping 0, AuthenticAMD
- Machine: AMD64
- Python version: 3.7.4
- Qt5 version: 5.12.4
- PyQt5 version: 5.12.3
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev2-daily-7016-9efa3592-bd033247-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/6yupgncu9ht53cn4ewgmmpae6ylokvmn/openshot-qt.zip) (102 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/6yupgncu9ht53cn4ewgmmpae6ylokvmn/libopenshot.zip) (40 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
https://youtu.be/BQ3Yy81Y_aY

**Comment by ferdnyc** [comment]
Hrm. The report sounds very similar to #3873, which I really hoped I'd fixed with #3877. But I guess not. :-(

Just to confirm, you're still encountering this even with the latest Daily Build versions, built more recently than January 27 (the day #3877 was merged)?

Also, just OOC, are you _Left_ or _Right_-clicking on the icon? (In theory either should work, but you can right-click anywhere on a clip to open its menu, so the icon is more intended for left-clicking.)

And when left-clicking... hmm, I suppose it's possible my fix in #3877 isn't effective (or is less effective) when opening menus in response to a left click. (Or, it's also possible it just didn't work.)

**Comment by AZGLi** [comment]
Yes, same bug. It didn't come up when I looked for similar bugs, sorry!
Feel free to combine.

Yes, latest daily build.

Bug is avoided if the mouse button is not released until the selection is
made.

Left mouse button.

Thanks!

**Comment by AZGLi** [comment]
This bug has been resolved in the latest version.
