### ISSUE TITLE
No hardware acceleration options available with nvidia GPUs

### ISSUE THREAD

**Issue by jfp1992** [OpenShot/openshot-qt#4098]
**Describe the bug:**
I have a gtx 980ti and a rtx 3070,
I go to edit>preferences>performance
I click hardware decoder mode but it doesn't show anything in the drop down.

**Steps to reproduce the behavior:**
1. Click on edit
2. Click on preferences
3. Click on performance
4. Click drop down

**Expected behavior:**
Able to see HW decoder for my GPU, such as nvenc / cuda

**Actual behavior:**
No drop down option for hardware acceleration

**Things tried**
Reinstalling openshot
Rebooting machine

**System Details:**
- OpenShot Version [2.5.1]: {{ log_context.openshot_qt_version }}
- Operating System [Windows 10]

**Screenshots:** (Optional)
![image](https://user-images.githubusercontent.com/20302512/115198585-2183a880-a0ea-11eb-8734-529372060430.png)

**Comment by DavidOsipov** [comment]
Same here. I trying daily build (09 of April 2021), but no effect.

**Comment by tactmaster** [comment]
Same with a 2060

**Comment by JacksonRG** [comment]
I'll look into this. It looks like currently GPU acceleration isn't fully supported on windows.

**Comment by excelsior091224** [comment]
Same with an AMD Radeon RX5700XT

OpenShot-v2.6.1-release-candidate-8238-59878784-d588dbd6

**Comment by AyrA** [comment]
Can confirm on my end too. System details:

```
NVEncC (x64) 5.41 (r2064) by rigaya, Oct 14 2021 13:42:50 (VC 1929/Win)
OS Version     Windows 10 x64 (19042) [UTF-8]
CPU            AMD Ryzen 9 5950X 16-Core Processor [3.40GHz] (16C/32T)
GPU            #0: NVIDIA GeForce RTX 3090 (10496 cores, 1785 MHz)[PCIe4x16][472.47]
NVENC / CUDA   NVENC API 11.1, CUDA 11.4, schedule mode: auto
```

NVEncC can successfully render video files using GPU so it's definitely not a driver or hardware issue.

**Comment by AyrA** [comment]
> * If this issue is reporting a bug, please can you attempt to reproduce on the [latest daily build](https://www.openshot.org/download/#daily) to help us to understand whether the bug still needs our attention.

Can confirm that this still exists in `OpenShot-v2.6.1-dev-daily-9498-664c5db8-46255e46-x86_64.exe`

**Comment by valankar** [comment]
https://openshot.org/files/libopenshot/md_doc_HW-ACCEL.html

currently says encoding is possible on Windows. Is this not correct?

**Comment by Colorjet3** [comment]
It may have worked previously but currently it does not.

**Comment by Thedoczek** [comment]
Still not working

**Comment by Colorjet3** [comment]
Hello @Thedoczek Correct, hardware acceleration in Windows is not yet working.  No ETA either!

**Comment by Colorjet3** [comment]
Here is the word from the DEV Team:
• Hardware Acceleration: Hardware Acceleration in Windows is supported but limited. Those new settings that you see in the Performance tab are new, experimental, and not fully baked.
- Hardware acceleration is still experimental in OpenShot Video Editor.
- NVIDIA NVENC acceleration is only available in Linux operating systems.
- OpenShot v2.6.0 and later includes Intel® Quick Sync Video encoding in Windows operating systems. If you have a CPU that supports Intel®QSV encoding, you can use the encoder by selecting the ( QSV) MP4 (h.264 qsv) Target on the Export Video window. You do not have to change the Preferences window to use the Intel® QSV encoder."
• Hardware acceleration in OpenShot requires using the proprietary drivers from the distribution package manager instead of the NVIDIA drivers. You cannot use the Nouveau, Xorg, or open-source drivers.
