### ISSUE TITLE
ModuleNotFoundError: No module named 'openshot'

### ISSUE THREAD

**Issue by theyoz** [OpenShot/openshot-qt#4137]
Hi,
I'm using Fedora 34. I've tried to run openshot from app image with no success, so I tried from source. I get

```[yoram@yoram-rog-g14 openshot-qt]$ python3 src/launch.py
Loaded modules from: /home/yoram/apps/open/openshot-qt/src
INFO app: ------------------------------------------------
INFO app:             Wed May 12 12:09:41 2021            
INFO app:               Starting new session              
ERROR app: OpenShotApp::Import Error
Traceback (most recent call last):
  File "/home/yoram/apps/open/openshot-qt/src/classes/app.py", line 100, in __init__
    import openshot
ModuleNotFoundError: No module named 'openshot'
Traceback (most recent call last):
  File "/home/yoram/apps/open/openshot-qt/src/launch.py", line 180, in main
    app = OpenShotApp(argv)
  File "/home/yoram/apps/open/openshot-qt/src/classes/app.py", line 100, in __init__
    import openshot
ModuleNotFoundError: No module named 'openshot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yoram/apps/open/openshot-qt/src/launch.py", line 199, in <module>
    main()
  File "/home/yoram/apps/open/openshot-qt/src/launch.py", line 182, in main
    app.show_errors()
AttributeError: 'NoneType' object has no attribute 'show_errors'
INFO app:             OpenShot's session ended            
INFO app:             Wed May 12 12:09:42 2021            
INFO app: ================================================
```

I've seen from otehr issues that maybe related to QT version.This is what's on mine

```
>>> from PyQt5 import Qt
>>> print(Qt.QT_VERSION_STR)
5.15.2
>>> print(Qt.PYQT_VERSION_STR)
5.15.4
```

Can you help?

**Comment by JacksonRG** [comment]
I'm going to look deeper into this. But in the meantime here's an [issue](https://github.com/OpenShot/openshot-qt/issues/2875) which appears to be dealing with a similar problem.

**Comment by theyoz** [comment]
I looked at the issue but it looks like you need a workign openshot which I don't. I'm running Fedora 34, and get an error when running from app image.

**Comment by wasimafser** [comment]
With my recent build experience, I also encountered the same issue, where libopenshot installation says successful, but wasn't available for use. So I decided to use the pythonpath method:

```
PYTHONPATH=/path_to_libopenshot/build/src/bindings/python \
python3 src/launch.py
```

This of course requires you to have the libopenshot built. If you want to use it now for some reasons, just get the sources and build it until it's fixed maybe ?

**Comment by ferdnyc** [comment]
From source, you definitely need libopenshot (and libopenshot-audio). On Fedora, both can be installed from the RPM Fusion repos. Of course, so can OpenShot itself.

I'll try to take a look at why the AppImage isn't working. If it's the 2.5.1 AppImage, I think that's expected given its age. If it's the Daily Build AppImage, most likely I broke something that I can hopefully also fix.

**Comment by ferdnyc** [comment]
@wasimafser 
> With my recent build experience, I also encountered the same issue, where libopenshot installation says successful, but wasn't available for use.

Well, the question is WHERE it was installed.  Which is partly an OS question.

On both MacOS and Windows, the Python module is just dumped into `<install_prefix>/python/` and it's up to the user to move it somewhere useful. (That's mostly because the Python extension library's dependencies have to be sorted out by hand, so installing into the Python `site-packages` isn't really useful on either platform.) The docs are probably out of date on that point.

It is possible to set a different `PYTHON_MODULE_PATH` destination, either on the CMake command line or as an environment variable prior to running `cmake`, but I'm pessimistic about that working even if set to the correct Python `site-packages` path.

On Linux, the install code attempts to discover the correct `site-packages` for the Python in use and installs there. Which, coupled with library installation into `/usr/` or `/usr/local`, lets all of the pieces find each other.

But the `PYTHONPATH=` method, pointing into the build dir, should work everywhere except Windows. (There, the lack of any sort of RPATH feature means that DLLs probably have to be copied around manually, before it'll run.)

**Comment by wasimafser** [comment]
Thank you very much for the information!

>  The docs are probably out of date on that point.

Sure it is, I was just focused on setting up the application that, I didn't notice what exactly was happening, until when I was stopped by that.

> but I'm pessimistic about that working even if set to the correct Python site-packages path

I can try that if you want !

**Comment by USATechDude** [comment]
I tested the latest Daily Build on Fedora 34 and verified that it works.  You can download and install the [latest Daily Build](https://www.openshot.org/download/#daily) of OpenShot from our website to address the issues until we release a new stable build.

**Comment by theyoz** [comment]
Works for me!!! Thank You!
