### ISSUE TITLE
openShot during use automatacaly close 

### ISSUE THREAD

**Issue by namdeosairise** [OpenShot/openshot-qt#4149]
openShot during use automatacaly close

**Comment by USATechDude** [comment]
You can usually fix crashing or freezing by addressing the following:

* Your computer may be struggling with the video editing process. This issue is most familiar with laptops and older hardware, and you can address it by following [this video](https://vimeo.com/420117641).
* If the above video did not solve the freezing/crashing, try a new OpenShot project for testing. Also, test another video using a new video profile. This approach allows us to see if the issue is in the installation or something happening with a specific video, and OpenShot is not cooperating.
* Uninstall / Reinstall the latest version of OpenShot (or the latest daily build if the current stable version is the problem).
* Remove `C:\Users\(USERNAME)\.openshot_qt` folder. Removing this folder removes settings and many things that can, in theory, become corrupt. OpenShot automatically recreates the folder.
* If the bug happens again (after a clean reinstall and removal of the `C:\Users\(USERNAME)\.openshot_qt` folder), immediately send us those log files. The best approach is to visit your `C:\Users\(USERNAME)\.openshot_qt` folder, delete the `libopenshot.log` and `openshot-qt.log` files. Then relaunch OpenShot, and recreate the errors. Now you can open [a bug report](https://github.com/OpenShot/openshot-qt/issues/new?assignees=&labels=%3Abeetle%3A+bug&template=bug-report.md) and send us the `openshot-qt.log` and `libopenshot.log` files.
* Download and install the [latest Daily Build](https://www.openshot.org/download/#daily) from our website.
