### ISSUE TITLE
Distribute Daily Builds (and releases?) as Portable applications, to avoid wiping out existing release installs

### ISSUE THREAD

**Issue by axalox** [OpenShot/openshot-qt#4152]
Hello

I'm on Windows 10 and when i install daily build I can't choose a folder.
All time i'm installing daily build it overwrites the stable version.
It will be cool if you let user choose the folder for install the daily build.

**Comment by ferdnyc** [comment]
Yeah, I've been thinking about something like that for a while. The reason you're not shown a folder selection option (like you _are_ when you first install OpenShot) is that the Daily Build installer detects the existing OpenShot installation, and automatically installs itself as an update. Installing multiple versions simultaneously isn't currently something the installer supports, though there's no reason it _couldn't_.

For now, though, you can actually install to a specific (alternate) folder by launching the installer from a command line and adding some options. This will install a downloaded Daily Build to a build-specific directory, for instance:
```cmd
OpenShot-v2.5.1-dev2-daily-6982-9efa3592-bd033247-x86_64.exe
  /DIR="C:\Program Files\OpenShot Video Editor 2.5.1_daily6982"
```

Unfortunately, because we don't use a start menu group for the launcher, the "OpenShot Video Editor" start menu entry will still be overwritten to point to the newest install. To fix that, we'd need to create a folder to install the launcher in, at which point its name could be customized by adding `/GROUP="OpenShot Video Editor 2.5.1_daily6982"` to the command line as well. (Or, maybe we could start using the install folder name as the launcher name, for when it's customized.)

I can't promise it won't break anything else, either. (Like, I'm not sure which version will be the _default_ association for `.osp` files, assuming you installed both with the "associate..." option checked.) But it does at least install a working copy of the application into the directory specified, I _believe_ without damaging the other install (except for modifying its start menu launcher).

**Comment by axalox** [comment]
Ok, it's possible

Thx for your explanation.

**Comment by ferdnyc** [comment]
In thinking about this more, a _better_ use of time and effort might be to come up with a Portable build of OpenShot, to complement the installable build(s). Then the Daily Builds could either be distributed _with_, or _exclusively as_, portable downloads. That way there's no worrying about installation or overwriting release versions.

The Linux AppImage is effectively already a portable build, we'd just need to come up with Windows and Mac equivalents. (...Actually the current macOS distribution might also qualify as a portable app. I don't know what happens if you extract `OpenShot Video Editor.app` somewhere random and run it, instead of putting it in an Applications folder. ...It probably works just fine that way.)

**Comment by ncabanes** [comment]
I was going to make the same request. 

I do not need it to be portable, but I would like to be able to choose. Even if an existing installation is detected, I should be able to install to a different folder... or even a different drive (my C: drive is far more limited than my D:). It if implies deleting the previous version, I should be warned, as it might seem OK to me, but I **hate** (and I mean **hate**) having software installed in my C: drive, which is quite overpopulated, and not being offered an alternative.

**Comment by seascape** [comment]
I'm looking for a Windows 10 video editor, preferably open source, and was irritated there was no portable option on the main website. Came here to check if there was a workaround or discussion. Glad to see it's been brought up, but wish it existed already as I only use portable apps when possible.

**Comment by ferdnyc** [comment]
> Thankfully it looks like there is an [unofficial portable distribution](https://portableapps.com/apps/music_video/openshot-portable). That will be fine for now.

So there is! Thanks. I just took a look at that real quick.

I'd feel a bit better if their exact packaging process was defined and logged somewhere public (maybe it is, but I'm not seeing it), but it _looks_ like they merely take the official installer build and re-package it for portability. (Actually, _builds_, since the portable app bundles the 32-bit and 64-bit installs together, which is crazy wasteful, but whatever.)

That's a good thing, as it means the build should be pretty comparable to the official package downloads. It's  not some weird, rogue build with who-knows-what stuck into it or messed with for unknowable reasons. (Of course, we can't _guarantee_ that will always be the case, especially in the future, but as things stand today it seems pretty OK.)

I'm tempted to link to the PortableApps distribution page from the README as an alternative download, in fact. No harm in giving people options.

**Comment by ferdnyc** [comment]
> I'd feel a bit better if their exact packaging process was defined and logged somewhere public (maybe it is, but I'm not seeing it)

\*grumble* In fact, they even do [a full blog-post-style release announcement](https://portableapps.com/news/2021-08-26--openshotportable-2.6.0-released) for each updated portable package... but even **that** is pure "marketing"; it doesn't provide any technical details about the packaging. Bleah. This is why I will never grok the Windows ecosystem.

**Comment by Twenkid** [comment]
Btw you've closed the duplicate issue but it was asking for the official releases as well (at least) as download options, assuming they were somewhat debugged, while the site offers only the last version and daily builds, which usually have annoying problems for some setups (and are a reason to search for older versions).
