### ISSUE TITLE
Cutted video does not play correctly when you speed it up.

### ISSUE THREAD

**Issue by smirnovp** [OpenShot/openshot-qt#4165]
It plays entire video when you speed it up even if it was cutted before upspeeding. It works fine inside the program with no issue, but shows up when you run a finally converted video.

1. Upload any video for editing.
2. Cut the video and save only left part.
3. Speed ​​up the left side by any multiplyer
4. Check playback, everything is showing correctly.
5. Convert video and run.

In the final video you see the whole clip as if it was not cutted at all.

**Comment by JacksonRG** [comment]
Could you include the OpenShot version, operating system, and file type you're using? This will help us recreate this issue.

**Comment by smirnovp** [comment]
OpenShot version: 2.5.1-dev2
OS: Ubuntu 20.04.2 LTS
file type (source): mkv
output format: YouTube-HD

**Comment by JacksonRG** [comment]
Thanks! Taking a look at this

**Comment by elliena-bulmer** [comment]
Got the same issue here, Any workaround?

OpenShot v: 2.5.1
libopenshot: 0.2.5
OS: Windows 10, 20H2
output format: YouTube-HD

**Comment by Bardaf** [comment]
Hello, I am also encountering the problem described here

I tested in version 2.5.1 / 2.6.0 and in the daily of September 6 and 8

OS: Windows 10 21H1
output format: Twitter / MP4 (h.264)

**Comment by Bardaf** [comment]
Hello,
I did some tests in the daily of September 10.
I wanted to work around the problem by making the cut in a project, exporting the video, making a new project to set up the acceleration.
What I see is that the cut video is exported correctly, but the video containing the acceleration still contains the bug.

Here is a link to the exported video after acceleration : (https://drive.google.com/file/d/1bvQrAtJ_wSjHttvMCBM7V1Imz6ZJJ4Kg/view?usp=sharing)

The initial problem still remains, when we do a cut + acceleration, the accelerated sequence is not done at the good timing of the original video. I presume as in the original message of this ticket, that during the overview everything is fine, the problem only appears on export. Here is a link to my full video project that I have the bug on:  https://drive.google.com/file/d/1_wz4WLMA776HMHUyiRecgaJPSQCproUQ/view?usp=sharing
We can clearly see the cut at 2 minutes 15, then the fixed image at 2 minutes 29. The problem also manifests itself at other times of the video. In addition, the card part on the right presents the same problem at other times (being an independent source video, it is cut and accelerated at other time than the main video)

Finally, here is a link to the logs in debug mode of my main video project (Itineraire Wavrin-Beaupré.osp). While writing its logs, I loaded the already saved project and exported the video. This bug is very penalizing because we have no workaround. Tell me you need more info / content, I will send it to you if possible.
(https://drive.google.com/file/d/1uu2VH2_5dHc-ym7A8Lu45kcrJkazp7CG/view?usp=sharing)



Sorry for my bad English

**Comment by Bardaf** [comment]
Hello,
here is new information.
The bug appears to be related to all actions over time. In this new video, I applied the freeze function. The whole video sequence where I applied the freeze is frozen (although I only applied it for a few seconds).
This time again, this only happens when exporting the video but not at the preview.
Is it possible to have a correction, it becomes really disabling.

This new video was made with the daily 8350 of September 29.

https://drive.google.com/file/d/1Lj7bQfQ-jjD5t80mQnd7b61Kkxk4evHQ/view?usp=sharing
