### ISSUE TITLE
Nur 4 CPUs?

### ISSUE THREAD

**Issue by Norderstedter24558** [OpenShot/openshot-qt#4203]
**Question:**
A clear and concise question. Your question should provide enough context and explanation for people to answer it. Avoid excessive background or irrelevant details, as they can obscure your actual question.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your question. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by Norderstedter24558** [comment]
Hallo,

laut Aktivitätsanzeige von Mac OS werden "nur" 4 CPUs genutzt. Ich habe ein Ryzen K9 3900X mit 24 Kernen - warum wird das Programm so ausgebremst?

**System Details:**
- OpenShot Version2.5.1
- Operating System / Distro: Mac OS 10.13.6

**Comment by JacksonRG** [comment]
Are you having performance issues with Openshot? A program can only use as many cores as it has threads.

**Comment by USATechDude** [comment]
> Hello,
>
>according to the activity display of Mac OS, "only" 4 CPUs are used. I have a Ryzen K9 3900X with 24 cores - why is the program slowing down so much?

Since Apple does not build machines with AMD processors, I assume you are running macOS in a virtual environment.  Did you assign more than 4 threads of your 12 core CPU to the virtual machine running macOS?
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Da Apple keine Maschinen mit AMD-Prozessoren baut, gehe ich davon aus, dass Sie macOS in einer virtuellen Umgebung ausführen. Haben Sie der virtuellen Maschine mit macOS mehr als 4 Threads Ihrer 12-Kern-CPU zugewiesen?

**Comment by Norderstedter24558** [comment]
No virtual Maschine. Only a native "Hackintosh".
