### ISSUE TITLE
Timeline should be able to zoom in MUCH further than 1 second increments

### ISSUE THREAD

**Issue by aneurysm1985** [OpenShot/openshot-qt#4219]
Hi there, I just downloaded OpenShot for the first time and started using it.

I was surprised to find that I was not able to zoom into the timeline to see increments further than 1 second.

I am trying to use a 'clapperboard' -style edit of audio and video using handclaps, and the current zoom intervals is simply not fine-grained enough for me to be able to line up the video and audio with any confidence. The experience leaves me leaning into my monitor, squinting, and wondering if things are exactly aligned or not.

I see users have [raised this issue in the past](https://github.com/OpenShot/openshot-qt/issues/286), and that it is still an issue for me to experience in 2021. **Hoping you increase the zoom intervals to comfortably allow frame-by-frame editing.** Cheers!

**Comment by Twenkid** [comment]
Good that somebody mentions that. ferdnyc gives an explanation thoguh, technical reasons: https://github.com/OpenShot/openshot-qt/issues/286#issuecomment-694033541
"Shift+← and Shift+→" for adjusting the frames

If I'm not mistaken ffmpeg has been discussed as not guaranted to produce frame-precise cuts.
By the way, do you use the option to show the waveform of the video (if it has audio), maybe it would help a bit.

The suggestion to edit the sound separately in the explanation of the problem sadly throws me to my self-developed video editor (used only in-house), where I used the same technique:

One separate audio track in WAV (in order to allow synchronising up to 1 audio sample, 1/48000 sec etc. mp3 etc. could be nasty when cutting and concatenating). The track is edited outside and is exported to say the same filename, which is linked to the video editor - the editor has a parameter "audio track". 

During the preview in the video editor, the editor plays that WAV, with a **"Sync"** option which shifts the audio clip (one for the whole project), it could be + or - and the precision is in seconds, floating point (not video frames), so such a sync could be done without re-exporting the audio. (It is similar in VirtualDub)

**Feature suggestion:** Linking audio to external audio tracks and time-sync shifts (as explicit parameters and high precision, not frames). That audio has to be unlocked for change by other programs (unlike the usual open files in the project), and only read, not written by OpenShot. That would allow quicker tests.

**Comment by ferdnyc** [comment]
@aneurysm1985

Thanks @Twenkid , that pretty much covers it.

The thing about the zoom level is, as I've said before, it's geared towards showing you exactly how much information you **can** make use of. Even if you were to zoom in more closely, you don't have the ability to position clips any more precisely than at exact frame intervals. (And half-frames, if you use the somewhat-hidden "nudge" feature.)

But even if you could zoom in closer, the audio waveform wouldn't have any additional detail, its resolution is also capped at roughly the video frame rate.

I wouldn't have thought that's enough accuracy to do the kind of exact positioning you're talking about, period. I probably would've questioned whether OpenShot is well-suited to your needs, for that reason. But since you say you've been managing so far, I may be wrong about that. A closer zoom is unlikely to really change anything for you, though.

(Sure, if you could zoom closer, AND see additional resolution in the waveform, AND position clips more accurately... then, sure. But that's a lot of ifs.)

**Comment by ferdnyc** [comment]
@Twenkid 
> Maybe the above could be emulated by manually adjusting the **Start-End parameters** of the audio clip tracks in OpenShot, however I don't know is it precise up to 0.01 or 0.001 s:

That, I can answer.  It's accurate to whatever the project frame rate is. So at 25fps, it's accurate to `0.04` seconds.

**Comment by Twenkid** [comment]
@aneurysm1985  _"The experience leaves me leaning into my monitor, squinting, and wondering if things are exactly aligned or not."_

Don't you examine it by the video and the sound itself? The lips of the speakers, the other sounds within the video - something hitting etc.? When I do sync, I just play/preview, or export the secton* of interest and I watch the video to "feel" does it sound right, make an adjustment etc.

* Here OpenShot is still lacking a quick export for such synchronizing/debug needs, so one has to calculate the frame numbers for the export dialog / Advanced.

You're welcome! @ferdnyc 

I think if working at 50-60 fps, 0.02 - 0.0166 s is not that bad as a precision.

As of using an external editor, another feature proposal which would make sync much easier:

**1)** What about an option for exporting the audio tracks directly into an Audacity .aup project and respectively importing an .aup project as tracks?; possibly with the markers and/or generating markers: "here starts that clip with these parameters start/end etc. (Some matching-pairing with the videos.)

**2)**  Adding a high-precision audio shift per clip. How to implement: before mixing, decoding to wav at sample-precision (if it's not done anyway when mixing?), applying the shift/trims etc. and adding *that* modified clip to the timeline so not depending on frame-length. I'd do that also with optional commands/script, which can be easily edited/automated. 

**3)** An automatic audio sync option. Search for the first claps and trim the clips automatically, with the audio shifted with the higher precision if possible.

**Comment by aneurysm1985** [comment]
> The thing about the zoom level is, as I've said before, it's geared towards showing you exactly how much information you **can** make use of. Even if you were to zoom in more closely, you don't have the ability to position clips any more precisely than at exact frame intervals. (And half-frames, if you use the somewhat-hidden "nudge" feature.)
> 
> But even if you could zoom in closer, the audio waveform wouldn't have any additional detail, its resolution is also capped at roughly the video frame rate.

I understand that, but my point is that right now the waveforms are too small to be useful to my eyesight, with the resolution of monitor that is available to me.

See the below image, of a project that I am working one, where I am syncing the audio and video using three handclaps. I **_really_** wish that could zoom in much further than this, so that I could get a big, clear look at how those 3 columns align with each other, and how the Shift+Right 'nudges' move the clips relative to each other.

The 'nudges' change things slightly, but I fit it hard to tell when I am right on the mark, versus having overstepped it.

![image](https://user-images.githubusercontent.com/6709073/126053003-5798df29-1b79-4cf9-bb1e-fcc8c3b96d5a.png)

My point remains that I am having to lean in, with my face extremely close to my PC monitor, to perceive how aligned the waveforms are to each other.

My suggestion remains that I would rather the option of being able to see big, chunky, zoomed-in blocks so that I can see how things look from a distance.

Note that I think that my vision is pretty good, so I imagine users with worse eyesight than me would be struggling even moreso trying to do this alignment with the current level of zoom available.

Just giving some real-world feedback to you, as were the multiple users who raised the issue via [Issue #286](https://github.com/OpenShot/openshot-qt/issues/286). Take that as you will.

**Comment by Twenkid** [comment]
@ferdnyc @aneurysm1985 I will also appreciate more zoom of the **view*** and the argument about people with worse vision is good - I think a compromise of the lack of precision in the editor and the zoomed view is just the **allowed *moves*** of the clips and the pointer positions to remain discrete - frame-time length, - so the user would not be confused that she is getting more than that.

@aneurysm1985
Regarding the need to lean, though, I guess you're either using a laptop with a very small screen or your eyesight is not that good as you believe, because I can dinstinguish the line clearly on a 20" monitor which is at 0.9 m - 1m away from my eyes, as the picture is in the small view on github, where the image width is about 21 cm; in that condition the red line width is visibly ~ 1/3 of the blue "tooth". In the more real use-case, when I open the picture and it covers the whole screen, its width is ~ 41 cm and it is comfortably visible, even "big" in my case.

Indeed when I've needed more precise positioning, my "struggle" have been with the discrete jumps if you click or more so if you drag the timeline, thus it was the mouse precision. 

However for placing the pointer (for Slicing), that's solved by moving the pointer with the arrow keys frame-by-frame, and for the cips it seems it is done by Arrows+Shift as ferdnyc suggested.

* Feature request: **Zoom-out the timeline tracks' height** **in order to show more tracks at once** (another zoom parameter): 
Sometimes there is a problem when selecting many clips for realignment. (I think I've once given a feature requests for automated clips-compression when deleting a clip etc. (there might be some constraints or user interaction, though, because it might be ambiguous). That is needed in order to avoid manual selection and dragging which is prone to mistakes and slight misalignments of the transitions (whose model is also prone to misalignments when moving, another old issue request I think). 

In order to see more tracks, curently the timeline section has to be widened, but this is limited and still, for complex videos with many audio tracks it may be not enough to cover all.

![изображение](https://user-images.githubusercontent.com/23367640/126059321-eff5e617-e2ed-436a-858c-26330651eb78.png)

For a multi-track selection it could be at least like that or even more compressed:

![изображение](https://user-images.githubusercontent.com/23367640/126059587-11312f02-ab16-4e11-ae2b-24155be41743.png)

**Comment by aneurysm1985** [comment]
> @ferdnyc @aneurysm1985 I will also appreciate more zoom of the **view*** and the argument about people with worse vision is good - I think a compromise of the lack of precision in the editor and the zoomed view is just the **allowed _moves_** of the clips and the pointer positions to remain discrete - frame-time length, - so the user would not be confused that she is getting more than that.
> 
> @aneurysm1985
> Regarding the need to lean, though, I guess you're either using a laptop with a very small screen or your eyesight is not that good as you believe, because I can dinstinguish the line clearly on a 20" monitor which is at 0.9 m - 1m away from my eyes, as the picture is in the small view on github, where the image width is about 21 cm; in that condition the red line width is visibly ~ 1/3 of the blue "tooth". In the more real use-case, when I open the picture and it covers the whole screen, its width is ~ 41 cm and it is comfortably visible, even "big" in my case.

To clarify, I **can** see the red line clearly next to the blue graph of the audio waveform. However, my mind always wonders "I wonder if that position is the closest possible alignment? I feel the need to zoom in and check with a super zoomed-in view, simply to satisfy my own curiosity, but the software currently only allows a wide zoom, so I am in a constant state of wondering how perfect the alignment is.

You make a good point that the timeline should only show the users the true amount of precision that they can actually get from their alignment. Only allowing discrete frame-by-frame positions that the editor can actually use is a good idea, so that users aren't fooled into thinking that they are getting more precision than the software allows.

**Comment by USATechDude** [comment]
Here's a trick that I use when displaying the waveform on the clip.  I increase the clip's volume (I usually have to guess at the amount) then click Display Waveform.  After the waveform displays on the timeline, I use CTRL+Z to undo the Volume change, but the waveform still shows on the clip.  This gives me larger peaks on the waveform to align my clips.

**Comment by JacksonRG** [comment]
Check out the daily build! I've reworked the ruler to allow zooming to see individual frames with +/- keys.
