### ISSUE TITLE
OpenShot File won't Open After Saved 

### ISSUE THREAD

**Issue by Athena12345678** [OpenShot/openshot-qt#4240]
My OpenShot project file will not open. After saving my OpenShot project and ensuring all files are saved accordingly, I closed the OpenShot application. The next day I went to open it and the file is unable to open. It is displaying the error message I have screenshotted below. I have tried re-downloading OpenShot and I have also tried copying the files from my external hard-drive (where I have them saved) and then tried to access them from my desktop. Nothing seems to work. 

Looking for any suggestions or further support. 

Thanks! 
<img width="1318" alt="Screen Shot 2021-07-23 at 11 21 54 AM" src="https://user-images.githubusercontent.com/87874566/126824282-82ec00a9-a808-4576-a009-49af3dc2c7b4.png">

**Comment by JacksonRG** [comment]
@ferdnyc I'm tagging you in this because I saw that you've dealt with this issue in the past. And today I've seen two of this exact error.

**Comment by JacksonRG** [comment]
Firstly, I'd advise you to check `/home/<your username>/.openshot_qt/recovery` for a backup of your project

**Comment by JacksonRG** [comment]
@Athena12345678 Yesterday I found that another user with a similar issue had file names with unusual characters in them. Specifically `"`, `?`, and `*`. If this is the case in your project, we might try finding and replacing those symbols so that they are easier for openshot to read. (Also if this is the case, I'll make a change so that openshot can't write files with such names).

Let me know if this helps. If not, I can help you try to fix your project file.
