### ISSUE TITLE
Video preview is too slow - but it worked before!

### ISSUE THREAD

**Issue by exaveal** [OpenShot/openshot-qt#427]
I installed "openshot-qt" for the first time. before I was running only "openshot" on my Ubuntu machine.
When I open my "old" projects which I have created with "openshot", it's impossible to go on working because the preview is so slow. Much too slow.
It's so laggy, that even video and sound are not synchronous.

I started openshot on the terminal to check if any error messages according the speed issues come up - but nothing. please help!

**Comment by edvaessen** [comment]
Same to me. It is a complete riddle. 
For the time being I'll have to fall back to Cinelerra-CV.

**Comment by exaveal** [comment]
It's a RAM problem. The computer is out of memory within seconds. 8GB are fully used after several seconds of preview or moving the position marker. see attached screenshot.
![openshot_ram](https://cloud.githubusercontent.com/assets/21370398/21547380/f84c632a-cde5-11e6-9152-c2c1e0da65d9.png)

**Comment by exaveal** [comment]
Same project file in preview mode with openshot 1.4.3. No memory-leak-problem!
![openshot1 4 3_ram](https://cloud.githubusercontent.com/assets/21370398/21565143/7f2b0e06-ce94-11e6-9c1c-9b58a27e84c2.png)

**Comment by exaveal** [comment]
I reported the bug in launchpad and tried to describe it as best as possible (for me 😄 ): https://bugs.launchpad.net/openshot/+bug/1653241
Please support a fix of the problems via "This bug affects you" and/or add more details.

**Comment by DylanC** [comment]
Dup of #411

**Comment by DylanC** [comment]
Try OpenShot v2.4. The preview is much better and no lag detected in my testing.

**Comment by fabrixx** [comment]
Same problem for me in v2.4 also with low res profiles (16Gb ram core i7 preview work only 3 seconds, after is slow and lagging)

**Comment by N3WWN** [comment]
Check out the discussion, and particularly what works for me, here: https://github.com/OpenShot/openshot-qt/issues/960#issuecomment-337678019

In short, reducing the quality and resolution of the preview cache may help...

**Comment by fabrixx** [comment]
I setted resolution 640px and at minimal settings, but ram go at 90% of use after 4-5 sec
With only mp4 work well, i notice that have this problem  with .mts clips.
I switched to kdenlive for now waiting for a solution.

**Comment by N3WWN** [comment]
@fabrixx Instead of changing the resolution of the project, the discussion in 960 is about changing the preview cache settings.  

I am using .mts clips, also, but I convert them to .mp4 with ffmpeg at the command line before importing into OpenShot (I do that to gain video stabilization and force integer frame rates, but you can just convert them).

**Comment by fabrixx** [comment]
There must be something weird. After completing my project with kdenlive I read your cache response, I wanted to test. I've taken 15 .mts clips and some .mp4 clips but the problem does not reappear. I suspect that the problem is when I load in the project a large number of clips as I did. At the moment i can not cache verification as i should replay more than 200 clips download them on the desktop and import them but suspect that the bug has a very high number of imported clips..

**Comment by fabrixx** [comment]
ok, after some test setting quality to 40 is only way for me for 60 fps (extreme pixellated)

**Comment by rcwtech** [comment]
I have the solution for this issue. 

The memory leaks are caused by the preview needing RAM to cache, yet not having the ability to due to default settings. 

Go to edit -> preferences -> Cache -> Cache Limit (MB) **Default Set to 250MB - THIS IS THE CAUSE OF LEAKS

I set this to 1000, which works perfectly. You could go higher if need be.

**Comment by rcwtech** [comment]
Also, set video quality to 80 or so and it should be enough to preview and will have less impact on preview.
