### ISSUE TITLE
Generic icon in Choose Profile and Preferences windows

### ISSUE THREAD

**Issue by scootergrisen** [OpenShot/openshot-qt#4285]
OpenShot 2.5.1-dev3
Windows 7

The icon for the Choose dialog window is generic.
Same for Preferences window.

![billede](https://user-images.githubusercontent.com/1836590/127382712-575bdf15-694e-4f15-a455-5bfae0d6e1f5.png)

The icon for e.g. Export Video dialog is the OpenShot icon.
![billede](https://user-images.githubusercontent.com/1836590/127382894-cd9108e1-5555-45b2-a736-7103cfae619f.png)

**Comment by scootergrisen** [comment]
Backup Recovered dialog (seen after OpenShot crashes and Openshot is opened again) also have generic icon.
This happened in OpenShot 2.6.0 release candidate build date 2021-08-19 21:04
![billede](https://user-images.githubusercontent.com/1836590/130373074-3ad52e88-4254-4ded-891a-c5f03649ac82.png)

**Comment by ferdnyc** [comment]
@scootergrisen 

Hmm. The difference is most likely due to the fact that the Export window is created from a `.ui` file that contains a `<property name="windowIcon">` definition.

Whereas the profile selector is built from a UI file _without_ a `<property name="windowIcon">`.

The recovery dialog, that's just a dialog launched from the code with no UI file.

I've just submitted #4460 which makes sure that all `.ui` files contain a `windowIcon` property, and sets the parent on that `QMessageBox()` that shows the backup recovery message.

Hopefully that'll solve the problems. Parenting the child windows (like Export, Preferences, etc.) would normally be the way this is done, but that causes issues on Linux so we've removed those parent settings. That's probably why this came up.
