### ISSUE TITLE
Seriously slow animated title [ Blender 2.76]

### ISSUE THREAD

**Issue by mikobuntu** [OpenShot/openshot-qt#429]
I can remember from previous versions that rendering an animated title would only take a few seconds in older versions of OpenShot compared to OpenShot version 2.1.0 | Blender 2.76 , where a basic exploding text at x2 is going to take hours to render. If needed I can post my hardware details etc, 

:)

**Comment by jonoomph** [comment]
Well, I wish that were true, but Blender controls the speed of rendering not OpenShot, and it's always been painfully slow on the more complex animations, like exploding. The simpler animations are much faster though. Thanks!

**Comment by littlefico** [comment]
i'd like to confirm @mikobuntu issue.
i tested it with the simplest title i've found. it takes about 0,5 - 1 sec/frame at 150 or 250 frames. means it would need over 2 minutes for a simple title.
is this normal?
i also noticed that OS won't recognize my graphics card. (i have a intel nuc hades canyon with a dedicated rx vega 4GB graphics card) does that have something to do with it?

**Comment by ferdnyc** [comment]
@littlefico That's not only normal, it's fairly quick. It takes my system tens of minutes for some of the more complex titles, where render throughput on the more complex frames drops to 20-30 seconds _per_ frame.

As far as acceleration, OpenShot doesn't need to recognize your GPU for it to be used when rendering animations, it  just has to be supported by Blender. If it is, and you check the option to enable Blender GPU (at the bottom of Preferences > Performance), OpenShot will insert code that _should_ activate Blender's GPU rendering engine. I don't know whether that's been tested with your GPU, so I can't say whether it _works_, but I'm hopeful it does. 

The caveat, though, regarding Blender's GPU rendering is that it relies on the GPU's 3D modeling acceleration, not its video-processing acceleration. So on some cards not designed for gaming (like my own Nvidia GT 710), Blender's GPU rendering can actually be slower than rendering on the CPU, even though the card does provide nice speedups for video encoding.

Your card, however, _sounds_ like it should provide some nice speedups for Blender rendering. (Which you might already be seeing, if you can render animation frames in under a second.) I've only personally tested Blender's GPU acceleration with my Nvidia card. In my case it involves Blender compiling a CUDA rendering kernel with Nvidia's `nvcc` compiler, then using the kernel to render on the GPU. Their solution for AMD cards would have to be something different, but I assume they probably have one. That's all dependent on the Blender side, though.

If you find that your GPU is not being used even though it's enabled, though, a session log from OpenShot that includes the Blender output might be informative. (You'll want to run from a recent Daily Build — https://openshot.org/download/, click "Daily Builds" — for that.) Really, though, first step is ensuring that Blender is able to render on the GPU at all, something that's probably more easily tested from the Blender interface than from within OpenShot. Once that's definitely working _in Blender_, then we can try to debug the process of activating it from OpenShot.

**Comment by ferdnyc** [comment]
If you find that getting good performance out of Blender requires using [AMD's ProRender Blender module](https://www.amd.com/en/technologies/radeon-prorender-blender), our current code almost certainly _won't_ work to activate **that** renderer. Mostly because I don't know what's involved in that, and have no access to an AMD GPU or a system that supports ProRender where I could develop support for it.

But if you get ProRender working in Blender, and are interested in providing testing feedback, I'd love to work on adding support to OpenShot as well.

**Comment by ferdnyc** [comment]
Hmm, from reading the [latest ProRender release notes](https://www.amd.com/en/support/kb/release-notes/rn-prorender-blender-v2-3-blender-2-80-2-81-2-82), it seems AMD have changed their installer so that it no longer requires a compatible GPU just to install the module. That would make it a lot easier to work on supporting it from OpenShot. Even if I can't actually use ProRender for rendering, I could hopefully at least test our activation code if I install it on my system. (Maybe. They also only officially support Ubuntu LTS releases, and I'm on Fedora 31. So, it's anyone's guess whether I'd actually be able to install ProRender.)

**Comment by ferdnyc** [comment]
It took some forcing, because their installer script is stupid and tries to run `dpkg` and `apt-get` commands to install dependencies before it'll install the plugin, but I convinced ProRender to install on Fedora and at least render using my CPU.

Continued, if at all, in #2812 where the original GPU support additions were discussed.
