### ISSUE TITLE
__pycache__ folders with pyc files remains after uninstall.

### ISSUE THREAD

**Issue by scootergrisen** [OpenShot/openshot-qt#4299]
OpenShot-v2.5.1-dev3-daily-7884-8e062b8e-c31fac5e-x86_64.exe
Windows 7

If i install and uninstall OpenShot there will remain some folders called __pycache__ with pyc files inside.
So perhaps they should be included in the uninstall so they are removed.

These are the folders/files that remain after uninstall:

    classes\exporters\__pycache__
    classes\exporters\__pycache__\edl.cpython-38.pyc
    classes\exporters\__pycache__\final_cut_pro.cpython-38.pyc
    classes\exporters\__pycache__\__init__.cpython-38.pyc

    classes\importers\__pycache__
    classes\importers\__pycache__\edl.cpython-38.pyc
    classes\importers\__pycache__\final_cut_pro.cpython-38.pyc
    classes\importers\__pycache__\__init__.cpython-38.pyc

    classes\__pycache__
    classes\__pycache__\app.cpython-38.pyc
    classes\__pycache__\assets.cpython-38.pyc
    classes\__pycache__\effect_init.cpython-38.pyc
    classes\__pycache__\exceptions.cpython-38.pyc
    classes\__pycache__\image_types.cpython-38.pyc
    classes\__pycache__\info.cpython-38.pyc
    classes\__pycache__\json_data.cpython-38.pyc
    classes\__pycache__\keyframe_scaler.cpython-38.pyc
    classes\__pycache__\language.cpython-38.pyc
    classes\__pycache__\logger.cpython-38.pyc
    classes\__pycache__\logger_libopenshot.cpython-38.pyc
    classes\__pycache__\metrics.cpython-38.pyc
    classes\__pycache__\openshot_rc.cpython-38.pyc
    classes\__pycache__\project_data.cpython-38.pyc
    classes\__pycache__\qt_types.cpython-38.pyc
    classes\__pycache__\query.cpython-38.pyc
    classes\__pycache__\sentry.cpython-38.pyc
    classes\__pycache__\settings.cpython-38.pyc
    classes\__pycache__\thumbnail.cpython-38.pyc
    classes\__pycache__\timeline.cpython-38.pyc
    classes\__pycache__\time_parts.cpython-38.pyc
    classes\__pycache__\ui_util.cpython-38.pyc
    classes\__pycache__\updates.cpython-38.pyc
    classes\__pycache__\version.cpython-38.pyc
    classes\__pycache__\waveform.cpython-38.pyc
    classes\__pycache__\__init__.cpython-38.pyc

    language\__pycache__
    language\__pycache__\openshot_lang.cpython-38.pyc
    language\__pycache__\__init__.cpython-38.pyc

    lib\zmq\backend\cython\__pycache__
    lib\zmq\backend\cython\__pycache__\__init__.cpython-38.pyc

    lib\zmq\backend\__pycache__
    lib\zmq\backend\__pycache__\select.cpython-38.pyc
    lib\zmq\backend\__pycache__\__init__.cpython-38.pyc

    lib\zmq\sugar\__pycache__
    lib\zmq\sugar\__pycache__\attrsettr.cpython-38.pyc
    lib\zmq\sugar\__pycache__\constants.cpython-38.pyc
    lib\zmq\sugar\__pycache__\context.cpython-38.pyc
    lib\zmq\sugar\__pycache__\frame.cpython-38.pyc
    lib\zmq\sugar\__pycache__\poll.cpython-38.pyc
    lib\zmq\sugar\__pycache__\socket.cpython-38.pyc
    lib\zmq\sugar\__pycache__\stopwatch.cpython-38.pyc
    lib\zmq\sugar\__pycache__\tracker.cpython-38.pyc
    lib\zmq\sugar\__pycache__\version.cpython-38.pyc
    lib\zmq\sugar\__pycache__\__init__.cpython-38.pyc

    lib\zmq\utils\__pycache__
    lib\zmq\utils\__pycache__\constant_names.cpython-38.pyc
    lib\zmq\utils\__pycache__\jsonapi.cpython-38.pyc
    lib\zmq\utils\__pycache__\strtypes.cpython-38.pyc
    lib\zmq\utils\__pycache__\__init__.cpython-38.pyc

    lib\zmq\__pycache__
    lib\zmq\__pycache__\error.cpython-38.pyc
    lib\zmq\__pycache__\__init__.cpython-38.pyc

    windows\models\__pycache__
    windows\models\__pycache__\effects_model.cpython-38.pyc
    windows\models\__pycache__\emoji_model.cpython-38.pyc
    windows\models\__pycache__\files_model.cpython-38.pyc
    windows\models\__pycache__\properties_model.cpython-38.pyc
    windows\models\__pycache__\transition_model.cpython-38.pyc
    windows\models\__pycache__\__init__.cpython-38.pyc

    windows\views\webview_backend\__pycache__
    windows\views\webview_backend\__pycache__\webengine.cpython-38.pyc
    windows\views\webview_backend\__pycache__\webkit.cpython-38.pyc
    windows\views\webview_backend\__pycache__\__init__.cpython-38.pyc

    windows\views\__pycache__
    windows\views\__pycache__\effects_listview.cpython-38.pyc
    windows\views\__pycache__\effects_treeview.cpython-38.pyc
    windows\views\__pycache__\emojis_listview.cpython-38.pyc
    windows\views\__pycache__\files_listview.cpython-38.pyc
    windows\views\__pycache__\files_treeview.cpython-38.pyc
    windows\views\__pycache__\find_file.cpython-38.pyc
    windows\views\__pycache__\properties_tableview.cpython-38.pyc
    windows\views\__pycache__\transitions_listview.cpython-38.pyc
    windows\views\__pycache__\transitions_treeview.cpython-38.pyc
    windows\views\__pycache__\tutorial.cpython-38.pyc
    windows\views\__pycache__\webview.cpython-38.pyc
    windows\views\__pycache__\zoom_slider.cpython-38.pyc
    windows\views\__pycache__\__init__.cpython-38.pyc

    windows\__pycache__
    windows\__pycache__\color_picker.cpython-38.pyc
    windows\__pycache__\main_window.cpython-38.pyc
    windows\__pycache__\preferences.cpython-38.pyc
    windows\__pycache__\preview_thread.cpython-38.pyc
    windows\__pycache__\video_widget.cpython-38.pyc
    windows\__pycache__\__init__.cpython-38.pyc

**Comment by ferdnyc** [comment]
It's writing those into the _application_ directory!?!! I'm surprised it would be able to!

(You're not running OpenShot as an Administrator, are you? You should not.)

I guess if it's somehow able to create cache files in the application space, then yeah we need to clean them up. I'm just wondering how easy it will be to convince InnoSetup's uninstall tool to do that. (Without having to resort to Pascal coding, because personally I'd rather gnaw off my own foot than re-learn Pascal.)

But if it's only happening because OpenShot is running with elevated permissions that allow it to write to that directory, then it's **#NotABug** because we don't support running it that way.

**Comment by scootergrisen** [comment]
It's inside "C:\Program Files\OpenShot Video Editor\".

Seems like the __pycache__ folders is only created when OpenShot is launched.
If i delete "C:\Program Files\OpenShot Video Editor\" and install OpenShot without launching OpenShot it seems the __pycache__ folders are not there... well most.

Standard user is not allowed to install and uninstall OpenShot.
Switched the user from standard user to administrator account type and i can install and it seems to be the same problem.

**Comment by ferdnyc** [comment]
> Seems like the `__pycache__` folders is only created when OpenShot is launched.

Well, yeah, that's definitely right, those are created by Python when it byte-compiles sources before running them.

> If i delete "C:\Program Files\OpenShot Video Editor" and install OpenShot without launching OpenShot it seems the `__pycache__` folders are not there... well most.

If you then run OpenShot from your regular user account, does it still create the `__pycache__` folders?

It sounds like what might be happening is, when the installer launches OpenShot at the end of the install, it's doing so without dropping its Administrator privileges (as you say, they're required in order to **perform** the actual install) and therefore the first run of OpenShot has permission it shouldn't have that lets it write to the application directory.

Hopefully, if OpenShot is launched **not** by the installer, but simply from your user account, it won't have that same permission and won't be able to write to the application dir.

And then double-hopefully, we can find some way to ensure that the installer's post-install launch option first releases its Administrator rights, so that it doesn't accidentally run OpenShot elevated. (In exactly the way we've been saying it _shouldn't_ be run.)

\*fistshake\* InnoSetup!!!

**Comment by ferdnyc** [comment]
Hrrm. Interesting. It _shoud_ be the default, according to their docs, that the installer drops permissions (reverts to the original identity, before UAC elevation) for a `postinstall` launch like we're doing. From the [Inno Setup docs](https://jrsoftware.org/ishelp/topic_runsection.htm):

> #### `runasoriginaluser`
> Valid only in a `[Run]` section. If this flag is specified, the spawned process will execute with the (normally non-elevated) credentials of the user that started Setup initially (i.e., the "pre-UAC dialog" credentials).
> 
> This is the default behavior when the `postinstall` flag is used.
> 
> If a user launches Setup by right-clicking its EXE file and selecting "Run as administrator", then this flag, unfortunately, will have no effect, because Setup has no opportunity to run any code with the original user credentials. The same is true if Setup is launched from an already-elevated process. Note, however, that this is not an Inno Setup-specific limitation; Windows Installer-based installers cannot return to the original user credentials either in such cases.
> 
> This flag cannot be combined with the `runascurrentuser` flag.

So, from what I'm reading there...
1. The installer should already be dropping elevated permissions, if possible.
2. Launching it _explicitly_ with Administrator privileges (as opposed to letting it make a UAC request) will break that functionality
3. There's nothing we can do about that.
4. Except _maybe_ (this is me spitballing) find some way to detect when we're stuck in Administrator privileges without initial user privileges we can revert to. And then just disable the "Launch OpenShot" checkbox on the last installer page, in that scenario.

That should hopefully prevent accidental Admin-privileges launches.

(Heck, I suppose we could even do what some apps do, and refuse to start up if we detect we're being run with elevated privileges. But that's pointless for **this** situation since it wouldn't prevent the `__pycache__` dirs, they'll already have been created by the time that logic kicks in.)

**Comment by scootergrisen** [comment]
I thought i tested it before but now it does not appear the __pycache__ folders are created as a normal user.
