### ISSUE TITLE
Make marker apperance consistent on timeline

### ISSUE THREAD

**Issue by scootergrisen** [OpenShot/openshot-qt#4300]
OpenShot-v2.5.1-dev3-daily-7884-8e062b8e-c31fac5e-x86_64.exe
Windows 7

Seems the apperance of the markers/key points are no consistent.
The button above the timeline shows a green arrow pointing down but on the timeline the marker/key point will appear as blue (look like the playhead but up-side down and smaller) and on the zoom area it is a blue line.

I would suggest using the same color/apperance for the markers/key points. E.g. green arrow pointing down since the playhead is using blue.

![billede](https://user-images.githubusercontent.com/1836590/128524677-55a84ea4-6986-4ab7-a945-2fc25b03a0eb.png)

Perhaps something like this.
![billede](https://user-images.githubusercontent.com/1836590/128526926-4721c078-db27-4664-873b-9fc1b9cf4bae.png)

**Comment by ferdnyc** [comment]
Yeah, that seems fair. TBH I've never personally been crazy about that blue teardrop, and it would seem at some point the markers used to be green triangles (or why would that be the icon?), plus I've long argued that blue is **crazy** overused in the current interface. Green is, except for the keyframe markings on Timeline items, totally _unused_ in the current interface, so it makes a good choice to go with the existing red, yellow, and blue elements/state-indicators.

My assumption is that the markers were changed to point **upwards** because that makes it easiest to see exactly where on the time ruler the marker has been placed. There's some validity to that, it does seem like the markers should point **towards** the ruler marks rather than away from them.

So that leaves us with two choices:
1. Flip the marker icon, and the marker triangles themselves, upside down.
2. Relocate the markers to appear **above** the ruler instead of beneath it.

I see potential positives and negatives to both.

Oh, and technically there's a third option:

3. Replace the green-triangle marker icon with a blue-teardrop version, instead.

I'm not crazy about that — because like I said, that teardrop, _meh_ — but it is certainly the **easiest** way to address the issue.

**Comment by ferdnyc** [comment]
I'm debating whether I want to leave this labeled "Bug", since it's not _technically_ a bug. The interface is working as designed. Its design is inconsistent. But it's been inconsistent in exactly the same way for at least 4 years now, which in its own way is a certain form of consistency.

**Comment by scootergrisen** [comment]
Also the playhead apperance in red apart from the blue drop on the timeline.
I so guess the timeline blue drop should be red.

For some reason there is both the blue drop and a small red circle at the playhead.
Seems like one of them would be enough.

Well i don't really use the software but seem logical to me that playhead would appear red everywhere and markers would appear green everywhere.

**Comment by ferdnyc** [comment]
Oh, I fixed this in #4466 , I  just forgot to tag it. The markers have a new SVG-based image, and there's a new "Add Marker" toolbar icon based on it.
