### ISSUE TITLE
Ctrl + Left Click does not deselect an item in track bar

### ISSUE THREAD

**Issue by sahin52** [OpenShot/openshot-qt#4310]
Steps: 
1. Add a video file to one of the tracks
2. Cut the video in anywhere you want
3. Select both by clicking on them while holding ctrl
4. Click one of them while holding ctrl, the selected clip does not get deselected.

Expected: 
The selected portion must be deselected, I can't select all files and move them because I can't deselect one. I have to select everything one by one.

Openshot Version 2.4.3  
on Ubuntu 20.04

**Comment by JacksonRG** [comment]
Could you try the most [recent version](https://www.openshot.org/download/) of openshot? This issue may have already been patched.

**Comment by JacksonRG** [comment]
Ok. After some quick testing, it works if your computer uses webkit rather than webengine. I'll look into making sure both work correctly

**Comment by sahin52** [comment]
This issue is on Ubuntu 18.04, sorry for not having had mentioned it.

**Comment by JacksonRG** [comment]
Good to know. The version on apt is the last full release of openshot. Countless bug fixes and improvements have been made since then, and we are *very* near a new release. Until then you can check out our daily builds [here](https://www.openshot.org/download/), as my testing (on 20.04) seems to suggest that this issue has been fixed.

If it still happens on the daily build, just `@` me, and I'll investigate further.

**Comment by speedytechdev** [comment]
Hi @sahin52 , Just checking in. Has your issue been fixed?

**Comment by Colorjet3** [comment]
It is working in v3.0.0.
