### ISSUE TITLE
Left side of exported video file is blinking 

### ISSUE THREAD

**Issue by suvashsumon** [OpenShot/openshot-qt#4336]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 2.4.3
- libopenshot Version:  0.2.2
- Platform: Linux-5.11.0-25-generic-x86_64-with-glibc2.29
- Processor: x86_64
- Machine: x86_64
- Python version: 3.8.10
- Qt5 version: 5.12.8
- PyQt5 version: 5.14.1
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: en_US.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.5.1-dev3-daily-8019-d246964f-af98548d-x86_64.AppImage

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/w4aolgb2zcqmrv776quekp7aiq7lh3ur/openshot-qt.zip) (12 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by speedytechdev** [comment]
Hi @suvashsumon , Have you tried our [daily build](https://www.openshot.org/download/) . If the issue still shows up after that our team will happily fix the issue for you. If you could also provide more detail about the issue we might be able to help. Could you please include the following information:

- [ ] Steps to reproduce the behaviour - What steps must our dev team take to find the bug again
- [ ] Expected behaviour - What is meant to happen with the software normally
- [ ] Screenshots if it's a UI/ Visual issue - Pictures 

Thanks, Speedytechdev
