### ISSUE TITLE
Attempting to use QSV encoder results in a window saying "Could not open video codec"

### ISSUE THREAD

**Issue by EverettAviation** [OpenShot/openshot-qt#4438]
I'm completely unable to use the QSV encoder on Windows 10 in OS v2.6.1 with an Intel i5-11600K CPU.

Steps to reproduce the bug
1. Click the video export button.
2. Select QSV for the encoder.
3. Click "Export."

**System Details:**
- OpenShot v2.6.1
- Windows 10
- CPU: Intel i5-11600K
- Motherboard: ASUS Z590 Plus Wifi
- GPU: Nvidia RTX 3060 Ti Founder's Edition

**Comment by xuejianxianzun** [comment]
me too

**Comment by JacksonRG** [comment]
Sorry, which export settings are causing you this problem? I'm not seeing QSV in the options, but may be missing it.

**Comment by xuejianxianzun** [comment]
> Sorry, which export settings are causing you this problem? I'm not seeing QSV in the options, but may be missing it.

![2022-02-15_083235.png](https://s2.loli.net/2022/02/15/mjrfgXUSqRbE5lV.png)
![2022-02-15_083308.png](https://s2.loli.net/2022/02/15/jDVcvuBXEzs2wae.png)

**Comment by mdrijwan123** [comment]
Hi, I am getting this issue while exporting the video using GPU hardware acceleration rather than CPU. Please help if there is any solution available. @JacksonRG 
I am using
OS: Windows 10
Open shot version: 3.0.0

![image](https://user-images.githubusercontent.com/35109373/218275100-e95ef284-5abc-468f-b884-ffc729880427.png)

**Comment by Colorjet3** [comment]
Hello @mdrijwan123 Here is some information from the development team regarding Hardware Acceleration in general:

• Hardware Acceleration in Windows is supported but limited. Those new settings that you see in Edit | Performance tab are new, experimental, and not fully baked (this is mainly for v3.0.0).
• Hardware acceleration is still experimental in OpenShot Video Editor.
• NVIDIA NVENC acceleration is only available in Linux operating systems.
• OpenShot v2.6.0 and later includes Intel® Quick Sync Video encoding in Windows
operating systems. If you have a CPU that supports Intel®QSV encoding, you can use the encoder by selecting the ( QSV) MP4 (h.264 qsv) Target on the Export Video window. You do not have to change the Preferences window to use the Intel® QSV encoder.
• Hardware acceleration in OpenShot requires using the proprietary drivers from the distribution package manager instead of the NVIDIA drivers. You cannot use the Nouveau, Xorg, or open-source drivers.
• AMD is not yet supported.

For QSV MP4 (h.264qsv) export please ensure that your CPU supports the Intel QSV encoding and that it is enabled.

By the way, you made this same report in Issue number 4812 so I am going to not respond to that one.
