### ISSUE TITLE
Video Preview

### ISSUE THREAD

**Issue by Mradul183** [OpenShot/openshot-qt#4447]
**Describe the bug**
I was trying to edit my video so as to know how the video is coming together I hit the spacebar to see the Video Preview but the preview speed is about one frame per second. With the dropped down speed the audio of the clip also shuts, meaning I can't know anything about the project without exporting it.

**Steps to reproduce the behavior:**
Hit the play button or spacebar

**Expected behavior**
I expected that the video preview runs at the normal speed or maybe perhaps a new option would be introduced to control the speed of the preview.

**System Details**
- OpenShot Version: 2.6.1-dev
- libopenshot Version:  0.2.7-dev
- Platform: Windows-7-6.1.7601-SP1
- Processor: x86 Family 6 Model 23 Stepping 10, GenuineIntel
- Machine: x86
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Not able to verify issue still exists in daily build

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/sgyss6pdxyf6xqmc9209jh4xv2hjcfew/openshot-qt.zip) (22 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by bernard01** [comment]
I have the same issue with 2.6.1 release on Windows 7 with system requirements met. I initially filed https://github.com/OpenShot/openshot-qt/issues/4464 because I could not hear any audio because my MP3 file does not have video only audio. Then I imported an mp4 video file and I see it runs at 1 frame per second (perhaps). Of course at this speed, audio is not defined. It counts like 00:00:00,13 ... 00:00:00,30 and then jumps from that last 2 digits 30 to 00:00:01,00 so on with the last digit changing at a rate of 1 per second. I don't know what the fraction of it is, looks like 1/30 of a second which runs much slower than that, actually slowing down as it goes.
Then I was thinking that the software needs one or more built-in simple project(s) that should be useful as a health check, especially for novice users, and a factory reset function perhaps because I cannot see whether there is any of the many settings that could be wrong and is perhaps causing this.. Something big is really wrong here at my end, there needs to be some "Fail fast" approach to this. Perhaps there is really a system issue not with the software itself, and the software should report it.

**Comment by DanPinGF** [comment]
@JacksonRG - Looks like a duplicate of #4375.
