### ISSUE TITLE
List of markers or colors for markers

### ISSUE THREAD

**Issue by murpholinox** [OpenShot/openshot-qt#4453]
It would be nice to have information on the markers. I am using markers to know where to cut, where I need to add an image, where to add a correction... I end with a lot of markers, so I have to review them to remember what I need to do. So it would be nice to have a list of all the markers with some text of why do I placed that marker there (text, I think, is more useful, but colors can do the trick. For example: blue, red, green and yellow markers mean cut-marker, add-an-image-marker, add-a-correction-marker, etc. (In that case, it would be nice to customize your markers))

PS I love openshot. Is just what I need to edit my online courses.

**Comment by ferdnyc** [comment]
@murpholinox 

Most of what you bring up is _very_ doable, if someone wishes to tackle it.<sup>1</sup> 

### Multiple colors

Storing marker _colors_, at least, would be a breeze.

#### Backend

When markers are stored in the project data, an image filename is stored with the position. Today, that image filename is always `blue.png`, which corresponds to the file `timeline/media/images/markers/blue.png` in the OpenShot install. But there are actually four other files _**already in there**_, named `green.png`, `purple.png`, `red.png`, and `yellow.png`:

![green](https://user-images.githubusercontent.com/538020/134804070-6d849356-4978-4a1f-8fb1-305868ad819e.png)  ![purple](https://user-images.githubusercontent.com/538020/134804073-bedfbd2f-7ef7-4260-a2de-0cbd17148630.png)  ![red](https://user-images.githubusercontent.com/538020/134804078-3541519f-632a-43b6-93ba-7d46cb02dd0a.png)  ![yellow](https://user-images.githubusercontent.com/538020/134804080-72cdcb70-168e-44a8-8d95-d551b66cb4a2.png)

Markers were always meant to support multiple colors, the frontend part of the functionality was just never implemented. But the support is all there on the backend.

#### Frontend

The frontend, though ­— the user interface to managing and interacting with markers — is where things get a little unclear, at least for me. (And I suspect for whoever made the original decision _not_ to implement multiple marker colors, as well.)

At the most basic level, since we already have a marker context menu, in theory that could be extended to allow setting marker color. Like, they're always created blue, but then you can change them individually afterwards.

That'd be a _possibility_, but honestly that idea kind of sucks IMHO. It sounds way too tedious to customize each _individual_ marker after-the-fact. For this to be useful, I think you'd have to be able to _either_:
1. Create markers in any of N colors directly, somehow... like maybe through multiple keyboard shortcuts, one per color? (Not loving that.)
2. Otherwise, you'd want to be able to select a "current marker color", where all new markers created from that point on have that color, until you change it again.

I also think that, if it were the second option, changing the selected color would have to be an immediate, part-of-the-workflow sort of action, something quick. A preferences item for "marker color" wouldn't cut it, I don't think. Going into the settings is way too disruptive to the editing/authoring process. So that means the marker-color selection would have to be part of the main OpenShot interface, in a way that's convenient... but not so obtrusive that it distracts/annoys people who have no interest in using it.

Coming up with an interface that strikes the right balance is a tricky thing. Any thoughts or ideas you have on it would be great to hear: How do _you_ envision working with multi-color markers, as part of your normal OpenShot user patterns?

### Text annotations

On the other things you mentioned... well, I'm going to skip over text annotations for markers right now, because I think that's a significantly more involved request. I figure it makes sense to start with the low-hanging fruit, and work upwards from there.

### Marker list

The next thing you mentioned, a list of all the project markers — for the most part, again we're back to a fairly easy task for some developer who wanted to take it on. Off the top of my head, it seems like the simplest approach would be to add a new dock widget. (That's how all of the resizable/rearrangeable/movable components of the existing UI are built, from the video preview to the timeline to the Properties list. Docks are great because you can organize the interface however you like, and any components you're not going to be using can be hidden so they're totally out of the way.)

A table like the Properties list that just displayed the position of each marker on the Timeline in standard `HH:MM:SS,FF` format would be a breeze. Plus, what that gives you even more than just the list itself is a new chunk of UI that can then be extended with other features, since now there's more space to fit them in. So with a working marker list dock:
1. Being able to set each marker's color from there seems like an obvious next step, and certainly more convenient than the context menu
2. If there were going to be a current-marker-color selection in the UI, making it part of the marker dock interface seems like a good compromise, and helps keep the rest of the main UI uncluttered.
3. If text annotations were going to be added to markers at any point in the future, I think editing them from a marker list in a dock widget would be _far_ more convenient than trying to accommodate that kind of functionality directly from the Timeline itself.
4. The ability to reposition, delete, and seek the playhead directly to any individual marker on the list all seem like fairly obvious enhancements, none of which should be especially difficult.

So that's where things stand. If anyone does feel like tackling this one, I'll be happy to give feedback and review code, though you may have to be a little patient. There are no deadlines here, which on the plus side means you can move at whatever pace works for you and take on as much or as little as you want.

##### Notes

1. (Please don't take these comments as me committing to work on this. I'm afraid I won't be free to do that any time soon, at least, as much as I'd like to. But I figured I'll leave this information here, in the hopes that maybe it will be enough to motivate an interested coder to tackle it... for someone looking to make a first contribution to OpenShot or to open-source in general, this would be a pretty ideal first project.)
