### ISSUE TITLE
Importing Mp4's slow, no feedback.

### ISSUE THREAD

**Issue by JupiterSnarl** [OpenShot/openshot-qt#4459]
I thought I was suffering from the ubiquitous old "importing mp4 freezes OpenShot" bug but it turns out it was just very slow. I am importing a 1.4Gb file, but it should not take 5+ minutes to import to a video editing program, and the program should not become "not responding" in windows. Video editing generally involves big media files like that... I switched away to browser to search for solutions and research and discovered on returning several minutes later that the file actually did import. 

A progress bar would help to communicate that the program is actually working on the import, but I maintain that it shouldn't take that long and freeze the program while it's working. In addition this entire experience repeats itself when trying to add clips to the timeline.

By comparison, Adobe Premier imports the same clip in about 5 seconds and has a progress bar, and has no delay when adding to the timeline.

OS: Windows 10
OpenShot Version: 2.6.1

Problem: OpenShot "freezes" while importing Mp4 files or adding clips to the timeline - with a rotating windows cursor and the program going "ghost" with "Not Responding", and the import is much too slow compared to most other programs. This happens both when "drag and drop" importing and using the "File>Import" option.

Expectation: OpenShot should not freeze up and become unresponsive during import. A progress bar or "importing" message should be displayed to let the user know it is working.

**Comment by ferdnyc** [comment]
Huh! I actually re-wrote the importing entirely for 2.5.0, and it's **muuuch** faster than it used to be. (But most of the slowness was due to time wasted on redundant operations occurring for each file, when opening multiple at once. Individual single file import wouldn't really have changed.)

Any remaining delays are likely to be libopenshot taking its time doing... whatever it's doing, to take so long. I'm surprised that would be an issue, but I admit I haven't ever tried with a 1+ gig video file. Neither my computer nor, I suspect, OpenShot is really up to that kind of task. If you have access to Premiere, it's likely a far better tool for that kind of heavy lifting.

**Comment by JupiterSnarl** [comment]
I have used Premiere for years, but I've also been trying to find something a bit more user friendly for years :D 
I find Premiere to be very tedious to use for most of my YouTube videos, so that's why I'm looking for something to edit quick videos together. OpenShot looks like it can do that, but the problem above made me go back to Premiere, unfortunately, because I had to get the video out :D 

If the program has to take a while to import, so be it, but I think a loading bar or other message would be a good band aid to let the user know the program hasn't *really* locked up and working on the task. I don't know if you can do that, or if it would take too much work, but hopefully you can look into it.
