### ISSUE TITLE
OpenShot instantly crashes when opened

### ISSUE THREAD

**Issue by MrITkid** [OpenShot/openshot-qt#4485]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**
1. Go to 'desktop'
2. Click on 'OpenShot'
3. See error

**Expected behavior**

It takes a bit to load and for a split second it shows a white screen and then closes 

**System Details**
- OpenShot Version: 2.6.1-dev
- libopenshot Version:  0.2.7-dev
- Platform: Windows-10-10.0.19041
- Processor: AMD64 Family 23 Model 17 Stepping 0, AuthenticAMD
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-8412-111026d8-73c519f0-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/7twr5l2oxqrlie6gldblrh7cc1qr4ron/openshot-qt.zip) (112 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/7twr5l2oxqrlie6gldblrh7cc1qr4ron/libopenshot.zip) (5 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Capturi de ecran** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.
              
![Screenshot_20211013-220706](https://user-images.githubusercontent.com/92473802/137197618-c0069aff-c19a-4f07-97fe-5f223da698a4.jpg)
 
![Screenshot_20211013-220710](https://user-images.githubusercontent.com/92473802/137197649-36ae937f-6523-4a83-a15a-6f84bcbcdd9d.jpg)

**Comment by gorbehnare** [comment]
This has been an issue since I have discovered this product 3 or 4 years ago. I have never actually managed to ever run this product. It does instantly crashes as soon as it is launched. I have tested this on several systems running Windows 10. I read some reviews on this product, and a bunch of articles mention it, so probably somebody can run this somewhere? but my impression is that this product is not well supported and maybe not intended for Windows 10. I ended up doing all my editing in Blender which can do almost everything, but not very friendly or easy to use.

Edit: I just downloaded the 2.6.1_x86 version (not x86_64 version) and it runs, for the first time ever! wow... it looks like the 64bit version is the one crashing. 
Edit 2: switching from thumbnail to waveform in the track view takes about 5min for a 1min clip... I'm 5min into using this, and I can see that this probably going to give me grief in the long run. I get the open-source and free nature of this, but unfortunately this is probably not worth it. Maybe ok for a hobby, but not production ready.
