### ISSUE TITLE
Temporarily hide a track

### ISSUE THREAD

**Issue by Symbai** [OpenShot/openshot-qt#449]
In other video editors we can hide a track temporarily from the preview. Or we can "solo" a track so only this track appears in the preview.

This is very useful when cutting and using several tracks as otherwise I have to move a track outside of all others just to find the location where to cut (or move it at the top of alll tracks).

**Comment by JtLively** [comment]
You can hide a track by selecting the **eye** icon on the left side of the timeline. For a specific section within the timeline, select **eye** icon on it underneath its individual title name or within its properties.

You can solo a track by right-clicking it from the timeline, selecting _Properties_, and the _Play_ button on the left.

**Comment by dvogel** [comment]
@JtLively is this enhancement in 2.4.3? I don't see any eye icon [in the UI when I run it on my machine](https://i.imgur.com/yHccFZr.png). I also don't see an eye icon in [this screenshot from the documentation](https://www.openshot.org/static/files/user-guide/_images/tracks.jpg). When I right click a track, no menu appears. If I right click on a clip I do get a menu with a _Properties_ option but there is no _Play_ button. In that properties area I can either set _Enable Video_ to zero or I can set _Alpha_ to zero. Both settings only affect that clip and not the entire track. That can get pretty tedious with a track that has a few dozen cuts. Is there a way to mute or solo an entire track? When I search the repo for "hide" or "eye" or "solo" I don't get many obvious results. What am I misunderstanding?

**Comment by qlerebours** [comment]
I can't see it either.
@JtLively are we missing something ?

**Comment by ferdnyc** [comment]
@qlerebours @dvogel 

This feature is not currently part of OpenShot 2.x. @JtLively was describing features from the retired OpenShot 1.x interface/codebase.

**Comment by Innitinnuit** [comment]
Wow, someone suggested this essential and basic feature 3 years ago and it hasn't been implemented? What? Thank god for the new emojis though. We all needed that.

**Comment by yogifred** [comment]
Please re-add this feature!

**Comment by NathanChristie** [comment]
Amazed this still hasn't been implemented. This would be very useful.

**Comment by Colorjet3** [comment]
We hear you and it is in the queue.  Unfortunately no ETA!

**Comment by seanwang0209** [comment]
The eye button really useful.

**Comment by XavierBit** [comment]
Any progress on that topic? I mean, that's really an essential function....

**Comment by Colorjet3** [comment]
Not at this time, unfortunately!

**Comment by x59a** [comment]
One thing you can do to accomplish this:

- Select the **clip** in the track that you want to 'hide'
- In the properties window: 
  - Enable Audio -> Off
  - Enable Video -> Off

It's not ideal but can do the trick.

**Comment by Colorjet3** [comment]
This enhancement request is in the queue and approved to be worked on.  Unfortunately, volunteer developers are very limited (actually none at this time) leaving the lead developer doing all the work.

**Comment by rickeyfessler** [comment]
This feature would be very useful. And much needed

**Comment by ThomasMeister123** [comment]
Found this page by searching for exactly this feature. An now I see: Its gone?! ;(

Cant use OpenShot WITHOUT this feature. I copy little parts from the main video(track) into another track. Maybe three little parts in one row. Then I HIDE the maintrack (video+audio) and export the track with the little parts. Thats how I work with MoviePlus X6. So.... unfortunately no chance to switch to OpenShot ;(

**Comment by matbeedotcom** [comment]
> One thing you can do to accomplish this:
> 
> * Select the **clip** in the track that you want to 'hide'
> * In the properties window:
>   
>   * Enable Audio -> Off
>   * Enable Video -> Off
> 
> It's not ideal but can do the trick.

Thank you!

**Comment by Colorjet3** [comment]
I have assigned this to the lead developer.  This enhancement request is in the queue.  However, I would like to hear a bit more about how you see this working.  Here are a few thoughts/questions that I have:

1.  When I hide a track what do you expect to happen:
a.  Do you just want the track to be hidden but still active in the "Video Preview" window?  What I mean by this is that are you just thinking that you want to unclutter your timeline where you might have several active levels and you don't want to see a track or multiple tracks?

2.  Or, when you hide a Track do you expect that that specific Track is not longer active in the project.  Meaning any videos/audio, audio, and image files are not going to preview and/or render when Exported?

This can be problematic if you are working on a project that say two tracks are somehow integrated where an image file is used as Text to overlay a video file below it.  What happens if you hide a Track that contains the text but it also contained video/audio, audio only, and other image files?  Just curious about the expectations.

3.  The Tracker effect has a feature now (in v3.2.x) where you can Parent an image to the Tracker box.  That image clip must be on a track above the video clip that you have the Tracker effect applied to.  Now, this image file doesn't have to be exactly right above the video clip track and can be on a track that is sever tracks higher.  Still you may have other clips on that same track and if you hide it the Tracker effect may stop working that is applied on a lower track.

Any way, what I am hoping for here is that you guys start thinking about exactly what your expectations are.  Please articulate as clearly as possible and I can put your suggestion in the queue.  In the end the lead developer will review the enhancement request, look at the suggestions and then he will ultimately decide how to move forward.

OpenShot is going through some major redesign (UI, performance, bug fixes, enhancements) so be patient as this project team is very small and is very dependent on volunteer developers.  Things don't move too fast!!!!

**Comment by ThomasMeister123** [comment]
[2]! Maybe deaktivate VIDEO and AUDIO-Track seperatly (when splitted).

When I deaktivate a layer with text, then I also want, that this track is NOT exported. 

Actual example: I have a video track and a track with a logo that is displayed in the video (for publication on the Internet). First I export the video WITH a logo. Then I deactivate the track with the logo (eye symbol) and export it again WITHOUT the logo. Or I have different logos in multiple tracks. Then I can gradually export the videos by always activating ONE logo track and deactivating the rest.

**Comment by dvogel** [comment]
I was thinking of both, with some interaction:

* A: I would like to be able to mark a track as disabled/deactivated so that it does not show up in the preview or the final rendering. This is my primary concern and related to my actual work product.
* B: I would also like the ability to hide or drastically collapse tracks to a very narrow placeholder. This is a secondary concern related to my efficiency.
* C: Having disabled/deactivated tracks be hidden/collapsed by default with a toggle above the track are would make it the most useful.

I would use (A) to produce different variations of a video, such as one with and one without a commentary track. I would also use (A) to test different background audio tracks, importing them all into the project and togging one on at a time. In these cases I would use (C) to choose to have the deactivated track(s) shown/expanded.

I would use (B) to make it easier to visually align tracks against each other. I may have a mostly unimportant track way down the stack where I need a cut to line up with the primary track. Most of my work is between the primary track and a handful of others but then at the end of the project I need to re-align the cut I made earlier. Being able to hide/collapse all the tracks in between would help me quickly realign those cuts without having to reorganize them. I would also use (B) in the case above where I was trialing background audio tracks. Sometimes I get indecisive and I want to leave them all in the project in order to ask a collaborator for their input later but in the meantime I don't want them cluttering up my work so I would use (C) to hide/collapse them.

**Comment by ThePeach** [comment]
I agreed with what @ThomasMeister123 said: "Hiding" a track should be a quick way to remove a bunch of clips from both preview and export. 
I also agree that having collapsible tracks, regardless of whether they are active/hidden or not could be a really good addition, especially if you are working with loads of tracks. It might something entirely separate thou. 

Very much looking forward to having this feature back in. :+1: Thank you for taking a look at it!

**Comment by Colorjet3** [comment]
Thank you @ThePeach for the additional enhancement request.  I have link to this Git in the queue so when the time comes and the lead developer is reviewing this request he will see all these comments as well.

**Comment by asloan7** [comment]
Hiding and soloing tracks is incredibly useful! Can this be re-opened?

**Comment by Colorjet3** [comment]
It is still in the queue in "Approved" status in an internal queue that the lead developer works off of.  Being closed here does make a difference.  I did remove the "Stale" label as to avoid it being archived/deleted.
