### ISSUE TITLE
The whole program doesnt work

### ISSUE THREAD

**Issue by max246** [OpenShot/openshot-qt#450]
I tired to edit my two videos from Phantom 3 ( mov files ) on two different pc with the same version 2.2.0 and both of them made the software crash when encoding or even unstable when editing.

I wonder what kind of test you do to release a stable version. I ended up to use ffmpeg via command line to cut up the videos and encode into one. If I was able by hand why your software cant??? this is not the first bad exprience of this software. I had trust over the years because it was young but now you cant even convert a MOV file into a small file with selected traces?

If you want some funny output:

This when the software decided to hang there forever:

> [libx264 @ 0x4d62300] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 LZCNT
> [libx264 @ 0x4d62300] profile High, level 4.0
> [libx264 @ 0x4d62300] 264 - core 142 r2389 956c8d8 - H.264/MPEG-4 AVC codec - Copyleft 2003-2014 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=2 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=10 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=12 keyint_min=1 scenecut=40 intra_refresh=0 rc_lookahead=12 rc=cbr mbtree=1 bitrate=8000 ratetol=1.0 qcomp=0.60 qpmin=2 qpmax=30 qpstep=4 vbv_maxrate=8000 vbv_bufsize=1835 nal_hrd=none filler=0 ip_ratio=1.25 aq=1:1.00
> Killed

Here went it decided to encode for 10 seconds with 100 warning from x264 then hang there forever

> [libx264 @ 0x54fd3c0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 LZCNT
> [libx264 @ 0x54fd3c0] profile High, level 4.0
> [libx264 @ 0x54fd3c0] 264 - core 142 r2389 956c8d8 - H.264/MPEG-4 AVC codec - Copyleft 2003-2014 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=2 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=10 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=12 keyint_min=1 scenecut=40 intra_refresh=0 rc_lookahead=12 rc=cbr mbtree=1 bitrate=15000 ratetol=1.0 qcomp=0.60 qpmin=2 qpmax=30 qpstep=4 vbv_maxrate=15000 vbv_bufsize=1835 nal_hrd=none filler=0 ip_ratio=1.25 aq=1:1.00
> [libx264 @ 0x54fd3c0] VBV underflow (frame 0, -821828 bits)
> [libx264 @ 0x54fd3c0] VBV underflow (frame 12, -855592 bits)

The only method that worked was to encode at 360p...

Just test before release!!!!

**Comment by Kagetsuki** [comment]
You just pointed out why you're having issues and you didn't even realize it. Your raw footage doesn't have a good composition for editing. Other video editors will convert to an intermediary format upon importing, which is why their project files will usually be huge. OpenShot doesn't do this (though I personally think that some time in the future it should). In your case I'm guessing a lot of compression isn't completely linear in your source file, or there's a lot of skipping or a variable frame rate - all of these things make your file an awful source for editing.

Convert your video to a fixed-rate, low compression format using ffmpeg *before* you import it into OpenShot.

**Comment by jonoomph** [comment]
Not every video file works perfectly in OpenShot (of course), and if you have a good example video that breaks OpenShot, please feel free to share it here, and I'll take a look. OpenShot works great for hundreds of thousands of users, so I think you are overstating the problem a bit. 

We have recently made a ton of improvements for video freezing and crashes, and I would like to verify this issue still occurs with our latest daily build. Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. 

If the issue still occurs, please reopen this issue and attach log files (https://github.com/OpenShot/openshot-qt/blob/master/.github/CONTRIBUTING.md), and hopefully we'll be able to nail this down and fix it. Thanks!

**Comment by max246** [comment]
I have been trying your software over the last 3 years, every single time it crashed for simple things, dragging or else.
I am sorry, I believe on opensource but if you release a video teaser where you show THIS and THAT but to crop 2 videos, it just doesnt work. Well you have made something wrong.

I moved to lightworks which is 100% stable and not even a crash.

I hope you are going to invest on opensource beta tester.

**Comment by Kagetsuki** [comment]
@max246 I myself have had various issues with OpenShot but I've taken the time to work through them or to report and keep on issues. Replicability is vital in reproducing errors; and as for this issue it's impossible for anyone but you to reproduce or diagnose the issue. We don't have samples from your camera nor do we have specific details on your system. In order to diagnose the issue and provide a fix we need those things - and if you don't provide them we may never be able to provide a fix.

Also keep in mind that lightworks has commercial support, but as far as I know @jonoomph only has some minor crowd-funding which doesn't come close to what would be needed to support him for the amount of time he's put into this project.

**Comment by max246** [comment]
As said previously, i do like opensource and support them. But these were
simple tasks of having two video and cut in 4 pieces. Nothing hard or
difficult to replicate.

I ended up to use ffmpeg command line that took me a bit of time but didn't
crash 5 times in a row.

I am sorry but this software is not ready to be distributed public. I hope
he gets some help as said before i support opensource but if the software
is not able to cut videos is a very basic stage.

Lightwork might have commercial support but at least i can cut videos
without worry to have a crash.

Probably a report manager of crashes is needed to be implemented so tickets
can be more accurate.
