### ISSUE TITLE
Pointer handle tries to hide

### ISSUE THREAD

**Issue by P-Woods** [OpenShot/openshot-qt#453]
The handle to the pointer in the timeline is half hidden at time 00:00:00:01
This is inelegant!
Also the time at the start should be 00:00:00:00    "Shurely shum mishtake?"

**Comment by P-Woods** [comment]
![screenshot_2016-10-21_08-19-11](https://cloud.githubusercontent.com/assets/22316637/21571667/53808fc6-cec9-11e6-85bd-a10cc2822bff.png)

Using the appimage: "OpenShot-v2.2.0-x86_64.AppImage"

**Comment by P-Woods** [comment]
Please ignore the screenshot image above.

Here is the correct one (I hope.)

![openshotscreengrab](https://cloud.githubusercontent.com/assets/22316637/21571724/e3ee62ea-cec9-11e6-9221-05a100cb964e.png)

This is using the appimage: "OpenShot-v2.2.0-x86_64.AppImage"

HTH

**Comment by P-Woods** [comment]
Confused by Git-Hub. (Can't be the first person to say that.)

Hope this will now become "OPEN"

**Comment by DylanC** [comment]
@P-Woods - Thanks for the feedback. I will try to confirm this in a newer version.

**Comment by DylanC** [comment]
This looks like a z-index type of issue.

**Comment by P-Woods** [comment]
Just the same in Appimage-v2.3.4-x86_64

**Comment by DylanC** [comment]
@P-Woods Thanks

**Comment by mikelacsa** [comment]
I tested this issue using the latest version. It still exists.

![image](https://user-images.githubusercontent.com/37053994/66160458-c485e600-e65c-11e9-80cb-f38be614de42.png)

After moving the pointer to the right, it shows completely.

![image](https://user-images.githubusercontent.com/37053994/66160550-f39c5780-e65c-11e9-877c-299979066698.png)

**Comment by jonoomph** [comment]
This is caused by the timeline being rendered in a web-view widget, and the rest of the UI being rendered by Qt5. The only fix for this would require rendering the playhead on top of the window, which is a pretty big redesign. 

I would suggest a simpler way to solve this would be to redesign the playhead to have a flat left edge, or some other graphic design type solution. 

I'm also not sure this is a "bug" in the classical sense. It's more of an enhancement request, or a design limitation, but there is nothing breaking in other words. Either way though, the easiest solution would be to redesign the playhead graphic probably.

**Comment by jonoomph** [comment]
On the flip side, if we did move the rendering of the Playhead to Qt5 (and outside of the web-view), it would allow us to more smoothly animated the playhead line... so it's not as jumpy. So there is that. :wink:

**Comment by ferdnyc** [comment]
> This is inelegant!

I've never in my life been accused of elegance.

> Also the time at the start should be 00:00:00:00 "Shurely shum mishtake?"

That part, for the record, is not a mistake. (It's an unfortunate decision. IMHO.) The first frame is Frame 1. (You can't accurately describe 00:00:00:00 as a "time" because it's a representation of HH:MM:SS:Frames, and frames are not a unit of time.)

> This is caused by the timeline being rendered in a web-view widget, and the rest of the UI being rendered by Qt5. The only fix for this would require rendering the playhead on top of the window, which is a pretty big redesign.

Forgive me, but... I don't think that's correct. All of the elements in question (the playhead position index, the track headers, the ruler, and the timeline) are _all_ rendered by the web view. I know, because they're all present if you load `src/timeline/index.html` in Chrome:

![image](https://user-images.githubusercontent.com/538020/66185408-5a197980-e64d-11e9-9f91-6493ad4d5c2e.png)


It's just a matter of how the HTML is structured. The left edge of the timeline container is at the 0 point, and it's styled `overflow: hidden`. In theory, this _could_ be fixed in the HTML+Angular code.

**Comment by ferdnyc** [comment]
> left edge of the timeline container is at the 0 point

(Actually, it would be more accurate to say that the the 0-point is fixed at the left edge of the timeline container. Which actually has a `140px` left margin, to make room for the track headers and position index display to its left. 

The `overflow: hidden` is a bit of a hack to prevent the playhead line from ever going past that edge, since if you use any other `overflow` value all hell tends to break loose in terms of positioning. I've tried it. But that same hack is what prevents the playhead handle from overhanging that edge.)

**Comment by ferdnyc** [comment]
Hah! In fact, I just _sort of_ fixed it.

If you change the styling for the ruler to:
```css
#scrolling_ruler {
  overflow: visible;
  position: absolute;
  left: 140px;
}
```
Then:
![image](https://user-images.githubusercontent.com/538020/66186573-98646800-e650-11e9-8636-ffd2e4db2419.png)

Problem is, now you can drag the playhead past the left edge of the timeline, which is undesirable:

![image](https://user-images.githubusercontent.com/538020/66186613-b8942700-e650-11e9-95b5-9075a66c4bc0.png)

**Comment by ferdnyc** [comment]
(Oh, right. and `position: absolute` means the ruler won't scroll with the timeline, so that's a no-go.)

**Comment by ferdnyc** [comment]
Currently `div.playhead-top` is inside `div#scrolling_ruler`. Then `div.playhead-line` is inside `div#track-container` DIV (which is inside `div#scrolling_tracks`) beneath it. They're actually completely separate siblings. The WebView `<body>` has four child `<div>`s, representing the four elements I mentioned (and the four quadrants of the WebView interface): The position index, the ruler, the track headers, and the timeline (respectively, left-to-right & top-to-bottom).

Because the right-column divs (ruler and timeline) are totally separate siblings, `div#scrolling_ruler` is absolutely dependent on `position: relative` to keep it scroll-locked with the timeline container. If they were both inside the same container, they'd scroll together but we'd have more flexibility in how the ruler can be styled. Problem is, that'd mess up **vertical** scrolling. There, we instead want the bottom-row divs (track headings and timeline) to scroll in sync, while the top row all stays fixed.

Seems to me it's effectively impossible to have the ruler and timeline share a common container for horizontal scrolling, when we also want the ruler and track headers to share a _different_ common container for vertical scrolling. So that _can't_ be the goal, which means we need to approach the problem differently.

**Comment by ferdnyc** [comment]
OK, I believe I've basically fixed this for real in #453. It wasn't actually that bad, in the end. I just widened the ruler container, shifted it left a bit, and gave its contents a left margin to compensate.

![image](https://user-images.githubusercontent.com/538020/66258654-d8713b00-e775-11e9-97f8-eb7002b3dc82.png)

**Comment by ferdnyc** [comment]
Idiot. _This_ is #453. I meant fixed it for real in #3033.

**Comment by mikelacsa** [comment]
@ferdnyc thanks!

**Comment by SuslikV** [comment]
I'm not considering this as issue at all. Feature. The new screens above only makes things worse.

**Comment by P-Woods** [comment]
I failed to realise that 00:00:00:01 meant FRAME 1.
I don't think that it is obvious to a first time user.
At first glance, it seems to be: Hour:Minute:Second:Hundredth or Day:Hour:Minute:Second.
A moments thought should have ruled out the 2nd version.

Perhaps changing the shape of the pointer to be half a "heart" might be considered.

Thanks for looking.

**Comment by SuslikV** [comment]
> I failed to realise that 00:00:00:01 meant FRAME 1.
> I don't think that it is obvious to a first time user...

This has PR... - https://github.com/OpenShot/openshot-qt/pull/3170 - it was made many moons ago.

My point of view in details was here - https://github.com/OpenShot/openshot-qt/pull/3033#issuecomment-539942000

Later, main developer said that UI will be reworked to something new... Maybe in years something will be changed.
