### ISSUE TITLE
Windows version badly lagging, then freezing, then crashing. 

### ISSUE THREAD

**Issue by b1k3rdude** [OpenShot/openshot-qt#4535]
**Describe the bug**

 - When using the program it will lag badly, then freeze then crash.

**System Details**
- OpenShot Version: 2.6.1-dev
- libopenshot Version:  0.2.7-dev
- Platform: Windows-10-10.0.19041
- Processor: AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-GB', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-8661-e1f75637-73c519f0-x86_64.exe

**Comment by b1k3rdude** [comment]
The latest dev build was very laggy, even worse than the 2.6.1 release build, but I think that to be expected. Am going back to 2.6.0 for the time being.

**Comment by JacksonRG** [comment]
What preview settings do you have? For instance, I tend to preview at mobile settings, rather than the settings I intend to export at.

**Comment by b1k3rdude** [comment]
> What preview settings do you have? For instance, I tend to preview at mobile settings, rather than the settings I intend to export at.

I was all default settings.

This bug hasent been fixed afaik. How do I reopen this ticket?

**Comment by Colorjet3** [comment]
There has been some performance improvements in the latest DEV Daily Builds.  This is also currently being worked on as I type this.  When you download the latest Daily Build, you will notice several new Cache settings that you can tweak.  Since it is work in-progress, there is much documentation and lot's of tweaking is happening.

One of the things you can take advantage of right away is by upping the Cache Limit to half your available RAM.  In my case I have a 32GB system and I allocated 8192 (I could do 16GB but not needed).  There is a bit of delay as the content is loaded into the Cache but it sure makes playing back smoother.

I don't have much detail about the rest of the settings and how to leverage them but I expect something to be available in the next month, if not sooner.

**Comment by b1k3rdude** [comment]
> I don't have much detail about the rest of the settings and how to leverage them but I expect something to be available in the next month, if not sooner.

Smashing, thanks for the update :-)
