### ISSUE TITLE
Drop-down selection box - contents box overspills screen

### ISSUE THREAD

**Issue by P-Woods** [OpenShot/openshot-qt#455]
Using: OpenShot-v2.2.0-x86_64.AppImage

This may be a QT issue (or Nvidea or X) but let's hope not.

On my (somewhat unusual)  screen layout
which is 7040 x 2104 with a big area missing,
the selection area of the Choose Profile box is
truncated and NOT scrollable.

Please see the photos

![small-screenshot_2016-12-30_20-18-23](https://cloud.githubusercontent.com/assets/22316637/21572299/5e887b6c-cecf-11e6-9105-a9bd2b069315.png)
![small-screenshot_2016-12-30_20-20-41](https://cloud.githubusercontent.com/assets/22316637/21572300/5e8d0bc8-cecf-11e6-983d-f3af6ba01a5d.png)

Can this box be made scrollable? Let's hope so.

**Comment by P-Woods** [comment]
This Git-Hub thing is confusing! 

There is a button for Close and then for Re-open but nothing for SEND!

I hope some-one at OpenShot is looking for this stuff.

Now it says "Close and comment" 

I just want it to go to OpenShot!

**Comment by P-Woods** [comment]
Now it says closed!!!!!!!!!!!!!   ARRRRRRGH!!!!!!!!!!

**Comment by P-Woods** [comment]
Now it says "OPEN"  What the flip????

Dr Spock must have written this interface

I'm beginning to think the button named "Comment" actually means "Send this comment you have already written above." and not "Write a comment.";
whereas the button named "Close and comment" means "Close this issue and send the comment to justify closure."

If so, when I now press the "Comment" button, maybe this issue will appear on OpenShots' radar.

**Comment by DylanC** [comment]
@P-Woods - Does this issue exist in OpenShot v2.3.4? Please confirm.

**Comment by P-Woods** [comment]
Just the same in v2.3.4-x86_64.AppImage

**Comment by DylanC** [comment]
@P-Woods - Thanks!

**Comment by peanutbutterandcrackers** [comment]
@P-Woods - Does this issue still arise in v2.4.1?

**Comment by DylanC** [comment]
@peanutbutterandcrackers - It seems scrollable to me but I don't have that large resolution screen. So its hard to test.

**Comment by P-Woods** [comment]
Just the same with OpenShot-v2.4.1-x86_64.AppImage

**Comment by P-Woods** [comment]
Just the same with OpenShot-v2.4.1-x86_64.AppImage

The issue is with having the L-shaped screen.

You don't need 6 VDUs, that's just my whim, having 3 gives the same effect.

Some software (could be X or QT or OpenShot or something else) sees the screen area as the whole rectangle defined by the outer boundaries, and doesn't understand that there is a gap in some part of the whole. A hole in the whole.

The selection area of the "Choose Profile" dropdown box is NOT scrollable unless it is taller than the maximum height of the whole screen. If taller, it opens with its' bottom at the bottom of the whole screen, (where there may be no display.) Or there may be no display to show the top items for selection.

The behavior seems fine, the issue is not knowing there is no display in that area.

**Comment by mikelacsa** [comment]
Hi! Is this issue still happening with ver2.4.4?

**Comment by ferdnyc** [comment]
@mikelacsa I'm going to _guess_ that I can answer for the user, and that the answer is yes. Nothing's changed in the code or packaging that would have changed the situation. Nor, TBH, is it likely that anything will.

> This may be a QT issue (or Nvidea or X) but let's hope not.

It is. X displays are _always_ rectangular. It's part of the display server specification that a screen's shape is defined in terms of width and height, or `x` and `y` pixel lengths.

When people started connecting multiple displays together and wanting to create funky, non-rectangular desktop areas that spanned all of them, the protocol was extended with "barrier" regions, additional rectangular chunks taken out of the overall desktop area and declared as inaccessible. Window managers know they're not supposed to draw into those areas, or let the mouse pointer enter them, etc. And they don't, as evidenced by the fact that the selection box doesn't extend into the barrier region of @P-Woods ' desktop, when OpenShot is placed beneath it.

But Qt is apparently being stupid, and blindly taking the desktop `y` dimension as the usable height for the profile selection dropdown. That's a decision made automatically by Qt, and there's really no solution to it on the OpenShot end. (Well, none that — forgive my bluntness — is worth implementing to fix such an obscure issue that will only ever impact a handful of people.) This should be fixed by Qt.

And it's quite possible it _has_ been fixed by Qt. The AppImage package sources haven't been updated since they were first created (except for FFmpeg), and they're built with an _**ANCIENT**_ Qt version (5.2.1— it's from 2014!). I wouldn't be surprised if Qt fixed this years ago.

@P-Woods , you didn't mention what distro you're using, but if there are OpenShot packages available that are built against a newer version of Qt, they're worth trying to determine whether this is indeed fixed on the Qt end. If so, then that's an additional reason I can give @jonoomph why he needs to upgrade the AppImage builds to a Qt release from this half of the decade.

But, barring that, this isn't going to get fixed in OpenShot. Either Qt has fixed or will fix it, or they won't, and that's what will determine whether it remains an issue. Closing as **#wontfix** from our end.

**Comment by ferdnyc** [comment]
> @P-Woods , you didn't mention what distro you're using

Technically true, but the Linux Mint logo on the desktop background _probably_ should've clued me in, so never mind. :wink:
