### ISSUE TITLE
Export DVD PAL Widescreen

### ISSUE THREAD

**Issue by AllanTen** [OpenShot/openshot-qt#456]
When importing and exporting Widescreen PAL DVD videos I've noticed that the aspect ratio of the exported video is always 4:3, although "DV/DVD Widescreen PAL" is selected. In the preview area, the video aspect is displayed correctly. Am I doing something wrong or is there a bug in the video exporter?  
Operating System: Windows 7 SP1, Language: German

**Comment by croco3008** [comment]
Same issue here. To work around this issue, I exported the project in BlueRay profile and downscaled result using Handbrake. You aren't doing nothing wrong - it's a bug. I'm going to look the profile definition, first. Hopefully it's easy to fix...

**Comment by DylanC** [comment]
@AllanTen @croco3008 - Is there still a problem in OpenShot with this?

**Comment by boamaod** [comment]
OpenShot 2.3.4 on Ubuntu 16.04/17.10 has the same problem of exporting Widescreen DV/DVD as 4:3 even though Widescreen profile is selected for project as well as for the export. Video is displayed fine in preview, but "Stretch" option has to be used after importing video file, because it is imported as 4:3 (no matter if Widescreen profile is selected before or after the import). Original video is displayed correctly as Widescreen in VLC player and others.

**Comment by DylanC** [comment]
@boamaod - Perfect. Thanks for the information!

**Comment by boamaod** [comment]
@DylanC Any ideas for quick fix or workaround? Maybe a patch to test?

**Comment by DylanC** [comment]
@boamaod - Not at the moment. I'm not too involved with development so far but I can ask the guys about this issue for you.

**Comment by boamaod** [comment]
@DylanC I'd appreciate that and I can try to fix it myself, if I am given some hints where to look. Since I have a one hour video file I already edited and cannot export, I have to find some solution in 12h or so. Otherwise I have to redo the whole work in some other video editor, which whould be quite annoying.

**Comment by DylanC** [comment]
@jonoomph - Is there a quick and easy fix for this?

**Comment by boamaod** [comment]
Seems like using profile [1024x576 16:9 PAL](https://github.com/OpenShot/openshot-qt/blob/master/src/profiles/square_pal_wide) on export for whatever reason gives decent results, although upscaling to 1024 is not really welcome. If you want some extra debug data from console, I can provide some.

**Comment by DylanC** [comment]
@boamaod - That may be useful, thanks. Please do provide it.

**Comment by DylanC** [comment]
@boamaod - Maybe we need a new profile to cater for what you want. So the ratio is 16.9, what resolution (width and height) do you need?

**Comment by DylanC** [comment]
@boamaod - Better question, should this profile:

https://github.com/OpenShot/openshot-qt/blob/master/src/profiles/dv_pal_wide

have some of the parameters from this one? 
https://github.com/OpenShot/openshot-qt/blob/master/src/profiles/square_pal_wide

Such as:
progressive=1
sample_aspect_num=1
sample_aspect_den=1

Plus the width be set to 720 instead?
