### ISSUE TITLE
Fill all empty spaces between items

### ISSUE THREAD

**Issue by gale93** [OpenShot/openshot-qt#4575]
While working on items added to a timeline's track, it would be handy to have a function that "compact" all items the filling empty gaps.

I am sorry if it already exists, I could not find it.
And if actually not exists, are there any architectural reasons ?

**Comment by JacksonRG** [comment]
Frankly, I think the reason we don't have that is because no-one asked for it. It could be an additional `align` option when multiple clips are selected.

Until then, make sure you have the `snapping` tool (button with a magnet symbol) turned on. It makes it pretty quick to line up the start of one clip with the end of another.

**Comment by Colorjet3** [comment]
I've seen this request in Reddit a few times.  A nice feature to have.

**Comment by gale93** [comment]
Hi @JacksonRG 
The snapping tool is indeed very helpful, but I had to work on a video with 20+ videos 5~ sec length and it has been painful.

I didn't look at codebase yet, but I could work on it, I will have some free times during upcoming festivities.

**Comment by JacksonRG** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Snap Together button](https://trello.com/c/wly7VcIS/147-snap-together-button)

**Comment by Colorjet3** [comment]
Hello @gale93.  This is now fixed in the latest dev daily build #12980.  You can go to openshot.org/download/#daily and download the latest dev daily build and give it a try.
