### ISSUE TITLE
Ability to delete "all markers", at once, from a project

### ISSUE THREAD

**Issue by Colorjet3** [OpenShot/openshot-qt#4591]
**Describe the new feature:**
Ability to delete all Markers set in a project at once.

**Describe the solution you'd like:**
Add another option to the popup window when you right click on a Marker that says "Remove All Markers".  This will be in addition to the existing option of "Remove Marker".

When you select "Remove All Markers", a pop up window should ask you "Are you sure?" with the options to click on Yes or No.  If you click on Yes all of the markers in the project are removed.  If you click No the pop up window closes and return back to the project timeline.

**Describe alternatives you have considered:**

Did not consider any other alternative solutions or features.

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your request.

**Comment by motoryzen** [comment]
I couldn't agree more.  This is a long over due SIMPLE power user piece of functionality that should have been available by now ( June 2022) that so many other video editors have.  I love OpenShot though and Prefer to stick with it.

If anyone knows precisely where to navigate to in any of the Openshot - involved directories/folders ( be it windows or linux) to edit or add this piece of functionatlity as a keyboard two or three button shortcut. ..I'm all eyes. 

I already know how to make it to where when I launch any new instance or the first instance of Openshot that it already knows my prefer Export folder target/destination ( instead of /home already filled out in Linux ) as well as a custom set bitrate, resolution, etc deal too.   ( if anyone needs that info.  just let me know and I'll post the info/link(s)  You do this at your own risk though I do not guarantee it won't mess with your particular installed-version of Openshot.  I did my install via terminal)

**Comment by Colorjet3** [comment]
Hello @motoryzen.  I don't know how much about the code regarding a shortcut to delete all markers or about the code architecture and will leave that to the development team.

In regards to folder location, please checkout the latest DEV Daily Build as it has this feature now where you can manage "File Import", "Save or Open Project", and "Video Export" behavior.  You can find these setting under Edit | Preferences | Location tab.

**Comment by motoryzen** [comment]
I'm guessing you skimmed over this part that I already said '

"" I already know how to make it to where when I launch any new instance or the first instance of Openshot that it already knows my prefer Export folder target/destination "" xD  I've already figured the " how to change the Default target Export folder/directory" part.  ;)  which was the first sentence in my last paragraph/section of my comment.

**Comment by Colorjet3** [comment]
I didn't read it that way.  My bad! I thought you had found a different way of doing it and I was trying to make you aware of something that you already had seen.

**Comment by JacksonRG** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Button: Remove all Markers](https://trello.com/c/X9csn82Q/140-button-remove-all-markers)

**Comment by Colorjet3** [comment]
This enhancement request is in the queue.
