### ISSUE TITLE
audio glitch when previewing

### ISSUE THREAD

**Issue by adambad-mod** [OpenShot/openshot-qt#4599]
**I put in any file with audio and when i preview it it has crackaling but when i export it its back to normal**

1. import audio file (in my case mp3 and mp4)
2. Click on '..play in the preview..'
3. audio glitch

**Expected behavior**
to play the audio with little to no problems.

**System Details**
- OpenShot Version: 2.6.1
- libopenshot Version:  0.2.7
- Platform: Windows-10-10.0.19041
- Processor: AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-8930-3c8dc71b-2b8b05c7-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/m1i7f3zpysllmkbcjcnhun15x6gux3pf/openshot-qt.zip) (10 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/m1i7f3zpysllmkbcjcnhun15x6gux3pf/libopenshot.zip) (4 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Comment by adambad-mod** [comment]
Ive tried changing the fps to match source files and changing it to the same audio channel as my headphones

**Comment by ghwmorg** [comment]
Me also get audio glitch, in previewing but in the rest of the uses.

Also interface problems fixing layout or view.

I've downgraded to 2.4.4 and again OK (again ok the new bugs, there are some traditional others).

**Comment by adambad-mod** [comment]
@ghwmorg im sorry i dont think i follow what you said. did you say that you switched to version 2.4.4 and the audio issues were gone but with the old bugs?

**Comment by ghwmorg** [comment]
> @ghwmorg im sorry i dont think i follow what you said. did you say that you switched to version 2.4.4 and the audio issues were gone but with the old bugs?

I had some traditional troubles, perhaps it can be called un-functionalities. Lets forget them right now in order avoid confussions.

Lets put the focus on v2.6.1:

I experimented, in the few days trying it, two specific problems (because of it):

1) The audio glitch.

and

2) The impossibility of fixing certain sizes and arrangement of the working windows (preview window, etc.). Before, using v2.4.4; I could, so that when I reopened Openshot, that working arrangement would be preserved.

Going back to v2.4.4, I have avoided those two issues as they are inherent in v2.6.1.

Is it understood now?

Greetings

**Comment by JacksonRG** [comment]
@adambad-mod Sorry we didn't respond to your issue earlier. We've recently made improvements to make sure we are matching the sample rate of the computer's audio devices. If you're still having this issue, I'd love to hear if it's present in the most recent build.
