### ISSUE TITLE
A 30 minute video consisting of several clips cannot play properly, the app skips many times in play...

### ISSUE THREAD

**Issue by bennetms** [OpenShot/openshot-qt#4612]
**Describe the bug**
create video consisting of several clips, and then play back inside the app, the payback skips a lot of content

**Steps to reproduce the behavior:**
create video consisting of several clips, and then play back inside the app, the payback skips a lot of content, the time time does not keep moving, but freezes, then carries on, skipping video and sound playback. Example play from 0m00s to 1:00 then the next time line that is shown is 1m:30s, so 30 seconds are skipped often, as if the app cannot keep up. I have made a few videos in recent past, which worked fine.

**Expected behavior**
Playback should work fine. with nothing else running, with out any skipping

**System Details**
- OpenShot Version: 2.6.1
- libopenshot Version:  0.2.7
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-8930-3c8dc71b-2b8b05c7-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/502xhfbcssfinhz2nkwyelvdkzlaveey/openshot-qt.zip) (6 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
None.

**Comment by JacksonRG** [comment]
Would you mind recording a short video of this bug occurring?

First question: Does this happen in the 2.6.1 release version? (I ask because we made a recent fix to some timing issues)

Second: Does this behavior show up in the exported video as well?
If not it may simply be that the project is a bit too demanding to render in real time.
You can try changing your preview profile to a lower resolution. Hit `ctrl + p` to change the current profile.

I'll take a look over your logs. Let me know if you learn any more about this bug.
