### ISSUE TITLE
Can't preview at all 

### ISSUE THREAD

**Issue by gaining** [OpenShot/openshot-qt#463]
I am unable to preview anything in openshot 2.2.0 dev. I have 2 mp3 music files on the second timeline and a 2700 frame snow effects on the first timeline. I was just trying this to test the new version. I have a theory that it might be the codecs that I'm using that's causing the issue. Does Openshot have a preference to specific codecs? If so, which are they so that I can have the right ones.
 I'm using mint 17.3 cinnamon 64 bit, intel i74510u CPU, 8GB ram, nvidia geforce 840m

**Comment by vales** [comment]
After a few seconds locks preview and the CPU is used at 100%.
This happens both on Windows 10 and Ubuntu 16.10.
I am using HP Envy, i7-5500U CPU, 2.4 GHz, RAM 16 G, NVIDIA GeForce GTX 950M

**Comment by vindolin** [comment]
I have the same problem, video instantly stutters and CPU goes up to 100%.
I'm trying this with a 1080p60 MP4.
System: Ubuntu 16.04 on Dell XPS13 with 16gb ram, Intel graphics, kaby lake.

**Comment by TombyT** [comment]
I have the same issue. Previews might work for the first 30-60 seconds of playback, but all the while the RAM usage and CPU usage will go to 100% and eventually stutter and then freeze. If i am patient the playback will resume but continuously laggy.

The cycle repeats until i close the program and my ram usage goes from 100% to 0 and then slowly ramps up again.

I have an i7-2630QM, GTX 460m, 32GB RAM and 256 SSD. Ubunti 16.10. I acknowledge this is old hardware but it can run many of these GoPro videos upon multiple monitors and still run modern games.

ffplay and melt all seem to run individual files correctly.

The exported product was mostly fine but had a few stutters/lag throughout (reproducible).

**Comment by brothermartin** [comment]
I am having the same problem. I did some videos on the old version, and was looking forward to exploring the upgrade, which has a lot more effects, but when I try and play the preview, it makes a little scratching sound instead of playing the mp3 file, and then the whole program freezes up. I'm running Ubuntu 14.04 on a Zareason with 3.9 GiB of memory, AMD Athlon(tm) 64 X2 Dual Core Processor 3800+ × 2, Gallium 0.4 on NV84 graphics, a 64-bit operating system, and 980.1 GB of disk space. I haven't checked ram usage, but occasional greyouts on the screen indicate 100% usage, I believe. 

I'm not terribly experienced at "poking around under the hood" of my computer--more of a writer and musician who uses a computer than a computer user who's a writer and musician. I hope this gets figured out soon!

**Comment by gaining** [comment]
I tested the newest openshot today and it seems to be fixed
