### ISSUE TITLE
OpenShot would not open after installing and also not giving any pop-up messages.

### ISSUE THREAD

**Issue by TechNila** [OpenShot/openshot-qt#4664]
**Describe the bug:**
I installed OpenShot 2.6.1 on my PC through the official website. After installing, when I try to open it through Windows start menu, and it would not even show anything like a pop-up message, or an error code, or anything else. I can see its trying to do something, but nothing eventually shows up. Please Help...

**Steps to reproduce the behavior:**
1. Go to 'C:\Program Files\OpenShot Video Editor'
2. Click on 'openshot-qt.exe'
3. Again, nothing.

**Expected behavior:**
OpenShot would just open up.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version 2.6.1}}
- Operating System / Distro: Windows 10 x64, 4gb RAM.

**Log Files:**
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/7963240/openshot-qt.log)

**Exception / Stacktrace:**
None.

**Screenshots:** (Optional)
I don't have anything to show..

**Comment by JacksonRG** [comment]
@TechNila Sorry we missed your issue! From your log file it looks like the libraries openshot needs are missing. How did you install openshot? We have installers at https://www.openshot.org/download/.
I recommend trying both the release (currently 2.6.1) and the *daily build* which contains lots of fixes that have been made since the release.

Also you might need to try running (or installing) openshot as an administrator. For some reason, OpenShot isn't able to find the files it needs.

**Comment by TechNila** [comment]
Thanks for getting back to me, but I don't use OpenShot any more now. But
Thanks anyways.

**Comment by JacksonRG** [comment]
No problem. Take care.
