### ISSUE TITLE
export 24-bit FLAC audio stream (eg. inside mkv container)

### ISSUE THREAD

**Issue by Ante33** [OpenShot/openshot-qt#4673]
When exporting video, I can manually change the audio codec to FLAC, but the resulting audio stream is always 16-bit. Is it possible to export as 24-bit? The audio source is 24-bit WAV.

I was hoping it would be possible to create an export option in a preset.xml file inside /home/user/.openshot_qt/presets

	<bitdepth>24</bitdepth>

similar to how we can specify

	<samplerate>96000</samplerate>

I know ffmpeg has the options:
sample_fmt=s16
sample_fmt=s32
for 16-bit/24-bit respectively.

**Comment by JacksonRG** [comment]
You'll have to pardon my inexperience with audio codecs. A quick Wiki dive tells me that FLAC has at most 24 bits. I assume that's why `sample_fmt=s32` creates a 24 bit audio stream.

I'll look into where we set the bit depth (if that's the right term?) and we could add an option in the export window.

**Comment by Ante33** [comment]
> I assume that's why `sample_fmt=s32` creates a 24 bit audio stream.

Apparently, the 24-bit samples are stored in 32-bits with padding.

> we could add an option in the export window

That would be great. In the above usage case, only this would ensure no loss of information during export.
