### ISSUE TITLE
error on open OSP

### ISSUE THREAD

**Issue by jpboussac** [OpenShot/openshot-qt#468]
...
uint DBusMenuExporterDBus::GetLayout(int, int, const QStringList&, DBusMenuLayoutItem&): Condition failed: menu
...
json_data:ERROR Couldn't load project data file: 'ascii' codec can't decode byte 0xc3 in position 18693: ordinal not in range(128)
project_data:ERROR Failed to load project file /mnt/38B0638C31EEFBF5/Montage/Essaouira/Essaouira2/EssaouiraHotelOrsonWelles.osp: invalid load key, '{'.

**Comment by jonoomph** [comment]
Hi @jpboussac Can you please update this issue with what OS you are using, and what version of OpenShot you are running? Also, please verify this still happens with our latest daily build of OpenShot 2.x. 
Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. 

If the issue is still happening, please attach your project file that is failing to load, and re-open this issue. Thanks!
