### ISSUE TITLE
Crash when importing .mp4 file

### ISSUE THREAD

**Issue by EddyNCNL** [OpenShot/openshot-qt#4684]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 2.6.1
- libopenshot Version:  0.2.7
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Skipped this step

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/5jxxukiuyzaign1prmikcwqltsu3lpsv/openshot-qt.zip) (45 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/5jxxukiuyzaign1prmikcwqltsu3lpsv/libopenshot.zip) (31 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by naanlizard** [comment]
Why did you close this? How did you fix it? I'm having the same problem

**Comment by JacksonRG** [comment]
@naanlizard Could you include some details about what went wrong? If you'd like you can open your own issue, and include details like how to replicate and the log files for how it happened. (instructions for that [here](https://github.com/OpenShot/openshot-qt/wiki/Issue-Logging))

Just off the top of my head, it may be a name issue if you have any special characters in the file name. Otherwise, you could try re-encoding the file with a tool like [handbrake](https://handbrake.fr/) to see if that allows the file to be imported.

**Comment by naanlizard** [comment]
https://user-images.githubusercontent.com/7061721/156084529-163284f4-7c0c-4e59-8e86-91c2fff2bdec.mp4

Try and import that video. It crashes every time for me, the filename is just "pig.mp4" for me.

**Comment by JacksonRG** [comment]
It imported. I'm running the daily build on Ubuntu, I'll grab 2.6.1 and test it as well.

**Comment by naanlizard** [comment]
I just tried dev, still crashed, even with a brand new project. I'm on windows 11, will try updating.

Here are logs

[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/8158018/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/8158019/openshot-qt.log)

**Comment by naanlizard** [comment]
Notably, my windows is set to portuguese (european), perhaps that's related?

**Comment by EddyNCNL** [comment]
> Why did you close this? How did you fix it? I'm having the same problem

Hi,
I closed it because the issue seemed to be with my video file.

I downloaded several video files from Google Photos, all were fine to import to OpenShot, except one.
When I tried to import it, OpenShot crashed every time.
The video was several minutes long but only 20 mb. I suspect something went wrong when downloading from Google Photos.

I downloaded the file again, much bigger this time, and was able to import it in OpenShot ok. That is why I closed this ticket.
So perhaps you might want to check your video file? Good luck.

**Comment by JacksonRG** [comment]
@EddyNCNL Good idea, @naanlizard my `pig.mp4` is 9.0 MB. What about you?

**Comment by naanlizard** [comment]
![image](https://user-images.githubusercontent.com/7061721/156238201-0d271dbb-a12c-45b2-9914-abb525f53c27.png)

Slightly smaller, I'm guessing you're rounding?

I'll try some alternative files - this one was transcoded from youtube

**Comment by JacksonRG** [comment]
![Properties](https://user-images.githubusercontent.com/42394129/156239511-7b786886-f716-45e8-85fd-c9cb9190594d.png)

Not rounding... But my computer was dividing by 1,000,000 instead of 2^20. But the bytes are the same. So that's not the issue.

Your log files are showing some interesting things problems in decoding the file. Still looking
