### ISSUE TITLE
OpenShot crashes with everything else but ›Basic keying‹ in the Chroma Key filter

### ISSUE THREAD

**Issue by matwolf** [OpenShot/openshot-qt#4689]
**Describe the bug**
When I choose a Key Method other than ›Basic keying‹ fpr a Chroma Key filter, OpenShot crashes without notice.

**Steps to reproduce the behavior:**
1. Put Chroma key filter on clip
2. Select C
3. Click on ›Proerties‹
4. Select anything else but ›Basic keying‹ for ›Key Method‹
5. Set the cursor into the clip with the Chroma Key filter
    (or start the video and wait until the respective clip is reached)
6. Openshot crashes gracelessly

**Expected behavior**
The clip should be shown.

**System Details**
- OpenShot Version: 2.6.1-dev
- libopenshot Version:  0.2.7-dev
- Platform: Linux-5.16.7-1-MANJARO-x86_64-with-ManjaroLinux-21.2.3-Qonos
- Processor: 
- Machine: x86_64
- Python version: 3.6.9
- Qt5 version: 5.9.5
- PyQt5 version: 5.10.1
- Qt Detected Languages: ['en-GB']
- LANG Environment Variable: en_GB.utf8
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-9138-f2b89e32-2b8b05c7-x86_64.AppImage

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/p3gm8gx282umyceo5qa9laa6xrjqnhv3/openshot-qt.zip) (8 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by mabequinho** [comment]
Any update on your side? I'm experiencing Chroma Key crashes too.

**Comment by arnolde** [comment]
I have the exact same issue, as described in the original post. Ubuntu 22.04, Openshot 3.1.1
```Feb 18 16:58:55 silver openshot-community_openshot-community.desktop[50033]: INFO properties_tableview: Choice_Action_Triggered
Feb 18 16:58:55 silver openshot-community_openshot-community.desktop[50033]: INFO properties_model: keymethod for BTPV6SCDT2 changed to 7 at frame 1 with interpolation: -1 at closest x: -1
Feb 18 16:58:55 silver openshot-community_openshot-community.desktop[50033]: INFO main_window: updateStatusChanged
Feb 18 16:58:55 silver openshot-community_openshot-community.desktop[50033]: INFO properties_model: Item BTPV6SCDT2: changed keymethod to 7 at frame 1 (x: -1)
Feb 18 16:58:55 silver openshot-community_openshot-community.desktop[50033]: ../babl/babl-internal.h:222 babl_fatal()
Feb 18 16:58:55 silver openshot-community_openshot-community.desktop[50033]: #011babl_format("CIE LCH(ab) float"): not found
Feb 18 16:58:55 silver openshot-community_openshot-community.desktop[50255]: sh: 1: gdb: not found
Feb 18 16:58:55 silver openshot-community_openshot-community.desktop[50033]: QObject::~QObject: Timers cannot be stopped from another thread
Feb 18 16:58:55 silver systemd[1838]: snap.openshot-community.openshot-community-586062b6-7a17-4a11-95bd-086957fb834d.scope: Consumed 25.479s CPU time.
```
EDIT: Since the OP Matthias Wolf is also in a German-speaking country (like me), I wonder if it's the German translation?

EDIT2: Nope, still crashes after changing the language from "default" (which resulted in German for me) to "US english":

```Feb 18 17:05:46 silver openshot-community_openshot-community.desktop[50738]: INFO main_window: updateStatusChanged
Feb 18 17:05:47 silver openshot-community_openshot-community.desktop[50738]: INFO properties_tableview: Context menu shown for Key Method (keymethod) for clip BTPV6SCDT2 on frame 1
Feb 18 17:05:47 silver openshot-community_openshot-community.desktop[50738]: INFO properties_tableview: Points: 0
Feb 18 17:05:49 silver openshot-community_openshot-community.desktop[50738]: INFO properties_tableview: Choice_Action_Triggered
Feb 18 17:05:49 silver openshot-community_openshot-community.desktop[50738]: INFO properties_model: keymethod for BTPV6SCDT2 changed to 1 at frame 1 with interpolation: -1 at closest x: -1
Feb 18 17:05:49 silver openshot-community_openshot-community.desktop[50738]: INFO main_window: updateStatusChanged
Feb 18 17:05:49 silver openshot-community_openshot-community.desktop[50738]: INFO properties_model: Item BTPV6SCDT2: changed keymethod to 1 at frame 1 (x: -1)
Feb 18 17:05:49 silver openshot-community_openshot-community.desktop[50738]: ../babl/babl-internal.h:222 babl_fatal()
Feb 18 17:05:49 silver openshot-community_openshot-community.desktop[50738]: #011babl_format("HSV float"): not found
Feb 18 17:05:49 silver openshot-community_openshot-community.desktop[50958]: sh: 1: gdb: not found
Feb 18 17:05:49 silver openshot-community_openshot-community.desktop[50738]: QObject::~QObject: Timers cannot be stopped from another thread
Feb 18 17:05:49 silver openshot-community_openshot-community.desktop[50738]: [50738:50854:0218/170549.632102:ERROR:gl_context_glx.cc(240)] Couldn't make context current with X drawable.
Feb 18 17:05:49 silver openshot-community_openshot-community.desktop[50738]: [50738:50854:0218/170549.632128:ERROR:gles2_cmd_decoder.cc(4847)]   GLES2DecoderImpl: Context lost during MakeCurrent.
Feb 18 17:05:49 silver openshot-community_openshot-community.desktop[50738]: [50738:50854:0218/170549.632158:ERROR:display_overrides.cpp(80)] MakeCurrent failed for GetTextureQt
Feb 18 17:05:49 silver openshot-community_openshot-community.desktop[50738]: [50738:50854:0218/170549.632650:ERROR:gl_context_glx.cc(240)] Couldn't make context current with X drawable.
Feb 18 17:05:49 silver openshot-community_openshot-community.desktop[50738]: [50738:50854:0218/170549.632684:ERROR:gl_context_glx.cc(240)] Couldn't make context current with X drawable.
Feb 18 17:05:49 silver openshot-community_openshot-community.desktop[50738]: [50738:50854:0218/170549.632706:ERROR:gles2_cmd_decoder.cc(4847)]   GLES2DecoderImpl: Context lost during MakeCurrent.
Feb 18 17:05:49 silver openshot-community_openshot-community.desktop[50738]: [50738:50854:0218/170549.633064:ERROR:gl_context_glx.cc(240)] Couldn't make context current with X drawable.
Feb 18 17:05:49 silver openshot-community_openshot-community.desktop[50738]: [50738:50854:0218/170549.633382:ERROR:gl_context_glx.cc(240)] Couldn't make context current with X drawable.
Feb 18 17:05:49 silver openshot-community_openshot-community.desktop[50738]: [50738:50854:0218/170549.633635:ERROR:gl_context_glx.cc(193)] Failed to create GL context with glXCreateContextAttribsARB.
Feb 18 17:05:49 silver openshot-community_openshot-community.desktop[50738]: [50738:50854:0218/170549.633646:ERROR:gpu_channel_manager.cc(753)] ContextResult::kFatalFailure: Failed to create shared context for virtualization.
Feb 18 17:05:49 silver openshot-community_openshot-community.desktop[50738]: [50738:50854:0218/170549.633656:ERROR:gl_surface_glx_qt.cpp(188)] glXCreatePbuffer failed.
Feb 18 17:05:49 silver openshot-community_openshot-community.desktop[50738]: [50738:50854:0218/170549.633668:ERROR:in_process_command_buffer.cc(415)] ContextResult::kFatalFailure: Failed to create surface.
Feb 18 17:05:49 silver systemd[1838]: snap.openshot-community.openshot-community-31575d52-6354-44cc-96f7-0660b054d679.scope: Consumed 29.923s CPU time.
```

**Comment by Colorjet3** [comment]
Hello @matwolf and @arnolde.  I am a novice Linux user and my primary host is Windows 11 Pro.  I don't have any crashing issues with Chroma key but there are still some bugs in it.  I do have Linux Virtual environment (Oracle Virtualbox) so I can run Ubuntu 22.04 lts.  However, I typically run into other issues when performing advanced editing since screen colors, etc., don't pass through from host to guest gracefully.

What would help me to test and troubleshoot is this:
1.  What version of OpenShot are you running (help | about openshot?)
2.  How did you install Openshot on your system.
3.  What type of file(s) are you working with (.jpg? .mp4? etc.).
4.  Please tell me step-by-step of when exactly you experience crash.  I need to understand at what point does OpenShot crash.

The more details the better the troubleshooting will be.  Eventually, we might need the lead developer to chime in and he will need as much detail as possible. 

**Update**
I highly recommend that you upgrade to the latest DEV Daily Build AppImage to test with.

If you upgraded from v2.5.x or v2.6.x to v3.1.1 or will be doing so during this testing then you need to cleanup the /home/username/.openshot_qt folder.

1.   Close Openshot if running.
2.   make a backup of /home/username/.openshot_qt folder.  Somehow flag this backup as the version of your current Openshot (this is important if you are currently running v2.5.x or v.2.6.x).  This will be important if you want to go back to v2.6.x.
3.   delete /home/username/.openshot_qt folder.
4.   go to openshot.org/download/#daily and download the latest DEV Daily Build AppImage available.
5.   Make it executable and run it.
6.   Start a new project and test the ChromaKey.

If you test with an existing project that was created with v2.5.x or v2.6.x you may/will experience possible issues as there were some major changes/fixes made to Chromakey and other effects.  Meaning, you may be able to open and existing project created in an older version but some of the effects/animation you have created may not function properly.

**Comment by arnolde** [comment]
@Colorjet3 Thanks for looking into it! My 9yo daughter and I are getting really frustrated with the crashing and the default basic chromakey does not work very well.

I run Openshot 3.1.1 / libopenshot 0.3.2 and installed it via the "Ubuntu software" menu (9-dot-menu, orange suitcase logo with an A on it) and of the 2 available versions, I installed the newer one (openshot community, links to: https://github.com/jssotomdz/openshot-snap) - so I guess it was installed via snap.

The source files are directly recorded from a Sony Alpha 57 in .mp4 format.

My Linux is installed in German language (it's my daughter's computer and her english is almost non-existant yet) and so openshot set itself to German automatically. Like I described above, I tried sitching to english but that didnt help. No idea if that is relevant.

This is the first install of openshot on a fresh Linux install, so I did not upgrade anything.

The procedure to reproduce:
1. Add a mp4 video with green elements to track 2. 
2. Add a still background frame to track 1. 
3. Add the chromakey effect to track 2. 
4. Edit the chroma properties and select a color by picking off the screen, adjust the threshold to 50+ and find that the chromekeying is not working well because of inconsistent lighting
5. Edit the choma properties again and switch the key method from "basic keying" to i.e. "LCH chroma", I tried several ones and they all immediately crashed the program, except for "cb,cr,vector" which works better than "basic" but still not perfect (seems to blend out anything that moves, regardless of color).

Let me know if you need to know anything else.

I suspect the clue here, there are different messages of the same type in the logs of my attempts:
#011babl_format("CIE LCH(ab) float"): not found
#011babl_format("HSV float"): not found

kind regards,
Ethan

**Comment by Colorjet3** [comment]
Hello @arnolde.  Please go to openshot.org/download/#daily and download the latest DEV Daily AppImage.  No need to backup and delete the .../.openshot_qt folder since you didn't upgrade from a previous version.

Make the AppImage executable, run it and test.  Let me know the results.

**Comment by arnolde** [comment]
That works now, I can select all the keying types now. Thanks! (Although I dont understand why the appimage works so much better than the snap)

**Comment by Colorjet3** [comment]
That is great!  The AppImage you downloaded is the latest Development (not production yet).  These are fixes the lead developer has made available for users with issues to test.  Eventually they will make it to production.  

I really don't understand how each of the linux environments update their repositories (Snap, Flatpak, PPA, etc.).
