### ISSUE TITLE
Can't Import Media (Couldn't apply 'insert' to update listener)

### ISSUE THREAD

**Issue by rioki** [OpenShot/openshot-qt#4772]
**Describe the bug**

When importing media (video or image) Open Shot says "Imported 0 files". Adding video or image onto a track works though.

**Steps to reproduce the behavior:**

1. Open OpenShot 
2. Import Media via RMB & Import on the Project Files or Drag & Drop.

**Expected behavior**

The media will be imported and is usable for editing.

**System Details**

- OpenShot Version: 2.6.1-dev
- libopenshot Version:  0.2.7-dev
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-9387-d909eccd-46255e46-x86_64.exe

**Log Files**

- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/xhtk7uz7u0yib58jcb7j4upb8cdsxmn9/openshot-qt.zip) (7 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**

```No stacktrace found in log files```

**Notes**

The behavior appears to have happened when upgrading from 2.5.1 to 2.6.1 and somehow broke the environment. Rollback to 2.5.1 does not resolve the issue; it appears something got borked in the environment. (Maybe not even the OpenShot Installer.)

- Removed .openshot_qt folder for each install.
- As there is some notes on network issues, disabled Firewall entirely. Issue persists. (The log was from the run without firewall.)

**Comment by karolyi** [comment]
+1, can confirm this.

I've got the exact same symptoms. Upon checking for said thumbnail server with netstat, I didn't see any ports open logged in the openshot-qt.log. It seems the thumbnail server doesn't start at all, resulting in importing failure.

When I try to import any videos, it just says "0 files imported" and the same error appears in the log.

Reverting to 2.5.1 didn't help either.

**Comment by JacksonRG** [comment]
Interesting... @karolyi were you able to drop files directly into the file window or the timeline like @rioki could?

**Comment by JacksonRG** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Setting "import_path" on file import prevents import](https://trello.com/c/vz1onT7T/117-setting-importpath-on-file-import-prevents-import)

**Comment by karolyi** [comment]
I have replied via email, doesn't seem to show up so here's what I wrote:

Hey,

it's my retired father's computer (he edits videos of his peer group with it), so I need to go on his computer and test it.

However I vaguely remember trying pulling videos into the library (not the timeline) and it didn't work either.

**Comment by rioki** [comment]
just to make sure we are on the same page: drag & drop into the library does not work; only into the timeline.

**Comment by karolyi** [comment]
I can confirm that dragging the file onto the timeline works, the video appears with an empty thumbnail.

**Comment by JacksonRG** [comment]
Strange! But that info should help us find the bug

**Comment by cwolter** [comment]
> I can confirm that dragging the file onto the timeline works, the video appears with an empty thumbnail.

Hi, I´m suffering the same issue, thanks for that workaround, I was not aware this works.

Here is my Log:
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/9828627/openshot-qt.log)

I guess this is the issue here:
09:19:50 INFO files_model: Imported media file D:/Stream_MD/MD-LP-35/Thumpnail.jpg
09:19:50 INFO project_data: _set key: ['files'] values: {'acodec': '', 'audio_bit_rate': 0, 'audio_stream_index': -1, 'audio_timebase': {'den': 1, 'num': 1}, 'channel_layout': 4, 'channels': 0, 'display_ratio': {'den': 9, 'num': 16}, 'duration': 3600.0, 'file_size': '3686400', 'fps': {'den': 1, 'num': 30}, 'has_audio': False, 'has_single_image': True, 'has_video': True, 'height': 720, 'interlaced_frame': False, 'metadata': {}, 'path': 'D:/Stream_MD/MD-LP-35/Thumpnail.jpg', 'pixel_format': -1, 'pixel_ratio': {'den': 1, 'num': 1}, 'sample_rate': 0, 'top_field_first': True, 'type': 'QtImageReader', 'vcodec': '', 'video_bit_rate': 0, 'video_length': '108000', 'video_stream_index': -1, 'video_timebase': {'den': 30, 'num': 1}, 'width': 1280, 'media_type': 'image', 'id': 'EOJW6FHJ14'} add: True partial: False remove: False
09:19:52 ERROR updates: Couldn't apply 'insert' to update listener: <windows.models.files_model.FilesModel object at 0x000001b28a6583a0>
HTTPConnectionPool(host='127.0.0.1', port=65335): Max retries exceeded with url: /thumbnails/EOJW6FHJ14/1/path/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001b28bac62b0>: Failed to establish a new connection: [WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte'))
09:19:52 INFO main_window: updateStatusChanged
09:19:52 INFO project_data: _set key: ['import_path'] values: D:/Stream_MD/MD-LP-35 add: False partial: False remove: False
09:19:52 INFO main_window: updateStatusChanged
09:22:31 INFO main_window: auto_save_project

**Comment by Colorjet3** [comment]
Please download the latest DEV daily build from openshot.org/download/#daily, install it and give it a try.
