### ISSUE TITLE
Transitions don't work for me

### ISSUE THREAD

**Issue by Bentsman** [OpenShot/openshot-qt#4800]
**Expected behavior:**
I expect the transitions to fade from one picture to another but they only fade from black or to black.

**System Details:**
Kernel: 5.4.0-110-generic x86_64 bits: 64 compiler: gcc v: 9.4.0 Desktop: MATE 1.24.0 : Linux Mint 20.2 Uma base: Ubuntu 20.04 focal

**Screenshots:** (Optional)
https://user-images.githubusercontent.com/23739106/168448314-91fb3901-e0e3-4d2d-a263-037432c594b4.png

**Comment by dhjw** [comment]
1. You can right-click a clip and use the Fade menu to set fade on clips without regular transitions
2. When you add a transition to the end of a clip you have to drag the next clip to the left to the beginning of the transition, overlapping the first clip a bit. I was confused by this myself at first.

**Comment by Bentsman** [comment]
Thanks for that but I like to use the circle in and out like the Apple iMovie that I normally use.

**Comment by JacksonRG** [comment]
So if you want to use other transitions, you'll still need to overlap the two clips. You can just remove the automatic `fade` transition, and replace it with the one you want. Or you could right click on the automatic one, open properties, and change the source transition for it.

**Comment by Bentsman** [comment]
Why is it so complicated. Why can't I just drag the circle transition to the middle of two clips like you do with iMovie.

**Comment by JacksonRG** [comment]
I understand some confusion, and we might add a quicker way to switch the default transition to another one in the future.

The reason, is that transitions can be used in many ways. You could reverse one on the end of a clip and then add one to the beginning of the next clip for a full "fade to black" between two clips. But this way you can also place the transition on the overlapping portion of two clips, so that the second slowly covers the first.

Our choice to default to the simple fade was because it's the most used, (In fact many video makers use very short cross fades, avoiding hard cuts all together). I think you have pointed out room for improvement in how easily we can switch between our default transition and another.

**Comment by Bentsman** [comment]
JacksonRG Thanks for your reply. I do think that if you put these extra fades in like circle. They should work easily or don't put them in at all. Just keep the editor simple to use and reliable. I would like to use Openshot more often as I like using LINUX. But at the moment I am mostly using Apple iMovie. Keep up the good work though.

**Comment by JacksonRG** [comment]
@dhjw also made a good suggestion. You can place the first clip. Then put a transition on the end of that clip. Stretch it to cover however long you want the transition to be. Then snap the second clip to the beginning of the transition.

**Comment by JacksonRG** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Quickly Switch Transition Type](https://trello.com/c/tQEXaPoE/108-quickly-switch-transition-type)
