### ISSUE TITLE
error exportacion

### ISSUE THREAD

**Issue by marsa-coder** [OpenShot/openshot-qt#4812]
**Question:**
A clear and concise question. Your question should provide enough context and explanation for people to answer it. Avoid excessive background or irrelevant details, as they can obscure your actual question.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your question. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

Tengo problemas al exportar. Me dice A valid video codec could not be found for this file. Me podeis ayudar?
![open](https://user-images.githubusercontent.com/106393538/170726300-765bc6d4-d1c6-4b50-ae37-956682b5ffb0.png)

**Comment by JacksonRG** [comment]
@marsa-coder Hi, have you tried using our daily build? You can find it [here](https://www.openshot.org/download/). If that doesn't work could you include your log files? They will be in:
`Users\<your user name>\.openshot_qt\` and named  `openshot-qt.log` and `libopenshot.log`.

**Comment by mdrijwan123** [comment]
Hi, I am getting this issue while exporting the video using GPU hardware acceleration rather than CPU. Please help if there is any solution is available.
I am using 
OS: Windows 10
Open shot version: 3.0.0

![image](https://user-images.githubusercontent.com/35109373/218274964-c50ca95c-8b01-4b46-b196-c46e326c1ef1.png)

**Comment by coldnight-tw** [comment]
> Hi, I am getting this issue while exporting the video using GPU hardware acceleration rather than CPU. Please help if there is any solution is available. I am using OS: Windows 10 Open shot version: 3.0.0
> 
> ![image](https://user-images.githubusercontent.com/35109373/218274964-c50ca95c-8b01-4b46-b196-c46e326c1ef1.png)

When I installed handbrake, QSV was working. Maybe .NET is the key. You could try to install handbrake.

**Comment by Colorjet3** [comment]
Hello @coldnight-tw Hardware Acceleration is very experimental and not well supported in Windows at this time.

**Comment by coldnight-tw** [comment]
> Hello @coldnight-tw Hardware Acceleration is very experimental and not well supported in Windows at this time.

Hello @Colorjet3 , The CPU of my laptop is intel N6000, the performance is very weak. But with the acceleration of QSV, the export rate can reach 24 fps, which is about 3.4 times faster than without acceleration. I really look forward to using hardware decoding, The export rate should be able to exceed 30 fps.
![test-cpu](https://user-images.githubusercontent.com/131603949/234754248-8394ec45-4988-427d-8d4a-904bcec2bf14.png)

![test-QSV](https://user-images.githubusercontent.com/131603949/234754278-aad9c3ad-ea79-4db4-864a-0f11896ea947.jpg)

**Comment by Colorjet3** [comment]
Hello @coldnight-tw Thank you for the update and I am glad you are able to benefit from the QSV acceleration.  I don't hear enough of that from other users.  Here is a response from the Openshot DEV team regarding Hardware Acceleration:

• Hardware Acceleration in Windows is supported but limited. Those new settings that you see in Edit | Preferences | Performance tab are new, experimental, and not fully baked.
• NVIDIA NVENC acceleration is only available in Linux operating systems.
• OpenShot v2.6.0 and later includes Intel® Quick Sync Video encoding in Windows
operating systems. If you have a CPU that supports Intel®QSV encoding, you can use the encoder by selecting the ( QSV) MP4 (h.264 qsv) Target on the Export Video window. You do not have to change the Preferences window to use the Intel® QSV encoder.
• Hardware acceleration in OpenShot requires using the proprietary drivers from the distribution package manager instead of the NVIDIA drivers. You cannot use the Nouveau, Xorg, or open-source drivers.
• AMD is not yet supported.

There is more works being done by the development team to improve performance (without Hardware Acceleration) and also work on better support for Hardware Acceleration in future releases on all platforms.
