### ISSUE TITLE
Unable to add captions to the video 

### ISSUE THREAD

**Issue by sgupta0812** [OpenShot/openshot-qt#4813]
Issue: clicking on the 'plus' sign in the captions tab to add the timestamp does nothing.

OS: Windows 10 Pro, 64 Bit
Openshot: v2.6.1

**Comment by JacksonRG** [comment]
Hi @sg12056 , We've made some changes to how our captions work. Have you tried this with a daily build? They can be found [here](https://www.openshot.org/download/)

**Comment by JacksonRG** [comment]
Also the way it currently works, the first `+` creates a caption's `starting time`.

You can then move your playhead (the red line on the timeline) to the time you want the caption to end. As long as your cursor is on the same line as a `start time` and you click the `+` again an `end time` will be added.

**Comment by Colorjet3** [comment]
Hello @sg12056 If you are still running version 2.6.1.-release-candidate then check this out:  https://www.youtube.com/watch?v=6oDWM5SDZNU&list=PLqq8viq6f2kdP2q_qM4i4W4imHmGwasGG&index=24&t=9s.

If you are trying the daily build then follow what @JacksonRG suggests above.

**Comment by nickidw** [comment]
From a comment on the youtube video mentioned by @Colorjet3 , it seems the start and end times for captions are relative to the ORIGINAL clip (i.e. BEFORE any trimming). 

EDIT: I confirmed this is still the case with 3.0.0 today. So you either have to do your captions before trimming, or guess the timestamps after trimming to get captions to work correctly.

**Comment by Matt-B50** [comment]
Using v3.0.0.
The Plus sign does nothing.  I'd assumed I can click that to load a VTT or drag and drop the VTT, but... nothing. 
What you have to do is add the Caption filter to the video.  You can then paste in the VTT file content.
None of this is explained - perhaps a message is needed when you click the caption button?

**Comment by Colorjet3** [comment]
Hello @Matt-B50.  Please watch this tutorial regarding Captions:  https://www.youtube.com/watch?v=6oDWM5SDZNU&t=11s.  This is one way of doing it.  

The Green + sign in the Caption Editor window does work if you are focused in that window.  However, there is a specific steps you should take while using the + sign (lacking documentation for sure).

I can also tell you that some needed improvements are made to the Caption effect in the latest DEV Daily build.  I highly recommend downloading and running the latest DEV Daily build:
1.  go to openshot.org/download/#daily and download the latest available.
2.  Close Openshot if running.
3.  backup c:\users\username\.openshot_qt folder.
4.  delete c:\users\username\.openshot_qt folder.
5.  Install the latest dev daily build.
6.  You should be set.

I am assuming you are running Windows since you didn't mention what operating system you are running.
