### ISSUE TITLE
Make 32 bit windows version

### ISSUE THREAD

**Issue by Kulixich** [OpenShot/openshot-qt#486]
Can someone pls make 32 bit version for windows? I mean, cmon, there is A LOT people with 32 bit windows installed, older laptops, desktops etc. It would  be greatly appreciated.

**Comment by Kagetsuki** [comment]
@Kulixich If the machine has a 32bit CPU then I seriously doubt it would have the lifting power to be used well as a video editor. If the issue is simply that your installed Windows version is 32bit but you have 64bit hardware then I think it would perhaps be a better idea to install Linux and run OpenShot on that.

While I'm not fully aware of the intricacies of OpenShot I am aware that it has quite a few dependencies and I seriously doubt all of them are supporting 32bit builds. I expect a 32bit build of OpenShot would be a lot of work for very little reward.

**Comment by jonoomph** [comment]
@Kagetsuki explained it great. =) A ton of work for very few users, and although it's possible, it's just not worth the effort right now, unless lots and lots of people start requesting it. Thanks.
