### ISSUE TITLE
 No hardware acceleration  detection api nvenc with Geforce GT730 and Geforce GT 710

### ISSUE THREAD

**Issue by debaure** [OpenShot/openshot-qt#4873]
**Question:**
A clear and concise question. Your question should provide enough context and explanation for people to answer it. Avoid excessive background or irrelevant details, as they can obscure your actual question.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your question. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
• Hardware Acceleration in Windows is supported but limited. Those new settings that you see in Edit | Performance tab are new, experimental, and not fully baked.
• Hardware acceleration is still experimental in OpenShot Video Editor.
• NVIDIA NVENC acceleration is only available in Linux operating systems.
• OpenShot v2.6.0 and later includes Intel® Quick Sync Video encoding in Windows
operating systems. If you have a CPU that supports Intel®QSV encoding, you can use the encoder by selecting the ( QSV) MP4 (h.264 qsv) Target on the Export Video window. You do not have to change the Preferences window to use the Intel® QSV encoder.
• Hardware acceleration in OpenShot requires using the proprietary drivers from the distribution package manager instead of the NVIDIA drivers. You cannot use the Nouveau, Xorg, or open-source drivers.
• AMD is not yet supported.
