### ISSUE TITLE
Cache Limit not honored after restart

### ISSUE THREAD

**Issue by bricelam** [OpenShot/openshot-qt#4874]
**Describe the bug:**
The saved Cache Limit doesn't seem to take effect when OpenShot is reopened.

**Steps to reproduce the behavior:**
1. Go to Edit > Preferences > Cache
2. Set the Cache Limit to something big like 3000
3. Play the video to see that the cached frame indicator grows nice and big
4. Close and reopen OpenShot
5. Play the video and notice that only a handful of frames are cached
6. Go to Edit > Preferences > Cache again
7. Change the Cache Limit slightly to something like 3001
8. Play the video again and see that a lot more frames get cached

**Expected behavior:**
The Cache Limit should be honored between instances of the app.

**System Details:**
- OpenShot Version: 2.6.1
- Operating System / Distro: Windows 11

**Comment by JacksonRG** [comment]
Hi, was this tested in our daily build as well? We made some changes so that the cache doesn't run as far ahead, but does keep frames that have been displayed to be replayed. Indirectly this appears to have fixed this issue. If you want to test the daily build yourself to make sure this issue isn't more specific, please do. I'd be happy to hear.

If this does happen in the daily build, we'll re-open this and take a closer look.

**Comment by bricelam** [comment]
Confirmed. The daily build behaves as expected.
