### ISSUE TITLE
Black screen at end of video with MP4 format

### ISSUE THREAD

**Issue by SkybuckFlying** [OpenShot/openshot-qt#4877]
When trying to create a loop video a black frame is display at the end of the video.

Not sure if this is caused by OpenShot video or by VCL Media Player.

Most likely VCL.

The input video was made perfect by me, the output video was generated by OpenShot video, and produces a black frame in VCL media player when it's on loop mode. While the original input video created with virtualdub via image sequence converted into an RGB video/avi does not show this black frame.

Amazing how many issues these software packages have, shamefull !

**Comment by JacksonRG** [comment]
A couple steps we can use to track this issue further.

1. Can you view this video in any other viewers? Your browser should work as one, if you enter the path to the video file.
2. You can shorten the export by one or more frames to determine whether openshot is treating your source video like it's a frame longer than it is.

**Comment by Colorjet3** [comment]
Hello @SkybuckFlying Please confirm either way if this issue still exists in the latest DEV Daily build (openshot.org/download/#daily).

**Comment by therealchris** [comment]
No.  It's not fixed.  When I cut a mp4 clip in OpenShot and save it out in mp4, a black frame seems to be inserted at rhe end of the clip  ) - :     Annoying because when the clip auto-ends, the screen shows a black frame, instead of the final frame of the clip.
Unless....
.... I am missing something here.

**Comment by Colorjet3** [comment]
hello @therealchris.  You are not missing anything.  I was able to replicate this issue with the latest released version.  I am going to submit a bug ticket for this to be reivewed and fixed in the next release.

Update -  Here is the bug ticket for the development team to review:  https://trello.com/c/UYku50Wq/16-exported-project-ends-with-a-blank-frame-instead-of-the-last-frame-of-the-imported-video-file

**Comment by therealchris** [comment]
SUPER!  Thanks Colorjet.   Other than that Open Shot a great tool.    One thing -- I have also saved mp4's from OpenShot that DO show the final frame upon completion of the shot.   Not sure why??  I thought it might be the soundtracks.  Messed around with shortening them compared to the video.  (just for a bit -- I am busy)   Couldn't kludge a solution.    No idea what's happening

**Comment by therealchris** [comment]
Couldn't help it.  went and diddled around some more.  Took a shot that worked correctly, entered and saved it out using OpenShot.  Worked fine.  Repeated test.  Got a black frame  ) - :     Couldn't get correct result to repeat.

**Comment by therealchris** [comment]
one REALLLYYYY nice and maybe fairly simple fix would be to have OpenShot remember the folder you last saved to, so repeat tasks would not require navigating to the folder each time.   (noticed this while trying to run tests to see what was messing up the saves)

**Comment by Colorjet3** [comment]
Hello @therealchris.  Thank you for trying and the FYI.  When we get to this ticket the dev team will further kick the tires to get to the bottom of it.

By the way, start Openshot and go to Edit | Preferences | Location tab.  You can control the behavior of how Openshot shot remembers where you import files from, what your Save or Open a project from, and where a Video gets Exported.

**Comment by InklingGirl** [comment]
This is still an issue.

**Comment by ConfusedToaster** [comment]
Can you try:
Export Video > Advanced > Advanced Options > Subtract 1 frame from the end frame of the video

It worked for me.

**Comment by InklingGirl** [comment]
Thank you so much @ConfusedToaster! This:
> Export Video > Advanced > Advanced Options > Subtract 1 frame from the end frame of the video

works well, but boy is it annoying to have to rely on a workaround like this.

**Comment by therealchris** [comment]
Huge thanks to ConfusedToaster (and cool name!)

Totally agree with Christian's comment, "... but boy is it annoying to have
to rely on a workaround like this."

On the other hand -- having built ground-up software myself -- it's way
easier to complain than perfect.
Gooooo, Openshot.  And thanks for the effort so far!

**Comment by Colorjet3** [comment]
This bug is in the queue:  https://trello.com/c/UYku50Wq/20-exported-project-ends-with-a-blank-frame-instead-of-the-last-frame-of-the-imported-video-file

Thank you @ConfusedToaster for the workaround!

**Comment by EburgGuy** [comment]
The workaround did not work for me.

Just to make sure it was still messing it up, I tried exporting both with extra frames removed (up to 10 of them) and extra frames added.

In every single case, as soon as I hit the "export" button, it reverts to the original number of frames.

Any other ideas?

**Comment by ConfusedToaster** [comment]
> In every single case, as soon as I hit the "export" button, it reverts to the original number of frames.

It only seems like that, can you try watching the exported video and check if the frames are gone?

**Comment by EburgGuy** [comment]
The extra frames remain.

**Comment by EburgGuy** [comment]
@ConfusedToaster yes, I exported it, trimmed off 100 frames from the end when doing so, and it still ends with a blank frame.

**Comment by Colorjet3** [comment]
Hello @EburgGuy.
1.  What version of OpenShot are you running (help | about Openshot)?  Please include the build # which you can find in the 3rd line of the About OpenShot page (...-99999-...).
2.  What operating system/version are your running (Windows 10 Pro?  Ubuntu 22.04 lts? etc.).
3.  Did you try to subtract only 1 frame first and the 100 and the result were the same?

**Comment by itaispector** [comment]
> The workaround did not work for me.
> 
> Just to make sure it was still messing it up, I tried exporting both with extra frames removed (up to 10 of them) and extra frames added.
> 
> In every single case, as soon as I hit the "export" button, it reverts to the original number of frames.
> 
> Any other ideas?

same here. this is really frustrating

**Comment by Colorjet3** [comment]
The "reverting" of the Start and End frames fields is a known issue.  However, OpenShot still should be honoring the numbers you enter.  Meaning, if your Start =1 & End = 5000, but you change Start to 500 and End to 2000, when you click Export, even thought the numbers revert back to 1 & 5000 the exported file should be frames 500-2000.  This works for me.

Now, if you are still getting a black frame at the end even though you might subtract a frame or 2 from the end then the workaround isn't working.  The lead developer will have to look into it.

**Comment by RedKrieg** [comment]
@EburgGuy I ran in to this today.  If you're changing the frame rate of your profile, you have to go back afterward and subtract one from the *new* end frame value.  The initial value for me was based on 30fps when my export was intended for 6fps.

**Comment by Colorjet3** [comment]
Thank you for the FYI @EburgGuy.  Can you please confirm which version of OpenShot you are running and in which environment (Windows 10, Ubuntu 22.04 lts, etc?).

If you haven't tried the latest dev daily build please give it a try (openshot.org/download/#daily).  Test with a video/audio file that you know you've had this issue with and do this:

1.  Install the latest dev daily build and start OpenShot.
2.  In a new project, import your video/audio file.
3.  Right click on your file in the "Project Files" window.
4.  Click on "Choose Profile".  This is an new feature which just got added.  OpenShot will now show you the profile of your video file, assuming it isn't something that is not common.  Select it and your profile, for your project, will change to your video/audio file profile.
5.  Now do whatever editing you do, and then export and let us know if you still get an extra black frame at the end of the exported file.

**Comment by Colorjet3** [comment]
Just as an FYI as several comments not related to this issue were made:

1.  By @therealchris - "one REALLLYYYY nice and maybe fairly simple fix would be to have OpenShot remember the folder you last saved to...."

In Openshot, go to Edit | Preferences | Location tab.  You will note that you can control the "File Import", "Save or Open Project", and "Video Export" folders behavior.  By default they are set to "Project Folder".  This means any time you try to import a file, save or open a project, or export a video, it will default to wherever your project file is saved (the projectname.osp file).  You can change this behavior for each of the tasks by changing the setting from "Project Folder" to "Recent Folder".  From now on, OpenShot will remember the last folder you imported from, or saved/opened a project from, or exported your project to. 

2.  By @itaispector - Reverting of the Frame Number.  This has been fixed in the later versions of the dev daily build.

**Note:**  The latest dev daily build now has persistent Export settings.  Meaning, for any specific project, it will remember your last Export settings and maintain those until you make a change.  This is really nice to have if you say edit in one specific profile but you like to Export using a different profile and other customization.

3.  You now have the ability to change your default profile for OpenShot, or a specific project in OpenShot, to match one of your imported files.  You can do this by right clicking on a file in the "Project Files" windows, select "Choose Profile" and then select the profile that is displayed, which is the profile of your imported file.

**Comment by wayne931121** [comment]
If any answer cannot deal with this, you can do it:
first get frame count:
` ffprobe -v error -count_frames -select_streams v:0 -show_entries stream=nb_read_frames -of csv=p=0 input.mp4`
second let the last frame cannot into output video
`ffmpeg -i input.mp4 -frames:v ${frames count - 1: if frame count is 227, then here is 226} -c:v copy -c:a copy output.mp4 `
Done
