### ISSUE TITLE
Titles on meme videos

### ISSUE THREAD

**Issue by TriangleBoii** [OpenShot/openshot-qt#4931]
**Question:**
I want to make a bit of a meme video. So I want to have the title to be on top of the said video. But when I make a blank white title, it is overlaid (or superimposed) on the video instead of appearing above it. 

**System Details:**
- OpenShot Version: 2.5.1
- Operating System / Distro: Windows 11

**Comment by JacksonRG** [comment]
In the preview, when you have a certain clip (or title) selected on the timeline, you can move it so that it's outside of the video. (You might need to scale the original video smaller to fit both in the resulting video.

Also when you do this, remember that where you are on the timeline matters. If you don't want the positions to move throughout, put the playhead at the beginning of the clip, then move it to the position you want.
