### ISSUE TITLE
Integration of plugin called "Destruction Pack"

### ISSUE THREAD

**Issue by frankinstien111** [OpenShot/openshot-qt#4955]
**Describe the new feature:**
The ability to use third party plugins that add video special effects.  Destruction Pack is a plugin that can work
with the most popular commercial video editing tools, so it would be very helpful if OpenShot could have such a feature 
as well.

**Describe the solution you'd like:**
An ability to integrate "Destruction Pack" into the OpenShot video editing workflow.

**Describe alternatives you have considered:**
I don't know of any alternatives.

**Screenshots:** (Optional)
https://bigfilms.shop/products/destruction-pack

**Comment by jonoomph** [comment]
@frankinstien111 Since "Destruction Pack" utilizes transparent *.mov video files, it "should" be compatible with OpenShot's general editing flow. Have you actually tried placing some of their assets in OpenShot, to see what happens? Closing this ticket until we can confirm these *.mov video files fail to work in OpenShot. Thanks and please keep us posted on the outcome.
