### ISSUE TITLE
Slow playback and freezing/crashing; Also captions moved

### ISSUE THREAD

**Issue by GitHeart16** [OpenShot/openshot-qt#4966]
**Describe the bug**
I was seeing slow playback, freezing and crashing. In trying to resolve that, a new problem emerged. Several captions changed location on screen and one appears at a different time now. The initial freezing, crashing has not been resolved either.

**Steps to reproduce the behavior:**
For freezing/crashing I followed directions in tutorials. 
1. Changed computer settings to optimize performance.
2. Shrunk the preview window size
3. Changed the profile to 720p 25fps
4. Then followed directions found here: https://www.reddit.com/r/OpenShot/wiki/commonproblems/#wiki_-why_is_openshot_is_crashing_or_freezing.3F
5. Following install of Daily build on 10/27/2022 I again changed profile to the small 720p 25 fps and tried to playback and freezing persisted. That is when I also noticed captions had moved. None of the profile elements (left size, right size, top size) had changed.
6. For the captions I thought that when I changed from 1080p 60fps to the smaller 720p perhaps that somehow created a bug that moved the captions. I tried changing it back but problem persisted. The slow playback and freezing/crashing has persisted as well.
7. I downloaded the Daily Build 10/28/22 and got all the same results as described above.

**Expected behavior**
I expected playback to be smooth. And I didn't expect my inserted captions to move when I hadn't changed any elements.

**System Details**
Processor Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz 2.50 GHz

Installed RAM 8.00 GB (7.75 GB usable)

System type 64-bit operating system, x64-based processor

OS WIndows 11 Home v21H2

Storage Local Disc 93.9 GB used of 222 GB (128 GB available)

Open Shot v 2.6.1. Verified problem still exists after downloading daily build on 10/28/22

No other 3rd party apps installed

**Log Files**
             
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/9892532/libopenshot.log)

[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/9892533/openshot-qt.log)

**Comment by Colorjet3** [comment]
I am trying to replicate the issue you have reported.  I am running the latest DEV Daily Build #10080 in Windows 10 Pro 64-bit with the latest windows updates.  I have a request and a few questions:

1.  Changed computer settings to optimize performance:  please elaborate on this unless you meant you tweaked OpenShot per the video?  If not Openshot then how did you tweak your Windows environment?

2.  Did you perform a clean installation?  If not, please follow the instructions here:  https://github.com/OpenShot/openshot-qt/wiki/Clean-Installation-of-OpenShot.

3. A bit more detail about your project, please:
- When you first start OpenShot, what is your default profile set at?  You can see this in the Title menu right above the menu bar.
- What kind of files are you working with (jpg, mov, mp4?).
- When you import your image and/or video file, then you right click on it and select File Properties, what are the dimensions and FPS values?

I am running build 10080 in both Windows 10 & Windows 11 environments and testing with very large projects and not experiencing freezing or crashing.

I would like to concentrate on the freezing/crashing issue first then we can look into the Captioning issue, which should be a new thread (I am curious how you created your Captions, did you use the Caption effect or did you create Titles or something else)?

**Comment by GitHeart16** [comment]
Thank you so much for taking a look at this!  Answers below:

1. All I did here was in the System Power & Battery settings I changed my selection from Best Power Efficiency to Best Performance.

2. Yes. I forgot to indicate that in my description. But I have done a clean install--twice actually.  The first time I downloaded OpenShot it was freezing when the only thing in my project was a 3 minute test clip.  I reinstalled and OpenShot was running clean until the problem I described above.  At that point I reinstalled and included the Daily Build.

3.  The other details:

-    My default profile is 720p 30fps (this was one of the adjustments I made to try to resolve the freezing. I plan to change it back to 1080p 30fps when the project is complete.
- Videos are all MP4. There are 3 jpg files. And audio is m4a.  (Its worth noting, and maybe this is significant--when I imported the audio files they could not be imported to the audio tab.  They kept snapping back when I tried to drag them so I used the "All files" tab and imported them.  They were dropped in the video tab and they've stayed there.  The audio files have a still image attached to them, so perhaps that's why its dropped in Video.
- File properties for the videos are 1920x1080 30fps. Since the audios seem to have images attached they also have dimensions indicated. They're 600x600 and 30fps.

Yes, thank you...the freezing/crashing is definitely the biggest problem since resolving that is necessary for me to address anything else.  

I used the Caption effect to create them and then manually changed the locations on screen by adjusting the left. right and top size. All was running smoothly and they looked great...until I did the clean install and tried to view my video again.

**Comment by Colorjet3** [comment]
Thank you @GitHeart16 for all that information.

1.  Your Windows environment.  There are many other performance tweaks that can be done.  I am not saying this is the solution but it is good housekeeping to have the Windows environment fine tuned and healthy as Video Editing software is demanding.  go to this site:  https://support.microsoft.com/en-us/windows/tips-to-improve-pc-performance-in-windows-b3b3ef5b-5953-fb6a-2528-4bbed82fba96.

a.  I would only do step 1 & 4.  The Paging file will help the most. 
b.  Ensure that you have the latest drivers for your hardware as well (GPU, Hard Drive, etc.).
c.  By the way, what kind of hard drive do you have (SATA, Nvme, M.2)?  Upgrading to a faster hard drive will make a big difference.
d. Is your device a laptop?  If yes, typically much slower so you will see some performance issues.
e. If you can add more RAM that will help as well as there are some fine tuning you can do inside of OpenShot as well.


Note:  Do this only after you tried step 2 below:  Another Windows health check is here:  https://www.windowscentral.com/software-apps/windows-11/how-to-use-dism-to-repair-local-image-on-windows-11

This should eliminate any possible Windows issues.

2.  Back to OpenShot and your project.
a. Please confirm that you are running daily build 10080 as there were two release on 10/28.  I just want to be sure you are running the latest daily build.  In OpenShot, click on Help | About Openshot, and note v2.6.1-dev-nnnnn-......  The nnnnn is the build number.
b. Give your porject a try again after confirming the build # and completing step 1 above.  If problem persists continue to 2.c.
c. The .m4a.  Most likely that is the cover label which caused OpenShot to treat it like a Video.  What I recommend is that you convert this .m4a to a .wav or .mp3 using a tool like Audacity.  Then import it into OpenShot and see how it works.
d. Try this experiment to further troubleshoot.  Start a new project, import one of the .mp4's and save it as Test01 or something.  Edit by dragging onto a track and manipulate it.  Does OpenShot crash?  Continue importing the other .mp4s, one at a time, edit, and see the behavior of OpenShot.  Continue doing this till you run into an issue.

I am suspecting the .m4a that might be the cause of the issue here.

**Comment by GitHeart16** [comment]
Thank you @Colorjet3 for all your help! I'm working my way through the steps you suggested.

Meanwhile I have a quick question re conversion to mp3. I've come across Audacity before and just curious to understand the benefits of using it. Is the conversion method available directly through iTunes glitchy and that's the reason for using 3rd party?(This is the conversion method in iTunes that I'm referencing: https://support.apple.com/en-us/HT204310 )

Thank you again and I'll touch base after I've worked through your suggestions.

**Comment by Colorjet3** [comment]
Hi @GitHeart16 .  I still consider myself a novice video editor but what I have come to learn about all these audio formats is that they have differences in compressions, sample rates, encoding formats, etc.  Running through a converter like Audacity will sometimes fix issues or better align an audio track for better consumption by other tools that play audio (VLC, iTunes, media player, etc.).  

I don't know much about iTunes or how it compares/differs from Audacity.  I think if you post your question at https://www.reddit.com/r/VideoEditing/ you will get a much better answer.

**Comment by GitHeart16** [comment]
Thank you @Colorjet3! I do appreciate your time with all of this.  

I've finished with computer/driver updates; and since so much time has passed since my initial post I've now downloaded the latest daily build #10148.  Unfortunately all the same problems remain, and somehow new problems have been created. I did convert all the audio files to mp3 (I used the iTunes method, so if that does somehow create an inferior mp3 then maybe that is still part of the problem).

The freezing, etc still exists and now unfortunately the audio portion of a video track now plays at a higher speed (voices sound like chipmunks) and even more of the captions have moved to incorrect spots on the screen. 

Somehow these project files seem to have become corrupt. I'm afraid I've run out of time to troubleshoot the software for this project so I've borrowed a friend's computer with different software and I unfortunately need to start over. Gah. 

I hope I can return to have greater success with OpenShot in the future. Thank you again for your attempts to help!

**Comment by Colorjet3** [comment]
Sorry to hear about the all the issues you are running into @GitHeart16.  Makes all sense to move forward with another solution for now.  I am confident that OpenShot will be much more stable and functional when you come back to give it a try in the future.

**Comment by GitHeart16** [comment]
Thanks @Colorjet3! Me too. I really enjoyed most of my experience with it. Cheers!
