### ISSUE TITLE
Always keep the cache when moving the play-head

### ISSUE THREAD

**Issue by Jonas-July** [OpenShot/openshot-qt#4967]
**Describe the bug:**
When moving the play-head just outside the cached timeline, then the cache is recalculated and previously cached frames aren't used anymore.
This doesn't happen if the play-head stays within the cached section.

**Steps to reproduce the behavior:**
1. Open a project (preferably with some expensive effects)
2. Set the cache limit very high (e.g. 4096 MB) and make the preview window very small. This mainly avoids running into the cache limit.
3. Make sure that the cache is generated by a) seeing the blue bar above the timeline increase and b) playing the video at the expensive section after they are cached
4. Move play-head just outside the blue bar
5. See that the blue bar disappears entirely
6. Go immediately back to the previously cached expensive section
7. Observe that the expensive section is now played way slower than before

I also monitored the RAM usage as it increased with the cache, so it does get filled up. However, when the cache was seemingly deleted (i.e. the blue bar disappears), then RAM usage didn't go down. On the other hand, it also didn't go up when the cache was refilled, so at least the same instance seems to have been used.

On request, I can provide screenshots and video clips of what I'm seeing.

**Expected behavior:**
The cache should a) only delete the least recently used frames and b) only once the cache limit is reached, as no frame has changed by moving the play-head.

**System Details:**
- OpenShot Version: 2.6.1-dev, built freshly today from git via [openshot-git](https://aur.archlinux.org/packages/openshot-git)
- Operating System / Distro: Arch Linux with up-to-date packages

Thanks in advance

**Comment by Colorjet3** [comment]
What you are seeing with the Cache behavior is exactly what I am also seeing in Windows 10 & Windows 11.  Your feedback/insight is greatly appreciated.  I am a tester for OpenShot.  The lead developer for OpenShot is making lots of improvements with Caching and improving the performance while editing and previewing so this is work in-progress.

Make a note of several Cache settings are now exposed to users to tweak the behavior of the Cache in Edit | Preferences | Cache tab):

1.  Cache Pre-roll: Min Frames: minimum # of frames that must be cached before playback begins. The larger the #, the larger the wait before playback begins.

2.  Cache Pre-roll: Max Frames: maximum # of frames that can be cached during playback (in front of the playhead). The larger the #, the more CPU is required to cache ahead - vs display the already cached frames.

3.  Cache Ahead (Percent): Between 0.0 and 1.0. This represents how much % we cache ahead of the playhead. For example, 0.5 would cache 50% behind and 50% ahead of the playhead. 0.8 would cache 20% behind and 80% ahead of the playhead.

4.  Cache Max Frames: This is an override on the total allowed frames that can be cached by our caching thread. It is defaulted to 600 frames, but even if you give a huge amount of RAM to OpenShot's cache size, this will override the max # of frames cached. The reason is... sometimes when the preview window is very small, and the cache size is set very high, OpenShot might calculate that we can cache 30,000 frames, or something silly which will take a huge amount of CPU, lagging the system. This setting is designed to clamp the upper limit of the cache to something reasonable... even on systems that give OpenShot huge amounts of RAM to work with.

Try this to see how the behavior of the Cache changes (positive or negative):
1.  Change the Pre-roll: Min Frames from 12 to 24
2.  Change the Pre-roll: Max Frames from 24 to 48
3.  Leave the Cache Ahead at .70
4.  Leave the Cache Max Frames at 600
5.  Leave the Cache Limit:  at 4096.

My experience with this setting is that when I move the playhead outside of the blue bar, I don't experience the slow down even though the Cache limit hasn't had a chance to rebuild fully (because I am in continuous play mode).  However, because the pre-roll numbers were doubled, OpenShot is more aggressive in reading ahead.  Once you Pause then the Cache is rebuilt.

Doubling the Pre-roll min & max to 48  & 96 respectively gets even more aggressive and the Playhead does not catch up to the blue cache bar as it is more aggressive in reading ahead.

These setting are also impacted by the hardware configuration you have (a powerful machine vs. a slower one).

You can also up the Max Cache Frames from 600 to 800 to 1000 (this is the limit) if you are manually typing in.  However, you can use the up / down arrow key at the end of the field to up the number (not sure if this is a bug in the code at this time).

On the positive, you don't have to have your "Video Preview" window too small when editing/previewing like you had to with previous builds to improve performance.

Would love your feedback as this will help the lead developer as well to ensure the consistency in behavior as we tweak those settings.

**Comment by Jonas-July** [comment]
Hi, thanks for the response!

My `Pre-roll: Min Frames` and `Pre-roll: Max Frames` were already at 24 and 48 respectively (though I didn't change them), so I doubled them again to 48 and 96. This did at least fix the lagging and stuff (after it loaded the first 48 frames of course), so I will keep this option in mind.

This, however, isn't the issue I'm having, fundamentally. Why do I need to recompute those Pre-roll frames at all, when I already had them in the cache, just because the playhead is a frame too early causing the entire cache to be cleared?
Frames should only be removed from the cache if they have been changed or if the cache is full. In the latter case, only enough frames should be removed to keep the cache size within the specified limit.

So I guess that the new settings can provide a good heuristic of whether to _add_ a frame to the cache, but don't have much to do with clearing the cache, which is what my issue is about.

**Comment by Jonas-July** [comment]
Also, when I let the entire video run through, then the cache fills completely, not only the last x% and the next y% from the playhead and obviously more than the 600 Cache Max Frames. And I think this is the correct behaviour.

Minor note: `Cache Max Frames` goes up to 1024, which can also be typed in (1025 cannot be typed in though, it stays at 102). So I don't think that's a bug per se, but usually the number in the field would go the maximum allowed (i.e. 1024 in this case).

**Comment by Colorjet3** [comment]
Thank you @Jonas-July for the FYI.  We will see what @jonoomph (lead architect/developer) will say about all this.  Also, thank you on the insight regarding the "Cache Max Frames".

**Comment by Jonas-July** [comment]
It's nice to see that the cache is being worked on. I originally came from the released 2.6.1 version and it was ... very different.
So I was positively surprised when I tried out the dev version :+1: 

Yeah, let's see how we can progress further on this matter
