### ISSUE TITLE
openshot crashes while exporting video made of images

### ISSUE THREAD

**Issue by ghost** [OpenShot/openshot-qt#4993]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 2.6.1-dev
- libopenshot Version:  0.2.8-dev
- Platform: Windows-10-10.0.22000
- Processor: Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v2.6.1-dev-daily-10243-854a3aa3-46255e46-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/reo2jw2k0o6c9qnkfiov8m2a9n6sfqm9/openshot-qt.zip) (155 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/reo2jw2k0o6c9qnkfiov8m2a9n6sfqm9/libopenshot.zip) (0 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
1.  Which daily build # are you running?  Help | About Openshot and you should see something like 2.6.1-dev-nnnnn----.  The nnnnn would be the build #.

2.  Tell us a bit more about your project:  the number of images? what type of image files? are you using any effects, etc.  

3.  Did you go through this process for capturing verbose logging?  I ask because your libopenshot.log file is 0 bytes which does not make sense.  Please follow the bug reporting process here:  https://www.openshot.org/issues/new/

4.  You can also download the latest DEV Daily Build and give it a try.  go to openshot.org/download/#daily and download and install the latest DEV Daily Build available.
