### ISSUE TITLE
Allow OpenShot to open links to media files 

### ISSUE THREAD

**Issue by shodanx2** [OpenShot/openshot-qt#5036]
For organisation purpose, I have links to my media files in large projects
So that I don't have multiple copies of these very large files

But when I try to drag and drop those shortcuts into the openshot UI, it doesn't dereference them and instead complains that it isn't a valid video, audio or image file !

![image](https://user-images.githubusercontent.com/10621885/206969722-0ceedf81-a881-4904-917a-58d68dd35aae.png)

**Comment by sc0nway** [comment]
As I understand the way OpenShot works, the program already uses links to your files.  OpenShot does not load your files into the application, but uses a link to the clip, then allows you to modify the linked clip in memory.  Therefore, OpenShot cannot load a link to the link to a video because the second link is not a clip for OpenShot to manipulate, and you receive the error message above.

To accommodate your request, our developers would have to rewrite the file handling and clip editing systems with safeguards allowing for recursive and possibly endless links.  We'll add your suggestion to our list of feature requests.  The more people that add their voices to your proposal, the more support we'll have for adding your request to OpenShot.
