### ISSUE TITLE
Split Audio Tracks hangs

### ISSUE THREAD

**Issue by thesamim** [OpenShot/openshot-qt#5045]
**Describe the bug:**
Splitting audio into multiple clips (two audio tracks) hangs the application. Also if video is on last track, the audio tracks do not get added, but seem to overlay the original track. eg: if Video is in track 1, at the bottom, it looks like the audio tracks are added to track 1. But not able to verify since application hangs.

**Steps to reproduce the behavior:**

1. Right click video just added to track
2. select split audio into multiple clips
3. wait patiently
4. Spinner never goes away

**Expected behavior:**
Audio tracks split into multiple tracks, and able to use the application.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
-     "version": {
        "openshot-qt": "3.0.0",
        "libopenshot": "0.3.0"
      }
- Operating System / Distro: Windows 10 version 22h2 (os build 19045.2311)

**Log Files:**
attached

**Exception / Stacktrace:**
no crash just hang

**Screenshots:** (Optional)
just hangs

[libopenshot.zip](https://github.com/OpenShot/openshot-qt/files/10238186/libopenshot.zip)
[openshot_qt.zip](https://github.com/OpenShot/openshot-qt/files/10238188/openshot_qt.zip)

**Comment by Colorjet3** [comment]
1. Does this happen with other audio files?
2. Have you tried splitting the audio file using the Razor tool (scissors icon)?  If not, give it a try and see if you get the same result?
3. Go to Edit | Preferences | Preview tab and change your Audio Sample Rate to 48000 (I am going to assume it is set to 44100).  Restart Openshot and try again.

**Comment by thesamim** [comment]
> 1. Does this happen with other audio files?
Don't understand the question. This is splitting audio tracks from a Video track. As in: I want the audio tracks to be separate from the video track  so I can adjust the audio timing. (use case: one of the sound sources is 30 ms ahead of the other sound sources and the video track resulting in echo....)

>     2. Have you tried splitting the audio file using the Razor tool (scissors icon)?  If not, give it a try and see if you get the same result?
Unless I'm misunderstanding, I thought the razor tool was for cutting up audio clips, not extracting audio from a video file. Please let me know what I'm missing.

>     3. Go to Edit | Preferences | Preview tab and change your Audio Sample Rate to 48000 (I am going to assume it is set to 44100).  Restart Openshot and try again.
Sample rate was already at 48000. Changed my default review to HD 1080 60 fps to match my project. Restarted.  Same results: Hangs.

NB: The project is not saved when OpenShot exits after hang.

Tried again with a much smaller clip, in case it's a memory usage thing (I have 32 g of memory though), same results.

**Comment by Colorjet3** [comment]
I think we are just stuck on semantics. Split, vs. extracting vs. separating.

Please tell me the exact steps you are taking so that I understand exactly what you are doing and see if I can replicate your issue.

**Comment by thesamim** [comment]
> I think we are just stuck on semantics. Split, vs. extracting vs. separating.
> 
> Please tell me the exact steps you are taking so that I understand exactly what you are doing and see if I can replicate your issue.

1. New Project
2. Import Video Clip
3. Add Video Clip to timeline
4. Right click on Video Clip
5. Click on "Separate Audio"
6. Click on "Multiple Tracks"

Expected behavior:
Timeline shows one (1) video track and two (2) audio tracks (two tracks recorded on video)

Actual behavior:
Wait spinner shows, and never goes away.
Assuming a hang. 
Found on later tests that I can actually still click around the UI but results are not predictable.

**Comment by Colorjet3** [comment]
Thank you for that.  Here is my testing results in Windows 10 Pro 22H2 (OS build 19045.2364)

1.  Working with a .mp4 file and was able to Separate the audio without any issues (Multiple Clips).
2.  I moved the .mp4 to the last track and was also able to Separate the audio successfully.  However, what happens here is that because there are no tracks below it it overlays the actual video file on the track(you essentially have 3 clips overlaying each other).  You can now individually move the separated audio clips(un-layering).

A. What type of a video file are you working with?  Try a different type of a file and see if you have the same issue.
B.  How big is this video?
C.  Go to Edit | Preferences | Cache and tell me what your setting are?
D.  Run your video file through a converter like HandBrake, VLC, or Shutter Encoder and convert to .mp4 (even if it is a .mp4 already).

**Comment by thesamim** [comment]
Can confirm: no issues with mp4 file.

> A. What type of a video file are you working with? 
.mkv file. Output from OBS. 

>B. How big is this video? 
997,104 kb

Chopped the video down to two minutes and tried again. Same result. ie: don't think size is the issue... Looking for a way to export just two minutes into a .mkv file. Will update if I find a reasonable solution


> C. Go to Edit | Preferences | Cache and tell me what your setting are? 
Please see attached screen shot.


> D. Run your video file through a converter like HandBrake, VLC, or Shutter Encoder and convert to .mp4 (even if it is a .mp4 already).
Problem (at least with VLC) on converting to mp4, the two audio tracks are merged into one when I export to .mp4

![openshotcachesettings](https://user-images.githubusercontent.com/5315625/208166346-5b8b93cf-dca9-4915-95ba-6b51a9460373.png)

**Comment by Colorjet3** [comment]
Thank you for all this information.

1. Please change your Cache Limit from 512 to 4096 and restart OpenShot (even though it doesn't ask you to do so).  
**Note:**  do not make this too large.  There are some known issues that will make editing experience painful as the Cache Continuously tries to rebuild.

2. Start a new project, import your .mkv file and drag it onto the top most track (most likely track 5).  You will notice a blue bar growing right above track 5.  That is the Cache Limit bar.  Let it grow until it stops.

3.  Now select your clip and Separate Audio again.  

5. When you see the hour glass, just wait a bit longer.

6.  After say 10 seconds or so, if you are still seeing the hour glass, click on the clip once and wait.  You may notice the OpenShot screen turn whitish.  Wait till its done.

Another trick to try is:
1.  Import your .mkv file and drag it onto a track (this is a new project).
2.  Export it (leave all the defaults on this screen except for the file name).
3.  The output will be a yourfilename.mp4.
4.  Now import this into OpenShot and try the Separate audio again.  Leave all your Cache Limit settings the same.

Let me know how it goes.

**Comment by Colorjet3** [comment]
I just wanted to confirm something as well with your .mkv file to know that you are positive you have two audio channels.  On my computer I just have a Logitech C310 Camera that only records in a single channel so I can not record with two channels.

May be you can share your .mkv file with me and I can play with it as well.

**Comment by thesamim** [comment]
Waited for an hour, OpenShot never recovered. Even after cutting down to two minutes.

> I just wanted to confirm something as well with your .mkv file to know that you are positive you have two audio channels. On my computer I just have a Logitech C310 Camera that only records in a single channel so I can not record with two channels.
> 
> May be you can share your .mkv file with me and I can play with it as well.

Yes, positive: Track 1 is the audio from a QSC Mixer, Track 2 is the audio from a Yeti microphone.

I apologize, i don't know enough about MKV files to split into a smaller file without losing the audio tracks and haven't found a tool to do it. I have uploaded the file to my google drive:
https://drive.google.com/file/d/1F0Dj9gUp7HXVx_gPHcCpG7JjDU5jiyev/view?usp=sharing

It should be publicly accessible. Please let me know if you have issues getting to it.

In the first two minutes, you will see me walk up to the lectern and do some clapping. My primitive way to get to the point where I can sync up the tracks. You may notice that Track 2 is about 30 ms behind Track 1 and the video. Hence the need to shift audio and video tracks to get alignment. (aside: yes I realize if I could get the tracks to align in OBS, I wouldn't have to go through this, but our church network is not particularly reliable. (video over NDI, sound over USB))

Thanks for all the time you've spent on this so far.

**Comment by Colorjet3** [comment]
Hell @thesamim Thank you for the file.  No issues downloading it.  Here is what is interesting.  After I Separated the audio, the hour glass (the mouse) never goes away.  However, the audio channels get separated but don't get processed correctly, meaning it is taking forever to change the thumbnail to audio only display.

Openshot also became painfully sluggish...obviously waiting to complete the Separate process.  I am in the process of converting the .mkv file to a .mp4 file using HandBrake to see if that makes it work better.

I'll provide another update once my testing is completed.

**Comment by Colorjet3** [comment]
OK.  I think I have a solution for you.  Not the most efficient but at least you can get your project completed.

Split your .mkv into smaller chunks (5 min).
1.  Download HandBrake (Open Source).
2.  Drag your .mkv file into it.
3.  To the right of the Title: field you will find the Range: field.
4.  Click the drop down menu and select seconds.
5.  Now start with 00:00:00 - 00:05:00.
6.  From the Summary tab, note the Format:  field.  Select .MP4 or .MKV.  If you leave it at MP4 then be sure to change the file Extension to .MP4 in the Save As:  field at the bottom.  Obviously name the file as you please.
7.  Now click on Start Encode at the top.
8.  Experiment with one by importing it into OpenShot and see how it works.  Five minute chunks was manageable for me.
9.  If you are happy with the 5 min. chunks you can queue up the splitting part in Handbrake.
10. After you select your time range, instead of clicking on Start Coding, click on Add to Queue.  You will have to change the file name for each range so you don't overwrite (you will be warned).
11. Once you have all your ranges in the queue.  Click on Start Queue.
12. Walk away and let the process complete.

Start editing:
13.  Now that you have your smaller chunks of your original clip, start importing them and editing.
14.  I would import them one at a time.  Save the project before you start doing anything.
15.  Now drag and Separate the audio.  It will still take a few seconds for the Separate function to complete but it should work.
16.  Tips for performance.
a.  Go to Edit | Preferences | Cache tab
b.  Change your Cache Limit to 1024 max.  Doesn't matter how much available RAM you have.  If you make this large it will negatively impact performance while editing (this is going to be worked on in the next minor release).
c.  When you are done with editing and you want to preview, then change the Cache Limit to 4096 or 8192.  You will note a blue bar right above the top most track building up when you are not playing.  Let the Cache build up and then click play to preview.  While scrubbing the playhead, as long as you are withing that cache bar OpenShot is very smooth and responsive.  Once you get out of the blue bar range the Cache bar starts rebuilding and this process is slow.
d.  If you start editing, change back to 1024 for Cache Limit.
e.  I have found that I do not have to restart OpenShot when changing the cache limit.  However, I do it any way.
f.  Save your project often.

I hope this does the trick for you.  I tried to edit your original file with another editor, it couldn't even import it.

**Comment by thesamim** [comment]
Thanks for trying. But if I have to go through all that I'll stick with DaVinci or Shotcut. They may be slow, but they get there in the end. Just tried in Kdenlive, and that's working too.

Is there any chance that this is an issue that will be resolved in the future? I'd like to give OpenShot another try.

**Comment by Colorjet3** [comment]
No worries.  I am sure it is an issue.  I have to submit to the Developer.  This is a very small team and being Opens Source dependent on volunteers.  I am sure it will be resolved in the future, I just couldn't tell you when.

By the way, I wanted to let you know that using HandBrake you can compress your file without losing quality of your video.  This will make managing the file a bit easier for Video Editors.  Since you mentioned that DaVinci Resolve or Shotcut as also slow (I don't know how slow), compressing the file hopefully will improve your performance.  

The file you shared with me went from 997,105KB to 468,826KB.  That is a considerable compression.  You may want to experiment with it to see if that makes it easier for you to edit in any video editor.

**Comment by thesamim** [comment]
Thanks @Colorjet3 . Will keep an eye out for the release notes.

**Comment by thesamim** [comment]
@sc0nway : Saw you closed this. Does that mean it's fixed?

**Comment by Colorjet3** [comment]
Hello @thesamim No, this is not fixed.  We closed it because you had indicated you found other video editor(s) that can handle this large file.  This issue will be documented, reviewed, and at some point prioritized to be worked on.

**Comment by thesamim** [comment]
Got it. 

 

Thanks.
