### ISSUE TITLE
openshot green video preview 

### ISSUE THREAD

**Issue by malikshoaibarif** [OpenShot/openshot-qt#5056]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 2.6.1
- libopenshot Version:  0.2.7
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.0.0-daily-10823-94e5f740-f55ec5d0-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/x2plp92wmpfqrzqn8qdkv4iovu7nl00x/openshot-qt.zip) (15 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/x2plp92wmpfqrzqn8qdkv4iovu7nl00x/libopenshot.zip) (35 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
1.  What operating system are you running(Win, Linux, Mac) and the version of?
2. What file type are you working with (.mp4, .mov, etc?)
3. Does this happen with other video files or just a specific one.
4. Is your display driver up-to-date?
Any additional information you can provide might be speed up the process of troubleshooting and resolving this issue.

**Comment by Colorjet3** [comment]
Hi @malikshoaibarif  I see that you also have a ticket in the support@openshot.com and working with Shawn (https://support.openshot.org/a/tickets/5069).  

Looking at your screen shot, in the this ticket, I don't see a clip being selected on the timeline.  When you select a clip, it will have a red border line around it.  

1.  What happens if you select one?
2.  What happens if you scrub (move the playhead with your mouse)?

Another thing you can try is to:
1.  Close OpenShot (assuming you are still running v3.0.0).
2.  Backup c:\users\username\.openshot_qt\openshot.settings file.
3.  Start OpenShot v3.0.0.
4.  Open your project and see if that fixed the issue.

We've seen issues in some instances when upgrading from an older version.

Let me know or just respond to Shawn.

**Comment by Colorjet3** [comment]
No Response

**Comment by Strellman** [comment]
Renamed the c:\users\username.openshot_qt\openshot.settings file so that it would create a new one and that fixed it for me.
Thanks heaps. The green preview of the video seemed to occur when dragging the layout frame. Nothing else seemed to clear it, not even deleting the video from the timeline and putting it back again.  This is on Windows 10 and openshot v3.0.0

**Comment by Colorjet3** [comment]
That is great @Strellman.  Best of luck with your projects.
