### ISSUE TITLE
Existing Project from V2.6... when loaded into 3.0 played faster 

### ISSUE THREAD

**Issue by williebme** [OpenShot/openshot-qt#5066]
When 3.0 installed without error I loaded an existing project and the speed of the playback of that project was faster than it had been in previous version.

Edition	Windows 10 Home
Version	22H2
Installed on	‎10/‎10/‎2020
OS build	19045.2364
Experience	Windows Feature Experience Pack 120.2212.4190.0

I downloaded the "daily build", installed and it installed without error but hung upon launch.

In reviewing the logs myself I noticed the error ...
WARNING preview_thread: Your sample rate (48000) does not match OpenShot (44100). Adjusting your 'Preferences->Preview->Default Sample Rate to match your system rate: 48000.

I then reviewed the openshot.settings file and noted in this file the setting was indeed 44100.  I do not know how to set the sample rate in Windows 10 or for that matter how to determine what the actual rate is in my current windows environment.

**Comment by Colorjet3** [comment]
This is a known issue.
1.  Start Openshot.
2.  Go to Edit | Preferences | Preview tab.
3.  Change the Default Audio Sample rate from 44100 to 48000.
4.  Restart OpenShot.
5.  This should take care of the issue.
Please confirm either way.

**Comment by williebme** [comment]
Hi There,

 

From one programmer to another, way to go, FAST service… Thank you very much.  I am retired, languages were VB… Sql… some c and assembly…

 

I noticed the setting was already 48000 but I think it was not set correctly in my project file.  Once I changed it in the project then the change took hold and all my other projects also load correctly now in 3.0.

 

For your amusement if you are so inclined… a “pre-release” music video of my next album… https://youtu.be/K9FuluVJfuA created with OpenShot (2.6.1).  And yes… I am a noobie…

 

Bill J Harper

Billy-Jay

**Comment by williebme** [comment]
Is it possible to overlap key frame definitions for different effects, for instance fade into a segment while also zooming in that segment beginning zoom part way through the fade in?  If so how can one identify beginning key frames from ending keyframes?

 

Bill Harper

**Comment by Colorjet3** [comment]
Yes, you can definitely overlap keyframe definitions for different effects.  To identify them is a bit more challenging.  Keyframe entries on a clip are like inserting markers on the timeline.  
1. Select a clip that has keyframes on it.  
2. Right click the clip and select Properties to display the properties window.
3. Find the Frame Number attribute and right click on None (the value) and change it to Timeline.  In the Video Preview window, in the top left corner, you will the the timeline value of where that clip.  If your playhead is positioned at the left edge and there is a keyframe marker then that is the beginning of a keyrame.
4. Next look for any attributes in the Properties window there the attribute label color is changed to Green.  This is the way OpenShot is telling you that some change was done to that attribute.   For example, I made a change to both Scale X & Y and Shear X & Y values.  So, even though I only see one circle (keyframe) I know that is the start of both Scale X & Y and Shear X & Y.
5. Now, click on the Next Key Point (the >| icon in the tool bar menu right above the timeline).  This will jump you to the next keyframe on your clip.
6. Now pay attention to the attributes in the Properties window.  You will note that the values have changed.  This is the end of the value of those attributes.  This assumes that both Scale X & Y and Shear X & Y ended exactly at the same place.  If the didn't, then if you click on Next Key Point, the playhead will jump to the next keyframe.  Note again the values in the Properties window and note the values of the attributes.  The ones that changed from the previous ones tells you that it is the end of that specific attribute.
7.  While you are doing all this, pay attention to the Frame Number in the top left corner of your clip to see where those keyframes fall on the timeline.  If you need to keep track of this location, you can insert Markers (the blue tear drop icon on the tools menu bar).  These become points on the timeline that you can jump to also with the Next or Previous key point.

I hope this helps.

**Comment by williebme** [comment]
Hi There,

 

Thanks for the incredible service!!!  

 

Unfortunately no matter what I do I cannot get the timeline frame number to show in the upper left corner of the preview window.  I have attached a screen shot showing the completed change in the properties, a clip with Key Frames, Time line marker in the clip (on a key frame) and nothing showing in the preview window.  I have tried a bunch of other stuff trying to get it to show.  I am using ver. 3.0.

 

Bill Harper

**Comment by Colorjet3** [comment]
I am unable to find the attached file.  Can you try attaching it again?  thanks!

Update:  Just to verify that it doesn't have to do anything with colors overlapping, please do this:
1.  Start OpenShot.  don't open an existing project.
2.  Click on Title | Title and select "Solid Color" template.  Don't make any changes and click Save.
3.  In your "Project File" you will see a new .svg file.
4.  Drag this onto a track.
5.  Select it and right click and select properties.
6.  Find and change the Frame Number from None to Both.
7.  Do you see both the Clip and Timeline values in the top left corner of your image in the Video Preview window?
8.  If not, we need to troubleshoot this first.
9.  If you do see this then you are running into an issue that I have reported (not fixed yet), where your image file is so bright in color that you can not see the white font that the Frame Number is in.

Update 2:  Sorry for this, just when I saved I thought of something.
1.  Open your project.
2.  Select the clip that you have the Frame Number enabled.
3.  Let's assume that Frame Number is working and the reason you can not see it is because of color conflict.
4.  Hover your mouse over Video Preview window.
5.  Hold down the CTRL key and scroll your window roller to zoom in.  As you zoom in you may need to reposition your image to keep the top left corner in focus.
6.  Keep zooming in until you make that corner large enough to possibly see the Frame Number value.
7.  Let me know if this did the trick.
8.  To quickly refocus your image click on the "Reset Zoom" in the Video Preview window.

**Comment by williebme** [comment]
Here it is… Thnks for all the help…

**Comment by Colorjet3** [comment]
Hello @williebme  This issue is now fixed in v3.1.1.

1.  go to openshot.org and from the home page click on "DOWNLOAD V3.1.1".
2.  make a backup of c:\users\username\.openshot_qt folder.
3.  delete c:\users\username\.openshot_qt folder.
4.  Install v3.1.1.
5.  Start and your audio should be resolved.

I am going to close this ticket but feel free to reopen if the issue persists.
