### ISSUE TITLE
When multiple keyframe elements are selected, remove should remove all selected

### ISSUE THREAD

**Issue by shodanx2** [OpenShot/openshot-qt#5077]
Using openshot 3.0.0

![image](https://user-images.githubusercontent.com/10621885/210317140-e5942229-0f7f-4663-b991-179ecc522f2e.png)

In the above select, you would expect all 3 selected keyframe element to be deleted

However, 
![image](https://user-images.githubusercontent.com/10621885/210317226-fe13f311-17ff-4f8f-8e31-ee656ea5ec64.png)

Only the last selected element is deleted

**Comment by Colorjet3** [comment]
This is by design and it has been like this since I started using Openshot with version 2.5.1.  Are you suggesting and enhancement to add this functionality?

Also, if you right click on the actual clip, then selection Animate | No Animation some of the attributes will be reset.  This is not fully baked and it doesn't always clear all setting.  There is an effort to fix the functionality of how the Reset All Animation works/would work.

**Comment by shodanx2** [comment]
I believe this is a bug, or rather an unfinished function.

The multi-row select works, I think any typical user would expect an action requested on multiple selection would apply to all selected items.

And this is different from a "delete all keyframe items" which also should exist.

This is really about delete "only selected element"

On top of that I would suggest as an enhancement, the ability to copy only selected elements and then be able to paste them as new keyframe elements on another selected timeline element. In my workflow this would be immediately useful when setting the "crop" for a video, since the crop usually is done on the first frame of the video but the actual values are found by going to the most "out of frame" section of the video, setting the crop by manipulating the bounding box scale/transform in the video preview, since there is not a copy/paste keyframe function, I have to then write down each value somewhere outside of openshot, move the playhead to the first frame of that clip and then type them all back in, a major inconvenience

**Comment by Colorjet3** [comment]
Thank you @shodanx2 for the feedback.  I will make the lead developer aware of this for his review.

Regarding copying of keyframe elements, right click on a clip on the timeline, and note that there are three options (Copy, Effects, and keyframes).  The Keyframes option gives a bit more granular control over what you wan to copy.  Does this help?  Play with it and see if it serves your purpose.

**Comment by shodanx2** [comment]
Thanks

I see the keyframe copy feature now

![image](https://user-images.githubusercontent.com/10621885/210458699-507fced4-0f52-470e-a985-9fba16d2c6aa.png)

I can't seem to get how pasting a keyframe works however

![image](https://user-images.githubusercontent.com/10621885/210458985-e9fda8f8-995b-4234-800e-ac13249a9b45.png)


Does the copying need to happen with the playhead directly on the keyframe being copied, or is right-clicking on the keyframe sufficient ? I tried both but in both cases pasting doesn't seem to do anything.

**Comment by Colorjet3** [comment]
I just tested this and it worked for me.  I think looking at your screens shots you didn't select the clip you wanted to paste to.  The Red border is still around the clip you copied from.  

Using your screen shot example this is how it should work:
1. Select the clip you want to copy the keyframes from.  In your example you have selected "VID_20221212_.....".
2. Set the Location X & Y as you desire.  Note:  When you are setting the location values, the location of the Playhead does matter.  If you don't have it at the left edge but somewhere in past the left edge then you will achieve animation.
3. Right click, Copy | Keyframe | Location.  For this function the Playhead position does not matter.
4. Now you must select the clip you want to apply the keyframes to.  Let's assume you want to apply it to fina-mask2-bw.png.  You need to ensure that you select it so that the Red border line focus on on the target clip.
5. Now Right click and Paste.

This should do it.
