### ISSUE TITLE
Unable to move video preview (only zoom in/out works)

### ISSUE THREAD

**Issue by shodanx2** [OpenShot/openshot-qt#5078]
Using openshot 3.0.0

I am unable to move the video preview, left/right/up/down, however zoom in/out works

Zooming is necessary to be able to reach the bounding box of various elements and move/resize them visually instead of numerically via the keyframe interface

I have a case where I have to manually move a mask picture frame by frame. 
This mask is quite small and needs to be pixel accurate.

I can reach the correct zoom level, however then I do not see the important part of the video (this is the very upper part of a vertical video)

I expected the middle move button should be able to do a translation of the view position of the video preview, however middle click has the same effect as left click and right click, which is to interact with the selected element.

**Comment by Colorjet3** [comment]
Hello @shodanx2 I am not quite understanding/picturing what you are trying to do and what the issue is.  Can you provide a screen shot and/or step-by-step of what you are doing?  Please include the file types you are using as well.

**Comment by irwandnn** [comment]
I am also looking for the solution.
How to zoom in to top-left part in preview window for example. Only scroll button works but it zooms a center of the preview and we can not see the 4 corners of the clip (not to zoom the video when it play but to zoom in editing -> not talking zoom effect)

**Comment by Colorjet3** [comment]
Let's make one thing clear.  If you use the mouse scroll wheel while hovering over the "Video Preview" window, yo will note that it will zoom in/out.  You will also note that in the top left corner of the "Video Preview" window you will have the ability to click on "Reset Zoom" to bring the view back to normal.  This is NOT a zoom in/out effect.  This is purely for you to preview the frame you are on.  So, if you Export the project there will be no zoom effect.

To achieve the actual zoom effect you need to leverage the Scale X & Y attributes.  Then, if you want to focus on a different area of the clip, you would leverage the Location X & Y attributes.

So, using the example from @irwandnn and assuming we want an animated zoom in to the top left corner you would do this:
1.  Drag your clip onto a track and align.
2.  Position the playhead (the red line) say 5 seconds into the clip.  This can be a video or an image.
3.  Right click on the clip and select Properties.
4.  From the properties window change Scale X & Y values to 2.0.  Click on the 1.0 and type 2.0 for each one.  This will achieve the zoom in.  Change your values if you need to zoom in more or less.
5.  Now change the values of Location X & Y to .5.  This will bring to-left corner to focus.  Note that you can use the mouse to grab the clip in the "Video Preview" window to move the image around.  While moving it using the mouse, you will see the Location X & Y values changing.

Hope this clarifies how to achieve the zoom in/out feature.

**Comment by irwandnn** [comment]
https://github.com/OpenShot/openshot-qt/assets/36688090/55e5328f-bb44-4ce3-8c99-9a79bdabcd6c

Hi Colorjet3,
Thank you for your quick reply.

Well to make more clear, actually I am not talking about zoom effect animation. Only zoom when we edit a clip as you said at the top of your answer.  So it can only zoom in/out using scroll button and reset, but it cannot move to the zoom area, say top-left corner to see a small object (image) on that area. 
It is more easy, I think, to edit for example transform effect of a smoll image from the "Video Preview" rather than using properties of that image.
Anyway thanks again for your answer.
Regards.

**Comment by Colorjet3** [comment]
Hello @irwandnn.  Thank you for the video and the explanation.  I now understand what you are trying to do.  What I am failing to understand is the "Why".  Why do you move the object all the way to the top right (in your video) of the "Video Preview" screen then try to zoom in on it?

If this is an enhancement request then please be specific as to what you expect to happen and how?

I am asking because if we can explain the "Why" then it give the lead developer something to review and think about.  He can then decide if this is a bug, a worthy feature to add, etc.

Please remember that you are working with a canvas that the size is determined by the "Profile" you select.  When you move an object, more specifically a smaller one, the handle bars (the blue border and handles) encompass a small area around that object.  Moving it to an extreme edge and then zooming in will cause the object to be off the "Video Preview" window.  This is common in many other applications as well.

**Comment by irwandnn** [comment]
Hi,
Thank you again for your reply.
I am happy that you understand what I and @shodanx2 are talking about.
But this is actually not  an enhancement request. I was previously thinking that I miss something there.
Kind regards.

**Comment by shodanx2** [comment]
To clarify my initial post. 
What I needed was to be able to zoom in and move around in the preview window. 
To pixel peep the video and make sure mask was aligned with the other layers.

This might have been added since, I have not been doing video editing since then.

**Comment by PreetomBoro** [comment]
I am facing a similar issue.
I want to add crop to a screen record of a small window.
Without the ability to freely zoom around to specific part of the preview window, I can't really tell if the crop is applied correctly.

**Comment by Colorjet3** [comment]
Hello everyone.  There is an enhancement request in the queue for this functionality.  The lead developer will have to review it and approve/reject.  This enhancement at this time is dependent on the user interface rewrite (in-progress).  

[Check this out.](https://trello.com/c/ZnazLQON/194-ability-to-move-around-the-video-preview-window-while-zoomed-in?search_id=48e48b4b-c17c-425b-b0b0-9d32e4f2d331).  If you are unable to get to the link directly then Filter on card #194 or "zoom" excluding the quotes and you will see it.

No ETA at this time.
