### ISSUE TITLE
OpenShot Video Editor does not display the font used in Inkscape

### ISSUE THREAD

**Issue by Pedr01308** [OpenShot/openshot-qt#5087]
After editing a Title in Inkscape, OpenShot does not display the fint selected in Inkscape and the text area dimensions set in Inkscape does not correspond in OpenShot.

**Steps to reproduce the behavior:**
1. Go to 'Open Video'
2. Click on 'Title' then Title, then Solid color template.
3. Edit template in Inkscape by clicking "Edit in advanced editor"
4. Add edited template to the OpenVideo Project

**Expected behavior:**
Fonts and title setup should be the same in Open video than Inkscape

**System Details:**
- OpenShot Version 3.0.0, Lib 0.3.0
- Inkscape 1.2.2 (732a01da63, 2022-12-09)
- OS : Windows 11 pro 22H2

Thank you for your help

**Comment by Colorjet3** [comment]
Hello @Pedr01308 .  When you select the Solid Color template, that template doesn't have any text in it and it is not designed to have text.  Are you having an issue with another template?

**Comment by Pedr01308** [comment]
Hello Colorjet3
Yes, the problem is the same with the Creative commons template. The font cannot be edited in OpenShot and modifications in Inkscape (launched through OpenShot) are not transferred to the OpenShot project.

Did I miss a warning about the unability to add text? 
Are there any editable templates?

**Comment by Colorjet3** [comment]
All these templates are editable.  I just tested v3.0.0 (the latest DEV Daily Build) and I am able to change the text and the fonts.  I was also able to test with Inkscape (Use Advance Editor) and any changes I made were saved back into OpenShot.  I am thinking there is something wrong with the installation.  Let's try this:
1. Close OpenShot.
2. Make a backup of c:\users\username\.openshot_qt folder.
3. Delete c:\users\username\.openshot_qt\openshot.settings file only.
4. Start Openshot and give it a try.
5. If problem persists, continue to step 6.
6. Close OpenShot.
7. Delete c:\users\username\.openshot_qt folder (**Warning:**  did you complete step 2 above?).
8. Start Openshot and give it a try.
9. If problem persists, continue with step 10.
10. Close OpenShot.
11. Go to openshot.org/download/#daily and get the latest DEV Daily Available and install it. (in the end, I recommend you do this any way since there have been many fixes since the release of v3.0.0-Release-Candidate).
12. Start OpenShot and try again.

Let me know what happens so we can continue troubleshooting, if needed.

**Comment by Pedr01308** [comment]
Thanks for that step by step procedure.

Unfortunately, after step 3, Open shot was unable to call Inkscape. When clicking on "Use Advance Editor", an error message appeared : "Please install Inkscape to use this function".

![image](https://user-images.githubusercontent.com/122354075/212018907-ac1c9fc3-587e-488f-815b-78015c7787fb.png)

So I went directly to step 10, reset the Inkscape launcher pathway (C:\Programs\Inkscape\bin\inkscape.exe) in the General Preferences of OpenShot.

Unfortunately, when trying to edit the title via "Use advanced editor", Inkscape opens with the good fonts, which are still not transferred to OpenShot when saving changes.

Is there a special procedure in Inkscape to transfer the modifications to Openshot ? or clicking on the "Save" button is enough?
Maybe should I try to reinstall Inkscape?

**Comment by Colorjet3** [comment]
Glad you got Inkscape working.  Now, regarding the Font issue.  Here are the steps you should be doing:
1.  After you choose your template, you click on "Use Advanced Editor".
2.  Inkscape starts and you make your Font changes in Inkscape.  In Inkscape, make sure you click the Apply button to actually change the Font.
3.  Now, just go ahead either click on the X to close Inkscape or File | Quit.
4.  You will now be prompted to "Close without saving", "Cancel", or "Save".
5.  Click on Save.
6.  When you click on Save, you will be back to OpenShot and your Font or any changes you made in Inkscape should show up in the Titles window in OpenShot.
7.  Then you click Save again in OpenShot and that should do it.

If this is not working for you, please tell me exactly which Template you are using and exactly what changes you are making in Inkscape so I can try and replicate it.  Also, which version of Inkscape have you installed?

**Comment by Pedr01308** [comment]
This is my Inkscape version : 1.2.2 (732a01da63, 2022-12-09).

The procedure you just sent is very similar to the one I used until now. And unfortunately, It still doesn't work.
The template I try to edit is : 
![image](https://user-images.githubusercontent.com/122354075/212276383-b24afdb6-dcbf-4dcf-b801-dd988040ddd0.png)

Final version of the Title in Inkscape
![image](https://user-images.githubusercontent.com/122354075/212282026-af857315-21ed-4120-a648-ff6d00d836d9.png)

Result in Openshot :
![image](https://user-images.githubusercontent.com/122354075/212281915-36d44a9e-5782-435d-9565-7e3a4972e3d4.png)


I even tried to create a new .svg file in Inkscape and added it in my Openshot project as an image. The font is not correctly displayed either.

Here are the screenshots of the procedure :
1. Creation of the.svg image in Inkscape with Avenir Next LT Pro font :
![image](https://user-images.githubusercontent.com/122354075/212277059-ed10257c-9d93-4b1b-bdbf-e37d3eb8b39a.png)


2. Insertion of .svg image in the Openshot project :
![image](https://user-images.githubusercontent.com/122354075/212281029-114f9c0b-0a3a-461b-9e00-9b982d1754b6.png)
(just add the image in the project files panel with "+" button. Then I click-&-dragged the image in the project. The result can be seen in the screenshot.

Then, the result in Openshot is the same either I try to edit a title after launching Inkscape from Openshot, or I separately create a .svg image in Inkscape and insert it in my project.

I have to finish my project soon so I think I will export the title in matrix image format and add an this image in Openshot. But I would be glad to understand the problem and be able to use vector graphics in my future projects.

**Comment by Colorjet3** [comment]
I think I may know what is going on but need to confirm.  Is Avenir Next LT Pro and add on Font you added to Windows?  I ask, because I don't have it in my Windows 10 or Windows 11.

If this is the case, let me know where you downloaded this font from.  I'll go ahead and then download it and test it.

Meanwhile, and just for testing, select and existing font that comes with the base Windows, something like Comic San MS and Segoe Script.  Apply them to two different sets of text lines and see if they work.  If this does, then this means that when you added the Avenir Next LT Pro, for some reason, Windows and other apps (Inkscape) sees it, but OpenShot is not.

**Comment by Pedr01308** [comment]
You are right, Avenir Next LT Pro was not embedded in my version of Windows. I remember I have downloaded it but I don't remember where. Maybe here : https://fontsgeek.com/fonts/avenir-next-lt-pro-regular

I then tested Comic sans MS and Segoe Sript, and again you were right. OpenShot was able to display them.

Thank you for all your answers and your help with troubleshooting.

**Comment by Colorjet3** [comment]
You are welcome @Pedr01308 and good luck with your project(s).
