### ISSUE TITLE
Selected keyframe element not distinc enough from "non-default" element

### ISSUE THREAD

**Issue by shodanx2** [OpenShot/openshot-qt#5111]
Running openshot 3.0.0 daily 2023-01-18

Here is what I mean

![image](https://user-images.githubusercontent.com/10621885/214400846-d9bd8df3-09fd-46ee-9aeb-352532de4a04.png)

White text on blue means non-default

Black text on blue means selected

I suggest changing the keyframe select select color to orange  ?

**Comment by Colorjet3** [comment]
Hello @shodanx2 Thank your for this feedback.  I agree with your assessment.  I am going to add this as an enhancement request.  It will most likely not make it in any of the immediate minor releases due to other priority bug fixes.  However, the lead developer is also working on a new UI interface (no ETA), and this should be part of the consideration of an enhanced UI.

Here is the link to the entry:  https://trello.com/c/dg5TwiYI/37-selected-keyframe-element-not-distinct-enough-from-non-default-element

I am going to close this ticket.
