### ISSUE TITLE
Unable to delete multiple selected keyframe elements 

### ISSUE THREAD

**Issue by shodanx2** [OpenShot/openshot-qt#5113]
Using openshot 3.0.0 daily 2023-01-18

Selecting multiple keyframe elements

![image](https://user-images.githubusercontent.com/10621885/214457276-3f56bbd6-8773-4694-8d5d-c81471cb0ab1.png)

And then click remove keyframe

![image](https://user-images.githubusercontent.com/10621885/214456995-9ae69afa-bc75-4a67-a3ff-dbf28dfc0b20.png)

This only removes the keyframe element that has been right clicked on and not the rest of the selection

![image](https://user-images.githubusercontent.com/10621885/214457408-4033230e-8685-455a-b938-9347f45430dc.png)

**Comment by Colorjet3** [comment]
Very interesting that you are able to select multiple attributes but the change only applies to the attribute that you right clicked on.  I am going to submit this ticket to be reviewed by the lead developer.  I don't know what the original design for allowing multiple attributes is and it could be a bug in itself.   I can think of a few other options:

Option1.  Right click on the clip itself and have the option of "Remove All Keyframes".
Option2.  Leverage the current available option (Right click on the clip, Animation | No Animation).

As I was playing with the multiple selection of attributes I thought of having the ability to adjust two values at once.  For example; I would select Location X & Y and when I change the value using the mouse or I manually type a value in one it would adjust both because they are selected.  But this can introduce other complexities where you might think I should be able to select more than two attributes and change all their values.

Any way, I would like to hear from you about your thoughts and possible ideas and the options I proposed above. The more ideas/options we provide, it makes it easier for the lead developer to review and think about.  He will ultimately review and approve the enhancement request.

Meanwhile, the quickest way to get rid of these effects is to delete the clip from the track and redrag it.  However, this could get rid of other effects that you may have applied and want to keep.

Looking forward to hearing from you.

**Comment by shodanx2** [comment]
For now I click each element one by one and delete them

I would be squeamish to use "delete all keyframe", it might delete something I don't want or expect and then risk having to start my work over from scratch !

I would really like remove keyframe to only remove the selected elements

As for mouse adjuting, that would be great, there could be a symbol you click on the element, when you click it , it toggles colour showing it's active. Now you vertical scroll wheel can adjust this setting. Would be fantastic with my logitech mx 3s.

Here is what that might look like

![image](https://user-images.githubusercontent.com/10621885/214464724-d7273863-9bc2-461c-a385-eb3a1e20a619.png)


You could also click this symbol and hold down the button, then circle the cursor around the symbol to increment/decrement the value. The wider the circles, the larger the value increment.

**Comment by Colorjet3** [comment]
Understood regarding an "all delete".  I also like your suggestion.  Like I mentioned many of these types of features are going to end up as par of the UI experience.

I will add this as an enhancement request as well.  In the end, the lead developer/production owner will decide as he may have other ideas as well and how and when to implement.
