### ISSUE TITLE
Openshot 3.0, Fedora 37

### ISSUE THREAD

**Issue by huubvanniekerk** [OpenShot/openshot-qt#5114]
**Describe the bug:**
Various problems with the second .mov video after placing it on the timeline:
- video does not have it full length
- the audio separation is taking forever
- cutting the video takes multiple seconds longer than in v. 2.6.1
  
**Steps to reproduce the behavior:**
- After putting a .mov file on the timeline it is much shorter than it should be. Not faster, just cut off.
- After selecting the top-choice of audio separation, it keep busy. I had to end the program 3 times before I decided to get back to v. 2.6.1
- - After right-click on the progress-needle, selecting 'keep both sides', it tales up to 5 seconds before the cut takes place. In v. 2.6.1 it takes just a second or 2.

**Expected behavior:**
- Full length video shown on the timeline
- Audio separation of a 2 minutes .mov video in max 10 seconds.
- Cutting the video in just 2 seconds.

**System Details:**
- OpenShot Version 3.0 all versions, including daily build 10947.
- Operating System / Distro: Fedora Linux 37

**Log Files:**

Sorry, have none

**Exception / Stacktrace:**
Sorry, have none

**Screenshots:** (Optional)
Sorry, have none

**Comment by Colorjet3** [comment]
Please download the latest DEV Daily Build v3.0.0 AppImage from openshot.org/download/#daily and give it a try.

**Comment by huubvanniekerk** [comment]
@Colorjet3 I used OpenShot-v3.0.0-daily-10947-510a7690-b5bbab66-x86_64.AppImage and it gave me the experiences I described in my report.

**Comment by Colorjet3** [comment]
Hello @huubvanniekerk I am sorry that I didn't notice you already had tried the latest DEV Daily build #10947.  I just tested with a few .mov files in both Windows 10 and Fedora 37 and I have no issues with importing, dragging onto a track (the same one multiple times and a few other .mov files).  Didn't have any issues in either platform with editing, animating, etc, either.

However, I do want to confirm that there is definitely performance degradation while editing/previewing.  This is something the lead developer is well aware of and there is an internal ticket to work on this issue. 

You may want to run your .mov file through a converter like VLC or Handbrake and convert it to .mp4.  Then import the .mp4 and see if that plays any better.

Here are some tips to fine tune v3.0.0 (stick with the latest DEV Daily build):

	○ Go to https://www.openshot.org/user-guide/. Search for Cache and click on Preferences > Cache. There are 4 new cache settings to play with to get acquainted with.
	○ In Openshot, Go to Edit | Preferences | Cache tab
	○ The Cache Limit(MB): This is not new, but be careful making this too large. I have a 32GB RAM but I rarely go over 4096. What happens with v3.0.0 is the the constant rebuilding of the Cache causes slow down during the editing/previewing process.
	○ Cache Max Frames: by default it is set to 600. I bump this up to the max of 1024.
	○ Cache Pre-roll: Min Frames: Change to 48
	○ Cache Pre-roll: Max Frames: Change to 96
These Cache settings seem to only help with performance while editing/previewing. I have not noticed any improvements in Exporting or Animated titles creation.
The nice part about the Cache Limit (MB) is that you can change it on the fly without having to restart OpenShot or reopen a project. I have found that when I am doing lots of edits, I change the this setting to 2048 so that during the editing part OpenShot is more responsive. When I get into previewing my changes, and especially with both large and/or complex projects, I change my Cache Limit (MB) to 8192. This assumes you are clicking on Play and watching your entire work. You will note that when you stop or make some changes, it takes longer for the Cache to get rebuilt (you will note a solid blue line building up right above the top most track). When you want to go back to editing (may be not just for one or two), I would change the Cache Limit back to 2048.
The lead developer is well aware of this and there are many more changes planned to improve the overall performance of OpenShot (previewing, editing, animation, and exporting).

I hope this helps.
