### ISSUE TITLE
Suddenly, a project won't render or export

### ISSUE THREAD

**Issue by davidsteele1975** [OpenShot/openshot-qt#5126]
**Describe the bug**
Whilst working on a project, right towards the end, it stopped rendering and will not render.

**Steps to reproduce the behavior:**
1. Load project - no errors in importing media.
2. Click on preview or export. Wait a second or two. Video doesn't preview or export dialogue doesn't appear.
3. Skip forward to later in the video and it still doesn't render.
4. Other projects work as planned.

**Expected behavior**
Video renders or exports

**System Details**
- OpenShot Version: 3.0.0 daily build
- libopenshot Version:  0.3.0
- Platform: Windows 10 64-bit
- Processor: Intel i7-10700K
- Machine: 
- Python version: 
- Qt5 version: 
- PyQt5 version: 
- Qt Detected Languages: 
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: yes, issue reoccurs

**Log Files**
*attached*

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain y
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/10574683/libopenshot.log)
our problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screensho
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/10574684/openshot-qt.log)
ts containing personal information.

**Comment by davidsteele1975** [comment]
Sorry for the omitted data or an incorrectly completed form. :/

**Comment by Colorjet3** [comment]
Hello @davidsteele1975 Since other projects work, please provide a bit more detail about this specific project that you are having issues with:
1.  What type of files are you importing into it (.mp4, .mov, .jpg, etc?).
2.  How big is your project?
3.  Are you using any Effects or Transitions?
4.  Are you using animation?
5.  Any other detail that will help us troubleshoot?

**Comment by davidsteele1975** [comment]
Hello there @Colorjet3 

I see where you may be going... :)

I'm importing .mp4 files, they're 4K, in total around 6.2GB but these are trimmed in the video.

I narrate the project using seventeen (17) .m4a files and there are four (4) .mp3 files, the largest is around 7MB.

In total, the project is under 15m length. As for effects... yes. This video I'm using a number of color saturation effects and I've split the .mp4 files into smaller clips. There are no transitions used but I'll fade one clip out and simultaneously fade another in. For animation, I've some emojis that grow or shrink, and move about the screen, if this counts?

For other details - the machine has 64GB of RAM and plenty of storage. It felt like a drive or folder access issue but I've checked and double checked all files and they're present and correct. I've tried removing an effect from a clip but OpenShot hangs when I right mouse over the button. That may be a clue, but I'm not able to remove an effect added to a clip.

**Comment by Colorjet3** [comment]
Thank you @davidsteele1975 for all that information.  Let's try a couple of things:

1.  Close Openshot.
2.  Make a backup of c:\users\username\.openshot_qt folder.
3.  Delete c:\users\username\.openshot_qt\openshot.settings file.
4.  Start Openshot.
5.  Open your project and give it a try.
6.  If it still behaves the same then continue....
7.  Close Openshot.
8.  Make sure that you have your backup from step 2 above.
9.  Delete c:\users\username\.openshot_qt folder.
10. Start Openshot.
11. Ensure that the Default Audio Sample Rate in Edit | Preference | Preview tab is set to 48000.
12. Restart Openshot.
13. Open your project and give it a try.
14. Let me know the result either way.

Please also provide me with a screen shot of Edit | Preferences | Cache tab.  Since you are running somewhat a bit larger project I can give you some hints on adjusting the Cache settings to improve your experience while editing.

First, let's focus on fixing your issue.

**Comment by davidsteele1975** [comment]
Unfortunately, I'd tried clearing the preferences before posting earlier (and should have said so), but I didn't check my Default Audio Sample Rate is 48000. It is still 48000, and unfortunately the changes have no effect.

I've noticed some weirdness as the application renders the preview. If I open another project to check that it still previews, and then load the project that isn't working, OpenShot shows it's rendering the preview in the cache but doesn't display video or play sound if you hit play. It keeps on processing the preview if you let it play.

If I close and re-open OpenShot with the project that isn't working, it doesn't appear to try to build the preview and doesn't respond to pushing play.

On a hunch, I tried clearing saved waveforms just in case this would release enough resources to let me remove something else... and this would successfully preview! But only if I loaded another working project first. If I opened the swollen too-large project and tried to clear waveforms, OpenShot became unresponsive.

So.... I opened another project, opened the swollen project, cleared waveforms, saved as another file name, then removed the second half, and it seems to be working. I haven't tried to render it yet but it looks like I was too greedy with the project files - and for that, I'm sorry. I should have probably known better!

Here's my Cache section, I increased this quite a bit during testing as I have lots of free RAM and this speeds it up from the default 512MB.

Thank you for your help! I appreciate it.

**Comment by Colorjet3** [comment]
Hello @davidsteele1975.  My apologies in advance but I am not quite clear if you think your issue has been resolved or you still need assistance.

Please let me know so that we can continue troubleshooting or I can go ahead and close this ticket.

**Comment by davidsteele1975** [comment]
Say @Colorjet3 - it's resolved. I was able to free up enough resources to split the project into two, render each one, and join them later. Thanks for your help! :)
