### ISSUE TITLE
SVG file shows all black

### ISSUE THREAD

**Issue by huubvanniekerk** [OpenShot/openshot-qt#5128]
**Describe the bug:**
In Openshot v. 3 (daily build), an SVG file created with Inkscape, shows all black after importing it. The same SVG file shows correct in v 2.6.1.

**Steps to reproduce the behavior:**
- Import SVG file
- File correctly shows all black in v. 3, shows white text on black  in v.2.6.1
- 
**Expected behavior:**
SVG file with white text showing text after importing

**System Details:**
- OpenShot Version [OpenShot-v3.0.0-daily-10947-510a7690-b5bbab66-x86_64.AppImage]
- Operating System / Distro: [Fedora Linux Mint 37]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
Hello @huubvanniekerk I am able to replicate this issue you reported in Daily Build 10947 also.  I know why it is happening but I don't know why it is working in v2.6.1 but not in v3.0.0.  

I am testing using Windows 10 so it seems that the behavior is the same in these platforms.

Here are a few options for a temporary work around:

Option1
1.  Start Inkscape and open your .svg file.
2.  Change the Font color to White (something other than black).
3.  Now import your .svg file into Openshot and you should see the letters.

I think what you might need to do to make your letters black is to make the background in Inkscape transparent.

Option 2 - This was not very reliable.  I think something is wrong with v3.0.0 and Inkscape integration.

1.  In the "Project Files" window, right click on your imported .svg file.
2.  Select "Edit Title".
3.  Double click on "Text Color" and change it to White even though it might look like it is set to white already (this could be the issue).

Option 3
1.  Start Openshot.
2.  Click Title | Title.
3.  Select a Template.
4.  Note that the font color is automatically set to White to be on contrast of the background of black (even though it is transparent).
5.  You still have the options to select "Use Advanced Editor" to start Inkscape from within Openshot to further manipulate the text file.  However, note that since the Font color is white your text will not be displayed in Inkscape.  You have to change the font color to something other than white.  Complete your edits, change the Font color back to White then Close Inkscape and save as you close.
6. You will now be back in Openshot to continue working with your Text title template.

**Comment by Colorjet3** [comment]
Hello @huubvanniekerk I am submitting a bug report so that the lead developer can take a look at this issue and a few others I discovered while testing.

**Comment by huubvanniekerk** [comment]
Hi @Colorjet3 Thank you for your action. Today I downloaded daily build #10996 and found that this reported SVG issue has not been fixed yet. 
However, what I did not do prior to reporting this bug, is try if other SVG files (6 in total) that I frequently use are being dealt with. These files do not just contain a bit of text but also a small image. So I just tried 1 of them in #10966, and it gives no problem whatsoever. Text and image are shown fine.

**Comment by Colorjet3** [comment]
Thank you for the updated information @huubvanniekerk.  Yes, the issue has not yet been fixed.  It is in the queue but hasn't made it passed the review stage.

I am curios to know which version of Inkscape you are running.

Thank you!

**Comment by huubvanniekerk** [comment]
@Colorjet3 I'm now using Inkscape 1.2.2 and created the pure white text on black backgrond with it. The other SVG files were created with a (slightly) earlier version.

**Comment by Colorjet3** [comment]
Thank you @huubvanniekerk for that.  Just remember that when creating these SVG files with Netscape, that the background is really transparent.  Meaning, when you import it into Openshot and then overlay this .svg file over another clip (video or image), you only see the image and/or text overlaying the clip below it (.svg on Track 5 right above an image or video clip on track 4).

Please feel free to close this ticket if you feel like you have a working solution.

Have a great day!

**Comment by huubvanniekerk** [comment]
@Colorjet3 I'm aware that the background of an SVG file created with Inkscape is actually transparent.

I always put The SVG files containing both an image and a text on Track 5, the rest of the files are spread over Tracks 1 - 4: .mov file on track 4, separated audio wave track on 3, .ogg file on track 2 and separated audio wave track on 1.
The SVG file containing only text is also put on Track 5. But in Openshot 3 this file is not showing the text, just the (black showing) transparent. As said before, in Openshot 2.6.1 it gives no problem: the text is shown as intended.

So as far as Openshot 3 goes, there is no working solution for me yet. I will test it with the Title option and report back in this issue.

**Comment by Colorjet3** [comment]
Hello @huubvanniekerk The Options I provided 4 days ago above should give you the workaround.  Did you try those?

**Comment by huubvanniekerk** [comment]
@Colorjet3 I did not have time yet to try those out. But I will in the coming days and report back if (one of) those work out.

**Comment by Colorjet3** [comment]
Hell @huubvanniekerk.  I am closing this ticket.  Please report back when you have time to try the options I provided in an earlier thread.
