### ISSUE TITLE
OpenShot 2.2.0 playback suddenly stops 

### ISSUE THREAD

**Issue by HanBaichuan** [OpenShot/openshot-qt#514]
I'm using Ubuntu 16.04. Openshot 2.2.0. I installed using add-apt-repository ppa:openshot.developers/ppa
Prossesor: Intel® Core™ i5-5200U CPU @ 2.20GHz × 4  
Graphics: ® HD Graphics 5500 (Broadwell GT2) 

What happened on GUI is when I trying to play a video (drag the video file to the timeline and click play button) On the playback screen it plays like 2 seconds and suddenly stops. No matter what I do the video doesn't play again.

Now when I trying to close the Openshot. A "This window is not responding" window pup up and I can only force quit.

I run the openshot-qt in terminal. When the error occur, nothing returns in the log.

Sorry for my English, and I think Openshot is a amazing software!

**Comment by jonoomph** [comment]
Please see https://github.com/OpenShot/openshot-qt/blob/master/.github/CONTRIBUTING.md for instructions on how to enable debug mode and generate log files. Also, please try with a few different video files / image files, and try to determine if the problem might be caused by a specific video file. Thx.

**Comment by jonoomph** [comment]
Oh, also, please try our latest AppImage daily build: Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot.

**Comment by HanBaichuan** [comment]
Thank you sir. The AppImage from March 4, 2017, 4:19 a.m. also have the problem. Also the video and audio play is choppy.

[openshot-qt.txt](https://github.com/OpenShot/openshot-qt/files/819198/openshot-qt.txt)

I got the log file now. Is it probably because the video is too long?(over an hour) shorter video also happened but less likely. I'll let you know if I figured something out.

**Comment by rogerfranz** [comment]
So far, the freezing issue happens with every file I load.

Windows 7 SP1, updated.
FX-8350, 16 GB RAM, 400 GB free hard drive space.

Openshot 2.2, from daily build download as indicated.

The video I'm working with at the moment is a non-standard size. It was a screen recording of MMO gameplay, scaled down 50% both directions from a 1680x1050 screen. The software added a few more pixels (that piece of software is gone, now, because I didn't care for other things it did), so 840x569.

Shouldn't even stress the software, right?

I cut it using AVIdemux to a 4-minute clip I was interested in. Many applications froze when I tried to load the 3.5 hr video (5 GB). VLC played it fine, as did Quicktime.

So, the 4-minute clip.

At first, I thought Openshot was freezing at 35 seconds into it. But, after reviewing this thread, I tried again. It's not a freeze -- it's a pause. And it happens when the playback pointer reaches the end of a little blue line just above the timeline. Like it's run out of cache -- just like what happens when I play a video on the Internet using a slower connection.

I remembered a few things from the 1990's, when I was running a RAM cache for my hard drive, so I tried different cache sizes. And, yes, different cache sizes definitely affect this issue.

I tried 1, 3, 10, 32, 100, 320, 1000, 3200, 10000 MB cache sizes, with debug set to verbose. I cut the clip to a minute, and played through it for each cache size, waiting through those pauses, and loaded a zipped set of log files (in labeled folders) to dropbox. I can't upload them here without compression; they are too large (10 MB limit; libopenshot for the 4 minute clip was 300 MB). 

[Dropbox link](https://www.dropbox.com/s/bwqmxadoknczk1i/OpenShot_Logs.zip?dl=0).

I noticed a few things during this test. Once the cache was at 100 or higher, the "freezes" were 15-20 seconds long, and often coincided with writing a log file to disk (I was watching the log directory). Also, during a freeze, CPU usage dropped on several processors but increased on others (I was watching the resource monitor while Openshot did its thing). I don't have a good CPU usage logging program, but Openshot's logs don't seem to be timestamped anyway.

Also, for 1 MB and 3 MB cache sizes, the cache seemed to be hopping forward in concert with the stuttering of the playback (with both of those, the un-paused play lengths were perhaps a second; the pauses were perhaps 1/10 to 1/4 seconds long).

After perusing the libopenshot logs, I noticed a rather large number of sequences that look a little like the sample below. These seem to occur at approximately the point in the file where the pauses are happening. This one is from a preliminary 3 MB cache test, as I recall.

Avidemux, VLC and Quicktime play these files just fine. No stuttering or anything like it. Otoh, Openshot doesn't have rendered output for preview playback.

All that to say, freezing, pausing, and stuttering during preview playback seem to all be the same issue, and it's related to cache. It gets worse for disk cache (I did not run these tests for disk caching).


```
Timeline::GetFrame (Add frame to cache) (frame_number=9.0000, info.width=1280.0000, info.height=720.0000)
Timeline::GetFrame (end parallel region) (requested_frame=9.0000, omp_get_thread_num()=0.0000)
VideoCacheThread::run (cache frame) (position=10.0000, current_display_frame=9.0000, max_frames=16.0000, needed_frames=1.0000)
Timeline::GetFrame (Cached frame found) (requested_frame=10.0000)
VideoCacheThread::run (cache frame) (position=11.0000, current_display_frame=9.0000, max_frames=16.0000, needed_frames=2.0000)
Timeline::GetFrame (Cached frame found) (requested_frame=11.0000)
VideoCacheThread::run (cache frame) (position=12.0000, current_display_frame=9.0000, max_frames=16.0000, needed_frames=3.0000)
Timeline::GetFrame (Cached frame found) (requested_frame=12.0000)
VideoCacheThread::run (cache frame) (position=13.0000, current_display_frame=9.0000, max_frames=16.0000, needed_frames=4.0000)
Timeline::GetFrame (Cached frame found) (requested_frame=13.0000)
VideoCacheThread::run (cache frame) (position=14.0000, current_display_frame=9.0000, max_frames=16.0000, needed_frames=5.0000)
Timeline::GetFrame (Cached frame found) (requested_frame=14.0000)
VideoCacheThread::run (cache frame) (position=15.0000, current_display_frame=9.0000, max_frames=16.0000, needed_frames=6.0000)
Timeline::GetFrame (Cached frame found) (requested_frame=15.0000)
VideoCacheThread::run (cache frame) (position=16.0000, current_display_frame=9.0000, max_frames=16.0000, needed_frames=7.0000)
Timeline::GetFrame (Cached frame found) (requested_frame=16.0000)
VideoCacheThread::run (cache frame) (position=17.0000, current_display_frame=9.0000, max_frames=16.0000, needed_frames=8.0000)
Timeline::GetFrame (Cached frame found on 2nd look) (requested_frame=9.0000)
Timeline::GetFrame (Cached frame found on 2nd look) (requested_frame=9.0000)
Timeline::GetFrame (Cached frame found) (requested_frame=10.0000)
PlayerPrivate::run (determine sleep) (video_frame_diff=1.0000, video_position=9.0000, audio_position=8.0000, speed=1.0000, render_time=6.0000, sleep_time=35.0000)
Timeline::SortClips (clips.size()=4.0000)
Timeline::find_intersecting_clips (Is clip near or intersecting) (requested_frame=17.0000, min_requested_time=0.6667, max_requested_time=0.9583, clip->Position()=0.2000, clip_duration=203.5417, does_clip_intersect=1.0000)
Timeline::update_open_clips (before) (does_clip_intersect=1.0000, closing_clips.size()=0.0000, open_clips.size()=2.0000)
```

I'm not sure if this helps, but it's information.

**Comment by DylanC** [comment]
@HanBaichuan - Does this issue exist in OpenShot v2.3.4? Please confirm.

**Comment by DylanC** [comment]
Try OpenShot v2.4. The preview is much better and no lag detected in my testing. If you need to get back to me I can reopen if the issue still exists.
