### ISSUE TITLE
Export crashes with no apparent reason.

### ISSUE THREAD

**Issue by Rotorial71** [OpenShot/openshot-qt#5153]
**Describe the bug**
I've tried to export a video for multiple days now, trying different Openshot versions & daily builds and setting combinations, but it always crashes at around 30%.

**Steps to reproduce the behavior:**
1. Click on export
2. Adjust settings
3. Click start and wait until about 30% completion.

**Expected behavior**

**System Details**
- OpenShot Version: 3.0.0
- libopenshot Version:  0.3.0
- Platform: Windows-10-10.0.19041
- Processor: AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.0.0-daily-11058-8f92bac0-b5bbab66-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/bnwh588ugiqd6eml0j1jbit6b5q63zgz/openshot-qt.zip) (9 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/bnwh588ugiqd6eml0j1jbit6b5q63zgz/libopenshot.zip) (5 KB)

**Exception / Stacktrace**
```_C_specific_handler            7ffb55a37f60
_chkstk                        7ffb55e12300
RtlRaiseException              7ffb55dc1070
KiUserExceptionDispatcher      7ffb55e10f20
avcodec_is_open                7ffafc7fac30
ZNopenshot::FFmpegReader::Close 7ffaffb5b400
ZNopenshot::FFmpegReader::Seek 7ffaffb53e40
ZNopenshot::FFmpegReader::Open 7ffaffb546d0
ZNopenshot::Clip::Open        7ffaffb295e0
ZNopenshot::Timeline::update_open_clips::Clip 7ffaffb9ded0
ZNopenshot::Timeline::find_intersecting_clips 7ffaffb9fd50
ZNopenshot::Timeline::GetFrame 7ffaffba0650
PyInit__openshot               7ffafe991c20
PyLong_FromUnsignedLong        7ffafebef890
PyEval_EvalFrameDefault        7ffafebd0a00
PyEval_EvalCodeWithName        7ffafebccbd0
PyFunction_Vectorcall          7ffafebe0770
PyEval_EvalFrameDefault        7ffafebd0a00
PyEval_EvalCodeWithName        7ffafebccbd0
PyFunction_Vectorcall          7ffafebe0770
PyMethod_New                   7ffafebec0c0
PyVectorcall_Call              7ffafebec590
PyInit_QtCore                  7ffac98da730
PyInit_QtCore                  7ffac98da730
PyInit_QtCore                  7ffac98da730
PyInit_QtCore                  7ffac98da730
PyInit_QtCore                  7ffac98da730
ZNQMimeType::qt_static_metacall::QObject::QMetaObject::Call 7ffaf9b06800
ZNQDialogButtonBox::standardButton::QAbstractButton 7ffaf2970ae0
ZNQMimeType::qt_static_metacall::QObject::QMetaObject::Call 7ffaf9b06800
ZNQAbstractButton::toggled  7ffaf28d3660
ZNQAbstractButton::qt_static_metacall::QObject::QMetaObject::Call 7ffaf28d5340
ZNQAbstractButton::mouseReleaseEvent::QMouseEvent 7ffaf28d5b30
PyInit_QtWidgets               7ffac92beca0
ZNQWidget::event::QEvent      7ffaf2827200
PyInit_QtWidgets               7ffac92beca0
ZNQApplicationPrivate::noti...```

![d17e270043a644648e2f2830c3157b56](https://user-images.githubusercontent.com/125723293/219845721-def91c45-26c6-47d5-bb31-61be9ccb8114.png)
![676a318ed13b83a844acc55291111d88](https://user-images.githubusercontent.com/125723293/219845727-cf4d6060-d3bc-4002-88ab-0903e1118f7c.png)

**Comment by Rotorial71** [comment]
It is important to note that Openshot does work on other exports, just one in particular doesn't work. I'm not sure if there's a specific reason but here's some images of my timeline and files added if that helps. I'm leaning towards the fact that it may be one of the files I uploaded or there's too many edits.

![d17e270043a644648e2f2830c3157b56](https://user-images.githubusercontent.com/125723293/219904656-c5d7ef41-1264-4220-8b6a-dfa3c9079dfd.png)
![676a318ed13b83a844acc55291111d88](https://user-images.githubusercontent.com/125723293/219904660-0fa4688d-6b0d-43e7-8ee2-cc32bf6309f3.png)

**Comment by Colorjet3** [comment]
Hello @Rotorial71 Sorry that you are having issues with one of your project exports.  I am suspecting that it is one of the video files (.mp4?) or possibly another type of video file.  I do not suspect the .mp3 or your image files.  I think the best way to isolate the issue would be to:

1.  Open your project.
2.  Perform File | Save Project As and save it as Test01.osp.
3.  It looks like Track 5 contains most of your video clips.
4.  Find the half way point and delete all the clips in the 2nd half of Track 5.
5.  Now Export.
6.  If it succeeds then one of the clips in the 2nd half of the clips is where the issue lies.  go to step 9
7.  If it fails, one of the clips in this first half is the issue.
8.  Do the same thing...halving this 1st half of the clips until you figure out the problem video.  When you find the problem video go to step 15.
9.  This means the 1st half clips are good.
10. Reopen Test01 project and do not save.
11. Now delete the 1st half of the clips from Track 5.
12. Select the rest of the remaining clips and drag them to the left so they all start from 0.01 position.
13. Now Export.
14. Do the same thing...halving this 2nd half of the clips until you figure out the problem video.  When you find the problem video go to step 15.
15. You are here because you have narrowed down the issue to a specific clip or clips.  Most likely a .mp4 or some other type of a video file.
16. Double check that you can play this video outside of openshot successfully.
17. Now run this video through a converter like VLC or Handbrake converting it to .mp4 (even if it is a .mp4).
18. Now start a new Openshot project.
19. Import this converted video (or more...) and Export it by itself.  If it succeeds then you have fixed the issue.
20. Go back to your original project.
21. Remove the original video from your project.
22. Import this newly converted/working video.
23. Now try Exporting the whole project again.

I hope all this makes sense.

**Comment by Rotorial71** [comment]
Hello [Colorjet3](https://github.com/Colorjet3), thank you for the response. I was able to narrow it down to one section but unfortunately it autosaved and I have to re-edit the first half (the problem area). I'll use this to my advantage to find out what caused the crash. Again, thank you for the help and have a great day.

**Comment by Colorjet3** [comment]
That is great @Rotorial71 .  In the future you can change your Autosave duration to a longer duration as you are troubleshooting and then change it back.

**Comment by Colorjet3** [comment]
I am going to close this ticket for now.  If you still need assistance please either reopen this or start a new thread.
