### ISSUE TITLE
Openshot has recently starting declaring that most of my media files are not valid media files. I ha...

### ISSUE THREAD

**Issue by JMcPeak3373** [OpenShot/openshot-qt#5166]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 3.0.0
- libopenshot Version:  0.3.0
- Platform: Linux-5.15.0-67-generic-x86_64-with-glibc2.4
- Processor: x86_64
- Machine: x86_64
- Python version: 3.8.10
- Qt5 version: 5.12.8
- PyQt5 version: 5.14.1
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: en_US.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.0.0-daily-11058-8f92bac0-b5bbab66-x86_64.AppImage

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/gba8m3yobd74srteer8p69a2lax2dgy6/openshot-qt.zip) (32 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/gba8m3yobd74srteer8p69a2lax2dgy6/libopenshot.zip) (3 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by JMcPeak3373** [comment]
open OPENSHOT, add clip, select media (.mkv, .mp4, .m4v). Openshot then says it's not a valid media type. No issues playing these files in; MPlayer, VLC, Kaffeine. I also have no issues adding these clips in KDENLIVE and exporting them.

**Comment by Colorjet3** [comment]
Hello @JMcPeak3373.  Since you say "...recently started...", I am going to assume you just upgraded to v3.0.0.  If this is the case there are some known issues with the v3.0.0-Releaes-Candidate.

Please do this:
1.  Go to Openshot.org/download/#daily and download the latest DEV Daily AppImage available.
2.  Run this and see if you are now able to import your files without Openshot generating error messages.

Please confirm either way.

**Comment by JMcPeak3373** [comment]
I already downloaded the latest daily build app image, and it is still happening. 

- System:
  Kernel: 5.15.0-67-generic x86_64 bits: 64 compiler: gcc v: 11.3.0 Desktop: Xfce 4.16.0
    tk: Gtk 3.24.23 wm: xfwm dm: LightDM Distro: Linux Mint 21.1 Vera base: Ubuntu 22.04 jammy
Info: quad core model: Intel Core i7-4810MQ bits: 64 type: MT MCP arch: Haswell rev: 3 cache:
    L1: 256 KiB L2: 1024 KiB L3: 6 MiB
Device-1: Intel 4th Gen Core Processor Integrated Graphics vendor: Dell driver: i915 v: kernel
    ports: active: eDP-1 empty: DP-1,HDMI-A-1,VGA-1 bus-ID: 00:02.0 chip-ID: 8086:0416
  Device-2: NVIDIA GK104GLM [Quadro K4100M] vendor: Dell driver: nvidia v: 470.161.03 pcie:
    speed: 2.5 GT/s lanes: 16 ports: active: none off: DP-4 empty: DP-2,DP-3 bus-ID: 01:00.0
    chip-ID: 10de:11b7

**Comment by Colorjet3** [comment]
Hello @JMcPeak3373.  Than you for the information.  Let's try one more thing:

1.  Close Openshot if open.
2.  Make a backup /home/username/.openshot_qt folder.
3.  Delete /home/username/.openshot_qt folder.
4.  Run the latest DEV Daily AppImage and try again.

If this fails, then we need to have one of the DEV team members to take a look at your issue.

**Comment by JMcPeak3373** [comment]
Ok, tried that, and no difference. I did discover something though, in Preferences/ performance/acceleration videos load as clips without issue when set to "NO ACCELERATION", I was able to originally use LINUX VA-PI to load and preview clips successfully. When I tried to use the accelerators; NVDEC, or VDPAU it would distort the clips and the exports would be corrupted, so I just used VA-PI and everything worked. Now I cannot use acceleration without the whole clip loading failing claiming it is an invalid file.

**Comment by Colorjet3** [comment]
Hello @JMcPeak3373.  Hardware acceleration does not work with the AppImage or the Linux package manager installation.  Here is a response from the Openshot DEV team regarding HW acceleration:

Hardware acceleration is still experimental in OpenShot Video Editor. NVIDIA NVENC acceleration is only available in Linux operating systems. OpenShot v2.6.0 and later includes Intel® Quick Sync Video encoding in Windows operating systems. If you have a CPU that supports Intel® QSV encoding, you can use the encoder by selecting the ( QSV ) MP4 (h.264 qsv) Target on the Export Video window. You do not have to change the Preferences window to use the Intel® QSV encoder.

Setting up hardware acceleration in OpenShot running on Linux distributions can be tricky. I've set up hardware acceleration several times and learned some Dos and Don'ts that I can share with you. There aren't any instructions or steps to follow because each customer's Linux installation is unique.

• Hardware acceleration only works with our PPA and source code installations, **not our AppImage** or the Linux package manager installations.
• If you choose our PPA install, ensure you use our Daily PPA to download the latest feature enhancements and bug fixes.
• Don't use NVIDIA's Linux graphics drivers. Use the proprietary video drivers from the package manager included with your distribution.
• Hardware acceleration only works with the first video device (display: 0).
• If you have a system with two video devices (integrated and discreet), you may have to use your system's BIOS to disable the CPU's graphics processor.
• Ensure that VDPAU and VA-API are working using vdpauinfo and vainfo.
• You don't have to select the graphics card in OpenShot's Preferences window on the Performance tab for hardware-accelerated decoding or encoding.
• Change the Target on the Simple tab of the Export Video window to (NVENC) MP4 (h.264 nv), then click the Export Video button.

**Comment by Colorjet3** [comment]
Hell @JMcPeak3373.  I haven't seen a response from you on this.  I am going to close the ticket for now.  Feel free to reopen if you have additional questions.
