### ISSUE TITLE
Nvidia decoder and encoder not working or glitching

### ISSUE THREAD

**Issue by Vi631** [OpenShot/openshot-qt#5170]
**Describe the bug**
When trying to export a video using Nvenc, i get this error: "Sorry, there was an error exporting your video: 
Error while writing raw video frame"
And while using Nvdec in preferences/performance it works but the pixels in video preview are not what they should be (they are mostly green)
Using CPU only works without errors.

**Steps to reproduce the behavior:**
1. Go to 'preferences/performance and set hardware decoder mode to nvdec'
2. Restart OpenShot
3. See first error in video preview
4. Try to export the video using nvenc
5. Video will not export

**Expected behavior**
The video should successfully export and the video preview should display correct pixels

**System Details**
- OpenShot Version: 3.0.0
- libopenshot Version:  0.3.0
- Platform: Linux-6.1.12-1-MANJARO-x86_64-with-glibc2.37
- Processor: AMD ryzen 5 4500
- Gpu: Nvidia Geforce RTX 2060 12GB
- Machine: x86_64
- Python version: 3.10.9
- Qt5 version: 5.15.8
- PyQt5 version: 5.15.9
- Qt Detected Languages: ['en-GB', 'en-Latn-GB']
- LANG Environment Variable: en_GB.UTF-8
- LOCALE Environment Variable: 
- Daily Build: Skipped this step

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/0oapgsjffuamgot6395gydppptqbh3yd/openshot-qt.zip) (7 KB)
- libopenshot.log: File too small or empty (not uploaded)
- With Debug mode:
- [libopenshot.log](https://github.com/OpenShot/openshot-qt/files/10950539/libopenshot.log)
- [openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/10950541/openshot-qt.log)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)

![bug2](https://user-images.githubusercontent.com/107301187/224537934-b196d0ef-28c6-4b53-93c0-727aed499137.png)
![bug3](https://user-images.githubusercontent.com/107301187/224537935-16f5ef63-c15d-46d0-a9fc-ff9a531f75c0.png)
![Screenshot_20230312_110759](https://user-images.githubusercontent.com/107301187/224537937-622585e4-d3dc-40ff-8ec2-c8500354c506.png)

**Comment by Colorjet3** [comment]
Hello @Vi631.  I am a very novice Linux user.  Here is an excerpt from the Openshot DEV team regarding hardware acceleration.  The 3rd bullet mentions not to use the NVIDIA driver.  I will need to get one of the developers to work with you if you need assistance installing the proprietary video driver for your linux build. 


Hardware acceleration is still experimental in OpenShot Video Editor. NVIDIA NVENC acceleration is only available in Linux operating systems. OpenShot v2.6.0 and later includes Intel® Quick Sync Video encoding in Windows operating systems. If you have a CPU that supports Intel® QSV encoding, you can use the encoder by selecting the ( QSV ) MP4 (h.264 qsv) Target on the Export Video window. You do not have to change the Preferences window to use the Intel® QSV encoder.
Setting up hardware acceleration in OpenShot running on Linux distributions can be tricky. I've set up hardware acceleration several times and learned some Dos and Don'ts that I can share with you. There aren't any instructions or steps to follow because each customer's Linux installation is unique.
• Hardware acceleration only works with our PPA and source code installations, not our AppImage or the Linux package manager installations.
• If you choose our PPA install, ensure you use our Daily PPA to download the latest feature enhancements and bug fixes.
• Don't use NVIDIA's Linux graphics drivers. Use the proprietary video drivers from the package manager included with your distribution.
• Hardware acceleration only works with the first video device (display: 0).
• If you have a system with two video devices (integrated and discreet), you may have to use your system's BIOS to disable the CPU's graphics processor.
• Ensure that VDPAU and VA-API are working using vdpauinfo and vainfo.
• You don't have to select the graphics card in OpenShot's Preferences window on the Performance tab for hardware-accelerated decoding or encoding.
• Change the Target on the Simple tab of the Export Video window to (NVENC) MP4 (h.264 nv), then click the Export Video button.

**Comment by Vi631** [comment]
Hello, thanks for your reply, i have uninstalled NVIDIA drivers and again installed them from my package manager instead (not from the nvidia run file on nvidia website), and installed openshot from source.

![Screenshot_20230314_143458](https://user-images.githubusercontent.com/107301187/225019517-d599304b-3e38-4090-9272-e523ef7709e4.png)

Here is the output from vdpauinfo:
[vdinfo.txt](https://github.com/OpenShot/openshot-qt/files/10968913/vdinfo.txt)

, va-api is not looking like it's working, here is the output from vainfo:
Trying display: wayland
Trying display: x11
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
vaInitialize failed with error code -1 (unknown libva error),exit

I have tried to fix the problem by reinstalling libva drivers or installing nvidia-vaapi-driver, however nothing worked and i have not been able to find any solution.

Openshot video export NVENC mp4 is still not working due to the same error message i mentioned earlier (in the first comment), maybe because the va-api is not working in my system.

Logs:
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/10969076/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/10969082/openshot-qt.log)
