### ISSUE TITLE
After uninstalling, reinstalling, delete qt file, etc openshot closes the program during export @30%...

### ISSUE THREAD

**Issue by woodwurker39** [OpenShot/openshot-qt#5174]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 3.0.0
- libopenshot Version:  0.3.0
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 55 Stepping 8, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.0.0-daily-11099-ec0c0b1c-b5bbab66-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/4503y0l5vo6mhb6vvzr47qeb2rm4wvka/openshot-qt.zip) (51 KB)
- [libopenshot.log](https://s3.amazonaws.com/logs.openshot.org/4503y0l5vo6mhb6vvzr47qeb2rm4wvka/libopenshot.zip) (10 KB)

**Exception / Stacktrace**
```_C_specific_handler            7ffe7a7f7f60
_chkstk                        7ffe7b972300
RtlRaiseException              7ffe7b921070
KiUserExceptionDispatcher      7ffe7b970f20
ZNjuce::FloatVectorOperations::add 7ffe4939dad0
ZNopenshot::Clip::get_time_mapped_frame::shared_ptr::Frame 7ffe4741bbb0
ZNopenshot::Clip::GetFrame::shared_ptr::Frame::TimelineInfoStruct 7ffe4742a0b0
ZNopenshot::Timeline::GetOrCreateFrame::shared_ptr::Frame::Clip::TimelineInfoStruct 7ffe4748bab0
ZNopenshot::Timeline::add_layer::shared_ptr::Frame::Clip 7ffe4748c500
ZNopenshot::Timeline::GetFrame 7ffe47493120
PyInit__openshot               7ffe496b51c0
PyLong_FromUnsignedLong        7ffe58abf890
PyEval_EvalFrameDefault        7ffe58aa0a00
PyEval_EvalCodeWithName        7ffe58a9cbd0
PyFunction_Vectorcall          7ffe58ab0770
PyEval_EvalFrameDefault        7ffe58aa0a00
PyEval_EvalCodeWithName        7ffe58a9cbd0
PyFunction_Vectorcall          7ffe58ab0770
PyMethod_New                   7ffe58abc0c0
PyVectorcall_Call              7ffe58abc590
PyInit_QtCore                  7ffe2b16a730
PyInit_QtCore                  7ffe2b16a730
PyInit_QtCore                  7ffe2b16a730
PyInit_QtCore                  7ffe2b16a730
PyInit_QtCore                  7ffe2b16a730
ZNQMimeType::qt_static_metacall::QObject::QMetaObject::Call 7ffe30fa6800
ZNQDialogButtonBox::standardButton::QAbstractButton 7ffe2f970ae0
ZNQMimeType::qt_static_metacall::QObject::QMetaObject::Call 7ffe30fa6800
ZNQAbstractButton::toggled  7ffe2f8d3660
ZNQAbstractButton::qt_static_metacall::QObject::QMetaObject::Call 7ffe2f8d5340
ZNQAbstractButton::mouseReleaseEvent::QMouseEvent 7ffe2f8d5b30
PyInit_QtWidgets               7ffe2ab4eca0
ZNQWidget::event::QEvent      7ffe2f827200
PyInit_QtWidgets               7ffe2ab4eca0
ZNQApplicationPrivate::notify_helper::QObject::QEvent 7ffe2f7e7f50
ZNQApplication::notify::QObject::QEvent 7ffe2f7eee00
PyInit_QtWidgets           ...

**Comment by Colorjet3** [comment]
Hello @woodwurker39.  There is a new Release-Candidate-11128.  Please do the following:
1.  Close Openshot.
2.  Go to Add or Remove Programs.  Search for Openshot and uninstall.
3.  Backup your c:\users\username\.openshot_qt folder.
4.  Delete c:\users\username\.openshot_qt folder.
5.  Go to openshot.org/download/#daily and download v3.1.0-Release-Candidate-11128 build.
6.  Install it and try the Export.
7.  If it fails again, then let us know if it fails at 30% consistently.
8.  If the answer to 7 is Yes then let's try and isolate a possible file/clip issue:

- Let's say you have 10 clips on multiple tracks.
- Remove the 2nd half of the clips from the tracks.
- Export.  If it fails, then remove a clip at a time and export until you narrow down to a clip.  Once you find it then we can deal with it.
-  If the export didn't fail at any time then it means the file causing the issue is in the 2nd half.
-  Remove the 1st half of the clips.
-  Shift all the clips from the 2nd half to the left at position 0:00.
-  Export and if it fails, then remove a clip one at a time and export until you find the clip that is causing the Export to fail.
-

**Comment by Colorjet3** [comment]
Hello @woodwurker39.  Any update on this?

**Comment by Colorjet3** [comment]
No update from user.
