### ISSUE TITLE
Version 3.1.0 freezes (Not responding) at startup

### ISSUE THREAD

**Issue by Sidder3** [OpenShot/openshot-qt#5195]
**Creating another thread, as advised by** @Colorjet3 

**Describe the bug:**

During startup application freezes and not responding.

**Steps to reproduce the behavior:**

1. Go to C:\Users\[My name]
2. Delete .openshot_qt folder
3. Go to Windows Settings / Apps / Program and Features and uninstall previous version of Openshot (RC 3.1.0 11199)
4. Go to https://www.openshot.org/download/ and download V 3.1.0 by clicking at big blue button.
5. Run installer
6. Launch Openshot
7. Openshot freezes and not responding.

**Expected behavior:**

I expect Openshot to work as intended after launch, not showing "Not responding" stauts

**System Details:**

- OpenShot Version 3.1.0.0 (Release version)
- Operating System: Windows 10 Home x64 22H2 (version: 19045.2788)
- CPU: Ryzen 9 5900x
- RAM: 32 Gb
- SSD
- NVidia RTX 2070S

**Log Files:**

No log files created

**Exception / Stacktrace:**

N/A

**Screenshots:** (Optional)

![3](https://user-images.githubusercontent.com/122721917/230772819-4032b450-a9e7-4d5e-9d8f-1fee3fda27cf.png)

![7](https://user-images.githubusercontent.com/122721917/230773157-6a97d73b-1809-4a96-b827-6e178418ffc4.png)

**Comment by Sidder3** [comment]
I have to add: all Daily builds post 11199 from March 31 - have similar behavior for me.
After rolling back to 11199 - issue disappears.

@Colorjet3 also asked "Provide the build # of the v3.1.0- that you are installing" -> I cant access Openshot/About as software freezes. But I can tell you hashes of installer or files in Openshot folder, if required.

Hope this helps.

**Comment by Colorjet3** [comment]
Hello @Sidder3.  I really appreciate that you started a new thread.  Furthermore, thank for all the information you provided.  Let's see if we can capture some log data so I can have one of the DEV team members take a look at your issue.

I realize this is making you go back and forth with different version installations but let's hope we capture good enough log data to identify the issue and come up with a fix.


1.  Install the latest v3.1.0 (the one you downloaded by clicking on the big blue button).
2.  Don't start it since we know it will not.
3.  Opens a command prompt and navigate to "Program Files\OpenShot Video Editor".
4.  Type "openshot-qt-cli.exe --debug" excluding the quotes and press the Enter key.
5.  Openshot will try to start with the command prompt window open in the back ground.
6.  When you get the "Not Responding" message choose "Close Program".
7.  From the Command prompt windows, copy the entire log file to notepad, save it, and attach it to this thread.

If form some reason this didn't work for you, you can try another way to capture log files:
1.  Assumption is that you still have v3.1.0 installed as above.
2.  Go to c:\users\username\.openshot_qt folder and delete these files only:  libopenshot.log and openshot-qt.log
3.  While in this folder, edit openshot.settings in a text editor (notepad or notepad++).
4.  Once you have it open in an editor, press CTRL+F to open the find window.
5.  Type "debug-mode" excluding the quotes in the "Find What" field then press Enter.
6.  You will find this section:
`
{
  "category": "Debug",
  "title": "Debug Mode (Verbose)",
  "value": false,
  "setting": "debug-mode",
  "restart": false,
  "type": "bool"
 },
`
8. Change "value": false, to "value": true,
9. Make sure you don't delete anything, change anything, etc., and save openshot.settings file.  
10. Start Openshot.
11.  When you get the "Not responding" message choose "Close Program".
12.  Once Openshot is closed attach the libopenshot.log and openshot-qt.log files to this thread.

**Comment by Sidder3** [comment]
Thank you for your response @Colorjet3. Here is resultant log file.

[log.txt](https://github.com/OpenShot/openshot-qt/files/11185952/log.txt)

**Comment by alighamdan** [comment]
any fixes?

**Comment by Colorjet3** [comment]
Hello @Sidder3.  I just noted that you are running Windows 10 Home addition.  We've seen similar issues with Windows 7 home and Windows 8.1 home where installing the Media Pack resolved the issue.  Please give this a try:

1.  Go to https://support.microsoft.com/en-us/topic/media-feature-pack-list-for-windows-n-editions-c1c6fffa-d052-8338-7a79-a4bb980a700a.
2.  Find and download the Microsoft Media Pack for your operating system.
3.  Install it and try Openshot again.

**Comment by Colorjet3** [comment]
Hello @alighamdan.  Please provide the following details if you are experiencing this same issue.  If not experiencing this same exact issue then please start a new posting.

1.  Operating system and version (windows 10 pro? Ubuntu 22.04 lts? etc.?
2.  Which version of Openshot are your installing and trying to run?
3.  Are you getting similar behavior as posted by @Sidder3 ?

**Comment by alighamdan** [comment]
my device:
Windows 10 Enterprise 21H2 (OS Build: 19044.2728), its 64x
installed 3.1.0 version
(8gb ram, Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz   2.59 GHz, NVidia GEFORCE 930M, HDD)

when i finished installing the app
I opened it for the first time I opened the app
I get the same as @Sidder3, I didn't use it even once in this version.
but I didn't get as the same of the second screenshot, only Not Responding... without crashing or anything else.

the file: [log.txt](https://github.com/OpenShot/openshot-qt/files/11193182/log.txt)

**Comment by Colorjet3** [comment]
Hello @alighamdan.  Thank you for that information.  I see that you are running the Enterprise version.  Are you in a work environment?  If yes, you may have some security configuration issues that is causing Openshot some issues.

The log.txt file you included, is this from the --debug log?  Thank you in advance!

**Comment by alighamdan** [comment]
> Hello @alighamdan. Thank you for that information. I see that you are running the Enterprise version. Are you in a work environment? If yes, you may have some security configuration issues that is causing Openshot some issues.
> 
> The log.txt file you included, is this from the --debug log? Thank you in advance!

i used --debug + turned value: true in verbose

**Comment by Colorjet3** [comment]
> > Hello @alighamdan. Thank you for that information. I see that you are running the Enterprise version. Are you in a work environment? If yes, you may have some security configuration issues that is causing Openshot some issues.
> > The log.txt file you included, is this from the --debug log? Thank you in advance!
> 
> i used --debug + turned value: true in verbose

If you turned on the verbose option as well, then please attach libopenshot.log and openshot-qt.log files to this thread.  You can find them in "c:\users\username\.openshot_qt" folder.

By the way, make sure to change "value": true, to "value": false, so that when Openshot start working your log files don't get too large.

That section should then look like this:

{   "category": "Debug",   "title": "Debug Mode (Verbose)",   "value": **true**,   "setting": "debug-mode",   "restart": false,   "type": "bool"  },

**Comment by alighamdan** [comment]
these are the files:
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/11193269/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/11193270/openshot-qt.log)

**Comment by alighamdan** [comment]
idk how, but i opened the app and didn't crash now....? weird

**Comment by strobel1x** [comment]
I'm having the same issue, also with the latest daily build.

- System: AMD Ryzen 5 2600, 32GB RAM, Nvidia Geforce RTX 2060 6GB
- OS: Windows 11 Pro for Workstations (version 22H2, build 22621.1485)

Logs:
[cmdline.log](https://github.com/OpenShot/openshot-qt/files/11198376/cmdline.log)
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/11198378/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/11198379/openshot-qt.log)

**Comment by Colorjet3** [comment]
> idk how, but i opened the app and didn't crash now....? weird

Hmm...interesting!  Is it still running ok now?

**Comment by Sidder3** [comment]
> Hello @Sidder3. I just noted that you are running Windows 10 Home addition. We've seen similar issues with Windows 7 home and Windows 8.1 home where installing the Media Pack resolved the issue. Please give this a try:
Go to https://support.microsoft.com/en-us/topic/media-feature-pack-list-for-windows-n-editions-c1c6fffa-d052-8338-7a79-a4bb980a700a.
Find and download the Microsoft Media Pack for your operating system.
Install it and try Openshot again.

Hello @Colorjet3 , sorry but after installing/reinstalling V 3.1.0 back and forth on weekend, I returned to RC 11199, which works fine for me.

I see you suggestion applies to N version of Windows 10, my version is not N anyway. I have Media Player, Groove Music and Skype installed already.

**Comment by alighamdan** [comment]
> > idk how, but i opened the app and didn't crash now....? weird
> 
> Hmm...interesting! Is it still running ok now?

yeah the Not responding had gone, i just changed the value from false to true i was this will work, i didn't work
then you told me to make it true to give you the log then turned to false and i run it after sometime and works without any problem

i mean: run -with false value-, run -true-, run -false-, run -true-, then i change to: `value: false`
after some hours i opened the app and it worked, idk if this is the reason ._. actually weird.
(i didn't reinstall or touching any files)
idk how

![image](https://user-images.githubusercontent.com/73795044/231482796-84751377-3476-4e32-9f55-c386a7474b73.png)

**Comment by Colorjet3** [comment]
Hello @alighamdan.  Now that Openshot is running, and for the future, you can go to Edit | Preferences | Debug tab.  Here you can find the "Debug Mode (Verbose)".  This is the True / False you were changing in the openshot.settings file.  We were doing this manually because Openshot wasn't starting for you or the "Not Responding".

Just make sure that "Debug Mode (Verbose)" is NOT checked.  Otherwise your log files will get very large.  Only enable it when directed to do so by technical support.

**Comment by alighamdan** [comment]
> Hello @alighamdan.  Now that Openshot is running, and for the future, you can go to Edit | Preferences | Debug tab.  Here you can find the "Debug Mode (Verbose)".  This is the True / False you were changing in the openshot.settings file.  We were doing this manually because Openshot wasn't starting for you or the "Not Responding".
> 
> Just make sure that "Debug Mode (Verbose)" is NOT checked.  Otherwise your log files will get very large.  Only enable it when directed to do so by technical support.

Ok thx for help

**Comment by strobel1x** [comment]
> I'm having the same issue, also with the latest daily build.
> 
> * System: AMD Ryzen 5 2600, 32GB RAM, Nvidia Geforce RTX 2060 6GB
> * OS: Windows 11 Pro for Workstations (version 22H2, build 22621.1485)
> 
> Logs: [cmdline.log](https://github.com/OpenShot/openshot-qt/files/11198376/cmdline.log) [libopenshot.log](https://github.com/OpenShot/openshot-qt/files/11198378/libopenshot.log) [openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/11198379/openshot-qt.log)

I finally got my problem solved - the key line in the log was this one:
`WARNING preview_thread: Your sample rate (48000) does not match OpenShot (44100). Adjusting your 'Preferences->Preview->Default Sample Rate to match your system rate: 48000.`
I changed that value in the `openshot.settings` file and now I don't get the "Not responding" error anymore (but when changing it back the error comes again).
Maybe this helps others to get it working and eventually to fix the code.

**Comment by Colorjet3** [comment]
Very interesting @strobel1x and thank you for sharing.  The Sample rate mismatch typically has never caused Openshot to "Not Respond" but typically associated with audio being out of sync or sounding cartoonish, etc. 

Glad this is now resolved.
