### ISSUE TITLE
MKV file was not found, but the file is osp extension

### ISSUE THREAD

**Issue by gustavohen27** [OpenShot/openshot-qt#5259]
**Describe the bug**
A clear and concise description of the issue

**Steps to reproduce the behavior:**

**Expected behavior**

**System Details**
- OpenShot Version: 3.1.1
- libopenshot Version:  0.3.2
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['pt-BR', 'en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.1.1-daily-11503-b1104d89-08c2cdd1-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/2dy2mwg3ehmmsr4g4agghnmtihbwqttd/openshot-qt.zip) (11 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Capturas de Ecrã** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
Hello @Abduzek.  When you open the .osp file are you getting a "Missing File" message box which includes the name of the file that OpenShot is looking for?

**Comment by gustavohen27** [comment]
> Hello @Abduzek. When you open the .osp file are you getting a "Missing File" message box which includes the name of the file that OpenShot is looking for?

yes and then the window goes into a loop

**Comment by Colorjet3** [comment]
Hello @Abduzek.  Please be sure to read the entire answer.


The Case of "Missing Files"!

This situation is widely misunderstood, with many people mistakenly believing that Openshot is "frozen" or "stuck in a loop." Although various solutions suggest killing the Openshot process, they often fail to properly recover the original project and its missing files.

Let me provide some context and explanation regarding the "Missing Files" issue/process.  When you create and save a project in Openshot, any files imported into the software (such as videos, audio, and images) must remain intact throughout the project's duration. This means that these imported files should not be renamed, deleted, or moved to different folders.   Additionally, the full path where these files are located should not be renamed either.  This principle applies to other video editing software as well. 

To illustrate what occurs, I'll provide a detailed example:

	1. All source files are saved in the "c:\temp" folder.  The files are file01.webm, file02.gif, and file03.png.
	2. I create a project called "c:\MyProjects\Test01.osp" and imported the 3 files from step 1.
	3. I drag "file01.webm" onto Track 4.
	4. I drag "file02.png" onto Track 5.
	5. I do not drag "file03.png" onto any track.
	6. Now I save the project.
	7. I close Openshot.
	8. I rename the "c:\temp" folder to "c:\temp99."
	9. I launch Openshot and open the "Test01.osp" project.
	10. I encounter the "Missing File (file01.webm)" message box, which states that "file01.webm cannot be found."  My only option is to click OK, so I do.
	11. Openshot then gives me the option to locate this file by opening File Explorer (in the case of Windows) or the native File Manager (in the case of Linux or Mac). Take note of the window's title, which states "Find directory that contains: file01.webm." It wants to know the folder where this file resides in.
	12. At this point, I must navigate to the folder where "file01.webm" is located, which, due to the folder renaming, is now "c:\temp99." If I go into the folder itslef, only sub-folders will be listed.  No files will be listed. 
	13. At the bottom of the File Explorer/File Manager, there is an option to click "Select Folder." I click on it.
	14. Finally, the project opens smoothly.
	15. The reason I didn't receive additional prompts for the other two files ("file02.gif" and "file03.png") is that Openshot continues searching for the remaining files in the last provided folder ("c:\temp99"). Since the other files exist there, Openshot finds them and proceeds.
	16. If "file02.gif" and "file03.png" were located in different folders, renamed, or deleted, I would have gone through the "Missing File (filename.xxx)" process again.
	17. Now that Openshot has located all the files, it's crucial to save the project at least once to update the file paths from "c:\temp..." to "c:\temp99...". This way, when reopening the project, the "Missing Files" process won't restart from the beginning.
	
The aforementioned scenario describes a case where I could navigate to the new folder name, and Openshot successfully found the files. However, let's assume I'm unaware of the issue and instead of navigating to the proper folder ("c:\temp99"), I choose to "Cancel" when prompted for the folder path. Using the same example starting from Step 8 (folder renamed to "c:\temp99"):
	1. I launch Openshot and open the "test01.osp" project.
	2. I encounter the "Missing File (file01.webm)" message box, stating that "file01.webm cannot be found." I click OK.
	3. Openshot then offers the option to find the file by opening File Explorer or the native File Manager. The window's title reads "Find directory that contains: file01.webm." Again, it is searching for the folder, not the file itself.
	4. Instead of navigating to the folder and clicking "Select Folder," I choose to select Cancel. Consequently, I skip "file01.webm."
	5. Openshot now skips this file and proceeds to the next file ("file02.gif").
	6. I repeat the process by clicking OK and then Cancel, thus skipping "file02.gif."
	7. Openshot continues skipping this file and moves on to the next one ("file03.png").
	8. I repeat the process again by clicking OK and then Cancel, effectively skipping "file03.png."
	9. Here is where it becomes confusing, and many, if not all, users assume that Openshot is stuck in a loop (there may be room for improvement in the following steps).
	10. Up to this point, I have been prompted three times for three missing files. All these files are part of the "Project Files" tab. Now, recall that I had dragged "file01.webm" and "file02.gif" onto Tracks 4 and 5, respectively. These files are considered clips on the timeline. Here's what happens next:
		a. Openshot now looks at the tracks containing clips and attempts to locate them, restarting the process.  Since "file01.webm" and "file02.gif" were on the tracks, I am prompted once again for each of them. It's important to note that since "file03.png" wasn't dragged onto any track, I won't receive a prompt for it.
		
Imagining this process with larger projects can be frustrating.  Users might end up killing the Openshot process but find themselves back where they started with their existing project.  If I realized that renaming the "c:\temp" folder to "c:\temp99" caused the issue, I would kill Openshot to stop the "Missing File" process (ideally, there should be a more graceful option like "Cancel All"). Then, I would rename the folder back to "c:\temp," start Openshot, open the project, and everything would work as expected.

The above example illustrated a simple case of folder renaming. In other scenarios: a. If you deleted source files outside of Openshot, you need to recover them and ensure they are in their original folder. If you recover them in a different folder, you will have to go through the process of informing Openshot about the new file location. b. If you renamed a source file outside of Openshot, you must rename it back to its original name.
There are alternative approaches to avoid this issue, but they typically involve disregarding folder organization, etc. Most users prefer organizing their files in a way that makes sense to them. In my case, I have chosen the following organization method:

	1. C:\work\Images: This is where I save all special image files I download, not related to any specific project but shared among many projects.
	2. C:\work\pics: This folder contains multiple sub-folders with family, trip, etc., content (movies, images, audio).
	3. C:\work\music: This folder contains various sub-folders with different audio files, which may include video/audio as well. These files are shared among many projects.
	4. C:\work\VideoProjects\Openshot: This is where I save all my "Projectname.osp" files. This folder also contains the accompanying "projectname_assets" folder.
	5. I also have folders like C:\work\VideoProjects\Blender, C:\work\VideoProjects\DaVinci, etc., as I work on projects using other applications.
	6. C:\work\Videos\Openshot: This is where I save my output (exports). I also have folders like C:\work\Videos\DaVinci, C:\work\Videos\OBS, etc.
	7. C:\work\Sounds: These are custom-made or downloaded audio files that are shared among many projects.
Everyone has their unique way of organizing files, and it's crucial to remember not to make changes to file paths, rename files, or delete files when working with video editors, as it can lead to missing file issues. I hope this explanation helps you and others dealing with similar situations.

**Comment by Colorjet3** [comment]
Hello @Abduzek.  I am closing this ticket assuming that your issue has been resolved.  Feel free to reopen if the issue persists.
