### ISSUE TITLE
Openshot freezes when moving the timeline slider to another position. [SOLVED]

### ISSUE THREAD

**Issue by thereticle** [OpenShot/openshot-qt#5282]
**Describe the bug:**
Every time I move the timeline slider to another position, the program freezes like it is not able to update the cache (or to load frames). This issue seems related to difficulty in managing cache. I tried changing the cache parameters many times but the behavior is the same. A similar problem also appears during normal playback: I see the blue cache bar advance a little in front of the cursor then suddenly the bar stops and playback too.
I also tried to purge the program by also deleting the .openshot-qt directory in the /home directory, but the behavior is still the same.
What else could I do?

**Steps to reproduce the behavior:**
1. Open the project as usual
2. Click on Play (the video starts)
3. Click on the upper side of the timeline (where the cursor is) in a different position (out of the blue bar of the cache)
4. The program freezes for many minutes

**Expected behavior:**
Video playback should resume immediately (or nearly so) from the newly selected point on the timeline.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 3.1.1 daily (07/12/23)
- Operating System / Distro: Xubuntu 23.04
- PC with i5-8600K, GeForce RTX 2070 SUPER, 64 GB RAM

**Comment by Colorjet3** [comment]
Hello @thereticle.  Performance is one are that still needs much improvement and the lead developer is very aware of this.  Until this issue is resolved/improved, here are some things you can try to make things a bit better:

• Fine tuning v3.1.1
	○ Go to https://www.openshot.org/user-guide/. Search for Cache and click on Preferences > Cache. There are 4 new cache settings to play with.
	○ Go to Edit | Preferences | Cache tab
	○ The Cache Limit(MB): This is not new, but be careful making this too large. I have a 32GB RAM but I rarely go over 4096. What happens with v3.x.x is the constant rebuilding of the Cache causes slow down during the editing/previewing process.
	○ Cache Max Frames: by default it is set to 600. I bump this up to the max of 1024.
	○ Cache Pre-roll: Min Frames: Change to 48
	○ Cache Pre-roll: Max Frames: Change to 96

These Cache settings seem to only help with performance while editing/previewing. I have not noticed any improvements in Exporting or Animated titles creation.
The nice part about the Cache Limit (MB) is that you can change it on the fly without having to restart OpenShot or reopen a project. I have found that when I am doing lots of edits, I change this setting to 2048 (you can even make it smaller) so that during the editing part OpenShot is more responsive. When I get into previewing my changes, and especially with both large and/or complex projects, I change my Cache Limit (MB) to 8192 (I have a 32GB RAM system). This assumes you are clicking on Play and watching your work. You will note that when you stop or make some changes, it takes longer for the Cache to get rebuilt (you will note a solid blue line building up right above the top most track). When you want to go back to editing (may be not just for one or two), I would change the Cache Limit back to 2048 (or even 1024).

Two other things that may improve performance are:
1.  Make your "Video Preview" smaller.
2.  Choose a lower resolution profile during editing.  This will not impact your final Exported project.

As I mentioned, the lead developer is well aware of this and there are many more changes planned to improve the overall performance of OpenShot (previewing, editing, animation, and exporting).

By the way, my system is:
• AMD Ryzen 7 3700X (8 Cores)
• 32GB RAM
• RTX 2060 (6GB RAM)
• Sabrent Rocket Q (1TB) Hard Drive.
• Windows 11.
• I also run Windows 10 on a separate SSD (Samsung SSD 850 EVO 500MB) drive in the same system. Haven't noticed much difference in performance with the exception of the disk writes.

I hope this helps and would like to hear back from you on your experience after applying some of these changes.

**Comment by thereticle** [comment]
> Hello @thereticle. Performance is one are that still needs much improvement and the lead developer is very aware of this. Until this issue is resolved/improved, here are some things you can try to make things a bit better:
> 
> • Fine tuning v3.1.1 ○ Go to https://www.openshot.org/user-guide/. Search for Cache and click on Preferences > Cache. There are 4 new cache settings to play with. ○ Go to Edit | Preferences | Cache tab ○ The Cache Limit(MB): This is not new, but be careful making this too large. I have a 32GB RAM but I rarely go over 4096. What happens with v3.x.x is the constant rebuilding of the Cache causes slow down during the editing/previewing process. ○ Cache Max Frames: by default it is set to 600. I bump this up to the max of 1024. ○ Cache Pre-roll: Min Frames: Change to 48 ○ Cache Pre-roll: Max Frames: Change to 96
> 
> These Cache settings seem to only help with performance while editing/previewing. I have not noticed any improvements in Exporting or Animated titles creation. The nice part about the Cache Limit (MB) is that you can change it on the fly without having to restart OpenShot or reopen a project. I have found that when I am doing lots of edits, I change this setting to 2048 (you can even make it smaller) so that during the editing part OpenShot is more responsive. When I get into previewing my changes, and especially with both large and/or complex projects, I change my Cache Limit (MB) to 8192 (I have a 32GB RAM system). This assumes you are clicking on Play and watching your work. You will note that when you stop or make some changes, it takes longer for the Cache to get rebuilt (you will note a solid blue line building up right above the top most track). When you want to go back to editing (may be not just for one or two), I would change the Cache Limit back to 2048 (or even 1024).
> 
> Two other things that may improve performance are:
> 
>     1. Make your "Video Preview" smaller.
> 
>     2. Choose a lower resolution profile during editing.  This will not impact your final Exported project.
> 
> 
> As I mentioned, the lead developer is well aware of this and there are many more changes planned to improve the overall performance of OpenShot (previewing, editing, animation, and exporting).
> 
> By the way, my system is: • AMD Ryzen 7 3700X (8 Cores) • 32GB RAM • RTX 2060 (6GB RAM) • Sabrent Rocket Q (1TB) Hard Drive. • Windows 11. • I also run Windows 10 on a separate SSD (Samsung SSD 850 EVO 500MB) drive in the same system. Haven't noticed much difference in performance with the exception of the disk writes.
> 
> I hope this helps and would like to hear back from you on your experience after applying some of these changes.

Thank you, #Colorjet3, I really appreciate the guide you posted. However, I must say that I had already tried more or less all the options you mentioned. The strange behavior that I see on my PC is that when I move the timeline cursor outside the blue cache bar, the program freezes as if it fails to cache from the new position. This also happens with very low Pre-roll Max Frame values (like 60 or 48). Additionally, I have noticed that during video playback, the Pre-roll frames are always a very small percentage of the total cached frames, even though the Cache Ahead (percentage) value is at 0.80.

Now, initially, I thought that the problem was due to the low power of my PC (I had an i7-2600k, 16GB RAM, and an NVIDIA RTX1060). So, I used a slightly more powerful computer (i5-8600K, GeForce RTX 2070 SUPER, 64GB RAM), but the result is the same even though I have repeatedly purged Openshot and reinstalled it after deleting the .openshot-qt folder.
At this point, the only remaining possibility would be some issues related to the Operating System (which I transferred as it was from the old PC to the new one).

I will try other attempts with the settings.

**Comment by thereticle** [comment]
Update.

After many other attempts and not making any progress, I began to doubt whether the problem was in the video, even though its source was the same as others I edited without any issues. 
I performed a frame check using Avidemux, but no errors were found. Then, I tried saving the video using Avidemux, and surprisingly, this solved the problem, even though I didn't make any apparent modifications as I simply used the "copy" option. 
Therefore, I can't exactly pinpoint what the issue was, but it has been resolved. 

So, I suggest that anyone experiencing similar problems should perform a video check.

@Colorjet3: Thank you again for your support.

**Comment by Colorjet3** [comment]
Hello @thereticle.  You are very welcome and I am glad you found a resolution and sharing it here.  This should also help other users with similar issues.

I will have to keep Avidemux in my arsenal of tools for this type of an issue.  I often recommend user to use something like VLC, Handbrake, or Shutter Encoder to convert the source back to .mp4, even if the source is .mp4, and most of the time this resolves the issue.

I have seen some other video editors where natively they can check for irregularities in the original and convert as they are imported.  Obviously, OpenShot doesn't have that ability at this time and may be a future enhancement.

Best of luck with your projects.

**Comment by lozzo52** [comment]
I used VLC to convert from .mp4 to .mp4 and the preview plays through smoothly now.
