### ISSUE TITLE
How Do I Reset Project Property Back To Normal?

### ISSUE THREAD

**Issue by zibdie** [OpenShot/openshot-qt#5287]
**Question:**
A long time ago, I tried to modify the video project properties to fit in an Instagram video but I forgot how. Now OpenShot is stuck on this and even if i drop a new video in a new project, OpenShot does not inherit the properties of that video [Opened a suggestion for it: https://github.com/OpenShot/openshot-qt/issues/5286 ]

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 
![image](https://github.com/OpenShot/openshot-qt/assets/59550818/ac7f4ca2-7917-41cd-b813-2a08055a7bc7)

- Operating System / Distro: Windows 11

**Screenshots:** (Optional)

What I see in OpenShot when I export out of OpenShot

![image](https://github.com/OpenShot/openshot-qt/assets/59550818/d84b1853-a6fc-4083-8c53-c2ab9b52cff8)

What the raw video should be

![image](https://github.com/OpenShot/openshot-qt/assets/59550818/354e918f-2441-4f85-a3a9-a1767d3c02d0)

Raw video properties according to VLC
![image](https://github.com/OpenShot/openshot-qt/assets/59550818/12066c5f-afbc-4330-97cc-e16f109d2c4b)

My default profile preference
![image](https://github.com/OpenShot/openshot-qt/assets/59550818/b31f0d1c-500e-4d1f-bf6a-36a925abf15a)

**Comment by Colorjet3** [comment]
Hello @zibdie.  
1.  When you first install OpenShot, this is what the default settings are:
![DefaultSettings](https://github.com/OpenShot/openshot-qt/assets/59097181/84d33279-1be5-4f4c-b4bd-50f17745389d).

2.  If you change them and restart OpenShot then those become the new Default Settings.  If you don't remember what changes you made and you want to get back to the Default Setting when you first installed OpenShot you can do this:
a.  Close OpenShot.
b.  Make a backup of c:\users\username\.openshot_qt folder.
c.  Start OpenShot and check Edit | Preferences.  Everything should be back to the original installation settings.

As for your Export issue, I am not clear on what the issue is.  Your shared images shows the Exported file to be all white and seems to match what your raw file is as well using VLC.

A bit more detail and possibly share your original file here so we can play with it as well.

**Comment by zibdie** [comment]
I just ended up looking through the profiles and found one that fits right. Not the ideal solution and wish something like my suggestion: https://github.com/OpenShot/openshot-qt/issues/5286 would be implemented. Closing
