### ISSUE TITLE
Configuation Changes Not Being Saved

### ISSUE THREAD

**Issue by jmb-555** [OpenShot/openshot-qt#5307]
**Describe the bug:**
The audio sample rate in preferences is not being saved. See the below video. I get a message to restart the program but nothing saves.

https://www.youtube.com/watch?v=QD8Raoyop38

**Expected behavior:**
Seems as if changes should be saved but are not.

**System Details:**
- OpenShot Version [3.1.1.]: 
- Ubuntu 22.04.3 LTS

**Comment by Colorjet3** [comment]
The behavior of the Default Audio Sample Rate within OpenShot was change sometime ago due to many reported issues with Audio during editing and exporting.  The behavior now is that when OpenShot starts it checks the Default Audio **Device** sample rate in the Operating System and whatever that sample rate is it matches it in OpenShot.

So, if you want to work with 48000 sample rate then you need to change your Ubuntu Default Device Audio Sample rate from  22050 to 48000.  Then restart OpenShot and the Default Audio Sample rate will change to 48000 as well.

Obviously this assumes that your Default Audio Device support 48000 sample rate.

**Comment by jmb-555** [comment]
Oh, well i got another possible problem i found. If i start my computer and then connect a bluetooth speaker, I do not get an option to select the bluetooth speaker as the playback audio device in preferences. The only option I can select is the default audio device and no other devices are even listed.

**Comment by Colorjet3** [comment]
Hello @jmb-555 I think you should start a new thread for this blue tooth issue since it is not related to this topic.  Mixing different issues in a single thread makes it challenging to manage from support perspective and difficult for others to find solutions when searching for answers.
