### ISSUE TITLE
 Save Still Frame feature is breaking 

### ISSUE THREAD

**Issue by Shellie-Lewis** [OpenShot/openshot-qt#5394]
**Using camera icon below the preview box to Save Still Frame results in a black box .png or partial layer image [not all layers displayed in preview]:**

**Steps to reproduce the behavior:**
1. Go to user interface in open program,
2. Click on Camera icon shown in the lower right hand corner of the preview box,
3. Go to project folder to see saved image,
4. See error, the saved image image is black or an incomplete selection not showing all layers of video tracks
5. Feel sad because I use this feature a lot and there is no keyboard shortcut or Export > Still Image in topnav menu to try to get the still frame save to try besides the camera icon button not saving the still frame   ;__;

**Expected behavior:**
See a saved .png of the image displayed in the video preview window.

**System Details:**
- OpenShot Version most current 23 Jan 2024 3.1.1  :  libopenshot version: 0.3.2
- Operating System / Distro: [Windows 10]

**Log Files:**
n/a

**Exception / Stacktrace:**
n/a

**Screenshots:** (Optional)
not helpful beyond verbal description

**Comment by Colorjet3** [comment]
Hello @Shellie-Lewis.  I am running Windows 11 Pro and Openshot v3.1.1 (the latest DEV Daily build #11627).  I just performed a test with positive results.

1.  I opened an existing project that I had.
2.  Ensured that I have two clips (one on Track 5 and the other just below it on Track 4).  The two left edge are aligned on the timeline.
3.  I made the size of the clip on Track 5 smaller than the clip on Track 4 so that when I position the playhead on the clip on Track 5 I also see the clip from Track 4 in the "Video Preview" window.
4. Now I click on the Camera icon.
5. I am asked to save the .png file which I do.  I am able to see this with VLC and Photos applications without issues.
6. I now import this into OpenShot and all is good.

Here are some recommendations:
1.  Restart your computer and make sure it is healthy.
2.  Make sure you have plenty free disk space.
3.  Upgrade OpenShot to the latest DEV daily build.  Go to openshot.org/download/#daily.  Download build #11627 and install it.
4.  If you are still having this issue try creating a test project and test again.

**Comment by Shellie-Lewis** [comment]
@Colorjet3 

1. did do a restart more than once, 
2. have 153 GB disk space free on HD which is good for me,
3. have 3.1.1 - did get build #11627 updated, 
4. yeah that worked now for a test project, so the Old Enemy of my life, video filetype encoding mysteries, seem to be the issue as I am notice a bounding box appear on the top layer of the project and not the others: I selected all layers on the timeline and that was not working either. Video do be like that doe. 

I will see how the next project goes for this. 

Many thanks!

**Comment by Colorjet3** [comment]
You are welcome @Shellie-Lewis.  One thing to do with your video file type is to run it through a converter like VLC, HandBrake, or ShutterEncoder and convert to a .mp4 file, even if it is a .mp4 to begin with.  Just create a new file.  Now import this in and see if it works any better.

I'll close this issue but feel free to reopen it if needed.
