### ISSUE TITLE
sound not syncking with video in editor 

### ISSUE THREAD

**Issue by horseymart** [OpenShot/openshot-qt#5396]
when editing a vidoe the play back sound is to fast i look in to it, and done apropite trouble shhot but dose not fix it!
the sound is running to fast and does not mtch the video im editing it was fine before update 3.1.1
win11 

https://github.com/OpenShot/openshot-qt/assets/130850040/2099711d-a108-4a3c-a01b-ae697421d5a0

  

**Describe the bug:**

**Steps to reproduce the behavior:**

**Expected behavior:**

**System Details:**
- OpenShot Version [e.g. 2.4.3]: {{ log_context.openshot_qt_version }}
- Operating System / Distro: [e.g. Windows 10, Linux Mint 17.1]

**Log Files:**
If you are experiencing a crash, please collect and attach logs of the problem.  Log files can be found in the `.openshot_qt` folder in your user home directory. Log files over 2 MB in size will need to be compressed, please attach a ZIP file instead of the raw logs.

**Exception / Stacktrace:**
If you are experiencing a crash or strange output on the command line, please attach a small snippet of the exception here, but please keep it as small as possible (for readability).

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
1.  Close OpenShot if running.
2.  Make a backup of c:\users\username\.openshot_qt folder.
3.  Delete c:\users\username\.openshot_qt folder.
4.  Go to openshot.org/download/#daily and download the latest DEV Daily Build available.
5.  Install it and see if your audio issue has been resolved.

**Comment by horseymart** [comment]
no it did not solve any thing still the same issue as above

**Comment by Colorjet3** [comment]
No worries.  Let's try one more thing.  Run your source video through a converter like VLC, Handbrake, or ShutterEncoder and convert it to .mp4 file (even if the original is a .mp4) with a new name.  Now import this new file into OpenShot and see if the audio issue is resolved.

**Update:**If you are still having issues then:
1.  What is your operating system/version (windows 10?  Linux mint 17? etc?)
2.  What is your operating system environment output audio device (speakers? headphones?) and what is the sample rate set to?
3.  What happens if you export your project even though during the preview the audio is not in sync?  Does the exported project play ok?

**Comment by horseymart** [comment]
Device name	Martin-PC
Processor	AMD Ryzen 9 5900X 12-Core Processor               3.70 GHz
Installed RAM	32.0 GB
Device ID	0C9632E0-33C5-4ED3-B338-B5598EE1F1FF
Product ID	00326-10000-00000-AA981
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 11 Home
Version	22H2
Installed on	‎07/‎12/‎2023
OS build	22621.3085
Experience	Windows Feature Experience Pack 1000.22684.1000.0

![image](https://github.com/OpenShot/openshot-qt/assets/130850040/37af70f3-f640-4cf8-829f-44c58a4c798a)
![image](https://github.com/OpenShot/openshot-qt/assets/130850040/a4816984-9de9-4abd-9278-a1ddedfbbb7e)
![image](https://github.com/OpenShot/openshot-qt/assets/130850040/14497c29-9edf-4d4c-b931-a42cb7d41a3a)

the audio synks correctly when exported

**Comment by horseymart** [comment]
![image](https://github.com/OpenShot/openshot-qt/assets/130850040/c986c764-0e6a-4767-ba73-408f98aa8276)

**Comment by Colorjet3** [comment]
Thank you for all the information you provided.

Ok, this makes sense now because OpenShot seems to struggle with Headphones (a known issue that has been reported by many users) and no permanent fix at this time.

At least you know that your Exported project is in synch so you can move forward with your project.

Some things to try:

1. In the last screen shot in the "Signal Enhancement" section, disable the "Enable Audio Enhancements".  Restart Windows, open your project and test.  Did this make a difference?  If not, put that setting back to being enabled.
2. To confirm the headphones being the issue you can unplug it for now and use your speakers.  You will need to restart OpenShot.  Did the audio sync within OpenShot when using the Speakers?
3. Plug the headphones back in, restart windows.  start Openshot and go to Edit | Preferences | Preview tab and ensure that the sample rate is matching your headphones sample rate set in Windows.
4.  In Edit | Preferences | Preview tab, make a note of "Playback Audio Device".  Click on the drop down and you will see a few other options to select (Windows Audio: headphonesname & DirectSound: headphonesname".  Try each one of those ensuring to restart OpenShot each time you make change and test.

If you are still having the issue with the headphones then we need to assign this to the lead developers for his review and input.

**Comment by horseymart** [comment]
sonar just stream mixer! i can change the out put! but can exit sonar GG just for editing? 
will try as sujested

**Comment by horseymart** [comment]
![image](https://github.com/OpenShot/openshot-qt/assets/130850040/98c1f8b3-1904-4417-9e8e-aa1253c360bc)
changing sample rate to 96000 openshot seam to of fixed it with matching it to sonar sample rate! 

thxs for your help

**Comment by Colorjet3** [comment]
That is great @horseymart and you are welcome.
