### ISSUE TITLE
instant crash

### ISSUE THREAD

**Issue by Ludesss** [OpenShot/openshot-qt#5403]
**Describe the bug**
Program crashes instantly after trying to separate audio from video onto different tracks

**Steps to reproduce the behavior:**
1. Go to  video you want audio of
2. Right click and hover over separate audio
3. Scroll down to single channel

**Expected behavior**
A channel of audio below the video i took it from

**System Details**
- OpenShot Version: 3.1.1
- libopenshot Version:  0.3.2
- Platform: Windows-10-10.0.19041
- Processor: AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Skipped this step

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/8747wzzquifrg4323k37v7mtjt7nz1gg/openshot-qt.zip) (18 KB)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by Ludesss** [comment]
this is the action before it crashes it looks like

![crash](https://github.com/OpenShot/openshot-qt/assets/158983487/4372631e-4454-4345-8fa8-dd086668672e)

**Comment by Colorjet3** [comment]
This may be fixed in the latest Dev Daily Build.  Please do this:

1.  Close OpenShot if running.
2.  Uninstall Openshot via Add or Remove Programs.
3.  Make a backup of c:\users\username\.openshot_qt folder.
4.  Delete c:\users\username\.openshot_qt folder.
5.  go to openshot.org/download/#daily and download the latest dev daily build #11627.
6.  Install it.
7.  Open your project and test again.

If OpenShot is still crashing then:
1.  What type of a file is it (.mov? .mp4? etc?)
2.  Run your file through a converter like VLC, Handbrake, or ShutterEncoder.  Convert it to a .mp4 even of the original is a .mp4 and give it a new name.
3.  Import this new converted file into OpenShot and test.

If still crashing, then if you can share the file with us (assuming you want to), then we can test with it.

**Comment by Ludesss** [comment]
installing the daily build definitely worked thank you so much!

**Comment by Colorjet3** [comment]
That is great.  Best of luck with your project(s).
