### ISSUE TITLE
Can't open old file : No module named 'classes.marker' error.

### ISSUE THREAD

**Issue by flccrakers** [OpenShot/openshot-qt#546]
Hello, 

**System Details:**
* Operating System / Distro: Ubuntu 16.04
* OpenShot Version: 2.2.0
**Issue Description and steps to reproduce:**
I can not open old project from version 1.4.3 on openshot. I get this error: 

project_data:ERROR Failed to load project file /home/hoonakker/CROISSANCEO/social-selling/VIDEOS/5-critères-pour-reconnaiter-un-aimant-a-prospects-efficace/5-critères-pour reconaitre un aimant a prospoects efficace.osp: No module named 'classes.marker'

What can I do ?
Best
Frank

**Comment by jonoomph** [comment]
Can you please attach your 1.4.3 project file here, and I'll take a look. Looks like I'm missing support for 'markers' in an old project.

**Comment by flccrakers** [comment]
Here is the file.
Thank You !

2017-03-27 22:37 GMT+02:00 Jonathan Thomas <notifications@github.com>:

**Comment by jonoomph** [comment]
I don't see any file attached. =)

**Comment by jonoomph** [comment]
Okay, I found the issue. Any old project which contained a marker or effect was failing to open. This is now fixed in our latest daily build. Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. _It might take a couple hours for the latest version to appear._

**Comment by flccrakers** [comment]
Ok, thank you !

2017-03-29 8:16 GMT+02:00 Jonathan Thomas <notifications@github.com>:
