### ISSUE TITLE
"Don't show this again" checkbox on messages like the one pictured:

### ISSUE THREAD

**Issue by MesaBlack** [OpenShot/openshot-qt#5489]
![Screenshot 2024-04-03 11 39 35 AM](https://github.com/OpenShot/openshot-qt/assets/132141735/e413dacb-c404-4680-82ab-257b2c5a5f44)

Verified as no similar issues have been filed before.

**Describe the new feature:**
A simple don't show this again checkbox.

**Describe the solution you'd like:**
I want smoother image imports,, without those messages in the way.

**Describe alternatives you have considered:**
N/A

**Comment by Colorjet3** [comment]
Are you being prompted multiple times while you have selected multiple image files?  I am just trying to understand this scenario.

I think instead of "Don't show this again" a better solution might be "Skip Image Sequence importing for now".  This will allow your import to complete, smoothly, without OpenShot prompting your for Image sequence.

I am suggestion this, because if you offer a "Don't show this again", then there needs to be a way to re-enable that functionality as there are times that you want to import an image sequence.

**Comment by MesaBlack** [comment]
> Are you being prompted multiple times while you have selected multiple image files? 

yes

**Comment by Colorjet3** [comment]
ok, that makes sense as OpenShot is recognizing multiple opportunities for importing "image sequences".

What are your thoughts on my suggestion?

**Comment by Colorjet3** [comment]
I will submit an enhancement request to the lead developer.  He will review it and if approved by him, he will get it in the queue to be worked on.

I wouldn't expect it any time soon because there are higher priority bugs in the channel to be fixed.

**Comment by Colorjet3** [comment]
Enhancement request has been submitted.
