### ISSUE TITLE
[development] Script Effect 

### ISSUE THREAD

**Issue by 625781186** [OpenShot/openshot-qt#5501]
https://github.com/OpenShot/libopenshot/issues/83

https://github.com/OpenShot/libopenshot/issues/362

[Clip::apply_effects](https://github.com/OpenShot/libopenshot/blob/a9e34a9bce59fdb78123c0eb824a171948c6b9e8/src/Clip.cpp#L1194)

![image](https://github.com/OpenShot/openshot-qt/assets/30521429/c6f596cb-3497-43ee-a984-254a3c4c565c)

### In python , Can we implement custom effects by inheriting `EffectBase` and implementing the `GetFrame` function ourselves?

![image](https://github.com/OpenShot/openshot-qt/assets/30521429/5fb72d12-ff3a-45a3-814b-326f4f38b2c5)

**Comment by jonoomph** [comment]
@625781186 All of our C++ video and audio effects inherit from EffectBase, and if you implement just a few required methods, such as GetFrame, and set the metadata of the effect (title, description, etc...), it should work just fine. However, I doubt you can do this directly in Python, since not all classes (i.e. EffectBase) can be instantiated directly... but I've also never attempted that. The easiest method would be to follow our [development guide](https://github.com/OpenShot/openshot-qt/wiki/Become-a-Developer), to get everything compiling locally, and then just implement an effect in C++ by coping an existing one (such as Bars), compiling a new version of libopenshot, and that should work well. Good luck!

**Comment by 625781186** [comment]
Because my conditions only allow me to develop on window,
However, it is too difficult to compile libopenshot on window system.

**Comment by 625781186** [comment]
![image](https://github.com/OpenShot/openshot-qt/assets/30521429/37465ead-d9e9-4ff8-80df-162a0a85f898)

I tried this with success, 
but unfortunately `effec->GetFrame` not enter `python's` effect GetFrrame function
