### ISSUE TITLE
Application crashing on video export

### ISSUE THREAD

**Issue by RoKeR420** [OpenShot/openshot-qt#5511]
Every time I try to export my video the application crashes and  I have to restart the process. Sometimes it makes it to 20%, sometimes 60%, but it continues to fail and crash.

This is my Event log:

Faulting application name: openshot-qt.exe, version: 3.1.1.0, time stamp: 0x607466f6
Faulting module name: libx264-159.dll, version: 0.159.2991.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0000000000136b9c
Faulting process id: 0x32f4
Faulting application start time: 0x01daa0d49633d279
Faulting application path: C:\Program Files\OpenShot Video Editor\openshot-qt.exe
Faulting module path: C:\Program Files\OpenShot Video Editor\lib\libx264-159.dll
Report Id: 8899c904-edd9-4f00-813f-0ddfaa58f0f1
Faulting package full name: 
Faulting package-relative application ID: 

[DxDiag.txt](https://github.com/OpenShot/openshot-qt/files/15242127/DxDiag.txt)

**Comment by Colorjet3** [comment]
Hello @RoKeR420 Please try the following:
1.  Close OpenShot if running.
2.  Make a backup of c:\users\username\.openshot_qt folder.
3.  Delete c:\users\username\.openshot_qt folder.
4.  Go to openshot.org/download/#daily and download the latest DEV Daily Build.
5.  Install it.
6.  Restart your computer.
7.  Ensure you have plenty of free disk space.
8.  Ensure your Windows environment is healthy.
9.  Start OpenShot and open your project.
10. Export it.  If it fails, continue to step 11 otherwise skip the rest.
11. Restart Openshot.
12. Create a small project and Export to see if the export works.
13. Open your project and perform File | Save Project As... and save as test01.
14. Now you are in Test01.osp project.
15. Delete the right half of your clips on the track(s).
16. Export your project.
17. If it worked, then reopen the Test01 project (don't save it when asked).  Now, instead of deleting the entire right half of the clips on the track(s), delete the last 3rd.
18. Now export.

This method at some point will expose the offending clip causing OpenShot to crash.  Once you find it we can further debug or may be you can recreate that clip.
20.

**Comment by leodf1** [comment]
Aside from what Colorjet said above. Generally the export progress bar follows the timeline from left to right. So for an offending clip on the timeline, the progress will always crash at the same percentage location, with the percentage giving you an idea of where on the timeline the bad clip is.  For different crash positions it could be more than one bad clip on the TL, however with the crash not happening regularly at the same points, more likely a system issue. Unless you have been tinkering with the TL between exports.  (IMO of course)

Similarly to what Color said, I isolate an offending clip by deleting one half of the timeline at a time, exporting each time, working my way up to the bad clip until the crash returns... You do this on a copy of the project, naturally.

**Comment by RoKeR420** [comment]
I followed what you have suggested, but the problem still remains. In this case I am actually only using the software to shorten a longer video and change the quality. I am taking a 10 minute video, shortening it by literally slicing it in half, then exporting it. I downloaded DaVinci Resolve and it was able to complete it no problem. Plus it was way faster due to it using more of my available hardware resources. Not sure why OpenShot is giving me issues all of the sudden. I have used it to compile YouTube videos plenty in the past and it has always worked great. I've updated all my drivers as well and Windows updates are topped off. I will leave this open for a bit longer in case someone else has any ideas.

**Comment by Colorjet3** [comment]
Hello @RoKeR420 Please tell us the build # you are running (help | about openshot).   A screen should would be great.

Another thing you can try is to run your source video file through a converter like VLC, Handbrake, or ShutterEncoder, and convert to a .mp4 (even of the original is a .mp4), but obviously with a new name.  Now import this new .mp4 file into OpenShot and see if things are better.

**Comment by Colorjet3** [comment]
No response from OP.
