### ISSUE TITLE
C++ Runtime Crashes when opening project with files missing

### ISSUE THREAD

**Issue by finchamp** [OpenShot/openshot-qt#553]
Hello,
I made a video on V2.2 on a Windows 10 machine. When I try to open it on other computers, I get a "This application has requested the runtime to terminate in an unusual way." error dialog, after which Open Shot crashes to desktop.

I have copied the video files into the project folder on both computers. However, if I remove all the videos from the project, I can open it with no problems.

The other two computers I have tried are:
-Both OpenShot V2.2
-One Windows 8.1, and one Windows 10
-One AMD Athlon XII x64, and one brand new Intel i7

**Comment by finchamp** [comment]
It appears that I was missing one audio file. So my change request would be to add a notification if there are project files missing, rather than allowing the runtime to crash.

**Comment by DylanC** [comment]
@finchamp - Good idea thanks.

**Comment by wrookie11** [comment]
I am having a similar issue. And i'm fairly certain that it's due to the same issue which finchamp was experiencing. Although i'm having trouble understanding his troubleshoot. How do you change the request to a notification rather than allowing it to crash. I see that this thread is from a year ago, but if someone sees this post, please help explain how to work this troubleshoot. I was in the middle of a big video game project and i'm dying to get it finished. So if anyone sees this, please explain how to work that troubleshoot.
