### ISSUE TITLE
when i open openshot, the program immediately stops responding.

### ISSUE THREAD

**Issue by freeve4h** [OpenShot/openshot-qt#5564]
**Describe the bug**
when i open openshot, the program immediately stops responding.

**Steps to reproduce the behavior:**
1. Open OpenShot

**Expected behavior**
OpenShot opening normally

**System Details**
- OpenShot Version: 3.2.0-dev
- libopenshot Version:  0.3.3
- Platform: Windows-10-10.0.19041
- Processor: Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
- Machine: AMD64
- Python version: 3.8.9
- Qt5 version: 5.15.2
- PyQt5 version: 5.15.4
- Qt Detected Languages: ['en-US']
- LANG Environment Variable: 
- LOCALE Environment Variable: 
- Daily Build: Verified issue still exists in daily build: http://github.com/OpenShot/openshot-qt/releases/download/OpenShot-v3.2.0-dev-daily-12555-044bb224-23713d3a-x86_64.exe

**Log Files**
- [openshot-qt.log](https://s3.amazonaws.com/logs.openshot.org/pi98ahtrswth3c9maglvl3379vus0pdf/openshot-qt.zip) (4 KB)
- libopenshot.log: File too small or empty (not uploaded)

**Exception / Stacktrace**
```No stacktrace found in log files```

**Screenshots** (Optional)
If applicable, add screenshots to help explain your problem. You can include screenshots by
copy/pasting them on GitHub or dragging-and-dropping into the GitHub page. All images are public,
so please don't post screenshots containing personal information.

**Comment by drizztguen77** [comment]
This happens to me as well. I just installed a new fresh version of Windows 10. When I install OpenShot 3.1.1 it works fine. But if I install 3.2.0 it just sits and spins when I attempt to run it. I have to kill the program in order to stop it. I have tried uninstalling and reinstalling, rebooting, changing the order of python in my paths and everything. Nothing seems to work except installing 3.1.1.

![2024-07-03 10_22_53-Untitled Project  HD 720p 30 fps  - OpenShot Video Editor (Not Responding)](https://github.com/OpenShot/openshot-qt/assets/1878537/c193bc26-4bdb-4298-a912-738f555ffd95)

**Comment by Mint-Martini** [comment]
Happening to me aswell 
![image](https://github.com/OpenShot/openshot-qt/assets/26099314/d4e3d65c-247f-445b-97ad-a2d84c8c606e)

**Comment by Colorjet3** [comment]
This has been fixed in the latest DEV daily build.

1.  Go to openshot.org/download/#daily and download/install the latest dev daily build.
2.  Start OpenShot.

Please confirm either way.

**Comment by drizztguen77** [comment]
I just installed the daily and it is working fine. So your change seems to have fixed the problem.

**Comment by drizztguen77** [comment]
> Please confirm either way.

I just installed the daily and it is working fine. So your change seems to have fixed the problem.
