### ISSUE TITLE
What's with the massive amount of resources this thing requires.?

### ISSUE THREAD

**Issue by AnonymousRonin** [OpenShot/openshot-qt#5566]
I have a 13th gen intel i9 and an AMD RX7900XTX and this program is constatntly using so much resources that it wonn't let me do anything else.  I've seen this was an issue in the past but never could track down a resolution.  How do I put this thing on a diet?

**Comment by Colorjet3** [comment]
Hello @AnonymousRonin Please provide some more details so we can better understand the resources being used.

1.  What operating system/version are you running (Windows 10 Pro?  Ubuntu 22.04 lts? etc?)
2.  Which version of OpenShot are you running (help | About OpenShot)?
3.  Resource usage.  Is this CPU, GPU, or RAM related?  Please provide as much detail as possible.
a.  When you start OpenShot, how much resources is it using?
b.  When you create/open/edit a project, how much resources is it using?
4.  Have you made any changes in Edit | Preferences section?  If yes, what changes?

I highly recommend that you download the latest dev daily build that was recently released to fix some startup issues in Winodws environment (Not sure what you are running).

Go to openshot.org/download/#daily and get the latest dev daily build available.  Install it and see if it is any better.

OpenShot currently is not fine tuned for hardware acceleration.  This is a known issue, documented, and in the queue to be fixed in a future relase (no ETA).

**Comment by Colorjet3** [comment]
No Response from OP

**Comment by AnonymousRonin** [comment]
My apologies.  It's CPU resources but not continuous.  I guess it's more of a random occurrence where all of sudden it's just spinning up resources so much it either lags or freezes.  Lately it's been just shutting down randomly.  I started saving more often and it does allow recovery when I fire it back up but it's still rather annoying.  I'm using debian 12 bookworm.

**Comment by AnonymousRonin** [comment]
By the way, I'm using version 24.04.  Mainly because the newer versions have some sort of issue related to matching system theme.  I use xfce4, qt, gtk 3. I think it's relelated to qt5 or qt6.  I couldn't find any bugs to speak so I wondered if it may be a setting I'm unaware of.

**Comment by Colorjet3** [comment]
Hello @AnonymousRonin 
1.  When you say 24.04 I take it you mean Ubuntu 24.04, correct?
2.  What version of OpenShot are you running and how did you install it (PPA, Software Manager, or AppImage)?
3.  Is it possible that you can share one of your projects (.osp and all imported files as well, zipped in one file).  The lead developer thinks that there might be a memory leak issue in Linux environment and a sample project causing the issue would help him debug.
