### ISSUE TITLE
All clips imported into OpenShot have a distortion.

### ISSUE THREAD

**Issue by Jayden58** [OpenShot/openshot-qt#5585]
**Describe the bug:**
.MP4 audio (I have not tested other file types) has distorted audio. I tried with Nvidia recorded footage and a YouTube to .MP4 file.
I also reinstalled the application (deleted the program files and the user date) and it still happens. After I deleted the program, I started having windows audio problems. 
First, the audio did not work, I restarted, then no input or output devices were listed in sound settings (except VB audio virtual outputs), then I restarted again and it seems to have gone back to normal.

I commented on a closed issue that had the same problem but it seems like nobody noticed.

**Steps to reproduce the behavior:**
1. open OpenShot
2. Import a .MP4 file with audio
3. put it onto the timeline
4. press play
5. you should hear distorted audio.

**Expected behavior:**
I expected the audio to play normally as I have before

**System Details:**
- OpenShot 3.2.1 and a earlier version
- Windows 10 version 22H2

**Log Files:**

[openshot-qt.log](https://github.com/user-attachments/files/16442843/openshot-qt.log)
[libopenshot.log](https://github.com/user-attachments/files/16442851/libopenshot.log)

**Screenshots:** (Optional)
If applicable, add screenshots to help explain your problem. To include screenshots, copy/paste them here, drag the image(s) into this form, or click the link below this edit field to load images saved to your computer. All images are public, so please don't post screenshots containing personal information.

**Comment by Colorjet3** [comment]
Hello @Jayden58 

Please try this:
1.  Perform a v3.2.1 [clean installation](https://github.com/OpenShot/openshot-qt/wiki/Clean-Installation-of-OpenShot).
2.  Import your .mp4 and see if this resolves the issue.  If not, continue....
3.  Is your output device headphones or speakers?  If headphones, please disconnect, restart Windows.
4.  Start OpenShot, import your .mp4 and try again.
5.  If still having issues, then in Control Panel, check the Windows default Output device sample rate.  For your speakers, try 48000 then 44100.  Each time you change, you MUST restart OpenShot.
6.  If issue continues, in OpenShot go to Edit | Preferences | Preview tab and change the "Playback Audio Device".  Select "Windows Audio:  yourdevice" or "DirectSound:  yourdevice".  Each change requires restart of OpenShot.

There is a possibility that your .mp4 audio has issues that OpenShot can not handle.  Try running it through a converter like VLC, HnadBrake, or ShutterEncoder and convert it to .mp4 again with a different name.  Now import this file and see if it is any better.

**Comment by Jayden58** [comment]
1. I have done this previously but I have done it again according to the links instructions.
2.  The issue still persists. But now it is a singular sound that does not go away even when pausing unless you close the program
3. I checked in sound settings and it was my computer speakers. 
4. Now the original and new problems are happening simultaneously.
5. I could not find this in the control panel
6.  Switching it to windows audio made the constant noise notably louder and it seems like **switching it to DirectSound fixed the problem.** Thank you for your time.

**Comment by Jayden58** [comment]
Should I make a separate bug report about Windows Audio causing problems?

**Comment by Colorjet3** [comment]
Thank you @Jayden58 for all the information.  I am glad that Step 6 (switching to DirectSound fixed the problem).

You are more than welcome to submit a separate bug report for the lead developer to review.  However, since the DirecSound fixed the issue than it may not be an OpenShot issue but rather something unique with the sound card, drivers, etc.   If you feel it is a bug then yes, a separate bug report is best.

Regarding seeing you output audio configuration in Windows 10, please do this:
1.  Go to Control Panel.
2.  Click on Hardware and Sound
3.  In the Sound section click on "Manage audio devices".
4.  The Sound window will list all your devices and the one that is the default will have a green check box next to it.
5.  Click on the default device and click on Properties.
6.  In the next window click on the Advanced tab.
7.  Here you can find the sample rate of your Audio device and can change it if needed.
8.  If you make a change here then be sure to restart OpenShot so it can detect the new sample rate and match it.
