### ISSUE TITLE
Timeline Arrangement Of Numbered Film Clips

### ISSUE THREAD

**Issue by Madbiker1960** [OpenShot/openshot-qt#5602]
**Describe the bug:**

I have added three pictures to explain what I am talking about.

I have added 29 clips of film footage that are numbered in sequence as they were recorded.

I import the clips to OpenShot and the problems begin in the Projects Files area, where they lose their numerical order.

Instead of staying in sequential order:

1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29

They end up on the OpenShot project files area in this order: 

![Screenshot_1](https://github.com/user-attachments/assets/97bc3486-6a22-46fb-907d-06e471dcbc0c)
![Screenshot_2](https://github.com/user-attachments/assets/35a891db-97ec-4616-95f3-5240218813bf)
![Screenshot_3](https://github.com/user-attachments/assets/d94b38ae-fd1e-4af6-b391-b9cd696fd220)
1,10,11,12,13,14,15,16,17,18,19,2,20,21,22,23,24,25,26,27,28,29,3,4,5,6,7,8,9

**Expected behavior:**

When I added the clips to OpenShot I expected the clips to stay in sequential order not change to numerical order as they did.

Having to correct this is very time consuming and laborious.

Unfortunately renaming al of the clips is not an option.

Can this please be corrected, SOON I have a lot of footage to work on here.

**System Details:**
- OpenShot Version >     >     >3.2.1
- Operating System>     >      > Windows 11 Home 23H2
- Device name	TeeJay1960
Processor	AMD Ryzen 7 5700X 8-Core Processor                3.40 GHz
Installed RAM	64.0 GB
Device ID	
Product ID	00326-03100-00003-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
Edition	Windows 11 Home
Version	23H2
Installed on	‎29/‎07/‎2024
OS build	22635.4010
Experience	Windows Feature Experience Pack 1000.22700.1035.0

**Comment by Colorjet3** [comment]
This is not a bug.  OpenShot is not parsing the file name to find numbers.  Additionally, because they are in a file name, they are treated as text and not numbers.  This is pretty standard practice unless you are using some advanced appication like Excel, etc.  It merely following what the operating system does when you use the File manager of your operating system.

I am currently running Windows 11 Pro and created 5 files named 1.txt, 2.txt, 3.txt, 10.txt and 20.txt.  In File Explorer, this is what they look like:

<img width="371" alt="image" src="https://github.com/user-attachments/assets/1bbc16c2-cb84-4b1f-a9a4-45459608bb6b">

If I want them sorted propertly, then I need to rename 1.txt to 01.txt, and 2.txt to 02.txt, and 3.txt to 03.txt.  I just went ahead and created 3 more files (01.txt, 02.txt, & 3.txt) and this is what File Explorer shows:

Command prompt (Dir)
![image](https://github.com/user-attachments/assets/c061cda1-75ef-491e-bc83-1db086dccc86)

To further test this I created a few .jpg files to mimic what I created above so I can import them into OpenShot.

This is what the files look like in a command prompt when I perform Dir.

<img width="248" alt="image" src="https://github.com/user-attachments/assets/d08d8ff7-17b3-47c7-9883-98420796ff30">

This is what the files look like when I import them into OpenShot.  The order is exactly the same.

<img width="693" alt="image" src="https://github.com/user-attachments/assets/ff01ed70-3c70-40cb-9ec7-8952e709d543">


The bottom line is that you need to change your files that have a single digit number in them (1, 2, 3,...9) to (01, 02, 03,....09) and then your sort order will be fine.

Now, if you expect OpenShot to figure that out for you then you should submit an "Enhancement" request but honestly that will be crazy because now someone else might have the numbers at the beginning or in the middle, include dates, time stamps, etc., and this will just never accomodate all.

**Hint:**
If you are running the latest version (3.2.1) you can rename the files in OpeShot.
1.  Start OpenSHot.
2.  Open your project.
3.  In the "Project Files" Window, double click the name and reanme the ".....1.mov" to "....01.mov"  make sure you do not imbed or delete an existing space.
4. Do step 3 for "...2.mov", "...3.mov",....., "....9.mov".
5. As soon as you change the name(s) of the files the sort order changes.

My recommendation is to fix your naming outside of OpenShot and then import.

**Comment by Colorjet3** [comment]
No response from OP.
