### ISSUE TITLE
OpenShot crashes when same image inserted again has time expanded

### ISSUE THREAD

**Issue by James763** [OpenShot/openshot-qt#5612]
**Describe the bug:**
I am using OpenShot-v3.2.1-release-12654-044bb224-23713d3a. When I insert the same image as a background image and expand its time to fit the rest of the length of a movie for an album/movie sync project, OpenShot crashes. The project is in UHD 2160p 23.98fps. The movie is downscaled to 1920 width and moved to fit the empty part of the background image (which is actually 2 inserts of the same image because of the time limit on images).

**Steps to reproduce the behavior:**
1. Go to 'Project Files'
2. Click on 'Image'
3. Select and drag the image to the timeline after the first iteration
4. Resize the image
5. OpenShot crashes

**Expected behavior:**
I expected the image's time to expand properly when I scaled it with my cursor. It didn't and OpenShot crashed.

**System Details:**
- OpenShot Version [e.g. 2.4.3]: 3.2.1
- Operating System / Distro: Windows 11

**Log Files:**
[libopenshot.log](https://github.com/user-attachments/files/16923777/libopenshot.log)
[openshot-qt.log](https://github.com/user-attachments/files/16923778/openshot-qt.log)

**Exception / Stacktrace:**
N/A

**Screenshots:** (Optional)
N/A

**Comment by Colorjet3** [comment]
Hello @James763 In order to try and replicate your issue please provide the following:

1.  Exact steps of how you created your project.  For example:
a.  I start OpenShot
b.  I change the profile to something....
c.  I import my source files.
d. my source files are .mp4, .jpg, etc.....
e.  I drag the image file to Track 4,

you get the point by now...don't skip steps and be sure the order of things are accurate.

2.  If you can share your source file(s) that would be great as well.

By the way, a latest dev daily build was just released.  If you want to give that a try first and see if it resolves your issue then you don't have to provide that information.

1.  Go to openshot.org/download/#daily.
2.  Download the proper executable (.64 bit vs. .32bit)
3.  Install and try your project again.

**Comment by Colorjet3** [comment]
No response from OP.
