### ISSUE TITLE
Video Freezes mid playback

### ISSUE THREAD

**Issue by Wi18hn** [OpenShot/openshot-qt#5624]
Open Openshot - add the video as a new project. 

Add to track. 

Freezes mid playback. 

I have reinstalled, cleared cache, tried dailybuild etc. it still occurs

**Comment by Colorjet3** [comment]
1.  what operating system/version are you running?
2.  what version of OpenShot are you running?
3.  What type of a video file are you importing (.mp4? .mov? etc?)

Give this a try:
1.  run your video file through a converter like vlc, shutterencoder, or HandBarake and convert it to a .mp4 (even if the original is a .mp4).
2. Now import this new file in and see if that resolves it.

If the issue is resolved, please let us know how your original file was created (iphone, android, webcam, etc.) to give us an idea.  It will also help to provide the details of your video file (resolution, fps, etc.)

**Comment by Colorjet3** [comment]
No Response from OP.
