### ISSUE TITLE
60 FPS Video just doesn't work

### ISSUE THREAD

**Issue by TombyT** [OpenShot/openshot-qt#564]
PC Specs : 6600K, samsung evo 840 ssd, gtx 1060, 32 GB ram
OS : windows 10 x64 and Ubuntu 16.10 64?
Openshot Versions : 2.0-2.3?
What's the deal here? I can't even play a preview of a single video on either os using GoPro footage i've taken (clip is 5 minutes long 1080p 60fps mp4.)

The interface seems really nice but I've never been able to get it to work without crashing (often). I was in the beginning able to piece/crop together enough clips to make a 12 minute film while tolerating frequent instability, but in the end I could only ever end up exporting 6 minutes of it and the audio was horribly choppy, even ear piercing at times.

Again I've tried virtually every appimage available on both Ubuntu 16.10 and Windows 10 x64 and have coincidentally even thrown a complete OS reformat in between for good measure to no avail.  My computer is even new and has the same issues as my old alienware laptop. Too many bugs I don't even know where to start.

**Comment by croco3008** [comment]
Could you upload  example video somewhere? Dropbox link may be helpfull. There are some kind of video formats which does not work well. If developers do not have same kind of video, its hard to track a bug.

**Comment by AluminiumTech** [comment]
I can confirm that I have the same issue mentioned above.

I'm using 1080p 60fps for videos and, in each case without fail, no matter how long the video is, OpenShot struggles to process it. The CPU is being completely decimated while the video isn't being loaded from the storage drive. I could not tell you why this happens, only that it does happen.

Specs: i5-4570, Adata SP600 SSD + Seagate 1TB 7200rpm HDD.

I've recorded what happens when I attempt to load a 1080p60 project. 

https://youtu.be/OK69Hrq3gyM

**Comment by TombyT** [comment]
Hi, thanks for the reply. Attached is one of the shorter examples of the primary type of GoPro footage I've been trying to use but I don't have much of other formats to test out.
https://www.dropbox.com/s/daa7m67efpt99yj/GOPR0485.MP4?dl=0

**Comment by TombyT** [comment]
I am in the middle of rendering right now and so far so good. One thing I did notice is that the GoPro format is actually 59.94 fps as opposed to 60 fps. I don't know if this is
