### ISSUE TITLE
Can't crop videos

### ISSUE THREAD

**Issue by BluebellCW** [OpenShot/openshot-qt#575]
**System Details:**
* Operating System / Distro: Windows 10
* OpenShot Version: 2.3.1
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
I'm pretty new to OpenShot, and I ran into this issue pretty quickly.
I want to be able to crop the frame of the video, and when I searched for info on it, I was directed to [this article](http://www.openshotusers.com/help/1.3/en/ar01s15.html). However, when I right-clicked on the clip and clicked Properties, instead a Properties tab appeared next to the timeline, and it did not seem to have the same features. Is there any way to fix this? Or is there another way to crop videos?

**Comment by eliboni** [comment]
That article is for an old openshot version. To do what you need check clip section at [http://www.openshot.org/files/user-guide/]

**Comment by BluebellCW** [comment]
I've looked through the User Guide multiple times and couldn't find anything on cropping.

**Comment by dvd2000** [comment]
I think you should use the new "Transform Tool" to crop a clip, http://www.openshot.org/files/user-guide/clips.html#transform

**Comment by MikeIronFist** [comment]
This is a legit issue: OpenShot simply _**does not have a tool for cropping clips.**_

It's a little tough because all of the other compositing features available are pretty amazing and much more visually complex than a simple image/video crop. Maybe it's a much more difficult feature to implement on a technical level but either way, we don't have cropping in OpenShot.

Still, if you NEED a cropped clip, it's 100% possible to create one using OpenShot; it just takes more time.

As a workaround you can create a separate video project for the clip you want cropped, then export it at the dimensions you would like it cropped to.
![Export settings for cropping 720p video to 960x720]
(http://i.imgur.com/ytp1Qy9.png)
Here's the export settings I used to crop a 720p (1280x720) clip to 960x720. All I really did was leave everything at default and just change the dimensions.

For cropping to things that aren't centered, you can just move your clip using the transform tool to center the section of the frame you want to crop to. I know it's tedious but hey, it works.

In the future I hope a proper crop tool appears in OpenShot. Until then, this can get the job done, if maybe a little slowly.

**Comment by DylanC** [comment]
@BluebellCW - Good idea! Thanks.

**Comment by peanutbutterandcrackers** [comment]
The crop effect has recently been [added to the source code](https://github.com/OpenShot/openshot-qt/commit/b18a3815f0998ad2740030e89c55897067f73522) and is available in the [daily builds](https://github.com/OpenShot/openshot-qt/releases/tag/daily). It will be available in v2.4.2 (stable release), too. For now, you should probably try out the daily build to use it.

Hope this resolves this issue.

@DylanC - I think this issue can now be closed.

**Comment by dontWasteYourTime** [comment]
2018-Oct-13

Downloaded it. Wasted 10 minutes trying to find a way to crop; nothing.

Went to 'Help'. Searched for 'crop'; still nothing.

Googled and found this thread. Noted the names of the OpenShot developers to ensure I never waste my time on their products again.

**Comment by DylanC** [comment]
@dontWasteYourTime - If you have such high expectations for an Open Source project you should probably go buy a video editor.

**Comment by peanutbutterandcrackers** [comment]
@dontWasteYourTime 

1. Drag your clip into the timeline
2. Go to the effects panel and find the `crop` effect
3. Drag and drop the crop effect into your clip on the timeline
4. Right click on the `c` that is displayed on your clip on the timeline and click on `properties`
5. Change the bottom, top, left and top crop values as required. Make sure the play head is at 1st frame of the clip if the entire video is to be cropped.
6. Be confused with OpenShot's *everything-is-keyframed* attitude.
7. [Go through this guide](https://gist.github.com/peanutbutterandcrackers/f0f666243133e0ed25abbc12a4ba23d7) to thoroughly understand OpenShot's design and behaviours.

OpenShot is a [Free Software](https://en.wikipedia.org/wiki/Free_software) created by volunteer developers from around the world who are passionate about film-making and believe that everyone should have the access to the tools to express themselves with audio-visual means. And we work very hard to do our bit to help make OpenShot better in whatever little way we can. Nobody pays us a penny. This is all a labour of love. So please be mindful about that.

**Comment by dontWasteYourTime** [comment]
" If you have such high expectations for an Open Source project you should probably go buy a video editor."

Da Vinci has crop, you self-righteous fool.

"OpenShot is a Free Software created by volunteer developers from around the world who are passionate about film-making and believe that everyone should have the access to the tools to express themselves with audio-visual means."

You didn't give me access to that. You rather wasted my time, left me a few hours closer to death with nothing to show for it. If you wanted to help people you document your software better. Freeze the features until the documentation-bug and others bugs are fixed.

"And we work very hard to do our bit to help make OpenShot better in whatever little way we can. Nobody pays us a penny. This is all a labour of love. So please be mindful about that."

Maybe you do it to pad your resume or feed your ego, if you want to help end-users, quit releasing time-wasting software.

**Comment by peanutbutterandcrackers** [comment]
1. Da Vinci is made by was made by [Da Vinci Systems](https://en.wikipedia.org/wiki/Da_Vinci_Systems) and is currently owned by [Blackmagic Design](https://en.wikipedia.org/wiki/Blackmagic_Design) - both huge corporations - with hundreds of paid full-time developers, documentation writers, testers, etc. behind it.
2. Just because you were unable to find a simple `crop` effect under the effects tab, which was sitting right there doesn't mean that we deprived you of the the tools, sir.
3. Yes, I agree. We haven't been that well at documenting the new features. But what we need is more help from the community. Not what you are giving us right now. There is, fundamentally, no difference between you and us. You could be helping out with the project just as well as us.
4. By your own logic, why would we put on our resume's something that is such a "waste of time" as OpenShot? Where I am from, none of the time I have put into OpenShot is going to be appreciated, as a matter of fact.
5. Ego? I am afraid, sir, that I am the one humbling myself and speaking politely with you here. Also, I have no IT job to speak of. I am just a recent graduate (and my field is not computers, but humanities and arts) who is on a break and is helping out a project that I believe in, in my spare time.

There is this man, Jonathan Thomas. He wrote a simple yet powerful video editor called OpenShot and decided to share it with the world. This other man going by the name DylanC decided to help him out with his efforts. And another few men dropped by, with a few patches to make OpenShot better. And then I found this wonderful software and saw how easy and powerful it was, and for free, and decided to do my bit to help make it better, so that posterity might have a good, stable and powerful video editor with them - to save their memories, to jump start their film-making career, sir. Not to get a 9 to 5 job at some low-paying office.

I see that you will not be using OpenShot. But if you ever plan on coming back around, [here is a little gift for you](https://gist.github.com/peanutbutterandcrackers/f0f666243133e0ed25abbc12a4ba23d7).

Funny, I remember [this comic](https://www.xkcd.com/743/) now, all of a sudden. :)

**Comment by MikeIronFist** [comment]
> " If you have such high expectations for an Open Source project you should probably go buy a video editor."
> 
> Da Vinci has crop, you self-righteous fool.
> 
> "OpenShot is a Free Software created by volunteer developers from around the world who are passionate about film-making and believe that everyone should have the access to the tools to express themselves with audio-visual means."
> 
> You didn't give me access to that. You rather wasted my time, left me a few hours closer to death with nothing to show for it. If you wanted to help people you document your software better. Freeze the features until the documentation-bug and others bugs are fixed.
> 
> "And we work very hard to do our bit to help make OpenShot better in whatever little way we can. Nobody pays us a penny. This is all a labour of love. So please be mindful about that."
> 
> Maybe you do it to pad your resume or feed your ego, if you want to help end-users, quit releasing time-wasting software.

Jeez this some really entitled garbage you're putting out here, buddy. OpenShot is free and made by some people in their spare time. You talk about never using "the OpenShot team's products" again. LOL. OpenShot is not a "product," it doesn't have a dev team. It's a free software project. There is no OpenShot company. You didn't pay any money for it. Stop acting like anyone owes you anything. You are not a customer.

I'm going to guess because you made a GitHub account just to complain that you don't know how open source/free software works. And because you're throwing a huge tantrum over it, I'm not really all that keen on explaining it to you. Let me just say this: no one cares how mad you are about this. OpenShot will continue to exist whether or not you have fits over "wasted time." It's your fault you wasted your time. Grow up.

**Comment by dontWasteYourTime** [comment]
> Jeez this is some really entitled garbage you're putting out here, buddy. OpenShot is free and made by some people in their spare time. You talk about never using "the OpenShot team's products" again. LOL. OpenShot is not a "product," it doesn't have a dev team. It's a free software project. There is no OpenShot company. You didn't pay any money for it. Stop acting like anyone owes you anything. You are not a customer.

You're the one acting entitled. I noted the names of the OpenShot developers to ensure I never waste my time on their products again. You can't cope with that, because of your entitlement complex. Cry more that I'm not tooting your horn or thanking you, because your software is bad.

> I'm going to guess because you made a GitHub account just to complain that you don't know how open source/free software works.

I've been using Emacs for development since the 1990's (for Intel and Microsoft among others). Thirty years, still no complaints, not a single one. You're being autistic about the facts, making up false facts in your mind instead of facing reality.

**Comment by dontWasteYourTime** [comment]
> 1. Da Vinci was made by was made by [Da Vinci Systems](https://en.wikipedia.org/wiki/Da_Vinci_Systems) and is currently owned by [Blackmagic Design](https://en.wikipedia.org/wiki/Blackmagic_Design) - both huge corporations - with hundreds of paid full-time developers, documentation writers, testers, etc. behind it.

It works better for end-users. Remember the speech earlier in this thread about how you do it all for the users? That was a lie. Da Vinci is better for end-users. If you cared about end-users, you would tell them to use Da Vinci.

"Just because you were unable to find a simple crop effect under the effects tab, which was sitting right there doesn't mean that we deprived you of the the tools, sir."

I told you, I searched the online docs, and the word 'crop' is not in them. You could have fixed it by now instead acting stupid.

**Comment by DylanC** [comment]
@dontWasteYourTime - Pretty amazing a developer like you joined GitHub "5 days ago" and has zero contributions to anything at all. You love Open Source yet give nothing back and yet don't understand it either?

> told you, I searched the online docs, and the word 'crop' is not in them. You could have fixed it by now instead acting stupid.

This goes for you too, you could have done this but again you don't seem to understand what an Open Source project means or probably have no clue how to do a pull request.

You seem like nothing more than an angry kid who wants a refund on a free "product". Go use Da Vinci and be happy.
