### ISSUE TITLE
OpenShot crashes when exporting video: Launch.exe has stopped working

### ISSUE THREAD

**Issue by hallic7** [OpenShot/openshot-qt#622]
**System Details:**
* Operating System / Distro: Windows 10 Pro / OS Build: 15063.250
* OpenShot Version: 2.3.1
* Message from Event Viewer:
Faulting application name: launch.exe, version: 0.0.0.0, time stamp: 0x57a98a3e
Faulting module name: libopenshot.dll, version: 0.0.0.0, time stamp: 0x58dd7c12

**Issue Description and steps to reproduce:**
When exporting a video project I always get the error: Launch.exe has stopped working. 
This closes the program. 
Settings I use to export:
- Target: MP4(h.264)
- Video Profile: HD 1080p 30 fps (1920x1080)
- Quality: High
I have changed some of these settings but it always crashes. 
The projects consists of 15 jpg images and a mp4 video which I divided into 2 segments with the Razor Tool.

**Comment by ADTClone** [comment]
Same bug occurred for myself. I have previously exported similar length videos, this video is about 1 hour long, but is a very simple project(two splits and fade in/out).

**System Details: **

- Operating System / Distro: Windows 10 Home / OS Build: 15063.138
- OpenShot Version: 2.3.1
- Message from Event Viewer: Similar to above, will have to confirm(have replicated the error with this project twice)

**Export settings:**

- Target: MP4(h.264)
- Video Profile: HD 1080p 29.97 fps (1920x1080)
- Quality: High

**Comment by ADTClone** [comment]
Here are the last few lines of the debug log before the error occurred and the application crashed:

> FFmpegReader::CheckMissingFrame (requested_frame=111186.0000, has_missing_frames=1.0000, missing_video_frames.size()=30.0000, checked_count=33708.0000)
FFmpegReader::CheckMissingFrame (requested_frame=124357.0000, has_missing_frames=1.0000, missing_video_frames.size()=30.0000, checked_count=14.0000)
FFmpegReader::CheckWorkingFrames (requested_frame=111186.0000, frame_number=124357.0000, is_video_ready=0.0000, is_audio_ready=1.0000, checked_count=14.0000, checked_frames.size()=38248.0000)
FFmpegReader::ReadStream (GetNextPacket) (requested_frame=111186.0000, processing_video_frames.size()=4.0000, processing_audio_frames.size()=0.0000, minimum_packets=8.0000, packets_processed=33792.0000)
FFmpegReader::ProcessVideoPacket (Before) (requested_frame=111186.0000, current_frame=124361.0000)
FFmpegReader::CheckMissingFrame (requested_frame=111186.0000, has_missing_frames=1.0000, missing_video_frames.size()=30.0000, checked_count=33709.0000)
FFmpegReader::CheckMissingFrame (requested_frame=124357.0000, has_missing_frames=1.0000, missing_video_frames.size()=30.0000, checked_count=15.0000)
FFmpegReader::CheckWorkingFrames (requested_frame=111186.0000, frame_number=124357.0000, is_video_ready=0.0000, is_audio_ready=1.0000, checked_count=15.0000, checked_frames.size()=38248.0000)
FFmpegReader::ReadStream (GetNextPacket) (requested_frame=111186.0000, processing_video_frames.size()=5.0000, processing_audio_frames.size()=0.0000, minimum_packets=8.0000, packets_processed=33793.0000)
FFmpegReader::ProcessVideoPacket (Before) (requested_frame=111186.0000, current_frame=124362.0000)
FFmpegReader::CheckMissingFrame (requested_frame=111186.0000, has_missing_frames=1.0000, missing_video_frames.size()=30.0000, checked_count=33710.0000)
FFmpegReader::CheckMissingFrame (requested_frame=124357.0000, has_missing_frames=1.0000, missing_video_frames.size()=30.0000, checked_count=16.0000)
FFmpegReader::CheckWorkingFrames (requested_frame=111186.0000, frame_number=124357.0000, is_video_ready=0.0000, is_audio_ready=1.0000, checked_count=16.0000, checked_frames.size()=38248.0000)
FFmpegReader::ReadStream (GetNextPacket) (requested_frame=111186.0000, processing_video_frames.size()=6.0000, processing_audio_frames.size()=0.0000, minimum_packets=8.0000, packets_processed=33794.0000)
FFmpegReader::ProcessVideoPacket (Before) (requested_frame=111186.0000, current_frame=124363.0000)
FFmpegReader::CheckMissingFrame (requested_frame=111186.0000, has_missing_frames=1.0000, missing_video_frames.size()=30.0000, checked_count=33711.0000)
FFmpegReader::CheckMissingFrame (requested_frame=124357.0000, has_missing_frames=1.0000, missing_video_frames.size()=30.0000, checked_count=17.0000)
FFmpegReader::CheckWorkingFrames (requested_frame=111186.0000, frame_number=124357.0000, is_video_ready=0.0000, is_audio_ready=1.0000, checked_count=17.0000, checked_frames.size()=38248.0000)
FFmpegReader::ReadStream (GetNextPacket) (requested_frame=111186.0000, processing_video_frames.size()=7.0000, processing_audio_frames.size()=0.0000, minimum_packets=8.0000, packets_processed=33795.0000)
FFmpegReader::ProcessVideoPacket (After) (requested_frame=111186.0000, current_frame=124358.0000, f->number=124358.0000)
FFmpegReader::ProcessVideoPacket (After) (requested_frame=111186.0000, current_frame=124357.0000, f->number=124357.0000)
FFmpegReader::ProcessVideoPacket (After) (requested_frame=111186.0000, current_frame=124359.0000, f->number=124359.0000)
FFmpegReader::ProcessVideoPacket (After) (requested_frame=111186.0000, current_frame=124360.0000, f->number=124360.0000)
FFmpegReader::ProcessVideoPacket (After) (requested_frame=111186.0000, current_frame=124361.0000, f->number=124361.0000)
FFmpegReader::ProcessVideoPacket (After) (requested_frame=111186.0000, current_frame=124362.0000, f->number=124362.0000)
FFmpegReader::ProcessVideoPacket (After) (requested_frame=111186.0000, current_frame=124363.0000, f->number=124363.0000)
FFmpegReader::ProcessVideoPacket (Before) (requested_frame=111186.0000, current_frame=124364.0000)
FFmpegReader::CheckMissingFrame (requested_frame=111186.0000, has_missing_frames=1.0000, missing_video_frames.size()=30.0000, checked_count=33712.0000)
FFmpegReader::CheckMissingFrame (requested_frame=124357.0000, has_missing_frames=1.0000, missing_video_frames.size()=30.0000, checked_count=18.0000)
FFmpegReader::CheckWorkingFrames (requested_frame=111186.0000, frame_number=124357.0000, is_video_ready=1.0000, is_audio_ready=1.0000, checked_count=18.0000, checked_frames.size()=38248.0000)
FFmpegReader::CheckWorkingFrames (mark frame as final) (requested_frame=111186.0000, f->number=124357.0000, is_seek_trash=0.0000, Working Cache Count=7.0000, Final Cache Count=20.0000)
FFmpegReader::CheckMissingFrame (requested_frame=124358.0000, has_missing_frames=1.0000, missing_video_frames.size()=30.0000, checked_count=1.0000)
FFmpegReader::CheckWorkingFrames (requested_frame=111186.0000, frame_number=124358.0000, is_video_ready=1.0000, is_audio_ready=1.0000, checked_count=1.0000, checked_frames.size()=38248.0000)
FFmpegReader::CheckWorkingFrames (mark frame as final) (requested_frame=111186.0000, f->number=124358.0000, is_seek_trash=0.0000, Working Cache Count=6.0000, Final Cache Count=20.0000)
FFmpegReader::CheckMissingFrame (requested_frame=124359.0000, has_missing_frames=1.0000, missing_video_frames.size()=30.0000, checked_count=1.0000)
FFmpegReader::CheckWorkingFrames (requested_frame=111186.0000, frame_number=124359.0000, is_video_ready=1.0000, is_audio_ready=1.0000, checked_count=1.0000, checked_frames.size()=38248.0000)
FFmpegReader::CheckWorkingFrames (mark frame as final) (requested_frame=111186.0000, f->number=124359.0000, is_seek_trash=0.0000, Working Cache Count=5.0000, Final Cache Count=20.0000)
FFmpegReader::CheckMissingFrame (requested_frame=124360.0000, has_missing_frames=1.0000, missing_video_frames.size()=30.0000, checked_count=1.0000)
FFmpegReader::CheckWorkingFrames (requested_frame=111186.0000, frame_number=124360.0000, is_video_ready=1.0000, is_audio_ready=1.0000, checked_count=1.0000, checked_frames.size()=38248.0000)
FFmpegReader::CheckWorkingFrames (mark frame as final) (requested_frame=111186.0000, f->number=124360.0000, is_seek_trash=0.0000, Working Cache Count=4.0000, Final Cache Count=20.0000)
FFmpegReader::ProcessVideoPacket (After) (requested_frame=111186.0000, current_frame=124364.0000, f->number=124364.0000)

**Comment by THAVARD46** [comment]
Same bug happened to me when I was trying to slow videos down.
Operating System / Distro: Windows 10 Home / OS Build: 10.0.14393
OpenShot Version: 2.3.1
Message from Event Viewer:
Faulting application name: launch.exe, version: 0.0.0.0, time stamp: 0x57a98a3e
Faulting module name: ntdll.dll, version: 10.0.15063.0, time stamp: 0xb79b6ddb
Exception code: 0xc0000374
Fault offset: 0x00000000000f775f
Faulting process ID: 0x14a8
Faulting application start time: 0x01d2c73477c14268
Faulting application path: C:\Program Files\OpenShot Video Editor\launch.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report ID: d476d97c-a166-4e3c-bdc9-e53205e397f9
Faulting package full name:
Faulting package-relative application ID:
Fault bucket 120731157860, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0
Problem signature:
P1: launch.exe
P2: 0.0.0.0
P3: 57a98a3e
P4: StackHash_ab40
P5: 10.0.15063.0
P6: b79b6ddb
P7: c0000374
P8: PCH_E8_FROM_ntdll+0x00000000000A5F04
P9:
P10:
Export settings:
Target: MP4(h.264)
Video Profile: HD 1080p 29.97 fps (1920x1080)
Quality: High
EDIT: Turned out the two previous crashes actually had slightly different errors. The first crash had the same error as the initial bug report.
Coincidently at the same timestamp, which is very interesting. I'm guessing that is in microseconds, which makes it ~24 minutes in, which I think lines up with the amount of time before it crashed. Only a guess there. Weird we all had the same timestamp though.
Faulting application name: launch.exe, version: 0.0.0.0, time stamp: 0x57a98a3e
Faulting module name: libopenshot.dll, version: 0.0.0.0, time stamp: 0x58dd7c12
Exception code: 0xc0000005
Fault offset: 0x000000000005016c
Faulting process ID: 0x1240
Faulting application start time: 0x01d2c721ded36237
Faulting application path: C:\Program Files\OpenShot Video Editor\launch.exe
Faulting module path: C:\Program Files\OpenShot Video Editor\libopenshot.dll
Report ID: ec701691-b5dc-433e-9e0d-01e9ed618a23
Faulting package full name:
Faulting package-relative application ID:

**Comment by DylanC** [comment]
@hallic7 - Does this happen in the v2.4 daily build?
