### ISSUE TITLE
WINDOWS: Where is the cutter to cut the video files in the project?

### ISSUE THREAD

**Issue by telelauro** [OpenShot/openshot-qt#70]
I've seen through the right mouse button but there is no icon, like in ubuntu version?

**Comment by jonoomph** [comment]
In OpenShot 2.x, you move the playhead line over the clip where you want to "slice", and right click. You can keep the left side, keep the right side, or keep both sides. More powerful that the old icon, since you get a preview of the frame as you move the playhead line, and can position it with frame accuracy. =)
