### ISSUE TITLE
Enhancement: Changing Property Values could be more intuitive

### ISSUE THREAD

**Issue by openpianist** [OpenShot/openshot-qt#725]
**System Details:** 
* Operating System / Distro: ? Ubuntu 17.04
* OpenShot Version: ?  2.3.4
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
The changing of the Value field of the Properties table could be more intuitive.
For first time users it is quite hard to figure out how to change predefined values like the Gravity Field / Scale field etc

(current how to: Just slide on the value field left - right..)

A "fly over help" explaining what to do, could already be helfpul

**Comment by N3WWN** [comment]
Not sure if this is stated anywhere in the docs, I never saw mention of it, but it took me a long time to figure out to right-click -> "remove keyframe" then double-click -> enter value to change the value of properties like location over an entire clip.

As a related ask, the ability to have pre-defined, custom properties that can be applied to a clip easily would be great!  I do a lot of picture-in-picture with a background video, a foreground video and border images that I change Gravity, Location X, Location Y, Scale, Scale X, Scale Y, and volume for every clip.  Presets that had a property mask so that only those properties that should change were applied to the destination clip would be awesome!

**Comment by openpianist** [comment]
> Not sure if this is stated anywhere in the docs, I never saw mention of it, but it took me a long time to figure out to right-click -> "remove keyframe" 

Wow, I have not figured out this feature... This really helps me.. I was wishing for something to be implemented, and it is already there.
Thanks N3WWN for highlighting this.

**Comment by DylanC** [comment]
@openpianist We should get this into the docs I think.
