### ISSUE TITLE
Feature Request: enhance export of sequences

### ISSUE THREAD

**Issue by openpianist** [OpenShot/openshot-qt#730]
**System Details:**
* Operating System / Distro: ? Ubuntu 17.04
* OpenShot Version: ? 2.3.4

Currently it is a kind of a guessing game to export a certain sequence of a video. (certain time frame)
It can be done under: File / Export Video / Advanced Tab / Advanced Options : Start Frame, End Frame
As only the min sec in a on the time line are shown, the big guessing game would be:
What is wanted the start frame? end frame?

possible solutions.
a) show the current frame on the timeline time head
b) show the current frame in the video preview window
c) show current frame under properties
d) show in the export dialog min, sec values in addition to the start frame / end frame values.

- O.

**Comment by milahti** [comment]
As a very new user for OpenShot I've been now trying to work with the export window and here are some comments/findings:

- For a newcomer it's difficult to find instructions related to how this advanced exporting with start+end works and what should be the input. I tested with trial & error and finally found this topic.

- As a workaround I first used to look at the properties view for a video and tried to do "fps x start" and "duration x fps" calculations to come up with the correct values. However, despite my OpenShot window title shows [HD 720p 30 fps] (default in my profile) and the properties of the source video says 15 fps, my trial and error analysis found that the correct fps for export calculation is 25 (in this case?)

- Lastly I found that the possible solution b from the description 

> b) show the current frame in the video preview window

 is already working. This can be enabled from the properties of the clip and this one helps if it's visible but the problem is that it's impossible to see this white text on white(ish) background and that's why I didn't even first realize that this functionality is working.
![image](https://user-images.githubusercontent.com/6698398/64856694-4c16a100-d62b-11e9-8ed0-aa15edfd1959.png)

Then the 2nd part of my video was from a full screen PPT presentation which leaves black vertical bars on the edges so form here I spotted that this is in fact working
![image](https://user-images.githubusercontent.com/6698398/64856821-926c0000-d62b-11e9-9bf7-602b4ed0b8ca.png)

However, even thought I can now see the frame number it seems that this frame numbering is following fps 30 and it's then not directly useful for those fields in advanced exporting.
