### ISSUE TITLE
Crash on Windows 10 64-bit on starting video export

### ISSUE THREAD

**Issue by manastalukdar** [OpenShot/openshot-qt#735]
**System Details:**
* Operating System / Distro:
```
Operating System
    Windows 10 Enterprise 64-bit [Version 10.0.15063]
CPU
    Intel Xeon E5 2630 @ 2.30GHz	44 °C
    Sandy Bridge-EP/EX 32nm Technology
    Intel Xeon E5 2630 @ 2.30GHz	50 °C
    Sandy Bridge-EP/EX 32nm Technology
RAM
    32.0GB Dual-Channel DDR3 @ 654MHz (9-9-9-24)
Motherboard
    Dell Inc. 082WXT (CPU 1)
Graphics
    ASUS PB287Q (2560x1440@60Hz)
    DELL U2417H (1920x1080@60Hz)
    DELL U2417H (1920x1080@60Hz)
    1024MB ATI AMD FirePro V4900 (FireGL V) Graphics Adapter (Dell)	60 °C
Storage
    475GB DELL PERC H310 SCSI Disk Device (RAID)
    1862GB DELL PERC H310 SCSI Disk Device (RAID)
    931GB TOSHIBA External USB 3.0 USB Device (USB (SATA))	27 °C
Audio
    Realtek High Definition Audio
```        
* OpenShot Version: 2.3.4
* _Please attach log files if crash_
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/1079185/openshot-qt.log.txt)

**Issue Description and steps to reproduce:**
On starting video export, Openshot crashes after a few seconds.
From Windows Application logs:
```
Fault bucket 129479549855, type 5
Event Name: RADAR_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: launch.exe
P2: 0.0.0.0
P3: 10.0.15063.2.0.0
P4: 19
P5: 10
P6: 9
P7: 
P8: 
P9: 
P10: 
```

**Comment by DylanC** [comment]
@manastalukdar - Was this with mp3 audio?

**Comment by manastalukdar** [comment]
Yes.

**Comment by DylanC** [comment]
@manastalukdar - I would suggest the daily build of v2.4. Its better for audio.

**Comment by manastalukdar** [comment]
No luck. Same crash happens.

**Comment by DylanC** [comment]
@manastalukdar - Can you try the very latest daily build and provide the log please?

**Comment by manastalukdar** [comment]
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/1476002/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/1476003/openshot-qt.log)

**Comment by DylanC** [comment]
@manastalukdar - Thanks

**Comment by soccerguy243** [comment]
Windows 10 (Version as of 19 nov 2017)
Openshot 2.4.1
Logs:
[libopenshot.log](https://github.com/OpenShot/openshot-qt/files/1486417/libopenshot.log)
[openshot-qt.log](https://github.com/OpenShot/openshot-qt/files/1486418/openshot-qt.log)
[openshot-qt.log.1.log](https://github.com/OpenShot/openshot-qt/files/1486422/openshot-qt.log.1.log)

My openShot 2.4.1 crashes during export as well due to launch.exe.  The error would open, I'd have to close the program, then my screens go black.  Sometimes it would recover to a single monitor with the lowest resolution.   I have an .mp3 file in my timeline.  I also had been saving over the previous export (that also crashed).  However, exporting to a new file name still resulted in launch.exe crashing.

I had also gotten a memory error (for the 1st time) but I was unable to capture a screenshot as I had to restart to get my displays back.

OpenShot is completely unusable for me.  I'm glad I had only spent an hour making a video before trying to export.

PS. this is my first github post hopefully I'm not being rude.

**Comment by DylanC** [comment]
@manastalukdar - Try to delete your preferences folder and start again.

**Comment by DylanC** [comment]
@soccerguy243 - Its no problem you are fine. Thanks for the logs.

**Comment by DylanC** [comment]
@manastalukdar - Try v2.4.3 and let us know if you still have a problem.

**Comment by manastalukdar** [comment]
@DylanC Crash issue does not occur any more with v2.4.3. Thanks.

**Comment by DylanC** [comment]
@manastalukdar - Great news, thanks! 👍
