### ISSUE TITLE
Missing 'Quit' menu on OS X

### ISSUE THREAD

**Issue by msgeek703** [OpenShot/openshot-qt#74]
Open Shot opened up just fine. There is, however, no menu option to gracefully quit Open Shot in the Mac version. That seems like a real oversight, no? Please fix, thanks.

**Comment by jonoomph** [comment]
This is funny actually. With PyQt5 (the UI framework I'm using), it moves some menu options around on OS X, to make the application feel more native. It moves the 'About OpenShot', 'Preferences', and 'Quit' menus around. However, for a reason I can't explain, it hides the Quit option in English. If you switch your language to a non-English language, the Quit menu will appear in the correct place. So....

If anyone has experience with this bug, please let me know. PyQt5 clearly detects the 'Quit' menu, because it removes it from the 'File' menu... it just doesn't add it back to the correct place. Very strange.

**Comment by msgeek703** [comment]
Thanks for the update.
M

**Comment by jonoomph** [comment]
I've done some more testing on this issue. The quit menu exists in some languages, such as "French" and "Japanese". The menu is missing in "English" and "Spanish" and many other languages. 

Even if I remove the actionQuit object from the UI file, the quit menu is added back automatically in the languages I mentioned above, and still missing in "English", "Spanish", and others.

So, I'm really not sure "what" is triggering the Quit menu to be hidden for some languages, and visible in others. I've upgraded Qt5 to the latest version, upgraded PyQt5, and still no change in this behavior.

The only trick I haven't tried, is starting to remove large chunks of code, and see if I can strip the main application window down to nothing, and isolate at what point does it start working again (I'm assuming something is breaking it in my code).

**Comment by jonoomph** [comment]
Getting closer! I've stripped just about everything out of the Main Window class, and the Quit option is always visible now. It can't hide much longer.

**Comment by msgeek703** [comment]
Thank you for all this trouble, Jon.
M

**Comment by jonoomph** [comment]
Dropping the mic

**Comment by msgeek703** [comment]
YAY!!!

M

On Wed, Mar 16, 2016 at 10:40 PM, Jonathan Thomas <notifications@github.com>
wrote:

> Dropping the mic
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenShot/openshot-qt/issues/74#issuecomment-197716142>
>



-- 
Michelle Klein-Hass: "That's *Ms.* Geek to you!" - Video - New Media - Geek
For Hire
*Ms. Geek Media* -- Box 2273, Van Nuys, CA, 91404-2273 -- 818-894-0226
http://msgeekmedia.wordpress.com/
