### ISSUE TITLE
Feature request: Export lossless

### ISSUE THREAD

**Issue by f2065** [OpenShot/openshot-qt#750]
**System Details:**
* Operating System / Distro: Windows 8.1 x64
* OpenShot Version: 2.3.4-dev1

Please make the video export modes with lossless-compression.
For example, in codec h264-lossless (or Lagarith, Huffyuv, uncomressed-AVI).

I watched the preset files (C:\Program Files\OpenShot Video Editor\presets\format_mp4_x264.xml), but I could not specify lossless codecs in them…

**Comment by fredgolightly** [comment]
Any info / update on this?

**Comment by gary9872** [comment]
This would be a great addition.

**Comment by DylanC** [comment]
@fredgolightly @gary9872 No update yet guys but I can ask the dev team directly for a quick answer on this.

**Comment by fredgolightly** [comment]
Would be gerat if this could be done :)

**Comment by N3WWN** [comment]
While not a complete solution, a work around may be to export the project to a series of images:
`Export Video` -> `Advanced` -> `Advanced Options` -> `Export To:` -> `Image Sequence`

These images could then be combined using ffmpeg and whatever lossless codec is required.

If the audio needs to be created by OpenShot, also, another export of `Audio Only` instead of `Image Sequence` could be used to generate the audio for ffmpeg to add to the lossless encoded video.
