### ISSUE TITLE
Title Font can't be changed

### ISSUE THREAD

**Issue by vowls** [OpenShot/openshot-qt#793]
* Operating System:  Linux Mint Serena
* OpenShot Version: 2.3.4
Hi, 
Forgive my ignorance-I am new to Linux and OpenShot.  When I try to create a standard title I can't change the font from Ubuntu.  Regardless of what font I choose or how I size it, it goes right back to the Ubuntu selection after clicking "OK".  If I select Use Advanced Editor it displays "Please install  to use this function."  I have Inkscape installed, but I don't know how to make it work with OpenShot.  When I try the animated title instead, it is so incredibly slow I can't tell if it's working.  Any help is much appreciated-thanks!

**Comment by PASTJL** [comment]
In the configuration menu, you must set the pathes of Inskape and blender like /usr/bin/inskape if inskape is under /usr/bin

**Comment by BluePointOyster** [comment]
I'm having the same issue. I do not have Inkscape installed, so my question is, do you have to install it in order to change the font size?

**Comment by DylanC** [comment]
Question has been answered by pastjl.

**Comment by BluePointOyster** [comment]
So the answer to "Do you have to install Inkscape in order to change the font size" is "In the configuration menu, you must set the paths of Inkscape, etc.". I guess I'll take that as a "yes".

But I would suggest that this is a flaw in the design. Why give the user controls to change the font and size, when even after configuring the Inkscape path, you still need to launch it via "advanced" in order for it to work?
