### ISSUE TITLE
Clipping and repositioning clip out of sync with export/save

### ISSUE THREAD

**Issue by thomasgwatson** [OpenShot/openshot-qt#807]
**System Details:**
* Operating System / Distro: Mac OS 10.12.5 Sierra 
* OpenShot Version: 2.3.4
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

Essential operation with clipping and moving clip out of sync between preview and exported/saved outcome.

Steps:
-I import a clip (maybe 4 minutes long)
-I clip off both ends, down to about a minue
-I move clip along track bar to 0'00
-I make some property changes to the clip, scale and x/y offset, to digitally zoom into parts of the clip

Preview looks good.

However. If I export, I know have a different segment of the original clip than before. Additionally, if I save the project, close the program and reload, the project is now at this same point in the original clip, that does not correspond to the preview.

I have now followed this process twice and each time it has reproduced the bug.

Halp

**Comment by DavidButterfield** [comment]
This is possibly a different problem, but I suspect it is the same.  It is possible you are not cutting where you think you are.  Maybe you can check other symptoms I mention about the time scale to see if yours are similar.

**Openshot 2.4.0 Timeline calibration sometimes off by a factor of 1.25**

I have a ~48-second video clip (full ffmpeg clip info at end):    
- Duration: 00:00:48.77    
- h264 (High), yuv420p, 640x480 [SAR 1:1 DAR 4:3], 29.97 fps, 29.97 tbr, 1k tbn, 59.94 tbc    
- Metadata: DURATION: 00:00:48.651000000

Playing the clip using VLC media player:    
- VLC plays correctly, taking about 48 seconds of wall-clock time, as expected.
- VLC lists the "Media Information" Metadata Duration as 00:00:48.765.
- VLC statistics indicate 1458 blocks Decoded and 1431 frames Displayed.
- [ 1431 / 29.97 = 47.75    and    1458 / 29.97 = 48.65 ]

When I import the clip into Openshot 2.4.0 and inspect File Properties:    
- Details -> Frame Rate appears as 30000/1001 (29.97 fps), non-interlaced    
- Video Format mkv, Video Codec h264, Bit Rate / Quality: 0    
- Frames 1 - 1439	    [ 1439 / 29.97 = 48.01 ]    

When I add the clip to a Track timeline at time zero, the box for the clip shows as extending to 47:10 (47 seconds and 10 frames), which sounds about right.  I can then use Openshot to preview the clip and see it play at the correct speed (my realtime appears to pass at the same rate as the realtime of the actors in the clip).  **_So far so good?_**

**However,** when using Openshot to preview the clip from zero, the "red line" time cursor reaches the end of the clip-**_box_** after only about 38 seconds of WALL-clock time, even though the indicated cursor time (to the left of the timeline), and the timeline scale value displayed above the red line at the right side of the box, both indicate 00:00:47:10.  And at this point the preview continues to play with several seconds still remaining.

In other words **the red cursor advances across its time scale at a rate 1.25 times the rate of realtime, indicating time values 1.25 times the wall-time elapsed.**  The time counter to the left of the time scale always matches the position of the red time-cursor beneath the time scale, as expected; but both of them advance 1.25 times faster than time is passing for me or for the actors in the clip.

Furthermore, the preview continues to play until its true end -- taking the rest of the 48 seconds of wall-clock time -- advancing the red cursor beyond the end of the track's box for the clip until finally reaching the end of the clip and stopping with a cursor time indication of 00:00:59:09.    [ 59.30 / 47.33 = 1.25 ]

**_So far that describes a nuisance, but when cutting a clip it becomes much worse:_**

If you set the cursor location to a desired "cut" point based on looking at the Preview frames, the cut will actually be done at the location whose timecode the red time cursor indicates -- which is a (1.25 times) higher time value than the true time value associated with the frame you were looking at.

However, it may not be immediately clear that it is broken, because the preview doesn't always refresh.  To see for sure what really happened, I have been saving the .osp file, exit, restart, and open the saved .osp file.

(I have successfully made cuts in the **_desired_** place by dividing its _**indicated**_ timecode by 1.25 and moving the cursor left to do the cut there instead, keeping both sides of the cut, then save, exit openshot, restart openshot, open saved session.  Not a very pleasant workaround, but it makes the point about 1.25x)

This problem does not occur with all files, but importing any particular single file seems to give consistent results (its time scale is either always correct, or always incorrect by a factor of 1.25).  I did not notice anything to support the idea that the 1.25 derives from a (30/24) FPS conversion error in the media file -- but then I'm not expert at reading these entrails:

Clip info as reported by ffmpeg:
    Input #0, matroska,webm, from 'Cheech and Chong - No Clean Jokes.mkv':
      Metadata:
	ENCODER         : Lavf56.40.101
      Duration: 00:00:48.77, start: 0.000000, bitrate: 538 kb/s
	Stream #0:0(eng): Video: h264 (High), yuv420p, 640x480 [SAR 1:1 DAR 4:3],
				 29.97 fps, 29.97 tbr, 1k tbn, 59.94 tbc (default)
	Metadata:
	  LANGUAGE        : eng
	  ENCODER         : Lavc56.60.100 libx264
	  DURATION        : 00:00:48.651000000
	Stream #0:1(und): Audio: vorbis, 44100 Hz, stereo, fltp (default)
	Metadata:
	  CREATION_TIME   : 2015-09-30 07:07:48
	  LANGUAGE        : und
	  HANDLER_NAME    : SoundHandler
	  ENCODER         : Lavc56.60.100 libvorbis
	  DURATION        : 00:00:48.765000000

**Comment by DavidButterfield** [comment]
I too have seen "frame reversal" similar to that described in Issue #772:
-  "One clip made of 1 sec of blue screen and 1 sec of red screen.  I want to split it into two clips in order to separate blue screen into a first clip and red screen in a second one."
- "After split, I always have some _unwanted red images left at the end of the 'blue part' **AND** unwanted blue images put at the beginning of the second 'red part'_!"

I noticed this a couple of times, both times on clips that were showing the time-scaling problem.  Possibly the problems are related.

**Comment by DylanC** [comment]
@thomasgwatson @DavidButterfield - How does v2.4.1 work in relation to this issue?

**Comment by DylanC** [comment]
@thomasgwatson - Can you or @DavidButterfield  confirm this in a daily build? This issue is reported on a much older version now.

**Comment by clearhat** [comment]
Yesterday's daily build (OpenShot-v2.4.1-53) resolved this issue (or very similar) for my purposes, which involved cutting smaller clips out of a longer video and then linking them together. In 2.4.1, when I attempted to do this, the timing was always off and I had to restart OpenShot in between each cut to ensure any kind of accuracy. Tedious! With this build, exporting a shorter video after pulling two smaller clips out and deleting leftovers worked exactly as it should. Much appreciated!

**Comment by DylanC** [comment]
@clearhat - Excellent news! Thanks!

**Comment by clearhat** [comment]
Um, as I continue working with this, I think I should qualify my enthusiasm: It works _much better_ than it did, but I'm occasionally noticing a single-frame issue. Previously, the timing was off by large increments, many frames at a time, and unpredictably so, but now it is occasionally off by a single frame. This may be a slightly different issue than what was just fixed. The workaround for me is to accept the loss of a frame as I err on the side of caution while clipping. Sorry I did not test it more rigorously earlier.

**Comment by peanutbutterandcrackers** [comment]
I think there are a few other similar issues reported. There have also been a few discussions as to how this can be solved. I think the devs will figure out a way soon to fix this issue too. Please do look forward to an amazing future. :)

P. S: Thank you for sticking with and supporting OpenShot!
