### ISSUE TITLE
Openshot freeze/crash when exporting a video

### ISSUE THREAD

**Issue by LucileDT** [OpenShot/openshot-qt#822]
### System Details
**Operating System / Distro:** Windows 7
**OpenShot Version:** 2.3.4
**Log files:**
- [libopenshot.zip -Mega file because it's too big to be upload in Github, sorry...](
https://mega.nz/#!AHJmXIIR!Ze8WtP6uI_GWeOFIsqSSxcX6OXQypP4pBO02o9YdB0k)

- [openshot-qt.zip](https://github.com/OpenShot/openshot-qt/files/1201746/openshot-qt.zip)

### Scenario
- Create a project
- Save it
- Create in it
  - 3 tracks with audio
  - 2 tracks with .mp4
  - 1 track with a picture
- Be sure that the current project duration is more than 2 hours
- Save the project
- Export the video by doing File > Export
- Setup mp4 output in 720p
- Click on Ok

### Expected behavior
- After waiting some time, the video is exported at specified location

### Current behavior
- After some time, OpenShot does not answer anymore, the loading pop up freeze
- After a lot of time, Windows throws an error showing that Openshot crashed
- A `.mp4` is created at the specified location but is not valid and can't be played

**Comment by abrajuder** [comment]
I have the same issue and the worst part is that I have read too many persons with the same issue and np workaround so far...

In my case I'm running 2.3.4 version on Windows 7.  The program freezes each single time I try to export.

**Comment by LucileDT** [comment]
It's often difficult to understand where the problem is coming from, furthermore if the community opens tons of issues for the same error, that's why I think the best thing to do is be patient and nice with devs 🙂 💙

**Comment by abrajuder** [comment]
unfortunately this only issue made Openshot not usable for me. I tried
several times before posting and several more before giving up.

I really think this seems to be a great software and hope to been able to
use it in the near future.  meanwhile I found an alternative in kdenlive
that proved stable and helped me to finish the small project I had in mind.

the fact is that this is a show stopper and perhaps this is the reason the
community insists for a solution.  nevertheless this also helps the devs to
be aware the problem isn't resolved yet, since I read some posts asking to
try again with the latest versions and that is what I did.

Best regards

Juan

**Comment by DylanC** [comment]
@LucileDT - Does this happen on the latest daily build?

**Comment by LucileDT** [comment]
I will try this week to update and say you if it's working! Don't hesitate to poke me if I forgot @DylanC :)

**Comment by DylanC** [comment]
@LucileDT - Poke :)

**Comment by DylanC** [comment]
@LucileDT - Another Poke. :)

**Comment by LucileDT** [comment]
Hello @DylanC, sorry for the lack of new, I was away from computer for 2 weeks...

I retried the given scenario with OpenShot 2.4.1 and it worked fine, thank you very much for the dev and for the pokes! 💙

**Comment by DylanC** [comment]
@LucileDT - No problem. I started to get tired of giving pokes. =)  Glad to hear its all working now.

**Comment by bearon1223** [comment]
I am having the same issue now 7 mp4 tracks and a ton of pics
