### ISSUE TITLE
Cannot open an OSP file - cannot create file when file already exists

### ISSUE THREAD

**Issue by ghost** [OpenShot/openshot-qt#840]
**System Details:**
* Operating System / Distro: Windows 10, Surface 3 Pro
* OpenShot Version: 2.3.4

**Issue Description and steps to reproduce:**
Hi, my editor just crashed and I tried to open the saved project after that and got an error about the file already existing below.
Error text: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\Phil\\.openshot_qt\\thumbnail'

I was nearly done and really don't want to go through this editing again.  Let me know if there's a way to access my file.

Cheers,
Phil

**Comment by croco3008** [comment]
Try to empty your thumbnail folder. Does it help?

**Comment by DylanC** [comment]
@pdaws11 - Hi Phil, Please try to delete your thumbnail folder. This should resolve your issue.

**Comment by Foadsf** [comment]
deleting the folder `thumbnail` in `c:\Users\foobar\.openshot_qt\` temporarily solves the problem. But this issue arises upon restart and requires proper solution IMHO.

**Comment by ferdnyc** [comment]
> deleting the folder `thumbnail` in `c:\Users\foobar\.openshot_qt\` temporarily solves the problem.

Only temporarily? Under what conditions does it reoccur?

> But this issue arises upon restart and requires proper solution IMHO.

On restart of... OpenShot, or the system?

The original report was about files existing during crash recovery, this shouldn't occur normally. (It shouldn't occur at all, really. There are like three different pieces of code that redundantly try to clear out the thumbnail directory.)

Long story short, it was believed that this _was_ solved.

Windows 10 has been known to exhibit some weird permissions issues that don't occur on other OSes, perhaps it's something specific to that OS.

**Comment by Foadsf** [comment]
> On restart of... OpenShot, or the system?

A restart of the OpenShot. This is only on Windows 10 `1903` ([more details of OS](https://github.com/OpenShot/openshot-qt/issues/493#issuecomment-526837086)) but on another system, with version 1809 (OS build 17763.678) it seems to be OK!

**Comment by ferdnyc** [comment]
Hmm. The only thing I can think of that might be causing this kind of problem _originates_ here, though it's not actually the bug:

https://github.com/OpenShot/openshot-qt/blob/483b719694da7d5d9413f7dab40535f1c505abd5/src/classes/info.py#L65-L66

That all works "fine", because of the `exist_ok=True`, even though it's mis-encoding the pathname. (As I've repeatedly tried to impress upon people, **Windows. _doesn't._ use.** UTF-8 for its filesystem encoding. Encoding paths into UTF-8 is always wrong, even if it works 99% of the time.) But it's not even the encoding that's the issue here.

The problem is with all those _other_ redundant thumbnail-clearing attempts I mentioned. They aren't protected against the same failures. So, if there are _permissions_ problems that are preventing us from deleting or recreating the directory `%USERPROFILE%/.openshot_qt/thumbnail` on Windows, they won't be noticed when `info.py` tries to set up the project dirs initially (because it was modified to ignore all of the warning signs). They'll only come up when this code subsequently attempts to clear out the dir:

https://github.com/OpenShot/openshot-qt/blob/483b719694da7d5d9413f7dab40535f1c505abd5/src/windows/main_window.py#L544-L552

Or when this code attempts to do the same thing, while loading a project file:

https://github.com/OpenShot/openshot-qt/blob/483b719694da7d5d9413f7dab40535f1c505abd5/src/classes/project_data.py#L365-L373

Most likely it's that last one, which also doesn't have the exception-handling around it that the previous code does. The second argument to `shutil.rmtree()` (set to `True`) is `ignore_errors`, which means that any failures deleting the path will be ignored, and the subsequent attempt to copy a thumbnail directory from elsewhere will result in an application crash.

I've completely rewritten the code for how project assets (including thumbnails) are managed recently, as it turns out (that's PR #2976). It doesn't solve **_this_** issue yet (in fact, I'm quite sure it will exhibit the same bug, currently), but I'd like to approach the problem in the context of the revamped code. 

To completely solve this issue, it may even be necessary to finally abandon the `%USERDIR%/.openshot_qt` directory in favor of the approved system locations for things like configuration, working, and cache files. I wouldn't be surprised if all three OSes make it increasingly difficult for us to keep using our "rogue" location to store OpenShot data.

Anyway, I guess two things for right now, @Foadsf:

1. There _should_ be at least some clues in `%USERPROFILE%/.openshot_qt/openshot-qt.log`  about OpenShot's actions leading up to the directory-creation failure, even if it doesn't log the actual failure itself. If you'd be able to provide a log capture for this issue on Windows 10, that would be helpful. The procedure is found in https://github.com/OpenShot/openshot-qt/blob/develop/CONTRIBUTING.md , and `.log` files can be posted directly to GitHub comments as an attachment.

2. I have some thoughts on fixes for this problem, both short- and longer-term... assuming I'm right that it's ultimately an unhandled permissions issue when we're trying to manage the OpenShot directories. I'll work on a PR with those changes.

    Once that's ready, I'd also like to generate test builds containing **both** the changes for this issue, and #2976 — if I make those available, would you be interested in testing the new code? I'd be very interested in the results, since I don't have access to a Windows 10 system for testing.

**Comment by ferdnyc** [comment]
> 1. There _should_ be at least some clues in `%USERPROFILE%/.openshot_qt/openshot-qt.log`  about OpenShot's actions leading up to the directory-creation failure, even if it doesn't log the actual failure itself. If you'd be able to provide a log capture for this issue on Windows 10, that would be helpful. The procedure is found in https://github.com/OpenShot/openshot-qt/blob/develop/CONTRIBUTING.md , and `.log` files can be posted directly to GitHub comments as an attachment.

Oh, but I should note: Don't worry about debug mode (in fact, _please_ **don't** enable debug mode), as it will just add a lot of extra noise to the logs that won't be any help in examining _this_ issue.

**Comment by Foadsf** [comment]
> if I make those available, would you be interested in testing the new code? 

sure. I don't know much about the technical jargon you just mentioned but I will be happy to test. If I ever miss your messages here, [this is my Twitter](https://twitter.com/fsfarimani). I also follow [you on Twitter](https://twitter.com/ferdnyc).

**Comment by ferdnyc** [comment]
My condolences. I avoid Twitter as much as possible.

Anyway, thanks for agreeing to test the new builds, I'll let you know when I have something. How about this part?

> If you'd be able to provide a log capture for this issue on Windows 10, that would be helpful. The procedure is found in https://github.com/OpenShot/openshot-qt/blob/develop/CONTRIBUTING.md , and `.log` files can be posted directly to GitHub comments as an attachment.
>
> Oh, but I should note: Don't worry about debug mode (in fact, _please_ **don't** enable debug mode), as it will just add a lot of extra noise to the logs that won't be any help in examining this issue.

**Comment by Foadsf** [comment]
Sure. I will have some time with my Windows computer on Thursday and will post the log file.

**P.S.** I hate posting log files into forums. I wish GitHub that the feature to attach a file or something. :(

**Comment by ferdnyc** [comment]
It... does? You just drop the file into the comment box to attach it.

Unless you mean you'd prefer to share the file _privately_? Not sure how GitHub could really make that work, since Issues data is all public, at least for public repositories.
