### ISSUE TITLE
Video Rolling Shutter Effect Fix

### ISSUE THREAD

**Issue by bes1002t** [OpenShot/openshot-qt#848]
Hi,

this is more a question than an issue. I'm new to video editing and probably I will use some tools just once a month or so, but for me a feature to fix the damn rolling shutter effect would be essential. All mirrorless systemcameras are producing this effect while filming in 4k, sometimes even in FullHD. So to enjoy the awesome video quality it would be important to fix this rolling shutter effect. 

There are some small fixes you can do on the camera itself, but they would affect the video quality. I would prefer to fix them by software after. Is OpenShot able to fix the rolling shutter effect in 4K videos? If not the only way for me would be to pay for Adobe Premiere Pro or some other expensive tools which are able to do that.

**Comment by DylanC** [comment]
@bes1002t - What is a shutter rolling effect? Do you have an example?

**Comment by bes1002t** [comment]
This is a good explanation I think: https://m.youtube.com/watch?v=EaB9EHeDLSk

**Comment by DylanC** [comment]
@bes1002t - Thanks.

**Comment by bes1002t** [comment]
some new thoughts about this topic?

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Do you have any thoughts on this?

**Comment by peanutbutterandcrackers** [comment]
@DylanC - It seems that rolling shutter is an effect that manifests because of the way the newer cameras record light (one row of pixels at a time). And, turns out, to my dismay, there aren't really many relevant  results showing up for a quick 'rolling shutter effect fix linux'. I think, if OpenShot could have an effect that could fix it, that would be awesome. A +1 for Open Source in general.
@ferdnyc and @N3WWN - Perhaps you'd like to give it a shot?

Also, there's [this](https://github.com/Zulko/moviepy) another command-line python movie processing project that could be used to fix this. And [here](https://github.com/alexd3rsan/rollingshutterpy) is someone's implementation (in python) of a simple rolling shutter effect - perhaps would come in handy for reverse-engineering...

**Comment by ferdnyc** [comment]
(Re: Rolling Shutter, for the record — documentation on tools / repair techniques from...)
* [Final Cut Pro X](https://support.apple.com/kb/ph12564?locale=en_US)
* [iMovie (2013)](https://support.apple.com/kb/PH14719?locale=en_US)
* [Adobe Premiere Pro](https://helpx.adobe.com/premiere-pro/using/rolling-shutter-repair.html)
* [muvee Turbo Video Stabilizer](https://www.muvee.com/for/stabilize-gopro-video/4-easy-ways-to-stabilize-videos/rolling-shutter-correction)
* [Deshaker](http://www.guthspot.se/video/deshaker.htm), a free plugin for the (also free) Windows video processing software VirtualDub

To be honest, OpenShot isn't going to be much help to you here. Certainly not at the moment. Maybe someday down the road it will include video repair/correction processing as part of its toolkit, but right now that's not even something it's _trying_ to handle. There are far better tools out there for converting/correcting video, ones written with that purpose in mind. With OpenShot it's generally best (at this point in its evolution, at least) to sort all of that out _beforehand_, then import the processed and cleaned-up video. OpenShot just isn't the place to be doing things like video stabilization, and if you're looking at it for that purpose **alone** then I absolutely recommend looking elsewhere.

Normally I'd suggest avidemux, as it's my go-to video processing/conversion swiss army knife. But it doesn't appear that they really have anything in the way of image-stabilization filters available. HandBrake is also a bust. VirtualDub with Deshaker is probably your best bet, certainly if you're running Windows.

**Comment by ferdnyc** [comment]
(I only just now realized the original question is a year old. But my comments stand for anyone else with the same needs, even if the original submitter is long gone.) 

This is not something OpenShot has **any** ability to deal with at present, and I'd be reluctant to change that because IMHO there are far better tools for doing _this_ sort of task. Correcting defects like shakiness and capture artifacts is best taken care of using a standalone processing tool, _prior to_ bringing the video into the edit bay — not done in real-time when you're _in_ the edit bay. 

Yes, massive commercial editors like Final Cut and Premiere offer stabilization as just another video "effect", but standalone processing/transcoding tools like Turbo Video Stabilzer, VirtualDub, avidemux, and etc. still have their uses and can sometimes give better results with a little tweaking. And doing that work beforehand lessens the load on your editing suite later on.

I'm honestly quite surprised that avidemux still doesn't have any filter that even makes an _attempt_ to address these issues. But software of _that_ type is where these tools should be developed, first.

**Comment by N3WWN** [comment]
I, too, resolve issues like this before importing the clips into OpenShot.

For stabilization, I use ffmpeg.

First, use detect the stabilization values that will need to be used:

`ffmpeg -i clip.mp4 -vf vidstabdetect -f null -` 

Then, use those values to stabilize the clip and save it as a new clip:

`ffmpeg -i clip.mp4 -vf vidstabtransform=smoothing=30:optzoom=2:zoomspeed=0.1,unsharp=5:5:0.8:3:3:0.4 -r 30 clip-Stabilized.mp4`

Finally, I like to sort my clips by date, so I touch the new clip to update the timestamp using the original clip as the reference:

`touch -r clip.mp4 clip-Stabilized.mp4`

**Comment by DylanC** [comment]
@peanutbutterandcrackers @ferdnyc @N3WWN - I think this question can be considered fully answered and closed at this point? 😆

**Comment by ferdnyc** [comment]
I would personally say so. It _could_ be considered a feature request, but IMHO it's just something OpenShot doesn't do, which is **#NOTABUG**.

**Comment by DylanC** [comment]
@ferdnyc - To me it sounds like something to be done before importing a clip at all. So maybe best left to an external tool. @N3WWN's solution looks good enough for me and most users.

**Comment by DylanC** [comment]
@bes1002t - Have a look at the solution posted by @N3WWN. If you feel this is really something Openshot should cater for can you open a separate enhancement request containing info on how you would expect this feature to work in Openshot? Thanks.

**Comment by bes1002t** [comment]
Hi all and thanks for your proposals!

The purpose of my ticket was a feature request. But if you say such a feature would not fit to the featureset of open shot, then it's ok for me. You guys posted enough other solutions and I think one of them would work for me. :P

thanks for your help!
