### ISSUE TITLE
Audio only works the first part of the video and then starts to stutter

### ISSUE THREAD

**Issue by kooij014** [OpenShot/openshot-qt#855]
**System Details:**
* Operating System / Distro: ? windows 10
* OpenShot Version: ? version 2.3.4 dev3
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
When I create a video and add audio then during preview and export the audio first plays well but after sometime (1 minute of more) the audio starts to stutter.

**Comment by jkjc** [comment]
Same for me with OpenShot-v2.3.4-6-g86f1d48-55-642-x86_64.exe on windows 7 except I get to 2 minutes before the the audio stutter starts.

**Comment by kooij014** [comment]
Indeed converting to OGG worked. Never heard of the format but it works!

**Comment by stimoceiver** [comment]
I was going to create a new issue but I appear to have the same problem.

Windows 7 Ultimate x64
CPU: I7 4790K running at 4.1 Ghz (motherboard default)
Motherboard: Supermicro X10SAT
Memory: 32GB Kingston DDR3
Graphics: AMD Radeon R9 290, 8GB
Openshot Versions: First 2.3.4 and, after reading about similar issues, today's nightly: OpenShot-v2.3.4-6-g86f1d48-55-642-x86_64

I imported one approximately 3 minute 192kbps CBR mp3

Problem: No matter what I do with the mp3, at least some portion of it - towards the end - begins stuttering.  I duplicated this by importing into an empty project: same stuttering. Tried updating to today's nightly build: still stuttering.

Stuttering does not always seem to begin at the same time marker - if I add static jpegs and images with transitions, the stuttering started earlier. 

The file plays fine on all other apps I've used, but I know that doesnt mean it is totally free of corruption. So I loaded the offending file in Audacity and re-exported as same bitrate but VBR instead of CBR, reimported into OpenShot: still stuttering. I used mp3diags to examine the file for issues, it didn't flag any, but I did note it was unable to "Rebuild VBR". Exporting from Audacity as ogg instead fixed the problem.

Attached mp3 in question. In an empty project, stuttering begins around 2:32:?? 
[06. final solution (full uncut version).mp3.zip]
(https://github.com/OpenShot/openshot-qt/files/1262376/06.final.solution.full.uncut.version.mp3.zip)

**Comment by kooij014** [comment]
Today I tried again with different MP3's.

1. video without any jpg still the stuttering will start towards the end of the video (say 2/3). 

2. played the mp3 in media player no problem it sounds perfect.

3. of all the video clips I brought down the volume to 0% before I added the mp3. Issue remains

4. converted mp3 to ogg and added. Still same result the stuttering starts say 2/3 of the elapsed time.

**Comment by kooij014** [comment]
Another attempt this time succesful. 

1. I  used 2 tracks! first track had the audio file in ogg format and the second track 4 video clips with a title and end.

2. ensure all audio on the clips was set to 0% before I added the audio file

Export was quick and result is good.

Am I happy no because I am not sure if this is the solution. It is still a bug that you cannot add audio without a lot of preperation. The above workaround seems to work for the moment but is not a solution.

**Comment by DylanC** [comment]
@kooij014 -  Thanks for the feedback. I know it is not ideal yet but in the future the project will become much more stable. It just takes time.
