### ISSUE TITLE
Import mp4 speedup video not work in result

### ISSUE THREAD

**Issue by grig27** [OpenShot/openshot-qt#874]
* Windows 7 x64
* OpenShot Version: 2.3.4

Import video mp4.
Append to video line.
Speed up video at x16.

Export video into mp4.

Play video.... speed x1.

**Comment by drsdre** [comment]
In the latest version 2.4.0 the speed up seems to work again.  But... with v 2.4.0 the problem now is that start time of the video with speed up is wrong in the rendered video (preview is fine).

For example if a clip was placed in the timeline to start at 00:02:00:00 with time speed x8 and rendered. The rendered result will be that on 00:02:00:00 the clip has already been playing since 00:00:00:00 and therefore the first part of the video is not shown.

**Comment by DylanC** [comment]
@grig27 - Tested this as working in v2.4. Please try again in the latest version.
