### ISSUE TITLE
Using seconds:frames in stead of decimal seconds

### ISSUE THREAD

**Issue by itsharrie** [OpenShot/openshot-qt#916]
System Details:

Operating System / Distro: Linux Mint 18.2 64bit
OpenShot Version: 2.4.0

**Issue Description and steps to reproduce:**
In the **Properties** frame, the **Position** property is expressed in decimal seconds. In the time line seconds:frames are used. To improve consistent use of dimensions (although not conform the SI standard;-)) I would suggest to also use seconds:frames in the **Position** property.

**Comment by peanutbutterandcrackers** [comment]
I wonder if the position really is talking about the __time__. While it does make sense to have a "consistent use of dimensions", I think the position, if it is dealing with time, is better off without accounting for the frames in the parameter itself as frame rates differ but time is quite standard. Don't you think? Just my opinion though...

**Comment by N3WWN** [comment]
I think this may be the underlying problem we see with some other issues where things occur at different times depending on the render frame rate;  keyframes appear to be located by storing the frame # .  

I think keyframes should probably be stored by location on the timeline since that is how we specify *when* we want something to occur.

Another improvement would be adding the value unit to the properties table... that could either be part of the existing name field or a new field to the right of the value.

I think implementing something like this will make some of the non-intuitive values apparent.  For instance, `Scale` is a unit value:

`Scale` `1.00`

...when it would probably be more intuitive if displayed as a percentage:

`Scale` `100` `%`

or

`Scale [%]` `100`

This would only require an internal change as to how keyframes are stored.  From frame number to time reference.

If the frame number is necessary, internally, for keyframes to work, the frame number could be calculated when the frames are loaded (when a saved project is opened), but saved in the project file as a time reference.

Any time a keyframe dependent (or frame rate dependent) change is made, the time of the keyframes would be converted to frame numbers.  Changing the project frame rate or using a different export frame rate than the project frame rate would trigger recalculation of all keyframe frame numbers.

But, adding the display unit would also allow the addition of preference settings so that values can be displayed in the unit best suited for the user, which is purely value entry and display.

**Comment by N3WWN** [comment]
This is one of those issues that remains but hasn't received any love :)

**Comment by N3WWN** [comment]
This is one of those issues that remains but hasn't received any love :)
