### ISSUE TITLE
Irregular time scale in Time Line

### ISSUE THREAD

**Issue by itsharrie** [OpenShot/openshot-qt#918]
**System Details:**
* Operating System / Distro: Linux Mint 18.2 64bit
* OpenShot Version: 2.4.0

**Issue Description and steps to reproduce:**
Zooming the **Time Line** can be done by dragging the slider. The **+** or **-** controls increment/decrement by 1 second. This often results in a highly irregular time scale. Also the setting becomes overly fine grained at high values.

For example, 17 seconds per division yields the following time scale:
00:00:00  00:00:17  00:00:34  00:00:51  00:01:08  00:01:25  00:01:42  00:01:59  00:02:16
This scale is difficult to interpret.

A setting of 15 seconds per division yields:
00:00:00  00:00:15  00:00:30  00:00:45  00:01:00  00:01:15  00:01:30  00:01:45  00:02:00
This time scale is much easier to read because the same seconds division repeats every minute.

To improve the usability of the time scale, the interval values set by the **+** or **-** controls should be limited to:
1, 2, 3, 4, 6, 10, 15, 20, 30, 60, 120, 180, 270, 360, 600, 900, 1200, 1800, 3600 seconds per division.

The same could/should be applied to setting the scale by dragging the slider. (Preferences setting?)

**Comment by DylanC** [comment]
@itsharrie - Thanks for the report.

**Comment by N3WWN** [comment]
I agree;  once the scale is adjusted beyond about 15s/div, zooming out by 1 sec intervals is not very useful.

There's also requests to zoom in more than 1s/div for those of us who need to do things like sync multiple videos (PIP, for instance) by dragging one of the videos frame-by-frame, so I think the minimum should be somewhere around 0.1s/div... perhaps 0.1, 0.2, 0.5, 1.0, 2.0 etc sec/div.

I think I'd prefer is there wasn't a hard minimum at all, though:

- If the sec/div is > 60, make it an even multiple of 60 (120, 240, 360, 480, 600...)
- If the sec/div is >= 1 and <= 60, make it a reasonable value (1, 2, 3, 5, 10, 15, 30, 60)
- If the sec/div is < 1, make it an even division of powers of 2 (0.5, 0.25, 0.125...)

**Comment by DylanC** [comment]
@N3WWN - What is the current situation with this issue? Still a problem?

**Comment by N3WWN** [comment]
@DylanC ,

I believe #1411 helped with this, but, as discussed in that PR, it may make sense for the step after 8s to be 15s (instead of 16s) so there are 1/4 minute and whole minute divisions.  Likewise with the next step being 30s instead of 32s for the same reason (although that may be implicitly fixed with an explicit 15s, I haven't looked at the code).  

The current step to 60s after 32s makes a lot of sense, as do the steps beyond that.

I don't think a "BUG" tag would be appropriate here... perhaps "ENHANCEMENT"?

**Comment by ferdnyc** [comment]
Yeah, it hasn't slipped my mind that I need to get back to that and finish it up, and I shall. The code continues to use a time-based scale for the zoom levels, and still allows arbitrary zoom levels that don't appear on the scale. (That's to avoid incompatibility with old project files, which will mostly have arbitrary stored zoom levels that don't match our new list — especially since 16s is the default. Which reminds me, I'll also need to change the default to 15s.) 

That actually makes it somewhat harder to have the zoom steps live in a set list of fixed levels, since arbitrary values don't match any element on that list. It's easier to just compute the next higher/lower zoom from the current value using math tricks, the way my current code does. But, I dug up a technique that uses Python's `bisect()` to quickly find the position of arbitrary values in a sorted list, whether they match one of the list elements or not. So, that should be no big deal to get working.

**Comment by N3WWN** [comment]
I haven't looked at the zoom code, either, but could you accept arbitrary zoom values which are stored in the project file when the project is opened, but when you zoom in or out, the "needle" drops into the "groove" of fixed levels?   Or perhaps round to the closest valid zoom value?

**Comment by ferdnyc** [comment]
> I haven't looked at the zoom code, either, but could you accept arbitrary zoom values which are stored in the project file when the project is opened, but when you zoom in or out, the "needle" drops into the "groove" of fixed levels? Or perhaps round to the closest valid zoom value?

That's the plan, yes. The current code does exactly that by performing math tricks on the zoom level, because it's nearly-exponential (so, roughly, `m = zoom_out_function(n)` produces the same result `m` for any zoom level `[n..m-1]`). If the stored zoom level isn't one of the set levels, the first time the function is applied it'll come out as the next higher/lower set level.

That'll be replaced with a set list of zoom levels, and (in pseudocode) two functions `zoom_out(n)` and `zoom_in(n)` that bisect the sorted list so that, for any positions `m` and `m+1` on the list, `zoom_out(n)` will return the `zoom[m+1]` value when `n` is any value between `zoom[m]` and `zoom[m+1]-1`. Same thing in the other direction, for `zoom_in(n)`.

**Comment by ferdnyc** [comment]
Aha. As I was about to start on that, I saw that I was beaten to the punch by @jonoomph with 836a0232161950b8da8b673c0ac3acdaf98de548 which reworks the zoom levels in a different way. So, ignore that stuff I said above.
