### ISSUE TITLE
Properties list scrolls up when reselecting the clip

### ISSUE THREAD

**Issue by itsharrie** [OpenShot/openshot-qt#919]
System Details:

    Operating System / Distro: Linux Mint 18.2 64bit
    OpenShot Version: 2.4.0

**Issue Description and steps to reproduce:**
Select a clip on the Time Line,
Scroll down the properties list,
Reselect the clip on the Time Line.
Result:
The properties list unexpectedly scrolls up. The user has to scroll down again to continue working on the desired property.

**Comment by ferdnyc** [comment]
Reopening this as well. Knowing what I know now about Qt table widgets, it's actually a fairly easy fix. In fact, Qt has the ability to capture and restore the selected row in a table, and to ensure that the same row is scrolled into view after repopulating the table's data. We should be taking advantage of that. 

This problem was made somewhat better when the default layout was changed to make Properties the full height of the window, but still most users don't have the screen height to fit a Clip's entire list. And right now, if you want to monitor the value of a property that doesn't fit on the first "page" of that list, it's incredibly frustrating to do. You have to keep constantly scrolling back down to it. Just having it selected in the list should be all that's required.

Marking as a beginner issue, tentatively. Because while it may be somewhat daunting for anyone unfamiliar with our code base, all of the functionality is readily available in the Qt API.
