### ISSUE TITLE
Inconsistent use of navigation icons in Time Line navigation bar

### ISSUE THREAD

**Issue by itsharrie** [OpenShot/openshot-qt#920]
System Details:

Operating System / Distro: Linux Mint 18.2 64bit
OpenShot Version: 2.4.0

**Issue Description and steps to reproduce:**
In the **Video Preview** frame the orange icons **|<** and **>|** are used to jump to start and end of the clip respectivily.
The same orange icons are used in the **Time Line** navigation bar to jump to previous and next marker. This is inconsistent and may confuse the user.

Proposed solution:
1. In the **Time Line** navigation bar use icons **'<** and **>'** (replace **'** with the marker icon used in the **Time Line**) for jumping to previous and next marker respectivily. Grey out these controls if no markers present.
2. To match the style of the **Time Line** navigation bar to the **Video Preview** navigation bar, the **Add Marker** control may be positioned inbetween the **Jump to Start** and **Jump to End** controls:**'<   V   >'**
3. Change the color of the three controls in the **Time Line** navigation bar as well as the marker icons in the **Time Line** to (light) blue to emphasize functional consistency.

**Comment by ferdnyc** [comment]
I'm going to close this one, because:

1. If there are no markers (or even if there are), when a clip is selected, Prev/Next Marker _will_ jump to the start/end of the selected clip; the clip boundaries are also treated as markers. So, graying them out when no (explicit) markers are present would not be desirable.
1. That also means that, in the presence of no markers, the functionality actually _does_ pretty well mirror the Preview transport controls that use the same icons.
1. The icons used are stock theme icons, they're not re-colorable (and not necessarily orange). They're also not easily customizable for the same reason.

**Comment by ferdnyc** [comment]
(Oh, right, and I already fixed the fact that the **same** icons were used in both places, with #1381. The Preview toolbar wasn't using the correct skip-start/skip-end media transport icons.)
