### ISSUE TITLE
Clips discarded by slice are showing up in the timeline after doing an Undo

### ISSUE THREAD

**Issue by ImpertinentThinker** [OpenShot/openshot-qt#934]
**System Details:**
* Operating System / Distro: Windows 10 Home 64x
* OpenShot Version: 2.4.0

**Issue Description and steps to reproduce:**
I'm not even sure if I have the vocabulary to describe this, but here goes. I was editing talking heads out of a short (2 min) video file. The way I normally do this is:
1. Drag position marker right until undesired image appears in preview
2. Drag position marker left until just before that
3. Right click, Slice, Keep Both
4. Drag slider right until undesired image is gone
5. Right click, Slice, Keep Right
6. Drag the clip on the right back left so it abuts what was sliced, making a seamless whole
7. Repeat

This is all fine and works, but near the end of the project the snap to during step 6 gets a bit sticky, and I accidentally drag it too far and create a transition. I press ctrl-z to get out of it, and suddenly 1)the right most clip is now one of the ones I discarded several steps earlier in one of the iteration of step 5. 2)every clip to the right is now gone, replaced by the old discarded clip that has somehow come back from the trash. I can't ctrl-z out of the problem, the timeline reverts, but every clip past the point of accidental transition is now the discarded clip. Interestingly, the timeline preview snapshot still shows the "old" (lost) thumbnail, and the video preview shows the "new" (discarded) clip, in either drag or playback modes. This happened consistently in this project after 7 slice/keep both/slice/keep right operations.

I'm sorry I can't describe it any better, but it "feels" like some kind of memory swaparoo is happening, where a memory range used by the assigned clip is somehow being replaced by a previous discarded clip. The important thing is that none of this happens **until** the accidental transition/undo happens; I've managed to do it accidentally three times on this project (the snap to gets really sticky at the end for some reason). I realize this is a weirdly ambiguous description but I've recreated it as best I can mentally. I can upload the project file if you like, it's only 200kb.

**Comment by DylanC** [comment]
@ImpertinentThinker - Can you record a screencast of this issue in action? I find the description a bit confusing if you don't mind me saying.

**Comment by ImpertinentThinker** [comment]
No offence taken, I knew it'd be a hard nut to comprehend before I wrote it up. I can't do it immediately since I'm at work and finished the video, but will try to get something going later possibly with screenshots as I've never done a screencast.

**Comment by gjinxers** [comment]
ImpertinentThinker  -- If I am understanding your explanation correctly, I have done this EXACT scenario several times within the project I am currently working on. I finally realized that I did not need to hit "ctrl-z" or "undo" at all to get rid of the transition that the dragging of the clip created.  Just stop moving the mouse, take a breath & right-click on the transition itself or use the little down arrow on the transition itself and select "remove transition" from the pop-up menu that populates. 

This way you don't UNDO the actual "slicing" of your video clip. When you hit "ctrl-z/undo", OpenShot performed the requested function of undoing your last mouse action which was the slicing & dragging of the clip. The transition creation was just an automatic function of you overlaying the 2 clips accidently.

Also since this happened to me repeatedly while using the "slice" function, I now use the "razor tool" its much more accurate. However, after you razor something and you see the new version of the clip in your track on the timeline, remember to select the razor tool icon again to give you back the regular mouse cursor before attempting to move the new razored clip and selecting the razor tool again to finish cutting the other end of the unwanted section.

Hope this helps..... My apologies if it doesn't.           Good luck with your issue though.
