### ISSUE TITLE
Error exporting video: Sorry, there was an error exporting your video:  exception class 'openshot.ReaderClosed'

### ISSUE THREAD

**Issue by benpocalypse** [OpenShot/openshot-qt#94]
Hello,

I'm running the latest OpenShot beta (2.0.6) under Xubuntu 15.04, and am having an issue exporting video. No matter what format I choose, as soon as I choose my export format, and then click Export Video, I get this error in a popup window:

```
Sorry, there was an error exporting your video: 
exception class 'openshot.ReaderClosed'
```

OpenShot doesn't crash, and continues to be useable afterwards, but I can't export any video this way. If you need any more information, or logs, or detailed information, just let me know and I can post them here.

The entire project is only ~136MB, so if you need me to put that somewhere to share, I can do that as well.

Thanks!
-Ben

**Comment by brobr** [comment]
Same here on Slackware64-current, although a different error is shown:

> "built-in function delete_InvalidCodec"

When openened in a console it seems that the export settings don't agree with the input clip.
After repairing that (width, audo-codec etc) it still gives this error (see attached docs).

Question: why does the export filter not take over the settings from the edited clip?? I just wanted to change the length of a nice video but it is very difficult to reproduce all the settings. The video obviously works, as I can edit and pre-view it but its characteristics are not directly translated to the export dialog. Could that be implemented? Would it also be possible to introduce an info-panel to show the characteristics of the clip one is working with as input; I now have to get that by opening it in SMPlayer or so......
[video-input.txt](https://github.com/OpenShot/openshot-qt/files/134887/video-input.txt)
[wed17feb.txt](https://github.com/OpenShot/openshot-qt/files/134888/wed17feb.txt)

**Comment by brobr** [comment]
I managed to export using ogg/vorbis and saw that these codecs were compiled into ffmpeg (see below). It turned out that x264 and mp3lame, though present on the system, had not been incorporated properly. After getting that sorted, export works ok and the result looks great ;-)

Before recompiling ffmpeg I got this:
`bash-4.3$ ffmpeg -codecs | grep 264
ffmpeg version 2.8.6 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.3.0 (GCC)
  configuration: --prefix=/usr --libdir=/usr/lib64 --shlibdir=/usr/lib64 --docdir=/usr/doc/ffmpeg-2.8.6/html --mandir=/usr/man --disable-debug --enable-shared --disable-static --enable-pthreads --enable-libtheora` **--enable-libvorbis** `--enable-gpl --enable-version3 --enable-postproc --enable-swscale --enable-x11grab --enable-avfilter --enable-gnutls --enable-libcdio --enable-libssh --enable-libcaca --enable-libsmbclient --enable-opengl --enable-libvpx --enable-libpulse --enable-libopenjpeg --enable-libwavpack --enable-libfreetype --enable-libfribidi --enable-fontconfig --enable-avresample --arch=x86_64
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
 D.V.LS h264                 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (decoders: h264 h264_vdpau )
`
after recompiling the same command gave:

`bash-4.3$ ffmpeg -codecs | grep 264
ffmpeg version 2.8.6 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.3.0 (GCC)
  configuration: --prefix=/usr --libdir=/usr/lib64 --shlibdir=/usr/lib64 --docdir=/usr/doc/ffmpeg-2.8.6/html --mandir=/usr/man --disable-debug --enable-shared --disable-static --enable-pthreads --enable-libtheora --enable-libvorbis --enable-gpl --enable-version3 --enable-postproc --enable-swscale --enable-x11grab --enable-avfilter --enable-gnutls --enable-libcdio --enable-libssh --enable-libcaca --enable-libsmbclient --enable-opengl --enable-libvpx --enable-libpulse --enable-libopenjpeg --enable-libwavpack --enable-libfreetype --enable-libfribidi --enable-fontconfig --enable-frei0r --enable-avresample --enable-libcelt --enable-libtwolame` **--enable-libmp3lame --enable-libx264** `--arch=x86_64
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
 DEV.LS h264                 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (decoders: h264 h264_vdpau ) (`  **encoders: libx264 libx264rgb** ` )
`

**Comment by jonoomph** [comment]
Please retest with our latest daily build. Please visit www.openshot.org/download, click '**Other Downloads**', and install the latest daily build of OpenShot. If you still have issues exporting videos with the latest version, please attach log files and reopen this issue. Thanks!

**Comment by TheYMCA** [comment]
I'm having the same problem, on ubuntu 16.04, how can I troubleshoot/ fix it please?
