### ISSUE TITLE
cannot split after 30 minutes

### ISSUE THREAD

**Issue by Athural** [OpenShot/openshot-qt#940]
using an mp4 that is 2 hours 13 minutes long, once i get to the 30 minute mark it stops loading the video. because of this i am unable to use the last hour and 45 of my source material. does anyone know why this happens? google returns nothing

**Comment by gjinxers** [comment]
Athural - I'm just a new user to OpenShot, but your issue peaked my interest. I would like to help if possible, but I have some questions regarding your issue. 

What operating system are you using?

Does the mp4 load and play fine in any other media player without any lag or long loading time?
When you say "it" stops loading the video, are you speaking of when you first IMPORT your file into OpenShot?

Or are you meaning that after you have imported the mp4 into OpenShot & see it's thumbnail in the "project files" window, drag/drop the file into the track for preview and after you make sure the timeline cursor is at the very beginning of your clip for playback, this is when the playback only plays to the 30 minute mark?

Or are you meaning that the timeline tracking bar only shows 30 minutes worth of counting numbers?

The reason I am asking questions is because I thought that part of my video file wasn't loaded either when I saw the timeline tracking bar numbers stop appearing as my video played in the preview. Even though the video preview window was still showing my video playing. I realize now that I was just a little overwhelmed by the program layout and functionality since it was so new to me.

I hope the wording of my questions make sense, and I am able to assist another OpenShot user.

Hope to hear back from you soon.

**Comment by Athural** [comment]
Thanks for expressing interest. I am using windows 10. To attempt to be a bit more clear what i am talking about is when i have added the mp4 to my project, and then right click and choose split clip. It will only play until it hits the 30 minute mark, and then stops. Choosing split clip and then trying to immediately take it past the 30 minute mark has the same result, the video just stops playing. I am able to add the video to the timeline and use the razor tool to edit the video anywhere from start to finish, and i am able to watch the video just fine in any media player i have tried. I have since made several other videos,  and i experience the same issue with all of them

**Comment by gjinxers** [comment]
@Athural -- I think this is a known issue for some. I have read lots of posts and haven't really seen much response back to the individual posts regarding this; however, they may be working on it since there are several users experiencing pretty much the same thing. 

Do you install the "daily builds" before opening each session of OpenShot?? I know that Dylan C has commented on several posts about some issues already being resolved in some of the builds.

**Comment by Athural** [comment]
I do not, but i will moving forward. Hopefully it is something that gets fixed eventually, as it is an inconvenience. I understand they probably have more important things to work on.

**Comment by gjinxers** [comment]
@Athural -- I am finding the program rather fun to play with, but unfortunately, I have a project that needs a faster turn-around than the solution to my issue is being provided to me. Sadly, I think I will have to try another video editing program that already has most of the bugs and kinks worked out.

I will keep playing with OpenShot though.   Good luck with your issue.

**Comment by DylanC** [comment]
@Athural - Thanks for the report.

**Comment by DylanC** [comment]
Dup of #629

**Comment by lindqueens10** [comment]
My video total length is 90 minutes+. I am having the Split Clip issue mentioned in this post also just before the 30-minute mark. Running Win 10, Openshot Editor 2.4.2. I increased Cache from the default of 250mb to 500mb and finally to 1,000mg. The problem persists. Please advise how I can fix the issue. thx.

**Comment by Athural** [comment]
Sorry, i havent found a solution.

**Comment by Willisbe30** [comment]
I am also having this problem. I am a brand new user - is it possible to just crop the original video into shorter chunks for this purpose in the short term? I haven't yet figured out how to do it.

**Comment by KorgBoy** [comment]
> 
> 
> I am also having this problem. I am a brand new user - is it possible to just crop the original video into shorter chunks for this purpose in the short term? I haven't yet figured out how to do it.

'crop' usually means putting a rectangle around a picture, and then remove the outter portion of the rectangular frame. I ended up just buying a software 'movavi' ...which I had bought after buying 'aunsoft final mate'. I got both of these software - but 'final mate' has a audio sync issue on my two computers, where (during editing) the audio is not aligned with the video footage - making it hard to edit. The 'movavi' works really well -- after figuring out how to use it. This openshot looks promising - as it is free - but this 30 min constraint definitely needs to be fixed - otherwise nobody can do much - unless the clip is relatively short.
