### ISSUE TITLE
Possible Bug: Fade to black at end of clip starts before reaching end of clip

### ISSUE THREAD

**Issue by pst007x** [OpenShot/openshot-qt#947]
OS: Ubuntu 16.04
OPENSHOT VERSION: 2.4.0 Openshot-qt

When adding a fade to black at the end of the clip, after export in 1080p the fade to black happens halfway through the clip. This does not happen when using 720p.

I create this issue by left clicking on the video timeline and adding the Fade at start of clip and Fade at end of clip. When reviewing BEFORE export all appears correct, this only happens after export using 1080p.

Export Details:
TARGET: MP4(h.264)
VIDEO PROFILE: HDV 1080 25p 1920x1080 (1920x1080)
QUALITY: High

This problem also happens when using Openshot-qt on Windows10

**Comment by pst007x** [comment]
OS: Ubuntu 16.04
OPENSHOT VERSION: 2.4.0  Openshot-qt 

When adding a fade to black at the end of the clip, after export in 1080p the fade to black happens halfway through the clip. This does not happen when using 720p.

I create this issue by left clicking on the video timeline and adding the Fade at start of clip and Fade at end of clip. When reviewing BEFORE export all appears correct, this only happens after export using 1080p.

This problem also happens when using Openshot-qt on Windows10

**Comment by DylanC** [comment]
@pst007x - Sync issues should be working in v2.4.1

**Comment by peanutbutterandcrackers** [comment]
@pst007x - Is this issue still persisting in Openshot v 2.4.1?

**Comment by george-easymarkit** [comment]
I am facing the same issue in 2.4.1

**Comment by N3WWN** [comment]
Are the 720p and 1080p framerates the same?  If you create a project using one frame rate, add keyframeable items (like fades) and then export at a different frame rate, the location of the fades will change.  This is a known issue and is being worked on.

**Comment by peanutbutterandcrackers** [comment]
1. You could [try out the latest daily builds](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914) to see if they work any better.
2. Instead of using the `right click > fade` method to do the fade ins and outs, you could go through [this guide](https://gist.github.com/peanutbutterandcrackers/f0f666243133e0ed25abbc12a4ba23d7) and learn how to use `alpha` value keyframes to control the fades - manually - giving you a lot more control over how things go.

Hope that helps!

**Comment by 3Dpassion** [comment]
Guys, I was rendering 25 minute 4K@60FPS video for 2 hours and guess what - same glitch. It faded out on minute 23 by itself, now have to rerender, and it may do the same thing again. I wish I used some paid software instead :((((((( It is not expensive, I just liked openshot more. Now I am a sad person :( Gonna try to render the remainding part and stitch them without having to reencode.

**Comment by peanutbutterandcrackers** [comment]
@3Dpassion - Sorry for the inconvenience. I have a few suggestions that might help.
1. Please make sure your footage and the profile (4k@60fps) really matches (which I don't think is the problem here but just in case)
2. Please try rendering into different 'targets' [`mp4`, `webm` etc]
![screenshot at 2018-11-26 15-55-09](https://user-images.githubusercontent.com/26764547/49007507-b725e280-f193-11e8-811f-c818eb911891.png)
3. If nothing else works, please head over to the Advanced tab of the export window and try the options there. For eg: Export 'Audio only' and 'Video only' (2 parts) and then mix them up using other tools like, perhaps `ffmpeg` or VLC Media Player (here's a guide: https://www.youtube.com/watch?v=0rN9yfO1kOc for VLC).
4. Perhaps try using the [latest daily build](https://gist.github.com/peanutbutterandcrackers/3618493b99ba08003e4e4b1602459914) of OpenShot rather than the stable version you are currently using.

Yes, OpenShot is not really the best software. But it will soon get better. Please be patient with it. Sorry for the inconvenience, again.

Hope that'll help.

**Comment by 3Dpassion** [comment]
Hey, thanks for your reply. Can not accept apologies for something I did not pay for :) After all it's free, and considering that fact it's a great piece of software. Bugs are inevitable. Answering your other hints - nothing helped and rendering audio and video separately won't work. As a temporary workaround, I removed a fade out at the end of video and just rendered that way and it worked.  Apparently the issue is in 60/30 FPS rendering. My video was 4K@60 which is not very typical for most people, which is why there is a bug probably.

Another suggestions for your software:
1) easy video stitching/joining without re-rendering - this would be great to have. Seems an easy task for you but was overlooked probably. I had to find another software for that, and none of software is good. Would be nice if you simply add that feature. I think stitching videos is way simpler compared to what you have already done :)
2) Color correction function. Also sadly missing. Would love to see it. It has been requested for quite some time (years), not sure why it is not done. Maybe it is hard to code? But anyways, I wanted to mention.
3) also, this is pretty bad "bug", not really a bug, but I have 8/16 core CPU, very powerful. 4.1GHz each core. But guess what, I can not preview or play 4K@60 video without it jerking every 1/2 second. What it looks like, is that software totally refuses to preload the clip further than 1/2 second ahead from current position, and this is why it jerks on heavy bandwidth load. There is no way my PC would cause this, so I am 100% certain it is the way Openshot is coded. Guys please allow this app to use more resources from CPU, in terms of cores, RAM etc. I have plenty and it seems it is not using them.

Thanks again for a great piece of FREE software we all can enjoy. I know how much work this is.

**Comment by peanutbutterandcrackers** [comment]
@3Dpassion - Thank you for the kind words.

For 1, you could use [avidemux](http://fixounet.free.fr/avidemux/); perhaps there might be a way to get that feature into openshot, too, someday; but I am not sure how feasible that will be. Still lets hope for the best.
For 2, yes work could be done regarding that
For 3, I guess you could try increasing the cache size by going to `Edit` > `Preferences` > `Cache` and setting the cache limit to a higher value. If you have an SSD, I would also suggest changing the cache mode to disk and changing the image quality to a much lower value. Playing around with the parameters there should give you a good result. Hopefully.

Please do let me know how it goes, and please do keep on loving, supporting, testing OpenShot.

Thank you!

**Comment by 3Dpassion** [comment]
None of that helps, otherwise I would have tuned that long time ago :) My memory limit there is at 8GB. Switching from my high speed 3200 ram to my NVMe SSD made things worse. Playing with image quality from 5 to 100 does nothing also, no change at all. I can even reduce CPU speed to 2.5GHz and it will also perform the same way and then I Overclock CPU to 4.2GHz and have same exact problem with no visible improvement, meaning this app is not using resources of my PC, not even nearly. Also I have GTX 1080Ti if that matters. Also, what is scale factor? Any ideas?

**Comment by peanutbutterandcrackers** [comment]
There is a hardware acceleration branch which is currently  work in progress. I am afraid you have no other choice but to wait for newer versions. In the meantime you could perhaps try pitivi, shotcut or kdenlive. Hope that helps.
