### ISSUE TITLE
Slow motion how to?

### ISSUE THREAD

**Issue by thob** [OpenShot/openshot-qt#949]
* Operating System / Distro: Linux Mint 17.x
* OpenShot Version: 2.4.0-dev1

How can I apply slow motion to a clip (or even parts of a clip). Tried the time property that didn't work at all.
Help appreciated.
Thanks

**Comment by grzegorz75jan** [comment]
- Operating System / Windows 10 Home 64bit
- OpenShot Version: OpenShot-v2.4.0-1-g8a71c3d-55-643-x86_64

I do not speak English. I will not do the instructional film for you because OpenShot does not want to work for me. It does not allow me to finish work. Each version of the program is a problem with:
- Preview of clip
- edition,
- export

Generally:
jerking, freezing, interrupting operation.
![2017 10 08-11 36_1](https://user-images.githubusercontent.com/32609882/31315693-b2e0765c-ac1d-11e7-91bd-8ffce65ea50b.jpg)

**Comment by thob** [comment]
well, that'll do it to some extent. How would you do this for only a few seconds of a clip? Or can you only apply it to entire clips?

**Comment by grzegorz75jan** [comment]
Can be applied to a fragment or to an entire clip. In my example, a clip of about 30 minutes is placed in the timeline. The clip is cut into fragments using the "Razor Tool" tool. Look carefully at my photo. The options shown apply to a fragment (several dozen seconds) with red frames on the sides. Just use the "Razor Tool" Extract the part you need. Then mark this part and work it out.

**Comment by thob** [comment]
Ok, so you need to cut then. Thanks

**Comment by DylanC** [comment]
@thob - This question seems to be answered. Closing for now. Thanks.
