### ISSUE TITLE
I can't manage to cut a clip before getting it to the time line

### ISSUE THREAD

**Issue by iniasoto** [OpenShot/openshot-qt#958]
**System Details:**
* Operating System / Distro: windows 7
* OpenShot Version: 2.4.0
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**

I recorded several clips with my camera, and have to select only a few seconds of each. 
I right click it and select "Divide clip"
![11](https://user-images.githubusercontent.com/32696434/31424142-07f88e32-ae2f-11e7-8ab7-cf5f02cae24e.png)

Then this screen appears, but i don't know where to select the start and end, i can only play the clip that i need to cut (for example i need only from 00:00:15 to 00:00:30)
![1](https://user-images.githubusercontent.com/32696434/31424200-55b24ad2-ae2f-11e7-8e1a-51048594c6aa.png)

When I click "Start" or "End" this appears and i can't do anything else. "Choose valid values of start and end for the clip"
![2](https://user-images.githubusercontent.com/32696434/31424260-9d83c804-ae2f-11e7-993d-3d880f05fe4a.png)

Where the f*ck do i choose them?

Please help!

Thanks

**Comment by DylanC** [comment]
@iniasoto - I can try this soon if you like. Should be able to figure it out.

**Comment by DylanC** [comment]
Users:
This guy wants to know how to use the split clip feature.

**Comment by peanutbutterandcrackers** [comment]
Hey there!

Wow. This has to be one of the best issue submissions. You have used screenshots and everything. Really well done.

Just in case you haven't figured it by now, think I can help. First and foremost, please upgrade your OpenShot to version 2.4.1. Then watch [this video](https://www.youtube.com/watch?v=BQS2tmgD_Rk). It's actually made by Jonathan Thomas himself. 

That should help you. I think the issue has been solved in 2.4.1. It's now called 'split clip' instead of 'divide clip' too.

Also, if your issue has been resolved, please do close the issue. Thanks!

**Comment by DylanC** [comment]
@iniasoto - 

Use split clip and set the values like this:

Start 00:00:15
End 00:00:30

That should be it. Thanks.
