### ISSUE TITLE
Openshot video preview might be too HD for good performance.

### ISSUE THREAD

**Issue by Amnikarr** [OpenShot/openshot-qt#960]
System Details: FX-8370 4.3ghz, AMD R9 380 4 gb, 8gb Ram
Operating System / Distro: Windows 10
OpenShot Version: Latest from the side

Hey guys !!! Can you make the video previewer screen show the video in a lower quality. It's kind of hard to edit something while it's HD . The filmora and movavi programs are using this method and are running a lot faster**
If there is a feature where one can change this to lower and I am to derp to see it can you guys make it more obvious?

Thank you,
Johnny

**Comment by DylanC** [comment]
@Amnikarr  - There is no feature to do this at the moment but it sounds like a good idea.

**Comment by 03F8** [comment]
I just had a major revelation about this. I had been trying to use OpenShot under Windows 10 and it was a performance nightmare. My system is a dual core i5 with 16 gigs\ram. No commercial software was giving me a problem. I read about other people having performance issues in Win 10 so I set up a proper Linux install on the same computer expecting that to solve the problem. Same unusable level performance problem. Then it all came together. I was shooting at 3840x2160 which is beyond what my CPU can handle while editing video. The preview window is trying to render at that resolution or at least at something similarly stupid high while other solutions dither the preview. I set my S8+ to record at 1920x1080 and all of my performance problems in Windows 10 and Linux are 100% solved. I am very happy. A lot of people are struggling with OpenShot, especially in Windows 10. This information needs to get out there until there is a fix for the preview Window. I do realize the problems this still presents for some people wanting to encode higher than they can work with. The next move for OpenShot needs to be fixing this.

**Comment by N3WWN** [comment]
I was having preview performance issues, also, and resolved them by doing the following:

Edit -> Preferences -> Cache
Set Cache Mode to "Disk".
Set Cache Limit to something sane... I use 250MB.
Set Image Format to "PPM" (Other settings may work or may be needed to work, but PPM works fine for me).
Set Scale Factor to "0.30".
Set Image Quality to "30".

I still use 1920x1080 @ 60fps and 1280x720 @ 100fps source video, but these settings reduce the resolution and quality of the Video Preview to very low.  I generally don't need to see exactly what is going on with a great amount of detail, just enough to align my clips frame-by-frame.

To fine tune the preview, increase or decrease the size of the Video Preview frame.

**Comment by 03F8** [comment]
N3WWN - Yup, that did it, I can work with higher resolutions now. There needs to be a more nuanced method regarding these settings. Even better would be sane defaults. I'm glad though. OpenShot has a ton of great features. The only comparable commercial alternatives are super expensive.

**Comment by 03F8** [comment]
Something else I noticed. If I keep caching on memory but up to 2048, I can work with 1080p with minor stuttering I can tolerate while using all the layers, effects, and transitions I want without the dreaded 30 seconds of "not responding" every few seconds. It's better than switching to disk cache for me at that res. Fortunately for me, I only need 1080p. But as the video preview progresses, memory uses climbs exponentially until it goes back to being unusable. Fortunately I can spare 10 gigs of ram for OpenShot cache. This is still under Windows 10. I am going try this under Linux too see if the same thing happens.

**Comment by DylanC** [comment]
@03F8 @N3WWN - Some great findings here guys! Definitely we need an easier way to control the preview quality. Not all users would go to this trouble to reduce the quality.

**Comment by 03F8** [comment]
Since I have your ear, I have to say my peace as this most current release of OpenShot is very exciting. I have been following the project since it started, but have always had reasons to be disappointed with each release to the point of not using it seriously. The 2.4.0 release really truly is something special. In fact amazing. I am back in a situation where I am going to be professionally editing video again (been years!) and after trying all the commercial contenders, I keep coming back to OpenShot as being feature perfect. Performance faults aside. Best of all, it does not crash anymore, even when it becomes unusable slow. This would be a great time for a year or two feature freeze to tighten things up a bit and refine the functionality of existing features based on feedback - something I am sure you get plenty of. 2.4.1, 2.4.2, 2.4.3, etc. Also, there is something I might have the time to help with in the near future. You need to recruit a dedicated group of people to create a laundry list of instructional videos canonical (the word, not the company) to the OpenShot project and this specific release. Sure, there are plenty of OpenShot tutorial videos out there, but they are scattered across 10 years of releases. I know **"you need to do this and that"** comments are often (and justifiably) reviled by Open Source programmers on large projects, but on this occasion I just could not help myself.

**Comment by N3WWN** [comment]
How about adding a button that will scale the quality and resolution (and Video Preview size?) based on the contents of the current project on the current hardware/OS?  

The button could automagically find the most complex segment of the project (most layers, layers with varying resolutions and/or frame rates, etc) and render a portion of it internally with various settings until the preview can be generated without delay.

If undoable, the user could test out the settings and revert them, if desired.  

Or, if the button is a toggle between the settings in the preferences and the auto-calculated values, the user could turn on no-latency preview when they want to examine the flow of the output and could turn off the no-latency preview when they want better quality.

Just my $0.02... but I'd also be interested in learning how to write plugins for OpenShot.  The plugin I'm interested in writing would add a running timer to the output that can be reset at any points along the timeline and also be able to add markers of various types in the output.  This could all be done with an additional timeline element, much like a title, if the markers could also be tied to the audio of any (or all) of the tracks.

**Comment by 03F8** [comment]
That is quite a tall order. Maybe something more along the lines of right click with a few simple option like 720p low color. Or even simpler "preview quality > high, medium, low. Where the definitions of high, medium, and low can be configured from defaults in settings. Any such solution should involve a default preview at 720p, IMHO. Right now, I just wish I had the same cache options for memory that disk has.

**Comment by 03F8** [comment]
While the preview functionality is a really big problem, and at least a band aid would be nice, I would really like for the people (person?) behind it to take a year or two and seriously refine the code base. After that we can all start begging for things like direct gimp\audacity integration and more advanced effects.

**Comment by DylanC** [comment]
@03F8 - Thanks for you kind words. I think OpenShot is a great project. I used it for all my videos to promote my own project and I'm glad it existed at the time. I decided to give back to the project with my time and support the devs by taking away some of the pressure with the support tickets.

@03F8 @N3WWN 
In relation to this, I was just thinking of something like a Low, Medium, and High setting but also the option to configure more advanced (detailed) settings if you wish.

**Comment by N3WWN** [comment]
@03F8 ,
> All in all, telling the preview window to display at a lower resolution than what the clips are as a matter of saving resources is probably a lot harder to do without turning right around and consuming even more resources to pull it off.

That was my reasoning behind having a no-latency combination of settings be calculated when the button is clicked, versus an ongoing, dynamic recalculation.  

@03F8 @DylanC 
I do like the idea of Low, Medium and High settings, which could also be incorporated into what I was thinking... the Low would be no-latency with medium and high increasing in quality as well as latency.  

What if the user has an old dual-core 2GHz machine with 4GB RAM?  What if they have a new 4x CPU (each with 8 cores) 3GHz machine with 64GB RAM?  What are sane values for Low, Medium and High?  

If OpenShot can calculate these settings, then they would be set appropriately for any hardware that may be running OpenShot.  

While I'm not necessarily a fan of this, there could be an external utility that could extract some data from an OSP file for use in some offline tests which could then be used to estimate sane values.

**Comment by 03F8** [comment]
@DylanC One last thing. If you have a Windows machine, download the Filmora demo. This is a good example of a low res preview window. This is also probably why it glides along so smoothon my paltry i5. As a better reference, throw together some large high resolution images of text and make a video out of that to really get an idea.

**Comment by fabrixx** [comment]
Preview is totaly unusable. Linux, Core i7 6700 16 Gb ram, Tryed several disk cache settings, also minimal settings after 15 secs of video recordered at 60fps, preview disappear or work for only 15 secs of video. Also tried to use profile at 30 fps.

**Comment by DylanC** [comment]
@03F8 - I may be able to try in a VM or I do have a Windows netbook if that would be capable of running it. I think the plan is to work on becoming more stable with OpenShot first and then time will be directed towards performance tweaks.

To be honest I have been working on my own project for years and I can see especially as I get a bit older how hard it is to find time for it.

**Comment by 03F8** [comment]
@fabrixx I have not had that drastic of an experience under Linux. Since lasting posting, I am running OpenShot under Ubuntu 17.10 on an old 6-core AMD CPU\Nvida Pci-E card system with 16 gigs of ram a slapped together from boxed up hardware. While performance is not perfect, is is substantially better on the "faster" i5 16 gig system I was using OpenShot with under Windows. I have been using Linux since 1996. Facts are facts, it's still not install it and go perfect. Especially true if you are not very comfortably with a BASH or similar shell as I suspect everyone here is. It may be valuable to know what video chipset\driver combo you are using.

**Comment by 03F8** [comment]
@DylanC A netbook should be fine. It is really smooth software. I still lean towards that being due to default low resolution preview window. After taking another look, it is far below 720p. Granted, I have not tested out much of anything else in the way of commercial Windows software for serious technical comparison. It sounds like, especially netbook bound, you are in a position to make substantial findings along this line of thinking. In regards to a follow up comment you made some time ago, as far as i am concerned, OpenShot has achieved stability. Performance should be the target.

**Comment by fabrixx** [comment]
**@03F8** 2318/5000
I use linux since 2003 and started using openshot 1.4 only a few years ago. Openshot 1.4 has never given me editing / rendering problems except in some crashes that forced me to save often, even on my old Core2. When I started testing version 2 I immediately had stability issues with casual locks and hard rescues but it was normal we started at the beginning. For a while I was forced to downgrade to 1.4, but then Arch Linux did not cause any problems with some older libraries. I started using stable version 2, the rescue problems I knew were far short of so far as they were almost absent. Working at 30fps / 720 I encountered particular problems that came when I started working at 1080 / 60fps. I solved a problem on the 60fps signaling it in this issue # 854 and was excited, finally I could use Openshot2! I always had problems with previews at 60fps, but I could edit it first by 30, but yesterday I do not run previews any cache / fps setting. After the first 20 seconds the system does not respond, although the preview is extremely sharp and minimal. After editing blind, however, I started the rendering that never gave me problems and once it slowed to 50% it nearly blocked up to 100%. Videos generated in addition to having chopped audio were silenced after 1 minute of 4 of the duration. I removed every transition working on a new profile at 60 fps but same problem. The only difference is that I had 320 audio instead of 128. Tried to export it to 320 192 and 128 with various codecs. For the video I kept what worked for me last week (1080 60fps 16m Mb / s). I have a Core i7 6700 Nvidia 1060GT 16Gb Ram. At the moment I am forced to use kdenlive but unfortunately I have all my titles in the format managed by openshot also rendering them for kdenlive the result is bad. Kdenlive perfectly manages the previews to the maximum resolution on my system and is very fluid in scanning. I want to use openshot, and if there is any particular command / trick let me explain it. Maybe I have to build id from sources by passing some particular parameters? I am willing to do so if necessary ...

**Comment by 03F8** [comment]
Hmmm... I am glad you brought up 1.4 and your experience with it. Between both of those version, our problems are similar yet diverge enough to be intriguing. By what method did you install Openshot 2.4? In my case I downloaded the .appimage from the site, set it executable and was off and running. I just took a look at the App Store and noticed that it offers 1.4.3-1.2 - so I have just installed it and have both running side by side. When I have some time later, I am going to work with both and watch the console output where actions succeed and fail. At this point, that may be the best thing to do.

I can't think of any command line parameters, but have also not tried compiling it from source. My "since 1996 \ BASH" comment was actually just badly offtopic Linux commentary that covertly made its way into my keyboard and the post : p Although for the record I prefer things that way. Suddenly longing for Slackware... anyway, offtopic.

**Comment by fabrixx** [comment]
No problems, I love openshot my desire is to always work with it, I do not know how to do but the 60 fps screencasts it exports are more fluid than with kdenlive.
I install it from aur, (pacman -S [openshot](https://www.archlinux.org/packages/community/any/openshot/)) but sometimes i tried the .appimage. I would like to find an oprnshot 1.4 appimage, always perfect in previews.  Downgrade not work anymore cause multiple broken dependences..

**Comment by N3WWN** [comment]
With 2.4.1, I am now able to use a cache scale factor of 1.00 and image quality of about 75 without preview latency causing stuttering.  

With 2.4.0, I had to scale back to 0.30 and reduce quality to about 30 in order to get similarly low-latency preview rendering.

**Comment by DylanC** [comment]
@N3WWN - Thanks for the info. Seems to be getting better with the new release.

**Comment by fabrixx** [comment]
Same problems on my Laptop Dell 7548 (UHD) Radeon R7 M265 Core i7 5500 with Arch Linux. Test various cache settings but i have a total block after 10 seconds of preview (720 30 fps).

With this machine & Desktop Openshot 2 worked well before latest upgrades.

**Comment by N3WWN** [comment]
@fabrixx Just a thought, but did you make sure your cache mode is set to 'disk' when trying the different cache settings?

**Comment by fabrixx** [comment]
Yes, setted to disk, tried several quality settings, and format. Last two format work but i see only black/white pixels.

**Comment by DylanC** [comment]
Dup of #132

**Comment by fabrixx** [comment]
UPDATE: On Arch Linux i switched to [Kernel mode setting](https://wiki.archlinux.org/index.php/kernel_mode_setting) uninstalling x**f86-video-intel** ad finally i can use  preview at high resolutions (only some lags sometimes).

Memory cache 1000 MB/PPM/0,40 Scale factor

**Comment by DylanC** [comment]
@fabrixx - Thats a good find. Thanks!

**Comment by udippel** [comment]
Okay, my machine is not meant for editing, really, but plays other clips well enough (Linux, Dual Core Broadwell). However, any display of Preview is stuttering, it seems irrespective of other load on the PC. 

Therefore, I appreciate the original idea. For my basic editing, I rather have a small, low-res Preview with sound being played continuously than an one-off_one-on_one-off stuttering thing. I use one track only, so why can't it play that track when VLC does without any problem?
