### ISSUE TITLE
Copying project to other PC?

### ISSUE THREAD

**Issue by Ruvision** [OpenShot/openshot-qt#988]
**System Details:**
* Operating System / Distro: ?
* OpenShot Version: ?
* _Please attach log files if crash_

**Issue Description and steps to reproduce:**
How do you copy a complete project with assets to an other PC? Just using Explorer is not enough. Project does not open on second PC

**Comment by DylanC** [comment]
@Ruvision - I have never tried it but I think you would need to structure it like this:

TopFolder (zip up this one and move to other PC)
->Source files for the video (images/music)
->project file (.osp)

Let us know if you try my above idea and if it works. Thanks.

**Comment by Ruvision** [comment]
Hi DylanC. This is exactly the way I tried to do. Moreover I have on the source PC everything (.osp, video,images and musicfiles) in the same  folder and copy the folder as such.  I fear that I have to copy some Registry lines too , but which? P{erhaps also some hidden files?
Anyhow I tried again, same negative result.

**Comment by DylanC** [comment]
@Ruvision - I will try to figure this out for you.

**Comment by peanutbutterandcrackers** [comment]
Perhaps OpenShot uses absolute path names instead of relative ones? And maybe that's why? @DylanC

**Comment by DylanC** [comment]
@peanutbutterandcrackers - Yes, I think that is the problem. Openshot needs to have a more portable file format in the future.

**Comment by DylanC** [comment]
#1105 - Set this as a bug. We need to resolve this I think. Unless there is any good reason for absolute paths.

**Comment by emanueleg** [comment]
I edited the osp file, changing paths of media file from absolute to relative: it works and the project can be moved to a different location without issues.

Please note that to make the project portable to a different computer, thumbnails should point to the local thumbnail directory (inside the project dir) and not the .openshot_qt\thumbnail directory inside the user home.

(Tested in Windows 10 and Linux with Openshot 2.4.1)

**Comment by jonoomph** [comment]
Currently, OpenShot 2.x uses relative file paths when saving an .OSP file. When the .OSP file is opened by OpenShot, it reconstructs the absolute paths (since they are required at runtime). If you can find a way to easily reproduce an OSP file with absolute paths, please let me know.. because that sounds like a bug. =)  Thanks!

**Comment by peanutbutterandcrackers** [comment]
@jonoomph - Mr. Thomas, on my machine, when I try to look at the .osp file, it shows that the .osp file is, indeed, using absolute paths. Here:
![screenshot from 2018-03-17 10 48 12](https://user-images.githubusercontent.com/26764547/37551841-d1fc5214-29d0-11e8-91bf-bdad356bd709.png)

**Comment by emanueleg** [comment]
@jonoomph to be more precise, an OSP file seems to contain both relative and absolute paths: relative paths are used for the project (files, clips etc), while the history (undo and redo) is saved using absolute paths. I suppose this happens because the convert_paths_to_relative() method does not loop through the elements of the history.
