### ISSUE TITLE
Portuguese locale

### ISSUE THREAD

**Issue by cirix81** [OpenShot/openshot-qt#99]
The portuguese (pt) locale used in openshot is not the one translated in launchpad. 
It seem the file it's the same of the greek one (el).

**Comment by timotheonb** [comment]
I, also, am running Openshot 2.0 on an Ubuntu Wiley (15.04). My system is Brazilian Portuguese, but it installs with greek as its default language. Is there some kind of workaround:

**Comment by jonoomph** [comment]
I think this is fixed now. I've update the translations from Launchpad, and just checked this screen in Portuguese and it no longer looks greek. =)

**Comment by keitalbame** [comment]
Thanks @jonoomph 

After downloading all files from pt locale folder, is no longer in Greek. It is all in English.

For me it is ok, I only use software in English but I would like to see an option in preferences to manually change the language.

I want to migrate my father from Movie Maker to Openshot but since his machine is in Portuguese, it will display correctly, but I would like to have the possibility to change my settings to Portuguese, if I need to give some assistance to him.

Issue #97 requesting this feature. Will this be implemented?
